### ISSUE TITLE
Unable to query existing sqlite3 db on upgrade from 1.6.1

### ISSUE THREAD

**Issue by limburgher** [gerbera/gerbera#1006]
Oct 14 10:47:41 bamboo gerbera[805427]: Query:SELECT "object_type" FROM "mt_cds_object" WHERE "id"=0SELECT "f"."id","f"."ref_id","f"."parent_id","f"."object_type","f"."upnp_class","f"."dc_title","f">
Oct 14 10:47:41 bamboo gerbera[805427]: error: unrecognized token: "0SELECT" file:/home/gwyn/fedora/git/gerbera/gerbera-1.6.3/src/storage/sqlite3/sqlite3_storage.cc line:441 function:waitForTask

**Comment by KarlStraussberger** [comment]
Did you test 1.6.2 or 1.6.3?

**Comment by limburgher** [comment]
1.6.3
