### ISSUE TITLE
Share user folder for gerbera

### ISSUE THREAD

**Issue by RastaDill** [gerbera/gerbera#1008]
Hello. I encountered a problem accessing the user's home folder

OS: Fedora 32
Version 1.4.0

Installed gerberga from command:
`sudo dnf install gerbera`

Tryed run from localuser, but show errors about missing config file
Run gerbega with systemctl:
`sudo systemctl start gerbera`
It's works, but in web-UI from file manager i cannot access to my localuser folder:
`Exception raised in [src/filesystem.cc:111] readDirectory(): could not list directory /home/<localuser_home> : Access denied`

In system have user gerbera. In unit file set user and group gerbera.
Added user gerbera in my localuser group, but not sence.
Change permission on <localuser_home> folder to read another group
Only after i add some folder in home and set:
` sudo chmod -Rv gerbera:gerbera /home/<some_folder> `
I can access to folder.

How share some folder to gerbera or needed create separate directory for gerbera user?

**Comment by KarlStraussberger** [comment]
Before running gerbera as a service you need to create a config file and adjust that to your needs: [Run Gerbara](http://docs.gerbera.io/en/latest/run.html)

For file access gerbera relies on Linux permissions. Either you change the group of you user directory to the gerbera group or you add gerbera to you user group. Your `chmod` is another way to grant access. That's how Linux works.

**Comment by RastaDill** [comment]
Config files with others automatically created after i run gerbera with systemctl. It's all fine - me not needed change settings.
I understand groups, but i not understand why gerbera not reach to folder. Maybe i not corrected set permission? Below my pipeline:
my localuser: rastaukropchik
gerbera user: gerbera
Needed access to folder /home/rastaukropchick/Video

1. Added groups:
`sudo usermod -G gerbera rastaukropchick` - added  rastaukropchik to gerbera group
`sudo usermod -G rastaukropchick gerbera` - added gerbera to rastaukropchik group
2. Check:
`id -Gn rastaukropchik`: 
rastaukropchik gerbera
`id -Gn gerbera`:
gerbera rastaukropchik
4. Add permission for group gerbera:
`chgrp gerbera /home/rastaukropchik/`
`chmod g+wx /home/rastaukropchik/`
`chgrp -R gerbera /home/rastaukropchik/Video/`
`chmod -R g+wx /home/rastaukropchik/Video/`

Now I assume that the user gerbera will be able to access the data in the directory /home/rastaukropchik/Video.
Check Unit file:
```
[Unit]
Description=Gerbera Media Server
After=network.target

[Service]
Type=simple
User=gerbera
Group=gerbera
ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
Just in case we do this:
`sudo systemctl daemon-reload`
Run gerbera server:
`sudo systemctl start gerbera`

Can open folder /home/rastaukropchik/ from web-UI and haver error:
Exception raised in [src/filesystem.cc:111] readDirectory(): could not list directory /home/rastaukropchik : Access denied

I tryed added folder fom flag --add-file, but don't help.
Where may be mistake?

But, i create folder ger in /home/ger. Set owner gerbera and group gerbera:
`drwxrwx---.  2 gerbera        gerbera  4096 окт 16 11:46 ger`
From my user (rastaukropchik) i can copy and create file in this directory. Why doesn't this work for the gerbera user?

**Comment by KarlStraussberger** [comment]
You added write access (w) instead of read (r) access.
Try with this:
`chgrp gerbera /home/rastaukropchik/
chmod g+rx /home/rastaukropchik/
chgrp -R gerbera /home/rastaukropchik/Video/
chmod -R g+rx /home/rastaukropchik/Video/`

**Comment by RastaDill** [comment]
I change, but don't help.
`ls -all /home/`
drwxrwxr-x+ 32 rastaukropchik gerbera  4096 окт 16 16:17 rastaukropchik
`ls -all /home/rastaukropchik/Video/`
drwxrwxr-x.  6 rastaukropchik gerbera       4096 окт 14 16:37  .

This may be affected by SELinux?

**Comment by KarlStraussberger** [comment]
Try running gerbera from console with the command in unit file and add option -D for detailled debug messages.

If that works add -D to your unit file and try again.

**Comment by RastaDill** [comment]
This my log file. On 8:18:02 (end file) i received same error.
<details>
  <summary>Log File</summary>
[gerbera.log](https://github.com/gerbera/gerbera/files/5399305/gerbera.log)
</details>

If i run gerbera from local user - i can open my home folder.
In unit file i change User to local user, after that i can open my home folder.
Can I log in as a user gerbera? I tryed:
` su - gerbera ` but don't have password.
There may be something wrong with the user? I didn't create it myself. It appeared after I installed the package

**Comment by KarlStraussberger** [comment]
That's quite normal. If you type
```
> id gerbera
uid=457(gerbera) gid=100(users) groups=456(gerbera),100(users)
```
You can try changing `/etc/passwd`:
```
gerbera:x:457:100::/usr/local/lib/gerbera::/sbin/nologin
```
(replace nologin with you favorite shell) to log in and get more debugging details.

**Comment by whyman** [comment]
Shall we close this off as it looks like a standard linux permission problem, and not a Gerbera bug?

**Comment by RastaDill** [comment]
My out command `id gerbera`:
uid=976(gerbera) gid=970(gerbera) группы=970(gerbera),1000(rastaukropchik)
May be change gid to 1000, sutuation will be changed.

I agree with @whyman. It all depends on the distribution and user configuration
