### ISSUE TITLE
Web configurator for import filter

### ISSUE THREAD

**Issue by EricdeWaal** [gerbera/gerbera#1012]
Excited to see my previous idea #982 has been implemented! Can hardly wait for the next tag to see it in operation.
Time for a new idea: leverage one of the great strenghts of Gerbera, it's unique import filter. 
If you have music from over 325 artists (like me), a simple artist/album/song scheme will not be very handy if you control your Pioneer N30 network player by the Hi-Fi Cast app (or similar) on a mobile, let alone the tiny screen on the player itself.
I set mine up to do initial_letter/artist/album/song. Excellent but not so easy to do for a novice.

So the idea is to make the import script configuarable through the web interface, with blocks like artist, album, song, year, etc that can be selected or not, reordered and so on to build the import script.
IMHO that would be enough to make Gerbera a lot less nerdy, much more mainstream!

**Comment by KarlStraussberger** [comment]
The idea is really great, but there is no way to import configuration into javascript. There is already am import script that does exactly what you want. I, myself, implemented it already for mediatomb.

**Comment by EricdeWaal** [comment]
I know there is an abc option and I'm using it myself already from the mediatomb days. And agree it may not be easy to edit the javascript import files from javascript in a browser!
Would it be an option to have some pre-configured options (like abc on or off) that the user can select from the web ui after installation?
