### ISSUE TITLE
A 'linking CXX executable' issue

### ISSUE THREAD

**Issue by ValeraBahleiUA** [gerbera/gerbera#1029]
My attempts to compile [Gerbera] proved futile. The dependencies seem to be alright. The documentation doesn't mention any make flags needed. So when I try to make, building reaches 100% and then fails on <pre>[100%] <font color="#4CE64C"><b>Linking CXX executable gerbera</b></font>
</pre> with the following message: <pre>/usr/bin/ld: liblibgerbera.a(sqlite_database.cc.o): undefined reference to symbol &apos;sqlite3_mprintf&apos;
/usr/bin/ld: /lib/x86_64-linux-gnu/libsqlite3.so.0: error adding symbols: DSO missing from command line
clang: <font color="#FF8787"><b>error: </b></font>linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [CMakeFiles/gerbera.dir/build.make:98: gerbera] Error 1
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/gerbera.dir/all] Error 2
make: *** [Makefile:130: all] Error 2</pre>
I am unfamiliar with this kind of issue, so would be grateful if someone explained it to me or, if possible, helped me to fix it

**Comment by whyman** [comment]
Looks like we are missing some sqlite flags on your system for some reason....

What is your:

Distro
Compiler
SQLite version

If you could paste your full build logs too, that would be helpful.

**Comment by ValeraBahleiUA** [comment]
xubuntu 20.04
gcc version 8.4.0
clang version 9.0.1-12 
SQLite version 3.31.1

Sorry, I am not sure if these are the right logs that you need
[CMakeError.log](https://github.com/gerbera/gerbera/files/5469802/CMakeError.log)
[CMakeOutput.log](https://github.com/gerbera/gerbera/files/5469804/CMakeOutput.log)
[terminaloutput.txt](https://github.com/gerbera/gerbera/files/5469818/terminaloutput.txt)

**Comment by whyman** [comment]
Do you have libsqlite3-dev installed? Our CI even runs Ubuntu 20.04....

**Comment by whyman** [comment]
Any news?

**Comment by ValeraBahleiUA** [comment]
A guy on an external forum with similar issues helped me to solve this problem.
What I did is installed this packages
<pre>libnss-systemd libpam-systemd libsystemd-dev libsystemd0 libsystemd0:i386
  systemd systemd-sysv systemd-timesyncd
</pre>
Then I reinstalled libupnp using a script within gerbera forlder, not from the Sourceforge archive.
Then I redid all the building from scratch and it worked

However, I can not find the gerbera.service file on /etc/systemd/system/
Is it critical if I want to run as a daemon? What do I do in this case?
Thank you so much for your time

**Comment by whyman** [comment]
Thats great news, glad you got it sorted.

Did you build with systemd support? `-DWITH_SYSTEMD=1`, that should install a unit file when you do `make install`

**Comment by ValeraBahleiUA** [comment]
I am 100% sure I did

**Comment by ValeraBahleiUA** [comment]
![Screenshot_2020-11-10_15-05-47](https://user-images.githubusercontent.com/48102830/98678048-a235c000-2366-11eb-9814-c17497102f05.png)
I actually did find that service file in the build folder. Should I just copy it to systemd/system ?

**Comment by whyman** [comment]
Sure, that is what `make install` would do.

https://github.com/gerbera/gerbera/blob/6217a28f3bb1bb11282186c9b059cb7d82ad8fa0/CMakeLists.txt#L524-L526
