### ISSUE TITLE
error  start in terminal

### ISSUE THREAD

**Issue by stoilovnikolai** [gerbera/gerbera#1035]
After start in terminal---
gerbera: symbol lookup error: /usr/lib64/libspdlog.so.1: undefined symbol: _ZN3fmt2v76detail10vformat_toIcEENS0_20basic_format_contextISt20back_insert_iteratorINS1_6bufferIT_EEES6_E8iteratorERS7_NS0_17basic_string_viewIS6_EENS0_17basic_format_argsINS3_IS4_INS5_INS0_13type_identityIS6_E4typeEEEESH_EEEE

**Comment by KarlStraussberger** [comment]
It seem the installed spdlog library and fmt library don't match. So either compile spdlog with install-spdlog from scripts directory or double check your installation

**Comment by stefan-langenmaier** [comment]
I just wanted to add that your comment helped me. I recompiled spdlog (1.7.0), libfmt (7.0.3) and Gerbera and now it's working again. Thanks!
