### ISSUE TITLE
Trim contents of PC Directory

### ISSUE THREAD

**Issue by lineinthesand** [gerbera/gerbera#1036]
Is there a way that I only have the folder structure starting from the folder I imported under PC-directory? Right now, I have the whole path, e.g. I imported
`/home/user/Music/flac`
and I get 
`PC Directory/home/user/Music/flac/Artist/Album/Track`
but I'd like to only have
`PC Directory/flac/Artist/Album/Track`
 or 
`PC-directory/Artist/Album/Track`
The latter, I understand, should be possible with
`<layout parent-path="no" />`
right?

**Comment by whyman** [comment]
Parent path no should do it, if I remember correctly. paths are built at import time, so you will need to remove and readd your files and restart your server after the config change.

**Comment by lineinthesand** [comment]
Actually I tried that; I deleted gerbera.db after adding `<layout parent-path="no" />` as a subnode of the `<import>` tag. Is that the correct location of the tag? Because then re-imported the `/home/user/Music/flac` folder via the web UI (changed to the flac dir and clicked Add item). But the result was the same: I got the whole path starting from the root folder under the PC Directory folder.

**Comment by KarlStraussberger** [comment]
Pc directory is not affected by layout settings.

Layout settings is used by virtual layout - either script or build-in.

**Comment by lineinthesand** [comment]
So is it possible to modify the content of PC Directory to only include paths I actually added without their parent paths starting from the root folder?

**Comment by KarlStraussberger** [comment]
That's the idea of this node: reflect the exact path of the imported files without any modification. Any other layout can be achieved by scripts. So in your place i would generate my own structure an hide pc directory

**Comment by lineinthesand** [comment]
Ah, now I understand! But how can I access the actual dirs the actual audio file objects reside in in the import.js file? I only see obj.title there.

**Comment by whyman** [comment]
Its `orig.location`

Also, see [scripting on the docs](http://docs.gerbera.io/en/latest/scripting.html)

**Comment by lineinthesand** [comment]
OK, I achieved it now adding 

```
var loc_stripped_str = orig.location.replace('/home/user/Music/', '')
var loc_stripped = loc_stripped_str.split('/')
chain = ['dirs'].concat(loc_stripped.slice(0,-1));
addCdsObject(obj, createContainerChain(chain));
```
somewhere near the bottom of `function addAudio` in `import.js`

**Comment by whyman** [comment]
Great!
