### ISSUE TITLE
Gerbera Flatpak package

### ISSUE THREAD

**Issue by TheHellSite** [gerbera/gerbera#1040]
Hello,

I have built my own NAS using Debian 10 for stability reasons.
Sadly the version of gerbera available in the official apt repo is still "1.1.0+dfsg-3+b1".

So my question is: Would it be possible to provide gerbera as a flatpak package?

**Comment by whyman** [comment]
You have few options:
1. Install the package from our friends deb-multimedia [Link](https://www.deb-multimedia.org/dists/stable-backports/main/binary-amd64/package/gerbera)
2. Use the docker build `gerbera/gerbera`
3. Creat a PR for a flatpak build :+1:

**Comment by TheHellSite** [comment]
I finally decided to switch my whole NAS system to archlinux.
