### ISSUE TITLE
IPv6 log issue

### ISSUE THREAD

**Issue by garyemiller** [gerbera/gerbera#1042]
When I start gerbera with "-i 2001:470:e815::8", gerbera.log says: 

 info: The Web UI can be reached by following this link: http://2001:470:e815::8:49152/

Which is an invalid URL.  It should be:

http://[2001:470:e815::8]:49152/

**Comment by garyemiller** [comment]
Thanks!

**Comment by whyman** [comment]
Thanks for reporting!
