### ISSUE TITLE
Is it possible to update the content of the folder imediately?

### ISSUE THREAD

**Issue by iDeception** [gerbera/gerbera#1048]
I used Media Sharing’ option in the settings of Ubuntu before and the content of the folder was updated immediately after  closing/opening folder in SmartShare app on my TV. Is it possible to do the same in Gerbera? When I copy the movie in the folder it doesn't appear in SmartShare folder on TV until I run sudo systemctl restart gerbera. And vice versa, deleted from folder file is still shown in SmartShare folder. Should it work this way or am I doing something wrong?

**Comment by KarlStraussberger** [comment]
It depends on the scan mode setting of your directory. Inotify should do exactly what you want. Timed should rescan after an interval.

Which version of gerbera do you run - we used to have some issues!

**Comment by iDeception** [comment]
Version 1.6.0. I tried Inotify all the same. I also don't understand why is there a folder database > Video > Directories > . being created? I have in database > Video > All Video 3 files but in database > Video > Directories > . only 2 files

**Comment by KarlStraussberger** [comment]
Can you run gerbera with -D for debug infos and share the output.

**Comment by iDeception** [comment]
2020-11-22 10:59:36   info: [main.cc:77] logCopyright(): Gerbera UPnP Server version 1.6.0 - http://gerbera.io/
2020-11-22 10:59:36   info: [main.cc:78] logCopyright(): ===============================================================================
2020-11-22 10:59:36   info: [main.cc:79] logCopyright(): Gerbera is free software, covered by the GNU General Public License version 2
2020-11-22 10:59:36   info: [main.cc:80] logCopyright(): Copyright 2016-2020 Gerbera Contributors.
2020-11-22 10:59:36   info: [main.cc:81] logCopyright(): Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2020-11-22 10:59:36   info: [main.cc:82] logCopyright(): ===============================================================================
2020-11-22 10:59:36  debug: [main.cc:256] main(): Home detected as: /home/XXXXXX/XXXXX
2020-11-22 10:59:36  error: [main.cc:316] main(): 
The server configuration file could not be found: "/home/XXXXXX/XXXXXX/.config/gerbera/config.xml"
Gerbera could not find a default configuration file.
Try specifying an alternative configuration file on the command line.
For a list of options run: gerbera -h

**Comment by KarlStraussberger** [comment]
This looks like you did not set up gerbera. You can add the location of the config file with -c

**Comment by iDeception** [comment]
Well, I read the documentation and there is a note: "Whilst you can run Gerbera as a “regular” application. It is strongly recommended to run it as a system service instead" so I decided to do that. 
In Gerbera Permissions section: The gerbera user must have access to config.xml file and to the directory referenced as the gerbera home. For example /etc/gerbera. I have config.xml in this folder already, why do I need another one in ~/.config/gerbera?

**Comment by KarlStraussberger** [comment]
The service configuration normally reads `gerbera -c /etc/gerbera/config.xml`. That's where things come together.

**Comment by iDeception** [comment]
So I need 2 config files anyway. right?

**Comment by KarlStraussberger** [comment]
You need just `/etc/gerbera/config.xml`. It all depends on the `-c` argument.

**Comment by iDeception** [comment]
I had config.xml in /etc/gerbera/ from the start

**Comment by KarlStraussberger** [comment]
You need to point gerbera to that file with -c. Normally, the service file does this. If you run gerbera from the command line you need to supply all arguments from the service file. 

If you don't supply `-c` gerbera looks in the user's home directory - like you found out. So, in order to get all sorted out, check your `gerbera.service`, copy the full line to command prompt, add `-D` and share the log file. You may also edit the service file, run `systemctl daemon-reload` and start the service.

**Comment by iDeception** [comment]
Sorry, I don't understand what I have to do) What does it mean check your gerbera.service? Where and how do I check it? I guess it's much easier to use Ubuntu's built-in upnp server

**Comment by KarlStraussberger** [comment]
Even for running other services, you should become familiar with your system's basics. There is no _builtin_ in linux systems. Services might be installed and run by default - they still use the same bottom layer. Before giving up on that issue, I recommend to work through my comments and get gerbera running.

**Comment by iDeception** [comment]
I'd love to but I just don't understand what to do. I did everything according to the documentation... I don't what to dig to the bottom layer) Anyway thanks for the help!
