### ISSUE TITLE
Docs --add-file /path/to/file 

### ISSUE THREAD

**Issue by OblackatO** [gerbera/gerbera#1049]
When using gerbera version 1.1.0, I only have the option --add and not --add-file like stated in the [docs](https://docs.gerbera.io/en/latest/run.html?highlight=Content#add-content), maybe this could be corrected?

**Comment by KarlStraussberger** [comment]
1.1.0 is three years ago. The online docs contains the latest pre1.7.0.

Obviously it was changed inbetween!
