### ISSUE TITLE
Last supported fmt version (of 1.6.4)

### ISSUE THREAD

**Issue by SCOTT-HAMILTON** [gerbera/gerbera#1054]
I've been doing some debugging to fix gerbera's build on [nixpkgs](https://github.com/NixOS/nixpkgs) see https://github.com/NixOS/nixpkgs/pull/106387.

The last supported version is fmt 7.0.1, after that, [this commit](https://github.com/fmtlib/fmt/commit/a2c4fed9819340b8ab3604d36e2579ced7c586ee) introduced the failure.

**Comment by whyman** [comment]
Interesting! Is it worth mentioning to upstream?

**Comment by SCOTT-HAMILTON** [comment]
Is gerbera of fork ?

**Comment by whyman** [comment]
Hey, sorry I wasnt clear. What I meant was it looks like its an issue with the `spdlog` library we are using, rather than Gerbera code directly (though we do also call fmt directly).

**Comment by whyman** [comment]
Looks like this got fixed... https://github.com/NixOS/nixpkgs/pull/106480/files
