### ISSUE TITLE
Confusion about Gerbera versions

### ISSUE THREAD

**Issue by NormHenderson** [gerbera/gerbera#1059]
Hi, I just installed Gerbera 1.6.0. on Ubuntu 20.04 LTS from the ppa: http://ppa.launchpad.net/stephenczetty/gerbera-updates/ubuntu focal main
This is the approach "strongly advised" on docs.gerbera.io.

The documentation that comes up however is for 1.7.0 and talks about some aspects of the Gerbera Web UI that I am not seeing, notably there is no Config tab in 1.6.0. Only after a lot of head scratching I noticed that v: stable gives documentation for 1.6.0, whereas the default documentation is for v: latest i.e. 1.7.0.

It would be better for the documentation redirect (on the Web site, and on the UI Documentation tab) to point at the stable version. Certainly the UI Documentation tab should point to documentation for the actual installed version.

Gerbera itself, was easy to install and is doing a great job of feeding a Sony srs-x77 speaker via Sony Music Center, good work!

**Comment by whyman** [comment]
This is a good idea, and must be something readthedocs support.

**Comment by whyman** [comment]
Fixed, it now defaults to "stable" which is the latest tagged release, check it out https://docs.gerbera.io
