### ISSUE TITLE
Video formats

### ISSUE THREAD

**Issue by NormHenderson** [gerbera/gerbera#1060]
Hi, Being new to this - I just installed Gerbera 1.6.0 on Ubunto 20.04 LTS and music streaming works well. In terms of video,

I have a several different formats on the server: mp4, mpg, avi, vob, wmv, and a few DVD ISO's. Should I be able to play all of these? On my (Sony) IP-capable TV, I'm only seeing a limited selection.

Or is this a dumb question which has nothing to do with Gerbera and depends entirely on the TV? If so is there some kind of solution?

**Comment by whyman** [comment]
This is usually a client issue, it may only be showing you files it supports.

You can check the Gerbera web UI to see what files have been imported successfully, or check the logs.

You can enable players to view more content by using transcoding to a format they support, see the [docs for how set it up](https://docs.gerbera.io/en/stable/transcoding.html).

**Comment by NormHenderson** [comment]
Thank you very much Ian. Actually I think the TV may have needed to index the content from Gerbera or something like that. After leaving this for a few days, today I can view all of the video file types, except .MTS of which I only have a few, and .iso files which I didn't expect to be able to view anyway. Gerbera is a great project, I'm so glad I found it!

**Comment by whyman** [comment]
Great to hear!
