### ISSUE TITLE
FanArtHandler::fillMetadata should also update upnp:albumArtURI for the files its called on when fanart is present

### ISSUE THREAD

**Issue by philbertasusa** [gerbera/gerbera#1061]
Cause if a file that lacks embedded artwork won't show artwork when playing even tho its album container does. Unless there is a way to add this via the import.js that I am not aware of. it seem incomplete that the function is called on all files imported. but only adds the resource for the album container.

**Comment by whyman** [comment]
Does your config include the fanart setup? https://docs.gerbera.io/en/stable/config-import.html?highlight=fanart#resources

**Comment by philbertasusa** [comment]
It did not. thank you!
