### ISSUE TITLE
Error on startup of fresh install. (undefined symbol: UpnpFileInfo_set_ExtraHeaders)

### ISSUE THREAD

**Issue by ordigno** [gerbera/gerbera#1064]
Running on a clean install of CentOS 8, installed gerbera via the package manager. I've been using this setup without any issues for about a year, had to reinstall the OS for unrelated problems and now gerbera won't start
This is what I'm getting:

`root@localhost:~$ gerbera`
`gerbera: symbol lookup error: gerbera: undefined symbol: UpnpFileInfo_set_ExtraHeaders`

I found the same issue here #539, however the OP's solution of reinstalling libupnp didn't work for me
I looked for conflicting versions of libupnp but couldn't find any, just the one shown in here

`root@localhost:~$ ldd /usr/bin/gerbera

	linux-vdso.so.1 (0x00007ffc10eab000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb905930000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fb905728000)
	libupnp.so.13 => /lib64/libupnp.so.13 (0x00007fb9054f0000)
	libixml.so.10 => /lib64/libixml.so.10 (0x00007fb9052e0000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007fb9050a0000)
	libsqlite3.so.0 => /lib64/libsqlite3.so.0 (0x00007fb904d88000)
	libduktape.so.202 => /lib64/libduktape.so.202 (0x00007fb904b40000)
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007fb9048b0000)
	libtag.so.1 => /lib64/libtag.so.1 (0x00007fb9045a8000)
	libmagic.so.1 => /lib64/libmagic.so.1 (0x00007fb904380000)
	libexif.so.12 => /lib64/libexif.so.12 (0x00007fb904138000)
	libexiv2.so.26 => /lib64/libexiv2.so.26 (0x00007fb903be0000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fb9039c8000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb903630000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb9032a8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb902ee0000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb902cc8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb905f38000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007fb902ac0000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007fb902898000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007fb902678000)
	libssh.so.4 => /lib64/libssh.so.4 (0x00007fb902408000)
	libpsl.so.5 => /lib64/libpsl.so.5 (0x00007fb9021f0000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007fb901f58000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007fb901a70000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fb901818000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fb901528000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fb901310000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fb901108000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007fb900eb8000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007fb900ca8000)
	libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007fb900a98000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007fb900710000)
	librt.so.1 => /lib64/librt.so.1 (0x00007fb900508000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fb9002f0000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fb9000e8000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fb8ffed0000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007fb8ffcb0000)
	libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007fb8ffa90000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fb8ff860000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fb8ff630000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fb8ff3a8000)`

Anyone else getting this behaviour?
Cheers

**Comment by ordigno** [comment]
Solved by downgrading libupnp from 1.8.7-1 to 1.8.4-3, which contains UpnpFileInfo_set_ExtraHeaders. 
Gerbera is not actually in the CentOS repos, I installed it from epel-release so I guess compatibility is not 100% guaranteed. I might try and just build the latest release from source, this is still version 1.3.5 by the way.
So not really a gerbera issue, sorry for wasting anyone's time...

**Comment by whyman** [comment]
Glad you got it sorted!

You should try a newer version 1.3.5 is quite old, docker images are available, or you can build yourself.

There is a Fedora package also that may be a good starting point.
