### ISSUE TITLE
No metadata import of specific 24bit/48kHz Flac files

### ISSUE THREAD

**Issue by ghlupe2** [gerbera/gerbera#1066]
I've got quite some 24bit/48kHz Flac files that get imported without any metadata. Debug log says "TagLibHandler: could not open flac file".
Foobar2000 reads the metadata okay and after re-generating the file with foobar2000 flac converter it gets imported well ([see log file](https://github.com/gerbera/gerbera/files/5716324/log.txt)).

This is the original file's header:

`fLaC���"€€�”�¸p�:6€%TtÏyËÒÆâÇ4¼Ø����À ���reference libFLAC 1.1.3 20070917`

This is the re-generated file's header:

`fLaC���"���9�AØ¸p�:6€%TtÏyËÒÆâÇ4¼Ø�À ���reference libFLAC 1.3.2 20170101
`

**Comment by whyman** [comment]
This is one to report with the taglib maintainers.

**Comment by ghlupe2** [comment]
Thanks. I did so and they say it is fixed in the current taglib head. Is there a chance to run Gerbera with it? Would I need to re-compile Gerbera after installing the latest taglib build?

**Comment by whyman** [comment]
Assuming they didnt break their ABI, you should be able to simply rebuild the library without a Gerbera rebuild.

**Comment by whyman** [comment]
Also, this is the taglib issue referenced for those following along at home: https://github.com/taglib/taglib/issues/985
