### ISSUE TITLE
Gerbera UI does not browse to some folders in the "File System".

### ISSUE THREAD

**Issue by klyuri** [gerbera/gerbera#1081]
If a folder contains a folder named 00 or 01 or 000, the parent folder will not be available to display all of its contents.
A warning appears at the bottom of the browser (picture attached).

But, if you rename the folder name 000 to 000A, the contents of the folder will be displayed and it will be possible to go to the next level in depth.

I have given only examples of simple directory names that cause a failure. Their list is longer.

I am using the version from the gentoo repository 1.6.1. But after looking at the changes to later versions, I have not found any changes dedicated to this problem.

![Screenshot_20201231_015535](https://user-images.githubusercontent.com/76794537/103386575-8c47ae80-4b10-11eb-9004-bd223deb25b2.png)

**Comment by KarlStraussberger** [comment]
I know that ugly little beast. It's called autodetection of json type. We met it in other places already. Now it hides in `https://www.github.com/gerbera/gerbera/tree/master/src%2Fweb%2Ffiles.cc`

Thanks for reporting.

**Comment by KarlStraussberger** [comment]
This particular one was fixed in #1024. But there is one more likely issue in files.cc and also the encoding can be optimized a bit more.
