### ISSUE TITLE
UE40KU6000UX Samsung TV not detecting a working Gerbera server 

### ISSUE THREAD

**Issue by Stepperer** [gerbera/gerbera#111]
Server itself is working fine and I can see it on my PC and PS4. But my TV cannot. What can be done?

**Comment by asavah** [comment]
AFAIK in mediatomb there was a workaround for samsung tvs via a custom header.
```<custom-http-headers>
        <!-- Samsung needs it -->
        <add header="transferMode.dlna.org: Streaming"/>
        <add header="contentFeatures.dlna.org: DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01500000000000000000000000000000"/>
    </custom-http-headers>
```
If memory serves currenly in gerbera or libupnp there is no support for custom headers.
https://github.com/v00d00/gerbera/blob/master/src/server.cc#L171

**Comment by v00d00** [comment]
libupnp 1.8 should have headers support we need to implement this.

**Comment by v00d00** [comment]
mrjimenez/pupnp#46 might be useful here.

**Comment by hollaho** [comment]
Just stumbled into the same roadblock. Makes gerbera currently unusable with Samsung TVs.

Yes, the crappy implementation of the Samsung TVs is also to blame. But doesn't help. The fat elephant Samsung wont move, so we need to fix it on this side... Hopefully it is fixed soon.

**Comment by v00d00** [comment]
@Smartsmurf that patch looks really nice! Thanks!

Perhaps you can open a pull request?

I do have a older Samsung, but its only wired network, which is a problem to test with at the moment.

The link to libupnp patch seems to be the same? You will possibly want to open a PR there too https://github.com/mrjimenez/pupnp

**Comment by Smartsmurf** [comment]
@v00d00 thanks for the hint. I corrected the libupnp link.

**Comment by b4r0z** [comment]
Sorry I don’t understand how to patch libupnp. What file needs editing? I have a Samsung tv and files are listed but nothing can be played (unsupported file) while it used to work with mediatomb. Everything is playing on the phone so gerbera (1.1 because 1.3 compile but the web interface wont work) does its job.

**Comment by elmodaddyb** [comment]
Hello @b4r0z - I remember we had a bug #218 - where UI would not work because the ARM chip architecture had problems with the UI's session ID.  Are you running Gerbera server on an ARM system?

Can you elaborate on what error you get on the web UI?

**Comment by b4r0z** [comment]
Bingo, it is a Banana Pi armv and #218 is the thread that helped me to compile succesfully.
The UI error is the same  as  #301
Thanks

**Comment by elmodaddyb** [comment]
I've been trying to create an Arch Linux VM to test out the scenario...Archlinux distro setup is manual labor...so its taking me some time to figure out #301.

**Comment by b4r0z** [comment]
with 1.2 UI is good!
gerbera still not working on Samsung TV though because of the header #220 (I guess).
I'm not as good as @mirecta https://github.com/gerbera/gerbera/issues/220#issuecomment-354501801
hopefully he pops up and write down a tutorial :)

**Comment by Smartsmurf** [comment]
> Sorry I don’t understand how to patch libupnp. What file needs editing? <

You only need to patch httpreadwrite.c by following this [patch](https://github.com/Smartsmurf/smartpackages/blob/master/libs/libupnp-1.8/patches/010-fix-http-response-crlf.patch)

> gerbera still not working on Samsung TV though because of the header #220 (I guess). <

The header is implemented, you find the DLNA_FLAGS in src/common.h

But you need to patch both: libupnp **and** gerbera following this [patch](https://github.com/Smartsmurf/smartpackages/blob/master/multimedia/gerbera/patches/010-improve-dlna-header-preparation.patch)

**Comment by b4r0z** [comment]
```
2018-05-22 01:37:24    INFO: unrecognized action X_GetFeatureList
2018-05-22 01:37:24   ERROR: ActionRequest::update(): response is nullptr, code -115 for X_GetFeatureList

```
Files patched but my Samsung tv is still not playing anything :(
Do I need to remove anything before re-compile?

(Sorry I'm a noob as you can tell)

**Comment by b4r0z** [comment]
- I edited httpreadwrite.c 

- run `install-pupnp18.sh` (modified with CFLAGS)`

- build gerbera `cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=0 -DWITH_EXIF=1 -DWITH_LASTFM=1`
`make -j4`
`make install`

but I still getting` INFO: (NOT) Adding HTTP header "transferMode.dlna.org: Streaming"`

what am I doing wrong? thank you

**Comment by Smartsmurf** [comment]
Between the steps "edit httpreadwrite.c" and "install-upnp18.sh" there should be a step "compile libupnp" resp. "cross-compile libupnp" - depending on which hardware you want to run it.
Basically the sequence of `configure` and `make`.

**Comment by Smartsmurf** [comment]
Very nice. Good job. I wonder whether it was just due to missing taglib...

Can you compile libupnp and gerbera without my patches and check whether it still works?

**Comment by b4r0z** [comment]
> Very nice. Good job. I wonder whether it was just due to missing taglib...

me neither... :)

> Could you please compile libupnp and gerbera without my patches and check whether it still works?

sure, I'm going to try (btw wouldn't that be like starting from scratch?)

**Comment by b4r0z** [comment]
just to make sure, this is the tutorial I've been following https://github.com/gerbera/gerbera/issues/218#issuecomment-354555006
what part do you want me to repeat? the closest thing to libupnp seems "install-upnp18.sh" 
the combile gerbera part is clear :)

**Comment by b4r0z** [comment]
install-upnp18.sh is returning errors ... I need to understand why....

`Makefile:491: recipe for target 'tv_combo' failed`
`make[3]: *** [tv_combo] Error 1`
`make[3]: Leaving directory '/gerbera/build/pupnp-release-1.8.3/upnp/sample'`
`Makefile:1599: recipe for target 'all-recursive' failed`
`make[2]: *** [all-recursive] Error 1`
`make[2]: Leaving directory '/gerbera/build/pupnp-release-1.8.3/upnp'`
`Makefile:502: recipe for target 'all-recursive' failed`
`make[1]: *** [all-recursive] Error 1`
`make[1]: Leaving directory '/gerbera/build/pupnp-release-1.8.3'`
`Makefile:403: recipe for target 'all' failed`
`make: *** [all] Error 2`

**Comment by b4r0z** [comment]
btw gerbera icon is back and the TV can't play files anymore
I would say libupnp is the culprit

**Comment by Smartsmurf** [comment]
OK, good to see. So I will raise pull requests for libupnp and gerbera.

**Comment by crodar33** [comment]
add to this thread #320 , without this add-on, no video can be played
