### ISSUE TITLE
time question

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1116]
I'm seeing this in the logs:

```
info: Loading autoscan location: /Music; recursive: true, last_modified: 1969-12-31 16:00:00
```

That time looks bogus. Any idea why?

**Comment by KarlStraussberger** [comment]
That's what happens if the previous scan of your library did not succeed and the `last_modified` timestamp is 0. If everything is correct it should be something reasonable and no files are scanned on startup. Still all the paths are scanned for inotify to init.

**Comment by neheb** [comment]
Right. This was with no database.

**Comment by whyman** [comment]
Maybe worth having something clearer as its at `info` level?

**Comment by KarlStraussberger** [comment]
I'll handle 0 with an "unset" output.
