### ISSUE TITLE
error when changing track in foobar2000 mobile

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1117]
Examples:

```
Failed to send data in request for `/content/media/object_id/250807/res_id/0'.
Failed to send data in request for `/content/media/object_id/212245/res_id/0/ext/file.mp3'.
Failed to send data in request for `/content/media/object_id/157411/res_id/0/ext/file.flac'.
Failed to send data in request for `/content/media/object_id/177695/res_id/0/ext/file.flac'.
```

Right after changing track is when I get the error. As an example, the mp3 error appeared right after i changed the track to a flac one, the flac one after I changed the track to another, etc...

**Comment by whyman** [comment]
I assume this is with `master`?

**Comment by neheb** [comment]
,Yes

**Comment by whyman** [comment]
I couldn't replicate this with master & libupnp 1.14.0

I assume therefore its a npupnp issue, or one its underlying libs (that message looks like its from microhttpd).

**Comment by neheb** [comment]
huh. ping @medoc92

**Comment by medoc92** [comment]
I can take a look but I need version information for everything

**Comment by neheb** [comment]
Latest Gerbera master, npupnp master and foobar2000 mobile (Android versionn).

**Comment by medoc92** [comment]
But do you have an actual problem, or is the message the problem ? 

Because I do get the message when skipping (probably foobar is less than polite when closing a connection to skip to the next track), but everything works fine as far as I can see (using foobar2000 on win10).

**Comment by neheb** [comment]
No there is no issue.

**Comment by medoc92** [comment]
ok :)
