### ISSUE TITLE
Web UI user accounts not working

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#1139]
or at least it seems so, for some reason they are not loaded out the config, on master.

**Comment by KarlStraussberger** [comment]
Oops, it took a long time for the first error of the rework to pop up.

`Config_manager.cc: 733` `account` is misspelled

I'm in the middle of the folder image change, so feel free to create the PR.

**Comment by KarlStraussberger** [comment]
Seems the issue behind #1099 as well
