### ISSUE TITLE
Add hexdump check to CMake

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#1142]
Its a build time dep now

**Comment by neheb** [comment]
what is hexhump?

**Comment by neheb** [comment]
Can xxd be used instead?

**Comment by whyman** [comment]
Haha! I hadnt noticed that typo :laughing: 

Im sure xxd could be used as an alternative, patches are welcome :)

**Comment by neheb** [comment]
xxd -i seems to have similar output. What do you think?

**Comment by whyman** [comment]
Could wortk with a a bit of post processing, I dont see what it gains though

**Comment by neheb** [comment]
In OpenWrt, we have xxd available but not hexdump.

**Comment by whyman** [comment]
Closed by #1183 instead
