### ISSUE TITLE
[patch] Add commandline Options to daemonize and drop Privs to a user

### ISSUE THREAD

**Issue by flya320** [gerbera/gerbera#1150]
The attached patch adds two commandline options:

-d           daemonize after startup
-u USER  drop privs to user USER

[gerbera-1.6.4-drop-privs-daemonize-2.patch.txt](https://github.com/gerbera/gerbera/files/5861853/gerbera-1.6.4-drop-privs-daemonize-2.patch.txt)

**Comment by whyman** [comment]
Hi @flya320!

Thanks for the patch it looks sensible and its well commented.

I'm wondering about the context of this change, which system are using that would need such functionality? I guess a traditional init of some description?

If that is the use-case I wonder if also there should be an option to write out a pid-file somewhere too?

Once again, thanks for taking the time to put together a patch and submit it.

**Comment by flya320** [comment]
> Hi @flya320!

Hi whyman!

Thanks for the quick reply! 

> I'm wondering about the context of this change, which system are using that would need such functionality? I guess a traditional init of some description?

Yes. I am using an old style init w/o systemd. Mainline gerbera for sure works with traditional init without that patch , however the startscript can be done cleaner with this patch.

> If that is the use-case I wonder if also there should be an option to write out a pid-file somewhere too?

Sounds good. If you decide to add the functionality to mainline, I would add pidfile support to the patch. 

One thing to note: I changed the handling of the confdir variable when it is not supplied by the commandline:
In mainline it only gets set to DEFAULT_CONFIG_HOME if neither config_file nor home is set on the commandline. The patch always sets it to DEFAULT_CONFIG_HOME if unset.

regards! thorsten

**Comment by KarlStraussberger** [comment]
I don't see a problem with confdir. But maybe you can merge that logic with the other checks in `ConfigManager` if nothing else breaks.

**Comment by ghlupe2** [comment]
--logfile may also be moved to the configfile.
Would not be too happy about this; during testing it comes in handy switching w/wo logging on the command line

**Comment by KarlStraussberger** [comment]
Instead of removing options I suggest to merge command line options and config handling: By removing /server/ from the config-xpath it becomes a command line option. If we pas opts into `ConfigManager` it can be done there.

`--logfile` and `--config` must be handled in main as well as the other actions like `--create-config` or `--version`.

I don't like the home-thing as well, but changing this might break a lot of current installations and even our tests might be affeccted.

**Comment by flya320** [comment]
> --logfile may also be moved to the configfile.
> Would not be too happy about this; during testing it comes in handy switching w/wo logging on the command line

Valid point!

**Comment by flya320** [comment]
So for now I will add --pidfile to the commandline options. Might need a week or two...

**Comment by whyman** [comment]
Sounds good! Feel free to fork and open a PR, it makes it easier for us to merge.

**Comment by whyman** [comment]
Hi @flya320, thanks again for you patch, did you get around to working on the additional parts?

**Comment by flya320** [comment]
Hi Ian,sorry to say, I forgot about the patch. March was busy. April should be more quiet. I ll be looking into it soon.Thanks for the reminderThorstenAm 23.03.2021 10:06 vorm. schrieb Ian Whyman ***@***.***>:
Hi @flya320, thanks again for you patch, did you get around to working on the additional parts?

**Comment by flya320** [comment]
Hello again,

in my branch flya320/gerbera the pidfile option is added. The only changes are in main.cc.

Since I am new to the github/merging thing: how does it work from here? Do you look into the changes and if approved merge them to mainline? Or do I have to do something?

Thanks,

Thorsten

**Comment by KarlStraussberger** [comment]
Thanks for your work,

That's quite easy. Just click 
![grafik](https://user-images.githubusercontent.com/23654788/112614925-25414980-8e22-11eb-96ad-dc37c283a72c.png). And fill in the details

**Comment by whyman** [comment]
Closed in #1349, thanks again @flya320!
