### ISSUE TITLE
zpipe: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by joerg-krause** [gerbera/gerbera#1156]
Since commit c443248787dcfb417191637a16daffde747faae7 cross-compiling gerbera fails because of the tool `zpipe`:

```
>>> gerbera custom Building
PATH="/home/joerg/buildroot/output/host/bin:/home/buildroot/output/host/sbin:/usr/local/bin:/usr/local/sbin"  /usr/bin/make -j9  -C /home/joerg/buildroot/output/build/gerbera-custom/
Scanning dependencies of target zpipe
[  1%] Building C object CMakeFiles/zpipe.dir/src/database/create/zpipe.c.o
[  2%] Linking C executable zpipe
[  2%] Built target zpipe
[  3%] Generating sqlite3_create_sql.h
build_headers.sh: line 35: /home/joerg/buildroot/output/build/gerbera-custom/zpipe: cannot execute binary file: Exec format error
make[4]: *** [CMakeFiles/libgerbera.dir/build.make:85: sqlite3_create_sql.h] Error 126
make[3]: *** [CMakeFiles/Makefile2:152: CMakeFiles/libgerbera.dir/all] Error 2
make[2]: *** [Makefile:171: all] Error 2
make[1]: *** [package/pkg-generic.mk:269: /home/joerg/buildroot/output/build/gerbera-custom/.stamp_built] Error 2
make: *** [common.mk:70: _all] Error 2
```

The issue is that the tool `zpipe` is cross-compiled for the target architecture, but CMake tries to run it on the host.

**Comment by whyman** [comment]
Oh interesting! I didnt think of this scenario.

I wonder how we can address this, can CMake know about the host compiler? I guess not?

**Comment by joerg-krause** [comment]
My workaround is to use a Python command instead of zpipe. I dropped zpipe from the CMakeLists.txt and replaced line 35 with the following Python command:

``` sh
$PYTHON3_PATH -c "import zlib,sys; sys.stdout.buffer.write(zlib.compress(sys.stdin.buffer.read()))" < ${FN} > "${FN}.Z"
```

If you can think of that as a solution, then I'll prepare a PR for replacing zpipe with a Python command.

**Comment by whyman** [comment]
Your python based solution is nice, but would add python a build time dependency everywhere.

What I am thinking currently is "why do we need this SQL in the executable?"

I dont think we do

We already install the plain SQL as text files in our install target, so we should probably just load those files and stop padding out the executable with extra stuff for no real gain.

**Comment by KarlStraussberger** [comment]
> We already install the plain SQL as text files in our install target, so we should probably just load those files and stop padding out the executable with extra stuff for no real gain.

In that case, we should add config file entries pointing to the plain text file for testing.

**Comment by neheb** [comment]
Just hit this issue when compiling for OpenWrt.
