### ISSUE TITLE
multi disk albums not showing up properly

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1164]
I have multiple multi disk albums where the disk field gets completely ignored, leading to problems such as successive 1s and 2s.

**Comment by KarlStraussberger** [comment]
Which properties are you using for disc number. Do you mean tracks or albums.

Can you give an example for your sorting - actual and expected. What's in the metadata.

**Comment by neheb** [comment]
example:

![sshot-1](https://user-images.githubusercontent.com/2918873/106102419-3b69ac80-60f4-11eb-9e1c-577389e5b832.png)

**Comment by KarlStraussberger** [comment]
`DISCNUMBER `is not part of the default meta data, it has to be loaded by library-options/id3/auxdata. Sorting in the server is only done by track number. In order to fix that my import script looks like `tracknumber = discnumber*1000+tracknumber`.

**Comment by whyman** [comment]
Duplicate of #832
