### ISSUE TITLE
The repository 'https://dl.bintray.com/gerbera/gerbera focal Release' is not signed.

### ISSUE THREAD

**Issue by dyseg** [gerbera/gerbera#1198]
Hi!

I'm following the "latest" [installation documentation for Ubuntu](https://docs.gerbera.io/en/latest/install.html#ubuntu-mint). After the apt key and the repository is succesfuly added, I run the "apt update" command, and I got the following error message: "The repository 'https://dl.bintray.com/gerbera/gerbera focal Release' is not signed.". Performing the same thing for the gerbera-git repository works as expected, i can proceed to "apt install".
The gerbera-git repo is fine for me, I just thought that maybe it's a not yet recognised issue.

**Comment by whyman** [comment]
Hi @dyseg!

Thanks for reporting, the reason is simply that we have yet to push any packages to the "non-git" repo yet.

The first version to be pushed there will be the 1.7.0 release which is due in the next couple of weeks.

**Comment by dyseg** [comment]
Okay, thanks for the clarification!
