### ISSUE TITLE
Gerbera: can't login with Haiku's browsers

### ISSUE THREAD

**Issue by extrowerk** [gerbera/gerbera#1205]
The web-UI shows up, but the login fields are missing, thus one cannot manage Gerbera on Haiku. Login from other device works.
Is there any way to eliminate the need of the login?

---------

Gerbera version: git main / last release
OS: Haiku 1 hrev54945 x86_64
Gerbera was built against npupnp with the following command line:
```
cmake .. -DWITH_INOTIFY=NO -DWITH_SYSTEMD=NO -DCMAKE_EXE_LINKER_FLAGS="-lnetwork -lbsd" -DCMAKE_INSTALL_PREFIX=/RAMDisk/Inst/gerbera -DWITH_NPUPNP=YES -DCMAKE_CXX_FLAGS="-D_BSD_SOURCE -D_DEFAULT_SOURCE"
```

Starting gerbera like:
```
./gerbera --ip 192.168.1.67
```
results the following:
```
2021-02-05 20:34:34   info: Gerbera UPnP Server git - http://gerbera.io/
2021-02-05 20:34:34   info: Copyright 2016-2021 Gerbera Contributors.
2021-02-05 20:34:34   info: Gerbera is free software, covered by the GNU General Public License version 2
2021-02-05 20:34:34   info: Loading configuration from: /boot/home/config/settings/gerbera/config.xml
2021-02-05 20:34:34   info: Checking configuration...
2021-02-05 20:34:34   info: Configuration check succeeded.
2021-02-05 20:34:34   info: About to migrate metadata from mt_cds_object to mt_metadata
2021-02-05 20:34:34   info: No data will be removed from mt_cds_object
2021-02-05 20:34:34   info: Migrated metadata - object count: 0
2021-02-05 20:34:34   info: Loading 0 configuration items from database
2021-02-05 20:34:34   info: Loading autoscan location: /Data/Zene; recursive: true, last_modified: 2020-10-30 13:25:26
2021-02-05 20:34:34   info: Loading autoscan location: /Data/Képek; recursive: true, last_modified: 2020-10-30 13:07:33
2021-02-05 20:34:34   info: Loading autoscan location: /Data/Video; recursive: true, last_modified: 2019-10-06 04:02:32
2021-02-05 20:34:34   info: Loading autoscan location: /Data/Letöltés; recursive: true, last_modified: 75969-12-13 10:11:04
2021-02-05 20:34:34   info: Initialising libupnp with interface: '/dev/net/idualwifi7260/0', port: 0
2021-02-05 20:34:34   info: Initialized port: 49152
2021-02-05 20:34:34   info: Server bound to: 192.168.1.67
2021-02-05 20:34:34   info: The Web UI can be reached by following this link: http://192.168.1.67:49152/
```

Config file content:
```
<?xml version="1.0" encoding="UTF-8"?>
<config version="2" xmlns="http://mediatomb.cc/config/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mediatomb.cc/config/2 http://mediatomb.cc/config/2.xsd">
  <!--
     See http://gerbera.io or read the docs for more
     information on creating and using config.xml configration files.
    -->
  <server>
    <ui enabled="yes" show-tooltips="yes">
      <accounts enabled="no" session-timeout="30">
        <account user="gerbera" password="gerbera" />
      </accounts>
    </ui>
    <name>Gerbera</name>
    <udn>uuid:163521cf-addf-467a-9e06-7c76f956adc0</udn>
    <home>/boot/home/config/settings/gerbera</home>
    <webroot>/RAMDisk/Inst/gerbera/share/gerbera/web</webroot>
    <!--
        How frequently (in seconds) to send ssdp:alive advertisements.
        Minimum alive value accepted is: 62

        The advertisement will be sent every (A/2)-30 seconds,
        and will have a cache-control max-age of A where A is
        the value configured here. Ex: A value of 62 will result
        in an SSDP advertisement being sent every second.
    -->
    <alive>62</alive>
    <storage>
      <sqlite3 enabled="yes">
        <database-file>gerbera.db</database-file>
      </sqlite3>
    </storage>
    <extended-runtime-options>
      <mark-played-items enabled="no" suppress-cds-updates="yes">
        <string mode="prepend">*</string>
        <mark>
          <content>video</content>
        </mark>
      </mark-played-items>
    </extended-runtime-options>
  </server>
  <import hidden-files="no">
    <scripting script-charset="UTF-8">
      <virtual-layout type="builtin" />
    </scripting>
    <mappings>
      <extension-mimetype ignore-unknown="no">
        <map from="mp3" to="audio/mpeg" />
        <map from="ogx" to="application/ogg" />
        <map from="ogv" to="video/ogg" />
        <map from="oga" to="audio/ogg" />
        <map from="ogg" to="audio/ogg" />
        <map from="ogm" to="video/ogg" />
        <map from="asf" to="video/x-ms-asf" />
        <map from="asx" to="video/x-ms-asf" />
        <map from="wma" to="audio/x-ms-wma" />
        <map from="wax" to="audio/x-ms-wax" />
        <map from="wmv" to="video/x-ms-wmv" />
        <map from="wvx" to="video/x-ms-wvx" />
        <map from="wm" to="video/x-ms-wm" />
        <map from="wmx" to="video/x-ms-wmx" />
        <map from="m3u" to="audio/x-mpegurl" />
        <map from="pls" to="audio/x-scpls" />
        <map from="flv" to="video/x-flv" />
        <map from="mkv" to="video/x-matroska" />
        <map from="mka" to="audio/x-matroska" />
        <map from="dsf" to="audio/x-dsd" />
        <map from="dff" to="audio/x-dsd" />
        <map from="wv" to="audio/x-wavpack" />
        <!-- Uncomment the line below for PS3 divx support -->
        <map from="avi" to="video/divx" />
        <!-- Uncomment the line below for D-Link DSM / ZyXEL DMA-1000 -->
        <!-- <map from="avi" to="video/avi" /> -->
      </extension-mimetype>
      <mimetype-upnpclass>
        <map from="audio/*" to="object.item.audioItem.musicTrack" />
        <map from="video/*" to="object.item.videoItem" />
        <map from="image/*" to="object.item.imageItem" />
        <map from="application/ogg" to="object.item.audioItem.musicTrack" />
      </mimetype-upnpclass>
      <mimetype-contenttype>
        <treat mimetype="audio/mpeg" as="mp3" />
        <treat mimetype="application/ogg" as="ogg" />
        <treat mimetype="audio/ogg" as="ogg" />
        <treat mimetype="audio/x-flac" as="flac" />
        <treat mimetype="audio/flac" as="flac" />
        <treat mimetype="audio/x-ms-wma" as="wma" />
        <treat mimetype="audio/x-wavpack" as="wv" />
        <treat mimetype="image/jpeg" as="jpg" />
        <treat mimetype="audio/x-mpegurl" as="playlist" />
        <treat mimetype="audio/x-scpls" as="playlist" />
        <treat mimetype="audio/x-wav" as="pcm" />
        <treat mimetype="audio/L16" as="pcm" />
        <treat mimetype="video/x-msvideo" as="avi" />
        <treat mimetype="video/mp4" as="mp4" />
        <treat mimetype="audio/mp4" as="mp4" />
        <treat mimetype="video/x-matroska" as="mkv" />
        <treat mimetype="audio/x-matroska" as="mka" />
        <treat mimetype="audio/x-dsd" as="dsd" />
      </mimetype-contenttype>
    </mappings>
    <online-content>
      <AppleTrailers enabled="no" refresh="43200" update-at-start="no" resolution="640" />
    </online-content>
  </import>
  <transcoding enabled="true">
    <mimetype-profile-mappings>
      <transcode mimetype="video/mpeg" using="vlcmpeg" />
    </mimetype-profile-mappings>
    <profiles>
      <profile name="vlcmpeg" enabled="yes" type="external">
        <mimetype>video/mpeg</mimetype>
        <accept-url>yes</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>yes</accept-ogg-theora>
        <agent command="vlc" arguments="-I dummy %in --sout #transcode{venc=ffmpeg,vcodec=mp2v,vb=4096,fps=25,aenc=ffmpeg,acodec=mpga,ab=192,samplerate=44100,channels=2}:standard{access=file,mux=ps,dst=%out} vlc:quit" />
        <buffer size="14400000" chunk-size="512000" fill-size="120000" />
      </profile>
    </profiles>
  </transcoding>
</config>

```

**Comment by extrowerk** [comment]
![Uploading 4D546F9A-C177-4F22-AF47-45CC1B24DC1B.png…]()

**Comment by extrowerk** [comment]
![407225D9-7F2C-4C52-A050-2B771121CE8D](https://user-images.githubusercontent.com/5569059/107081195-9be2a300-67f2-11eb-8a5d-70ebc2972400.png)

**Comment by extrowerk** [comment]
![529F19F2-A2CA-4F1B-936B-DA56F94C618B](https://user-images.githubusercontent.com/5569059/107081293-c3397000-67f2-11eb-8e94-d69ba5bb2f6b.png)

**Comment by whyman** [comment]
Login will be an artifact of something JavaScript not working, it's not enabled by default.

Any is errors in the console?

**Comment by extrowerk** [comment]
![A774DB0F-C533-4B73-87C7-42A6E19DC946](https://user-images.githubusercontent.com/5569059/107087563-e9afd900-67fb-11eb-88e0-a62736a17bb7.png)

**Comment by extrowerk** [comment]
Otter also complains about the “Unexpected keyword: export” in the popper.js file.

**Comment by whyman** [comment]
Does this browser exist on other platfroms?

There shouldnt be any CORS because everything is served from the same server....

**Comment by extrowerk** [comment]
WebPositive is Haiku only, but Otter should be available on other platforms. FYI: the Otter port on Haiku 
uses QtWebKit, not QtWebEngine. We don't have yet that backend.

Ian Whyman ***@***.***>:

**Comment by whyman** [comment]
I tried it on Midori `AppleWebKit/605.1.15 Midori/6` and Ephinany (both based on GTKWebKit) and could not reproduce on master :(

**Comment by extrowerk** [comment]
Thanks for testing it.
If you are brave-herated adventureous type you can install Haiku (64 bit recommended: https://download.haiku-os.org/nightly-images/x86_64/ ) as a virtual machine ( https://www.haiku-os.org/guides/virtualizing ). 
Gerbera and its dependencies should be available trough HaikuDepot (application store, you can find it In the leaf menu).
WebPositive comes preinstalled, Otter also available in the Depot. If you need any assistance, feel free to contact me here or trough irc.

**Comment by extrowerk** [comment]
Also keep in mind you can't change files installed trough the package management, do not even try to sudo them, because they are immutable. Also the whole system is immutable.

If you want to hack gerbera on Haiku you would have to build it in a writeable prefix (like home). You would need the required develop packages, which doesn't gets listed in Depot in default (use the menu at the top of the Depot window to make them visible or use cli like ```pkgman search somethin``` and ```pkgman install something_devel``` or ```pkgman install devel:something``` to install the devel counterpart).

Here is the current gerbera recipe, you can get some hint how to build it from this: https://github.com/haikuports/haikuports/tree/master/net-misc/gerbera
You probably won't need the patches, they are required only for packaging.
Do not care about $secondaryArchSuffix, thats required only for 32 bit.

Socket and its friends are in -lnetwork
pthread/math/c lib is -lroot and it is linked implicitly.

**Comment by Brunobasta** [comment]
I like to try the new Gerbera - 1.8.2-1 - x86_64 Version, is the Login still needed?

**Comment by KarlStraussberger** [comment]
> I like to try the new Gerbera - 1.8.2-1 - x86_64 Version, is the Login still needed?

we prefer new issues for new topics - anyway the answer is **no**. Login has to be enabled in `config.xml`

**Comment by extrowerk** [comment]
Even if login not needed, the admin UI is not usable on Haiku right now, but one can manage gerbera trough a phone or trough a different computer.

**Comment by KarlStraussberger** [comment]
Does the browser support network analysis in developer tools (F12 on Firefox or Chrome) to see the sequence of requests and their respective content?

**Comment by extrowerk** [comment]
Otter browser have that functionality

**Comment by extrowerk** [comment]
WP: http://0x0.st/-_d1.png
Otter: http://0x0.st/-_dj.png

The links on the top bar is simply not active.

**Comment by KarlStraussberger** [comment]
Can you work out where the call is leaving the gerbera server? Is there any js-library (e.g jquery) on your server or any redirection to web resources that raises the CORS issue.

There should not be a `?` in the end of the URL.

**Comment by extrowerk** [comment]
I don't know about this things,sorry.
It is my desktop machine, running latest Gerbera. No other server runs on it, i don't use js libraries. I have no firewall here, but a hblock (hosts file based block). 

I understand neither WebPositive ( WebKit) nor Otter (QtWebKit) sports the latest engines, and Haiku is not a main platform for Gerbera, but the bug seems to be something small and it would be nice if we could iron it out.

Let me know if you need any info or assistance. Also you can try it in [QEMU or in something similar.](https://www.haiku-os.org/guides/virtualizing)

**Comment by KarlStraussberger** [comment]
The page is inactive because the javascript is blocked by the CORS error. This happens if the main page is loaded from another server than the script or if the script is calling another server (cross origin). All the entries in the network log seem to point to your server only, except those not visible in the screenshot do not. If they do it's very likely, that there is an issue in your browsers engine.

**Comment by extrowerk** [comment]
Thats easily possible.
