### ISSUE TITLE
  Cannot Compile simple program using std::filesystem

### ISSUE THREAD

**Issue by adamj02090830** [gerbera/gerbera#1215]
Tried compiling code on macOS Mojave. Here's the result:

cmake ../gerbera
-- Gerbera Version: v1.6.4-207-g1e0cb4eb
CMake Error at cmake/modules/FindFilesystem.cmake:227 (message):
  Cannot Compile simple program using std::filesystem
Call Stack (most recent call first):
  CMakeLists.txt:312 (find_package)

**Comment by whyman** [comment]
You need to pass some args to CMake on macos

This is what we do in the CI:
https://github.com/gerbera/gerbera/blob/1e0cb4ebf6443a63875b0ae2c97c6be820d3d251/.github/workflows/macos.yml#L42-L44

**Comment by neheb** [comment]
Ah yes. On macOS , gcc is symlinked to clang with some hackery to make it seem more gcc like...

**Comment by whyman** [comment]
@adamj02090830 did you sort your issue?

**Comment by whyman** [comment]
Assuming they got it working.
