### ISSUE TITLE
Cannot get to media directories from gerbera.html

### ISSUE THREAD

**Issue by froginperil** [gerbera/gerbera#1227]
Fedora 33

There is no way to get to an external hard drive to add files via /run/media/[user]/[resource]. Nor can I get to subdirectories from home.

**Comment by KarlStraussberger** [comment]
You're right. There is a couple of paths that are excluded from adding via ui, including /run, /sys, /dev. Anyway, media files have to be permanently available, so if you mount to add an external drive, create a propert mount point, like /myMedia.

I don't understand your issue with home. Where does home reside?

You can bypass some of the restrictions by adding the config entries for [autoscan](https://docs.gerbera.io/en/latest/config-import.html#autoscan)

**Comment by KarlStraussberger** [comment]
@froginperil I see your point and intend to make these directories configurable in `config.xml`
