### ISSUE TITLE
Debug output is disabled in build-dev.sh

### ISSUE THREAD

**Issue by dyseg** [gerbera/gerbera#1230]
Hi! Is there any reason why is the debug output disabled in the debian/ubuntu build?
https://github.com/gerbera/gerbera/blob/11b9273b75973aa05c753cfdeaba4227f2c5f207/scripts/debian/build-deb.sh#L141
For the docker build, the debug output is enabled, I think for macOS build too (implicitly). Could you enable for debian/ubuntu build too? The command line option -D does not have any effect currently.

**Comment by whyman** [comment]
Good idea, it was just to reduce the Deb size
