### ISSUE TITLE
Update library versions

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#1232]
Taglib 1.12 is [out](https://github.com/taglib/taglib/commits/master)

spdlog 1.8.2 is [available](https://github.com/gabime/spdlog/tags)

Do we want to update before 1.7?

**Comment by KarlStraussberger** [comment]
I'm running with spdlog since two weeks.

taglib is under investigation.

**Comment by whyman** [comment]
Wow a taglib release finally! Great to see

**Comment by KarlStraussberger** [comment]
Run a full library scan with taglib and was glad to see a lot less messages from taglib.

**Comment by KarlStraussberger** [comment]
I also tried with pupnp 1.14.1, but got a crash.

**Comment by whyman** [comment]
> I also tried with pupnp 1.14.1, but got a crash.

Concerning, I guess you are already looking into it.

**Comment by KarlStraussberger** [comment]
I switched back to head which works. Maybe it's been some downgrade issue. Need some time...

**Comment by KarlStraussberger** [comment]
@whyman
I do not really understand why 1.14.1 crashed and head didn't. Anyway, I came in 7 hours late. Now there are two PRs in pupnp (https://github.com/pupnp/pupnp/pull/234 and https://github.com/pupnp/pupnp/pull/235).

From my point of view it's not a big issue because it only happens if you have an interface without address at all. In my case there are two physical interfaces which are bonded. They are up and do multicast.

```
2: eth1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bond0 state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
3: eth0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc fq_codel master bond0 state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
4: bond0: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether xx:xx:xx:xx:xx:xx brd ff:ff:ff:ff:ff:ff
```

On top of this I run separate VLANs for home, guests and network management 😓

**Comment by whyman** [comment]
Nice PR, yours seems cleaner than the other one

I feel like pupnp should do a 1.14.2 with that fix ASAP
