### ISSUE TITLE
Import images in subdirectories

### ISSUE THREAD

**Issue by vogtuh** [gerbera/gerbera#1240]
It is not possible to import media from a subdirectory called "01" or "02" etc. (abbreviation for months!)
Rem: it seems to be a problem of the leading zero. I changed to Jan or Feb etc. and it works fine, even changing it to 01-Jan or 02-Feb etc. works!

**Comment by whyman** [comment]
Which Gerbera version are you running? Can you provide a debug log?

**Comment by KarlStraussberger** [comment]
There used to be isssues in the web UI up to gerbera 1.6.4, but the files have been imported (check with upnp client like foobar or vlc), afaik.

**Comment by vogtuh** [comment]
Version 1.6.0 on Ubuntu with MySql
How to I generate a debug log?

**Comment by vogtuh** [comment]
I'm sure something was imported, but I discovered, that my server was on 100% load during searching with a UpNp client! So I had to kill the gerbera process.

**Comment by KarlStraussberger** [comment]
Debug output can be gather when starting `gerbera --debug` if debug support was compiled in, in the first place. Check with `gerbera --compile-info`.

1.6.0 has some trouble, so maybe you can get hold of 1.6.4 or even better - build and test our current development head.

**Comment by whyman** [comment]
You can download a deb package of git master from actions: https://github.com/gerbera/gerbera/actions/runs/575501511

**Comment by vogtuh** [comment]
Thank you for help.
I'm using the repository of ppa:stephenczetty/gerbera-updates. If he doesn't upgrade soon I change the deb pachages.
