### ISSUE TITLE
Ubuntu 20.04 package on Bintray seems incorrectly configured

### ISSUE THREAD

**Issue by lckarssen** [gerbera/gerbera#1264]
Let me start off by mentioning that this is the first time I try to install Gerbera, so I may easily be missing something. 

I tried to install Gerbera (1.7.0) from [the Ubuntu repository at Bintray](https://bintray.com/gerbera/gerbera), as mentioned in the documentation. After adding the repo I installed the package and its dependencies and I expected the service to have started (as is usual on Debian). This turned out not to be the case. 

I then read on in the documentation and came across the section about the config file. A `dpkg-query -L gerbera` showed me that no default `config.xml` was supplied be the package and that the `/etc/gerbera` required byt the daemon wasn't created either. I created the directory and the `config.xml` file, `chown`-ed both, changed the `<home>` entry to `/etc/gerbera` and expected all to be fine. Yet, a `systemctl start gerbera` followed by a `systemctl status gerbera` showed me that the service still didn't run. 

Next, I decided to run `gerbera` manually to see if there were any error messages: 
```
$ sudo -u gerbera gerbera -c /etc/gerbera/config.xml
2021-02-28 22:33:27   info: Gerbera UPnP Server 1.7.0 - http://gerbera.io/
2021-02-28 22:33:27   info: Copyright 2016-2021 Gerbera Contributors.
2021-02-28 22:33:27   info: Gerbera is free software, covered by the GNU General Public License version 2
2021-02-28 22:33:27   info: Loading configuration from: /etc/gerbera/config.xml
2021-02-28 22:33:27   info: Checking configuration...
2021-02-28 22:33:27  error: File '/usr/local/share/gerbera/sqlite3.sql' does not exist
```
As you can see it is looking for a file in `/usr/local/share/gerbera`, whereas the `dpkg-query` command I mentioned above only lists files in `/usr/share/gerbera` (so without the `local/`). This is also what one expects on Debian. I then checked the generated `config.xml` file and replaced all `/usr/local/` paths with `/usr/`, but still no luck. I guess the path to the `sqlite3.sql` file is hardcoded somewhere. 

Finally, I checked the systemd service description: 
```
$ cat /lib/systemd/system/gerbera.service 
[Unit]
Description=Gerbera Media Server with MySQL
After=mysql.target network.target

[Service]
Type=simple
User=gerbera
Group=gerbera
ExecStart=/usr/local/bin/gerbera -c /etc/gerbera/config.xml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
Much to my surprise, this also references `/usr/local/bin/`, instead of `/usr/bin/` where the `gerbera` binary actually is located.

Am I missing something, or is the `1.7.0-focal1` package on Bintray not up to par (yet)? 

Would it be better to go with the other PPA mentioned in the documentation?

**Comment by Martii** [comment]
Already installed:

``` console
$  apt-cache madison sqlite3
   sqlite3 | 3.31.1-4ubuntu0.2 | http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
   sqlite3 | 3.31.1-4ubuntu0.2 | http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
   sqlite3 |   3.31.1-4 | http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages

$ apt-cache policy sqlite3
sqlite3:
  Installed: (none)
  Candidate: 3.31.1-4ubuntu0.2
  Version table:
     3.31.1-4ubuntu0.2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
     3.31.1-4 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages

$ locate sqlite3.sql
/usr/share/gerbera/sqlite3.sql

$ apt-cache policy gerbera
gerbera:
  Installed: 1.6.0-1~ppa1
  Candidate: 1.6.0-1~ppa1
  Version table:
 *** 1.6.0-1~ppa1 500
        500 http://ppa.launchpad.net/stephenczetty/gerbera-updates/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0+dfsg-3ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
```
**NOTE** 1.6.0 ... this explains what the small fire in the noggin the other day on a machine redo. So the PPA seems to be a bit behind [releases](https://github.com/gerbera/gerbera/releases) of [1.7.0](https://github.com/gerbera/gerbera/releases/tag/v1.7.0)... Cc: @stephen-czetty  ... anyhow...

This is currently what the PPA does for the systemd service:

``` ini
$ cat /lib/systemd/system/gerbera.service
[Unit]
Description=Gerbera Media Server
Documentation=man:gerbera(1) https://gerbera.io/
After=mysql.target network.target

[Service]
Type=simple
EnvironmentFile=/etc/default/gerbera
User=gerbera
Group=gerbera
ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml $EXTRAARGS
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

My most recent initial setup tagged in `journalctl`:
```
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Loading configuration from: /etc/gerbera/config.xml
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Checking configuration...
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Setting filesystem import charset to UTF-8
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Setting metadata import charset to UTF-8
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Setting playlist charset to UTF-8
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Configuration check succeeded.
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41 warning: Sqlite3 database seems to be corrupt or doesn't exist yet.
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: no sqlite3 backup is available or backup is corrupt. automatically creating database...
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: database created successfully.
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: About to migrate metadata from mt_cds_object to mt_metadata
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: No data will be removed from mt_cds_object
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Migrated metadata - object count: 0
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Initialized port: 49152
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: Server bound to: x.x.x.x
Dec 04 11:12:41 server gerbera[2473]: 2020-12-04 11:12:41   info: The Web UI can be reached by following this link: http://x.x.x.x:49152/
```

My most recent startup:

```
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Loading configuration from: /etc/gerbera/config.xml
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Checking configuration...
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Setting filesystem import charset to UTF-8
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Setting metadata import charset to UTF-8
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Setting playlist charset to UTF-8
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Configuration check succeeded.
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: About to migrate metadata from mt_cds_object to mt_metadata
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: No data will be removed from mt_cds_object
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Migrated metadata - object count: 0
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Initialized port: 49152
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: Server bound to: x.x.x.x
Feb 28 23:14:43 server gerbera[1365]: 2021-02-28 23:14:43   info: The Web UI can be reached by following this link: http://x.x.x.x:49152/
```

Hope some of this might help. :smile_cat:

**Comment by whyman** [comment]
Thanks for reporting @lckarssen!

The repo is new, and I dont run debian, so apologies for the bugs and feedback is very much appreciated :+1:

I did a test in docker and it seemed fine, but clearly that was not representative of a real system

**Comment by whyman** [comment]
In the code it looks like you can also override the default DATADIR path via `GERBERA_DATADIR` env var

So something like 

```
GERBERA_DATADIR=/usr/share/gerbera gerbera --home /var/lib/gerbera --create-config > /etc/gerbera/config.xml
```

Should generate you a correct config file.

Ive make some changes in #1265, would be great if you could test them

**Comment by whyman** [comment]
Debs have been build and published to the git repo, or you can grab them directly from https://github.com/gerbera/gerbera/actions/runs/610267879

**Comment by lckarssen** [comment]
Thanks @whyman! I will try to find some time to test the new deb in the coming days and will report back.

**Comment by whyman** [comment]
Great, we are likely to do a 1.7.1 release, so it would be nice to get it sorted for that.

**Comment by lckarssen** [comment]
I have tried to install the `.deb` you linked to below and it almost works. 
1. there is a typo in the URL you posted above: the `:` following the last `/` needs to be removed :smiley: 
2. the file `/etc/gerbera/config.xml` gets generated :+1: 
3. however, the service doesn't start automatically. 

It turns out the home directory specified in the config file (`/var/lib/gerbera`) isn't created automatically, which leads to the failure:
```
/usr/bin/gerbera -c /etc/gerbera/config.xml 
2021-03-04 21:02:18   info: Gerbera UPnP Server v1.7.0-3-g2edd6e7f - http://gerbera.io/
2021-03-04 21:02:18   info: Copyright 2016-2021 Gerbera Contributors.
2021-03-04 21:02:18   info: Gerbera is free software, covered by the GNU General Public License version 2
2021-03-04 21:02:18   info: Loading configuration from: /etc/gerbera/config.xml
2021-03-04 21:02:18   info: Checking configuration...
2021-03-04 21:02:18  error: [/__w/gerbera/gerbera/src/config/config_manager.cc:929] load Error: Directory '/var/lib/gerbera/' does not exist
```
I think you need to remove the `--no-create-home` from [line 19 of `/scripts/debian/postinst`](https://github.com/whyman/gerbera/blob/2f8abe701ca200fbc73d32773763afd8546c1761/scripts/debian/postinst#L19). 

After manually creating and `chown`ing `/var/lib/gerbera`, the service starts successfully .

**Comment by whyman** [comment]
@lckarssen Thanks so much for testing it, and for the great feedback!

I will put together a small patch with your changes (unless you are feeling generous enough to open a PR :grin: )

**Comment by lckarssen** [comment]
I can definitely whip up a PR for that change, however, I probably won't have time to do that before Sunday. If you can wait, that's fine. If you want to fix it yourself before that: fine too :grin:

**Comment by lckarssen** [comment]
@whyman PR #1286 has the fix for the missing home directory. Let's see if the CI checks pass (I assume they will, given that it is such a small change). Do the CI scripts automatically build `.deb`s? If so, can you tell me where to find them so I can test the package?

**Comment by whyman** [comment]
@lckarssen Yes, they are built automatically (on merge to master)

You can get the debs either as a build artifact from actions (https://github.com/gerbera/gerbera/runs/2054630473) or they are pushed to the "git" bintray repo: (https://dl.bintray.com/gerbera/gerbera-git/pool/main/g/gerbera/)

**Comment by lckarssen** [comment]
@whyman Thanks for pointing to the build artifacts. I will try to test the 20.04 build tonight and get back here.

**Comment by lckarssen** [comment]
@whyman I just installed the `gerbera_1.7.0+21~20210307224427-focal1_amd64.deb` that was generated from PR #1286 and it works fine. 

Thanks for the help on this issue.
