### ISSUE TITLE
Extend supported devices by Denon RCD-N9

### ISSUE THREAD

**Issue by phi-whiterabbit** [gerbera/gerbera#1281]
I have a Denon RCD-N9 system and i am successfully using it with gerbera since a couple of years. So Denon RCD-N9 should probably be added to the list of supported devices.

**Comment by KarlStraussberger** [comment]
Thanks for sharing your device details.

Does the N9 already run on the HEOS platform? If not, what's the device identification from UPnP broadcast?

**Comment by phi-whiterabbit** [comment]
I have to admit that neither i know what the HEOS platform is nor do i know how to determine the device identification from UPnP broadcast.

**Comment by KarlStraussberger** [comment]
The fastest way is to go to gerbera web ui and check out the userAgent of your N9.

HEOS is the Denon multiroom system which obviously is the difference between N9 and my N10.

**Comment by phi-whiterabbit** [comment]
According to gerbera web ui the user agent is
KnOS/3.2 bridgeCo-DMP/3.0 DLNADOC/1.50 INTEL_NMPR/2.0
