### ISSUE TITLE
File listing issue in Denon HEOS app

### ISSUE THREAD

**Issue by lckarssen** [gerbera/gerbera#1287]
@KarlStraussberger in #1281 I saw you mentioned the Denon HEOS multiroom system. Yesterday I happened to try Gerbera with the HEOS app (on Android). I noticed that, although the Gerbera server is found, it doesn't list my albums, artists, etc. in the main search view, i.e. when I go to any of the options (except 'Door mappen bladeren', which means 'Browse through folders; see below):
![Screenshot_20210306-235127_HEOS_small](https://user-images.githubusercontent.com/5592236/110256932-c6637f80-7f9b-11eb-8114-a3ac7ba2a97a.png)

For example, if I click on "Albums", I get an empty listing ("Geen informatie beschikbaar' means 'No information available"):
![Screenshot_20210306-235135_HEOS_small](https://user-images.githubusercontent.com/5592236/110256971-0460a380-7f9c-11eb-9e35-a05f08912b88.png)

If, however, I go to the "Browse through folders" menu item I see:
![Screenshot_20210306-235232_HEOS_small](https://user-images.githubusercontent.com/5592236/110256947-df6c3080-7f9b-11eb-93ca-cad373ea03e2.png)
From there I can e.g. go to "Audio" and find my audio files. So after some digging through the HEOS app, I can find my media, but not from the main screen. @KarlStraussberger do you observe this too? 

I run Gerbera on a server with Ubuntu 20.04 (an LXC container) with [the `.deb` package created by @whyman in this comment on #1264](https://github.com/gerbera/gerbera/issues/1264#issuecomment-787873485). 

I also tried to install MiniDLNA/ReadyMedia and Universal Media Server (in separate containers) and those do show the artists, albums, etc. when selecting Albums etc. in the main screen of the HEOS app. This leads me to believe it could be some misconfiguration of Gerbera on my side, or maybe a difference in the way the information is advertised on the network (I have no knowledge of UPnP, so this is a wild guess).

**Comment by KarlStraussberger** [comment]
@lckarssen Thanks for creating the issue. Actually, this is on my todo list, but I did not find the time, yet.

**Comment by lckarssen** [comment]
Thank you for the heads-up @KarlStraussberger. So, from your comment I understand it is not a configuration issue, but rather something that has to be implemented in Gerbera, right? 

I don't have direct access to a HEOS system myself (it's at my parents' place), but if you need some testing I will see what I can do.

**Comment by KarlStraussberger** [comment]
Thanks for your offer to test, because testing is always welcome. But I suppose my testing equiment (4 speakers, 1 N-10 and 1 AVR) is quite substantial :smile:

**Comment by KarlStraussberger** [comment]
> 
> 
> Thank you for the heads-up @KarlStraussberger. So, from your comment I understand it is not a configuration issue, but rather something that has to be implemented in Gerbera, right?

Yes, it's got to do with search which only works for tracks at the moment.

**Comment by KarlStraussberger** [comment]
From my point of view search for artists seems to be broken in current version of the app. I get an error -11 immediately after pressing search and there is no message in server log.

**Comment by Jurian15** [comment]
After a month I thought I would try to solve it, but using a custom file structure (I added more containers to artist and genre and moved the containers of audio to the parent of audio) and running it with docker on gerbera/gerbera-master, it still refused to work. The search on the N10 didn't freeze anymore, but it and the app only gave results when searching in tracks. The album, artist and genre folders in the main view list no content, while the Browse folders and tracks work.
I have tried changing the searchable tag in common.js, and changing the flag for it in the config.xml, with no result. I also tried one container with chain.album with no succes. What is needed in the virtual structure so ceol is able to recognize the containers?

**Comment by KarlStraussberger** [comment]
For the search in albums and artists to work you need to set the `<upnp searchable-container-flag="yes">` and reimport your whole library.

We use property `searchable` on containers to identify the ones to be found.

**Comment by Jurian15** [comment]
I already had the flag attribute set in the configuration, but I tried different ending tags: `...yes>`, `...yes/>` and `...yes></upnp>`. All without succes. I tried those variants with the virtual-layout type set to builtin, but that also didn't work.

**Comment by KarlStraussberger** [comment]
The crucial item for search is not the container flag. It only reduces the result list to exactly one item.

The import change was the response to `GetSearchCapability` UPnP command. HEOS needs `dc:creator` to be searchable otherwise it does not search. Maybe you can try some app like _UPnP Tools_ and call the method on the _ContentDirectoryService_ of your gerbera server.

**Comment by Jurian15** [comment]
Via Device Spy, the gerbera server returned on GetSearchCapabilities:
`upnp:class,dc:title,upnp:artist,upnp:album,dc:date,dc:created,upnp:date,upnp:genre,dc:description,upnp:longDescription,upnp:episodeSeason,upnp:originalTrackNumber,upnp:albumArtURI,upnp:region,dc:creator,upnp:author,upnp:director,dc:publisher,upnp:rating,upnp:actor,upnp:producer,upnp:artist@role[AlbumArtist],upnp:composer,upnp:conductor,upnp:orchestra,upnp:contentClass,res,res@size,res@duration,res@bitrate,res@sampleFrequency,res@nrAudioChannels,res@resolution,res@colorDepth,res@protocolInfo,res@resFile,res@type,res@fanArtObject,res@fanArtResource,res@bitsPerSample,res@dc:language,res@sec:acodec,res@sec:vcodec`
dc:creator is in the list, so it looks like that can't be the issue.

**Comment by KarlStraussberger** [comment]
Did you pull the latest docker image? There have been some smaller issues in search. My local system works perfectly, which does not help you :sad:

**Comment by Jurian15** [comment]
Yes, I have been using the master image since you pointed out that I had to use that image.

**Comment by Jurian15** [comment]
I have been able to log all the network traffic on my server and inspect it with Wireshark. Looking in the packets and copying the arguments to Device spy. I have to conclude that searching for `object.container.person.musicArtist` and `object.container.album.musicAlbum` never returns a result. searching for `object.item.audioItem.musicTrack` works just fine.

**Comment by KarlStraussberger** [comment]
Can you try to get the output if you run gerbera with `--debug`

**Comment by KarlStraussberger** [comment]
> Yes, I have been using the master image since you pointed out that I had to use that image.

Please make sure the image was updated within the last week.

**Comment by Jurian15** [comment]
> Can you try to get the output if you run gerbera with `--debug`

Is it possible to run debug gerbera with docker or do you have to run it directly?

**Comment by Jurian15** [comment]
> Please make sure the image was updated within the last week.

I forgot to update the docker images, so it was running a version from November. The latest version didn't fix the problem.

**Comment by KarlStraussberger** [comment]
@Jurian15 Did you try out newer versions (HEOS App and gerbera) in the meantime? My system is doing perfectly well with all sorts of structures and media. If still present, please create a new issue with the output created when running `gerbera --debug`
