### ISSUE TITLE
MySQL: Error: tried to create or update an object with an illegal parent id

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#1300]
Gerbera master (commit f9ccc01, way after 1.6.4) with the fix for #1299 does not work with MySQL:

> Error: [/usr/local/src/gerbera/src/database/sql_database.cc:351] _addUpdateObject Error: tried to create or update an object with an illegal parent id

This seems to happen with every file that gets added (many hundreds of that errors).

**Comment by cweiske** [comment]
When browsing the server via the web interface, every folder only has a single item inside.

**Comment by KarlStraussberger** [comment]
That is fixed in #1292. Can be merged.

**Comment by cweiske** [comment]
This is indeed fixed with #1292.
The only-one-file-in-each-folder-problem is also gone.

Thank you, @KarlStraussberger
