### ISSUE TITLE
Limit "File system" web UI tab to certain folders

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#1302]
Gerbera's web interface "File system" tab shows many directories that should not be shown:

- /home
- /media
- /mnt
- /opt
- /root
- /srv

On the other side, it does not show the `/var` directory that I have my music files in:

![2021-03-14 gerbera file system web ui](https://user-images.githubusercontent.com/59036/111065170-a27ecd00-84b8-11eb-9a01-b54bbe5826ae.png)

I would like to be able to configure which directories are visible in the "file system" view.

My usecase would be that only `/var/spool/music/` and subfolders are visible, and no others.

----

This is with Gerbera master (commit f9ccc014, long after 1.7.0)

**Comment by cweiske** [comment]
Ah. This is partially solved by #1252.

**Comment by whyman** [comment]
Partially?

**Comment by KarlStraussberger** [comment]
You can check https://docs.gerbera.io/en/latest/config-server.html#upnp. It should do what you look for.

**Comment by whyman** [comment]
This is now configurable, thanks to @KarlStraussberger 



See: https://github.com/gerbera/gerbera/pull/1252

**Comment by cweiske** [comment]
Partially, because I have to manually specify all folders to exclude.
When I install a new application on the server, I must remember to add a new exclude to my gerbera configuration.

A whitelist would be much more secure than a blacklist:
```
    <system-directories>
      <add-path name="/bin"/>
      <add-path name="/boot"/>
      <add-path name="/dev"/>
      <add-path name="/etc"/>
      <add-path name="/home"/>
      <add-path name="/lib"/>
      <add-path name="/lib32"/>
      <add-path name="/lib64"/>
      <add-path name="/lost+found"/>
      <add-path name="/media"/>
      <add-path name="/mnt"/>
      <add-path name="/opt"/>
      <add-path name="/proc"/>
      <add-path name="/root"/>
      <add-path name="/run"/>
      <add-path name="/sbin"/>
      <add-path name="/srv"/>
      <add-path name="/sys"/>
      <add-path name="/tmp"/>
      <add-path name="/usr"/>

      <add-path name="/var/backups"/>
      <add-path name="/var/cache"/>
      <add-path name="/var/lib"/>
      <add-path name="/var/local"/>
      <add-path name="/var/lock"/>
      <add-path name="/var/log"/>
      <add-path name="/var/lost+found"/>
      <add-path name="/var/mail"/>
      <add-path name="/var/opt"/>
      <add-path name="/var/run"/>
      <add-path name="/var/tmp"/>
      <add-path name="/var/www"/>

      <add-path name="/var/spool/anacron"/>
      <add-path name="/var/spool/citadel"/>
      <add-path name="/var/spool/cron"/>
      <add-path name="/var/spool/dma"/>
      <add-path name="/var/spool/mail"/>
      <add-path name="/var/spool/news"/>
      <add-path name="/var/spool/owncloud"/>
      <add-path name="/var/spool/rsyslog"/>
      <add-path name="/var/spool/uptimed"/>

    </system-directories>
```

**Comment by KarlStraussberger** [comment]
Ok, I see your issue. The simplest thing would be to add an attribute `mode` to `system-directories` with values:
- black-list
- white-list

**Comment by cweiske** [comment]
Thank you!
