### ISSUE TITLE
Add Directories container to Audio in builtin layout

### ISSUE THREAD

**Issue by phi-whiterabbit** [gerbera/gerbera#1310]
I would like to see a Directories container in Audio when using builtin layout, just like in Videos and Photos. What do you think?
Would you accept such a patch?
Yes, i know i can just use js layout and do this via javascript, but this ist damn slow compared to builtin layout.

**Comment by KarlStraussberger** [comment]
I don't see a problem with such an addition

**Comment by Jodi42-shb** [comment]
Why hasn't this added yet??

**Comment by KarlStraussberger** [comment]
@Jodi42-shb It's there https://github.com/gerbera/gerbera/blob/17f39d704fa549dd5c62c1f80e19381e12f2c80b/src/content/layout/builtin_layout.cc#L481-L482 (**builtin layout**)
