### ISSUE TITLE
Option to sort by filename

### ISSUE THREAD

**Issue by phi-whiterabbit** [gerbera/gerbera#1311]
I am using gerbera with an import javascript, where i added a Directories container like for Videos and Photos. Here i want my audio file in a directory to be sorted by filename instead of by title or track number. Is that possible? If not, then this would be a nice feature, isn't it?

**Comment by phi-whiterabbit** [comment]
The default is to sort by title isn't it?

**Comment by KarlStraussberger** [comment]
As by definition albums are sorted by track number and plain containers by track name. In order to get the sort order changed, change the type from `UPNP_CLASS_CONTAINER_MUSIC_ALBUM `to `UPNP_CLASS_CONTAINER`

**Comment by phi-whiterabbit** [comment]
Ah ok.
