### ISSUE TITLE
Can't work with Debian 10 Buster and large file sizes

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1320]
I get these errors:

```
ex:filesystem error: cannot get file size: Value too large for defined data type
```

Similar issue to https://github.com/gerbera/gerbera/blob/master/src/util/tools.cc#L212 but no idea where it shows up now.

**Comment by neheb** [comment]
Hmm https://github.com/neheb/gerbera/commit/4f361c0ff7636842f649f890093d315f12c92d31 doesn't seem to fix it.

**Comment by whyman** [comment]
Hmm, almost like you built without support for large files? I assume you are on a 32bit system?

Can you paste your cmake build log?

**Comment by neheb** [comment]
No the issue is with this version of libstdc++, std::filesystem doesn't support largefile on 32-bit. This bug was fixed with libstdc++ 8.4.

**Comment by whyman** [comment]
Ah, okay, not much we can do about that then, you could perhaps try a clang/libc++ build to avoid that problem?

I guess we need to check this broken case in cmake.

**Comment by neheb** [comment]
It's not a clang or gcc problem. It's the libstdc++. I could compile gerbera with libcxx, but then there are issues with linking the other libraries which use libstdc++.

**Comment by neheb** [comment]
Related: https://github.com/gerbera/gerbera/issues/737

**Comment by neheb** [comment]
Just reported to Debian. Hope they fix it.

**Comment by whyman** [comment]
@neheb's bug report is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=985385

**Comment by ItsMeMarc** [comment]
I updated my 32-bit Raspbian operating system with the latest Gerbera version and now I have the same problem again as @neheb. I reported such an error about one year ago (#737). Is there a way to use the previous workaround from https://github.com/gerbera/gerbera/pull/746 again? I think Debian will need longer to fix it.
Thank you.

**Comment by neheb** [comment]
https://github.com/gerbera/gerbera/pull/1323 fixes it.

**Comment by ItsMeMarc** [comment]
Thanks @neheb, I give it a try.

**Comment by ItsMeMarc** [comment]
@neheb : When I look on #1132 I see the following message: "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." 
Is there any easy possibility to download the workaround using git, as it doesn't belong to any branch?

**Comment by neheb** [comment]
Use

```
curl https://patch-diff.githubusercontent.com/raw/gerbera/gerbera/pull/1323.patch | git am
```

if you can't figure it out.

**Comment by ItsMeMarc** [comment]
@neheb: Thanks.

It works now, though the log says: 
`2021-03-31 16:10:19.493  error: [content_manager.cc:1281] createObjectFromFile(): File or directory cannot be read: /home/pi/Video/Folder1/Video8.mkv (Value too large for defined data type)`

**Comment by neheb** [comment]
No idea. All I know is files larger than 2GB work for me locally.

**Comment by neheb** [comment]
I don't get that warning.

**Comment by whyman** [comment]
> Are you using JS layout or built-in @neheb ?

Because it may occur on one not the other, if @ItsMeMarc is using the other option to yourself.

**Comment by ItsMeMarc** [comment]
If it helps, here is an excerpt from the log file.
But as already written, it works even if an error is displayed.
[gerbera-21031-1610_cut.log](https://github.com/gerbera/gerbera/files/6244131/gerbera-21031-1610_cut.log)

**Comment by KarlStraussberger** [comment]
I'm quite sure the reason is `dirEnt.file_size()` which is the core of the problem: the data type in too small for large files. As soon as dirEnt is constructed `directory_entry` tries to populate its properties. Altough the patch bypasses the effective issue, it still calls the constructor. We hope for the bug to be fixed instead of working around.

**Comment by neheb** [comment]
There seems to be no progress on that. I don't think debian really cares honestly.

**Comment by mbawiec** [comment]
Same problem here  :(


Gerbera UPnP Server v1.9.0-67-g2677c0e5
Copyright 2016-2021 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_MAGIC=1
WITH_MYSQL=0
WITH_CURL=1
WITH_INOTIFY=YES
WITH_JS=1
WITH_TAGLIB=1
WITH_AVCODEC=1
WITH_FFMPEGTHUMBNAILER=0
WITH_EXIF=1
WITH_EXIV2=NO
WITH_SYSTEMD=YES
WITH_LASTFM=0
WITH_DEBUG=YES
WITH_TESTS=NO

Git info:
-------------
Git Branch: refs/heads/master
Git Commit: 2677c0e519bf5a41e246fe0039f351609010da1b


error: monitorUnmonitorRecursive: Failed to iterate /home/pi/gdrive-media, Value too large for defined data type
error: _rescanDirectory: Failed to iterate /home/pi/gdrive-media, Value too large for defined data type
error: monitorUnmonitorRecursive: Failed to iterate /home/pi/gdrive-media, Value too large for defined data type
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Aborted


Scanned directory /home/pi/gdrive-media is mounted by rclone (google drive), so this is why vary then system file system.

Any hope for fix?

**Comment by whyman** [comment]
Perhaps try a docker container? It will contain different more modern libstdc++

**Comment by neheb** [comment]
FWIW Debian 111 is out now. It does not have these problems.

**Comment by KarlStraussberger** [comment]
@mbawiec "Normally" the issue only is with single files. If your problem is with the whole directory, the reason may be the number of files in the directory or missing permissions for the gerbera process to access the mounted content. Anyway it's an issue in the distro and beyond our reach.

**Comment by mbawiec** [comment]
Ok., thanks very much for your investigation and time.
