### ISSUE TITLE
Gerbera gets killed when ran as a systemd user service

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1321]
Recent systemd behavior is to kill all user sessions upon logout. There's a way to avoid that by using some systemd APIs supposedly. GNU Screen for example does not get killed upon logout. That's the workaround I currently use.

**Comment by whyman** [comment]
Run gerbera as a system service? See: https://docs.gerbera.io/en/stable/daemon.html

**Comment by neheb** [comment]
That's one solution. I run gerbera under --user as it makes it easier to recover when my OS gets hosed (has happened before).

**Comment by whyman** [comment]
Fair enough. Sounds like a systemd configuration issue rather than a Gerbera one. If you come up with a nice solution, a PR to add it to the docs is always appreciated.
