### ISSUE TITLE
error: LibUPnP error code: -121

### ISSUE THREAD

**Issue by phi-whiterabbit** [gerbera/gerbera#1324]
Since i updated from gerbera 1.6.4 to 1.7.0 i am observing sporadic failures when starting gerbera. The following log info is contained in my journal when startup fails:

Mar 17 07:07:58 futro gerbera[287]: 2021-03-17 07:07:58   info: About to migrate metadata from mt_cds_object to mt_metadata                                            Mar 17 07:07:58 futro gerbera[287]: 2021-03-17 07:07:58   info: No data will be removed from mt_cds_object                                                             Mar 17 07:07:58 futro gerbera[287]: 2021-03-17 07:07:58   info: Migrated metadata - object count: 0                                                                    Mar 17 07:07:58 futro gerbera[287]: 2021-03-17 07:07:58   info: Loading 0 configuration items from database                                                            Mar 17 07:07:58 futro gerbera[287]: 2021-03-17 07:07:58   info: Initialising libupnp with interface: '', port: 0
Mar 17 07:07:58 futro gerbera[287]: 2021-03-17 07:07:58  error: LibUPnP error code: -121
Mar 17 07:07:58 futro gerbera[287]: 2021-03-17 07:07:58  error: UpnpUnRegisterClient failed (-116)
Mar 17 07:07:58 futro gerbera[287]: 2021-03-17 07:07:58  error: UpnpUnRegisterRootDevice failed (-116)

With gerbera 1.6.4 i have never observed this issue.

I am using archlinux and libupnp-1.14.2.

**Comment by phi-whiterabbit** [comment]
I have successfully used the very same version of libupnp with gerbera 1.6.4, where everything works AS expected.

**Comment by whyman** [comment]
This is quite strange. -121 is `UPNP_E_INVALID_INTERFACE`

Can you run with `--debug` is will show what we pass to `UpnpInit2`

**Comment by phi-whiterabbit** [comment]
Well i can try. As i said this is not exactly reproducible. Most of the time gerbera starts successfully. Only sometimes it does not work.
Could this be something that systemd just has not fully started the interface yet?

**Comment by whyman** [comment]
Yes, it would make difference. Libupnp expects to find the interface ready and capable of multicast when we initialise it.

**Comment by phi-whiterabbit** [comment]
With --debug the amount of logging is quite excessive. What do you want me to look for?

**Comment by phi-whiterabbit** [comment]
Nevermind. There is not much left If gerbera fails.


Mar 21 07:37:06 futro gerbera[288]: 2021-03-21 07:37:06  debug: [sql_database.cc:2205] doMetadataMigration(): mt_cds_object rows having metadata: 0                    Mar 21 07:37:06 futro gerbera[288]: 2021-03-21 07:37:06  debug: [sqlite_database.cc:346] select(): Adding select to Queue: SELECT COUNT(*) FROM "mt_metadata"          Mar 21 07:37:06 futro gerbera[288]: 2021-03-21 07:37:06  debug: [sql_database.cc:2212] doMetadataMigration(): mt_metadata rows having metadata: 346685                 Mar 21 07:37:06 futro gerbera[288]: 2021-03-21 07:37:06   info: [sql_database.cc:2219] doMetadataMigration(): About to migrate metadata from mt_cds_object to mt_metad>Mar 21 07:37:06 futro gerbera[288]: 2021-03-21 07:37:06   info: [sql_database.cc:2220] doMetadataMigration(): No data will be removed from mt_cds_object               Mar 21 07:37:06 futro gerbera[288]: 2021-03-21 07:37:06  debug: [sqlite_database.cc:346] select(): Adding select to Queue: SELECT "id" FROM "mt_cds_object" WHERE "met>Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07   info: [sql_database.cc:2236] doMetadataMigration(): Migrated metadata - object count: 0
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sqlite_database.cc:346] select(): Adding select to Queue: SELECT DISTINCT "item","key","item_value",">Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sql_database.cc:1608] getConfigValues(): loading 0 items                                              Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07   info: [config_manager.cc:1345] updateConfigFromDatabase(): Loading 0 configuration items from database
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sql_database.cc:1667] updateAutoscanList(): setting persistent autoscans untouched - scanmode: timed; Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sqlite_database.cc:363] exec(): Adding query to Queue: UPDATE "mt_autoscan" SET "touched"=0 WHERE "pe>Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sqlite_database.cc:614] run(): UPDATE "mt_autoscan" SET "touched"=0 WHERE "persistent"=1 AND "scan_mo>Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sql_database.cc:1678] updateAutoscanList(): updating/adding persistent autoscans (count: 0)
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sqlite_database.cc:363] exec(): Adding query to Queue: DELETE FROM "mt_autoscan" WHERE "touched"=0 AN>Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sqlite_database.cc:614] run(): DELETE FROM "mt_autoscan" WHERE "touched"=0 AND "scan_mode"='timed'
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [sqlite_database.cc:346] select(): Adding select to Queue: SELECT "a"."id","a"."obj_id","a"."scan_leve>Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [server.cc:90] run(): start
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07   info: [server.cc:106] run(): Initialising libupnp with interface: '', port: 0
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  error: [main.cc:342] main(): LibUPnP error code: -121
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [server.cc:240] emptyBookmark(): Clearing bookmark file at: /etc/gerbera/gerbera.html                  Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [server.cc:262] shutdown(): Server shutting down
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  error: [server.cc:266] shutdown(): UpnpUnRegisterClient failed (-116)                                         Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  error: [server.cc:271] shutdown(): UpnpUnRegisterRootDevice failed (-116)
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [server.cc:278] shutdown(): now calling upnp finish                                                    Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [content_manager.cc:298] shutdown(): start
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [content_manager.cc:300] shutdown(): updating last_modified data for autoscan in database...
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [content_manager.cc:336] shutdown(): signalling...                                                     Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  debug: [content_manager.cc:339] shutdown(): waiting for thread...

**Comment by whyman** [comment]
So, as we suspected, Gerbera is doing nothing fancy here:

```
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07   info: [server.cc:106] run(): Initialising libupnp with interface: '', port: 0
Mar 21 07:37:07 futro gerbera[288]: 2021-03-21 07:37:07  error: [main.cc:342] main(): LibUPnP error code: -121
```

We ask libupnp do pick the interface and port, so, clearly something is going wrong there.

I guess we could add some retry logic in there, or query the interfaces ourselves to see if they are ready, but ideally libupnp would handle this for us :thinking:

**Comment by phi-whiterabbit** [comment]
I will try for a couple of days whether using After=network-online.target instead of After=network.target makes any difference.

**Comment by phi-whiterabbit** [comment]
Yes, it makes a difference. Now i am sometimes getting the following error:

Mar 22 05:00:27 futro gerbera[309]: 2021-03-22 05:00:27   info: About to migrate metadata from mt_cds_object to mt_metadata                                            Mar 22 05:00:27 futro gerbera[309]: 2021-03-22 05:00:27   info: No data will be removed from mt_cds_object                                                             Mar 22 05:00:28 futro gerbera[309]: 2021-03-22 05:00:28   info: Migrated metadata - object count: 0                                                                    Mar 22 05:00:28 futro gerbera[309]: 2021-03-22 05:00:28   info: Loading 0 configuration items from database
Mar 22 05:00:28 futro gerbera[309]: 2021-03-22 05:00:28   info: Initialising libupnp with interface: '', port: 0
Mar 22 05:00:28 futro gerbera[309]: 2021-03-22 05:00:28  error: LibUPnP could not bind to socket.
Mar 22 05:00:28 futro gerbera[309]: 2021-03-22 05:00:28   info: Please check if another instance of Gerbera or                                                         Mar 22 05:00:28 futro gerbera[309]: 2021-03-22 05:00:28   info: another application is running on port TCP 0 or UDP 1900.                                              Mar 22 05:00:28 futro gerbera[309]: 2021-03-22 05:00:28  error: UpnpUnRegisterClient failed (-116)

Strange.

**Comment by whyman** [comment]
Interesting, we should update our systemd unit file in this case.

Seems we are still getting: `UPNP_E_SOCKET_BIND` back from the library :-1:

**Comment by whyman** [comment]
@phi-whiterabbit If possible, could you try the patch in https://github.com/gerbera/gerbera/pull/1337? Thanks!

**Comment by phi-whiterabbit** [comment]
@whyman: Sure i will try. I revert to After=network target then.

**Comment by phi-whiterabbit** [comment]
Is it ok if a try to apply the patch against 1.7.0 release, or does this depend on something that has been introduced in branch master since 1.7.0?

**Comment by phi-whiterabbit** [comment]
> Is it ok if a try to apply the patch against 1.7.0 release, or does this depend on something that has been introduced in branch master since 1.7.0?
I just give it a try.

**Comment by phi-whiterabbit** [comment]
> > Is it ok if a try to apply the patch against 1.7.0 release, or does this depend on something that has been introduced in branch master since 1.7.0?
> 
> I just give it a try.

Nah. Won't work. It seems i have to checkout your branch and try to build that one. Might take a day or two. Please bear with me.

**Comment by phi-whiterabbit** [comment]
OK, now i am really confused. Now i am getting:

Mar 22 19:54:38 futro gerbera[297]: 2021-03-22 19:54:38   info: Gerbera UPnP Server v1.7.0-50-gaf73956c - http://gerbera.io/                                           Mar 22 19:54:38 futro gerbera[297]: 2021-03-22 19:54:38   info: Copyright 2016-2021 Gerbera Contributors.                                                              Mar 22 19:54:38 futro gerbera[297]: 2021-03-22 19:54:38   info: Gerbera is free software, covered by the GNU General Public License version 2                          Mar 22 19:54:38 futro gerbera[297]: 2021-03-22 19:54:38   info: Loading configuration from: /etc/gerbera/config.xml                                                    Mar 22 19:54:38 futro gerbera[297]: 2021-03-22 19:54:38   info: Checking configuration...                                                                              Mar 22 19:54:38 futro gerbera[297]: 2021-03-22 19:54:38   info: Configuration check succeeded

snip...

Mar 22 19:54:39 futro gerbera[297]: 2021-03-22 19:54:39   info: About to migrate metadata from mt_cds_object to mt_metadata                                            Mar 22 19:54:39 futro gerbera[297]: 2021-03-22 19:54:39   info: No data will be removed from mt_cds_object                                                             Mar 22 19:54:39 futro gerbera[297]: 2021-03-22 19:54:39   info: Migrated metadata - object count: 0                                                                    Mar 22 19:54:39 futro gerbera[297]: 2021-03-22 19:54:39   info: Loading 0 configuration items from database                                                            Mar 22 19:54:39 futro gerbera[297]: 2021-03-22 19:54:39   info: Initialising libupnp with interface: <unset>, port: <unset>
Mar 22 19:54:39 futro gerbera[297]: 2021-03-22 19:54:39 warning: UPnP Init failed: UPNP_E_INVALID_INTERFACE (-121). Retrying in 1 seconds..

snip...

Mar 22 19:54:41 futro gerbera[297]: 2021-03-22 19:54:41 warning: UPnP Init failed: UPNP_E_SOCKET_BIND (-203). Retrying in 2 seconds..

snip...

Mar 22 19:54:43 futro gerbera[297]: 2021-03-22 19:54:43 warning: UPnP Init failed: UPNP_E_SOCKET_BIND (-203). Retrying in 3 seconds...
Mar 22 19:54:46 futro gerbera[297]: 2021-03-22 19:54:46   info: IPv4: Server bound to: 192.168.1.7:49152                                                               Mar 22 19:54:46 futro gerbera[297]: 2021-03-22 19:54:46   info: IPv6: Server bound to: fe80::1e1b:dff:fefc:2a79:49152                                                  Mar 22 19:54:46 futro gerbera[297]: 2021-03-22 19:54:46   info: IPv6 ULA/GLA: Server bound to: fd0b:cf8c:f107:0:1e1b:dff:fefc:2a79:49153                               Mar 22 19:54:46 futro gerbera[297]: 2021-03-22 19:54:46   info: Loading autoscan location: /home/gast/Music; recursive: true, last_modified: 2021-03-20 21:18:30       Mar 22 19:54:46 futro gerbera[297]: 2021-03-22 19:54:46   info: Loading autoscan location: /home/gast/Videos; recursive: true, last_modified: 2021-01-17 22:18:55      Mar 22 19:54:46 futro gerbera[297]: 2021-03-22 19:54:46   info: Loading autoscan location: /home/gast/Pictures; recursive: true, last_modified: 2020-12-20 08:47:28
Mar 22 19:54:46 futro gerbera[297]: 2021-03-22 19:54:46   info: The Web UI can be reached by following this link: http://192.168.1.7:49152/

**Comment by phi-whiterabbit** [comment]
So everything looks fine as if the retry logic just works.
BUT: Once i try to access gerbera via the webui or via a upnp client like VLC, it is completely dead and does not respond.

**Comment by phi-whiterabbit** [comment]
Despite the different log messages, this is the same behavior that i have seen without the patch.

Fwiw: If i try to stop gerbera then using "systemctl stop gerbera", then it does not react. The command seems to hang. I have to execute systemctl kill gerbera twice before it is really gone. This also ist the same with and without the patch.
Here is the respective log:

Mar 22 20:35:01 futro gerbera[297]: 2021-03-22 20:35:01   info: Gerbera shutting down. Please wait...                                                                  Mar 22 20:35:01 futro systemd[1]: Stopping Gerbera Media Server..

snip...

Mar 22 20:35:12 futro systemd[1]: gerbera.service: Sent signal SIGTERM to main process 297 (gerbera) on client request.                                                Mar 22 20:35:12 futro gerbera[297]: 2021-03-22 20:35:12   info: Gerbera still shutting down, signal again to kill.                                                     Mar 22 20:35:21 futro gerbera[297]: 2021-03-22 20:35:21  error: Clean shutdown failed, killing Gerbera!                                                                Mar 22 20:35:21 futro systemd[1]: gerbera.service: Sent signal SIGTERM to main process 297 (gerbera) on client request.                                                Mar 22 20:35:22 futro systemd[1]: gerbera.service: Main process exited, code=exited, status=1/FAILURE                                                                  Mar 22 20:35:22 futro systemd[1]: gerbera.service: Failed with result 'exit-code'.                                                                                     Mar 22 20:35:22 futro systemd[1]: Stopped Gerbera Media Server.

**Comment by phi-whiterabbit** [comment]
I can do the following: I build gerbera 1.6.4 and Check again whether the issue occurs/does mit occur with that version of gerbera.
Then we know at least whether this is a regression of gerbera or whether it is caused by some change in another part of the software stack that gerbera is using.

**Comment by neheb** [comment]
You could try building with npupnp instead.

**Comment by phi-whiterabbit** [comment]
> You could try building with npupnp instead.

Thanks, i will try that.

**Comment by phi-whiterabbit** [comment]
> I can do the following: I build gerbera 1.6.4 and check again whether the issue occurs/does not occur with that version of gerbera.
> Then we know at least whether this is a regression of gerbera or whether it is caused by some change in another part of the software stack that gerbera is using.

Hm. I did that and the same error also occurs with gerbera-1.6.4. Maybe this is some update of systemd (was updated from 247.3 to 247.4 in the time frame where i started seeing the issue). I am using systemd-networkd.

**Comment by phi-whiterabbit** [comment]
Now i am trying whether libnpupnp makes the difference.

**Comment by phi-whiterabbit** [comment]
> Now i am trying whether libnpupnp makes the difference.

It seems that the issue is gone If i use libnpupnp.

**Comment by phi-whiterabbit** [comment]
OK, the issue is really gone. So i think it is the fault of libupnp or gerbera uses it in a wrong way. So from my side this issue can be closed. But maybe you want to keep it to track this strange behavior? So i leave it up to you guys to decide.

Fwiw: In the logs there now is a considerable time delay between these two log messages:

```
Mar 25 14:09:07 futro gerbera[296]: 2021-03-25 14:09:07   info: Initialising libupnp with interface: '', port: 0
Mar 25 14:09:11 futro gerbera[296]: 2021-03-25 14:09:11   info: Initialized port: 49152
```

**Comment by phi-whiterabbit** [comment]
Btw.: The unit retry logic seems to be the right path in my humble opinion (except the compile issue when using libnpupnp), but there is this issue of gerbera not responding to any requests or signals afterwards.
If you want me to try something out there, then i will do so If i can.

**Comment by whyman** [comment]
I am keen to understand the problem with libupnp, ideally. I dont think its a Gerbera specific issue, but the vast majority of Gerbera users will be using it libupnp, so it is good to help fix up libupnp if possible.

I guess I will have to take a look at npupnp and see if we can "backport" the fixes to libupnp. It is interesting the delay that you spotted.

There is no great way to get more info out of libupnp either at the moment, so thats not helpful.

re: the compilation problem, its because we call a method that was added recently to libupnp (and not yet npupnp) I have opened an issue: https://framagit.org/medoc92/npupnp/-/issues/13, but we can an add an ifdef for now.

**Comment by phi-whiterabbit** [comment]
> I am keen to understand the problem with libupnp, ideally. I dont think its a Gerbera specific issue, but the vast majority of Gerbera users will be using it libupnp, so it is good to help fix up libupnp if possible.
> 
> I guess I will have to take a look at npupnp and see if we can "backport" the fixes to libupnp. It is interesting the delay that you spotted.
> 

Yeah, i thought maybe libnpupnp already implements something like a retry logic.

**Comment by phi-whiterabbit** [comment]
One more experiment: I am using archlinux and libupnp is compiled with default settings there, so without the options
```
--enable-reuseaddr
--disable-blocking-tcp-connections
```
that are recommended by gerbera. So i compiled my own version of libupnp with these options.

Result: The issue remains. There is one difference in behavior though: Instead of just not responding, gerbera now does not respond AND consumes CPU time as crazy.
