### ISSUE TITLE
Where is the Notify inteval option?

### ISSUE THREAD

**Issue by joan-carles** [gerbera/gerbera#1333]
I checked documentation. But I really Can't find what I will ask

When I switch on the TV I wait long time and my TV is not able to detect there is a DLNA server. If I restart the server Gerbera then Automatically and instantly detects there is Gerbera because I guess gerbera notifies-broadcast is there.

Other mediaserver use to have a parameter in the configuration to set the seconds you want.. But I can't find it in Gerbera. I thought was the alive option... but the minimum value I can set is 180 seconds if wait 3 minutes my TV doesn't detect any DLNA server.

If you can help thanks

**Comment by whyman** [comment]
https://docs.gerbera.io/en/latest/config-server.html#alive

**Comment by KarlStraussberger** [comment]
Normally your device sends a discover message on startup. This is answered by gerbera with the same package that it sends in as alive package.

Some devices do not comply with that protocol. 

However, 180 is the minimum alive period defined for UPnP.
