### ISSUE TITLE
media not updating nor removing

### ISSUE THREAD

**Issue by oakes8585** [gerbera/gerbera#1334]
System:    Host: oakes-desktop Kernel: 4.15.0-137-generic i686 bits: 32 compiler: gcc v: 7.5.0 
           Desktop: Cinnamon 4.2.4 wm: muffin dm: LightDM Distro: Linux Mint 19.2 Tina 
           base: Ubuntu 18.04 bionic 
Machine:   Type: Desktop Mobo: N/A model: 775i65G. serial: <filter> BIOS: American Megatrends 
           v: P3.00 date: 03/20/2007 
CPU:       Topology: Single Core model: Intel Celeron D bits: 64 type: MCP arch: Netburst Presler 
           rev: 5 L2 cache: 512 KiB 
           flags: lm nx pae sse sse2 sse3 bogomips: 6391 
           Speed: 3196 MHz min/max: N/A Core speed (MHz): 1: 3196 
Graphics:  Device-1: Intel 82865G Integrated Graphics vendor: ASRock driver: i915 v: kernel 
           bus ID: 00:02.0 chip ID: 8086:2572 
           Display: x11 server: X.Org 1.19.6 driver: intel unloaded: fbdev,modesetting,vesa 
           resolution: 1280x1024~60Hz 
           OpenGL: renderer: Mesa DRI Intel 865G x86/MMX/SSE2 v: 1.3 Mesa 20.0.8 
           direct render: Yes 
Audio:     Device-1: Intel 82801EB/ER AC97 Audio vendor: ASRock driver: snd_intel8x0 v: kernel 
           bus ID: 00:1f.5 chip ID: 8086:24d5 
           Sound Server: ALSA v: k4.15.0-137-generic 
Network:   Device-1: Realtek RTL-8100/8101L/8139 PCI Fast Ethernet Adapter vendor: ASRock 
           driver: 8139too v: 0.9.28 port: b800 bus ID: 01:05.0 chip ID: 10ec:8139 
           IF: enp1s5 state: unknown speed: 100 Mbps duplex: full mac: <filter> 
           IF-ID-1: tun0 state: unknown speed: 10 Mbps duplex: full mac: N/A 
Drives:    Local Storage: total: 990.67 GiB used: 166.45 GiB (16.8%) 
           ID-1: /dev/sda vendor: Seagate model: ST1000DM003-1CH162 size: 931.51 GiB 
           speed: <unknown> serial: <filter> 
           ID-2: /dev/sdb type: USB model: Walgreen Infinitive size: 59.16 GiB serial: <filter> 
Partition: ID-1: / size: 914.21 GiB used: 151.09 GiB (16.5%) fs: ext4 dev: /dev/dm-1 
           ID-2: /boot size: 703.5 MiB used: 142.4 MiB (20.2%) fs: ext4 dev: /dev/sda1 
           ID-3: swap-1 size: 976.0 MiB used: 355.0 MiB (36.4%) fs: swap dev: /dev/dm-2 
Sensors:   Message: No sensors data was found. Is sensors configured? 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/additional-repositories.list 
           1: deb https: //dl.bintray.com/gerbera/gerbera bionic main
           Active apt repos in: /etc/apt/sources.list.d/mikhailnov-pulseeffects-bionic.list 
           1: deb http: //ppa.launchpad.net/mikhailnov/pulseeffects/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/nilarimogard-webupd8-bionic.list 
           1: deb http: //ppa.launchpad.net/nilarimogard/webupd8/ubuntu bionic main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com tina main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu bionic main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ bionic partner
Info:      Processes: 181 Uptime: 1h 38m Memory: 988.7 MiB used: 558.5 MiB (56.5%) Init: systemd 
           v: 237 runlevel: 5 Compilers: gcc: 7.5.0 alt: 7 Client: Unknown python3.6 client 
           inxi: 3.0.32 

SO before i post the main issues i just wanna say i have more ram on the way........

this pc was put together from random layin parts in the house

ok so........

i am running transmission as a client download interface headless and gerbera as a media server but after looking at the config unless im missing something i cant find a update interval for added media or removed.......

i have removed a media file and it is still showing when i connect to the media server even though it is non existent also i have 44 files in the dir of the media server and it is only showing about 11 in one dir of the media server the sub dir has 33 movies itself but as i said it is not sowing on ANY device through the house so what must i do to fix this problem?

**Comment by whyman** [comment]
Is Gerbera server running?

How did you add the directory? If via the UI did you add it as an autoscan?

**Comment by oakes8585** [comment]
i added the dir via ui and uppp how do i enable autoscan?
