### ISSUE TITLE
1.8.0 Release Tracker

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#1338]
Mostly will contain fixes for #1272, but there is also a bunch of other stuff including the lovely work by @dyseg on the Samsung bookmark handling (#1288)

**Comment by neheb** [comment]
The latter introduces unused variable warnings.

**Comment by whyman** [comment]
No warnings in the CI? https://github.com/gerbera/gerbera/runs/2165393611

**Comment by neheb** [comment]
Pass WITH_DEBUG=FALSE
