### ISSUE TITLE
Renaming file during import

### ISSUE THREAD

**Issue by stoinov** [gerbera/gerbera#1340]
Using fresh docker installation of 1.7.0 on arm64.

I am wondering if there is a way to change the title of a file being added?
I've setup my own custom script that changed the container structure, but I want to shorten some of the filenames to be more readable in the list.

I tried the obvious `obj.title.replace('Long part of the title', 'Short')` in the script just before `addCdsObject` but this didn't work for me.

**Comment by KarlStraussberger** [comment]
replace does not do inplace update. Your code should look like this: 
`obj.title = obj.title.replace('Long part of the title', 'Short');`

**Comment by stoinov** [comment]
Of course... that's what you get for writing code in 4AM in a language you haven't used in year(s) 😄
