### ISSUE TITLE
Discrepancy when importing by hand or automatically

### ISSUE THREAD

**Issue by stoinov** [gerbera/gerbera#1341]
I've made my custom script to change the container structure but I think this also happened by default. When the video files are imported automatically, they get put in a two level path, while if I remove and reimport them manually, they are put only in a one level path. I am monitoring the `video` and `series` folders separately. Example:

**File system**
```
media
   ├─ video
   │    └─ folder1
   │          └─ file1.mkv
   └─ series
        └─ folder2
              └─ file2.mkv
```
**Database autoimport**
```
   ┌─ video
   │    └─ folder1
   │          └─ file1.mkv
   └─ series
        └─ folder2
              └─ file2.mkv
```
**Database manual import**
```
   ┌─ folder1
   │     └─ file1.mkv
   └─ folder2
         └─ file2.mkv
```
I suspect this has something to do with my lack of understanding of the `getRootPath` function - what is `object_script_path` and where does it get set?

**Comment by stoinov** [comment]
searching for `object_script_path` broght me to [this comment](https://github.com/gerbera/gerbera/issues/386#issuecomment-512972172), that sounds exactly as my issue.

**Comment by KarlStraussberger** [comment]
Just from memory: With autoscan `object_script_path` is set to the autoscan dir. When you import manually it is set to the parent of the dir with the file. The code therefore is somewhere in `src/content/scripting/`.

**Comment by stoinov** [comment]
Thanks, I've went ahead and overwrote `const dir = getRootPath(object_script_path, obj.location);` with this:
`const dir = obj.location.substring(7, obj.location.lastIndexOf('/')).split('/');`
my monitored paths have the same length prefix `/media/` that I can ignore.
