### ISSUE TITLE
Persisting data of Docker container

### ISSUE THREAD

**Issue by fkrivsky** [gerbera/gerbera#1342]
Hi,

Can you advise on how to persist database when running Gerbera in Docker container?

Currently, media needs to be rescanned fron scratch after container restart. 

Thanks.

**Comment by KarlStraussberger** [comment]
You need to mount the database in the same way you mount your media. Easiest way is to mount /etc/gerbera with config.xml and put the database there as well.

**Comment by aleho** [comment]
I'm using two volumes for the container, e.g.:

`gerbera_run:/run/gerbera:rw` where database and config files will be stored, and
`/path/to/media:/content:ro` where content fill be scanned (according to config.xml).

Config file has `<home>/run/gerbera/</home>` under `<server>`, but I think this is the default in newer containers, right?

**Comment by weendigo** [comment]
Thanks, @aleho , that path seems to work for me!

**Comment by whyman** [comment]
Should add something to the docker README for this.
