### ISSUE TITLE
response is nullptr, code -115 for X_GetFeatureList

### ISSUE THREAD

**Issue by aleho** [gerbera/gerbera#1347]
Using git build via docker container `gerbera:master` I'm getting "response is nullptr, code -115 for X_GetFeatureList" for a Samsung TV.

Log output (fresh DB, one file only): [gerbera.log](https://github.com/gerbera/gerbera/files/6214740/gerbera.log)

Related to https://github.com/gerbera/gerbera/issues/352#issuecomment-799314030, hope this helpful.

**Comment by whyman** [comment]
This is correct, we do not handle the X_GetFeatureList call currently. I do not think it should be a requirement for the Samsung bookmark support to work.

**Comment by KarlStraussberger** [comment]
@aleho Can you check that PR on your device, please? I'm not sure about the ids and there is absolutely nothing to be found in the web except some other implementations that do similar stuff.

**Comment by aleho** [comment]
Sorry, I somehow missed your comment.

I haven't seen any errors so far, seems to be running quite well!
