### ISSUE TITLE
Bookmarks not saved on Samsung TV

### ISSUE THREAD

**Issue by aleho** [gerbera/gerbera#1348]
If I'm interpreting #848 correctly, the bookmark feature should be implemented already.

Using git build f3182bc8 via docker container gerbera:master bookmarks are not handled on my Samsung TV.

Database content:
```
427||2|2|object.item.videoItem|big_buck_bunny.mkv|F/content/big_buck_bunny.mkv|3212239177|||0~bitrate=825910&duration=1%3A30%3A54%2E449&nrAudioChannels=6&protocolInfo=http-get%3A%2A%3Avideo%2Fx-matroska%3A%2A&resolution=1280x692&sampleFrequency=48000&size=4504887295~~|6~protocolInfo=http-get%3A%2A%3Aimage%2Fjpeg%3A%2A&resolution=128x69~rh=6~rct=th|0|video/x-matroska|1||||0
428|427|5|2||big_buck_bunny.mkv||||||0|video/x-matroska|513||||0
429|427|8|2||big_buck_bunny.mkv||||||0|video/x-matroska|1||||0
```

Log output (fresh DB, one file only): [gerbera.log](https://github.com/gerbera/gerbera/files/6214756/gerbera.log)

Sorry for the noise if this is caused by #1347, but I didn't want to mix two different issues into one. Hope that's OK for you.

**Comment by dyseg** [comment]
I don't see any call for `ContentDirectoryService::doSamsungBookmark`, which would store the played position into the db. Maybe your TV does not support this?

I only see calls for restoring the bookmark(this is not initiated by the client, but by gerbera if this option is enabled). If you have the opportunity to modify the db content, you could change the column `bookmark_pos` of your media item(id=428) to e.g. 60 to see at least if the restore works or not. If it doesn't work please also try SAMSUNG_BOOKMARK_MSEC. If non of this works, then your client does not support this feature, at least by our current knowledge :|.

**Comment by aleho** [comment]
Yes, that's the strange thing about this log!

I'm am 100% sure the TV does set bookmark calls on 1.7, that's why I even discovered it wasn't implemented before through log output. I didn't see failures related X_GetFeatureList before, so maybe that's related?

I'll try to provide a log from 1.7 container today or tomorrow.

**Comment by kyak** [comment]
I've originally reported #848 and I can tell that it works with gerbera 1.8.0.

I had to add this to config:

```
<clients enabled="yes">
    <client ip="192.168.1.168" flags="SAMSUNG_BOOKMARK_MSEC"></client>
</clients>
```

One thing though. I don't want this quirk to be tied to `ip`. But how do I figure out the `userAgent` string that TV sends to gerbera? I couldn't find any setting for verbose logging or something like that.

**Comment by KarlStraussberger** [comment]
You can go to the clients page in web UI and copy the user agent string or at least significant parts of it. They start with `SEC_HHP_`.
After that you can replace your `ip=...` with `userAgent=...`

**Comment by kyak** [comment]
@KarlStraussberger thanks, it worked. I don't use web UI, but enabled it for that occasion.

**Comment by aleho** [comment]
I cannot reproduce the log output any more. Maybe I just imagined it? Sorry for the spam :(.

Bookmark saving doesn't seem to work on this old UE48H6470 though.
