### ISSUE TITLE
Lack of AAC support causes blank entries

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1373]
This is the case with Debian 10 and Alpine Linux (official Docker images) as ffmpeg is not built with --enable-nonfree .

I'm sure it could be made to work if someone took the time to factor out HE-AAC support from ffmpeg's AAC decoder (LC AAC patents expired). Based on IRC conversations, there seems to be no interest.
![Screenshot_20210407-212856](https://user-images.githubusercontent.com/2918873/113969749-62c2b100-97ea-11eb-9c0e-3d19a8932ceb.png)
![Screenshot_20210407-212935](https://user-images.githubusercontent.com/2918873/113969754-63f3de00-97ea-11eb-8939-a609a36e3040.png)

**Comment by neheb** [comment]
I'm guessing this is some kind of parses issue actually. I don't think gerbera does any decoding.

GStreamer supports demuxing mp4 streams just fine. But adding that to Gerbera is quite a bit of work...

**Comment by whyman** [comment]
If the tree is populated with the tags as expected then its all good from our perspective.

After that we simply serve the files via HTTP, so looks like a client issue to me.

**Comment by neheb** [comment]
Oh the files definitely have tags.

**Comment by whyman** [comment]
Does it work with other clients?

**Comment by neheb** [comment]
Surprisingly....it does. I tested with WIndows and its entry under This PC.

**Comment by whyman** [comment]
Okay, I think its best to close this until you can narrow down what is happening with your client in that case?

**Comment by neheb** [comment]
Hmm I think this is partially a Gerbera problem. Under This PC in Windows, the album shows up and clicking it does have entries but the album art is missing in the Album view. All files have embedded art in them.

**Comment by whyman** [comment]
Any progress on this @neheb?

**Comment by neheb** [comment]
None. I informed Mr. foobar2000 about the issue. I don't see a response.

If I had to guess, it's some taglib problem. I have not debugged it yet. I think @KarlStraussberger uses foobar2000 mobile.

**Comment by KarlStraussberger** [comment]
I've got foobar2000 but I run on openSuSE and only use default MP3 files.

**Comment by neheb** [comment]
Update: it seems foobar2000 mobile had some update that at least made the files playable.

Bad news is that albumart is still missing.

I ran gerbera with the -D option and found out that taglib_handler is not being used at all. Even after renaming the files to .mp4 taglib is not handling them. I have no idea why they're not being identified as mp4.

**Comment by neheb** [comment]
Turns out the mimetype is different. I added a small debug dection:

```
debug: [metadata_handler.cc:76] setMetadata(): mimetype is set to audio/x-m4a
```

I don't see audio/x-m4a anywhere in the codebase. I also see:

```
debug: [metadata_handler.cc:86] setMetadata(): content_type is set to
```

**Comment by neheb** [comment]
yeah... not even /usr/share/mime has such an entry.

**Comment by KarlStraussberger** [comment]
Mimetypes can be set in config.xml. You can also tweak its treatment. See https://docs.gerbera.io/en/stable/config-import.html#mappings

**Comment by neheb** [comment]
> 
> 
> Mimetypes can be set in config.xml. You can also tweak its treatment. See https://docs.gerbera.io/en/stable/config-import.html#mappings

I just checked out libmagic. wow that's horrible. m4a == audio/x-m4a and m4b == audio/mp4 ????

**Comment by KarlStraussberger** [comment]
Just add a matching line to `<mimetype-contenttype>` and it should work

**Comment by neheb** [comment]
Closing since this is not an issue anymore. What is an issue is the album art. But there's https://github.com/gerbera/gerbera/issues/784 for that.
