### ISSUE TITLE
gerbera.jfrog.io repositories are not signed

### ISSUE THREAD

**Issue by twdkeule** [gerbera/gerbera#1374]
When using the jfrog repositories on Ubuntu 20.04 LTS, apt complains: 
```
E: The repository 'https://gerbera.jfrog.io/artifactory/debian focal Release' is not signed.
E: The repository 'https://gerbera.jfrog.io/artifactory/debian-git focal Release' is not signed.
```

**Comment by whyman** [comment]
Hmmm. I _thought_ I had set that up.

**Comment by whyman** [comment]
Okay, this is now fixed.

I had to generate a new signing key, so you will need to run

```curl -fsSL https://gerbera.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -```

To pull the new signing key.

Thanks for reporting :+1:
