### ISSUE TITLE
gerbera 1.8.0 does not compile with libnpupnp

### ISSUE THREAD

**Issue by phi-whiterabbit** [gerbera/gerbera#1377]
When trying to compile gerbera 1.8.0 using -DWITH_NPUPNP=1, then compilation fails with

src/server.cc:139:87: error: ‘UpnpGetServerUlaGuaPort6’ was not declared in this scope; did you mean ‘UpnpGetServerPort6’?                                                                                                                                                                139 | GLA: Server bound to: {}:{}", UpnpGetServerUlaGuaIp6Address(), UpnpGetServerUlaGuaPort6());

I am using libnpupnp-4.0.14.

**Comment by neheb** [comment]
libnpupnp 4.0.20 fixes this.

**Comment by phi-whiterabbit** [comment]
> libnpupnp 4.0.20 fixes this.

Hm?? You mean 4.1.2 isn't it?

**Comment by neheb** [comment]
Yeah. Latest version was specifically made to fix this.

**Comment by phi-whiterabbit** [comment]
I'll give it a try.
However, the cmake dependency should then reflect this, so that things are failing earlier, no?

**Comment by phi-whiterabbit** [comment]
The doc still lists 4.0.11 as minimal version, as well as the CMakeLists.txt. The minimal version of libupnp is incorrect in the doc, but correct in the CMakeLists.txt.

**Comment by neheb** [comment]
PRs welcome :).

**Comment by phi-whiterabbit** [comment]
Gerbera compiles successfully and works for me using libnpupnp-4.1.2.
