### ISSUE TITLE
Browsing Media Library Slow with MySQL

### ISSUE THREAD

**Issue by LinuxUser2017** [gerbera/gerbera#138]
Hello,

I'm noticing a fairly consistent delay when browsing through folders. It can take up to 30 seconds (if I have the patience to wait) for the contents of folders to show.

I am using Mysql on another computer to handle the database. I have found it's doing a 'SELECT 'id' FROM 'mt_cds_object' WHERE ( lower ' ..... etc query while I'm waiting.

Would I be right in saying it's looking for cover images /album art ?

I will do a bit more testing to investigate. Is there any documentation on how to setup a fresh Mysql database for Gerbera ? (I'm using my old mediatomb one). It's ~83 Meg, (Is that too big, or a feasible size to query quickly?)

Thanks,

**Comment by v00d00** [comment]
I will have to set up a MySQL instance to test with, there have been reports of it being slow, but fixes where merged to improve it.

**Comment by v00d00** [comment]
Sqlite has always reported to be fast, though.

**Comment by v00d00** [comment]
@LinuxUser2017 would it possible for you to mail me a mysqldump of your Gerbera DB so I can run some tests? thev00d00 AT gentoo DOT org

**Comment by LinuxUser2017** [comment]
Hello,

To avoid wasting your time, I have setup a fresh database (not a recycled mediatomb database). I willl report my findings once it approaches the same size.

**Comment by LinuxUser2017** [comment]
Hello,

I fired up a fresh Gerbera (populated) database ~40mb.

Took 75 seconds to timeout on showing the media library. (bubble upnp).

Sql query in process:
|  734 | gerbera | securitypi:44172 | gerbera | Query   |   75 | Sending data | SELECT `id` FROM `mt_cds_object` WHERE ( lower(`dc_title`) LIKE 'cover.jp%' OR lower(`dc_title`) LIK |

Also noteworthy mysql is running at 100% CPU usage while this is happening.
Once this query clears the library becomes responsive again.

**Comment by v00d00** [comment]
That is not ideal. Can you send me your DB so I can experiment?

Really we need to re-engineer the artwork stuff entirely, but that is no small task.

**Comment by LinuxUser2017** [comment]
Hello,

I sent you a file 24 Aug.

**Comment by cweiske** [comment]
Can this be closed? That bug is 7 years old, any gerbera internals changed quite a bit over time.
If the problem can be reproduced on a current 2.2.0 gerbera version it can re-opened. Until then it should be closed.

**Comment by KarlStraussberger** [comment]
Good point
