### ISSUE TITLE
Album folder art vanished in 1.8.0

### ISSUE THREAD

**Issue by whorfin** [gerbera/gerbera#1381]
Compared to af73956c304dab1582f713e48384cc6ad9cbf0af, folder art no longer appears.
To elaborate, in clients such as 8player and mobile foobar2000, when viewing "PC Directory" mode, folders would show album art instead of generic "folder" icon when scrolling a list of directories.  Album art could be from "cover.jpg" or the cleverly named "folder.jpg", etc
With 1.8.0, that's gone and only track art seems to show now

Sadface

**Comment by KarlStraussberger** [comment]
That's been part of th 1.7 change already. You have to set [Resources](https://docs.gerbera.io/en/stable/config-import.html#resources) if there are no embedded album covers - which is my preferred way, because you get the cover also if you download the file to your mobile.

But you may be right with Pc directory - need to check that

**Comment by whorfin** [comment]
...it may be worth either elaborating in the docs or changing behavior to address this somewhat surprising behavior:
If one adds any entries via `add-file` to fanart, one has to rebuild the whole damn database
`resource` does not help here - while the file is "added" in a semantic sense, presumably since the database records that the file itself was _not_ newly added to the filesystem, and so does not trigger any directory rescan.
FWIW

**Comment by KarlStraussberger** [comment]
First of all, I just added PR #1394 which brings back container images in `PC Directory`. It now accepts the same setup rules as virtual containers.

Generally, the idea behind the change was to move all logic to the import process (incl. add images to upper levels and virtual containers) - you have to fiddle around a bit before everything is up and running, but it is deterministic and not hard coded anymore. After that browsing just checks the item and serves the data which increases speed especially in large directories like yours. The price we pay for that is that we need to rescan parts of the library to get the data right and sometimes we need to scan more than really necessary to make sure we got the change. It's like a change in the metadata which triggers the whole virtual layout of that file because you do not know what the effect might be. I've got an entry on my to todo-list to reduce the footprint here.

Regarding the documentation, it's like always: The more users complain, the faster it's enhanced. So feel free to share your findings with us.

**Comment by whorfin** [comment]
There's still something not quite right here
I tried a single directory with 110 album folders, each with cover.jpg and no embedded art
Most of them now show PC Directory folder art, but not all.  It is seemingly random
If I go inside the "shows generic folder icon instead" folders, i see album art on the tracks
It seems random but is deterministic -  if i delete the database and rescan, the same set of missing art shows up missing again.  Out of 110 directories in my test, 21 end up with no artwork for the PC Directory folder, though again the art is correctly associated with tracks.
(as an aside - it is _very slow_ in 8player to display the artwork)

I'm including a snippet of `--debug` logging during test database scan; The "[CYAN 005]" folder is the one without folder artwork.  It is surrounded in log by "[CYAN 059]" and "[CYAN 083]" both of which show folder artwork.

**Comment by KarlStraussberger** [comment]
I've seen similar effects which may originate from the scan reading the image file first and so the container tries to read its artwork from that file. I'll run some tests on my potential fix.

**Comment by whorfin** [comment]
That solved it, thank you

**Comment by whorfin** [comment]
OK, not quite
Two issues have cropped up, @KarlStraussberger 

-  With previous gerbera container art in `PC Directory` scenario, a folder which contained no tracks but only fanart, eg folder.jpg or the like, would still get that fanart to show.  This arrangement is typical for multi-disc albums:
artist/album/cd1/...
artist/album/cd2/...
artist/album/folder.jpg (or cover.jpg)
in `PC Directory` mode, gerbera no longer shows fanart for artist/album, but it did previously
- I am guessing this is related to the `resource` tag for "rescan" but am not sure, but am observing that with no `resources` entries, database build took around 12-16 hours, and rescan was less than an hour.  I'm now 14 hours into a rescan [i can tell because 100% of one core CPU]...
and as previously reported, `foobar2000` is unresponsive to large directories when gerbera is scanning or, unfortunately, even rescanning

**Comment by KarlStraussberger** [comment]
The normal way to get artwork for containers is via the media files it contains. If you have extra files, you may use the container setting in resources https://docs.gerbera.io/en/stable/config-import.html#resources. It slows down import a bit, but you should get all the images you want.

Taking the cpu load on scan and rescan into account, it can be expected that all client requests take their time. The same is valid for your changes. Everything is handled in the content thread - sequientially. Maybe we should block requests during high activity.

**Comment by whorfin** [comment]
i have have listed above with my config settings, i have done that
artist/album/cover.jpg   # shows container art for "artist/album" but seems to do so _only if there are media files in artist/album directory_

At the risk of reiterating for clarity, and in all cases this is with `PC Directory` viewing mode:
```
artist/album/cd1/[contains music tracks and cover.jpg]
artist/album/cd2/[contains music tracks and cover.jpg]
artist/album/folder.jpg (or cover.jpg)
```
With the configuration shown above with usage of `resources`, then I see fanart for 
```
artist/album/cd1
artist/album/cd1
```
but i do _not_ see fanart, only generic icon, for
```
artist/album
```
Rescan is at 18 hours and still going; this is much slower than it was before using `resources`, and while I have made changes, they're only on the order of hundreds of tracks. 

As far as this goes:
> Everything is handled in the content thread - sequientially. Maybe we should block requests during high activity.
Please don't block!  Some clients such as `8player` still work during import, and `foobar2000` does too unless the folder contains many subfolders.

**Comment by whorfin** [comment]
> ...also, one more thing although not yet certain:
> perhaps related to the logic above with directories which don't contain tracks [?]
> I have a boxset example where
> artist/boxset/album{1..14}/tracks
> The "boxset" subdir contains nothing but those 14 album directories
> i renamed every one of the album subdirectories before a rescan, and the "boxset" container went away, leaving those sub-albums inaccessible
> Is it possible the "delete missing/inaccessible containers" logic has an oops?
> The scan is still progressing so I suppose it's possible it will come back, I just would have thought all actions related to a given directory level would happen contemporaneously, but perhaps i'm wrong

...well, after 28 hours of full CPU usage on the rescan, which is far longer than the clean scan took, this folder still had not reappeared
I tried to restart it in order to (sigh) delete the database and try yet another fresh scan
It would not stop - it received the signal but did not shut down
I sent another HUP and got this lovely message:
```
2021-04-17 00:38:08   info: Gerbera still shutting down, signal again to kill.
2021-04-17 00:38:08  error: main: error [/home/whorfin/gerbera/gerbera-1.8.0-e947930/src/database/sql_database.cc:1917] _checkOverlappingAutoscans Error: SQL error
```
I think there are still some serious problems with rescans

**Comment by whorfin** [comment]
...and to confirm that, the "scan from scratch" took less than 7 hours
By comparison, the rescan was still going at 28 hours

The good news in all this is that after the fresh scan, gerbera was once again incredibly responsive, `foobar2000` loads gigantic containers very quickly indeed

**Comment by KarlStraussberger** [comment]
I'm glad that your response issues have been resolved.

The Issue isn't with the rescan itself, it's somewhere in SQLite thread: If the thread encounters an (unexpected) error it block and runs in an high speed loop. There may be something wrong with the different locks in the task code, which I do not see at first glance and only pops up at random.

**Comment by whorfin** [comment]
hmm
symptom-wise, while in this "bad rescan" state, CPU usage was not always 100%
it would settle down to a few percent, still too high for normal gerbera quiescent but not indicative of a spin-lock.  after some time, it would revert again to full CPU
the .db file was always slowly growing as well - size increasing, just not very fast
FWIW

**Comment by whorfin** [comment]
Also, I'd greatly appreciate if you could comment on the `PC Directory`  container fanart per above, which seems like a bug unless there is some further setting I am missing or do not understand.

**Comment by KarlStraussberger** [comment]
> 
> 
> Also, I'd greatly appreciate if you could comment on the `PC Directory` container fanart per above, which seems like a bug unless there is some further setting I am missing or do not understand.

Sorry, I simply had no clue this morning.  Now I've been able to fix it which was quite complicated #1411 
- Normally container images are searched in special folder (e.g. with all artist files) -> I added the folder itself
- The search for the image was made for files, so the image can be in parent_directory -> Have to check folder directly

For your configuration: You only have to use `<container>` to get the folder image. The other entries are for media files.

**Comment by whorfin** [comment]
That's great news, thank you!

**Comment by KarlStraussberger** [comment]
> That's great news, thank you!

These rare situations need user's help for detection. Thank you too!

**Comment by whorfin** [comment]
Rescan terminated after 18 hours and still going...
shutdown seemed normal
Something is still amiss with rescan performance, could it be the `<resource>` handling?

**Comment by KarlStraussberger** [comment]
Rescan still suffers from not being able to update exsting entries in virtual tree (we don't know what the result is before running the script). So whenever we have to rescan a file everything belonging to the file has to be deleted before - that's a lot more than just scanning.

Rescanning a file that is covered by `<resource>` patterns leads to rescanning the whole directory (there is no infiniete loop!). In normal situations this is no issue because it's on directory. If your scan was not finished correctly, it is a time issue. I've got an eye on it but no final solution to the dilemma.
