### ISSUE TITLE
server-threads default too aggressive

### ISSUE THREAD

**Issue by whorfin** [gerbera/gerbera#1382]
It looks like a recent change defaults to running threads in system scheduling scope.  If gerbera is not launched as root, at least on my OS config, that results in errors:
```
2021-04-08 15:49:04  error: Could not start thread UpdateThread: Not owner
2021-04-08 15:49:04  error: Could not start thread ContentTaskThread: Not owner
```
...and then gerbera is crippled - rescan doesn't happen, etc

The culprit seems to be a default of "yes" for system-threads; I was able to fix the problem by changing my config.xml with an amended `<system>` declaration:
```
  <server system-threads="no">
```

As running such services as root, or system-privileged user is ... unwise, I would argue that a default of "yes" is needlessly aggressive, and will likely end in tears for many users.  As far as I can tell, it's also a change in behavior, as `pthread_create()` had nullptr attr previously

**Comment by KarlStraussberger** [comment]
It seems an issue on your systems. If we get more similar reports, changing to process mode could be made default. The `attr` is necessary to set the mode, it does no other things.

**Comment by whorfin** [comment]
> The `attr` is necessary to set the mode, it does no other things.

I understand, I just mean that the construction of the `attr` and passing to `pthread_create()` is a change in this version.

**Comment by KarlStraussberger** [comment]
From my reading of https://man7.org/linux/man-pages/man3/pthread_attr_setinheritsched.3.html it is nescessary to enable per thread setting. So I would gladly merge your PR to handle the issue properly.

**Comment by whorfin** [comment]
Note that https://man7.org/linux/man-pages/man3/pthread_attr_setscope.3.html asserts:
```
       POSIX.1 requires that an implementation support at least one of
       these contention scopes.  Linux supports PTHREAD_SCOPE_SYSTEM,
       but not PTHREAD_SCOPE_PROCESS.
```
This would imply that PTHREAD_SCOPE_SYSTEM is already the default?

This little test would appear to confirm that:
```
#include <pthread.h>
#include <cstdio>



int main(int argc, char** argv, char** envp){
    int ihs;

    pthread_attr_t *attr = new pthread_attr_t;
    pthread_attr_init (attr);
    pthread_attr_getinheritsched(attr, &ihs);

    printf("PTHREAD_SCOPE_PROCESS=%d, PTHREAD_SCOPE_SYSTEM=%d; ihs=%d\n", PTHREAD_SCOPE_PROCESS, PTHREAD_SCOPE_SYSTEM, ihs);
}
```

I tried this on both a Linux and Illumos box, and see that while the integer values are different, they both default to PTHREAD_SCOPE_SYSTEM, it would appear
