### ISSUE TITLE
This breaks npupnp support. UPNP_USING_CHUNKED is not implemented.

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#1383]
This breaks npupnp support. UPNP_USING_CHUNKED is not implemented.

_Originally posted by @neheb in https://github.com/gerbera/gerbera/pull/1372#issuecomment-816304768_

**Comment by diizzyy** [comment]
This seems to be fixed upstream

https://framagit.org/medoc92/npupnp/-/issues/15

**Comment by whyman** [comment]
I think this fixed with #1388
