### ISSUE TITLE
docker works, but documentation needs improvement

### ISSUE THREAD

**Issue by divStar** [gerbera/gerbera#1393]
Hi,

thank you for Gerbera! I love it, because it's modern and easy and I have been using it without docker for quite some time. Now that I reinstalled my system though, I decided to go all-docker on most of my server applications. **It took me 4 hours to get the docker image of gerbera to work.**

I have 2 folders I want to share, one containing video and one - music. I already had a gerbera DB, but unfortunately the paths were different (and I did not want to introduce them into the image), so I decided to not repair it using SQLite, but let gerbera re-read a bazillion files instead - that's okay though and my fault / decision.

**I'd like to suggest the following docker-related information to be introduced into the docs; it'll help the not-so-docker-savvy, but who are interested in a clean, upgradable solution for their gerbera server**:
The docker image can have various volumes attached to it. Some may contain configuration and / or database as well as the actual media to share.

Database needs read-write access (`gerbera.db`) and is defined in the `config.xml`.
Configuration needs read-only access and is expected to be in `/run/gerbera`.

You may also specify several folders, which will then be present in `/contant/...` inside the container.

Example call with configuration and database being in a read-write-volume and video and music being in a read-only-volume:
`docker run -d --name gerbera-server --network=host -v /path/to/video:/content/video:ro -v /path/to/music:/content/music:ro -v /home/gerbera/config/:/var/run/gerbera/:rw gerbera/gerbera`

In the example above:
`/path/to/video` is the folder on the host, which contains video files to share,
`/path/to/music` is the folder on the host, which contains music files to share,
`/home/gerbera/config` is the folder on the host, which contains `config.xml` and `gerbera.db`.

**Comment by whyman** [comment]
Hi @divStar

Thanks for the kind words.

Would you be happy to put together a Pull Request with your suggested improvements changes? 

There [README.docker.md](https://github.com/gerbera/gerbera/blob/master/README.Docker.md) if published as the dockerhub README, so perhaps that could be a good place?

**Comment by divStar** [comment]
Hello :),

will do it today or tomorrow (am at work now).

**Comment by divStar** [comment]
I've found another strange behavior. Even though I have forwarded port 49494 through the firewall, it seems I am having trouble connecting (but web-access works). If I turn off the firewall, everything works as expected.

Do I have to only forward this port? And only as TCP or do I need UDP forwarding in it, too?

**Comment by whyman** [comment]
Hey @divStar, you need two ports, 49494/TCP for the data, and 1900/UDP for discovery

https://github.com/gerbera/gerbera/blob/master/README.Docker.md#ports

**Comment by divStar** [comment]
@whyman sorry, it has been a busy week. I saw, that either you added the ports to the documentation or I haven't noticed them when I read it.

The only command I'd add - for those, who do not have a stock configuration file yet:
`sudo docker run -it gerbera/gerbera gerbera --create-config`
where `gerbera/gerbera` is the image and the third `gerbera` is the actual command inside the image along with a parameter (that's how I'd describe it in the `README.Docker.md`).

Actually I am not well-versed in GitHub; I believe in order to make a pull request, I should fork gerbera, do the changes, and then offer a pull request?

Anyway: thank you for your help :)! I'm closing (or trying to close) the issue.

**Comment by whyman** [comment]
> I also want to apologize for not making a pull request as I agreed to. I am not well-versed in GitHub yet; I believe in order to make a pull request, I should fork gerbera, do the changes, and then offer a pull request for merge?

Thats correct, fork, make changes on your copy, then open a pull request to get those changes incorporated.
