### ISSUE TITLE
Gerbera - Unable to browse file system

### ISSUE THREAD

**Issue by geno11x11** [gerbera/gerbera#1399]
I recently installed **Gerbera 1.7.0** on **OpenSuse LEAP 15.2.** 

I have successfully started Gerbera as a service but the UI will not allow me to browse a data drive where my multimedia files reside. The root directory is color orange and will open to a single subdirectory which is locked and is color black. Although there are many, no other subdirectories are listed. I have added Gerbera as a user to a group, and gave group file read/write permissions to the entire tree. 

I have also scoured config.xml for the system-directories tag but I did not find it or anything like it.

Oddly, the UI allows me to browse most (but not all) of the Linux home directory tree. 

So I am locked out of the data drive and not able to add content to the database. I would greatly appreciate your help to solve this issue.

**Comment by whyman** [comment]
Hi @geno11x11!

You are right it sounds like a permissions issue. Could you please post your log file?

**Comment by geno11x11** [comment]
I did some further investigating: The directories that I can browse **(orange color)** and those I cannot **(black color)** have the  **same file permissions**:  

**Owner: Me**       Access: Create & Delete Files
**Group: Users**   Access: Access Files
**Others:**             Access: Access Files

This leads me to suspect the problem might not be a file permissions issue after all.

Attached files:
[gerberalog.txt](https://github.com/gerbera/gerbera/files/6306186/gerberalog.txt)
[log.txt](https://github.com/gerbera/gerbera/files/6306187/log.txt)
![2021-04-13 Gerbera File System Web Page](https://user-images.githubusercontent.com/56106411/114608958-15fc3180-9c53-11eb-87f5-8e04ee699924.png)

Note the drive I need to access is DATA2

**Comment by KarlStraussberger** [comment]
Did you close by accident or is the ussue solved?

In order to access the dir, the gerbera group must also have "x" permission to enter the tree.

Easiest way `chmod -R ugo+rx /data2`. After that you can be sure it's no access issue.

**Comment by geno11x11** [comment]
No, I did not

**Comment by geno11x11** [comment]
Another development: If you compare the UI File System images above, you will note that in the top image the directory **Downloads** is black and inaccessible. In the lower image, it is orange and can be browsed. 

I made no changes to that directory. The only action I took was to delete the DATA2 directory.

**Comment by KarlStraussberger** [comment]
We added an option to 1.8 to define system dirs - i.e. make them invisible or make dirs like `/run` visible.

For 1.7 you have to choose a different mount point or add the autoscan entry to you `config.xml`.

**Comment by geno11x11** [comment]
A different mount point would be problematic.

- 1.7: Pls provide an example of the config.xml autoscan entry or where it can be found in the docs.
- 1.8 was listed as experimental. Is it stable?

Which option do you recommend?

**Comment by whyman** [comment]
We always recommend running the latest code :+1: 

If you do not want to update you can add the path in your configuration file instead of via the UI as mentioned by @KarlStraussberger

Something like

```xml
<autoscan use-inotify="yes">
       <directory location="/path/to/stuff" mode="inotify" level="full" recursive="yes" hidden-files="no"/>
</autoscan>
```

See https://docs.gerbera.io/en/stable/config-import.html?highlight=autoscan

**Comment by geno11x11** [comment]
Great! I'll try 1.8. 

The OpenSuse website only lists 1.7 for download.  GitHub lists six 1.8 varieties but no descriptions for them. How are they different, and which is compatible with OpenSuse 15.2?

1. gerbera_1.8.0-bionic1_amd64.deb
2. gerbera_1.8.0-bullseye1_amd64.deb
3. gerbera_1.8.0-buster1_amd64.deb
4. gerbera_1.8.0-focal1_amd64.deb
5. gerbera_1.8.0-groovy1_amd64.deb
6. gerbera_1.8.0-sid1_amd64.deb

Thanks for your patience.

**Comment by geno11x11** [comment]
In the meantime, I added the autoscan in 1.7. 

Success! Gerbera has imported a large number of mp3 files, I can see them in the UI Database page, and my Denon receiver is happily playing mp3 files as I write this.

Thanks for your help. The only issue I have with 1.7 is with Win7 WMP - It shows the Gerbera UPnP server but no files. Is there a compatibility issue?

**Comment by KarlStraussberger** [comment]
> Great! I'll try 1.8. 
> 
> The OpenSuse website only lists 1.7 for download.  GitHub lists six 1.8 varieties but no descriptions for them. How are they different, and which is compatible with OpenSuse 15.2?
> 
> 1. gerbera_1.8.0-bionic1_amd64.deb
> 2. gerbera_1.8.0-bullseye1_amd64.deb
> 3. gerbera_1.8.0-buster1_amd64.deb
> 4. gerbera_1.8.0-focal1_amd64.deb
> 5. gerbera_1.8.0-groovy1_amd64.deb
> 6. gerbera_1.8.0-sid1_amd64.deb
> 
> Thanks for your patience.

Those are debian packages for different distro versions. It may take some maintainer of the suse package to realize 1.8 is out...

**Comment by KarlStraussberger** [comment]
> In the meantime, I added autoscan in 1.7. 
> 
> Success! Gerbera has imported a large number of mp3 files, I can see them in the UI Database page, and my Denon receiver is happily playing mp3 files as I write this.
> 

Great

> Thanks for your help. The only issue I have with 1.7 is Win7_64 Pro WMP - It shows the Gerbera UPnP server but no files. I have temporarily turned off Windows Firewall for testing. Is there a compatibility issue?
> 

I've got no win7 anymore and you should not use it also. But my Win10 does not show files also - A new task for the next couple of nights...
