### ISSUE TITLE
C++ assumptions

### ISSUE THREAD

**Issue by gburca** [gerbera/gerbera#14]
I wanted to have a bit of an open discussion about what the expectations/directions are for the code base going forward, specifically for this fork. The existing code base contains a number of constructs that are now provided by most modern C++ compilers.

Is it safe to modernize the code base? If so, should it target C++11? C++14?

Many of the utilities in the `zmm` and `hash` directories have more robust cousins in C++11 or later. For example: string, regex, atomic, array, stack, queue, hash, shared pointer. Is it worth transitioning to the standard C++ equivalents over time?

One of the reasons I'm bringing this up is that I've noticed various issues. For example, some song titles are garbled when viewed on the web. Is that due to MediaTomb's String class? Or is it somewhere else in the mp3/flac tags, taglib, internal MT code, iconv, JS scripts, html output chain? Who knows. There's lots of custom string handling code around, and I suspect some of it may be responsible. I'd feel better about it if std::u16string or one of its friends was used to handle user strings.

I've also seen error logging from the hash table code about "maximal number of iterations exceeded". I haven't debugged it, but I'd feel better about it if a standard C++ container was used instead.

That by itself is not enough justification to make massive sweeping changes, but perhaps over time new code can start using std::string, std::stack, etc... instead of the zmm::Foo versions.

**Comment by v00d00** [comment]
> Is it safe to modernize the code base? If so, should it target C++11? C++14?

I think realistically for the project to be sustainable there is no choice but to modernize the codebase. The more standardised the code the more developers will be able to understand it and (hopefully) contribute which is important to keeping the project/fork healthy over time.

Locally I already have `set_property(TARGET mediatomb PROPERTY CXX_STANDARD 14)` in CMakeList.txt - I should probably commit that and add something to the README.

> Many of the utilities in the zmm and hash directories have more robust cousins in C++11 or later. For example: string, regex, atomic, array, stack, queue, hash, shared pointer. Is it worth transitioning to the standard C++ equivalents over time?

Absolutely and I would hope sooner rather than later. Perhaps a good transitionary step would be reimplement those classes as a wrapper of the modern standard equivalents.

> I've also seen error logging from the hash table code about "maximal number of iterations exceeded". I haven't debugged it, but I'd feel better about it if a standard C++ container was used instead.

Me too, I would like to get rid of `zmm` entirely. But that is not a small task!

**Comment by gburca** [comment]
I started updating the synchronization mechanisms defined in `sync.h`. Instead of maintaining the old code as a wrapper, I completely removed it. Here are some old/new samples. If there's an issue with the proposed replacements, let's discuss. These will be difficult to debug if we get it wrong.

```
// old
Ref<Mutex>(new Mutex())
Ref<Mutex>(new Mutex(true))
```
```
// new
std::mutex
std::recursive_mutex
```

For locks that don't have to be unlocked within the defining scope:
`AUTOLOCK(mutex)` became `std::lock_guard<std::mutex> lock(mutex)`.

For locks used with condition variables, or that needed to be unlocked:
```
AUTOLOCK(mutex);
AUTOUNLOCK;
AUTORELOCK;
AUTOLOCK_NOLOCK(mutex);
```
became
```
unique_lock<std::mutex> lock(mutex);
lock.unlock();
lock.lock();
unique_lock<std::mutex> lock(mutex, std::defer_lock);
```

For condition variables:
```
zmm::Cond cv;
cv.signal();
cv.broadcast();
cv.wait();
cv.timedwait();
```
became
```
std::condition_variable cv;
cv.notify_one();
cv.notify_all();
cv.wait(unique_lock);
cv.wait_for(unique_lock);
```

**Comment by v00d00** [comment]
LGTM 👍

**Comment by v00d00** [comment]
Lets close this, its C++14 for now. Replace old stuff `Ref` etc as you touch it.
