### ISSUE TITLE
One definition C++ violations

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1400]
During the linking stage, gerbera seems to fail with GCC10 + gold linker.

Output: https://gist.github.com/neheb/c7af9b3c139dbdb0a99b0ddcd7c52990

**Comment by whyman** [comment]
> name 'CFG_IMPORT_AUTOSCAN_TIMED_LIST' differs from name 'CFG_IMPORT_MAGIC_FILE' defined in another translation unit

Sounds less than ideal.

**Comment by whyman** [comment]
What did you run to get this result? If I set my linker to gold, it links with no warnings...

**Comment by neheb** [comment]
No real idea. I just ran OpenWrt's build system with GCC10.

**Comment by neheb** [comment]
Let's leave this alone.
