### ISSUE TITLE
Segfault if start-up fails

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#1405]
Starting master pointed at an invalid interface ( I used `lo` ) and after upnp init fails, it blows up :boom: 

ContentManager `shutdown()`

Looks like we try access various locks that dont exist because start() was never called :-1:

**Comment by whyman** [comment]
I feel like the `start()` and `shutdown()` methods in the future could be moved to the con/destructors, then we can worry about normal C++ lifecycles

**Comment by KarlStraussberger** [comment]
Normally, it's good practise to separate creation and startup. Especially, as we have quite some cross refs (to e.g. config manager, database).

From my point of view, `Server::run` is far too optimistic that everything go straight - and that method is too big and might be refactored into smaller parts that encapsulate stuff.

**Comment by whyman** [comment]
I dont disagree, but this kind of shows how it could be a lot simpler to combine them. LIke `std::thread` starts the thread in the constructor, and that lets the nice RAII stuff work. You could argue that initialisation should give you a fully functioning object, rather than a half ready shell.

Agreed on the run method, it does a lot of stuff and there is pretty much one error path :shushing_face:

**Comment by KarlStraussberger** [comment]
The best strateg here is, to improve as other changes come in. That's why I start reworking the run method, because I experience random startup failures without notice.
