### ISSUE TITLE
Support for multiple values in import.js script

### ISSUE THREAD

**Issue by imolb** [gerbera/gerbera#1425]
The id3v2.4.0 standard allows multiple values:
https://id3.org/id3v2.4.0-frames, chapter 4.2
```
4.2.   Text information frames

   [...] All text
   information frames supports multiple strings, stored as a null
   separated list, where null is reperesented by the termination code
   for the charater encoding.
```

Calling the tagreader.cpp example from the taglib 1.12 with the mp3 file attached in #1410, it looks like the taglib library also supports the return of multiple values for the RELEASETYPE attribute:

```
/tagreader sample_releasetype_multi.mp3 
******************** "sample_releasetype_multi.mp3" ********************
-- TAG (basic) --
title   - "sample"
artist  - ""
album   - ""
year    - "0"
comment - ""
track   - "0"
genre   - ""
-- TAG (properties) --
RELEASETYPE - "album"
RELEASETYPE - "compilation"
TITLE       - "sample"
-- AUDIO --
bitrate     - 178
sample rate - 44100
channels    - 2
length      - 0:10
```

To support multiple values in the whole database might be a huge issue.
But in a first step I'd appreciate to have access to the multiple values in the import.js script of Gerbera.

But nevertheless thanks for this great software!

**Comment by KarlStraussberger** [comment]
I appreciate your request for the feature in import scripts, but it means we have to invent some way transfering them to and from javascript stored in a crude way internally. I prefer doing things the proper way - add support for multiple values in resources.
