### ISSUE TITLE
Samsung TV - DLNA profile issue

### ISSUE THREAD

**Issue by Smartsmurf** [gerbera/gerbera#1426]
I recently stumbled across a Samsung TV which refused to work with Gerbera, although the UPNP quirks were set up properly.

I activated logging and got this:

X-User-Agent: redsonic
Content-Disposition: attachment; filename="test.mp4"
Accept-Ranges: bytes
CaptionInfo.sec: 
contentFeatures.dlna.org: DLNA.ORG_PN=AVC_MP4_EU;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01200000000000000000000000000000
transferMode.dlna.org: Streaming
5910 (1166): ContentType: 11
5911 (1166): Content-Range start: 0
5912 (1166): Content-Range end: 3706845
5913 (1166): Content-Range total : 3706846
5914 (1166): CaptionUrl:  
5915 (1166): Full syntax of contentFeatures.dlna.org : DLNA.ORG_PN=AVC_MP4_EU;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01200000000000000000000000000000
5916 (1164): **Error: no matched DLNA.ORG_PN!**
5917 (1166): DLNA.ORG_OP:01
5918 (1166): DLNA.ORG_CI:0
5919 (1166): Streaming Mode Flag is set
5920 (1166): HTTP Stalling Flag is set 
5933 (1168):    -- DLNA Read - Read Time : 190

The error is "no matched DLNA.ORG_PN!". A little look into the supported DLNA.ORG_PN (reverse engineered the TV executable) brought up this list (filtered AVC_*):

...
.rodata:01C0C1F0                 DCD aMpeg4H2633gppP_0   ; "MPEG4_H263_3GPP_P3_L10_AMR"
.rodata:01C0C1F4                 DCD aAvcTsMpSdAacMu     ; "AVC_TS_MP_SD_AAC_MULT5"
.rodata:01C0C1F8                 DCD aAvcTsMpSdAacMu_0   ; "AVC_TS_MP_SD_AAC_MULT5_T"
.rodata:01C0C1FC                 DCD aAvcTsMpSdAacMu_1   ; "AVC_TS_MP_SD_AAC_MULT5_ISO"
.rodata:01C0C200                 DCD aAvcTsMpSdHeaac     ; "AVC_TS_MP_SD_HEAAC_L2"
.rodata:01C0C204                 DCD aAvcTsMpSdHeaac_0   ; "AVC_TS_MP_SD_HEAAC_L2_T"
.rodata:01C0C208                 DCD aAvcTsMpSdHeaac_1   ; "AVC_TS_MP_SD_HEAAC_L2_ISO"
.rodata:01C0C20C                 DCD aAvcTsMpSdMpeg1     ; "AVC_TS_MP_SD_MPEG1_L3"
.rodata:01C0C210                 DCD aAvcTsMpSdMpeg1_0   ; "AVC_TS_MP_SD_MPEG1_L3_T"
.rodata:01C0C214                 DCD aAvcTsMpSdMpeg1_1   ; "AVC_TS_MP_SD_MPEG1_L3_ISO"
.rodata:01C0C218                 DCD aAvcTsMpSdAc3       ; "AVC_TS_MP_SD_AC3"
.rodata:01C0C21C                 DCD aAvcTsMpSdAc3T      ; "AVC_TS_MP_SD_AC3_T"
.rodata:01C0C220                 DCD aAvcTsMpSdAc3Is     ; "AVC_TS_MP_SD_AC3_ISO"
.rodata:01C0C224                 DCD aAvcTsMpSdAacLt     ; "AVC_TS_MP_SD_AAC_LTP"
.rodata:01C0C228                 DCD aAvcTsMpSdAacLt_0   ; "AVC_TS_MP_SD_AAC_LTP_T"
.rodata:01C0C22C                 DCD aAvcTsMpSdAacLt_1   ; "AVC_TS_MP_SD_AAC_LTP_ISO"
.rodata:01C0C230                 DCD aAvcTsMpSdAacLt_2   ; "AVC_TS_MP_SD_AAC_LTP_MULT5"
.rodata:01C0C234                 DCD aAvcTsMpSdAacLt_3   ; "AVC_TS_MP_SD_AAC_LTP_MULT5_T"
.rodata:01C0C238                 DCD aAvcTsMpSdAacLt_4   ; "AVC_TS_MP_SD_AAC_LTP_MULT5_ISO"
.rodata:01C0C23C                 DCD aAvcTsMpSdAacLt_5   ; "AVC_TS_MP_SD_AAC_LTP_MULT7"
.rodata:01C0C240                 DCD aAvcTsMpSdAacLt_6   ; "AVC_TS_MP_SD_AAC_LTP_MULT7_T"
.rodata:01C0C244                 DCD aAvcTsMpSdAacLt_7   ; "AVC_TS_MP_SD_AAC_LTP_MULT7_ISO"
.rodata:01C0C248                 DCD aAvcTsMpSdBsac      ; "AVC_TS_MP_SD_BSAC"
.rodata:01C0C24C                 DCD aAvcTsMpSdBsacT     ; "AVC_TS_MP_SD_BSAC_T"
.rodata:01C0C250                 DCD aAvcTsMpSdBsacI     ; "AVC_TS_MP_SD_BSAC_ISO"
.rodata:01C0C254                 DCD aAvcMp4MpSdAacM     ; "AVC_MP4_MP_SD_AAC_MULT5"
.rodata:01C0C258                 DCD aAvcMp4MpSdHeaa     ; "AVC_MP4_MP_SD_HEAAC_L2"
.rodata:01C0C25C                 DCD aAvcMp4MpSdMpeg     ; "AVC_MP4_MP_SD_MPEG1_L3"
.rodata:01C0C260                 DCD aAvcMp4MpSdAc3      ; "AVC_MP4_MP_SD_AC3"
.rodata:01C0C264                 DCD aAvcMp4MpSdAacL     ; "AVC_MP4_MP_SD_AAC_LTP"
.rodata:01C0C268                 DCD aAvcMp4MpSdAacL_0   ; "AVC_MP4_MP_SD_AAC_LTP_MULT5"
.rodata:01C0C26C                 DCD aAvcMp4MpSdAacL_1   ; "AVC_MP4_MP_SD_AAC_LTP_MULT7"
.rodata:01C0C270                 DCD aAvcMp4MpSdAtra     ; "AVC_MP4_MP_SD_ATRAC3plus"
.rodata:01C0C274                 DCD aAvcMp4BlL3lSdA     ; "AVC_MP4_BL_L3L_SD_AAC"
.rodata:01C0C278                 DCD aAvcMp4BlL3lSdH     ; "AVC_MP4_BL_L3L_SD_HEAAC"
.rodata:01C0C27C                 DCD aAvcMp4BlL3SdAa     ; "AVC_MP4_BL_L3_SD_AAC"
.rodata:01C0C280                 DCD aAvcMp4MpSdBsac     ; "AVC_MP4_MP_SD_BSAC"
.rodata:01C0C284                 DCD aAvcTsBlCif30Aa     ; "AVC_TS_BL_CIF30_AAC_MULT5"
.rodata:01C0C288                 DCD aAvcTsBlCif30Aa_0   ; "AVC_TS_BL_CIF30_AAC_MULT5_T"
.rodata:01C0C28C                 DCD aAvcTsBlCif30Aa_1   ; "AVC_TS_BL_CIF30_AAC_MULT5_ISO"
.rodata:01C0C290                 DCD aAvcTsBlCif30He     ; "AVC_TS_BL_CIF30_HEAAC_L2"
.rodata:01C0C294                 DCD aAvcTsBlCif30He_0   ; "AVC_TS_BL_CIF30_HEAAC_L2_T"
.rodata:01C0C298                 DCD aAvcTsBlCif30He_1   ; "AVC_TS_BL_CIF30_HEAAC_L2_ISO"
.rodata:01C0C29C                 DCD aAvcTsBlCif30Mp     ; "AVC_TS_BL_CIF30_MPEG1_L3"
.rodata:01C0C2A0                 DCD aAvcTsBlCif30Mp_0   ; "AVC_TS_BL_CIF30_MPEG1_L3_T"
.rodata:01C0C2A4                 DCD aAvcTsBlCif30Mp_1   ; "AVC_TS_BL_CIF30_MPEG1_L3_ISO"
.rodata:01C0C2A8                 DCD aAvcTsBlCif30Ac     ; "AVC_TS_BL_CIF30_AC3"
.rodata:01C0C2AC                 DCD aAvcTsBlCif30Ac_0   ; "AVC_TS_BL_CIF30_AC3_T"
.rodata:01C0C2B0                 DCD aAvcTsBlCif30Ac_1   ; "AVC_TS_BL_CIF30_AC3_ISO"
.rodata:01C0C2B4                 DCD aAvcTsBlCif30Aa_2   ; "AVC_TS_BL_CIF30_AAC_LTP"
.rodata:01C0C2B8                 DCD aAvcTsBlCif30Aa_3   ; "AVC_TS_BL_CIF30_AAC_LTP_T"
.rodata:01C0C2BC                 DCD aAvcTsBlCif30Aa_4   ; "AVC_TS_BL_CIF30_AAC_LTP_ISO"
.rodata:01C0C2C0                 DCD aAvcTsBlCif30Aa_5   ; "AVC_TS_BL_CIF30_AAC_LTP_MULT5"
.rodata:01C0C2C4                 DCD aAvcTsBlCif30Aa_6   ; "AVC_TS_BL_CIF30_AAC_LTP_MULT5_T"
.rodata:01C0C2C8                 DCD aAvcTsBlCif30Aa_7   ; "AVC_TS_BL_CIF30_AAC_LTP_MULT5_ISO"
.rodata:01C0C2CC                 DCD aAvcTsBlCif30Aa_8   ; "AVC_TS_BL_CIF30_AAC_940"
.rodata:01C0C2D0                 DCD aAvcTsBlCif30Aa_9   ; "AVC_TS_BL_CIF30_AAC_940_T"
.rodata:01C0C2D4                 DCD aAvcTsBlCif30Aa_10  ; "AVC_TS_BL_CIF30_AAC_940_ISO"
.rodata:01C0C2D8                 DCD aAvcMp4BlCif30A     ; "AVC_MP4_BL_CIF30_AAC_MULT5"
.rodata:01C0C2DC                 DCD aAvcMp4BlCif30H     ; "AVC_MP4_BL_CIF30_HEAAC_L2"
.rodata:01C0C2E0                 DCD aAvcMp4BlCif30M     ; "AVC_MP4_BL_CIF30_MPEG1_L3"
.rodata:01C0C2E4                 DCD aAvcMp4BlCif30A_0   ; "AVC_MP4_BL_CIF30_AC3"
.rodata:01C0C2E8                 DCD aAvcMp4BlCif30A_1   ; "AVC_MP4_BL_CIF30_AAC_LTP"
.rodata:01C0C2EC                 DCD aAvcMp4BlCif30A_2   ; "AVC_MP4_BL_CIF30_AAC_LTP_MULT5"
.rodata:01C0C2F0                 DCD aAvcMp4BlL2Cif3     ; "AVC_MP4_BL_L2_CIF30_AAC"
.rodata:01C0C2F4                 DCD aAvcMp4BlCif30B     ; "AVC_MP4_BL_CIF30_BSAC"
.rodata:01C0C2F8                 DCD aAvcMp4BlCif30B_0   ; "AVC_MP4_BL_CIF30_BSAC_MULT5"
.rodata:01C0C2FC                 DCD aAvcMp4BlCif30A_3   ; "AVC_MP4_BL_CIF30_AAC_912"
.rodata:01C0C300                 DCD aAvcMp4BlCif15H     ; "AVC_MP4_BL_CIF15_HEAAC"
.rodata:01C0C304                 DCD aAvcMp4BlCif15A     ; "AVC_MP4_BL_CIF15_AMR"
.rodata:01C0C308                 DCD aAvcTsMpHdAacMu     ; "AVC_TS_MP_HD_AAC_MULT5"
.rodata:01C0C30C                 DCD aAvcTsMpHdAacMu_0   ; "AVC_TS_MP_HD_AAC_MULT5_T"
.rodata:01C0C310                 DCD aAvcTsMpHdAacMu_1   ; "AVC_TS_MP_HD_AAC_MULT5_ISO"
.rodata:01C0C314                 DCD aAvcTsMpHdHeaac     ; "AVC_TS_MP_HD_HEAAC_L2"
.rodata:01C0C318                 DCD aAvcTsMpHdHeaac_0   ; "AVC_TS_MP_HD_HEAAC_L2_T"
.rodata:01C0C31C                 DCD aAvcTsMpHdHeaac_1   ; "AVC_TS_MP_HD_HEAAC_L2_ISO"
.rodata:01C0C320                 DCD aAvcTsMpHdMpeg1     ; "AVC_TS_MP_HD_MPEG1_L3"
.rodata:01C0C324                 DCD aAvcTsMpHdMpeg1_0   ; "AVC_TS_MP_HD_MPEG1_L3_T"
.rodata:01C0C328                 DCD aAvcTsMpHdMpeg1_1   ; "AVC_TS_MP_HD_MPEG1_L3_ISO"
.rodata:01C0C32C                 DCD aAvcTsMpHdAc3       ; "AVC_TS_MP_HD_AC3"
.rodata:01C0C330                 DCD aAvcTsMpHdAc3T      ; "AVC_TS_MP_HD_AC3_T"
.rodata:01C0C334                 DCD aAvcTsMpHdAc3Is     ; "AVC_TS_MP_HD_AC3_ISO"
.rodata:01C0C338                 DCD aAvcTsMpHdAac       ; "AVC_TS_MP_HD_AAC"
.rodata:01C0C33C                 DCD aAvcTsMpHdAacT      ; "AVC_TS_MP_HD_AAC_T"
.rodata:01C0C340                 DCD aAvcTsMpHdAacIs     ; "AVC_TS_MP_HD_AAC_ISO"
.rodata:01C0C344                 DCD aAvcTsMpHdAacLt     ; "AVC_TS_MP_HD_AAC_LTP"
.rodata:01C0C348                 DCD aAvcTsMpHdAacLt_0   ; "AVC_TS_MP_HD_AAC_LTP_T"
.rodata:01C0C34C                 DCD aAvcTsMpHdAacLt_1   ; "AVC_TS_MP_HD_AAC_LTP_ISO"
.rodata:01C0C350                 DCD aAvcTsMpHdAacLt_2   ; "AVC_TS_MP_HD_AAC_LTP_MULT5"
.rodata:01C0C354                 DCD aAvcTsMpHdAacLt_3   ; "AVC_TS_MP_HD_AAC_LTP_MULT5_T"
.rodata:01C0C358                 DCD aAvcTsMpHdAacLt_4   ; "AVC_TS_MP_HD_AAC_LTP_MULT5_ISO"
.rodata:01C0C35C                 DCD aAvcTsMpHdAacLt_5   ; "AVC_TS_MP_HD_AAC_LTP_MULT7"
.rodata:01C0C360                 DCD aAvcTsMpHdAacLt_6   ; "AVC_TS_MP_HD_AAC_LTP_MULT7_T"
.rodata:01C0C364                 DCD aAvcTsMpHdAacLt_7   ; "AVC_TS_MP_HD_AAC_LTP_MULT7_ISO"
.rodata:01C0C368                 DCD aAvcTsBlCif15Aa     ; "AVC_TS_BL_CIF15_AAC"
.rodata:01C0C36C                 DCD aAvcTsBlCif15Aa_0   ; "AVC_TS_BL_CIF15_AAC_T"
.rodata:01C0C370                 DCD aAvcTsBlCif15Aa_1   ; "AVC_TS_BL_CIF15_AAC_ISO"
.rodata:01C0C374                 DCD aAvcTsBlCif15Aa_2   ; "AVC_TS_BL_CIF15_AAC_540"
.rodata:01C0C378                 DCD aAvcTsBlCif15Aa_3   ; "AVC_TS_BL_CIF15_AAC_540_T"
.rodata:01C0C37C                 DCD aAvcTsBlCif15Aa_4   ; "AVC_TS_BL_CIF15_AAC_540_ISO"
.rodata:01C0C380                 DCD aAvcTsBlCif15Aa_5   ; "AVC_TS_BL_CIF15_AAC_LTP"
.rodata:01C0C384                 DCD aAvcTsBlCif15Aa_6   ; "AVC_TS_BL_CIF15_AAC_LTP_T"
.rodata:01C0C388                 DCD aAvcTsBlCif15Aa_7   ; "AVC_TS_BL_CIF15_AAC_LTP_ISO"
.rodata:01C0C38C                 DCD aAvcTsBlCif15Bs     ; "AVC_TS_BL_CIF15_BSAC"
.rodata:01C0C390                 DCD aAvcTsBlCif15Bs_0   ; "AVC_TS_BL_CIF15_BSAC_T"
.rodata:01C0C394                 DCD aAvcTsBlCif15Bs_1   ; "AVC_TS_BL_CIF15_BSAC_ISO"
.rodata:01C0C398                 DCD aAvcMp4BlCif15A_0   ; "AVC_MP4_BL_CIF15_AAC"
.rodata:01C0C39C                 DCD aAvcMp4BlCif15A_1   ; "AVC_MP4_BL_CIF15_AAC_520"
.rodata:01C0C3A0                 DCD aAvcMp4BlCif15A_2   ; "AVC_MP4_BL_CIF15_AAC_LTP"
.rodata:01C0C3A4                 DCD aAvcMp4BlCif15A_3   ; "AVC_MP4_BL_CIF15_AAC_LTP_520"
.rodata:01C0C3A8                 DCD aAvcMp4BlCif15B     ; "AVC_MP4_BL_CIF15_BSAC"
.rodata:01C0C3AC                 DCD aAvcMp4BlL12Cif     ; "AVC_MP4_BL_L12_CIF15_HEAAC"
.rodata:01C0C3B0                 DCD aAvcMp4BlL1bQci     ; "AVC_MP4_BL_L1B_QCIF15_HEAAC"
.rodata:01C0C3B4                 DCD aAvc3gppBlCif30     ; "AVC_3GPP_BL_CIF30_AMR_WBplus"
.rodata:01C0C3B8                 DCD aAvc3gppBlCif15     ; "AVC_3GPP_BL_CIF15_AMR_WBplus"
.rodata:01C0C3BC                 DCD aAvc3gppBlQcif1     ; "AVC_3GPP_BL_QCIF15_AAC"
.rodata:01C0C3C0                 DCD aAvc3gppBlQcif1_0   ; "AVC_3GPP_BL_QCIF15_AAC_LTP"
.rodata:01C0C3C4                 DCD aAvc3gppBlQcif1_1   ; "AVC_3GPP_BL_QCIF15_HEAAC"
.rodata:01C0C3C8                 DCD aAvc3gppBlQcif1_2   ; "AVC_3GPP_BL_QCIF15_AMR_WBplus"
.rodata:01C0C3CC                 DCD aAvc3gppBlQcif1_3   ; "AVC_3GPP_BL_QCIF15_AMR"
.rodata:01C0C3D0                 DCD aWmvmedBase         ; "WMVMED_BASE"
...

As you can see, there is no AVC_MP4_EU, which makes the error consequent.

My proposal to cope with situations like this is to add a new mapping in config.xml

`

      <mimetype-dlnaprofile>
        <map from="mp4" to="AVC_MP4_BL_CIF30_AAC_MULT5"/>
      </mimetype-dlnaprofile>
`

Please find attached a patch which brings this functionality (code only, no documentation).

[gerbera-add-mimetype-to-dlnaprofile.patch.txt](https://github.com/gerbera/gerbera/files/6393759/gerbera-add-mimetype-to-dlnaprofile.patch.txt)

**Comment by KarlStraussberger** [comment]
Feel free to create a PR, which is easier to discuss.

Instead of adding to config_generator I propose to make the current settings default (there are several examples with the other mappngs). This also keeps compatibility up.

Please do not forget to update the docs and the config*.xsd files.
