### ISSUE TITLE
Slash in track metadata causes undesired containers to be generated with JS import

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#1429]
I have an album named _Shake/Shiver/Moan_. On the filesystem it's been converted to _Shake-Shiver-Moan_ for obvious reasons but the correct name with slashes is present in the metadata.

While writing an import script I noticed that additional containers are generated due to the slashes in the album title. I've confirmed that this also occurs on the default JS import script (i.e. `addAudio`). It does not occur with the builtin importer.

![image](https://user-images.githubusercontent.com/6924622/116785506-208e3780-aa57-11eb-9475-f9db541bfb0e.png)

I see the documentation makes mention of escaping the slashes under addCdsObject
> - containerChain (string) –
>     - A string, defining where the object will be added in the database hierarchy. The containers in the chain
> are separated by a slash ‘/’, for example, a value of ‘/Audio/All Music’ will add the object to the Audio, All Music container in the server hierarchy. Make sure to properly escape the slash characters in container names. You will find more information on container chain escaping later in this chapter. 
>     - A string, containing the container id as obtained from addContainerTree. In this case the third parameter is not used.

However I can't find any reasonable example of escaping. `createContainerChain` only operates on an array strings which I can't use with `addContainerTree`. Almost all the example scripts use `addContainerTree` over `createContainerChain`. Is the only approach to manually call `escapeSlash` for each metadata field?

**Comment by KarlStraussberger** [comment]
Thank you for reporting that rare case. 

If you want it fixed quickly, you need to escape the slashes in your `js`. The correct fix is in `content_manager.cc` which I'm going to prepare.

**Comment by KarlStraussberger** [comment]
Actually, this was never handled. That's why my import script handled the slashes, e.g. in AC/DC. Now it's handled internally.

**Comment by mill1000** [comment]
Just a heads up. Updated to v1.8.1 and the fix appears to introduce a bit of a compatibility issue with import scripts that use escapeSlash.

![image](https://user-images.githubusercontent.com/6924622/118372409-ab4e5680-b56e-11eb-961c-61124771e2fd.png)

**Comment by KarlStraussberger** [comment]
Thanks for the hint, but I don't see a save way to really avoid this.

Good to know that it only happens if users modified the scripts - they may be able to modify them again 🥇
