### ISSUE TITLE
Documented command-line options missing

### ISSUE THREAD

**Issue by orlitzky** [gerbera/gerbera#143]
I was just working on the gerbera init script in Gentoo, and I noticed that the following options (at least) are documented in the man page, but missing:

* --daemon
* --user
* --group

Our init script tried to make use of the `--pidfile` option, but without those three above, it's hard to do so sensibly =)

**Comment by v00d00** [comment]
We should document somewhere that those options where removed. What is the issue with the Gentoo init scripts?

**Comment by orlitzky** [comment]
You probably just got the email:

https://bugs.gentoo.org/show_bug.cgi?id=629962

**Comment by v00d00** [comment]
Thanks
