### ISSUE TITLE
Failing macOS build - Use native libuuid on *BSD

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#144]
Hello,

I often build Gerbera on **Fedora**, but occasionally on **macOS**.  It seems like my macOS fails to compile after the FreeBSD libuuid commit --> 5fa52b3fdd89c7d55173aef42b500282cee9cbb3.

> If I revert the 5fa52b3fdd89c7d55173aef42b500282cee9cbb3, all is well.  

It is almost like `#ifdef BSD` is not respected during build time, but printing out the flag yields `BSD` is disabled.

I am novice with C++ so perhaps the **correct** setting evades my knowledge.

Build Options
```
-DWITH_MAGIC=1 -DWITH_MYSQL=0 
-DWITH_CURL=1 -DWITH_JS=0 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 
-DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_INOTIFY=0
```

Build Output
```
/usr/local/bin/cmake --build /Users/gerbera/cmake-build-debug --target gerbera -- -j 4
Scanning dependencies of target libgerbera
[  1%] Building CXX object CMakeFiles/libgerbera.dir/src/config_manager.cc.o
[  2%] Building CXX object CMakeFiles/libgerbera.dir/src/tools.cc.o
In file included from /Users/gerbera/src/config_manager.cc:39:
/usr/local/Cellar/ossp-uuid/1.6.2_2/include/ossp/uuid.h:94:24: error: typedef redefinition with different types ('struct uuid_st' vs '__darwin_uuid_t' (aka 'unsigned char [16]'))
typedef struct uuid_st uuid_t;
                       ^
/usr/include/sys/_types/_uuid_t.h:30:25: note: previous definition is here
typedef __darwin_uuid_t uuid_t;
                        ^
/Users/gerbera/src/tools.cc:358:5: error: use of undeclared identifier 'uuid_create'
    uuid_create(&uuid, &status);
    ^
/Users/gerbera/src/tools.cc:359:5: error: use of undeclared identifier 'uuid_to_string'
    uuid_to_string(&uuid, &uuid_str, &status);
    ^
/Users/gerbera/src/config_manager.cc:2114:9: error: no matching function for call to 'uuid_create'
        uuid_create(&uuid, &status);
        ^~~~~~~~~~~
/usr/local/Cellar/ossp-uuid/1.6.2_2/include/ossp/uuid.h:97:22: note: candidate function not viable: requires single argument '_uuid', but 2 arguments were provided
extern uuid_rc_t     uuid_create   (      uuid_t **_uuid);
                     ^
/Users/gerbera/src/config_manager.cc:2115:9: error: use of undeclared identifier 'uuid_to_string'
        uuid_to_string(&uuid, &uuid_str, &status);
        ^
2 errors generated.
make[3]: *** [CMakeFiles/libgerbera.dir/src/tools.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
3 errors generated.
make[3]: *** [CMakeFiles/libgerbera.dir/src/config_manager.cc.o] Error 1
make[2]: *** [CMakeFiles/libgerbera.dir/all] Error 2
make[1]: *** [CMakeFiles/gerbera.dir/rule] Error 2
make: *** [gerbera] Error 2
```

**Comment by elmodaddyb** [comment]
OK, really confusing me.  If i change the definition to `HAS_BSD` instead of `BSD` it compiles just fine.

```CMakeLists.txt
if (BSD)
    add_definitions(-DHAS_BSD)
endif()
```
```config_manager.cc
#ifdef HAS_BSD
        uuid_create(&uuid, &status);
        uuid_to_string(&uuid, &uuid_str, &status);
#else
```
I clobbered the `/build/` directory for each run.  Not sure I fully understand why it works yet...so will do more research to find the root cause.

**Comment by michael-o** [comment]
Is Darwin detected as BSD? Wouldn't surprise me actually. BSD has defined on its own, we could use that, but that would go against the remaining approach. It seems to me that macOS comes with bundled `libuuid` in `libc`. Can you verify that?

**Comment by elmodaddyb** [comment]
@michael-o - Thanks for the helpful information.  I will try as you mentioned and see the outcome.

**Comment by elmodaddyb** [comment]
Yup, macOS is based on **BSD**!
[Apple Developer - BSD Overview](https://developer.apple.com/library/content/documentation/Darwin/Conceptual/KernelProgramming/BSD/BSD.html)

_... some random details from this article._

http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system
```
Apple's OSX for the Mac and iOS for iPhones and iPads are based in part on a fork of FreeBSD distributed as Darwin. As such, OSX and iOS also define the BSD macro within <sys/param.h>. 
However, compilers for OSX, iOS, and Darwin do not define __unix__. 
To detect all BSD OSes, including OSX, iOS, and Darwin, use an #if/#endif that checks 
for __unix__ along with __APPLE__ and __MACH__ (see the later section on OSX and iOS).
```
So it seems basing strictly on the **BSD** macro is not sufficient for macOS.

```
#ifdef BSD
    printf("macOS is based on BSD!!!!\n");
#endif
```
Yields

```
macOS is based on BSD!!!!
```
Still working to reconcile the native `libuuid`
For BSD & macOS support maybe this type of condition is required.

**Comment by elmodaddyb** [comment]
I am thinking the below should be used for BSD OSes (_to exclude Darwin_) ?

`#if defined(BSD) && defined(__unix__)`   instead of `#ifdef BSD`

Still need to confirm it works OK on **FreeBSD** though.

**Comment by v00d00** [comment]
Our OS detection is done in cmake, but I guess the defines are too generic so we are getting conflicts with outside defines.

Easiest thing would be to change them to have say OS_ as a prefix.

**Comment by michael-o** [comment]
They are better ways, I guess. For instance, FreeBSD defines `__FreeBSD__`. See [here](https://www.freebsd.org/doc/en/books/porters-handbook/porting-versions.html). I am certain that OpenBSD and NetBSD do the same. [Here](http://nadeausoftware.com/articles/2012/01/c_c_tip_how_use_compiler_predefined_macros_detect_operating_system) is another overview. Does this sound like something usable?

**Comment by v00d00** [comment]
I would rather not litter the code with such `ifdef`s if it can at all be helped. My personal preference is to enhance FindLibUUID.cmake to understand the native support and pass on down a obviously named definition.

**Comment by v00d00** [comment]
Done in https://github.com/gerbera/gerbera/commit/d4a1eb8642936d0dfae1efbdf597ba1421c20025

Please test

**Comment by elmodaddyb** [comment]
I will pull the latest master and retest.

**Comment by elmodaddyb** [comment]
Further down the macOS rabbit hole.  Getting a linkage error...It seems unrelated to this issue but perhaps my Upnp install is junk?
```
[  5%] Building CXX object CMakeFiles/libgerbera.dir/src/autoscan_inotify.cc.o
In file included from /Users/gerbera/src/action_request.cc:32:
In file included from /Users/gerbera/src/action_request.h:36:
In file included from /usr/local/include/upnp-1.8/upnp.h:47:
In file included from /usr/local/include/upnp-1.8/UpnpInet.h:41:
/usr/include/arpa/inet.h:77:13: error: declaration of 'inet_ntop' has a different language linkage
const char      *inet_ntop(int, const void *, char *, socklen_t);
                 ^
/System/Library/Frameworks/Kernel.framework/Headers/netinet/in.h:649:20: note: previous declaration is here
extern const char *inet_ntop(int, const void *, char *, socklen_t); /* in libkern*/
                   ^
```

**Comment by v00d00** [comment]
So this is sorted then? What did you mean by "reverted back"?

**Comment by michael-o** [comment]
Let me test on FreeBSD too.

**Comment by elmodaddyb** [comment]
Sorry for the confusion. The new uuid cmake causes a linkage error on macOS d4a1eb8642936d0dfae1efbdf597ba1421c20025

I need to research a bit to understand why the prior revision does **not** cause the linkage errors.

**Comment by michael-o** [comment]
I have checked the commit. While it works for me, it is somewhat confusing: Why has the file been renamed? The logic has been changed in a way that if `libuuid` is installed on a BSD machine, it is taken from `/usr/local` instead of native one. This is unlogical and I causes another problem. Consider that some port has installed libuuid and everything is recursively removed when the port is not necessary anymore. I do plan to create the Gerbera port somewhere this year. Now, the port is installed and detects libuuid from ports and libuuid is uninstalled at some point. `dld` which complains at Gerberra start that `/usr/local/lib/libuuid.so` cannot be found.

**Comment by michael-o** [comment]
@v00d00 Any opinion on the revert?

**Comment by v00d00** [comment]
I think we just need to tidy the logic up.

Please try https://github.com/gerbera/gerbera/commit/a388f01cbb967b00a5b9b93a8816a7e1f027e42c

**Comment by michael-o** [comment]
@v00d00 The commit works for me, except for the typos I have commented.

**Comment by elmodaddyb** [comment]
OK, climbed out of the rabbit hole that is Apple Clang + LLVM.

I had to set this option in CMake `-DCMAKE_FIND_FRAMEWORK=LAST` to make the Gerbera build work OK.

I will pull a388f01cbb967b00a5b9b93a8816a7e1f027e42c and see how compile goes....if all is well, will work on some macOS instructions too!

**Comment by v00d00** [comment]
Typos have been fixed in master now...

**Comment by michael-o** [comment]
@elmodaddyb This is worth adding to `README.md`.

**Comment by elmodaddyb** [comment]
Boom!!!
```
2017-09-10 15:40:45    INFO: Configuration check succeeded.
2017-09-10 15:40:45    INFO: Initialized port: 49152
2017-09-10 15:40:45    INFO: Server bound to: 192.168.0.1
2017-09-10 15:40:45    INFO: The Web UI can be reached by following this link: http://192.168.0.1:49152/
```
UUID found via, the homebrew'd `ossp-uuid` (_I think_)
```
//Path to a file.
UUID_INCLUDE_DIRS:PATH=/usr/include

//Path to a library.
UUID_LIBRARIES:FILEPATH=/usr/local/lib/libuuid.dylib
```
Great work @v00d00 and @michael-o 🥇 I will pull together some documentation for macOS soon.

I will try to stream a few files...then close this issue!!

**Comment by michael-o** [comment]
@elmodaddyb header file in `/usr`, but library in `/usr/local`? That looks weird to me.

**Comment by elmodaddyb** [comment]
agreed it looks odd, looking at macOS, there are darwin's _uuid.h_ in /usr/include....but the `libSystem.dylib` does not yield any `_uuid` exports.
```
nm -a /usr/lib/libSystem.dylib | grep -i "_uuid"
```
If i delete `ossp-uuid` using brew, then no library is found for UUID.  I am not sure how to *find* the native library which provides uuid :(

**Comment by michael-o** [comment]
What about [this](https://patchwork.ozlabs.org/patch/57826/) one?

**Comment by elmodaddyb** [comment]
Yea, I tailed a bunch of libraries in `/usr/lib` to no avail.

Here's the macOS instructions thus far

https://gist.github.com/elmodaddyb/5d29ba6b7b286cdb71ed01d74766fa68
