### ISSUE TITLE
Importing m3u files with errors can cause sqlite database errors

### ISSUE THREAD

**Issue by run2000** [gerbera/gerbera#1446]
Environment: Gerbera 1.8.1 release, Docker image from hub.docker.com

Symptoms: Importing my audio collection, I noticed a database error turning up in the user interface. 

![error1](https://user-images.githubusercontent.com/7520160/117944479-673a3680-b361-11eb-8c95-c5d14723fd6b.png)

The problem seems to be with M3U files that are malformed or with incorrect paths. I had several M3U files that were encoded with Windows ANSI encoded filenames, where Gerbera seems to expect UTF-8. The problem only seems to happen when there's several bad M3U files; only one doesn't seem to be sufficient. Also it may not fail at the same point on each import.

Attached are the logs from the Docker container, the config.xml file, and an example of a problem M3U file. The log file in particular is interesting, because it first indicates a transaction failure, then fails to rollback, then closes the connection prematurely.

[gerbera.log](https://github.com/gerbera/gerbera/files/6464811/gerbera.log)
[config.xml.txt](https://github.com/gerbera/gerbera/files/6464815/config.xml.txt)
[The Beach Boys - Smiley Smile.m3u.txt](https://github.com/gerbera/gerbera/files/6464825/The.Beach.Boys.-.Smiley.Smile.m3u.txt)

**Comment by KarlStraussberger** [comment]
There are two different issues: playlist encoding, which can be set to Ansi, which may fix the m3u errors, but may bring up others. Best thing is to encode all m3u in utf-8.

The second issue is more complicated. It's based on the way sqlite commands are handled. The workaround is to turn off transactions (https://docs.gerbera.io/en/stable/config-server.html#storage). I'm working on a solution to the issue.

**Comment by mill1000** [comment]
Also seeing this database issue. Seems like a pretty significant issue with v1.8.1. Perhaps the release should be pulled.

**Comment by KarlStraussberger** [comment]
The fix is ready now. There is an issue with one of the  CI checks that blocks merging 😢
