### ISSUE TITLE
Replace non-ASCII characters with ASCII in common.js

### ISSUE THREAD

**Issue by imolb** [gerbera/gerbera#1449]
The abcbox in scripts/js/common.js is a nice feature.
https://github.com/gerbera/gerbera/blob/9d99462f044ad05072b2bf5be5f54f8e5dec2b05/scripts/js/common.js#L111

Unfortunately it gets confused with non ASCII characters (e.g. Á, Ä, ...) because these are considered as special characters. But I would have expected these in the box ABC and not ^\&#.

In the audiotagger MusicBrainz Picard there is a nice feature named "Replace non-ASCII characters".
This replaces several special characters with similar ASCII characters:
https://github.com/metabrainz/picard/blob/3ea43252c498bd27aa16ad5b7899c2b55c1027b5/picard/util/textencoding.py#L199

Would it make sense, to have this functionality also in the common.js script?
Any idea how to reuse the Python script from Picard, or is it necessary to do some search-and-replace to convert it to Javascript style?

**Comment by KarlStraussberger** [comment]
It's not that complicated. Just take a look at genre-map

**Comment by imolb** [comment]
For my own purpose I've just done a simple replacement directly in my custom.js

```
function replaceWithAsciiChar(character) {
    const replaceMap =  {
        'Á': 'A',
        'Ä': 'A',
        'Ā': 'A',
        'É': 'E',
        'İ': 'I',
        'Ö': 'O',
        'Ü': 'U'
    };
    if (character in replaceMap) {
        return replaceMap[character];
    } else {
        return character;
    }
}
```
Do you think, this kind of logic would be interesting for others, so to integrate it into the master stream and in the configuration like the genreMap?


Side-topic:
https://github.com/gerbera/gerbera/blob/9d99462f044ad05072b2bf5be5f54f8e5dec2b05/scripts/js/common.js#L124
In the abcbox and init-character I personally prefer, to use the second (or third ...) character of the string, if the first character is not alpha-numeric. But this is for sure personal taste...

**Comment by KarlStraussberger** [comment]
Hold on, I've got a PR in work.
