### ISSUE TITLE
link.txt incorrectly generated by cmake on FreeBSD

### ISSUE THREAD

**Issue by michael-o** [gerbera/gerbera#145]
Using Gerbera from master, installed manadatory dependencies to `/usr/local/gebera` and configured with:
 `cmake .. -DWITH_JS=0 -DWITH_TAGLIB=0 -DWITH_EXIF=0 -DWITH_INOTIFY=0 -DUPNP_INCLUDE_DIR=/usr/local/gerbera/include/upnp-1.8 -DUPNP_UPNP_LIBRARY=/usr/local/gerbera/lib -DUPNP_IXML_LIBRARY=/usr/local/gerbera/lib -DCMAKE_INSTALL_PREFIX=/usr/local/gerbera`

output is:

    [mosipov@mika-ion ~/Projekte/gerbera/build]$ cmake .. -DWITH_JS=0 -DWITH_TAGLIB=0 -DWITH_EXIF=0 -DWITH_INOTIFY=0 -DUPNP_INCLUDE_DIR=/usr/local/gerbera/include/upnp-1.8 -DUPNP_UPNP_LIBRARY=/usr/local/gerbera/lib -DUPNP_IXML_LIBRARY=/usr/local/gerbera/lib -DCMAKE_INSTALL_PREFIX=/usr/local/gerbera
    -- The C compiler identification is Clang 4.0.0
    -- The CXX compiler identification is Clang 4.0.0
    -- Check for working C compiler: /usr/bin/cc
    -- Check for working C compiler: /usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /usr/bin/CC
    -- Check for working CXX compiler: /usr/bin/CC -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
    -- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
    -- Found Iconv: /usr/local/lib/libiconv.so
    -- Found PkgConfig: /usr/local/bin/pkg-config (found version "1.3.7")
    -- Looking for libuuid
    -- Looking for libuuid - found
    -- Found UUID: TRUE
    -- Looking for native LFS support
    -- Looking for native LFS support - found
    -- Found LFS: TRUE
    -- Found UPnP: /usr/local/gerbera/lib (found version "1.8.2")
    -- Found EXPAT: /usr/local/lib/libexpat.so (found version "2.2.1")
    -- Found Sqlite3: /usr/local/lib/libsqlite3.so
    -- Looking for nl_langinfo
    -- Looking for nl_langinfo - found
    -- Looking for setlocale
    -- Looking for setlocale - found
    -- Found CURL: /usr/local/lib/libcurl.so (found version "7.55.1")
    -- Found MAGIC: /usr/include
    -- Found ZLIB: /usr/lib/libz.so (found version "1.2.11")
    -- Configuring done
    WARNING: Target "gerbera" requests linking to directory "/usr/local/gerbera/lib".  Targets may link only to libraries.  CMake is dropping the item.
    WARNING: Target "gerbera" requests linking to directory "/usr/local/gerbera/lib".  Targets may link only to libraries.  CMake is dropping the item.
    -- Generating done
    -- Build files have been written to: /home/mosipov/Projekte/gerbera/build

let's compile now:

    Scanning dependencies of target gerbera
    [ 99%] Building CXX object CMakeFiles/gerbera.dir/src/main.cc.o
    [100%] Linking CXX executable gerbera
    CMakeFiles/libgerbera.dir/src/action_request.cc.o: In function `ActionRequest::ActionRequest(s_UpnpActionRequest*)':
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x62): undefined reference to `UpnpActionRequest_get_ActionName_cstr'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x9f): undefined reference to `UpnpActionRequest_get_DevUDN_cstr'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0xdc): undefined reference to `UpnpActionRequest_get_ServiceID_cstr'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x14e): undefined reference to `UpnpActionRequest_get_ActionRequest'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x164): undefined reference to `ixmlPrintDocument'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x19b): undefined reference to `ixmlFreeDOMString'
    CMakeFiles/libgerbera.dir/src/action_request.cc.o: In function `ActionRequest::update()':
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x5cb): undefined reference to `ixmlDocument_createDocument'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x606): undefined reference to `ixmlParseBufferEx'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x68f): undefined reference to `UpnpActionRequest_set_ErrCode'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x6fe): undefined reference to `UpnpActionRequest_set_ActionResult'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x71d): undefined reference to `UpnpActionRequest_set_ErrCode'
    /home/mosipov/Projekte/gerbera/src/action_request.cc:(.text+0x76a): undefined reference to `UpnpActionRequest_set_ErrCode'
    CMakeFiles/libgerbera.dir/src/file_request_handler.cc.o: In function `FileRequestHandler::get_info(char const*, s_UpnpFileInfo*)':
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x12fe): undefined reference to `UpnpFileInfo_set_IsReadable'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x1326): undefined reference to `UpnpFileInfo_set_IsReadable'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x18fb): undefined reference to `UpnpFileInfo_set_FileLength'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x1f56): undefined reference to `UpnpFileInfo_get_FileLength'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x2ea7): undefined reference to `UpnpFileInfo_set_FileLength'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x2f1d): undefined reference to `UpnpFileInfo_set_FileLength'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x4513): undefined reference to `ixmlCloneDOMString'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x4530): undefined reference to `UpnpFileInfo_set_ExtraHeaders'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x45e0): undefined reference to `UpnpFileInfo_set_LastModified'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x461a): undefined reference to `UpnpFileInfo_set_IsDirectory'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x4654): undefined reference to `ixmlCloneDOMString'
    /home/mosipov/Projekte/gerbera/src/file_request_handler.cc:(.text+0x4671): undefined reference to `UpnpFileInfo_set_ContentType'
    CMakeFiles/libgerbera.dir/src/server.cc.o: In function `Server::upnp_init()':
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0xefa): undefined reference to `UpnpInit2'
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x105e): undefined reference to `UpnpGetServerPort'
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x110e): undefined reference to `UpnpGetServerIpAddress'
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x16a1): undefined reference to `UpnpSetWebServerRootDir'
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x1bb6): undefined reference to `UpnpAddVirtualDir'
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x28af): undefined reference to `UpnpRegisterRootDevice2'
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x2aac): undefined reference to `UpnpSendAdvertisement'
    CMakeFiles/libgerbera.dir/src/server.cc.o: In function `Server::shutdown()':
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x2f84): undefined reference to `UpnpUnRegisterRootDevice'
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x30af): undefined reference to `UpnpFinish'
    CMakeFiles/libgerbera.dir/src/server.cc.o: In function `Server::upnp_callback(Upnp_EventType_e, void const*, void*)':
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x345f): undefined reference to `UpnpActionRequest_set_ErrCode'
    CMakeFiles/libgerbera.dir/src/server.cc.o: In function `Server::getIP()':
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x4328): undefined reference to `UpnpGetServerIpAddress'
    CMakeFiles/libgerbera.dir/src/server.cc.o: In function `Server::getPort()':
    /home/mosipov/Projekte/gerbera/src/server.cc:(.text+0x4368): undefined reference to `UpnpGetServerPort'
    CMakeFiles/libgerbera.dir/src/serve_request_handler.cc.o: In function `ServeRequestHandler::get_info(char const*, s_UpnpFileInfo*)':
    /home/mosipov/Projekte/gerbera/src/serve_request_handler.cc:(.text+0x103e): undefined reference to `UpnpFileInfo_set_FileLength'
    /home/mosipov/Projekte/gerbera/src/serve_request_handler.cc:(.text+0x1061): undefined reference to `UpnpFileInfo_set_LastModified'
    /home/mosipov/Projekte/gerbera/src/serve_request_handler.cc:(.text+0x109b): undefined reference to `UpnpFileInfo_set_IsDirectory'
    /home/mosipov/Projekte/gerbera/src/serve_request_handler.cc:(.text+0x10fe): undefined reference to `UpnpFileInfo_set_IsReadable'
    /home/mosipov/Projekte/gerbera/src/serve_request_handler.cc:(.text+0x1123): undefined reference to `UpnpFileInfo_set_IsReadable'
    /home/mosipov/Projekte/gerbera/src/serve_request_handler.cc:(.text+0x1162): undefined reference to `ixmlCloneDOMString'
    /home/mosipov/Projekte/gerbera/src/serve_request_handler.cc:(.text+0x117f): undefined reference to `UpnpFileInfo_set_ContentType'
    CMakeFiles/libgerbera.dir/src/subscription_request.cc.o: In function `SubscriptionRequest::SubscriptionRequest(s_UpnpSubscriptionRequest*)':
    /home/mosipov/Projekte/gerbera/src/subscription_request.cc:(.text+0x7d): undefined reference to `UpnpSubscriptionRequest_get_ServiceId_cstr'
    /home/mosipov/Projekte/gerbera/src/subscription_request.cc:(.text+0xae): undefined reference to `UpnpSubscriptionRequest_get_UDN_cstr'
    /home/mosipov/Projekte/gerbera/src/subscription_request.cc:(.text+0xdf): undefined reference to `UpnpSubscriptionRequest_get_SID_cstr'
    CMakeFiles/libgerbera.dir/src/upnp_cds_subscriptions.cc.o: In function `ContentDirectoryService::process_subscription_request(zmm::Ref<SubscriptionRequest>)':
    /home/mosipov/Projekte/gerbera/src/upnp_cds_subscriptions.cc:(.text+0x436): undefined reference to `ixmlParseBufferEx'
    /home/mosipov/Projekte/gerbera/src/upnp_cds_subscriptions.cc:(.text+0x812): undefined reference to `UpnpAcceptSubscriptionExt'
    /home/mosipov/Projekte/gerbera/src/upnp_cds_subscriptions.cc:(.text+0x868): undefined reference to `ixmlDocument_free'
    CMakeFiles/libgerbera.dir/src/upnp_cds_subscriptions.cc.o: In function `ContentDirectoryService::subscription_update(zmm::String)':
    /home/mosipov/Projekte/gerbera/src/upnp_cds_subscriptions.cc:(.text+0xd00): undefined reference to `ixmlParseBufferEx'
    /home/mosipov/Projekte/gerbera/src/upnp_cds_subscriptions.cc:(.text+0xff7): undefined reference to `UpnpNotifyExt'
    /home/mosipov/Projekte/gerbera/src/upnp_cds_subscriptions.cc:(.text+0x1037): undefined reference to `ixmlDocument_free'
    CMakeFiles/libgerbera.dir/src/upnp_cm_subscriptions.cc.o: In function `ConnectionManagerService::process_subscription_request(zmm::Ref<SubscriptionRequest>)':
    /home/mosipov/Projekte/gerbera/src/upnp_cm_subscriptions.cc:(.text+0x419): undefined reference to `ixmlParseBufferEx'
    /home/mosipov/Projekte/gerbera/src/upnp_cm_subscriptions.cc:(.text+0x811): undefined reference to `UpnpAcceptSubscriptionExt'
    /home/mosipov/Projekte/gerbera/src/upnp_cm_subscriptions.cc:(.text+0x864): undefined reference to `ixmlDocument_free'
    CMakeFiles/libgerbera.dir/src/upnp_cm_subscriptions.cc.o: In function `ConnectionManagerService::subscription_update(zmm::String)':
    /home/mosipov/Projekte/gerbera/src/upnp_cm_subscriptions.cc:(.text+0xbaa): undefined reference to `ixmlParseBufferEx'
    /home/mosipov/Projekte/gerbera/src/upnp_cm_subscriptions.cc:(.text+0xe38): undefined reference to `UpnpNotifyExt'
    /home/mosipov/Projekte/gerbera/src/upnp_cm_subscriptions.cc:(.text+0xe78): undefined reference to `ixmlDocument_free'
    CMakeFiles/libgerbera.dir/src/url_request_handler.cc.o: In function `URLRequestHandler::get_info(char const*, s_UpnpFileInfo*)':
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0xc75): undefined reference to `UpnpFileInfo_set_FileLength'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x1174): undefined reference to `UpnpFileInfo_set_FileLength'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x13da): undefined reference to `UpnpFileInfo_set_FileLength'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x154b): undefined reference to `UpnpFileInfo_set_IsReadable'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x156b): undefined reference to `UpnpFileInfo_set_LastModified'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x158b): undefined reference to `UpnpFileInfo_set_IsDirectory'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x161e): undefined reference to `ixmlCloneDOMString'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x163b): undefined reference to `UpnpFileInfo_set_ExtraHeaders'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x169c): undefined reference to `ixmlCloneDOMString'
    /home/mosipov/Projekte/gerbera/src/url_request_handler.cc:(.text+0x16b9): undefined reference to `UpnpFileInfo_set_ContentType'
    CMakeFiles/libgerbera.dir/src/web_callbacks.cc.o: In function `register_web_callbacks()':
    /home/mosipov/Projekte/gerbera/src/web_callbacks.cc:(.text+0x18): undefined reference to `UpnpVirtualDir_set_GetInfoCallback'
    /home/mosipov/Projekte/gerbera/src/web_callbacks.cc:(.text+0x36): undefined reference to `UpnpVirtualDir_set_OpenCallback'
    /home/mosipov/Projekte/gerbera/src/web_callbacks.cc:(.text+0x54): undefined reference to `UpnpVirtualDir_set_ReadCallback'
    /home/mosipov/Projekte/gerbera/src/web_callbacks.cc:(.text+0x72): undefined reference to `UpnpVirtualDir_set_WriteCallback'
    /home/mosipov/Projekte/gerbera/src/web_callbacks.cc:(.text+0x90): undefined reference to `UpnpVirtualDir_set_SeekCallback'
    /home/mosipov/Projekte/gerbera/src/web_callbacks.cc:(.text+0xae): undefined reference to `UpnpVirtualDir_set_CloseCallback'
    CMakeFiles/libgerbera.dir/src/web_request_handler.cc.o: In function `WebRequestHandler::get_info(char const*, s_UpnpFileInfo*)':
    /home/mosipov/Projekte/gerbera/src/web_request_handler.cc:(.text+0xc55): undefined reference to `UpnpFileInfo_set_FileLength'
    /home/mosipov/Projekte/gerbera/src/web_request_handler.cc:(.text+0xc75): undefined reference to `UpnpFileInfo_set_LastModified'
    /home/mosipov/Projekte/gerbera/src/web_request_handler.cc:(.text+0xc95): undefined reference to `UpnpFileInfo_set_IsDirectory'
    /home/mosipov/Projekte/gerbera/src/web_request_handler.cc:(.text+0xcb5): undefined reference to `UpnpFileInfo_set_IsReadable'
    /home/mosipov/Projekte/gerbera/src/web_request_handler.cc:(.text+0x1039): undefined reference to `ixmlCloneDOMString'
    /home/mosipov/Projekte/gerbera/src/web_request_handler.cc:(.text+0x1056): undefined reference to `UpnpFileInfo_set_ContentType'
    /home/mosipov/Projekte/gerbera/src/web_request_handler.cc:(.text+0x1077): undefined reference to `ixmlCloneDOMString'
    /home/mosipov/Projekte/gerbera/src/web_request_handler.cc:(.text+0x1094): undefined reference to `UpnpFileInfo_set_ExtraHeaders'
    c++: error: linker command failed with exit code 1 (use -v to see invocation)
    *** Error code 1
    
    Stop.
    make[2]: stopped in /usr/home/mosipov/Projekte/gerbera/build
    *** Error code 1
    
    Stop.
    make[1]: stopped in /usr/home/mosipov/Projekte/gerbera/build
    *** Error code 1
    
    Stop.
    make: stopped in /usr/home/mosipov/Projekte/gerbera/build
    [mosipov@mika-ion ~/Projekte/gerbera/build]$

So, some libs and lib dirs aren't passed to the linker. `link.txt` says:

    /usr/bin/CC   -Wall -stdlib=libc++   
    CMakeFiles/gerbera.dir/src/main.cc.o 
    CMakeFiles/libgerbera.dir/src/action_request.cc.o 
    CMakeFiles/libgerbera.dir/src/atrailers_content_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/atrailers_service.cc.o 
    CMakeFiles/libgerbera.dir/src/autoscan.cc.o 
    CMakeFiles/libgerbera.dir/src/autoscan_inotify.cc.o 
    CMakeFiles/libgerbera.dir/src/buffered_io_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/cached_url.cc.o 
    CMakeFiles/libgerbera.dir/src/cds_objects.cc.o 
    CMakeFiles/libgerbera.dir/src/cds_resource.cc.o 
    CMakeFiles/libgerbera.dir/src/cds_resource_manager.cc.o 
    CMakeFiles/libgerbera.dir/src/config_manager.cc.o 
    CMakeFiles/libgerbera.dir/src/content_manager.cc.o 
    CMakeFiles/libgerbera.dir/src/contrib/md5.c.o 
    CMakeFiles/libgerbera.dir/src/curl_io_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/destroyer.cc.o 
    CMakeFiles/libgerbera.dir/src/dictionary.cc.o 
    CMakeFiles/libgerbera.dir/src/exceptions.cc.o 
    CMakeFiles/libgerbera.dir/src/fd_io_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/file_io_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/file_request_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/filesystem.cc.o 
    CMakeFiles/libgerbera.dir/src/generic_task.cc.o 
    CMakeFiles/libgerbera.dir/src/io_handler_buffer_helper.cc.o 
    CMakeFiles/libgerbera.dir/src/io_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/io_handler_chainer.cc.o 
    CMakeFiles/libgerbera.dir/src/jpeg_resolution.cc.o 
    CMakeFiles/libgerbera.dir/src/lastfm_scrobbler.cc.o 
    CMakeFiles/libgerbera.dir/src/layout/fallback_layout.cc.o 
    CMakeFiles/libgerbera.dir/src/layout/js_layout.cc.o 
    CMakeFiles/libgerbera.dir/src/logger.cc.o 
    CMakeFiles/libgerbera.dir/src/mem_io_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/memory.cc.o 
    CMakeFiles/libgerbera.dir/src/metadata/exiv2_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/metadata_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/metadata/libexif_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/metadata/taglib_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/metadata/fanart_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/mt_inotify.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/attribute.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/comment.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/context.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/document.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/element.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/node.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/parseexception.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/parser_expat.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/xml_text.cc.o 
    CMakeFiles/libgerbera.dir/src/mxml/xml_to_json.cc.o 
    CMakeFiles/libgerbera.dir/src/online_service.cc.o 
    CMakeFiles/libgerbera.dir/src/online_service_helper.cc.o 
    CMakeFiles/libgerbera.dir/src/play_hook.cc.o 
    CMakeFiles/libgerbera.dir/src/process.cc.o 
    CMakeFiles/libgerbera.dir/src/process_executor.cc.o 
    CMakeFiles/libgerbera.dir/src/process_io_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/request_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/rexp.cc.o 
    CMakeFiles/libgerbera.dir/src/scripting/import_script.cc.o 
    CMakeFiles/libgerbera.dir/src/scripting/js_functions.cc.o 
    CMakeFiles/libgerbera.dir/src/scripting/playlist_parser_script.cc.o 
    CMakeFiles/libgerbera.dir/src/scripting/runtime.cc.o 
    CMakeFiles/libgerbera.dir/src/scripting/script.cc.o 
    CMakeFiles/libgerbera.dir/src/server.cc.o 
    CMakeFiles/libgerbera.dir/src/serve_request_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/session_manager.cc.o 
    CMakeFiles/libgerbera.dir/src/singleton.cc.o 
    CMakeFiles/libgerbera.dir/src/sopcast_content_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/sopcast_service.cc.o 
    CMakeFiles/libgerbera.dir/src/storage/cache_object.cc.o 
    CMakeFiles/libgerbera.dir/src/storage.cc.o 
    CMakeFiles/libgerbera.dir/src/storage/mysql/mysql_storage.cc.o 
    CMakeFiles/libgerbera.dir/src/storage/sqlite3/sqlite3_storage.cc.o 
    CMakeFiles/libgerbera.dir/src/storage/sql_storage.cc.o 
    CMakeFiles/libgerbera.dir/src/storage/storage_cache.cc.o 
    CMakeFiles/libgerbera.dir/src/string_converter.cc.o 
    CMakeFiles/libgerbera.dir/src/subscription_request.cc.o 
    CMakeFiles/libgerbera.dir/src/task_processor.cc.o 
    CMakeFiles/libgerbera.dir/src/thread_executor.cc.o 
    CMakeFiles/libgerbera.dir/src/timer.cc.o 
    CMakeFiles/libgerbera.dir/src/tools.cc.o 
    CMakeFiles/libgerbera.dir/src/transcoding/transcode_dispatcher.cc.o 
    CMakeFiles/libgerbera.dir/src/transcoding/transcode_ext_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/transcoding/transcoding.cc.o 
    CMakeFiles/libgerbera.dir/src/transcoding/transcoding_process_executor.cc.o 
    CMakeFiles/libgerbera.dir/src/update_manager.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_cds_actions.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_cds.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_cds_subscriptions.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_cm_actions.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_cm.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_cm_subscriptions.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_mrreg_actions.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_mrreg.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_mrreg_subscriptions.cc.o 
    CMakeFiles/libgerbera.dir/src/upnp_xml.cc.o 
    CMakeFiles/libgerbera.dir/src/url.cc.o 
    CMakeFiles/libgerbera.dir/src/url_request_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/web/action.cc.o 
    CMakeFiles/libgerbera.dir/src/web/add.cc.o 
    CMakeFiles/libgerbera.dir/src/web/add_object.cc.o 
    CMakeFiles/libgerbera.dir/src/web/auth.cc.o 
    CMakeFiles/libgerbera.dir/src/web_callbacks.cc.o 
    CMakeFiles/libgerbera.dir/src/web/containers.cc.o 
    CMakeFiles/libgerbera.dir/src/web/directories.cc.o 
    CMakeFiles/libgerbera.dir/src/web/edit_load.cc.o 
    CMakeFiles/libgerbera.dir/src/web/edit_save.cc.o 
    CMakeFiles/libgerbera.dir/src/web/files.cc.o 
    CMakeFiles/libgerbera.dir/src/web/items.cc.o 
    CMakeFiles/libgerbera.dir/src/web/pages.cc.o 
    CMakeFiles/libgerbera.dir/src/web/remove.cc.o 
    CMakeFiles/libgerbera.dir/src/web_request_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/web/tasks.cc.o 
    CMakeFiles/libgerbera.dir/src/web/web_autoscan.cc.o 
    CMakeFiles/libgerbera.dir/src/web/web_update.cc.o 
    CMakeFiles/libgerbera.dir/src/xpath.cc.o 
    CMakeFiles/libgerbera.dir/src/youtube_content_handler.cc.o 
    CMakeFiles/libgerbera.dir/src/youtube_service.cc.o 
    CMakeFiles/libgerbera.dir/src/youtube_video_url.cc.o 
    CMakeFiles/libgerbera.dir/src/zmm/array.cc.o 
    CMakeFiles/libgerbera.dir/src/zmm/exception.cc.o 
    CMakeFiles/libgerbera.dir/src/zmm/stringtokenizer.cc.o 
    CMakeFiles/libgerbera.dir/src/zmm/object.cc.o 
    CMakeFiles/libgerbera.dir/src/zmm/stringbuffer.cc.o 
    CMakeFiles/libgerbera.dir/src/zmm/strings.cc.o  -o gerbera -Wl,-rpath,/usr/local/lib: -lpthread /usr/local/lib/libiconv.so /usr/local/lib/libuuid.so /usr/local/lib/libexpat.so /usr/local/lib/libsqlite3.so /usr/local/lib/libcurl.so -lmagic -lz

Confusing is here that some libraries are referenced with absolute paths and mandatory libs are completely absent, as well as compile time library dirs and rpath dirs. Patching `link.txt` make linking work again.

Changed `link.txt` to `-Wl,-rpath,/usr/local/lib:/usr/local/gerbera/lib -lpthread /usr/local/lib/libiconv.so /usr/local/lib/libuuid.so /usr/local/lib/libexpat.so /usr/local/lib/libsqlite3.so /usr/local/lib/libcurl.so -lmagic -lz -L/usr/local/lib -L/usr/local/gerbera/lib -lupnp-1.8 -lixml-1.8`. Voila:

    [mosipov@mika-ion ~/Projekte/gerbera/build]$ make
    [ 99%] Built target libgerbera
    [100%] Linking CXX executable gerbera
    [100%] Built target gerbera

    [mosipov@mika-ion ~/Projekte/gerbera/build]$ ldd ./gerbera
    ./gerbera:
            libthr.so.3 => /lib/libthr.so.3 (0x28241000)
            libiconv.so.2 => /usr/local/lib/libiconv.so.2 (0x28264000)
            libuuid.so.1 => /usr/local/lib/libuuid.so.1 (0x28359000)
            libexpat.so.1 => /usr/local/lib/libexpat.so.1 (0x2835d000)
            libsqlite3.so.0 => /usr/local/lib/libsqlite3.so.0 (0x28383000)
            libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x2849b000)
            libmagic.so.4 => /usr/lib/libmagic.so.4 (0x284f1000)
            libz.so.6 => /lib/libz.so.6 (0x28510000)
            libupnp-1.8.so.10 => /usr/local/gerbera/lib/libupnp-1.8.so.10 (0x2852f000)
            libixml-1.8.so.10 => /usr/local/gerbera/lib/libixml-1.8.so.10 (0x28564000)
            libc++.so.1 => /usr/lib/libc++.so.1 (0x2856e000)
            libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x2862c000)
            libm.so.5 => /lib/libm.so.5 (0x28645000)
            libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x2866d000)
            libc.so.7 => /lib/libc.so.7 (0x28679000)
            libssl.so.8 => /usr/lib/libssl.so.8 (0x287d8000)
            libcrypto.so.8 => /lib/libcrypto.so.8 (0x28832000)

**Comment by v00d00** [comment]
UPNP_UPNP_LIBRARY and UPNP_IXML_LIBRARY are expected to be paths to `libupnp.so` and `libixml.so`

**Comment by v00d00** [comment]
We should add a way to provide the libupnp path, though.

**Comment by michael-o** [comment]
Indeed! I am not used to use cmake. I assumed it to be like with autoconf: just passing the dir contaning the library. Maybe a note in the `README.md` for the unknowning that `*_LIBRARY` refers really to the shared object/archive rather than the dir containing it.

**Comment by v00d00** [comment]
I think we should consider being able to override the default paths per Find module though, as at the moment you have to set the generic `CMAKE_PREFIX_PATH`  rather than on a per module basis.
