### ISSUE TITLE
Container metadata mixed up

### ISSUE THREAD

**Issue by imolb** [gerbera/gerbera#1454]
Using the default js audio layout
`<virtual-layout type="js" audio-layout="Default" />`
and importing the attached audio track to an empty database leads to a wrong dc:title attribute.

Container: Database/Audio/Artists/Adiemus
Details in web gui:

Metadata
dc:title | Year
upnp:artist | Adiemus
upnp:artist@role[AlbumArtist] | Adiemus

Instead of dc:title | Year I would have expected "Adiemus".

In the sqlite db the container has the mt_cds_object ID 11
In mt_metadata the wrong entry is ID 26, item_id 11, property_name dc:title, property_value: Year
In the debug-log file I cant find any line setting this value to this id.

[sample_container_metadata.zip](https://github.com/gerbera/gerbera/files/6511424/sample_container_metadata.zip)
[gerberalog_dctitle_reduced.zip](https://github.com/gerbera/gerbera/files/6511425/gerberalog_dctitle_reduced.zip)

**Comment by KarlStraussberger** [comment]
Thank you for reporting this one.

I removed an issue that the statement did not work at all (`property_name='property_name'` never matched). This issue was hidded right behind :smiley:

**Comment by imolb** [comment]
Thanks for the fast fix, which I can confirm.
