### ISSUE TITLE
Playlist title appears truncated twice in UI

### ISSUE THREAD

**Issue by run2000** [gerbera/gerbera#1458]
Environment: Gerbera v1.8.1-12-gf8dc162b, Docker image from hub.docker.com (currently tagged Master)

Symptoms:

Any M3U playlist file that contains more than one period in the filename, the title for the appears to truncate to the second-last period. For example, in a playlist "Mr. Mister - Welcome To The Real World.m3u", the title is truncated to "Mr". Simiarly, for a playlist "The Beatles - Sgt. Pepper's Lonely Hearts Club Band.m3u", the title is truncated to "The Beatles - Sgt".

Note, it is not truncated to the first period. I've played with a few examples, adding multiple periods, and it always truncates to the second-last.

My guess is that it gets truncated at two different places in the code, but I don't see any obvious red flags. One place might be around line 1296 of content_manager.cc.

`title = dirEnt.path().stem().string();`

Attached shows an example of the double-truncation as it appears in the UI.

![image](https://user-images.githubusercontent.com/7520160/119058026-ae8b8b80-ba21-11eb-98d5-1fa70b3345c3.png)

**Comment by KarlStraussberger** [comment]
Thank you for digging into the root cause also. Location was quite easy to spot in `playlist.js`

**Comment by run2000** [comment]
Confirmed fixed on build v1.8.1-16-ga210f4dd in Docker. Thanks!
