### ISSUE TITLE
container on pi:  libupnp ThreadPoolAdd too many jobs: 100

### ISSUE THREAD

**Issue by zenhighzer** [gerbera/gerbera#1464]
Hi, 
i dont know how to really setup gerbera in container on raspberry pi:
i tried the following: 

docker run --name gerbera --network=host -v $PWD/content:/content:ro gerbera/gerbera
-> container wont start: 
error: [/gerbera_build/src/config/config_manager.cc:1058] load Error: Directory '/var/run/gerbera/.config/gerbera' does not exist 

then i did: 
docker run --rm gerbera/gerbera gerbera --create-config > config.xml
and started again with: 

docker run --name gerbera -dit --network=host -v $PWD/content:/content:ro -v $PWD/config.xml:/var/run/gerbera/.config/gerbera/config.xml gerbera/gerbera

container seems to start, but web-ui says:
- 500 Internal Server Error

"docker logs gerbera" says: 
libupnp ThreadPoolAdd too many jobs: 100
libupnp ThreadPoolAdd too many jobs: 100
libupnp ThreadPoolAdd too many jobs: 100
[..]

Am i doing something wrong? 
Best Regards
Zen

**Comment by whyman** [comment]
Hey, this is an issue with libupnp.

Was your libupnp built with `--disable-blocking-tcp` it can help

**Comment by zenhighzer** [comment]
Hi, 
i use the docker-image on https://hub.docker.com/r/gerbera/gerbera
I dont know how it was built to be honest :-/

**Comment by imolb** [comment]
As far as I understand, the current gerbera Dockerfile uses alpine:3.13.
This contains libupnp 1.14.0-r0. (https://pkgs.alpinelinux.org/packages?name=libupnp&branch=v3.13)
According to the build-log
https://build.alpinelinux.org/buildlogs/build-3-13-x86_64/community/libupnp/libupnp-1.14.0-r0.log
it's build **with** blocking_tcp:
`checking for --enable-blocking_tcp_connections... yes`

Is it necessary to make an own build of the libupnp in the Docker-build **without** blocking_tcp?

**Comment by whyman** [comment]
I suppose that building our own libupnp will be needed here.

Until recent times that is what we did anyway (as alpines version is was too old)

**Comment by neheb** [comment]
> I suppose that building our own libupnp will be needed here.
> 
> Until recent times that is what we did anyway (as alpines version is was too old)
> 
> Or we can ask alpine upstream to change their flags.

Alpine also contains libnpupnp.

**Comment by imolb** [comment]
And what's the more constructive approach?
1) Build libupnp with the install-pupnp.sh script.
2) Use the libnpupn from alpine and build gerbera with WITH_NPUPNP=YES.

Approach 1 works for me. For option 2 the build is missing the FindNPUPN.cmake:
```

CMake Error at CMakeLists.txt:334 (find_package):
  By not providing "FindNPUPNP.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NPUPNP", but
  CMake did not find one.

  Could not find a package configuration file provided by "NPUPNP" with any
  of the following names:

    NPUPNPConfig.cmake
    npupnp-config.cmake

  Add the installation prefix of "NPUPNP" to CMAKE_PREFIX_PATH or set
  "NPUPNP_DIR" to a directory containing one of the above files.  If "NPUPNP"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by neheb** [comment]
@imolb https://github.com/alpinelinux/aports/blob/master/community/gerbera/APKBUILD has NPUPNP enabled. I haven't checked recently but I believe it still builds.

**Comment by imolb** [comment]
@neheb I don't believe so, cause the version of libnpupn in alpine 3.13 is just 4.0.14
https://pkgs.alpinelinux.org/packages?name=libnpupnp&branch=v3.13
but with #1388 gerbera requires at least 4.1.2
https://github.com/gerbera/gerbera/blob/a639a4eca10f008ec86431620c718d698ee54032/CMakeLists.txt#L332
And even in alpine edge only 4.1.1 is available.

So we end up with the similar problem for the docker: The lib of libupnp has wrong compile options, and libnupnp is too old.

**Comment by neheb** [comment]
Sent a merge request for gerbera and libnpupnp : https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/21848

**Comment by imolb** [comment]
Great!
I can confirm the successful docker build with libnupnp, when using alpine:edge.

@zenhighzer Solves this your problem? You've to build the docker image your self with libnpupnp support based on alpine:edge, .e.g. use my fork:
`# docker build https://github.com/imolb/gerbera.git#docker-npupnp`

**Comment by neheb** [comment]
Just ran into this. Specifically with the MariaDB backend.
