### ISSUE TITLE
Cannot add new item of external link type with a title or location containing "?" (question mark) to database

### ISSUE THREAD

**Issue by 1a2m3** [gerbera/gerbera#1468]
Running Gerbera 1.8.1 on 12.2-RELEASE-p6 amd64. 

Adding a new item of External Link type with a title, or a title and location containing question marks to database results in error.

![image](https://user-images.githubusercontent.com/65949266/119247668-7c248000-bb40-11eb-8d41-445f5b51680b.png)

JSON response:

`{"success":false,"error":{"text":"no session id given","code":400}}`

No session ID error is bogus, because removing question marks from the title and location fields works fine.

If I try to add an item with question mark only in the location field, the JSON response is different:

`{"success":false,"error":{"text":"Error: [/wrkdirs/usr/ports/net/gerbera/work/gerbera-1.8.1/src/web/add_object.cc:123] process Error: empty class","code":800}}`

Mediatomb didn't have this problem.

**Comment by KarlStraussberger** [comment]
Thanks for reporting. It got introduced long time ago.
