### ISSUE TITLE
Items with a "+" (plus sign) in their name end up without having "+"

### ISSUE THREAD

**Issue by 1a2m3** [gerbera/gerbera#1470]
Adding a new container or an external link item to database with a plus sign in their names results in items ending up without the plus sign.

![image](https://user-images.githubusercontent.com/65949266/119287777-0a117100-bbfc-11eb-8e92-38fba5ef1ad6.png)

![image](https://user-images.githubusercontent.com/65949266/119287873-52c92a00-bbfc-11eb-8ed3-7240194753f4.png)

**Comment by whyman** [comment]
Nice spot, we should escape that!
