### ISSUE TITLE
Gerbera stops working after a while - database issues?

### ISSUE THREAD

**Issue by St3ll4rM4n** [gerbera/gerbera#1480]
Im using Ubuntu 20.04.2 LTS with Gerbera 1.8.1 (from apt - gerbera.jfrog.io).

After a day of working the gerbera stops it's upnp server and general doesn't work. The WWW is still available but connection to database is lost.

The following errors are available in logs.

`
May 27 22:43:10 myserver gerbera[591280]: 2021-05-27 22:43:10   info: Exception: Mysql: error while updating db: mysql_error (4031): "The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior."; query: START TRANSACTION
May 28 21:06:30 myserver gerbera[591280]: 2021-05-28 21:06:30 warning: Web Error: 500 mysql_error (4031): "The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior."
`

I switched to mysql as I had the same behaviour with sqlite and thought maybe it's broken. However it crashes on both sqlite and mysql databases.

Here are the sqlite errors
`
May 16 21:28:15 myserver gerbera[72388]: 2021-05-16 21:28:15  error: prematurely shutting down.
May 16 21:28:15 myserver gerbera[72388]: 2021-05-16 21:28:15  error: prematurely shutting down.
May 16 21:28:15 myserver gerbera[72388]: 2021-05-16 21:28:15  error: [/__w/gerbera/gerbera/src/database/sqlite3/sqlite_database.cc:356] exec Error: [/__w/gerbera/gerbera/src/database/sqlite3/sqlite_database.cc:435] addTask Error: sqlite3 task queue is already closed
May 16 21:28:15 myserver gerbera[72388]: 2021-05-16 21:28:15  error: prematurely shutting down.
May 16 21:28:15 myserver gerbera[72388]: 2021-05-16 21:28:15  error: prematurely shutting down.
`

Any thoughts?

**Comment by KarlStraussberger** [comment]
Thanks for you report even if it means trouble.

At least the sqlite topic is known and - hopefully - fixed.

In order to reproduce the mysql issue, we need as much details as you can gather.

If you are bored by all this, you can turn off transactions: https://docs.gerbera.io/en/stable/config-server.html#storage

**Comment by St3ll4rM4n** [comment]
I can confirm that setting
`    <storage use-transactions="no">`
in the config.xml file did the trick.

It's interesting as I'm using Gerbera for more than few years now and never had such an issues before.

Anyway, glad that this is working now.

**Comment by KarlStraussberger** [comment]
Not very astonishing that you did not have similar issues, because transactions are new 1.8.

To allow further testing transactions with multithreading, transactions have been disabled in 1.8.2.

**Comment by hkirschk** [comment]
Just for the records, I observed the same behaviour for gerbera v1.8.2-5-gc838aae2 and mysql Ver 8.0.25 for FreeBSD12.2 on amd64. To fix this, I increased both the interactive_timeout and wait_timeout to 86400, i.e. one day.

`cat /usr/local/etc/mysql/my.cnf`
`[server]`
`...`
`interactive_timeout = 86400`
`wait_timeout = 86400`
