### ISSUE TITLE
Testing gerbera in ARMv7

### ISSUE THREAD

**Issue by bezze** [gerbera/gerbera#149]
I've successfully compiled gerbera in my RPi 3 running arch. At first glance the servers seems to work fine, but when I try to play any song it starts ~1 minute ahead. The song file length is not read correctly and displays an impossible number like "24:01:54". When I try to seek the server logs this:

>2017-09-11 12:27:50   ERROR: web_seek(): Exception during seek: fseek failed
>Exception raised in [src/file_io_handler.cc:105] seek(): fseek failed

**Comment by v00d00** [comment]
Hey. Are you running 1.0? It is known to have issues on RPi . You should build from master, it's all fixed there.

1.1 will be released soon hopefully.

**Comment by bezze** [comment]
Yes. I'm running 1.0.0. I'll try master and report back. Thanks!

**Comment by bezze** [comment]
Works like a charm with 1.1.0_alpha on armv7. I'll let you know if I find anything else. Infinite gratitude!

**Comment by v00d00** [comment]
Glad to hear it!
