### ISSUE TITLE
docker-compose instructions does not declare volume

### ISSUE THREAD

**Issue by hmoffatt** [gerbera/gerbera#1496]
The instructions for docker-compose reference a volume called gerbera-config, but it is not declared, so starting the container fails with

```
ERROR: Named volume "gerbera-config:/var/run/gerbera:rw" is used in service "gerbera" but no declaration was found in the volumes section.
```

The container needs to be declared with
```
volumes:
  gerbera-config: {}
```

However, I don't think a named volume is a good idea for the config anyway because then it's not easily able to be edited from the host. (Named volumes are stored in Docker's private directories). It would be better to use a local directory with a bind mount. ie:

```
services:
  gerbera:
...
    volumes:
      - ./config:/var/run/gerbera
```

**Comment by whyman** [comment]
Hi @hmoffatt!

I think you are entirely right here, would you be able to put together a PR to update it?

**Comment by KarlStraussberger** [comment]
#3260
