### ISSUE TITLE
CI: clang linking broken

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#1507]
@whyman Do you have any clue how to fix linking. It terminates with`undefined reference to std::__throw_bad_array_new_length()@GLIBCXX_3.4.29` which tells me that a core package is build against the wrong library, but I could not circle it.

**Comment by whyman** [comment]
In the CI?

**Comment by whyman** [comment]
Hmm, looks like its libspdlog as you will have seen... I guess the package was built against a different glibc version

**Comment by whyman** [comment]
Looks like the clang11 images are built on `bionic`: https://github.com/conan-io/conan-docker-tools/blob/004c777fb608152ecb071e719df9d5f7f9b2f5c0/clang_11/Dockerfile#L1

**Comment by whyman** [comment]
So I wonder if we should switch that CI job to 18.04 specifically?

**Comment by KarlStraussberger** [comment]
I did not try that, yet. Let me see later.
