### ISSUE TITLE
No ubuntu repository for Hirsute Hippo 21.04

### ISSUE THREAD

**Issue by jonathanrwatts** [gerbera/gerbera#1509]
I just upgraded my system from Kubuntu 20.10 to 21.04, and Gerbera stopped working.  Before trying to troubleshoot, I figured I should make sure I have the latest version, and tried adding the ubuntu repository back (following the instructions for the latest tagged release here:  https://docs.gerbera.io/en/stable/install.html ), only to discover there is no hirsute repository.

**Comment by jonathanrwatts** [comment]
I have no experience with compiling from source; I did install git and cmake and tried cloning and compiling the repo, but I'm missing the source for all the dependencies and not sure how to proceed.

**Comment by KarlStraussberger** [comment]
Thanks for your efforts.

You may just perform the `run` commands from https://github.com/gerbera/gerbera/blob/master/.github/workflows/publish-deb.yml if you want to be the first to run gerbera on 21.04 :smile:

**Comment by jonathanrwatts** [comment]
tried to run "scripts/debian/build-deb.sh", got the following error:
`Ign:8 https://gerbera.jfrog.io/artifactory/debian hirsute InRelease                                       
Err:9 https://gerbera.jfrog.io/artifactory/debian hirsute Release
  404  Not Found [IP: 34.105.229.119 443]
Reading package lists... Done
E: The repository 'https://gerbera.jfrog.io/artifactory/debian hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.`

**Comment by KarlStraussberger** [comment]
Looks like `ART_API_KEY` is set. Please call

```
unset ART_API_KEY:
```

before running `build-deb.sh`

**Comment by jonathanrwatts** [comment]
That got me a bit farther, but I end up with `CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find libuuid (missing: libuuid_FOUND)`

**Comment by KarlStraussberger** [comment]
Seems one additional package has to be installed 

```
sudo apt install -y uuid-dev
```

**Comment by jonathanrwatts** [comment]
I also needed to add `libpugixml-dev` `libsqlite3-dev` `duktape-dev` `libmysql++-dev`, but now I'm stuck on CURL, as I'm not sure which of the many packages that include "curl" and "-dev" in their names is the one I actually need (those others were obvious).

**Comment by KarlStraussberger** [comment]
build-dep.sh contains the following lines

```
 mkdir build-deb

  echo "::group::Installing dependencies"
  sudo apt-get update
  sudo apt-get install -y \
      dpkg-dev \
      systemd \
      wget autoconf libtool pkg-config \
      cmake \
      bsdmainutils \
      duktape-dev \
      libavformat-dev \
      libcurl4-openssl-dev \
      libduktape205\
      libebml-dev \
      libexif-dev \
      libffmpegthumbnailer-dev \
      libmagic-dev \
      libmatroska-dev \
      libmysqlclient-dev \
      libpugixml-dev \
      libsqlite3-dev \
      libtag1-dev \
      uuid-dev
```
Maybe that helps to complete. Wonder why it did not pull when you first called it.

**Comment by KarlStraussberger** [comment]
Duktape may be 206 already

**Comment by jonathanrwatts** [comment]
Well, I now have a .deb file to install, so apparently `duktape-dev` was good enough.

**Comment by jonathanrwatts** [comment]
And I now have a working Gerbera installation again (at least, the web interface works; haven't tried actually streaming any media yet)!

**Comment by KarlStraussberger** [comment]
Would be great if you could sum up all your packages.

Thanks a lot!

**Comment by jonathanrwatts** [comment]
What do you mean by "sum up all my packages"?

**Comment by KarlStraussberger** [comment]
Well, I need the complete list of packages you installed to update the build-script so the next release can be built automatically for 21.04

**Comment by jonathanrwatts** [comment]
It's already in the comment above (other than `uuid-dev`).  Although, I did install git and cmake previously.

**Comment by jonathanrwatts** [comment]
> Maybe that helps to complete. Wonder why it did not pull when you first called it.
It didn't pull because that was when I got the first error (about the repository not having a Release file), and then it never ran again because the folder already existed.

**Comment by jonathanrwatts** [comment]
Hmm, something isn't quite right.  After rebooting my computer, Gerbera didn't start properly.  `service gerbera status` shows `Initialising UPnP with interface: <unset>, port: <unset>`.  Restarting the service fixes the problem.

**Comment by KarlStraussberger** [comment]
Looks like you started gerbera too early. The network has to be up incl. routing before gerbera is able to announce its network services.

**Comment by jonathanrwatts** [comment]
So, how do I start gerbera later, then?

**Comment by KarlStraussberger** [comment]
If you're having systemd it's the line `After=mysql.target network.target` in [Unit] section.

If you have a startup script in init.d you need to pick a number greater than your network setup.

**Comment by jonathanrwatts** [comment]
gerbera.service already contains `After=mysql.target network.target`.  Any other ideas?

**Comment by whyman** [comment]
Probably worth changing that our version too

**Comment by jonathanrwatts** [comment]
OK, adding `network-online.target` to both `After` and `Wants` seems to have fixed the issue.  Thanks for the help!
