### ISSUE TITLE
How to enable WebUI on https instead of http

### ISSUE THREAD

**Issue by NetDevils** [gerbera/gerbera#1511]
Hi there,
really liking Gerbera as an alternative to Serviio on my Pi! Nice job.

Just wanted to check if there is any option to switch the WebUI to https instead of http? I have not found a setting anywhere.

Cheers

**Comment by whyman** [comment]
We dont support HTTPS for the UI. You can put it behind a proxy of some kind (nginx, caddy) if you like.

**Comment by NetDevils** [comment]
> We dont support HTTPS for the UI. You can put it behind a proxy of some kind (nginx, caddy) if you like.

Did so. Thanks!

**Comment by Sithuk** [comment]
@NetDevils Could you paste your nginx config? I’m trying to get nginx to work as a reverse proxy to avoid having to type the port number to access the webui. Gerbera doesn’t appear to be accessible through localhost so I’m not sure what to put in the proxy pass part of the nginx config.

**Comment by NetDevils** [comment]
Hi @Sithuk: I am using Apache not ngnix.

But for the sake of completeness this is my setup::

Activate mods for Apache: `sudo a2enmod proxy proxy_http ssl`
In `/etc/gerbera/config.xml` I set my server port to 55555, thus Gerbera is listening for http there.
In `/etc/apache2/sites-available/default-ssl.conf` I set my virtual host to listen on https on 44444 and re-route to http 55555

```
<VirtualHost *:44444>
  ServerName NAMEOFMYSERVER
  ServerAlias NAMEOFMYSERVER
  
  SSLProxyEngine on
  SSLProxyVerify none 
  SSLProxyCheckPeerCN off
  SSLProxyCheckPeerName off
  SSLProxyCheckPeerExpire off
  ProxyPreserveHost off
  
  ProxyPass / http://NAMEOFMYSERVER:55555/
  ProxyPassReverse / http://NAMEOFMYSERVER:55555/
  
  SSLEngine on
  SSLCertificateFile	/path/to/my/servers-own-cert-file.crt
  SSLCertificateKeyFile /path/to/my/servers-own-key-file.key
</VirtualHost>
```

And in `/etc/apache2/ports.conf` tell Apache to listen on that port:
```
<IfModule ssl_module>
  Listen 44444
</IfModule>

```

**Comment by Sithuk** [comment]
I've changed the Gerbera webui port to 55555 and enabled accounts in the Gerbera config file (/etc/gerbera/config.xml). I now get a username and password prompt. I can enter the username and password and a webpage loads. Unfortunately there is no content. The page has white lines marking out the page frames, but no content. There is a "mediatomb" graphic placeholder at the top.
My nginx config is as follows and is saved in /etc/nginx/conf.d/ Do you know what the problem might be? The webui loads perfectly if I access directly using gerbera.lan:55555.
----------------------------
server {
    listen 80;
    server_name gerbera.lan;

    location / {
        proxy_set_header   X-Real-IP        $remote_addr;
        proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_pass         http://gerbera.lan:55555;

    }
}

**Comment by KarlStraussberger** [comment]
Did you set virtualURL in config.xml?

You may also need a / in the end of the proxy_pass URL

**Comment by KarlStraussberger** [comment]
Let's switch the discussion to #1531
