### ISSUE TITLE
Database failure in AUR instance of gerbera

### ISSUE THREAD

**Issue by ValeraBahleiUA** [gerbera/gerbera#1524]
Installed gerbera from AUR. Webui works, but the program does not function. Throws following error message:
```
2021-06-06 18:18:20   info: Gerbera UPnP Server 1.8.1 - http://gerbera.io/
2021-06-06 18:18:20   info: Copyright 2016-2021 Gerbera Contributors.
2021-06-06 18:18:20   info: Gerbera is free software, covered by the GNU General Public License version 2
2021-06-06 18:18:20   info: Loading configuration from: /etc/gerbera/config.xml
2021-06-06 18:18:20   info: Checking configuration...
2021-06-06 18:18:20   info: Configuration check succeeded.
2021-06-06 18:18:20  error: [/home/fhpcuser/.cache/yay/gerbera/src/gerbera-1.8.1/src/database/sqlite3/sqlite_database.cc:182] init Error: Sqlite3Database.init: could not open '/home/fhpcuser/.config/gerbera/gerbera.db' exclusively

```
My guess is  something wrong with gerbera user groups or something, as here on arch I had to give permissions i don't recall giving back on ubuntu...
(the _useradd_ seems to be performed  automatically during installation)
`groups gerbera ` command outputs only `video gerbera`
don't know if it's correct.
Would be heavenly glad if someone from the wise people helped me. Where should I look?

**Comment by ValeraBahleiUA** [comment]
inbf: gerbera home folder permissions set like this:
```
drwxr-xr-x  2 gerbera  gerbera  4096 Jun  6 16:38 .
drwxr-xr-x 13 fhpcuser users    4096 Jun  7 02:57 ..
-rwxr-xr-x  1 gerbera  gerbera 73728 Jun  6 06:30 gerbera.db
-rwxr-xr-x  1 gerbera  gerbera     0 Jun  6 16:38 gerbera.db-wal
-rwxr-xr-x  1 gerbera  gerbera   108 Jun  6 16:52 gerbera.html

```

**Comment by KarlStraussberger** [comment]
Looks like an issue with file access to me. Don't know your particular setup, so you need to give some more details like config.xml section of sqlite, directory listing with db file.

On the other hand you should get hold of 1.8.2 because 1.8.1 has some flaws with transactions which you should turn off in 1.8.1

**Comment by KarlStraussberger** [comment]
How do you start gerbera, does it really run under user gerbera?

**Comment by ValeraBahleiUA** [comment]
My config is default the database section is default as well
```
<storage>
      <sqlite3 enabled="yes">
        <database-file>gerbera.db</database-file>
      </sqlite3>
```
i may be stewpid, but that file:
`/home/fhpcuser/.cache/yay/gerbera/src/gerbera-1.8.1/src/database/sqlite3/sqlite_database.cc` actually did not exist...
the  "/gerbera-1.8.1/" folder laid there archived and even if untarred, the path had one of the /src/ folders omitted
but even if restoring everything manually the problem remains the same. Here is the exact check in sqlite_database.cc that throws this error:
```
    // try to detect already active database client and terminate before doing any harm
    try {
        prepare();
    } catch (const std::runtime_error& e) {
        shutdown();
        throw_std_runtime_error("Sqlite3Database.init: could not open '{}' exclusively", dbFilePath);
    }

```

> How do you start gerbera
Through systemctl, if everything works fine. But here it won't start in any way

**Comment by KarlStraussberger** [comment]
I'm not sure about the reason of you crash but maybe you try to turn off transactions
`<storage use-transactions="no">`
