### ISSUE TITLE
SIGHUP does not re-open log file

### ISSUE THREAD

**Issue by jcowgill** [gerbera/gerbera#154]
Please can the log file be closed and re-opened when Gerbera receives a SIGHUP signal. This allows utilities such as logrotate to work properly.

**Comment by v00d00** [comment]
Signal handling is a mess right now to be frank. I am gradually working through the initialisation stages and removing singletons which helps towards re-factoring that kind of behaviour, but its not going to be done for a while.

**Comment by KarlStraussberger** [comment]
We are using spdlog::drop to close the output. Testers are welcome 😸
