### ISSUE TITLE
docker image has no timezone information

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1545]
This causes issues with the time being set to UTC, even with a TZ env variable being passed.

**Comment by neheb** [comment]
Apparently only

```
apk add tzdata
```

is needed.

**Comment by whyman** [comment]
PR welcome!

**Comment by whyman** [comment]
Fixed in #1546

You will need to use a git image to get until the next official release is cut.

**Comment by neheb** [comment]
no worries.
