### ISSUE TITLE
Can Duktape source be included as per their usage instead of as a library

### ISSUE THREAD

**Issue by SheamusPatt** [gerbera/gerbera#155]
Hi. I'm attempting to build gerbara on a Debian Stretch system. I've navigated past the upnp version issues (like FreeBSD, Stretch has an older version than the 1.8 version required, so I've built it from source). However, now I'm stuck on Duktape. This package (actually, duktape-dev) does exist but does not include a library, just the C source and header files. This seems completely in line with how the Duktape maintainers describe it being used however http://duktape.org/ .
Can the Gerbara build be updated to directly include the duktape engine as source, instead of a library, to be consistent with the maintainer's instructions? (Or perhaps do both, perhaps by checking if DUKTAPE_LIBRARY points to a real library)? Otherwise, building on platforms that are simply following Duktape's instructions will have to do some non-scripted work to create the library for gerbara.
WITH_JS=0 is not an option for me; scripting is the main capability I would like to use in Gerbara.
Thanks.

**Comment by elmodaddyb** [comment]
@SheamusPatt - the duktape library is referenced as a shared library in the Gerbera build. 

There is a script under **scripts/install-duktape.sh** that calls the shared library Makefile for duktape. Thus installing it locally and making it referenceable to the gerbera compilation. 

The setup you describe ( including duktape.c directly ) was how gerbera worked initially. We opted for the shared library to avoid close coupling the two implementations.

**Comment by SheamusPatt** [comment]
That works for me. Might be worth a small pointer in your README.md file about the purpose of these scripts, perhaps in a "Pre-Build" section.
I don't think I agree with your rational for altering duktape's packaging process, though. They have gone so far as to put the entire library into a single source file, so it's likely not possible to wander outside of the declared API. Depending on your custom built-and-installed duktape shared library will make it difficult to package up a genberra build for use on other systems, and I think is actually exposing a security hole since "hackers" will find it easier to call into the JS engine than if it were compiled in as they recommend.
Thanks, though.

**Comment by elmodaddyb** [comment]
Good to hear you successfully built the gerbera runtime.  Thanks for the insight regarding the packaging.
We would have to think about how to pull in the correct version of the Duktape source at build time.  I guess it could be done via cmake?

**Comment by SheamusPatt** [comment]
If duktape-dev is in the package repository, then there would be no need to "pull in" a version, just use what's installed. Locating it might be a trick because it's not in /usr/include or /usr/lib - Debian puts it in /usr/share/duktape though other distributions might differ.

**Comment by michael-o** [comment]
@SheamusPatt I am planning to make Gerbera along with its dependencies available as a FreeBSD port. As for Duktape, why do you want to amalgamate it? You can put everything to `/usr/local/gerbera` and reference to it until the port is available.

**Comment by SheamusPatt** [comment]
I'm not so familiar with FreeBSD, but if it follows the Filesystem Hierarchy Standard, ( http://www.pathname.com/fhs/pub/fhs-2.3.pdf ) then putting private libraries in /usr/local/**lib**/gerbera would work.(/usr/local is not allowed though). If you're actually planning to make a package available to others, though, I would expect gerbara to be in /usr/bin and the libraries in /usr/lib/gerbera. 
My main reason for preferring that it be compiled in is that the duktape maintainers prefer it that way, and it's available for Debian in a way that supports this approach whereas no library is provided. It also seems somewhat more secure, as if one were able to run foreign code within Gerbera, it's much simpler to locate methods in a shared library than in a stripped executable, and a Javascript engine seems to be a very dangerous capability to expose.

**Comment by michael-o** [comment]
> I would expect gerbara to be in `/usr/bin` and the libraries in `/usr/lib/gerbera`.

No, this is broken by default. Software which does not come with the base system always goes to `/usr/local`.

Works for me with: 

    make -f Makefile.sharedlibrary
    $ file libduktape.so.201.20101
    libduktape.so.201.20101: ELF 32-bit LSB shared object, Intel 80386, version 1 (FreeBSD), dynamically linked, not stripped

    $ ldd ./gerbera
    ./gerbera:
            libthr.so.3 => /lib/libthr.so.3 (0x28275000)
            libiconv.so.2 => /usr/local/lib/libiconv.so.2 (0x28298000)
            libupnp-1.8.so.10 => /usr/local/gerbera/lib/libupnp-1.8.so.10 (0x2838d000)
            libixml-1.8.so.10 => /usr/local/gerbera/lib/libixml-1.8.so.10 (0x283c2000)
            libexpat.so.1 => /usr/local/lib/libexpat.so.1 (0x283cc000)
            libsqlite3.so.0 => /usr/local/lib/libsqlite3.so.0 (0x283f2000)
            libinotify.so.0 => /usr/local/gerbera/lib/libinotify.so.0 (0x2850a000)
            libduktape.so.201 => /home/mosipov/Projekte/duktape-2.1.1/libduktape.so.201 (0x28512000)
            libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x2855d000)
            libmagic.so.4 => /usr/lib/libmagic.so.4 (0x285b3000)
            libz.so.6 => /lib/libz.so.6 (0x285d2000)
            libc++.so.1 => /usr/lib/libc++.so.1 (0x285e8000)
            libcxxrt.so.1 => /lib/libcxxrt.so.1 (0x286a6000)
            libm.so.5 => /lib/libm.so.5 (0x286bf000)
            libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x286e7000)
            libc.so.7 => /lib/libc.so.7 (0x286f3000)
            libssl.so.8 => /usr/lib/libssl.so.8 (0x28852000)
            libcrypto.so.8 => /lib/libcrypto.so.8 (0x288ac000)

I see no reason why this should not work on Debian.

**Comment by SheamusPatt** [comment]
Not quite. You're loading libduktape from your build directory, which won't work on someone else's system.
Still, with a bit of effort, it can be made to work.

- build the necessary dependencies (duktape, pupnp) into a private directory eg. `/usr/local/lib/gerbera `(or perhaps `/usr/local/lib/gerbera/lib,` as the build structure for duktape and pupnp will support this via an install path of `/usr/local/lib/gerbera `(they will append /lib).
- link gerbera so that it will look in its private directory for libraries. The ld -rpath option would do this eg. `gcc -Wl,rpath=/usr/local/lib/gerbera/lib`

**Comment by michael-o** [comment]
The private directory is just an example. After successful verification, I'd install anything to `/usr/local` and this will comply with the FHS.

**Comment by SheamusPatt** [comment]
The FHS is pretty clear that only certain predefined subdirectories can go in `/usr/local`, which is why I proposed `/usr/local/lib/gerbera `. See http://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.pdf which seems to be a current version, section 4.9.

**Comment by v00d00** [comment]
I have no intention of doing this, but would be open to somebody else opening it.

Building the shared library from an upstream provided Makefile seems sensible to me. We could perhaps make it more clear in the README though.
