### ISSUE TITLE
Gerbera 1.8.2 on Ubuntu 21.04 Hirsute on Raspberry Pi

### ISSUE THREAD

**Issue by samf74** [gerbera/gerbera#1571]
I'm trying to upgrade Gerbera from an old version 1.1 to 1.8.2 on ubuntu 21.04 running on a raspberry pi. 
The current build doesn't support architecture 'arm64'

See below when trying to add the git repository:
 Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://gerbera.jfrog.io/artifactory/debian-git hirsute InRelease' doesn't support architecture 'arm64'

**Comment by KarlStraussberger** [comment]
Thank you for pointing to it. Currently, we're happy to provide prebuilds for amd64 and i386. arm architecture is waiting for appropriate time, knowledge and support. So you are invited to fill in that gap.

**Comment by KarlStraussberger** [comment]
duplicates #1467
