### ISSUE TITLE
ERROR: ActionRequest::update(): response is nullptr, code -115

### ISSUE THREAD

**Issue by vasyugan** [gerbera/gerbera#158]
I have compiled and installed gerbera on a raspberrypi 3 with Arch Linux Arm from AUR.

After starting it, the clients see the server, but there is nothing in the library, even though several directories are indexed. I am using MariaDB.

In the system log I see:

Sep 19 11:34:06 raspberrypi gerbera[18474]: 2017-09-19 11:34:06   ERROR: ActionRequest::update(): response is nullptr, code -115

**Comment by elmodaddyb** [comment]
The return code `-115`, is coming from the underlying `UPNP` library.
https://github.com/mrjimenez/pupnp/blob/f07f07857560344a0b5fbf9c4cffb8f2de45fa5f/upnp/inc/upnp.h#L182

It sounds like the Request DOM XML object is malformed somehow.  I wonder if it has to do with the issues with ARM compilation on 1.0.0?

Does `master` build helps resolve?

> If not, what type of _UPNP device_ are you hitting your gerbera instance with?  Maybe you need to enable the extended protocol info similar to #123.

**Comment by vasyugan** [comment]
I have been trying with BubbleUPN and Rhythmbox mainly. In a built from the code I directly checked out frome github, it seems fixed.

**Comment by elmodaddyb** [comment]
That's great news.  I've used primarily systems using VLC (Linux, Apple tvOS), PS3 and PS4 Media Player.  I think we still have some issues with Samsung smart TV's.  It good to hear the clients used!

**Comment by elmodaddyb** [comment]
I think we can mark this issue for resolution when v1.1 is released

**Comment by v00d00** [comment]
As @elmodaddyb mentions, this is fixed in master and will be in 1.1

**Comment by zyxmon** [comment]
It is not fixed in 1.1 (entware-3x on armv7). I have 

```
2017-10-03 08:03:06   ERROR: ActionRequest::update(): response is nullptr, code -115
2017-10-03 08:03:06   ERROR: ActionRequest::update(): response is nullptr, code -115
2017-10-03 08:03:06   ERROR: ActionRequest::update(): response is nullptr, code -115
2017-10-03 08:14:21   ERROR: ActionRequest::update(): response is nullptr, code 706
```

When trying to play videos on samsung. The recipe for mediatomb with custom headers + mimetype map did not help (video format not recognized). VLC does   not "see" gerbera. Windows media player played a couple of avi's.

**Comment by v00d00** [comment]
@zyxmon can you get a packet capture when you are running it?

`tcpdump -i <interface> -s 65535 -w <some-file>`

**Comment by v00d00** [comment]
Also, note that you might need to build with `-DPROTOCOL_EXTENSIONS=1` and that Gerbera does not support custom headers (as they are not supported in upstream libupnp, yet).

**Comment by zyxmon** [comment]
I'll try to make packet capture later.
FYI - I have installed gerberа 1.1 on three arm devices. In two cases i had to specify port via command line `-p num` for gerbera to start. Without port  definition - 

```
Exception raised in [src/server.cc:123] upnp_init(): upnp_init: UpnpInit failed
2017-10-01 23:29:56   ERROR: main: upnp error -203
2017-10-01 23:29:56   ERROR: Could not bind to socket.
```

It looks like libupnp issue.

**Comment by zyxmon** [comment]
Here is the dump - http://entware-3x.zyxmon.org/binaries/other/gerbera.tar.gz
Gerbera is started on host with ip=10.0.0.36/24
Compile info

```
# gerbera --version

Gerbera UPnP Server version 1.1.0 - http://gerbera.io/

===============================================================================
Gerbera is free software, covered by the GNU General Public License version 2

Copyright 2016-2017 Gerbera Contributors.
Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
===============================================================================
Compile info:
-------------
WITH_MAGIC=1
WITH_MYSQL=0
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=1
WITH_TAGLIB=0
WITH_AVCODEC=1
WITH_FFMPEGTHUMBNAILER=0
WITH_EXIF=1
WITH_EXIV2=0
WITH_PROTOCOL_EXTENSIONS=1
WITH_LASTFM=0
WITH_LOGGING=
WITH_DEBUG_LOGGING=0
```

**Comment by v00d00** [comment]
Thanks, I should hopefully get a chance to take a look in the next few days.
