### ISSUE TITLE
Problems changing gerbera database from Sqlite to MySQL

### ISSUE THREAD

**Issue by geno11x11** [gerbera/gerbera#1586]
**The short story:** Gerbera has been working flawlessly for months on my **OpenSuse 15.2** server. However I recently installed an application that required **MySQL (MariaDB)**. During installation, Packager required **deinstallation of Sqlite3**. Since I remembered from the Gerbera installation that MySQL was supported, I allowed Packager to continue, and Gerbera was summarily broken. 

Getting into the fix, apparently my installation of Gerbera was compiled without **MySQL** support. I've investigated all of the online documentation I have found but have not yet found a solution.

In one, https://github.com/gerbera/gerbera/blob/ff76162d03e5b6ffcfe2f220f5ad5b755b5ca92e/doc/run.rst, there appear to be omissions and errors i.e., _If database auto creation was not compiled in you have to create the **tables** manually_. But to create a table you must have a schema which appears to be auto-created by Gerbera - Did the author mistakenly use the word "table", intending "database"? The author also commented, "_After creating the database and making the **appropriate changes** in your Gerbera config file you are ready to go_". Please elaborate on the **appropriate changes** in a newbie fashion.

I have created an **MySQL database** at /etc/gerbera/gerbera.sql - which is the **home path** in config.xml. It has a user named gerbera and rights, but no table. To create a table I need at least one column, and the full build will require a schema to follow.

So I need more information: A guide to reconfiguring config.xml for MySQL would be very helpful. This is what I have for a start, using the Sqlite3 entries as an example:

```
<storage>
 <!--
              <sqlite3 enabled="yes">
              <database-file>gerbera.db</database-file>
              </sqlite3>
 -->
              <mysql enabled="yes">
              <database-file>gerbera.sql</database-file>
              </mysql>
</storage>
```

A sample of code lines to copy & paste would be great. Chances are I can manage the changes with the accompanying comments, but I would greatly appreciate guidance as well.

Thanks alot,

Geno

**Comment by KarlStraussberger** [comment]
Hi Geno,

to be at bit more helpful than your former source of information, can you point to your installation package and the installation manual.

**Comment by geno11x11** [comment]
I installed version 1.7.0 using YAST from: https://software.opensuse.org/ymp/home:lineinthesand/openSUSE_Leap_15.2/gerbera.ymp?base=openSUSE%3ALeap%3A15.2&query=gerbera

For installation procedures: https://docs.gerbera.io/en/latest/config-overview.html
Also, by searching Github/Gerbera Issues, and searches of the web.

**I note that version 18.2 is available from OpenSuse.Org. Would that upgrade 1) overwrite the current configuration files and 2) might it fix the MySQL problem during installation?

**Comment by geno11x11** [comment]
**UPDATE:** I installed gerbera 1.8.2 and created a fresh config.xml file. Specifying the route to config.xml, the gerbera server now runs with an error that it is unable to find SQLITE3 (recall it was deinstalled when MariaDB was installed). 

The web UI is functional but shows an empty database. When I go to Config-->Storage there are entries for both **SQLITE3 and MySQL** but everything is grayed out and nothing can be changed. 

In /etc/gerbera/config I changed the home path, and disabled SQLITE3. I noted there is nothing in config.xml referring to **MySQL**. Afterward, the gerbera server would not start. So I re-enabled SQLITE3 and at least have a running server although there is no running database.

So, I've made a few small steps forward. 

**Questions:**

**1. What must be done to access MySQL?** The steps found in the documentation do not do the trick - there are apparently other changes needed.

**2. In the UI, File System only shows the system drive.** My media files are on another mounted drive. I know how to manually change the path in config.xml but my understanding was that a method to navigate to another mounted drive would be one of the upgrades featured in 1.8.x.

Thx again,

Geno

**Comment by KarlStraussberger** [comment]
In order to get MySQL running your config.xml should look like
```
<sqlite3 enabled="no">
    <database-file>/etc/gerbera/gerbera.db</database-file>
    <synchronous>off</synchronous>
    <on-error>restore</on-error>
    <backup enabled="yes" interval="600"/>
</sqlite3>
<mysql enabled="yes">
    <host>localhost</host>
    <username>gerbera</username>
    <database>gerbera</database>
</mysql>
```
Before running gerbera you have to follow the steps for MySQL https://docs.gerbera.io/en/stable/run.html#using-mysql-database.

As long as your database isn't configured correctly the web UI is not able to store any new settings. Database settings cannot be changed by web, anyway.

The system directories are under _Import_ in expert mode. For normal operation, I recommend changing settings in config.xml because there is no direct way to save them if you have to clear the database (after changing core import settings).

**Comment by geno11x11** [comment]
I made the config.xml changes above and now gerbera won't start.

**/etc/config.xml:**
```
    <storage>
        <sqlite3 enabled="no">
            <database-file>/etc/gerbera/gerbera.db</database-file>
            <synchronous>off</synchronous>
            <on-error>restore</on-error>
            <backup enabled="yes" interval="600"/>
        </sqlite3>
        <mysql enabled="yes">
            <host>localhost</host>
            <username>gerbera</username>
            <database>gerbera</database>
        </mysql>
    </storage>

```
**gerbera start & error message:**

```
# systemctl restart gerbera
# systemctl status gerbera
● gerbera.service - Gerbera Media Server
   Loaded: loaded (/usr/lib/systemd/system/gerbera.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-06-21 10:37:56 PDT; 4s ago
  Process: 4534 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml (code=exited, status=1/FAILURE)
 Main PID: 4534 (code=exited, status=1/FAILURE)

Jun 21 10:37:56 systemd[1]: gerbera.service: Failed with result 'exit-code'.
/etc/gerbera # mysql
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
:/etc/gerbera #
```
Based on the error message above, it appears that gerbera is trying to access MySQL as **root not as gerbera.** The code in config.xml defines the username as gerbera with no password, but that doesn't appear to be recognized when gerbera starts.

**MySQL commands:**

```
# mysql -u gerbera
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 4
Server version: 10.5.10-MariaDB MariaDB Server

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use gerbera
Database changed
MariaDB [gerbera]> show tables
    -> ;
Empty set (0.001 sec)
```

**Comment by geno11x11** [comment]
I changed **[username]** to **[user]** in config.xml and eliminated that error, but there is still a problem.

**/etc/gerbera/config.xml:**
```
        <mysql enabled="yes">
            <host>localhost</host>
-->         <user>gerbera</user>
            <database>gerbera</database>
        </mysql>
```
**Gerbera start and error message:**

```
# systemctl restart gerbera
# systemctl status gerbera
● gerbera.service - Gerbera Media Server
   Loaded: loaded (/usr/lib/systemd/system/gerbera.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2021-06-21 11:15:39 PDT; 3s ago
   Process: 5770 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml (code=exited, status=1/FAILURE)
   Main PID: 5770 (code=exited, status=1/FAILURE)

Jun 21 11:15:39 # systemd[1]: gerbera.service: Failed with result 'exit-code'.
```
Is there a way to test the **gerbera** to **MySQL** connection? ...or do we rely on error messages or the lack of them?

**Comment by KarlStraussberger** [comment]
What happens if you try to start gerbera on the command line?

Well messages typicall increase in density if there are problems in one case or the other. MySQL is not on the list here 😄 

To start from the beginning, please compare the systemd unit file. 
```
[Unit]
Description=Gerbera Media Server with MySQL
After=mysql.target network-online.target

[Service]
Type=simple
User=gerbera
Group=gerbera
ExecStart=/usr/local/bin/gerbera -c /etc/gerbera/config.xml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

You need a local user gerbera (the service switching to this user on startup) and you need to grant this user permissions on your new database. It is also possible to set the password and add this to config.xml in case MySQL blocks the connection (depends on setup)!

**Comment by geno11x11** [comment]
**Great suggestion Karl** - I started gerbera from the command line and got the following error:

```
# gerbera -c /etc/gerbera/config.xml
2021-06-22 11:58:44   info: Gerbera UPnP Server 1.8.2 - http://gerbera.io/
2021-06-22 11:58:44   info: Copyright 2016-2021 Gerbera Contributors.
2021-06-22 11:58:44   info: Gerbera is free software, covered by the GNU General Public License version 2
2021-06-22 11:58:44   info: Loading configuration from: /etc/gerbera/config.xml
2021-06-22 11:58:44   info: Checking configuration...
2021-06-22 11:58:44  error: You enabled MySQL database in configuration, however this version of Gerbera was compiled without MySQL support!
```
So my Gerbera installation **does not include MySQL support**. What are my options? 

- Is it easy to add MySQL support to gerbera? I've never compiled a program, but I learn pretty quickly.
- It seems **inefficient to run two databases** and there is evidence of conflicts from my online research.
- Any other thoughts?

**Comment by KarlStraussberger** [comment]
Suse always had two separate packages to get the installation requirements settled.

Technically we always build with sqlite3 and mysql is the addition. So your rpm should support sqlite and you can run it without a problem. I switch back and forth for testing. Never experienced any conflicts.

The main difference is that sqlite uses its own file(s) while mysql/maria is a full blown database server. Performance is similar. From the admin point of view (backup, permissions), sqlite is simple - mysql requires advanced skills.

**Comment by geno11x11** [comment]
**Gerbera is now up and running** happily once again. 

I can't help but feel resentful over this one -- a whole lot of **wasted hours**. The MySQL installation dialogue indicated that the deinstallation of sqlite3 was a requirement. Yet I just reinstalled and it is humming alongside MySQL with no issues. Further, somehow MySQL support was mysteriously removed from Gerbera without disclosure anywhere in the documentation. In the end, a 20-second sqlite3 installation with no dependencies resolved this whole matter - which could have been done a week ago.

Enough grumbling. I'm very pleased with Gerbera. **Karl, thanks again** for your abundance of patience. It was your last post that suggested the sqlite reinstall. It's doubtful I would have stumbled on that solution otherwise.

**Two more questions:**

1. I have been searching for a list of feature improvements for each version step of Gerbera. Although that web search returns a hit, it points to installation documentation, but no list of improvements. Is there a resource?

2. Since Gerbera is based on MediaTomb, I am curious how features that were already part of MediaTomb are missing from Gerbera. The best example is that the MediaTomb file navigation feature showed all mounted drives while Gerbera does not. Another would be integration with Windows Media Player - Present in MediaTomb and missing in Gerbera.

**Comment by geno11x11** [comment]
Before this thread is closed, **another problem** has arisen:

Gerbera runs fine from the command line: 
# gerbera -c /etc/gerbera/config.xml

But will not run as a service: 
# systemctl status gerbera
● gerbera.service - Gerbera Media Server
   Loaded: loaded (/usr/lib/systemd/system/gerbera.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2021-06-22 16:29:26 PDT; 2s ago
  Process: 20656 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml (code=exited, status=1/FAILURE)
 Main PID: 20656 (code=exited, status=1/FAILURE)

Jun 22 16:29:26 safeandtacticalfirearmstraining.com systemd[1]: gerbera.service: Main process exited, code=exited, status=1/FAILURE
Jun 22 16:29:26 safeandtacticalfirearmstraining.com systemd[1]: gerbera.service: Unit entered failed state.
Jun 22 16:29:26 safeandtacticalfirearmstraining.com systemd[1]: gerbera.service: Failed with result 'exit-code'.

**Comment by KarlStraussberger** [comment]
> 
> 
> **Gerbera is now up and running** happily once again.
> 
> I can't help but feel resentful over this one -- a whole lot of **wasted hours**. The MySQL installation dialogue indicated that the deinstallation of sqlite3 was a requirement. Yet I just reinstalled and it is humming alongside MySQL with no issues. Further, somehow MySQL support was mysteriously removed from Gerbera without disclosure anywhere in the documentation. In the end, a 20-second sqlite3 installation with no dependencies resolved this whole matter - which could have been done a week ago.

Just to cool you down a bit more, MySQL was not removed by the SuSE guys. You switched to a community package because gerbera is not part of the main distro, yet. That package was compiled without MySQL support and maybe others (you should check the spec file of the package). I don't see that mariadb conflicts with sqlite in YAST. Did you install MySQL from elsethere? Blame them!

> **Two more questions:**
> 
>     1. I have been searching for a list of feature improvements for each version step of Gerbera. Although that web search returns a hit, it points to installation documentation, but no list of improvements. Is there a resource?

Go throught the release descriptions https://github.com/gerbera/gerbera/releases 

> 
>     2. Since Gerbera is based on MediaTomb, I am curious how features that were already part of MediaTomb are missing from Gerbera. The best example is that the MediaTomb file navigation feature showed all mounted drives while Gerbera does not. Another would be integration with Windows Media Player - Present in MediaTomb and missing in Gerbera.

- The list of hidden drives has been truncated for security reasons but can be modified https://docs.gerbera.io/en/latest/config-import.html#system-directories
- Windows Media Player works fine (well I don't use it but tested it)

**Comment by KarlStraussberger** [comment]
> 
> 
> Before this thread is closed, **another problem** has arisen:
> 
> Gerbera runs fine from the command line:
> # gerbera -c /etc/gerbera/config.xml
> 
> But will not run as a service:
> # systemctl status gerbera
> 
> ● gerbera.service - Gerbera Media Server
> Loaded: loaded (/usr/lib/systemd/system/gerbera.service; enabled; vendor preset: disabled)
> Active: activating (auto-restart) (Result: exit-code) since Tue 2021-06-22 16:29:26 PDT; 2s ago
> Process: 20656 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml (code=exited, status=1/FAILURE)
> Main PID: 20656 (code=exited, status=1/FAILURE)
> 
> Jun 22 16:29:26 systemd[1]: gerbera.service: Main process exited, code=exited, status=1/FAILURE
> Jun 22 16:29:26 systemd[1]: gerbera.service: Unit entered failed state.
> Jun 22 16:29:26 systemd[1]: gerbera.service: Failed with result 'exit-code'.

Check the file permissions in /etc/gerbera or whereever it writes to. Running from commandline may produce file not accessible by the gerbera user! Also check /var/log/messages for hints why gerbera goes down.

**Comment by geno11x11** [comment]
Looks like I've made a mess. 

When the server boots systemd loads gerbera but the opening dialog does not present the normal message providing the IP address and port number. When I initiate the UI, a message at the bottom says "The System Has Encountered An Error".

From the command line entry and from /var/log/messages there is a common error on the final line ref sqlite db:

```
gerbera -c /etc/gerbera/config.xml
2021-06-23 09:35:01   info: Gerbera UPnP Server 1.8.2 - http://gerbera.io/
2021-06-23 09:35:01   info: Copyright 2016-2021 Gerbera Contributors.
2021-06-23 09:35:01   info: Gerbera is free software, covered by the GNU General Public License version 2
2021-06-23 09:35:01   info: Loading configuration from: /etc/gerbera/config.xml
2021-06-23 09:35:01   info: Checking configuration...
2021-06-23 09:35:01   info: Configuration check succeeded.
2021-06-23 09:35:01  error: [/home/abuild/rpmbuild/BUILD/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:182] init Error: Sqlite3Database.init: could not open '/etc/gerbera/gerbera.db' exclusively
```
Since I was last working on config.xml I created a new one, updated file privileges, but no change.
I also made some file permission changes to the gerbera.db & gerbera.backup.db files. Owner was changed to gerbera with rwx privileges. I also tried returning it to root & placed all user accounts in a group with rwx. No joy.

I think the best clue is: Error: Sqlite3Database.init: could not open '/etc/gerbera/gerbera.db' exclusively, but I have found nothing online. ...awaiting your input. Thx.

**Comment by KarlStraussberger** [comment]
Well the message means exactly what is say: Opening the database file failed. For correct operation you should 
`chown -R gerbera /etc/gerbera/; chmod 644 /etc/gerbera/*` and do a `rm /etc/gerbera/*.db*` for a clean start. If that does not work, I'm running out of ideas.

**Comment by geno11x11** [comment]
**OK - back in business.** The gerbera.db file apparently was corrupt. My guess would be it happened when I ran gerbera from the command line, not realizing that system.d already had it running. Another possibility is the auto-restore-on-error command in config.xml. I have removed the sqlite backup and auto-restore commands in hopes that database corruption might be reduced.

So I have learned a few things about Gerbera:

- When the sqlite database won't open, delete and recreate it.
- Once the database has been deleted, the **service version** of gerbera will not recreate it. Gerbera must be started from the **command line** to recreate gerbera.db.
- After the database has been recreated **file permissions of gerbera.db must be modified** per your instructions above to start the service although the command line startup will work with **unmodified file permissions**.

So now everything is working fine once again and I have a tentative feeling of being in control. With trepidation, I have **one additional question:**

Gerbera documentation shows the **[system-directories]** entry for **config.xml** but does not provide a coding example. This was my best guess but it produced a parsing error. My goal is to unhide /run and all subdirectories. What is the correct syntax?

`  <system-directories="/bin /boot /dev /etc /lib /lib32 /lib64 /libx32 /proc /run /sbin /sys /tmp /usr /var"> </system-directories> `   

Again, Thx for your ongoing help.

**Comment by KarlStraussberger** [comment]
Running gerbera twice is the fastest way to crash your database. A major difference to using mysql, but it's easy to fix :smile:

Normally, the service does the same as the process on the command line, except that it has fewer permissions (not being root). That's why you have to set the permissions right.

The syntax is 
```
             <system-directories>
                                <add-path name="/mnt"/>
                                <add-path name="/bin"/>
                </system-directories>
```

You're welcome
