### ISSUE TITLE
Gerbera 1.8.2 Crash on with {string pointer is null}

### ISSUE THREAD

**Issue by xcom169** [gerbera/gerbera#1599]
gerbera.service - Gerbera Media Server
     Loaded: loaded (/etc/systemd/system/gerbera.service; enabled; vendor preset: disabled)
     Active: active (running) since Mon 2021-06-21 07:36:51 CEST; 4h 20min ago
   Main PID: 421 (gerbera)
      Tasks: 11 (limit: 6919)
     Memory: 69.7M
        CPU: 32.862s
     CGroup: /system.slice/gerbera.service
             └─421 /usr/bin/gerbera -c /etc/gerbera/config.xml -m /etc/gerbera

jún 21 07:36:52 x45 gerbera[421]: 2021-06-21 07:36:52   info: About to migrate metadata from mt_cds_object to mt_metadata
jún 21 07:36:52 x45 gerbera[421]: 2021-06-21 07:36:52   info: No data will be removed from mt_cds_object
jún 21 07:36:52 x45 gerbera[421]: 2021-06-21 07:36:52   info: Migrated metadata - object count: 0
jún 21 07:36:52 x45 gerbera[421]: 2021-06-21 07:36:52   info: Loading 0 configuration items from database
jún 21 07:36:52 x45 gerbera[421]: 2021-06-21 07:36:52   info: Loading autoscan location: /srv/HDD/ss; recursive: true, last_modi>
jún 21 07:36:52 x45 gerbera[421]: 2021-06-21 07:36:52   info: Loading autoscan location: /srv/HDD/xr; recursive: true, last_modif>
jún 21 07:36:52 x45 gerbera[421]: 2021-06-21 07:36:52   info: Loading autoscan location: /srv/HDD/xa; recursive: true, last_m>
jún 21 07:36:52 x45 gerbera[421]: 2021-06-21 07:36:52   info: Initialising UPnP with interface: <unset>, port: <unset>
jún 21 07:36:52 x45 gerbera[421]: [*** LOG ERROR #0001 ***] [2021-06-21 07:36:52] [] {string pointer is null}
jún 21 07:36:53 x45 gerbera[421]: [*** LOG ERROR #0002 ***] [2021-06-21 07:36:53] [] {string pointer is null}

**Comment by whyman** [comment]
Hmm, is your network interface up and initialised when Gerbera starts?

**Comment by KarlStraussberger** [comment]
Seems to be an issue in the network configuration.
