### ISSUE TITLE
All songs stop after appr. two minutes

### ISSUE THREAD

**Issue by vasyugan** [gerbera/gerbera#161]
So this is still about gerbera on Arch Linux Arm on a Raspberry Pi3, armv7h. I built Gerbera from master which fixed several bugs, but it caused a new one:

All songs are muted / stop after approximately two minutes. Tried with BubbleUPNP and with Rhythmbox (Grilo plugins mediabrowser) .

I am not seeing something obviously related even if I start gerbera with the --debug option. Could you kindly advise what info would be relevant for tracking this down?

**Comment by michael-o** [comment]
Are you able to run Wireshark on the server? You would be see how the socket is aborted, for instance.

**Comment by elmodaddyb** [comment]
The UPNP protocol will send a resource definition for a given media type.
```
<res protocolInfo="http-get:*:video/mp4:*" size="2067769601" bitrate="348797" duration="01:38:48.2"
         sampleFrequency="48000" nrAudioChannels="6" resolution="720x480">
        http://localhost:49153/content/media/object_id/143/res_id/0/ext/file.mp4
    </res>
```
The UPNP client will buffer and request the file in chunks by specifying the `# of bytes` to request (_i think_).

I wonder 2 things.

1. Is the resource definition correct, duration, file type, etc.
2. Can you download the resource directly from browser, without it crashing

This might help determine if Gerbera runtime is faulty or if the client is having troubles?

**Comment by vasyugan** [comment]
Thanks both of you, maybe this was a temporary hickup, as after a reboot it seems gone, I cannot reproduce.
