### ISSUE TITLE
URL resource path is incorrect

### ISSUE THREAD

**Issue by druban** [gerbera/gerbera#1612]
Today's updating (I haven't updated in a month or so) broke playback. The issue seems to be with resource path in the URLs. From tcpdump+strings:
http://192.168.6.1:49152/content/media/object_id/734/res_id/1/ext/file.ACTUAL_FILE_NAME_HERE.mkv
instead of 
http://192.168.6.1:49152/content/media/object_id/734/res_id/1/ext/file.mkv

I haven't looked at the code yet so no idea what's going on.

**Comment by KarlStraussberger** [comment]
Does actual file name contain any _illegal_ chars?

**Comment by druban** [comment]
Which characters are illegal? File name contains digits, punctuation and white spaces

**Comment by druban** [comment]
Ok, here's a fix:

```
diff --git a/src/upnp_xml.cc b/src/upnp_xml.cc
index f821c46a..d2c35b38 100644
--- a/src/upnp_xml.cc
+++ b/src/upnp_xml.cc
@@ -458,7 +458,7 @@ std::string UpnpXMLBuilder::renderExtension(const std::string& contentType, cons
     }
 
     if (!location.empty() && location.has_extension()) {
-        std::string extension = location.filename().string();
+        std::string extension = location.extension().string();
         // make sure that the extension does not contain the separator character
         if (extension.find(URL_PARAM_SEPARATOR) == std::string::npos) {
             return fmt::format("{}.{}", ext, extension);
```

**Comment by druban** [comment]
As a side note - "extension" should be const string reference, not a string.

**Comment by KarlStraussberger** [comment]
I added url escaping for the file name. Does that fix your issue?

**Comment by druban** [comment]
It didn't. I'm also not sure why would we expose the actual file name in it (even though it's escaped and such). IMHO, it should't be .../file.ACTUALL_ESCAPED_FILE_NAME.srt, but rather .../file.srt. The same applies to video and/or audio.
I don't understand this particular change, although it doesn't do anything positive/negative. File names should not be exposed. That's a security risk.

**Comment by KarlStraussberger** [comment]
The file name is visible in web ui as full location anyway. 

The reason are subtitles. Some tools (vlc, kodi) take the section before the extension an the next dot as title, i.e language, for the sub.
