### ISSUE TITLE
subtitles on samsung are broken

### ISSUE THREAD

**Issue by druban** [gerbera/gerbera#1613]
And here I was thinking I'm done complaining for today ;-)
Samsung (could be others as well) subtitles are broken. I haven't done any serious investigation, but it seems that
resources in UpnpXMLBuilder::renderSubtitle() don't match isMetaResource(VIDEO_SUB) when subtitles are available even though I can see in the log file that fillMetadata() properly identifies subtitle file and adds it to the resources lists of bunch of files, including the one being tested.

**Comment by KarlStraussberger** [comment]
No worries about reporting issues!

There used to be separate code segments to render subtitle which have been merged. The side effect is that special Samsung handling was broken. That's the problem of so many different clients behaving their special way. Hope it's back with the PR.

**Comment by druban** [comment]
I'll definitely give it a shot once changes are merged

**Comment by druban** [comment]
There's an improvement, but subtitles are still broken. Now I can see CaptionInfo.sec header and judging from tcpdump TV actually fetches subtitle file. But no subtitles are displayed. Could it be because of mime type? Looks like gerbera advertises them as text/srt. Not sure if it's the right mime type for Samsung TV

**Comment by druban** [comment]
Confirmed, we used to advertise subtitles mime type as text/plain

**Comment by KarlStraussberger** [comment]
Thank you for looking into the details. Need to find out why the mime type mapping is overwritten (metacontent_handler.cc#L294). Maybe we can set the mime type for Samsung only.

**Comment by druban** [comment]
I don't think it gets overwritten. We pull _type_ as path.extension().string().substr(1) which results in _type_ being set to "srt". Then we set _mimeType_ to be text/_type_. Result - mime type is text/srt. Then we search for "plain" in the newly generated mime type. No such thing found. So we store "text/srt" in protocolInfo ...

**Comment by druban** [comment]
However, adding a dumb hack to replace _srt_ with _plain_ didn't seem to do the trick. Subtitles are still now shown, yet content type seems to be correct. Must be something else (or a combination of this and something else)

**Comment by KarlStraussberger** [comment]
With the last patch the resource and CaptionInfo are added, Maybe that brings subtitles back to your TV.

**Comment by druban** [comment]
Tried fresh build w/ your changes. Still not subtitles displayed ...

**Comment by KarlStraussberger** [comment]
So let's start from the beginning: Which version of gerbera do you remember worked with your TV and subtitles.

**Comment by druban** [comment]
If I restore code line to March 1st of this year, subtitles are displayed properly.

**Comment by druban** [comment]
![Screen Shot 2021-06-28 at 10 45 04 AM](https://user-images.githubusercontent.com/35857466/123680753-e98d9580-d7fd-11eb-882d-109e1e13791c.jpg)

**Comment by KarlStraussberger** [comment]
Can you try this small change
```
diff --git a/src/upnp_xml.cc b/src/upnp_xml.cc
index 9cb7dce3..fe5aeb4b 100644
--- a/src/upnp_xml.cc
+++ b/src/upnp_xml.cc
@@ -441,6 +441,7 @@ bool UpnpXMLBuilder::renderSubtitle(const std::string& virtualURL, const std::sh
     for (auto&& res : item->getResources()) {
         if (res->isMetaResource(VIDEO_SUB, CH_SUBTITLE)) {
             url = renderOneResource(virtualURL, item, res, realCount);
+            url.append(renderExtension("", res->getAttribute(R_RESOURCE_FILE)));
             srtAdded = true;
             break;
         }
```

**Comment by druban** [comment]
No subtitles still ...

**Comment by KarlStraussberger** [comment]
Can you try running with `--debug` to see the server footage because I'm running out of ideas.

**Comment by druban** [comment]
Sure thing. Do you want debug output for current gerbera version or for one from March 1st code line? (or both)

**Comment by KarlStraussberger** [comment]
If you don't mind: both - to see the change

**Comment by druban** [comment]
I stand corrected. With your latest patch subtitles are working fine. I just had to start from scratch, dropping database and rescanning video folder. Thanks a lot for your help!

**Comment by KarlStraussberger** [comment]
You're welcome. We've been able to sort out the issue and make gerbera a little better again!
