### ISSUE TITLE
Unable to launch gerbera via systemd

### ISSUE THREAD

**Issue by tcrass** [gerbera/gerbera#162]
Hi there,

first of all I'd like to thank you for resurrecting mediatomb from, well, its tomb. Apart from some technical improvements, I'm particularly fond of the new logo, which is definitely more cheerful than the old one! :)

I managed to compile gerbera on a Debian Stretch system with very little hassle and I'm also able to start the daemon from the command-line, but I just can't get it to work using systemctl and the .service file (actually: a modified versio of) from the repo.

Currently my service file looks like this:

    [Unit]
    Description=Gerbera Media Server
    After=network.target

    [Service]
    Type=simple
    User=root
    Group=root
    ExecStart=/usr/local/bin/gerbera -c /etc/gerbera/config.xml
    Restart=on-failure
    RestartSec=5

    [Install]
    WantedBy=multi-user.target

So the only modifications I made were changing user/group to root (since I don't have a gerbera user yet) and updating the ExecStart path to gerbera's actual install location.

However, when issuing

    systemctl start gerbera

the journal gives me

    Sep 20 22:09:52 priamos systemd[1]: gerbera.service: Service hold-off time over, scheduling restart.
    Sep 20 22:09:52 priamos systemd[1]: Stopped Gerbera Media Server.
    Sep 20 22:09:52 priamos systemd[1]: Started Gerbera Media Server.
    Sep 20 22:09:52 priamos systemd[22400]: gerbera.service: Failed at step USER spawning /usr/bin/gerbera: No such process
    Sep 20 22:09:52 priamos systemd[1]: gerbera.service: Main process exited, code=exited, status=217/USER
    Sep 20 22:09:52 priamos systemd[1]: gerbera.service: Unit entered failed state.
    Sep 20 22:09:52 priamos systemd[1]: gerbera.service: Failed with result 'exit-code'.
    Sep 20 22:09:57 priamos systemd[1]: gerbera.service: Service hold-off time over, scheduling restart.
    Sep 20 22:09:57 priamos systemd[1]: Stopped Gerbera Media Server.
    Sep 20 22:09:57 priamos systemd[1]: Started Gerbera Media Server.
    ....

Oh, and I *did* make sure that the /etc/gerbera directory does exits.

So am I missing something or is gerbera missing something?

Cheers --

Torsten

**Comment by jcowgill** [comment]
Did you run `systemctl daemon-reload` after editing the service file?

As you're probably aware, running gerbera as root is a **very** bad idea so change that back as soon as possible.

**Comment by elmodaddyb** [comment]
I put together a README.md which I will PR to master for loading the `systemd`. I used these instructions with a clean Fedora system, and it worked OK.

https://gist.github.com/elmodaddyb/6ce7154d5e5eb9c332d1dd00e6f97667

Let me know if it helps.  If you still encounter issues can you run gerbera without `systemd` successfully?  If so, perhaps its a systemd permissions issue?
