### ISSUE TITLE
mark-played-items extended runtime

### ISSUE THREAD

**Issue by Mikeput** [gerbera/gerbera#1642]
Not an issue as such, but is there a scope where you can make it client specific in terms of the ip address of last played the item? Instead for all clients?

**Comment by KarlStraussberger** [comment]
Nice idea, but not as easy to implement: DHCP changes IP addresses, on Windows more than on player can be used.

To finish the thought we need to define some "UserRule" and set expiration times otherwise the database grows with each client.

Stuff for longer winter nights 😄

**Comment by KarlStraussberger** [comment]
The winter is over and you can try it out. In order to get the the client identified you need to add an entry to clients (https://docs.gerbera.io/en/latest/config-clients.html#clients) (match either by IP or userAgent) and set to `group` attribute.

**Comment by Mikeput** [comment]
Thanks for this, could you give me an example of the configure setting to set, i would be going via IP.

**Comment by KarlStraussberger** [comment]
```
<clients enabled="yes">
  <client ip="192.168.1.42" group="karl" flags="SAMSUNG"/>
</clients>
```
