### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by yyy33** [gerbera/gerbera#1643]
Version is 1.8.2  ,system is arch
````
● gerbera.service - Gerbera Media Server
     Loaded: loaded (/usr/lib/systemd/system/gerbera.service; disabled; vendor preset: disabled)
     Active: active (running) since Tue 2021-06-29 13:58:21 CST; 10min ago
   Main PID: 32388 (gerbera)
      Tasks: 12 (limit: 9373)
     Memory: 10.3M
        CPU: 573ms
     CGroup: /system.slice/gerbera.service
             └─32388 /usr/bin/gerbera -c /etc/gerbera/config.xml

6月 29 13:58:47 x550vc-yyy gerbera[32388]: 2021-06-29 13:58:47  error: prematurely shutting down.
6月 29 13:58:47 x550vc-yyy gerbera[32388]: 2021-06-29 13:58:47 warning: skipping /mnt/1341-694F (ex:[/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed)
6月 29 13:58:49 x550vc-yyy gerbera[32388]: 2021-06-29 13:58:49  error: prematurely shutting down.
6月 29 13:58:49 x550vc-yyy gerbera[32388]: 2021-06-29 13:58:49 warning: Web Error: 800 Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed
6月 29 14:00:19 x550vc-yyy gerbera[32388]: 2021-06-29 14:00:19  error: prematurely shutting down.
6月 29 14:00:19 x550vc-yyy gerbera[32388]: 2021-06-29 14:00:19  error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed
6月 29 14:07:12 x550vc-yyy gerbera[32388]: 2021-06-29 14:07:12  error: prematurely shutting down.
6月 29 14:07:12 x550vc-yyy gerbera[32388]: 2021-06-29 14:07:12 warning: Web Error: 800 Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed
6月 29 14:08:28 x550vc-yyy gerbera[32388]: 2021-06-29 14:08:28  error: prematurely shutting down.
6月 29 14:08:28 x550vc-yyy gerbera[32388]: 2021-06-29 14:08:28 warning: Web Error: 800 Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed

````

**Comment by yyy33** [comment]
> Version is 1.8.2 ,system is arch
> 
> ```
> ● gerbera.service - Gerbera Media Server
>      Loaded: loaded (/usr/lib/systemd/system/gerbera.service; disabled; vendor preset: disabled)
>      Active: active (running) since Tue 2021-06-29 13:58:21 CST; 10min ago
>    Main PID: 32388 (gerbera)
>       Tasks: 12 (limit: 9373)
>      Memory: 10.3M
>         CPU: 573ms
>      CGroup: /system.slice/gerbera.service
>              └─32388 /usr/bin/gerbera -c /etc/gerbera/config.xml
> 
> 6月 29 13:58:47 x550vc-yyy gerbera[32388]: 2021-06-29 13:58:47  error: prematurely shutting down.
> 6月 29 13:58:47 x550vc-yyy gerbera[32388]: 2021-06-29 13:58:47 warning: skipping /mnt/1341-694F (ex:[/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed)
> 6月 29 13:58:49 x550vc-yyy gerbera[32388]: 2021-06-29 13:58:49  error: prematurely shutting down.
> 6月 29 13:58:49 x550vc-yyy gerbera[32388]: 2021-06-29 13:58:49 warning: Web Error: 800 Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed
> 6月 29 14:00:19 x550vc-yyy gerbera[32388]: 2021-06-29 14:00:19  error: prematurely shutting down.
> 6月 29 14:00:19 x550vc-yyy gerbera[32388]: 2021-06-29 14:00:19  error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed
> 6月 29 14:07:12 x550vc-yyy gerbera[32388]: 2021-06-29 14:07:12  error: prematurely shutting down.
> 6月 29 14:07:12 x550vc-yyy gerbera[32388]: 2021-06-29 14:07:12 warning: Web Error: 800 Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed
> 6月 29 14:08:28 x550vc-yyy gerbera[32388]: 2021-06-29 14:08:28  error: prematurely shutting down.
> 6月 29 14:08:28 x550vc-yyy gerbera[32388]: 2021-06-29 14:08:28 warning: Web Error: 800 Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:342] select Error: [/home/yyy/Downloads/gerbera/src/gerbera-1.8.2/src/database/sqlite3/sqlite_database.cc:439] addTask Error: sqlite3 task queue is already closed
> ```

What other effective information should I provide,thanks.

**Comment by KarlStraussberger** [comment]
Try to get the beginning of the server log. `systemctl status -n1000 gerbera` (or whatever it takes). You may also check you syslog/mesages.

**Comment by yyy33** [comment]
[log.tar.gz](https://github.com/gerbera/gerbera/files/6739576/log.tar.gz)


> Try to get the beginning of the server log. `systemctl status -n1000 gerbera` (or whatever it takes). You may also check you syslog/mesages.

**Comment by KarlStraussberger** [comment]
There are three things you need to check out
1. The network: Provide an interface name in config.xml instead of letting gerbera guess. And enable broadcasting: https://docs.gerbera.io/en/latest/run.html#network-setup
2. The file source: You try to import from /mnt as a service. Does the service user have sufficient permissions?
3. Is there some security system restarting gerbera `Operator of unix-process:26606:329921 successfully authenticated as unix-user:yyy to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-units for system-bus-name::1.826 [systemctl restart gerbera] (owned by unix-user:yyy)` because of missing pid files etc?

Try to run it from console `su -m gerbera -c "gerbera -c /etc/gerbera/config.xml"`. User gerbera needs write permissions to the datadir for the database file. Please share `/etc/gerbera/config.xml` if you have further problems.

**Comment by yyy33** [comment]
> There are three things you need to check out
> 
> 1. The network: Provide an interface name in config.xml instead of letting gerbera guess. And enable broadcasting: https://docs.gerbera.io/en/latest/run.html#network-setup
> 2. The file source: You try to import from /mnt as a service. Does the service user have sufficient permissions?
> 3. Is there some security system restarting gerbera `Operator of unix-process:26606:329921 successfully authenticated as unix-user:yyy to gain TEMPORARY authorization for action org.freedesktop.systemd1.manage-units for system-bus-name::1.826 [systemctl restart gerbera] (owned by unix-user:yyy)` because of missing pid files etc?
> 
> Try to run it from console `su -m gerbera -c "gerbera -c /etc/gerbera/config.xml"`. User gerbera needs write permissions to the datadir for the database file. Please share `/etc/gerbera/config.xml` if you have further problems.

Thank you. After deleting and rebuilding the database file, it is running fine now.I think it's a matter of access.
