### ISSUE TITLE
AVC

### ISSUE THREAD

**Issue by Jack-12-12** [gerbera/gerbera#1645]
Hello

Trying to transcode in order to see some mkv in my ps3, could not understand how to configure the profile section using video/avc mimetype. On PS3 it shows "unkown data"

Using video/mpeg and ffmpeg mpeg2 it worked. 

Any suggestions ?

Regards

**Comment by KarlStraussberger** [comment]
In `mimetype-profile-mappings` you define which mimes you need to transcode, `mkv` is `video/x-matroska`

In `profile` you set the output to something your PS3 can play, e.g. `video/mpeg` and configure the transcoder to produce exactly that format.

If all three parts work together correctly you should be able to watch your movie.

AVC file may well be recognised as `video/mp4`
