### ISSUE TITLE
Compilation fails on CentOS 7.4

### ISSUE THREAD

**Issue by nelgin** [gerbera/gerbera#165]
I'm trying to compile on CentOS 7.4 and coming across an error.  Open to suggestions on what to try to get it working.

[login@server build]$ cmake3 ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++
-- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib64/libc.so
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1") 
-- Looking for BSD native UUID
-- Looking for libuuid
-- Looking for libuuid - found
-- Found UUID: TRUE  
-- Looking for native LFS support
-- Looking for native LFS support - found
-- Found LFS: TRUE  
-- Found UPnP: /usr/lib/libupnp-1.8.so (found version "1.8.1") 
-- Found EXPAT: /usr/lib64/libexpat.so (found version "2.1.0") 
-- Found Sqlite3: /usr/lib64/libsqlite3.so
-- Looking for native inotify
-- Looking for native inotify - found
-- Found Duktape: /usr/local/lib/libduktape.so  
-- Found CURL: /usr/lib64/libcurl.so (found version "7.29.0") 
-- Found TagLib: -L/usr/local/lib -ltag
-- Found MAGIC: /usr/lib64/libmagic.so  
-- Found EXIF: /usr/lib64/libexif.so  
-- Found systemd: /bin/pkg-config
-- Configuring systemd unit file: gerbera.service
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/madsonic/build
[login@server build]$ make -j4
Scanning dependencies of target libgerbera
[  1%] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
[  2%] Building CXX object CMakeFiles/libgerbera.dir/src/atrailers_service.cc.o
[  3%] Building CXX object CMakeFiles/libgerbera.dir/src/atrailers_content_handler.cc.o
[  4%] Building CXX object CMakeFiles/libgerbera.dir/src/autoscan.cc.o
[  4%] Building CXX object CMakeFiles/libgerbera.dir/src/autoscan_inotify.cc.o
[  5%] Building CXX object CMakeFiles/libgerbera.dir/src/buffered_io_handler.cc.o
[  6%] Building CXX object CMakeFiles/libgerbera.dir/src/cached_url.cc.o
[  7%] Building CXX object CMakeFiles/libgerbera.dir/src/cds_objects.cc.o
[  8%] Building CXX object CMakeFiles/libgerbera.dir/src/cds_resource.cc.o
[  9%] Building CXX object CMakeFiles/libgerbera.dir/src/cds_resource_manager.cc.o
[  9%] Building CXX object CMakeFiles/libgerbera.dir/src/config_manager.cc.o
[ 10%] Building CXX object CMakeFiles/libgerbera.dir/src/content_manager.cc.o
[ 11%] Building C object CMakeFiles/libgerbera.dir/src/contrib/md5.c.o
[ 12%] Building CXX object CMakeFiles/libgerbera.dir/src/curl_io_handler.cc.o
[ 13%] Building CXX object CMakeFiles/libgerbera.dir/src/destroyer.cc.o
[ 14%] Building CXX object CMakeFiles/libgerbera.dir/src/dictionary.cc.o
[ 14%] Building CXX object CMakeFiles/libgerbera.dir/src/exceptions.cc.o
[ 15%] Building CXX object CMakeFiles/libgerbera.dir/src/fd_io_handler.cc.o
[ 16%] Building CXX object CMakeFiles/libgerbera.dir/src/file_io_handler.cc.o
[ 17%] Building CXX object CMakeFiles/libgerbera.dir/src/file_request_handler.cc.o
[ 18%] Building CXX object CMakeFiles/libgerbera.dir/src/filesystem.cc.o
[ 19%] Building CXX object CMakeFiles/libgerbera.dir/src/generic_task.cc.o
[ 19%] Building CXX object CMakeFiles/libgerbera.dir/src/io_handler_buffer_helper.cc.o
[ 20%] Building CXX object CMakeFiles/libgerbera.dir/src/io_handler.cc.o
[ 21%] Building CXX object CMakeFiles/libgerbera.dir/src/io_handler_chainer.cc.o
[ 22%] Building CXX object CMakeFiles/libgerbera.dir/src/jpeg_resolution.cc.o
[ 23%] Building CXX object CMakeFiles/libgerbera.dir/src/lastfm_scrobbler.cc.o
[ 24%] Building CXX object CMakeFiles/libgerbera.dir/src/layout/fallback_layout.cc.o
[ 24%] Building CXX object CMakeFiles/libgerbera.dir/src/layout/js_layout.cc.o
[ 25%] Building CXX object CMakeFiles/libgerbera.dir/src/logger.cc.o
[ 26%] Building CXX object CMakeFiles/libgerbera.dir/src/mem_io_handler.cc.o
[ 27%] Building CXX object CMakeFiles/libgerbera.dir/src/memory.cc.o
[ 28%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/exiv2_handler.cc.o
[ 29%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o
[ 29%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata_handler.cc.o
[ 30%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/libexif_handler.cc.o
[ 31%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/taglib_handler.cc.o
[ 32%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/fanart_handler.cc.o
[ 33%] Building CXX object CMakeFiles/libgerbera.dir/src/mt_inotify.cc.o
[ 34%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/attribute.cc.o
[ 34%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/comment.cc.o
[ 35%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/context.cc.o
[ 36%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/document.cc.o
[ 37%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/element.cc.o
[ 38%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/node.cc.o
[ 39%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/parseexception.cc.o
[ 39%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/parser_expat.cc.o
[ 40%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/xml_text.cc.o
[ 41%] Building CXX object CMakeFiles/libgerbera.dir/src/mxml/xml_to_json.cc.o
[ 42%] Building CXX object CMakeFiles/libgerbera.dir/src/online_service.cc.o
[ 43%] Building CXX object CMakeFiles/libgerbera.dir/src/online_service_helper.cc.o
[ 44%] Building CXX object CMakeFiles/libgerbera.dir/src/play_hook.cc.o
[ 44%] Building CXX object CMakeFiles/libgerbera.dir/src/process.cc.o
[ 45%] Building CXX object CMakeFiles/libgerbera.dir/src/process_executor.cc.o
[ 46%] Building CXX object CMakeFiles/libgerbera.dir/src/process_io_handler.cc.o
[ 47%] Building CXX object CMakeFiles/libgerbera.dir/src/request_handler.cc.o
[ 48%] Building CXX object CMakeFiles/libgerbera.dir/src/rexp.cc.o
[ 49%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/import_script.cc.o
[ 49%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/js_functions.cc.o
[ 50%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/playlist_parser_script.cc.o
[ 51%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/runtime.cc.o
[ 52%] Building CXX object CMakeFiles/libgerbera.dir/src/scripting/script.cc.o
[ 53%] Building CXX object CMakeFiles/libgerbera.dir/src/server.cc.o
[ 54%] Building CXX object CMakeFiles/libgerbera.dir/src/serve_request_handler.cc.o
[ 54%] Building CXX object CMakeFiles/libgerbera.dir/src/session_manager.cc.o
[ 55%] Building CXX object CMakeFiles/libgerbera.dir/src/singleton.cc.o
[ 56%] Building CXX object CMakeFiles/libgerbera.dir/src/sopcast_content_handler.cc.o
[ 57%] Building CXX object CMakeFiles/libgerbera.dir/src/sopcast_service.cc.o
[ 58%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/cache_object.cc.o
[ 59%] Building CXX object CMakeFiles/libgerbera.dir/src/storage.cc.o
[ 59%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/mysql/mysql_storage.cc.o
[ 60%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/sqlite3/sqlite3_storage.cc.o
[ 61%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/sql_storage.cc.o
[ 62%] Building CXX object CMakeFiles/libgerbera.dir/src/storage/storage_cache.cc.o
[ 63%] Building CXX object CMakeFiles/libgerbera.dir/src/string_converter.cc.o
[ 64%] Building CXX object CMakeFiles/libgerbera.dir/src/subscription_request.cc.o
[ 64%] Building CXX object CMakeFiles/libgerbera.dir/src/task_processor.cc.o
[ 65%] Building CXX object CMakeFiles/libgerbera.dir/src/thread_executor.cc.o
[ 66%] Building CXX object CMakeFiles/libgerbera.dir/src/timer.cc.o
[ 67%] Building CXX object CMakeFiles/libgerbera.dir/src/tools.cc.o
[ 68%] Building CXX object CMakeFiles/libgerbera.dir/src/transcoding/transcode_dispatcher.cc.o
/home/madsonic/gerbera/src/timer.cc: In member function ‘void Timer::removeTimerSubscriber(Timer::Subscriber*, zmm::Ref<Timer::Parameter>, bool)’:
/home/madsonic/gerbera/src/timer.cc:89:29: error: no matching function for call to ‘std::list<Timer::TimerSubscriberElement>::erase(std::_List_const_iterator<Timer::TimerSubscriberElement>&)’
         subscribers.erase(it);
                             ^
/home/madsonic/gerbera/src/timer.cc:89:29: note: candidates are:
In file included from /usr/include/c++/4.8.2/list:64:0,
                 from /home/madsonic/gerbera/src/timer.h:42,
                 from /home/madsonic/gerbera/src/timer.cc:34:
/usr/include/c++/4.8.2/bits/list.tcc:108:5: note: std::list<_Tp, _Alloc>::iterator std::list<_Tp, _Alloc>::erase(std::list<_Tp, _Alloc>::iterator) [with _Tp = Timer::TimerSubscriberElement; _Alloc = std::allocator<Timer::TimerSubscriberElement>; std::list<_Tp, _Alloc>::iterator = std::_List_iterator<Timer::TimerSubscriberElement>]
     list<_Tp, _Alloc>::
     ^
/usr/include/c++/4.8.2/bits/list.tcc:108:5: note:   no known conversion for argument 1 from ‘std::_List_const_iterator<Timer::TimerSubscriberElement>’ to ‘std::list<Timer::TimerSubscriberElement>::iterator {aka std::_List_iterator<Timer::TimerSubscriberElement>}’
In file included from /usr/include/c++/4.8.2/list:63:0,
                 from /home/madsonic/gerbera/src/timer.h:42,
                 from /home/madsonic/gerbera/src/timer.cc:34:
/usr/include/c++/4.8.2/bits/stl_list.h:1193:7: note: std::list<_Tp, _Alloc>::iterator std::list<_Tp, _Alloc>::erase(std::list<_Tp, _Alloc>::iterator, std::list<_Tp, _Alloc>::iterator) [with _Tp = Timer::TimerSubscriberElement; _Alloc = std::allocator<Timer::TimerSubscriberElement>; std::list<_Tp, _Alloc>::iterator = std::_List_iterator<Timer::TimerSubscriberElement>]
       erase(iterator __first, iterator __last)
       ^
/usr/include/c++/4.8.2/bits/stl_list.h:1193:7: note:   candidate expects 2 arguments, 1 provided
make[2]: *** [CMakeFiles/libgerbera.dir/src/timer.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/libgerbera.dir/all] Error 2
make: *** [all] Error 2

**Comment by v00d00** [comment]
Which compiler are you using?

**Comment by nelgin** [comment]
I’m using EPEL’s cmake package which contains cmake 3.6.3

**Comment by v00d00** [comment]
What does `gcc --version` give you?

**Comment by nelgin** [comment]
Oh yeah, compiler ☺

4.8.5 20150623 (Red Hat 4.8.5-16)

**Comment by v00d00** [comment]
Assuming you have got the the default you will have GCC 4.8.x(!) still.

Try installing "Devtoolset 6" from software collections, that will give you a GCC 6.3.

[Link](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-6/)

**Comment by nelgin** [comment]
That helped on the compilation but now I’m getting a lot of linkage errors. I did have to compile a couple of libraries before hand so I’ll recompile with the later version of gcc and see if that helps any.

Thanks,
Nigel

**Comment by nelgin** [comment]
Just to follow up, once I got my libraries sorted out, it compiled cleanly using the scl.

Thanks,
Nigel

**Comment by v00d00** [comment]
Great to hear! I will close this issue.

Perhaps you consider adding a patch to our README with which steps where needed to build on CentOS 7.

**Comment by elmodaddyb** [comment]
I was able to get a Dockerfile working using CentOS.  I will provide some documentation for CentOS build in the near future.

https://github.com/elmodaddyb/gerbera-docker/blob/master/Dockerfile.centos

**Comment by akiya64** [comment]
Hi, @v00d00, @elmodaddyb 
I try garbera in CentOS 7.4 by using gcc 6.4.8.
I have been using Mediatomb sice 6 or 7 years ago, I am pleased that I can use gerbera based Mediatomb.
