### ISSUE TITLE
Gerbera returns no music after a while

### ISSUE THREAD

**Issue by vasyugan** [gerbera/gerbera#166]
First when I start gerbera, things are fine, but when I recheck after 24 hours, clients who contact it seem to get empty responses, they show no media for the server until I restart it.

I see the following in the syslog
 
```
Okt 01 07:13:54 raspberrypi gerbera[25199]: 2017-10-01 07:13:54   ERROR: ActionRequest::update(): response is nullptr, code -115
Okt 01 07:13:54 raspberrypi gerbera[25199]: 2017-10-01 07:13:54   ERROR: ActionRequest::update(): response is nullptr, code -115
Okt 01 07:15:44 raspberrypi systemd[1]: Stopping Gerbera Media Server...
Okt 01 07:15:44 raspberrypi gerbera[25199]: 2017-10-01 07:15:44    INFO: Gerbera shutting down. Please wait...
Okt 01 07:15:45 raspberrypi gerbera[25199]: 2017-10-01 07:15:45    INFO: Exception: sqlite3 task queue is already closed
Okt 01 07:15:45 raspberrypi gerbera[25199]: 2017-10-01 07:15:45    INFO: Gerbera exiting. Have a nice day.
Okt 01 07:15:46 raspberrypi systemd[1]: Stopped Gerbera Media Server.
Okt 01 07:16:06 raspberrypi systemd[1]: Started Gerbera Media Server.

```

The programme has been compiled from master a few days ago. I am on Arch Linux

**Comment by v00d00** [comment]
Hmm, can you try running with debug logging for a while? The log snippet doesn't tell too much.

**Comment by vasyugan** [comment]
What I see now is that gerbera seems to scan the full music dir, in the web interface everything seems fine (the database is filled with entries), but UPNP clients are not served anything. 

journalctl -fu gerbera shows:

Okt 24 10:15:32 raspberrypi gerbera[14816]: 2017-10-24 10:15:32   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:18:09 raspberrypi gerbera[14816]: 2017-10-24 10:18:09   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:18:09 raspberrypi gerbera[14816]: 2017-10-24 10:18:09   DEBUG: [src/server.cc:347] upnp_actions(): start
Okt 24 10:18:09 raspberrypi gerbera[14816]: 2017-10-24 10:18:09   DEBUG: [src/upnp_cds.cc:188] process_action_request(): start
Okt 24 10:18:09 raspberrypi gerbera[14816]: 2017-10-24 10:18:09   DEBUG: [src/upnp_cds.cc:201] process_action_request(): unrecognized action Search
Okt 24 10:18:09 raspberrypi gerbera[14816]: 2017-10-24 10:18:09   DEBUG: [src/upnp_cds.cc:206] process_action_request(): ContentDirectoryService::process_action_request: end
Okt 24 10:18:09 raspberrypi gerbera[14816]: 2017-10-24 10:18:09   ERROR: ActionRequest::update(): response is nullptr, code -115
Okt 24 10:18:09 raspberrypi gerbera[14816]: 2017-10-24 10:18:09   DEBUG: [src/server.cc:326] upnp_callback(): returning 0

**Comment by vasyugan** [comment]
Here is some more:

Okt 24 10:34:37 raspberrypi gerbera[14816]: 2017-10-24 10:34:37   DEBUG: [src/upnp_cds.cc:216] process_subscription_request(): start
Okt 24 10:34:37 raspberrypi gerbera[14816]: 2017-10-24 10:34:37   DEBUG: [src/upnp_cds.cc:235] process_subscription_request(): end
Okt 24 10:34:37 raspberrypi gerbera[14816]: 2017-10-24 10:34:37   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:34:37 raspberrypi gerbera[14816]: 2017-10-24 10:34:37   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:34:37 raspberrypi gerbera[14816]: 2017-10-24 10:34:37   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:35:06 raspberrypi gerbera[14816]: 2017-10-24 10:35:06   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:35:06 raspberrypi gerbera[14816]: 2017-10-24 10:35:06   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:35:06 raspberrypi gerbera[14816]: 2017-10-24 10:35:06   DEBUG: [src/upnp_cds.cc:216] process_subscription_request(): start
Okt 24 10:35:06 raspberrypi gerbera[14816]: 2017-10-24 10:35:06   DEBUG: [src/upnp_cds.cc:235] process_subscription_request(): end
Okt 24 10:35:06 raspberrypi gerbera[14816]: 2017-10-24 10:35:06   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:35:06 raspberrypi gerbera[14816]: 2017-10-24 10:35:06   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:35:06 raspberrypi gerbera[14816]: 2017-10-24 10:35:06   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:35:36 raspberrypi gerbera[14816]: 2017-10-24 10:35:36   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:35:36 raspberrypi gerbera[14816]: 2017-10-24 10:35:36   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:35:36 raspberrypi gerbera[14816]: 2017-10-24 10:35:36   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:35:36 raspberrypi gerbera[14816]: 2017-10-24 10:35:36   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:35:36 raspberrypi gerbera[14816]: 2017-10-24 10:35:36   DEBUG: [src/upnp_cds.cc:216] process_subscription_request(): start
Okt 24 10:35:36 raspberrypi gerbera[14816]: 2017-10-24 10:35:36   DEBUG: [src/upnp_cds.cc:235] process_subscription_request(): end
Okt 24 10:35:36 raspberrypi gerbera[14816]: 2017-10-24 10:35:36   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:36:09 raspberrypi gerbera[14816]: 2017-10-24 10:36:09   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:36:09 raspberrypi gerbera[14816]: 2017-10-24 10:36:09   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:36:09 raspberrypi gerbera[14816]: 2017-10-24 10:36:09   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:36:09 raspberrypi gerbera[14816]: 2017-10-24 10:36:09   DEBUG: [src/upnp_cds.cc:216] process_subscription_request(): start
Okt 24 10:36:09 raspberrypi gerbera[14816]: 2017-10-24 10:36:09   DEBUG: [src/upnp_cds.cc:235] process_subscription_request(): end
Okt 24 10:36:09 raspberrypi gerbera[14816]: 2017-10-24 10:36:09   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:36:36 raspberrypi gerbera[14816]: 2017-10-24 10:36:36   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:36:36 raspberrypi gerbera[14816]: 2017-10-24 10:36:36   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:36:36 raspberrypi gerbera[14816]: 2017-10-24 10:36:36   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:36:36 raspberrypi gerbera[14816]: 2017-10-24 10:36:36   DEBUG: [src/server.cc:272] upnp_callback(): start
Okt 24 10:36:36 raspberrypi gerbera[14816]: 2017-10-24 10:36:36   DEBUG: [src/upnp_cds.cc:216] process_subscription_request(): start
Okt 24 10:36:36 raspberrypi gerbera[14816]: 2017-10-24 10:36:36   DEBUG: [src/upnp_cds.cc:235] process_subscription_request(): end
Okt 24 10:36:36 raspberrypi gerbera[14816]: 2017-10-24 10:36:36   DEBUG: [src/server.cc:326] upnp_callback(): returning 0
Okt 24 10:36:36 raspberrypi gerbera[14816]: 2017-10-24 10:36:36   DEBUG: [src/server.cc:326] upnp_callback(): returning 0

**Comment by vasyugan** [comment]
Also I should say that now when I reload the web interface it never fishines loading and never gets to the point of showing any entries 


![bildschirmfoto von 2017-10-24 10-38-03](https://user-images.githubusercontent.com/3313208/31932815-a8a0d0f6-b8a7-11e7-95d5-fb3c5ef83b6a.png)

**Comment by v00d00** [comment]
It looks like libupnp has stopped for some reason. Which version of libupnp do you have?

**Comment by vasyugan** [comment]
Name            : libupnp
Version         : 1.6.21-2
Description     : Portable Open Source UPnP Development Kit
Architecture    : armv7h
URL             : http://pupnp.sourceforge.net/
Licenses        : BSD
Groups          : None
Provides        : None
Depends On      : glibc
Optional Deps   : None
Required By     : mpd  vlc
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 476.00 KiB
Packager        : Arch Linux ARM Build System <builder+xu6@archlinuxarm.org>
Build Date      : Wed Jun 21 12:49:07 2017
Install Date    : Wed Sep 20 11:11:36 2017
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : SHA-256 Sum

**Comment by v00d00** [comment]
Hmm, we only support 1.8?

**Comment by vasyugan** [comment]
1.8? http://pupnp.sourceforge.net/ gives libupnp 1.6.22 as the current version, same for https://sourceforge.net/projects/pupnp/files/?source=navbar
