### ISSUE TITLE
PPA & No file at /var/lib/gerbera/gerbera.html

### ISSUE THREAD

**Issue by NosajDraw** [gerbera/gerbera#167]
Just installed the PPA, searched for "gerbera" in my GUI, it opens Firefox with this address "file:///var/lib/gerbera/gerbera.html" which results in "Firefox can't find the file at /var/lib/gerbera/gerbera.html."

I checked that directory for the file, and the only file there is gerbera.db

**Comment by v00d00** [comment]
I am assuming you are on a ubuntu with systemd in which case you will want to follow the systemd instructions to run it as a service, then try the link again.

https://github.com/gerbera/gerbera/tree/master/scripts/systemd

Really the PPA packaging should do all that for you, perhaps @stephen-czetty can comment.

**Comment by stephen-czetty** [comment]
The package "should" do the right thing, but the systemd stuff in the 1.0 package was a bit borked.  I'll be building a new package for 1.1 this weekend, if you can wait for that.

**Comment by NosajDraw** [comment]
I will wait for the weekend :) cheers.

**Comment by mrenvoize** [comment]
Hmm, I'm having the same issue.. going through the systemd route the service does appear to be running but I still get the 'file not found' issue when navigating to `file:///var/lib/gerbera/gerbera.html` in the browser.

**Comment by NosajDraw** [comment]
Gave this issue a better name, as others are now adding to it.

**Comment by stephen-czetty** [comment]
Quick update: I was able to get a new build working, but I realized that I'll need to rebuild libupnp also, and I simply ran out of time.  I'm going to try to wrap it all up and upload a new ppa either this evening or tomorrow.

Sorry about the delay!

**Comment by stephen-czetty** [comment]
I pushed up new packages for xenial and zesty.  This version has scripting turned off, since I need to figure out how to get duktape working.  I'll be working on that this week, and I'll hopefully have a new package up soon.

**Comment by NosajDraw** [comment]
I'm trying Gerbera for the first time, so not sure what's what.  Does the lack of "scripting" mean I as a noob should hang fire till you get the full fix, or am I ready to go?

**Comment by stephen-czetty** [comment]
I don't think scripts worked in 1.0, so I don't think you'll be missing any functionality.  It's supposed to enable the ability to write custom scripts that automatically set up your media tree based on metadata.  Or, at least I think that's what it's supposed to do. :)  @v00d00 can probably comment further.

**Comment by v00d00** [comment]
You can use JS to organise how your media is presented to the clients. If you are just getting started you are unlikely to need this feature.
