### ISSUE TITLE
Gerbera fails to link with GCC 10+ when build with -Os

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#1674]
Just going to link this here: https://github.com/openwrt/packages/issues/16080

**Comment by whyman** [comment]
Ive been building with GCC10 for ages without this issue, we will need you to dig into it a bit.

**Comment by micmac1** [comment]
This was also reported on Gentoo's bugzilla: [Link](https://bugs.gentoo.org/show_bug.cgi?id=783219)

They say that this happens with "-Os" and it doesn't with "-O2". I tried and can confirm this.

**Comment by neheb** [comment]
What a strange error...

**Comment by micmac1** [comment]
With gerbera 1.7.0 this doesn't happen. So I did a git bisect till 1.8.2 and this was the result:

```
git bisect bad
af73956c304dab1582f713e48384cc6ad9cbf0af is the first bad commit
commit af73956c304dab1582f713e48384cc6ad9cbf0af
Author: Karlchen <k_straussberger@netzland.net>
Date:   Sun Mar 21 23:25:00 2021 +0100

    Remove container if access to directory was removed

 src/content/content_manager.cc | 39 +++++++++++++++++++++++----------------
 1 file changed, 23 insertions(+), 16 deletions(-)
```

Hope this helps!

**Comment by neheb** [comment]
Reproduced on Fedora 34 with Os. Lovely...

**Comment by neheb** [comment]
https://github.com/neheb/gerbera/commit/84960fb91424fac7e745bf89be0fbd9247dafffd fixes it. I don't think the transformation is correct though...

**Comment by KarlStraussberger** [comment]
Looks like the initial `fs::directory_iterator dIter` call to default constructor gets optimized out for some reason.

You may try 
```
    auto dIter = fs::directory_iterator(".", ec); // current directory must be iterable
    auto rootDir = fs::directory_entry(location, ec);
```
instead. The objective of the code is to detect a missing directory and report it correctly before iterating its items.

From performance point of the view the change is not perfect because it reads the current dir each time. If it resolves the link issue we can work that out.

Another attempt may be to use
```
    std::unique_ptr<fs::directory_iterator> dIter;

    if (!ec && rootDir.exists(ec) && rootDir.is_directory(ec)) {
        dIter = std::make_unique<fs::directory_iterator>(location, ec);
```
(don't forget to add change `for (auto&& dirEnt : *dIter)`). Avoids extra iteration with a little extra cost for the `unique_ptr`

**Comment by neheb** [comment]
@KarlStraussberger it's not that it gets optimized out. It's that it's having issues reassigning dIter to something else, which is why it errors on some libstdc++ thing called swap. Note that

```
fs::directory_iterator dIter;
```

is equivalent to:

```
auto dIter = fs::directory_iterator();
```

My lambda solution assigns it once.

Anyway, your initial solution still fails to compile with the same error.

Wrapping it in unique_ptr works.

**Comment by neheb** [comment]
Size difference between unique_ptr and my lambda thing:

unique_ptr:
```
-rw-r--r-- 1 mangix mangix 2886841 Aug 22 16:43 bin/packages/aarch64_cortex-a53/packages/gerbera_1.9.0-1_aarch64_cortex-a53.ipk
```

lambda:
```
-rw-r--r-- 1 mangix mangix 2886397 Aug 22 16:45 bin/packages/aarch64_cortex-a53/packages/gerbera_1.9.0-1_aarch64_cortex-a53.ipk
```

**Comment by KarlStraussberger** [comment]
I suppose that in your lambda case you did not readd the log messages which are the core of the code.

**Comment by neheb** [comment]
Right. OTOH, WITH_DEBUG is disabled. I believe that makes the log_ functions noop.
