### ISSUE TITLE
gerbera/gerbera" does not exist.

### ISSUE THREAD

**Issue by gerroon** [gerbera/gerbera#168]
Hi

I am on Debian testing. I cloned the repo -> cd gerbera > mkdir build > cd build>run the line below

 cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_LASTFM=1

CMake Error: The source directory "/media/xxx/xxx/gerbera/gerbera" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

thanks

**Comment by gerroon** [comment]
Ok I ran cmake in the root folder then it works I am not sure if this is the wrong way or not but I compiled. Maybe the cd command was not supposed to be there?

**Comment by elmodaddyb** [comment]
@gerroon - I think you should be able to `cd` into the `build` directory and issue a command like below:

```
cmake ../ -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_LASTFM=1
```
I think the instructions assume that the directory structure is like below:
```
/folder/gerbera  <-- the clone'd repository
/folder/build <-- a separate build folder
```
This keeps build cruft out of your cloned working copy.  Its a bit easier to create a fresh build.

**Comment by gerroon** [comment]
Hi
Ok that makes sense. I assumed that the build was in gerbera.
