### ISSUE TITLE
X_GetFeatureList broken

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#1680]
It did migrate resources and rescanned everything. But now from a Samsung's client perspective it's completely broken. Trying to access gerbera from my TV gives me: "Request cannot be completed. MEDIA PLAY will return to the main screen".
My NAIM NDX music player can access gerbera no problem. Gerbera log is attached.
[gerbera.log.gz](https://github.com/gerbera/gerbera/files/6836850/gerbera.log.gz)

_Originally posted by @druban in https://github.com/gerbera/gerbera/issues/1672#issuecomment-882107981_

**Comment by KarlStraussberger** [comment]
@druban: I don't have a Samsung device at hand, can you please try this PR whether it solves your issue?

**Comment by druban** [comment]
Nope, same error ...

**Comment by KarlStraussberger** [comment]
I added two more Samsung extensions to UPnP actions. Can you try these out and grab the new debug-log.
Thank you.

**Comment by druban** [comment]
Same error, log is attached
[gerbera.log.gz](https://github.com/gerbera/gerbera/files/6842915/gerbera.log.gz)

**Comment by KarlStraussberger** [comment]
Thank you. Now I hope that I managed to fix the first error message. Maybe that makes the rest work as well. Otherwise I'm hoping for your log again.

**Comment by druban** [comment]
Is there a diff that I can test?

**Comment by KarlStraussberger** [comment]
Right after `X_GetFeatureList` there is/was an `error`.

**Comment by druban** [comment]
Not sure I understand ... Is that a question or a statement?

**Comment by KarlStraussberger** [comment]
I changed two lines in upnp_quirks that caused the `error` for featurelist. if that error is gone the tv may behave differently.

**Comment by druban** [comment]
Ahh, I see your change. Let me give it a shot

**Comment by druban** [comment]
Same error. Log is attached.
[gerbera.log.gz](https://github.com/gerbera/gerbera/files/6843846/gerbera.log.gz)

I don't need to start w/ a clean database, and re-import everything before testing, do I?

**Comment by KarlStraussberger** [comment]
Well, we have to reverse engineer the Samsung extension now. There is no open spec on the web, so I have to do like the few sources available do.

Last try for tonight!

**Comment by druban** [comment]
Sounds good and thanks for looking into this! Let me know if there's any other change you'd like me to test, or if there's something like a tcpdump output that might help.
Cheers!

**Comment by KarlStraussberger** [comment]
Tcpdump only helps if you have another media server, like Serviio, that is heavy enough to implement every small bit.

For now you can test my latest commit. I added content to the new actions. Hope that helps. Need some rest now :sleep:

**Comment by druban** [comment]
> Tcpdump only helps if you have another media server, like Serviio, that is heavy enough to implement every small bit.
> 
> For now you can test my latest commit. I added content to the new actions. Hope that helps. Need some rest now :sleep:

Well, Serviio is open source. Worst comes to worst, I could install/configure it on my server so we could analyze tcpdumps

**Comment by KarlStraussberger** [comment]
The diff is fine. I've already got a LG tcpdump I'm not able to analyze because of lack of time.

In your log I'm missing the result for `X_GetObjectIDfromIndex` which should be `<ObjectID>0</ObjectID>`. I assume that this result is sent as `ObjectID` in the next `doBrowse()` which is empty in the log. Outdated?

**Comment by KarlStraussberger** [comment]
I changed `X_GetFeatureList` to return a serialized string instead of a XML substructure. It's worth another try now.

**Comment by druban** [comment]
Tried it, same result. I'm a bit worried that I might have missed some part[s] of the patch. Could you please send a global diff that I could reapply w/ patch command? After I make sure changes are consistent, I'll post debug log.
Cheers!

**Comment by KarlStraussberger** [comment]
It's a git feature

https://github.com/gerbera/gerbera/pull/1681.diff

**Comment by druban** [comment]
Yay! We have a winner! With your last change set it works fine now!

**Comment by KarlStraussberger** [comment]
Thank you for sorting this out. :applause:
