### ISSUE TITLE
Samsung TVs order of content

### ISSUE THREAD

**Issue by Mikeput** [gerbera/gerbera#1703]
It works but it always list them in alpha order no matter what order Gerbera sends them in is there a way to specify the order in the XML sent to the device? or does the folder has been off a certain class? (possibly can modify them to be a track number for example)?

**Comment by KarlStraussberger** [comment]
Gerbera orders items by title except musicAlbum which is ordered by tracknumber.

On the other hand some players/devices download the whole folder and do their own sorting.

**Comment by Mikeput** [comment]
Yes, all i done is prefix it when an order if the player is Samsung, so it displays 001 etc before the filename to ensure its in the correct order. a bit rubbish but it works for the moment. similar to the already seen part already in place.   A dirty hack but works so far.

**Comment by KarlStraussberger** [comment]
I've done the same with music files because my player sorted them alphabetically inside an album.
