### ISSUE TITLE
FR: File date based sorting

### ISSUE THREAD

**Issue by gerroon** [gerbera/gerbera#171]
Hi

I know most people will say that sorting should be the player's feature but in reality that does not work because most players do not  really offer sorting let alone file date sorting.

I used to use UMS and it offered sorting based on the file mod date which was very helpful because that way it was easy to find the lastly added media to the library otherwise one has to keep track of all those files mentally. 

Maybe this can be for meta lists like albums, all audio etc.

thanks

**Comment by v00d00** [comment]
Nice idea.

I want to add a recently added folder to the default layout too.

**Comment by gerroon** [comment]
Thanks for considering.

That is one reason why I was running 2 Dlna servers on the same desktop! One was for regular sorting and the other was for date based sorting.

**Comment by gerroon** [comment]
@v00d00

How long do you think it would take to get this feature in Gerbera? I realize that developing open source is tedious stuff, just curious.

**Comment by v00d00** [comment]
My time has been taken up with other things lately :-1: , so I haven't been able to spend as much time on Gerbera as I would like. I think its unlikely to happen anytime soon unless we receive a patch from somebody to implement this.

**Comment by gerroon** [comment]
Understandable. Thanks for the update.

**Comment by elmodaddyb** [comment]
@gerroon ,

Can you help me understand a bit more how this should behave?

Where is it sorted by date.  when you view a list of items in any container (all items sorted by date)....or is it a Container that is named *Sort By Date* and within the library is re-organized by date for each container?

Any ideas?

**Comment by gerroon** [comment]
@elmodadyb

Persoanlly I am used to being able enter a drive "folder" and see my items sorted based on the date of mod time (not scan time, though that might be ok too). I use it like that in UMS but UMS is so memory hungry that I would like to move my stuff to Gerbera. 

The problem I see sort by date container is that it might not understand the the content of the folders well enough to provide a reasonable listing, for instance if we have sort albums by date, which might be ok given that grabbing tags from audio and creating an album list is doable (and then listing it based on lately modifed songs in the album)  but sort video by date might not be so sexy because most video might not have proper tags associations etc. That is why I think that sort by date should b e avail when browsing folders.

On the other hand to keep things organized, maybe Gerbera can offer the same folder stuff but in a sorted form under one of those meta containers.

**Comment by gerroon** [comment]
On the other hand some other DLNA servers provide things like, recently added, last added albums, latest songs etc etc which is fine for music stuff. I think that is useful too. 

The bottom line is this, you just added an awsome album to your lib and you wnt to listen it right away. D oyou want to spend some mins to locate it in your player or do you want to access it right away and play it for pleasure.

**Comment by elmodaddyb** [comment]
@gerroon - thanks for taking the time to discuss.  I like the idea of @latest or @recent @popular

**Comment by gerroon** [comment]
@elmodaddyb

Thanks for considering implementing this. 

While you are on it, I would like to also have recently played or accessed (via Gerbera) I do not have have access to  Gerbera atm, maybe it already provides it. 

@random album @random songs is good too ;)

**Comment by elmodaddyb** [comment]
I am starting to look at the shoutcast enhancement, but will need to gain better understanding of containers and the database storage. So it’s likely I will try this enhancement first.

**Comment by elmodaddyb** [comment]
So, taking a look at this in more detail.  Let's take **recently added music** scenario.  We could use dynamic container generation.

1. Create a new container chain in the database to hold `Recently Added` items...like.
```
/Audio/Recently Added/
```
2. During addition of new `object.item.audioItem` ... add a new entry to `Recently Added` container chain
3. Add a new property in `config.xml` which defines the **recent-range** value...such as hours, days, weeks.
4. Final step of add new item....trim `Recently Added` container data based on `#3`

_optionally_ 
_5.Create a task to cleanup expired recent objects (not a great idea)..._

Maybe we could also consider creating some type of custom **playlistContainer** as per the UPNP class specs...and then dynamically generate the recently added items into a playlist.
[http://upnp.org/specs/av/UPnP-av-ContentDirectory-v1-Service.pdf](http://upnp.org/specs/av/UPnP-av-ContentDirectory-v1-Service.pdf)

_Still working to see if any UPNP class provides for dynamic generation of a list of items...that way could be recognized by the storage system as special query..._

**Comment by ngosang** [comment]
Any update?

**Comment by KarlStraussberger** [comment]
Working lately on Upnp browse and search, I can imagine a config entry like

```
       <import>
                ...
		<containers>
			<container title="Last Added/7 Days" sort="-last_updated">upnp.class derivedfrom "object.item" and last_updated &lt; @last7</container>
			<container title="Last Added/31 Days" sort="-last_updated">upnp.class derivedfrom "object.item" and last_updated &lt; @last31</container>
		</containers>
       </import>
```

Sort could uses Upnp sort formatting, the content would be a Upnp search string. With a bit of additions (like last_updated and `@last7`)

**Comment by ngosang** [comment]
Working in Gerbera 1.9.0 but there are some changes regarding the previous comment:
```
<server>
...

    <containers enabled="yes">
      <container location="/LastAdded7Days" title="Recently Added 7 Days" sort="-last_updated">
        <filter>upnp:class derivedfrom "object.item" and last_updated &gt; "@last7"</filter>
      </container>
      <container location="/LastAdded30Days" title="Recently Added 30 Days" sort="-last_updated">
        <filter>upnp:class derivedfrom "object.item" and last_updated &gt; "@last30"</filter>
      </container>
    </containers>

</server>
```

Ref => https://github.com/KarlStraussberger/gerbera/blob/88345cda282b1a6110de4117fa72c08021f1aaa3/test/config/fixtures/mock-config-all.xml#L37

**Comment by KarlStraussberger** [comment]
I don't see the issue. We use a different setting in default than in the example. Both should work, don't they?

**Comment by ngosang** [comment]
The code in https://github.com/gerbera/gerbera/issues/171#issuecomment-861303918 is nor working for me.

**Comment by KarlStraussberger** [comment]
Thats the difference between idea and implementation. Run with `--create-config` and check out the documentation.
