### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by rubyFeedback** [gerbera/gerbera#1731]
Hey folks,

Please feel free to ignore this request, but I just found gerbera. I read the main README but
I am still not entirely sure what gerbera does exactly and how it fits into other multimedia-related
software.

Would it be possible to add a few screenshots that show some typical use cases? That way it
would do a quick visual impression of what can / could be done with gerbera.

At any rate, thank you for reading.

**Comment by KarlStraussberger** [comment]
Take a look here: https://gerbera.io and https://docs.gerbera.io/en/stable/ui.html

But the ui is not the main part. You need to have network media players or dlna tv sets to benefit from gerbera.
