### ISSUE TITLE
mysql-upgrade.xml broken

### ISSUE THREAD

**Issue by matthiasstraka** [gerbera/gerbera#1736]
In the latest MySQL upgrade script `src/database/mysql/mysql-upgrade.xml` version 13, the index generation script for grb_cds_resource_id is outside the `<script>` tag (Line 78) and therefore not executed

**Comment by KarlStraussberger** [comment]
Thanks for reporting this. Looks like a one off when adding the `<script>` blocks (mysql does not run multple commands)
