### ISSUE TITLE
Alow client and codec specific transcoding

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#1738]
I've tried using `client-flags` with transcoding profiles and they work just fine. However this issue is about ability to differentiate between codecs used in a specific container (or mimetype), and choose transcoding profile based on that.

Thus, "Allow codec specific transcoding" would be super-awesome!

_Originally posted by @kyak in https://github.com/gerbera/gerbera/issues/1201#issuecomment-890967545_

**Comment by kyak** [comment]
Let me explain my use case.

I have one TV that support modern codecs, like x264/x265 but doesn't support older like XviD.

I have another TV that supports XviD and x264, but not x265.

For the first TV, I'm transcoding from XviD to MPEG based on that TV's client-flags. I'm very glad that I can do this only for this TV based on client-flags.

For the second TV, I want to transcode from x265 to x264. But, both x265 and x264 are using the same .mkv file extension and x-matroska mimetype. I don't want to waste resources transcoding x264 for this TV.

If there was a way to narrow that to x265, that would be great.

**Comment by KarlStraussberger** [comment]
Maybe #1972 can improve the situation a bit.

**Comment by kyak** [comment]
@KarlStraussberger can you please elaborate? I don't really understand how to use new `dlna-profile` setting to achieve what's explained in the use case.

**Comment by KarlStraussberger** [comment]
The new `dlna-profile` is used as output only for devices to pick the right (transcoded) stream. So if you just have `AVC_MP4_EU` your tv set will pick it but if it says `AVC_MP4_MP_HD_720p_AAC` it won't because it does not support AAC encoding.

**Comment by kyak** [comment]
You are talking about device picking the right transcoded stream. This implies that there could be more than one transcoded stream. I don't get this part, how do I output more than one transcoded stream? There is a one to one mapping between mimetype and transcoding profile.

**Comment by KarlStraussberger** [comment]
You can keep the original stream. Good point to allow one to many as part of this issues' solution.

And the profile may be necessary for the device to accept the stream.
