### ISSUE TITLE
FreeBSD build error

### ISSUE THREAD

**Issue by imp1sh** [gerbera/gerbera#176]
Hi,

I'm on
FreeBSD 11.0-STABLE FreeBSD 11.0-STABLE #0 r321665+25fe8ba8d06(freenas/11.0-stable): Mon Sep 25 06:24:11 UTC 2017
It's actually a jail running on FreeNAS 11.
Gerbera build
af663af395b9ff04d9ab2104d5bc43031d74db88

When I follow the instructions I get this error:
```
$ cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0
-- Looking for BSD native UUID
-- Looking for BSD native UUID - found
-- Found Sqlite3: /usr/local/lib/libsqlite3.so
-- Looking for native inotify
-- Looking for native inotify - not found
-- Looking for libinotify
-- Looking for libinotify - found
-- Found TagLib: -L/usr/local/lib -ltag
-- Could NOT find Systemd (missing: SYSTEMD_FOUND)
CMake Error at CMakeLists.txt:577 (message):
  Systemd not found


-- Configuring incomplete, errors occurred!
See also "/home/username/build/CMakeFiles/CMakeOutput.log".
See also "/home/username/build/CMakeFiles/CMakeError.log".
```

Output.log
https://paste.fedoraproject.org/paste/iIIyaB3KlgIJEQ4DqoVbMQ
Error.log
https://paste.fedoraproject.org/paste/eXMoFQZgattZEY4NPKueUw

**Comment by asavah** [comment]
Obviously add `-DWITH_SYSTEMD=0` for *BSD

**Comment by elmodaddyb** [comment]
Yep, **SYSTEMD** is **ON** by default

**Comment by imp1sh** [comment]
I don't know why issues get closed down so fast.
I issued a pull request because documentation was OBVIOUSLY wrong.
