### ISSUE TITLE
Gerbera 1.9.0 playback on Samsung 40C6000 TV broken

### ISSUE THREAD

**Issue by EricdeWaal** [gerbera/gerbera#1761]
Hi,

After a new install of Gerbera, playback on my Pioneer N30 still works, but not anymore on the Samsung TV. 
 'systemctl status gerbera' shows the next errors:

Aug 06 13:07:26 NAS gerbera[766]: 2021-08-06 13:07:26  error: ActionRequest::update(): response is nullptr, code 0 for X_GetFeatureList
Aug 06 13:07:27 NAS gerbera[766]: 2021-08-06 13:07:27  error: ActionRequest::update(): response is nullptr, code 0 for X_GetObjectIDfromIndex

Up to Gerbera 1.8.2 there was no problem. I use the deb package from deb-multimedia, (1:1.9.0-dmo0~bpo10+1) a backport to debian buster 64 bits.
Config is default with 2 exeptions: I use a MYQSL database and structured audio layout.

**Comment by KarlStraussberger** [comment]
Seems your device is not detected automatically.

Check the *Flags* on the clients page on web ui and add the *User Agent* to config with *SAMSUNG* flag.

**Comment by EricdeWaal** [comment]
The clients page shows:
<html><body>


IP Address | Host Name | Profile | User Agent | Match Type | Match Pattern | Client Type | First Seen | Last Seen | Quirk Flags
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
192.168.0.249 | 192.168.0.249 | Unknown | DLNADOC/1.50 | None |   | None | Fri Aug 06 15:43:29 2021 | Fri Aug 06 15:43:29 2021 | None


</body>
</html>
So I added in the server section:
`<clients enabled="yes">
    <client ip="192.168.0.249" flags="SAMSUNG"></client>
</clients>`
But no luck

**Comment by EricdeWaal** [comment]
`	<clients enabled="yes">

		<client ip="192.168.0.249" flags="SAMSUNG"></client>

	</clients>`
Sorry, code was missing

**Comment by EricdeWaal** [comment]
Also via the config screen it does not work; I made the following settings:

![afbeelding](https://user-images.githubusercontent.com/5586423/128523871-20b81826-eddc-405d-9725-b35feb7576a4.png)

**Comment by KarlStraussberger** [comment]
You should not set UserAgent and IP at the same time (I'd prefer IP). What's in the clients table after setting the flag? Is there another message in the log?

**Comment by EricdeWaal** [comment]
OK, now I set IP only, same result. message:
Aug 06 16:57:13 NAS gerbera[2107]: 2021-08-06 16:57:13  error: ActionRequest::update(): response is nullptr, code 0 for X_GetFeatureList
Aug 06 16:57:14 NAS gerbera[2107]: 2021-08-06 16:57:14  error: ActionRequest::update(): response is nullptr, code 0 for X_GetObjectIDfromIndex

**Comment by KarlStraussberger** [comment]
If the clients table does not contain `SAMSUNG` flag, it cannot work `clients` is not in `server` but after it (or before)!

**Comment by EricdeWaal** [comment]
I DID put SAMSUNG in the webconfig field:
![afbeelding](https://user-images.githubusercontent.com/5586423/128535910-75a53a81-92f5-435a-b407-65fae697c0c3.png)
No luck.

Then I removed it and put the `clients` in config.xml outside `server`
**Now it works! Thanks a lot!**
But how come that the webconfig does not work?

**Comment by KarlStraussberger** [comment]
I'll put it as another issue of the web ui.

**Comment by KarlStraussberger** [comment]
It would have worked if you restarted the server after adding the client via UI.
