### ISSUE TITLE
libduktape.so.201 not found on Debian source install

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#178]
I tried to update gerbera to the latest git version only to find that it needed duktape now.
Thus I ran the script `./scripts/install-duktape.sh`, which put the compiled lib into `/usr/local/lib/libduktape.so.201`.

Now I compiled gerbera, installed it and tried to start it. It fails with:

    /usr/local/bin/gerbera: error while loading shared libraries:
    libduktape.so.201: cannot open shared object file: No such file or directory

Using `strace` I see that gerbera does not try to load the lib from `/usr/local/lib`.

How can I get gerbera to use the locally installed duktape lib? (For now I made a symlink from `/usr/lib/libduktape.so.201` to `/usr/local/lib/libduktape.so.201` which works, but that shouldn't be necessary).

**Comment by v00d00** [comment]
CMake should put the rpath of the libraries into the Gerbera binary, so this is strange...

Is /usr/local/lib on your `LD_LIBRARY_PATH`?

**Comment by cweiske** [comment]
```
root@dojo:/usr/local/src/gerbera> echo $LD_LIBRARY_PATH

```

apparently it's empty. No idea why.

**Comment by v00d00** [comment]
what does `ldd gerbera` give you?

**Comment by cweiske** [comment]
```
$ ldd `which gerbera`
	linux-vdso.so.1 (0x00007ffdf9be0000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f10871d3000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f1086fce000)
	libupnp-1.8.so.10 => /usr/local/lib/libupnp-1.8.so.10 (0x00007f1086d9c000)
	libixml-1.8.so.10 => /usr/local/lib/libixml-1.8.so.10 (0x00007f1086b92000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f1086969000)
	libsqlite3.so.0 => /usr/lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f108669f000)
	libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f1086487000)
	libduktape.so.201 => /usr/lib/libduktape.so.201 (0x00007f1086246000)
	libmysqlclient.so.18 => /usr/lib/x86_64-linux-gnu/libmysqlclient.so.18 (0x00007f1085d01000)
	libcurl.so.4 => /usr/lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f1085a8d000)
	libmagic.so.1 => /usr/lib/x86_64-linux-gnu/libmagic.so.1 (0x00007f108586d000)
	libexif.so.12 => /usr/lib/x86_64-linux-gnu/libexif.so.12 (0x00007f1085627000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f108540c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f1085101000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f1084dff000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1084a54000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f108483e000)
	/lib64/ld-linux-x86-64.so.2 (0x000055892746a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1084639000)
	libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f1084405000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f10841e8000)
	libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f1083fbe000)
	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f1083d5d000)
	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f1083961000)
	libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f1083715000)
	libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f1083441000)
	libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f1083210000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f108300b000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f1082dfc000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f1082baa000)
	libgnutls-deb0.so.28 => /usr/lib/x86_64-linux-gnu/libgnutls-deb0.so.28 (0x00007f108288a000)
	libhogweed.so.2 => /usr/lib/x86_64-linux-gnu/libhogweed.so.2 (0x00007f108265b000)
	libnettle.so.4 => /usr/lib/x86_64-linux-gnu/libnettle.so.4 (0x00007f1082428000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f10821a5000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f1081ec4000)
	libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f1081cb7000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f1081ab3000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f108189c000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f108167f000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f1081439000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f1081224000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f1081012000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f1080e08000)
```

(duktape is the symlink)

**Comment by v00d00** [comment]
Can you paste your CMake log?

**Comment by cweiske** [comment]
http://tmp.cweiske.de/gerbera-cmakeoutput.log

**Comment by SilentButeo2** [comment]
Have the same issue on Ubuntu 
Maybe this could help?
https://github.com/nanomsg/nanomsg/issues/798

**Comment by jcowgill** [comment]
I just had an experiment to see if I can reproduce this. Is your umask set to something other than `022`? The duktape Makefile uses `cp` instead of `install` so it will install all the libraries using your umask. If your `umask` is `077` (the default on Ubuntu I think) then the installed libraries will be readable only by root.

**Comment by SilentButeo2** [comment]
`/usr/local/lib$ ls -la
drwxr-xr-x  6 root   root     4096 Nov 15 12:44 .
drwxr-xr-x 10 root   root     4096 Apr 30  2017 ..
lrwxrwxrwx  1 root   root       24 Nov 15 12:44 libduktaped.so -> libduktaped.so.201.20100
lrwxrwxrwx  1 root   root       24 Nov 15 12:44 libduktaped.so.201 -> libduktaped.so.201.20100
-rwxr-xr-x  1 root   root  1506504 Nov 15 12:44 libduktaped.so.201.20100
lrwxrwxrwx  1 root   root       23 Nov 15 12:44 libduktape.so -> libduktape.so.201.20100
lrwxrwxrwx  2 root   root       23 Nov 15 12:44 libduktape.so.201 -> libduktape.so.201.20100
-rwxr-xr-x  2 root   root   325576 Nov 15 12:44 libduktape.so.201.20100
`
seems that all are readable by everyone after install.

On my setup, the umask:
$umask
0002
$ umask -S
u=rwx,g=rwx,o=rx

**Comment by v00d00** [comment]
I wonder if there is anything in your system journal, perhaps its getting blocked for some reason? (apparmor?)

**Comment by cweiske** [comment]
On my system umask is `0022`, and I do nothave apparmor enabled.

**Comment by cweiske** [comment]
I have the same problem when installing libupnp with `--prefix=/usr/local` - libupnp does not get found then:

```
$ gerbera --help
gerbera: error while loading shared libraries: libupnp.so.10: cannot open shared object file: No such file or directory

$ ldd /usr/local/bin/gerbera|grep upnp
	libupnp.so.10 => not found
```

**Comment by cweiske** [comment]
Ok, found the issue.

Gerbera could be started after doing this:

```
$ export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
```
(was empty before)

But even without that, simply running `ldconfig` made it work, too:

```
$ # install libupnp or libduktape
$ ldconfig
$ gerbera --help
.. works
```
