### ISSUE TITLE
Freebsd 11.1 multiple ip

### ISSUE THREAD

**Issue by syntezit** [gerbera/gerbera#179]
On one interface 2 ip
172.16.0.1 - basic
172.16.1.1 - alias
When you specify the key -i 172.16.0.1.
Gerbera ignores this parameter and starts on 172.16.1.1.
Because of this, the dlna client can not receive content.
Writes a "no file" error.
In config.hml - this parameter is also ignored.
If you remove the alias, then everything works fine.

P.S. Sorry for my English. I write with the aid of google translate.

**Comment by v00d00** [comment]
libupnp has no real concept of binding to an IP as far as I can remember.

So what we so do is find the interface with that IP on it, and then tell libupnp to bind to that.

Not sure what we can do here, short of adding support in the upstream project, but I will leave this open until we have time to investigate it.

**Comment by v00d00** [comment]
Unfortunately this is not possible with libupnp at the moment, they would need to add new `UpnpInit` call to allow this: https://github.com/mrjimenez/pupnp/blob/master/upnp/inc/upnp.h#L580

You could perhaps raise it with them?

**Comment by crass** [comment]
I'm having this issue as well.  I have an interface with multiple IPs (one is aliased) and when I set the `<ip>` config value to the alias IP, gerbera starts and listens on the primary IP. 

> Unfortunately this is not possible with libupnp at the moment, they would need to add new `UpnpInit` call to allow this: https://github.com/mrjimenez/pupnp/blob/master/upnp/inc/upnp.h#L580
> 
> You could perhaps raise it with them?

While pupnp definitely leaves much to be desired, it does not appear that the statement above is quite correct.  [`UpnpInit`](https://github.com/pupnp/pupnp/blob/7a7c5339f78dc03e58b82207f65d88e7bfc22d6b/upnp/inc/upnp.h#L546) actually does appear to allow binding to a specific IP address.  Gerbera uses `UpnpInit2` which takes an interface name and selects the first ipv4 IP, if it has multiple ones.

I propose that in [`Server::run()`](https://github.com/gerbera/gerbera/blob/1603016cf980e659ce55a9aa9a803e79644b5de0/src/server.cc#L111) if `<ip>` is specified that `UpnpInit` is used and if `<interface>` is specified `UpnpInit2` is used.  The current behavior should be used if neither `<ip>` or `<interface>` is used.
