### ISSUE TITLE
Debian Stable deb packaging failing on master

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#1797]
https://github.com/gerbera/gerbera/runs/3339421247

**Comment by KarlStraussberger** [comment]
Looks like a DNS caching issue or a broken container.

```
404  Not Found [IP: 151.101.66.132 80]
...
E: The repository 'http://security.debian.org/debian-security stable/updates Release' does not have a Release file.
Error: Process completed with exit code 100.
```

I see a `stable-security/updates` in `http://security.debian.org/debian-security`. We only run `apt-get update -y`

**Comment by KarlStraussberger** [comment]
issue is gone. Maybe caused by debian version upgrade
