### ISSUE TITLE
Freebsd 11.1 pupnp-1.8.1 error start gerbera

### ISSUE THREAD

**Issue by syntezit** [gerbera/gerbera#180]
If you compile with pupnp-1.8.1, gerbera does not start.
##error##
Exception raised in [src/server.cc:123] upnp_init(): upnp_init: UpnpInit failed
   ERROR: main: upnp error -203
   ERROR: Could not bind to socket.
    INFO: Please check if another instance of Gerbera or
    INFO: another application is running on port 49152.
   ERROR: upnp_cleanup: UpnpUnRegisterRootDevice failed
Exception raised in [src/server.cc:248] shutdown(): upnp_cleanup: UpnpUnRegisterRootDevice failed
##error#

It is necessary in the script install-pupnp18.sh to change

release-1.8.1 to release-1.8.2

####install-pupnp18.sh####
#!/bin/sh
set -ex

unamestr=`uname`
if [ "$unamestr" == 'FreeBSD' ]; then
   extraFlags=""
elif [ "$unamestr" == 'Darwin' ]; then
   extraFlags="--prefix=/usr/local"
else
   extraFlags="--prefix=/usr"
fi

wget https://github.com/mrjimenez/pupnp/archive/release-1.8.2.tar.gz -O pupnp-1.8.2.tgz
tar -xzvf pupnp-1.8.2.tgz
cd pupnp-release-1.8.2
./bootstrap && ./configure $extraFlags --enable-ipv6 --enable-reuseaddr && make && sudo make install
####end####

Then everything starts.

P.S. Sorry for my English. I write with the aid of google translate.

**Comment by v00d00** [comment]
That is interesting and clearly an upstream libupnp bug. I guess it was fixed by #12 and https://github.com/mrjimenez/pupnp/pull/47.

Can you make a pull request to update the FreeBSD build instructions?

**Comment by v00d00** [comment]
Lets close this as per #181
