### ISSUE TITLE
Can the version number start with a digit and not a 'v'

### ISSUE THREAD

**Issue by BobManMasher** [gerbera/gerbera#1814]
Currently I have to manually add a version number in CMakeLists.txt when compiling Gerbera versions because when the debian armel package is created and I try to install it, the following error is produced:

> sudo dpkg -i *.deb
dpkg: error processing archive gerbera_v1.9.0-78-gb0ce736f_armel.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 8 package 'gerbera':
 'Version' field value 'v1.9.0-78-gb0ce736f': version number does not start with digit
Errors were encountered while processing:
 gerbera_v1.9.0-78-gb0ce736f_armel.deb

Is it possible for future builds to remove the 'v' at the start of the build number?

**Comment by whyman** [comment]
The script used in the CI overrides the version, so I guess you will need to do similar.
```
git_ver=$(git describe --tags | sed 's/\(.*\)-.*/\1/' | sed s/-/+/ | sed s/v//)
```

From https://github.com/gerbera/gerbera/blob/master/scripts/debian/build-deb.sh
