### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by bouwew** [gerbera/gerbera#1815]
![image](https://user-images.githubusercontent.com/11290930/130317925-3c830447-6794-4ccc-b34c-41b87f6e2f65.png)

This is on a ProxMox VM running Debian.
I'm pulling from the master-branch and using the default build process as indicated in the README.

**Comment by whyman** [comment]
Which version of `fmt` do you have?

**Comment by bouwew** [comment]
![image](https://user-images.githubusercontent.com/11290930/130323236-0d81e9f2-f37f-4578-a910-db57732adca9.png)

**Comment by bouwew** [comment]
Wait, the script did install `libfmt.so` v7.1.3

The above version is for `/usr/bin/fmt`

**Comment by KarlStraussberger** [comment]
You can run `install-fmt.sh static` to get a static lib only. But that may still collide with the one already installed (/usr/lib is searched before /usr/local/lib).

**Comment by KarlStraussberger** [comment]
> Wait, the script did install `libfmt.so` v7.1.3
> 
> The above version is for `/usr/bin/fmt`
> 
> From the picture it looks like the correct version of fmt is used, from `/usr/local/include/spdlog/fmt`.

You may need to run `install-spdlog.sh` because it builds `spdlog` without bundled `libfmt` allowing the one installed with `install-fmt.sh` to become active.

**Comment by bouwew** [comment]
Thank you, that works!
