### ISSUE TITLE
Currently broken against git master branch of pupnp; missing cookies

### ISSUE THREAD

**Issue by whorfin** [gerbera/gerbera#182]
This commit: mrjimenez/pupnp@ed501e14b2b1974a887e5a3b2297e3182af51674
[per v00d00] added a mandator userdata/cookie to virtualDir calls and callbacks

But gerbera does not yet provide them.
This causes build failures with eg
```
src/server.cc:170:54: error: too few arguments to function ‘int UpnpAddVirtualDir(const char*, const void*, const void**)’
  ret = UpnpAddVirtualDir(virtual_directory.c_str());
```

**Comment by v00d00** [comment]
Fixed by using the cookies 🍪 👍 

https://github.com/gerbera/gerbera/commit/55396b59027f12a8da09e81a83c7565051466159
