### ISSUE TITLE
Only one subtitle file embedded

### ISSUE THREAD

**Issue by stinovlas** [gerbera/gerbera#1826]
Hello, I just started using Gerbera yesterday and I already like it. What a great software solution!

I use Gerbera UPnP Server version: 1.8.2 (from the PPA).

I tried adding subtitles to my movies by following ocnfiguration:

```
  <import>
    <resources>
      <subtitle>
        <add-file name="%filename%.sub"/>
        <add-file name="%filename%.srt"/>
      </subtitle>
      <resource>
        <add-file name="%filename%.sub"/>
        <add-file name="%filename%.srt"/>
      </resource>
    </resources>
    ...
  </import>
  ...
```

When I play a movie over network with just `.sub` or `.srt` subtitles, everything works as expected. Subtitle stream is added to the movie. However, when both `.sub` and `.srt` are present for the movie, only the former is added. When I change the configuration and state the `.srt` first, then it's added and `.sub` is ignored. All considered, it seems that gerbera only adds first subtitle file found and ignores the other ones.

Also, is there any way to specify subtitles encoding? Or does gerbera expect UTF-8 everywhere? If so, it's not a big hassle to convert them, just asking.

**Comment by KarlStraussberger** [comment]
Thanks for using and celebrating gerbera.

Multiple subtitles are supported as of 1.9.0 :smile_cat:

Gerbera does not do anything with the content of subtitle files, it's your clients task. From the international point of view UTF-8 is the better choice.

**Comment by stinovlas** [comment]
Thank you for a quick response! I'll try 1.9.0 and report back.

I concur that UTF-8 is the best solution, it's just that most of the czech subtitles you can download are encoded in `cp1250` and it's kind of a chore to convert them. I'll have to write a script for that ;-).

**Comment by stinovlas** [comment]
Works like a charm, thank you very much for your help =o). All the subtitles are now used with my configuration.

**Comment by kane69** [comment]
Hi @stinovlas, im new to GitHub - this is my first activity :). I really like gerbera however I hit the wall with external subtitles.
Im wondering if you could have looked at an issue of mine.
I keep subtitles in the same directory as a video file, subtitles format srt. despite my best effort, I cannot force subs propagation 

Platform details

NAME="Linux Mint"
VERSION="20.2 (Uma)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.2"
VERSION_ID="20.2"
VERSION_CODENAME=uma
UBUNTU_CODENAME=focal

gerbera
Gerbera UPnP Server v1.9.2-201-g6abbbeb9
Copyright 2016-2021 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.

in the config file, I added a section recommended by you - unfortunately still no success with external subtitles.
*.srt files are not propagated regardless of the receiver device LG_tv or mobile phone etc

snipped config file
![image](https://user-images.githubusercontent.com/94906744/143035399-80d2c1dd-3bc6-41ad-b5c4-184c12fcfdb1.png)

**Comment by kane69** [comment]
this part is also reflected in the UI config 

![image](https://user-images.githubusercontent.com/94906744/143039069-165c0283-a211-40e2-ba09-76419401725a.png)

**Comment by KarlStraussberger** [comment]
Thank you for using Gerbera and your request.

I assume you ran the import after adding the resources section (you don't really need `%filename%.sub`) to the config. Otherwise just delete the sqlite file and its backup and restart gerbera.

To verify the import you can check out an item's properites in `Database`. (Press _Show Details_) If it shows the subtitle resource we need to investigate on the upnp telegram otherwise the import process.

**Comment by kane69** [comment]
Hi @KarlStraussberger, thanks for the quick response -really appreciate that. I have checked if files exist in DB. It seems that both files are available in DB - both files with labels type -item. Class for movie== object.item.videoItem and for subs object.item

![image](https://user-images.githubusercontent.com/94906744/143054956-733aa972-d65f-4128-9646-20dd192793d8.png)

As per Your recommendation, I have removed sub from config and restarted the service

![image](https://user-images.githubusercontent.com/94906744/143056606-90dd4a79-856b-4a80-856c-b1d1299a39ab.png)

![image](https://user-images.githubusercontent.com/94906744/143056986-35247422-d4f7-4785-ad05-80d0c51794d4.png)

Please let me know what should I do as the next step in an investigation :) 

Best,
Marek

**Comment by KarlStraussberger** [comment]
Can you share please the details view of the movie, too.

**Comment by kane69** [comment]
hi @KarlStraussberger, subtitles are working now. It was my mistake or lack of experience that was causing the problem.
Gerbera is working excellently, as expected 

Thanks for your support

**Comment by KarlStraussberger** [comment]
Thank you for closing the issue. Feel free to come back with any question regarding gerbera.

**Comment by nakhla** [comment]
Dear Mr Karl
I have installed latest gerbera v2.1 on ubuntu focal and is working great seeking and pausing on my samsung tv, but i need to propagate subtitles across the movie.

I edited the confix.xml and added these lines between the <import></import> tags
`<resources>
      <subtitle>
        <add-file name="%filename%.srt"/>
      </subtitle>
      <resource>
        <add-file name="%filename%.srt"/>
      </resource>
  </resources>
`
then cleared all the database, and add one movie with subtitle in the same directory and added the movie from the webui but it just don't working, do i miss something, I found that this issue related to me so i posted it here, thanks for this amazing peace of software

**Comment by KarlStraussberger** [comment]
Subtitles on Samsung TVs is very sophisticated and might still be broken with 2.1 (Might be the device or gerbera, but none of us has such a device). There are other issues concerning that topic, where you may some helpful notes for your device. Other than that you may open a new issue with all the details on your device.
