### ISSUE TITLE
Sometimes binds the server to incorrect port

### ISSUE THREAD

**Issue by stheine** [gerbera/gerbera#1847]
Hi,

I have the gerbera server configured on a specific port. for making it available via docker and firewall, the server should be really on that specific port.
but on startup, sometimes the gerbera server comes up on a different port. typically that happens when I restart the server, so I could imagine that somehow the previous server still blocks the port during shutdown, so the new server cannot register there - and then it seems to increase the numbers to find the next available port.

in case the configured port cannot be used as it is blocked by something else, I would like the gerbera server not to start up on a different port, but fail with an appropriate error message, reporting that the port cannot be used.

> 2021-08-27 12:31:15   info: Initialising UPnP with interface: <unset>, port: 59154
> 2021-08-27 12:31:15   info: IPv4: Server bound to: 192.168.6.7:59160
> 2021-08-27 12:31:15   info: IPv6: Server bound to: fe80::265e:beff:fe21:a8b6:59154
> 2021-08-27 12:31:15   info: IPv6 ULA/GLA: Server bound to: 2002:5fd0:995f:0:265e:beff:fe21:a8b6:59154
> 2021-08-27 12:31:15   info: The Web UI can be reached by following this link: http://192.168.6.7:59160/

this happens in 1.9.1 as well as in previous builds.

Regards
  stheine

**Comment by neheb** [comment]
@stheine It's probably related to libupnp built without reuse addr.

**Comment by ngosang** [comment]
Probably fixed by #2313
