### ISSUE TITLE
Bleeding edge dependency versions make deployment difficult

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#1851]
Can you guys chill with the bleeding edge dependencies? I'm not trying to be a stick in the mud here but you just bumped spdlog and libfmt requirements in a patch release. Come on guys.

This is project is a media _server_, which means it'll likely be running on _server_ OSes. These rarely have the latest versions available in their package managers.  Even my desktop distro doesn't have them some of these dependency versions available.

* libfmt 7.1.3 - Released less than a year ago. On Ubuntu, it's only available for 21.04 which was released a mere four months ago.
* spdlog 1.8.2 - Released less than a year ago. Not even available in Ubuntu 21.04.
* pupnp 1.14.0 - Released just over a year ago. Not available in any version of Ubuntu

**Comment by whyman** [comment]
We will always track pretty closely to the latest version of libupnp for hopefully fairly obvious reasons. A decent number of changes to libupnp recently have been because of Gerberas requirements and a number of bug fixes have direct impact on Gerbera.

I do think that installing libfmt/spdlog should be easier. Perhaps we should follow the lead of other projects and bundle them into our repo, but I am personally not a fan of that approach. Another option would be having CMake download and build them if they are not found.

We do provide scripts to build and install the deps in the scripts directory, and you can also use Conan which would download the libraries from its own repos instead.

That said, I agree that not being able to use the packages directly from your distro is annoying.

**Comment by neheb** [comment]
libfmt dependency is probably artificial. See: https://github.com/gerbera/gerbera/pull/1779

No comment on spdlog.

The pupnp thing is weird. Is npupnp available?

**Comment by KarlStraussberger** [comment]
The dependency to upnp cannot be discussed because it carries features and security. Most distros just don't care about it and ship stuff like 1.6!

spdlog and fmt are compile time dependencies and linked statically.

**Comment by matthiasstraka** [comment]
Besides upnp, would it make sense to ease libfmt and spdlog requirements to 7.1.3 and 1.8.1 to increase compatibility with the latest Ubuntu? This was also a major issue to get me started in the beginning. Is [spdlog 1.8.2](https://github.com/gabime/spdlog/releases/tag/v1.8.2) essential?

**Comment by KarlStraussberger** [comment]
As in most parts it's the topic of testing.

After starting to use `fmt::join` compilation was broken and the fastest way is to go for stuff that's already running and well tested. There may be versions in between that work also but they were never tested with gerbera.

On the other hand both are compile time dependencies and we provide the proper scripts to build them from its sources, only developers and early adopters are really getting in touch with them. From a developers perspective, it's a lot simpler to browse the web for current specs compared to searching for historic revisions.

**Comment by matthiasstraka** [comment]
I did a quick check on a clean machine, there was only one line of code broken with spdlog 1.8.1 (`log_debug("start upnp: {}; ui: {}", fmt::join(maybeEmpty->upnp, ","), fmt::join(maybeEmpty->ui, ","));` in sql_database.cc:1741) which can easily be fixed (basically rendering the joins as strings and then passing them to log_debug). Also, I found an error in comile.rst for downloading the 1.14.0 upnp (still uses 1.12). I can later add a PR that fixes that if you want.

**Comment by matthiasstraka** [comment]
I added [PR 1944](https://github.com/gerbera/gerbera/pull/1944) where I downgraded to libspdlog to 1.8.1 to make it easier to compile with Ubuntu Hirsute. Since the required change is minimal, we should consider this change. This won't break anything for people using newer versions of libspdlog.

**Comment by mill1000** [comment]
> Taglib 1.12 is now required ([8b37173](https://github.com/gerbera/gerbera/commit/8b371731e35fde2eaa0fae10d1cce0272562a587)), but Debian 11 (latest stable) ships v1.11.1 (https://packages.debian.org/bullseye/libtag1-dev). Yes I use `scripts/install-taglib.sh`, but still.

Ubuntu 20.04 also lacks Tablib 1.12

**Comment by neheb** [comment]
@mill1000 you may want to look at https://github.com/gerbera/gerbera/pull/1868

The dependencies are implemented as subprojects. ninja install will install them to /usr/local by default.

**Comment by mill1000** [comment]
Is the (newish) CMake 3.18 a hard dependency? I was able to successfully build with CMake 3.13.4
https://github.com/gerbera/gerbera/blob/0a2e46b8b884cf0690669c4170b3b451575b2f64/CMakeLists.txt#L1
introduced here ac05976dda335ce1c28a5cc78e4e009a145e3559

**Comment by whyman** [comment]
> Is the (newish) CMake 3.18 a hard dependency? I was able to successfully build with CMake 3.13.4
> 
> https://github.com/gerbera/gerbera/blob/0a2e46b8b884cf0690669c4170b3b451575b2f64/CMakeLists.txt#L1
> 
> introduced here [ac05976](https://github.com/gerbera/gerbera/commit/ac05976dda335ce1c28a5cc78e4e009a145e3559)

IIRC Its only strictly needed for targets that are `IMPORT GLOBAL` or something like that, which is used for e.g. Conan's provided modules.

**Comment by cweiske** [comment]
Ubuntu 20.04 LTS ships CMake 3.16.3, so I can't build gerbera on that.

**Comment by neheb** [comment]
should be buildable with the meson PR. What's the issue with older cmake?

**Comment by mill1000** [comment]
I finally drank the Docker koolaid. Dependencies are no longer my problem. :)

Any reason I shouldn't close this?

**Comment by KarlStraussberger** [comment]
Thank you for staying with us.
