### ISSUE TITLE
Search returns duplicate results for albums due to virtual containers

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#1863]
Gerbera v1.9.1

Searching for an album returns duplicate results as shown in the screenshot. 

![Screenshot_20210829-160526](https://user-images.githubusercontent.com/6924622/131267161-298aec02-d71a-4fa7-8d46-083a14dc838d.png)

The duplicate results are from each virtual container that has `upnp_class` set to `object.container.album.musicAlbum`. 
![image](https://user-images.githubusercontent.com/6924622/131267213-a0a985fa-25f2-4a90-a589-4c04d9224d62.png)

This database was imported using the default JS import script. My custom import script has even more duplicates due to additional virtual containers. 

Removing upnp_class from the additional containers eliminates them from the search results, but browsing behavior is negatively impacted as the control point no longer knows to display the container as a music album.

Music track's don't have this issue. Perhaps the same approach could be used here. For each album, a "root" item is added to the database with `upnp_class = object.container.album.musicAlbum`. Each virtual container references this "root" album via `ref_id`.

**Comment by KarlStraussberger** [comment]
The result is correct from the database point of view. The search matches for each virtual entry and the query does not know which is the _correct_ one (PC Directory may be hidden). In my opinion we should prefix the search result with the full virtual path or add a flag to the import which item is searchable.

**Comment by mill1000** [comment]
A flag to the import would be akin to the idea of a "root" item I suppose.

I don't think there is any situation where I would want all 3 results, full paths or not.

**Comment by KarlStraussberger** [comment]
Actually, everything needed was already there but not stored to database for containers. Now you can enable it in the config.
