### ISSUE TITLE
Title displayed in search results does not match title displayed during browse

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#1867]
Last one for a bit I promise.

The title displayed for an item in search does not match the title that is displayed when browsing. The title for search appears to be the raw dc_title field from that database. I think we should populate the title from metadata instead.

Population from metadata is specifically blocked here:
https://github.com/gerbera/gerbera/blob/9aaddea1306f16de227ffa441dac96ac15dde189/src/upnp_xml.cc#L161-L163

which was likely to prevent modification of the title which may have
- Been truncated due to size
- Modified to include a "Played" indicator

Instead, we could update the title when building the CdsObject like so:
```patch
diff --git a/src/database/sql_database.cc b/src/database/sql_database.cc
index 7d8913f5..cce34b94 100644
--- a/src/database/sql_database.cc
+++ b/src/database/sql_database.cc
@@ -1389,7 +1389,10 @@ std::shared_ptr<CdsObject> SQLDatabase::createObjectFromSearchRow(const std::uni
 
     auto meta = retrieveMetadataForObject(obj->getID());
     if (!meta.empty())
+    {
         obj->setMetadata(meta);
+        obj->setTitle(meta[MetadataHandler::getMetaFieldName(M_TITLE)]);
+    }
 
     auto resources = retrieveResourcesForObject(obj->getID());
     if (!resources.empty()) {
```

If the devs feel like this is something worth doing I can packaged it up in a proper PR

**Comment by neheb** [comment]
PR would be lovely.
