### ISSUE TITLE
Device specific transcoding

### ISSUE THREAD

**Issue by renne** [gerbera/gerbera#188]
Hi,

I have a device limited to 16bit/48kHz audio. As transcoding any audio reduces quality and needs a lot of CPU power on the Gerbera host the transcoding should be limited to media sources which exceed the machine capabilities. So I suggest to add the following transcoding conditions based on the media source meta-data (e.g. ID-Tag) to Gerbera:

1. match a specific UPNP/DLNA renderer (IP address, MAC, HTTP User-agent) [Sourceforge discussion](https://sourceforge.net/p/mediatomb/discussion/440750/thread/a717cf1c/)
   `<transcode IP|MAC|user-agent ="..." using="..."/>`
2. match audio sampling-rate for downsampling to hardware capabilities
  `<transcode sampling-rate > xxxxxx using="..."/>`
3. match audio bit-width for downsampling to hardware capabilities
   `<transcode bit-width > 8|16|24 using="..."/>`

It should also be possible to concatenate conditions with logical operators, e.g.
   `<transcode user-agent ="..." && (sampling-rate > xxxxxx || bit-width > 8|16|24) using="..."/>`

**Comment by whyman** [comment]
@pamapa This one can built on top of the client tracking code too?

**Comment by jpalus** [comment]
Per client transcoding is something I'd be interested in as well. In my case I would like to expose Gerbera to a remote host over VPN so bandwidth would be limited, hence I would like to be able to transcode audio files to opus for this particular client. Hosts over LAN would still use FLAC though.
