### ISSUE TITLE
Gerbera Style for Gerbera UI

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#189]
The new Gerbera UI currently has bootstrap default style.  The application should reflect desired **Gerbera** style, similar to [gerbera.io](http://gerbera.io/) website.

Here are a bunch of changes I have in a local branch.

> Please provide any feedback on the style, and suggestions.  Honest critiques welcome.

### Gerbera Menu Bar
![menu-bar](https://user-images.githubusercontent.com/8599799/32983591-06e5ab8e-cc65-11e7-91c3-19ef631bad01.png)

#### Hover Menu Bar
![hover-menu](https://user-images.githubusercontent.com/8599799/32983605-3bd7824a-cc65-11e7-990d-f6bfb89a0acf.png)

### Gerbera Tree & Items
![tree-items-with-pages](https://user-images.githubusercontent.com/8599799/32983596-1b3bfdae-cc65-11e7-9292-16dd0d7f01b1.png)

### Gerbera Overlay
![overlay-modal](https://user-images.githubusercontent.com/8599799/32983600-27e81812-cc65-11e7-8268-e6fb81f12b16.png)

### Gerbera Toast Message Bar
![toast-message](https://user-images.githubusercontent.com/8599799/32983606-4a724056-cc65-11e7-911b-85a0b9ed82a4.png)

### Hover Trail Icons
![hover-trail-icons](https://user-images.githubusercontent.com/8599799/32983611-5638d54e-cc65-11e7-825b-ba8f3ad44918.png)

### Hover Item Icons
![hover-icons](https://user-images.githubusercontent.com/8599799/32983615-5f208292-cc65-11e7-854d-45cefe61a597.png)

**Comment by elmodaddyb** [comment]
All style changes are done and in forked branch.  I'll wait for any feedback and submit PR in the next few days.

**Comment by v00d00** [comment]
I like it, but would keep the white background.

**Comment by v00d00** [comment]
Closing as per #191
