### ISSUE TITLE
General Question about CMake & Testing

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#190]
Anyone out there have suggestions for C++ unit test structure?  I was able to get a simple C++ test working using Google Test.  The gerbera library dependencies seem expansive (obviously there are many), which probably means, the testing setup is **wrong**..or the project has a very flat architecture at this time.
```
/src/
/test/CMakeLists.txt        <---- includes sub-dirs of tests
/test/testonlineservices/   <---- each test is its own executable
```
Here is an example that imports a **libgerbera** and instantiates a `OnlineService`.

[https://gist.github.com/elmodaddyb/1e5aad8c21d47e7da21441b3486dd9b9](https://gist.github.com/elmodaddyb/1e5aad8c21d47e7da21441b3486dd9b9)

Any thoughts welcome... :1st_place_medal:

**Comment by elmodaddyb** [comment]
I made progress on testability with Gerbera C++ source.  Here are some findings.  Feedback from more experience C++ developers is welcome.

### 1. The `Singleton` classes are difficult to mock

Using overloaded constructors to dependency inject the singletons into the consumers seems to work OK, but I think may NOT be thread safe :rotating_light: 

```c++
ShoutcastService :: refreshServiceData() {
   Ref<ConfigManager> config = ConfigManager::getInstance();
   config....
}
```
versus
```
ShoutcastService::ShoutcastService(zmm::Ref<URL> serviceUrl, 
   zmm::Ref<ConfigManager> cfgManger) {
  url = serviceUrl;
  configManager = cfgManger;
}

ShoutcastService :: refreshServiceData() {
   configManager....
}
```

### 2. The majority of functions are `static` or **not** `virtual` so mocking is not possible.
Changing method signatures to `virtual` allows **GoogleMock** to replace functionality during tests.
**EXISTING**
```config_manager.h
zmm::Ref<zmm::Array<zmm::Object> > getObjectArrayOption(config_option_t option);
```
**MOCKABLE**
```config_manager.h
virtual zmm::Ref<zmm::Array<zmm::Object> > getObjectArrayOption(config_option_t option);
```

**Comment by v00d00** [comment]
Yeah, please don't add new Singletons if you can help it, I have been trying to remove them as I go, but we are getting on to the meatier ones now that take more of a rewrite!

I would just create your new class with a normal constructor, then create a single instance somewhere.

I'm not a fan of the make everything virtual approach. What I would do is pull the definitions into an interface and then create mocks from that.

**Comment by elmodaddyb** [comment]
@v00d00, those are great suggestions. I will work towards interfaces approach.

**Comment by elmodaddyb** [comment]
Closing for now. I will be adding the start of c++ tests for `libgerbera` in the near future. I will also add to Travis CI as a new stage!!
