### ISSUE TITLE
libupnp-1.8.3/4 is not supported

### ISSUE THREAD

**Issue by MrDini123** [gerbera/gerbera#192]
Hi,

When I am trying to compile gerbera v1.1.0 with the latest libupnp, I get this error:

```
[ 49%] Building CXX object CMakeFiles/libgerbera.dir/src/server.cc.o
/i-data/bf835951/build/gerbera/src/server.cc: In member function 'void Server::upnp_init()':
/i-data/bf835951/build/gerbera/src/server.cc:170:54: error: too few arguments to function 'int UpnpAddVirtualDir(const char*, const void*, const void**)'
     ret = UpnpAddVirtualDir(virtual_directory.c_str());
                                                      ^
In file included from /i-data/bf835951/build/gerbera/src/io_handler.h:35:0,
                 from /i-data/bf835951/build/gerbera/src/tools.h:41,
                 from /i-data/bf835951/build/gerbera/src/timer.h:36,
                 from /i-data/bf835951/build/gerbera/src/autoscan.h:36,
                 from /i-data/bf835951/build/gerbera/src/storage.h:42,
                 from /i-data/bf835951/build/gerbera/src/content_manager.h:41,
                 from /i-data/bf835951/build/gerbera/src/server.cc:40:
/usr/local/zy-pkgs/ffproot/ffp/include/upnp/upnp.h:2741:17: note: declared here
 EXPORT_SPEC int UpnpAddVirtualDir(
                 ^
CMakeFiles/libgerbera.dir/build.make:1550: recipe for target 'CMakeFiles/libgerbera.dir/src/server.cc.o' failed
make[2]: *** [CMakeFiles/libgerbera.dir/src/server.cc.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/libgerbera.dir/all' failed
make[1]: *** [CMakeFiles/libgerbera.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

What Can I do?

Thanks.

**Comment by MrDini123** [comment]
Ah, I see now clearly. The pupnp source has been changed, and this cause the few args error. https://github.com/mrjimenez/pupnp/issues/57

After realised that, I wondered what if I pass two NULL values as cookies. It compiled successfully, but I got another error later which is also related with the libupnp 1.8.3.

I am now trying to compile the 1.8.2 (btw that wasn't so easy, because this zip was removed from sourceforge. I had to use git checkout to get the sources). It should work now.

Would you mind updating the source in order to work with the latest libupnp API?

Thanks a lot.

**Comment by v00d00** [comment]
Updating to support 1.8.4 is on my todo, but time is lacking. Should be an easy patch, though.

**Comment by MrDini123** [comment]
Okay, thanks.

May I ask you another question? It is completely off, but I don't think it is worse a new bug report, because actually it isn't a bug. It is an embedded device which has uClibc C library. And in uClibc, the UTF-8 and locale support is experimental, and by default the uClibc is built without locale support. I have a separate libiconv package installed, so I could compile the gerbera, but while scanning, the non english special characters, like é becomes a question mark, and after the question mark the title is splitted.

However, I have an uClibc which has locale support, but I don't want to use it in production. But during the compile, I Can use that version, and I want to link the libc statically.

I didn't find any cmake option in the gerbera source, So how Can I do that? Sorry, I am not familiar with cmake...

And one more thing. I have a lot of wav file, and on scanning I Can see a lot of taglib error (pcm not supported). Gerbera is retrying to scan that, or I just have a lot of wav, and that cause the flood in the log?

**Comment by v00d00** [comment]
I would recommend to open new issues for those. Check you have set the varoius encodings in the config file and iconv should work as expected.

Not sure about the wav one, in theory wav can have metadata, so we need to scan it, but perhaps our error handling needs improvement if its not present.

**Comment by MrDini123** [comment]
Wohooo. :)

The charset error is solved now. You were right. I had to specify that inside the config file. Thanks.

**Comment by elmodaddyb** [comment]
I was able to get latest `libupnp` and latest `gerbera` running on **macOS  High Sierra(10.13.1)** with the needful cookie changes....Also found that macOS High Sierra changed the various `/include/` paths....so CMakeCache reset is required...

**Comment by MrDini123** [comment]
@elmodaddyb How? With untouched sources?

I am using gerbera 1.1.0, but I Cannot compile it with the latest stable (1.8.3) libupnp. The cache is empty BTW.

And it is a Linux system.

**Comment by elmodaddyb** [comment]
I did as you mentioned, set the cookies to NULL.  Also had to update the **web_callbacks** signatures to pass the const * void cookie.

**Comment by MrDini123** [comment]
@elmodaddyb Yes, I also managed to work that way. But I opened the ticket, because the latest release isn't works with the latest libupnp without manual editing.

**Comment by elmodaddyb** [comment]
@v00d00 - I have a simple patch that makes the new `libupnp` cookie signature work within Gerbera master.  It doesnt really handle the cookies in any way, just **NULL** them on the calls.

Shall I submit for review...or is there something better on the horizon?

**Comment by v00d00** [comment]
The issue with that is that you will then break the older version <=1.8.2.

You could add a CMake check and a define and some ifdefs to avoid it, which was my short-term plan.

**Comment by elmodaddyb** [comment]
Yea, that makes total sense, forgot about that. #IFDEF’s around all those callbacks won’t be elegant, but would work.

**Comment by v00d00** [comment]
Whoops, misclicked :-1:

**Comment by ozmartian** [comment]
hey guys...i've patched the gerbera Arch Linux AUR package with the NULL cookie workaround mentioned here already + callbacks update + renaming the pupnp dependency to libupnp-git as its currently incorrectly named and pointing to the stable older version rather than latest upstream... all appears to be working so thought i'd share it here and post a comment on the AUR package page for any people out there wanting to get this installed right now...

attached is the final built package which needs libupnp-git installed from AUR... had to ZIP the tar.xz package archive so just unzip the attached file first and then install it:

[gerbera-1.1.0-1-x86_64.zip](https://github.com/gerbera/gerbera/files/1564681/gerbera-1.1.0-1-x86_64.zip)

```
$ unzip gerbera-1.1.0-1-x86_64.zip
$ sudo pacman -U gerbera-1.1.0-1-x86_64.pkg.tar.xz
```
