### ISSUE TITLE
FFmpegthumbnailer not works

### ISSUE THREAD

**Issue by MrDini123** [gerbera/gerbera#193]
Hi again,

Now I wanted to enable the FFmpegthumbnailer funcionality in the config file, like this:

```
      <ffmpegthumbnailer enabled="yes">
        <thumbnail-size>128</thumbnail-size>
        <seek-percentage>10</seek-percentage>
        <filmstrip-overlay>yes</filmstrip-overlay>
        <workaround-bugs>no</workaround-bugs>
        <image-quality>8</image-quality>
      </ffmpegthumbnailer>
```

But it doesn't seems to do anything.

In turn, I compiled an FFmpeg 3.4 and FFmpegthumbnailer 2.2.0 just for this purpose (to use with gerbera). :)

Is there a way to see all the available config options with "what these actually does" comments/documentations?

Here is my gerbera binary's ldd output:

```
	libpthread.so.0 => /ffp/lib/libpthread.so.0 (0x4001a000)
	libiconv.so.2 => /ffp/lib/libiconv.so.2 (0x40035000)
	libuuid.so.1 => /ffp/lib/libuuid.so.1 (0x4011c000)
	libupnp.so.10 => /ffp/lib/libupnp.so.10 (0x40127000)
	libixml.so.10 => /ffp/lib/libixml.so.10 (0x40156000)
	libexpat.so.1 => /ffp/lib/libexpat.so.1 (0x40166000)
	libsqlite3.so.0 => /ffp/lib/libsqlite3.so.0 (0x4018e000)
	libduktape.so.202 => /ffp/lib/libduktape.so.202 (0x4023e000)
	libcurl.so.4 => /ffp/lib/libcurl.so.4 (0x40281000)
	libtag.so.1 => /ffp/lib/libtag.so.1 (0x402e9000)
	libmagic.so.1 => /ffp/lib/libmagic.so.1 (0x403c3000)
	libavcodec.so.57 => /ffp/lib/libavcodec.so.57 (0x403e7000)
	libavformat.so.57 => /ffp/lib/libavformat.so.57 (0x416de000)
	libavutil.so.55 => /ffp/lib/libavutil.so.55 (0x418d5000)
	libswscale.so.4 => /ffp/lib/libswscale.so.4 (0x41965000)
	libvorbis.so.0 => /ffp/lib/libvorbis.so.0 (0x419d9000)
	libvorbisenc.so.2 => /ffp/lib/libvorbisenc.so.2 (0x41a0c000)
	libtheora.so.0 => /ffp/lib/libtheora.so.0 (0x41b82000)
	libz.so.1 => /ffp/lib/libz.so.1 (0x41bcc000)
	libbz2.so.1.0 => /ffp/lib/libbz2.so.1.0 (0x41be8000)
	libffmpegthumbnailer.so.4 => /ffp/lib/libffmpegthumbnailer.so.4 (0x41c01000)
	libexif.so.12 => /ffp/lib/libexif.so.12 (0x41c1e000)
	libstdc++.so.6 => /ffp/lib/libstdc++.so.6 (0x41c58000)
	libm.so.0 => /ffp/lib/libm.so.0 (0x41d63000)
	libgcc_s.so.1 => /ffp/lib/libgcc_s.so.1 (0x41d7d000)
	libc.so.0 => /ffp/lib/libc.so.0 (0x41da4000)
	ld-uClibc.so.0 => /ffp/lib/ld-uClibc.so.0 (0x2a000000)
	libdl.so.0 => /ffp/lib/libdl.so.0 (0x41e1b000)
	librtmp.so.1 => /ffp/lib/librtmp.so.1 (0x41e26000)
	libssl.so.1.0.0 => /ffp/lib/libssl.so.1.0.0 (0x41e3f000)
	libcrypto.so.1.0.0 => /ffp/lib/libcrypto.so.1.0.0 (0x41ea3000)
	libboost_atomic.so.1.57.0 => /ffp/lib/libboost_atomic.so.1.57.0 (0x42024000)
	libswresample.so.2 => /ffp/lib/libswresample.so.2 (0x4202e000)
	libwebp.so.7 => /ffp/lib/libwebp.so.7 (0x4204d000)
	libx265.so.116 => /ffp/lib/libx265.so.116 (0x420a3000)
	libx264.so.148 => /ffp/lib/libx264.so.148 (0x421bb000)
	libwebpmux.so.3 => /ffp/lib/libwebpmux.so.3 (0x4231d000)
	libvpx.so.4 => /ffp/lib/libvpx.so.4 (0x4232d000)
	libtwolame.so.0 => /ffp/lib/libtwolame.so.0 (0x42473000)
	libtheoraenc.so.1 => /ffp/lib/libtheoraenc.so.1 (0x424a1000)
	libtheoradec.so.1 => /ffp/lib/libtheoradec.so.1 (0x424df000)
	libshine.so.3 => /ffp/lib/libshine.so.3 (0x424fa000)
	libopus.so.0 => /ffp/lib/libopus.so.0 (0x4250b000)
	libmp3lame.so.0 => /ffp/lib/libmp3lame.so.0 (0x42560000)
	liblzma.so.5 => /ffp/lib/liblzma.so.5 (0x425e8000)
	libgnutls.so.30 => /ffp/lib/libgnutls.so.30 (0x4260e000)
	libogg.so.0 => /ffp/lib/libogg.so.0 (0x4277f000)
	libavfilter.so.6 => /ffp/lib/libavfilter.so.6 (0x4278b000)
	libjpeg.so.8 => /ffp/lib/libjpeg.so.8 (0x429a7000)
	libpng16.so.16 => /ffp/lib/libpng16.so.16 (0x429ed000)
	librt.so.0 => /ffp/lib/librt.so.0 (0x42a1f000)
	libtasn1.so.6 => /ffp/lib/libtasn1.so.6 (0x42a2a000)
	libnettle.so.6 => /ffp/lib/libnettle.so.6 (0x42a42000)
	libhogweed.so.4 => /ffp/lib/libhogweed.so.4 (0x42a7b000)
	libgmp.so.10 => /ffp/lib/libgmp.so.10 (0x42aaf000)
	libintl.so.8 => /ffp/lib/libintl.so.8 (0x42b17000)
	libavresample.so.3 => /ffp/lib/libavresample.so.3 (0x42b27000)
	libpostproc.so.54 => /ffp/lib/libpostproc.so.54 (0x42b40000)
	libass.so.9 => /ffp/lib/libass.so.9 (0x42b51000)
	libfribidi.so.0 => /ffp/lib/libfribidi.so.0 (0x42b7f000)
	libglib-2.0.so.0 => /ffp/lib/libglib-2.0.so.0 (0x42b9e000)
	libpcre.so.1 => /ffp/lib/libpcre.so.1 (0x42cb0000)
	libfontconfig.so.1 => /ffp/lib/libfontconfig.so.1 (0x42cf7000)
	libfreetype.so.6 => /ffp/lib/libfreetype.so.6 (0x42d3f000)
```

BTW I took a look on the code, but something also don't clear for me. Where these images will be saved? In the directory of my media file? If yes, Can you please implement a function to save these thumbnails into a separate directory (like /var/cache/gerbera/thumbs/)?

**Comment by v00d00** [comment]
You can set the path in your config file under `/server/extended-runtime-options/ffmpegthumbnailer/cache-dir`, or home + `/cache-dir` if unset.

**Comment by MrDini123** [comment]
Thanks for the quick reply.

I have modified the config to this:

```
      <ffmpegthumbnailer enabled="yes">
        <cache-dir>/ffp/var/cache/gerbera</cache-dir>
        <thumbnail-size>128</thumbnail-size>
        <seek-percentage>10</seek-percentage>
        <filmstrip-overlay>yes</filmstrip-overlay>
        <workaround-bugs>no</workaround-bugs>
        <image-quality>8</image-quality>
      </ffmpegthumbnailer>
```

But unfortunately nothing changed. My /ffp/var/cache/gerbera folder is empty (I created it manually).

**Comment by v00d00** [comment]
Can you run it with --debug mode and post the log? You may need to reimport your files.

**Comment by MrDini123** [comment]
Of course. But I built gerbera without debug flag. Do I have to recompile?

**Comment by MrDini123** [comment]
The debug output revealed the following:

```
2017-11-23 16:59:18   DEBUG: [src/config_manager.cc:2191] getOption(): Config: option not found: /server/extended-runtime-options/ffmpegthumbnailer/cache-dir/attribute::enabled using default value: yes
      <ffmpegthumbnailer enabled="yes">
      </ffmpegthumbnailer>
```

But I Can't see any other errors related with ffmpegthumbnailer.

**Comment by elmodaddyb** [comment]
I remember in issue #123 we also had to have `<protocolInfo extend="yes"/>` for the proper data to be sent to client's to request the thumbnails.

**Comment by MrDini123** [comment]
@elmodaddyb I also saw that issue, but there is no thumbnail at all. I enabled the generation in the config, but the generation isn't works.

I Can see my music coverarts on the clients, just the generation lacks.

**Comment by MrDini123** [comment]
I also installed the latest Gerbera from source on my x64 desktop PC (Ubuntu 16.04 LTS), but it doesn't generate any thumbnails for me. I Can reproduce exactly the same thing with the PPA build also.

[Here](https://pastebin.com/ztXbuMCG) is the config that I am using now. And I have ffmpegthumbnailer 2.2.0 compiled from source also. What FFmpegthumbnailer do you have @v00d00 and @elmodaddyb?

**Comment by elmodaddyb** [comment]
@MrDini123 - I too am running `ffmpegthumbnailer 2.2.0`.  Here is some instruction on how to verify the thumbnail generation...

If you have access to the source code, you can enable the verbose output of the UPNP resources sent to the client.  There is a logging statement that outputs the UPNP compliant XML sent to the client.

https://github.com/gerbera/gerbera/blob/e47448a3e641b8a6e41dcbc0633d795cdfa947cf/src/upnp_xml.cc#L233

This should output the `<res>` resources that gerbera is generating, including the thumbnails.  Here is an example.  You can see it contains a resource URL reference to the thumbnail _file.jpg_.

```xml
<item id="11" parentID="10" restricted="1">
<dc:title>Movie.mp4</dc:title><upnp:class>object.item.videoItem</upnp:class>
<res protocolInfo="http-get:*:video/mp4:DLNA.ORG_OP=01;DLNA.ORG_CI=0" size="2877201018" bitrate="342475" duration="02:20:01.1" sampleFrequency="48000" nrAudioChannels="6" resolution="720x480">http://localhost:49152/content/media/object_id/11/res_id/0/ext/file.mp4</res>
<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=01;DLNA.ORG_CI=0" resolution="128x85">http://localhost:49152/content/media/object_id/11/res_id/1/rh/6/ext/file.jpg</res>
</item>
```

If you download the `JPEG` resource using **curl** you should see if gerbera is generating thumbnails properly.  If the server is a-OK...then likely it has something to do with the UPNP client, and how it processes the `protocolInfo` to re-request the image files from the server.

From my limited knowledge, I think `protocolInfo` may be device specific, e.g. works on PS3 but not on another client.  If i had to guess, we need to enhance the server to identify and send the proper protocolInfo to the device.

**Comment by MrDini123** [comment]
Wait. The thumbnails isn't generated during the scan time? Oh, that makes sense.

Will see and share the results, thanks for the wide explanation. :)

**Comment by MrDini123** [comment]
I have also enabled protocolInfo, but I am afraid nothing changed regarding the thumbnails. I Can see my music collection's albumarts through DLNA without any protocolInfo change, just the thumbnail generation lacks.

BTW, without any source recompile, I Could catch an XML sent to my client from the debugger log (the next idea would be WireShark packet sniffing), and I see there is an image file sent to the client. With curl, I Can see some random characters. I saved the url, but I got a corrupted JPG without any actual usable content. With a simple webbrowser, I get a download unsuccessful message. But the downloading starts if I visit this link.

And here is a log part, when I am trying to access a JPG:

```
2017-11-25 00:47:12   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/media/object_id/118507/res_id/1/rh/6/ext/file.jpg, Path: (null)
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:55] get_info(): start
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:71] get_info(): full url (filename): /content/media/object_id/118507/res_id/1/rh/6/ext/file.jpg, parameters: object_id/118507/res_id/1/rh/6/ext/file.jpg
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:140] get_info(): path:/tmp/big_buck_bunny.mkv
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:154] get_info(): fetching resource id 1
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:160] get_info(): setting content length to unknown
2017-11-25 00:47:12   DEBUG: [src/metadata/ffmpeg_handler.cc:392] serveContent(): Returning cached thumbnail for file: /tmp/big_buck_bunny.mkv
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:299] get_info(): web_get_info(): end
2017-11-25 00:47:12   DEBUG: [src/web_callbacks.cc:143] web_open(): web_open(): /content/media/object_id/118507/res_id/1/rh/6/ext/file.jpg
2017-11-25 00:47:12   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/media/object_id/118507/res_id/1/rh/6/ext/file.jpg, Path: (null)
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:312] open(): start
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:326] open(): full url (filename): /content/media/object_id/118507/res_id/1/rh/6/ext/file.jpg, parameters: object_id/118507/res_id/1/rh/6/ext/file.jpg
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:334] open(): Opening media file with object id 118507
2017-11-25 00:47:12   DEBUG: [src/file_request_handler.cc:470] open(): fetching resource id 1
2017-11-25 00:47:12   DEBUG: [src/metadata/ffmpeg_handler.cc:392] serveContent(): Returning cached thumbnail for file: /tmp/big_buck_bunny.mkv
```

**Comment by MrDini123** [comment]
I have to correct myself. Therefore, the download was successful, just mine Picture viewer app had cache problems, that's why I saw a corrupted file. With another program, or using my phone, I Can open the JPG. 

So it seems like, just the Kodi doesn't support thumbnails for movies. I have to figure out, why.

Thanks for all your help. That was a big user error, sorry about that.

**Comment by elmodaddyb** [comment]
Well, you may be right. It looks like Kodi is based on XBMC....and XBMC should support thumbnails. I wonder if the extended protocol info needs to send additional **DLNA.ORG_FLAGS=** for XBMC/kodi to pick it up right.

**Comment by asavah** [comment]
AFAIK Kodi does not support thumbnails over upnp.
Also Kodi's library and scrapers do not support upnp sources.

**Comment by MrDini123** [comment]
@elmodaddyb Definitely. It isn't an XBMC fork, it is the XBMC itself. Just had to be renamed due to copyright issues.

I Can see a lot of forum thread and an open bug tracker issue, so most likely the Kodi devs simply doesn't care about UPnP too much. That's fine, because there are a lots of alternatives from FTP to webDAV, CIFS etc. Just I Can't imagine why this feature isn't implemented now.

If you Can see some light at the end of the tunnel, it would be much appreciated. And please mention me, if you find a solution. But don't waste your time on that if you have better things to do. For me, the Kodi was just a testing environment. The real job of Gerbera will be smart TV content serving.

Thanks for all your efforts.

**Comment by elmodaddyb** [comment]
Yea @asavah - I can't seem to find any type of UPNP retrieval logic for thumbnails in the Kodi system.  Although it does look like they do try to retrieve **thumb**nails from other Kodi remotes... _if i read it right_

[https://github.com/xbmc/xbmc/blob/1270137b6f3fd2eac308b1f07c41e82f0892d67d/xbmc/video/VideoThumbLoader.cpp](https://github.com/xbmc/xbmc/blob/1270137b6f3fd2eac308b1f07c41e82f0892d67d/xbmc/video/VideoThumbLoader.cpp)

I was able to stream a movie over UPNP + Gerbera with Kodi...which does have a pretty cool UI...
