### ISSUE TITLE
Does not build on GNU/Hurd

### ISSUE THREAD

**Issue by jcowgill** [gerbera/gerbera#194]
Gerbera fails to build on Debian's hurd port:
```
CMake Error at CMakeLists.txt:314 (message):
  Gerbera was unable to deterimine the host OS.  Please report this.  Value
  of CMAKE_SYSTEM_NAME: GNU


-- Configuring incomplete, errors occurred!
```

Full log:
https://buildd.debian.org/status/fetch.php?pkg=gerbera&arch=hurd-i386&ver=1.1.0%2Bdfsg-2&stamp=1511312309&raw=0

I don't understand why there is a whitelist of system names in the `CMakeLists.txt` file. The value of the `HOST_OS`, `LINUX` and `DARWIN` variables are never used. Can the host os check be removed (with the exception of solaris and bsd which might need some magic)?

**Comment by v00d00** [comment]
I think we can make it less restrictive. It was previously used to look for inotify and such but its not needed now I dont think.
