### ISSUE TITLE
When scanning, 'red eyed skull' flashes on top left of web page

### ISSUE THREAD

**Issue by lyallp** [gerbera/gerbera#195]
Using gentoo build of 1.1.0-r1 on 64 bit amd64 (Intel) system.
I suspect during theming update, the display of the Red eyed skull, indicating server activity, was overlooked. The Red eyed skull is predominantly shown during library scans.

Maybe the central part of the flower could change colour? :)

As a side note, mediatomb used to listen on localhost, gerbera does not. Only a convenience thing. :)

**Comment by v00d00** [comment]
@elmodaddyb has been working on a whole new UI, a read only preview is in 1.1, on please try it by adding `/gerbera.html` to the normal path.

So hopefully we can just drop the old UI at some point over the next couple of releases.

On the side note: the old libupnp bundled by mediatomb used to bind to everything all the time even if you didn't ask for that, which was a bit bad (think public interfaces!). But I agree having the UI on localhost would be useful and will keep it in mind.

**Comment by elmodaddyb** [comment]
The latest master has the full CRUD UI. A snack bar now shows when:

1. A processing request is successfully submitted. 
2. When the UI receives long polling updates from the server.

**Comment by elmodaddyb** [comment]
I have these changes in a local branch, and will submit a PR following completion of PR #222 

![loading-icons](https://user-images.githubusercontent.com/8599799/34463673-83320d0c-ee31-11e7-9279-7f52c101be36.png)
