### ISSUE TITLE
Should not store UDN in config file.

### ISSUE THREAD

**Issue by v00d00** [gerbera/gerbera#196]
We currently generate and then write back a UDN if its not in the config which means we have to have write access to our config file, which is frowned upon.
See https://bugs.gentoo.org/632122

**Comment by elmodaddyb** [comment]
Yep, UDN generation should be easy enough to migrate to the `ConfigGenerator`

Happenstance, I used the UUID generation to generate a test folder for testing read/write of the config.xml when running unit tests!! 😖 

> I will include UDN in the PR, likely be ready this weekend.

**Comment by elmodaddyb** [comment]
@v00d00 - I plan to completely remove modification capability, which will include remove of...

`ConfigManager.h`
```c++
void save();
void save_text(zmm::String filename, zmm::String content);
void migrate();
void prepare_udn();
```
The `validate` method remains active.

> Do you agree?

**Comment by elmodaddyb** [comment]
All set...

https://github.com/elmodaddyb/gerbera/blob/config-generator/src/config/config_generator.cc#L416

**Comment by elmodaddyb** [comment]
@v00d00 - do you think this bug is solved, or is it pending a new gentoo build?

**Comment by v00d00** [comment]
In all honesty I thought this already closed!
