### ISSUE TITLE
Master v1.9.1-138-g744621f7 is buggy

### ISSUE THREAD

**Issue by bouwew** [gerbera/gerbera#1969]
It look like it starts up fine, no error when I check the status via `sudo systemctl status gerbera.service` but browsing some of the local web pages doesn't work, I see an `invalid session-id` error at the bottom of the page. Also, when I try to browse a list of movies on my LG OLED tv it says that the server has disconnected.
Playing audio on my speaker with chromecast, via the Hi-Fi Cast app, works.

Gerbera is running in a Proxmox 7 linux-container.

**Comment by KarlStraussberger** [comment]
The message `invalid session-id` orginates from the web page which was opened too long ago. This should not lead to isses. Can you run gerbera using `--debug` in the command line to get more messages.

**Comment by bouwew** [comment]
With `--debug` added, I see it start up and start scanning. After a while the scrolling stops with this:
![image](https://user-images.githubusercontent.com/11290930/134954775-d03a14eb-fcf2-4ba7-b0aa-c24e7690b3b7.png)

I've tried a few times, it's stops at a different file each time.

**Comment by KarlStraussberger** [comment]
Maybe, before updating your whole system you can try the PR.

**Comment by bouwew** [comment]
I've updated to Debian Bullseye and installed the branch with the PR.
Now I get a segmentation fault directly after issuing starting gerbera.

**Comment by KarlStraussberger** [comment]
Can you again share the `--debug` output, please.

**Comment by bouwew** [comment]
[log.txt](https://github.com/gerbera/gerbera/files/7249219/log.txt)
Here's the logfile.

**Comment by KarlStraussberger** [comment]
@bouwew The issue was closed automatically, but from the looks it should be fixed in your case as well.

**Comment by bouwew** [comment]
Confirmed, the latest master runs fine when started from the command-line. No segmentation-fault anymore.
