### ISSUE TITLE
Build on Raspberry Pi / openSuSE Leap fails

### ISSUE THREAD

**Issue by Richard-MQ** [gerbera/gerbera#197]
Build fails on Raspberry Pi 3, running openSuSE Leap. 
`uname -a` reports
`Linux linux.suse 4.4.92-18.36-default #1 SMP Tue Oct 24 15:20:18 UTC 2017 (3f3cfaa) aarch64 aarch64 aarch64 GNU/Linux`

I'm following the build guide (admittedly, it says it's for freeBSD) at https://github.com/gerbera/gerbera#differences-to-mediatomb-so-far. I think I have all relevant packages installed, the steps

`git clone https://github.com/v00d00/gerbera.git` 
`mkdir build`
`cd build`
`sh ../gerbera/scripts/install-pupnp18.sh`
`sh ../gerbera/scripts/install-duktape.sh`
`cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=0` 
all seem to be fine, but 
`make -j4`
fails. More precisely I see a lot of warnings building taglib_handler:
`Building CXX object CMakeFiles/libgerbera.dir/src/metadata/taglib_handler.cc.o`
`/home/rpm/gerbera/src/metadata/ffmpeg_handler.cc: In function ‘void addFfmpegResourceFields(zmm::Ref<CdsItem>, AVFormatContext*, int*, int*)’:`
`/home/rpm/gerbera/src/metadata/ffmpeg_handler.cc:73:27: warning: ‘AVStream::codec’ is deprecated (declared at /usr/include/ffmpeg/libavformat/avformat.h:893) [-Wdeprecated-declarations]`
but the build continues anyway until it gets to "tools" where it hits an error:
```/home/rpm/gerbera/src/timer.cc: In member function ‘void Timer::removeTimerSubscriber(Timer::Subscriber*, zmm::Ref<Timer::Parameter>, bool)’:
/home/rpm/gerbera/src/timer.cc:89:29: error: no matching function for call to ‘std::list<Timer::TimerSubscriberElement>::erase(std::_List_const_iterator<Timer::TimerSubscriberElement>&)’
         subscribers.erase(it);
                             ^
```
Am I just unlucky with the state of the codebase at the moment or does anyone else see anything similar? I'm not much of a programmer but fairly used to building from source like this, however I am new to gerbera though a long-time user of Mediatomb.

Alternatively, has anyone successfully built gerbera for an RPM-based Raspi distro? 

Many thanks
Richard

**Comment by elmodaddyb** [comment]
@Richard-MQ the last issue with similar result was related to incorrect GCC version

Check issue #165 

I also encountered similar issue in **macOS** due to non matching clang tool chains.

**Comment by v00d00** [comment]
We do set that we need a C++14 compiler in the CMake, but it doesn't seem to complain...

This has happened a couple of times now, so its worth investigating giving a nice message.

GCC >=5 or clang should be fine.

**Comment by v00d00** [comment]
So, [the docs on CMake's CXX_STANDARD](https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html) say that it decays to older versions if the target isn't available, which makes it pretty useless. We will have to come up with some other solution.

**Comment by elmodaddyb** [comment]
Maybe we could use

**CMAKE_<LANG>_COMPILER_VERSION**

**Comment by Richard-MQ** [comment]
Indeed this does look like the same issue as [#165](https://github.com/gerbera/gerbera/issues/165)

```
$ cmake --version
cmake version 3.5.2
$ gcc --version
gcc (SUSE Linux) 4.8.5
```
I see if I can find a newer version of either, especially gcc - but openSuSE raspi is not a very well supported platform...

Thanks all
Richard

**Comment by Richard-MQ** [comment]
I was unduly pessimistic - I now have 
```
$ gcc --version
gcc (SUSE Linux) 6.2.1 20160826 [gcc-6-branch revision 239773]
```
and simply
`sudo ln -s /usr/bin/gcc-6 /usr/bin/gcc`
to use it in place of gcc 4.8

I did a `make clean; make -j4` and now tools.cc compiles but it fails on transcode_dispatcher.cc with much the same error as before:

```
[ 66%] Building CXX object CMakeFiles/libgerbera.dir/src/timer.cc.o
[ 67%] Building CXX object CMakeFiles/libgerbera.dir/src/tools.cc.o
[ 68%] Building CXX object CMakeFiles/libgerbera.dir/src/transcoding/transcode_dispatcher.cc.o
/home/rpm/gerbera/src/timer.cc: In member function ‘void Timer::removeTimerSubscriber(Timer::Subscriber*, zmm::Ref<Timer::Parameter>, bool)’:
/home/rpm/gerbera/src/timer.cc:89:29: error: no matching function for call to ‘std::list<Timer::TimerSubscriberElement>::erase(std::_List_const_iterator<Timer::TimerSubscriberElement>&)’
         subscribers.erase(it);
                             ^
```
Any further pointers gratefully received.

**Comment by elmodaddyb** [comment]
When I did a centos docker I set all the binaries
```
##--------------------------------------
## Override GCC versions - not ideal
##--------------------------------------
RUN ln -sf /opt/rh/devtoolset-6/root/usr/bin/g++ /usr/bin/c++
RUN ln -sf /opt/rh/devtoolset-6/root/usr/bin/g++ /usr/bin/g++
RUN ln -sf /opt/rh/devtoolset-6/root/usr/bin/gcc /usr/bin/gcc
RUN gcc --version
```

Probably overkill, but it worked. Are you sure all your GCC stuff is latest?

**Comment by Richard-MQ** [comment]
Hmm, yes, these were indeed wrong, fixed.
```
sudo rm /usr/bin/g++; sudo ln -s /usr/bin/g++-6   /usr/bin/g++
sudo rm /usr/bin/c++; sudo ln -s /usr/bin/g++-6   /usr/bin/c++
```
Also spotted in cmake output that it was using gcc 4.85, not sure why. I found a post that offered a fix by adding 

```
set(CMAKE_C_COMPILER /usr/bin/gcc-6)
set(CMAKE_CXX_COMPILER /usr/bin/g++-6)
```
to ~/gerbera/CMakeLists.txt

Now the build runs through to the linker stage before failing
```
[ 99%] Linking CXX executable gerbera
CMakeFiles/libgerbera.dir/src/action_request.cc.o: In function `ActionRequest::ActionRequest(s_UpnpActionRequest*)':
action_request.cc:(.text+0x50): undefined reference to `UpnpActionRequest_get_ActionName_cstr'
action_request.cc:(.text+0x6c): undefined reference to `UpnpActionRequest_get_DevUDN_cstr'
action_request.cc:(.text+0x88): undefined reference to `UpnpActionRequest_get_ServiceID_cstr'
action_request.cc:(.text+0xbc): undefined reference to `UpnpActionRequest_get_ActionRequest'
...
```

PS
> Maybe try purging the cmake build folder??

I don't know how to do this?

Thanks again for any help!
Richard

**Comment by Richard-MQ** [comment]
The above edit doesn't make it very clear, but I have just realised that I have openSuSE libupnp6 (with devel files) version **1.6.21** but I just saw that **v1.8** is the minimum required. I'll see where I can get that from!

**Comment by elmodaddyb** [comment]
You beat me to it...that’s looks like libupnp issue :)

There is a script to install the libupnp version required. Check out the `/scripts` directory.

**Comment by Richard-MQ** [comment]
I had already run h ../gerbera/scripts/install-pupnp18.sh successfully, though I also have the standard opensuse version installed - looks like it is finding this latter. No more time tonight but will try again tomorrow without version 1.6.21 and see if it helps...

Thanks again
Richard

**Comment by Richard-MQ** [comment]
Hurrah! Build completed. Now I need to test it.
But first, I will summarise the issues when building on openSuSE 42.2 / raspi:

1. gcc version - OSL42.2 comes with 4.85 which is too old. 
    Installing v6 is easy enough but needed linking to /usr/lib/gcc (also c++, g++) 

2. cmake header file needs a tweak if gcc 4.85 is still installed as it will use that by default. 
    So add the following at the head of ~/gerbera/CMakeLists.txt:
```
set(CMAKE_C_COMPILER /usr/bin/gcc-6)
set(CMAKE_CXX_COMPILER /usr/bin/g++-6)
```

3. libupnp - OSL42.2 comes with 1.6.21 which is too old. 
    Make sure it is not installed as co-existence is tricky.
    run ~/gerbera/scripts//install-pupnp18.sh (after uninstalling 1.6.21 if applicable)

4. Only then run cmake. I didn't have (or need) ffmpegthumbnailer or last.fm support, so used options
`-DWITH_FFMPEGTHUMBNAILER=0  -DWITH_LASTFM=0`

I hope this might help others with similar platforms.
Thanks to all who help me get there!
Richard

**Comment by elmodaddyb** [comment]
I will try and write some CMake logic since this issue has happened a few times. 

1. Check for minimum version of GCC 
2. Check for minimum version of libupnp
