### ISSUE TITLE
Browser tab still shows Mediatomb title

### ISSUE THREAD

**Issue by lyallp** [gerbera/gerbera#198]
Low priority since I know a new UI is on the way, but just so it's noted somewhere.
Using Firefox 52.4 tabs on Gentoo Linux Intel 64 bit with gerbera 1.1.0
The tab/page title is still Mediatomb.

And, I am sorry, I have real problems remembering the name Gerbera, I keep thinking of [Gerbils](https://en.wikipedia.org/wiki/Gerbil). I miss Mediatomb. :)

**Comment by v00d00** [comment]
I'm sure Gerbera will _grow_ on you. :laughing:

**Comment by lyallp** [comment]
I blooming hope so... :) I will leaf it alone now.
