### ISSUE TITLE
Client chokes on <?xml..?> header in browse response and shows empty tree

### ISSUE THREAD

**Issue by heischro** [gerbera/gerbera#1987]
I have one client (a Dual internet radio) that reports an empty content tree for my gerbera server.
After checking the differences between the gerbera browse response and the response of servers that work with the client, I found none of the other servers sends a `<?xml..?>` header in the result part of the browse response.

And indeed, after commenting out the two places in upn_cds.cc where pugi::node_declaration is prepended to the DIDL-Lite response the client works as expected.

Even if this is most probably a client bug:
As other UPNP servers do not add this declaration, I'd like to propose to either drop it completely or make it configurable.

**Comment by whyman** [comment]
We have a "quirks" mechanism that would be a good fit for this. What's the device user agent?

**Comment by KarlStraussberger** [comment]
Sounds like a client issue, so we should go for an option and add your device to the supported list. Alternatively we could autodetect your client by useragent and add it to quirks.

**Comment by KarlStraussberger** [comment]
Anyway, thanks for reporting and digging in.

**Comment by heischro** [comment]
Yes, I thinks it's a client issue, too. Even if the xml-header is not obligatory, it should at least accept it.

I just checked the HTTP header again:
The device sends the User-Agent "EC-IRADIO/1.0" in the GET request for the description.xml.
However, it does not send a User-Agent in the POST request, so I'm not sure if matching by User-Agent will work

Anyway, a quirk flag would be fine. One could always add a device override by IP address in the config.
(I thought about this myself, but I didn't have the time to dig into the code deep enough to find the right places to add it...)

BTW: The device is called "Dual CR 510".

**Comment by KarlStraussberger** [comment]
You can check the clients page in the web ui for the userAgent.

**Comment by heischro** [comment]
Yes, the field is empty in the web UI. That's why I checked the HTTP headers.

**Comment by KarlStraussberger** [comment]
We can still go for the tweaks then, but you would have to set the client flag by IP.

**Comment by KarlStraussberger** [comment]
The PR is ready for you to test.

**Comment by heischro** [comment]
FYI: Works as expected. (Flag has to be set by IP.)
Thanks for implementing it so quickly.
