### ISSUE TITLE
Multi-value metadata changes break existing import scripts

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#1988]
More of an FYI for anyone else who experiences this. The changes introduced in #1958 break existing import scripts as the old "meta" property of containers is no longer processed in `dukObject2cdsObject`. Custom import scripts must migrate to the new multi-valued "metaData" property.

**Comment by KarlStraussberger** [comment]
Thank you. I forgot to mention it when writing the release notes. Add a sentence now.
