### ISSUE TITLE
Unexpected search results for music tracks due to matching underlying dc_title

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#1989]
Music track searches are performed against dc_title in the database. Since the dc_title for `object.item.audioItem.musicTrack` items are derived from the underlying filename, any term matching the (modified) filename is returned as a match.

This may be the intended but the results may be confusing to a user who uses the new `search-item-result` configuration option to only result `Title` instead of `Artist - Title`.

**Example:**
I have a collection of songs by an artist named "Hollerado". The filenames all take the form `Hollerado - XX - Track Title`. There is a track titled "Hollerado Land (By Sam)" in this collection. When searching for "holler" I would expect only the track titled "Hollerado Land (By Sam)" to match, but instead all tracks match.

I've confirmed this behavior on HiFi Cast and BubbleUPNP. As you can see, they both return all 12 tracks
![Current behavior](https://user-images.githubusercontent.com/6924622/135726606-98469250-ad43-4d17-8948-7df9dbc12a0e.png)

This is the behavior from MinimServer which I would instead expect.
![Desired behavior](https://user-images.githubusercontent.com/6924622/135726589-eab74d8a-7b1e-4796-a6b2-6fa473cfcb92.png)

Some possible solutions that come to mind.

-  Don't search against `dc_title` in the `mt_cds_object` table but instead search against the `dc:title` property in the `mt_metadata` table.
- Allow setting of the `dc_title` for non-virtual items.
- Expand the searchable flag option to non-container items. Virtual items (with desired `dc_title`) could be made searchable while the non-virtual root item is made non-searchable. This would also require adding the correct `upnp_class` to the virtual items (is that even possible?). This seems tangentially related to #1923 in the sense that the DB in inconsistent with it's handling of `upnp_class` for virtual and non-virtual items.

**Comment by KarlStraussberger** [comment]
Thank you! That's a valid point. I think searching in the metadata instead of the properties produces the expected result. Need to look into the containers (virtual and physical)

**Comment by mill1000** [comment]
Works like a charm.
