### ISSUE TITLE
Media are not playable on ARM after upgrade to 1.9.2

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#1993]
I've upgraded from 1.8.2 to 1.9.2 on Arch Linux ARM. I've removed old database and diligently moved my old config to the new config (based on the automatically generated config).

I'm seeing the following error messages in log. The TV just shows "Check your network connection" when trying to play a file.

> error: Exception during seek: [/home/user/.cache/pikaur/build/gerbera/src/gerbera-1.9.2/src/iohandler/file_io_handler.cc:88] seek Error: fseek failed

Transcoding has also stopped working, but the error message is different from transcoded files:

> error: Exception: [/home/user/.cache/pikaur/build/gerbera/src/gerbera-1.9.2/src/file_request_handler.cc:244] open Error: Invalid resource ID given

What could be the issue?

**Comment by kyak** [comment]
Frankly speaking, it broke in 1.9.1. But I was too busy to report/hoping the issue would fix itself in 1.9.2, but it didn't.

**Comment by KarlStraussberger** [comment]
Thank you for reporting, any time is fine.

Could you please provide a stacktrace of the fiest crash, the file_io_handler code there was not changed for ages.

Did you rebuild your database after updating? Resource handling did get some overhaul which may also affect transcoding.

**Comment by kyak** [comment]
> Could you please provide a stacktrace of the fiest crash, the file_io_handler code there was not changed for ages.

But gerbera doesn't crash at this point, there is only this error message in logs.

> Did you rebuild your database after updating? Resource handling did get some overhaul which may also affect transcoding.

I've completely removed the old database and it is recreated by gerbera.

**Comment by ectotropic** [comment]
Very quickly adding my own experience to this - exactly the same issue with transcoding on 1.9.2, but I'm on x84/ubuntu.

That is, opening _any_ file for transcoding results in nothing being served and one or more
> error: Exception: [/__w/gerbera/gerbera/src/file_request_handler.cc:244] open Error: Invalid resource ID given

entries in the log file.

Definitely used to work relatively recently, but couldn't say exactly which version was the last I used that did work (something in the last few months though). FWIW a delete and complete rebuild of the database didn't help.

If I get time I'll run with `--debug` and post my logs.

**Comment by whyman** [comment]
Thanks for confirming @ectotropic

**Comment by stinovlas** [comment]
I'm encountering this issue with gerbera 1.9.2 as well. If I understand correctly, this issue has been amended in master. Do you plan to realease a bugfix version sometimes soon or should I start discovering how to compile gerbera from scratch?

**Comment by KarlStraussberger** [comment]
We're still fighting some strange cases, but this should not take too long anymore.
