### ISSUE TITLE
Useless operation on copy of property

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#2033]
I found it in https://github.com/gerbera/gerbera/pull/982 in file src/config_setup.cc:1296
```cpp
entry->getAttributes()[MetadataHandler::getResAttrName(R_RESOLUTION)] = optValue;
```
where getAttribues() returns a copy which then gets altered and immediatly destroyed. I don't think this is intended. I did not look into the side-effects yet.

_Originally posted by @matthiasstraka in https://github.com/gerbera/gerbera/issues/2032#issuecomment-943432258_

**Comment by KarlStraussberger** [comment]
I'm already on it

**Comment by matthiasstraka** [comment]
Note to self: read updates before working on a fix :)

**Comment by KarlStraussberger** [comment]
No worries. Yours is a lot clearer than my single line.
