### ISSUE TITLE
Docker image with default args doesn't allow access to web UI

### ISSUE THREAD

**Issue by iandellarocca** [gerbera/gerbera#2036]
Hello!

I wanted to run gerbera using Windows, and I think the only way for me to do this is to use Docker. 
I did a docker pull, as per the instructions on the docker hub [page](https://hub.docker.com/r/gerbera/gerbera).
`docker pull gerbera/gerbera`

I then ran it with the arguments shown, also on the same docker hub page.
`docker run
    --name some-gerbera
    --network=host 
    -v /some/files:/content:ro 
     gerbera/gerbera:latest`

With only `/some/files` changed to a directory path on my PC. 
This appears to work correctly, showing the following output:

> 2021-10-14 20:00:07   info: Gerbera UPnP Server 1.9.2 - http://gerbera.io/
> 2021-10-14 20:00:07   info: Copyright 2016-2021 Gerbera Contributors.
> 2021-10-14 20:00:07   info: Gerbera is free software, covered by the GNU General Public License version 2
> 2021-10-14 20:00:07   info: Loading configuration from: /var/run/gerbera/config.xml
> 2021-10-14 20:00:07   info: Checking configuration...
> 2021-10-14 20:00:07   info: Configuration check succeeded.
> 2021-10-14 20:00:07 warning: Sqlite3 database seems to be corrupt or doesn't exist yet.
> 2021-10-14 20:00:07   info: No sqlite3 backup is available or backup is corrupt. Automatically creating new database file...
> 2021-10-14 20:00:07   info: database created successfully.
> 2021-10-14 20:00:07   info: Loading 0 configuration items from database
> 2021-10-14 20:00:07   info: Loading autoscan location: /content; recursive: true, last_modified: unset
> 2021-10-14 20:00:07   info: Initialising UPnP with interface: \<unset\>, port: 49494
> 2021-10-14 20:00:07   info: IPv4: Server bound to: 192.168.65.4:49494
> 2021-10-14 20:00:07   info: IPv6: Server bound to: fe80:0000:0000:0000:5c5a:54ff:fea5:79ce:49494
> 2021-10-14 20:00:07   info: IPv6 ULA/GLA: Server bound to: :49495
> 2021-10-14 20:00:07   info: The Web UI can be reached by following this link: http://192.168.65.4:49494/`

Following the http://192.168.65.4:49494/ link shown in the logging output resulted in no connection. I tried going to localhost:49494/ instead. This resulted in the same problem. 

The "\<unset\>" in the 12th logging output line raised concerns with me:
> 2021-10-14 20:00:07   info: Initialising UPnP with interface: \<unset\>, port: 49494

What do I need to change to make this work? 
Thanks in advance!

**Comment by KarlStraussberger** [comment]
The container's network is isolated. With `-p` you link the port from the container to the port of your PC. You may also need to map `udp 1900` for SSDP discovery.

Either the port was blocked by the Windows firewall or already in use by another service. Networking on Windows is nasty.

**Comment by whyman** [comment]
Docker on windows needs the explicit port mapping so it can set up the forwarding to the Linux VM that runs the containers.

Host network mode on windows binds to the VMs network which is not that helpful. Works as expected on a native Linux machine.

Please let is know if you have any troubles and thanks for using Gerbera!

**Comment by iandellarocca** [comment]
Thanks for your help! Looking forward to using Gerbera!
