### ISSUE TITLE
Transcoding fails

### ISSUE THREAD

**Issue by GitKalle** [gerbera/gerbera#2037]
FreeBSD: 12.2 (Jail)
Gerbera version: commit 2c41334
ffmpeg: 4.4_4,1
libnpupnp: 4.1.5

Hello, 

I play around some days with Gerbera to get transcoding working. The file to be transcoding is not visible at the Samsung TV (see gerbera_samsung.log) and on the Onkyo receiver (see gerbera_onkyo.log) the message "Access denied by server" occurs. Thats why I try to check the transcoding by open the URL.

First the transcoding doesn't start but with the fix of commit ce8533b25 transcoding starts.
The transcoding stops after less seconds, see gerbera_transcoding.log. I notice that the size of transfered file never increased. I use ffmpeg to open the URL and save as a file with

`sudo -u gerbera ffmpeg -y -i http://192.168.1.215:49152/content/media/object_id/74/res_id/none/pr_name/ogg2mp3/tr/1/ext/file.mp3 /home/gerbera/test.mp3`

To test the transcoding I followed the [Testing and Troubleshooting](https://docs.gerbera.io/en/stable/transcoding.html#testing-and-troubleshooting) from the Gerbera documentaion.

```
# Console 1 (see tr-test_console2.log)
mkfifo /tmp/tr-test
sudo -u gerbera ffmpeg -y -i /mnt/media/music/test/2-Carl_Orff-Carmina_Burana_-_O_Fortuna.opus -f mp3 /tmp/tr-test
```

```
# Console 2 (see tr-test_console2.log)
sudo -u gerbera ffmpeg -y -i /tmp/tr-test /home/gerbera/test.mp3
```

The file test.mp3 has the mimetype `audio/mpeg` and is playable as an audio file.

Can somebody help?

[gerbera_onkyo.log](https://github.com/gerbera/gerbera/files/7349250/gerbera_onkyo.log)
[gerbera_samsung.log](https://github.com/gerbera/gerbera/files/7349251/gerbera_samsung.log)
[gerbera_transcoding.log](https://github.com/gerbera/gerbera/files/7349252/gerbera_transcoding.log)
[tr-test_console1.log](https://github.com/gerbera/gerbera/files/7349253/tr-test_console1.log)
[tr-test_console2.log](https://github.com/gerbera/gerbera/files/7349254/tr-test_console2.log)

Edit 1:
With the transcoder agent `ogg123` and the corresponding configuration `<agent command="ogg123" arguments="-d wav -f %out %in"/>` BubbleUPnP and VLC play the transcoded .opus file.
The problem with Samsung TV and Onkyo receiver persists.

**Comment by whyman** [comment]
Did you resolve this?

Thanks for providing a detailed report!
