### ISSUE TITLE
Large MKV imports take a long time

### ISSUE THREAD

**Issue by ngosang** [gerbera/gerbera#2045]
I have been using Gerbera for some time and It's working very well for me. Thank you.

The issue I'm experiencing from the first day is the huge amount of time it takes to index the collection.
My collection is not that big ~4.8 TB and ~7000 media files. 
**It takes 7 hours to import and that happens after every restart!**

![image](https://user-images.githubusercontent.com/10577978/137564316-ad7e585d-3d15-44ed-bc61-dec10b5db655.png)
![image](https://user-images.githubusercontent.com/10577978/137564292-8ad5d5da-8422-442a-9042-a836c9d1109e.png)

Since Gerbera CPU usage is low and the disk read speed is low too (much slower than the disk speed) I don't know where the bottle neck is.
* I run Gerbera 1.9.2 in Docker in a Raspberry Pi 4. The storage is in a external RAID 1 connected with USB 3.0
* I have thumbnails disabled and inotify enabled.
* I'm using sqlite database, current size is just 13 MB for the complete collection. This database is in the RaspberryPi SD card which is slow. ~~I tried to enable transactions but the import speed is the same. **I'm pretty sure the issue is here, I see it takes some time to write the data in de DB if I enable debug logs.**~~

I have some questions:
* It's normal to take 7 hours in importing 7k files?
* Why is required to re-import after restart? NOTE: I'm not sure about this, I just see it sometimes. Maybe the database is corrupted due to bad shutdown.
* Can we speed up importing of already imported files just hashing the file or checking the modification date / size?
* ~~It will be faster if I use MySQL database instead of SQLite?~~
* Do you have any configuration or recommendation to improve my Gerbera?

**UPDATE**: After testing with MYSQL storage I'm not sure about sqlite anymore. It takes almost the same time. The issue I see is the following. The music is imported pretty fast, several songs per second. But, I have a folder with MKV movies (each movie is around 10 GB). It takes 20-30s to import each movie and 5 -10s for TV shows. If you do the math it takes 7 hours indeed. **Are you reading the whole file or something like that?**

Thank you!

**Comment by whyman** [comment]
I can replicate this, will post back once I have had a chance to work out whats happening.

**Comment by whyman** [comment]
Quick update: it looks like our code finds and then skips every single `EbmlElement` in the file, it take some time to go through them all in multi-GB videos.

**Comment by ngosang** [comment]
@whyman @KarlStraussberger great improvement!
With the same collection it only takes 20 minutes (instead of 7 hours before the fix). That is acceptable for me.
![image](https://user-images.githubusercontent.com/10577978/141689586-0ec5629e-8406-422c-8c78-dd52386d8ec9.png)

**Comment by whyman** [comment]
@ngosang great, thanks for reporting and confirming the fix
