### ISSUE TITLE
Receiver reports "Access denied by Server"

### ISSUE THREAD

**Issue by GitKalle** [gerbera/gerbera#2053]
System:
- FreeBSD 12.2 Jail
- libnpupnp v4.1.5
- Gerbera commit 8824074

Hello,

if a "magic" file is in the the current list of the UPNP client then the receiver reports "Access denied by Server". When I remove this file from the database or change the virtuell folder to files without problems then all is fine. It doesn't matter whether the file is a mp3 or a file to transcode. There are no problems with BubbleUPnP (Android), VLC (Android, PC) or my Samsung TV.
The "magic" file has the same permissions and ownership as other files.

```sh
-rwxr-xr-x 1 root wheel 6157306 Oct 20 21:15 01 Kommt zusammen.mp3*
-rwxr-xr-x 1 root wheel 1456288 Oct 20 21:16 music_without_special_char.mp3*
```

To test this I create a folder "Test" with two .mp3 files.
1. music_without_special_char.mp3 - *this file makes the problem (The name is because in former time I thought there is a problem with special chars.)*
   - Artist: Test
2. 01 Kommt zusammen.mp3 - *no problems at all*
   - Artist: 2raumwohnung
   - Title: Kommt zusammen

I don' know what I can do further. Maybe somebody of you have an idea.

[debug.log](https://github.com/gerbera/gerbera/files/7387468/debug.log)

**Comment by whyman** [comment]
One thing that seems strange is that your "zusammen" file ends up with `sec:vcodec="mjpeg"`, which is weird for audio file!

Can you provide a log from import time with that file?

**Comment by KarlStraussberger** [comment]
It seems that your **magic** file uses/contains an album art _movie_ instead of just an image. That causes your receiver to bail out. Can you grab `mediainfo` output on that file, please?

**Comment by KarlStraussberger** [comment]
Funny thing. I get this on my audio files as well. It is set by ffmpeg. Which version do you link?

Still the size of the image may be interesting. Some clients break on images larger than 200x200.

**Comment by GitKalle** [comment]
I have not found the reason but a solution. Before I used [abcde](https://abcde.einval.com/wiki/FrontPage) to rip my CDs. Now  I switched to [Fre:ac](https://www.freac.org/) and the receiver can access the files provided by `gerbera`.

Thank you for your support.

**Comment by KarlStraussberger** [comment]
Thanks for reporting back. Looks that it was a client issue altogether.

**Comment by whyman** [comment]
@GitKalle if you are willing, please provide a file from each `abcde` and `Fre:ac` so we can see if we can identify the problem.

**Comment by GitKalle** [comment]
I don't think we should make much effort because it only affects the receiver.

**Comment by whyman** [comment]
True, but I like to know what causes these things 😄
