### ISSUE TITLE
Transcoding error: unable to create fifo

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#2090]
I'm using latest gerbera from git: v1.9.2-92-gf1b9d855

When trying to play transcoded content, I see the following error message and file doesn't play:

> debug: [transcode_ext_handler.cc:64] serveContent(): Start transcoding file: /path/to/file.avi
debug: [transcode_ext_handler.cc:123] makeFifo(): creating fifo:
error: [transcode_ext_handler.cc:126] makeFifo(): Failed to create fifo for the transcoding process!: No such file or directory
error: [server.cc:527] operator()(): [/build/src/transcoding/transcode_ext_handler.cc:127] makeFifo Error: Could not create fifo

For some reason, the `fifoName` here returns empty:

https://github.com/gerbera/gerbera/blob/f1b9d855cf1fd0626771bedd4038d126adedcfe2/src/transcoding/transcode_ext_handler.cc#L123

**Comment by whyman** [comment]
Thats interesting, I've only just changed this code and it works for me.

Can you try explicitly setting your tmp dir in your config? https://docs.gerbera.io/en/stable/config-server.html#tmpdir

It should default to `/tmp/` though...

**Comment by kyak** [comment]
> Thats interesting, I've only just changed this code and it works for me.
> 
> Can you try explicitly setting your tmp dir in your config? https://docs.gerbera.io/en/stable/config-server.html#tmpdir
> 
> It should default to `/tmp/` though...

I've set the `tmpdir` in config, but it didn't make any difference.

**Comment by whyman** [comment]
If you add a  `log_debug("tmpDir: {}", tmpDir.string());` to line 122 and rebuild do you see something printed?

```patch
diff --git a/src/transcoding/transcode_ext_handler.cc b/src/transcoding/transcode_ext_handler.cc
index 995df5e8..f62e9be6 100644
--- a/src/transcoding/transcode_ext_handler.cc
+++ b/src/transcoding/transcode_ext_handler.cc
@@ -119,6 +119,7 @@ std::unique_ptr<IOHandler> TranscodeExternalHandler::serveContent(std::shared_pt
 fs::path TranscodeExternalHandler::makeFifo()
 {
     fs::path tmpDir = config->getOption(CFG_SERVER_TMPDIR);
+    log_debug("{}", tmpDir.string());
     auto fifoPath = tmpDir / fmt::format("grb-tr-{}", generateRandomId());

     log_debug("Creating FIFO: {}", fifoPath.string());
```

**Comment by whyman** [comment]
Whats interesting now I look closer is that the master code says `Creating FIFO` but your log says `creating fifo:`

**Comment by kyak** [comment]
> Whats interesting now I look closer is that the master code says `Creating FIFO:` but your log says `creating fifo:`

Well, you just made this change! I was still on f1b9d855 from 5 hours ago :)

I'll try with the latest master now.

**Comment by whyman** [comment]
Oh apologies, I thought you were my recently changed version already!

**Comment by kyak** [comment]
Works fine on 581e0ec0, thank you!
