### ISSUE TITLE
Manpage and builtin help show a different set of command line options.

### ISSUE THREAD

**Issue by felixbecker2** [gerbera/gerbera#2123]
The manpage (`man 1 gerbera`) mentions only the following command line options:

`-i -e -p -c -m -f -a -l -D --compile-info --version -h`,

While `gerbera -h` mentions the following (which are more):

`-D -d -u -P -e -p -i -c -m -f -l --compile-info -v -h --create-config --add-file`.

**Comment by KarlStraussberger** [comment]
The man page was last changed ages ago. Now, we need somebody who reflects the current situation in `docs/gerbera.1`
