### ISSUE TITLE
Documentation for the first time run

### ISSUE THREAD

**Issue by asbruff** [gerbera/gerbera#213]
Hi, i don't know if this is the right place to write my complain.

As far as i see there is no documentation online (poor documentation?) to explain a first time run of Gerbera. Also the location of the config files are different from mediatomb (eg. the config.xml file is not in /etc/gerbera, no user directories are created in the home).

I've already set up a machine with gerbera, spending hours to configure it, but now it works great. The web interface is very easy and i'm happy with it. I'm trying now to configure a new machine with it, but with no luck.

Maybe i'm just dumb , and i can't find the existing documentation, but i've look almost everywhere.

Also I would be happy to contribute to the project translating the site and the documentation in italian (if there's a need to).

**Comment by elmodaddyb** [comment]
@asbruff - There is definitely some knowledge acquisition needed in Gerbera compilation and runtime.

I am working on the new UI documentation, to go on the gerbera.io website.

I see a number of projects **auto-generating** documentation at build/publish time.  I really like this idea, so going to look into that a bit.

Have you had experience with good documentation generation tools? (Doxygen?)

**Comment by asbruff** [comment]
no, i've never had any experience with that.. but i'm also not a programmer. I might contribute spreading the word on my blog, or even translating (i experienced transifex).
I think Gerbera would be a good software even for non advanced users when installed and working, but at the momento it's tricky to set up.

**Comment by v00d00** [comment]
I am thinking that we need some type of site generator for https://gerbera.io.

Undecided which one as yet though, ideally something in python as its easy to extend and with markdown as the documentation language.

**Comment by Adirelle** [comment]
https://readthedocs.org ? It is OSS, supports Markdown, webhooks, multi-version docs, is written in Python, and offers hosting (eventually on alternate domains)

**Comment by elmodaddyb** [comment]
Here's a good article:
https://www.fullstackpython.com/static-site-generator.html

Pelican seems to be a legit python based site generator.
http://docs.getpelican.com/en/stable/

**Comment by v00d00** [comment]
Ive set up [docs.gerbera.io](docs.gerbera.io) to point at readthedocs.

I will look at putting together some rst documentation in /doc

**Comment by kewball** [comment]
Might want to add a link to docs.gerbera.io in Readme.md and/or gerbera.io

**Comment by v00d00** [comment]
The docs are pretty bad at the moment, a lot of the setup information is no longer applies.

Once we have cleaned it up a bit we will make the link nice and obvious.

**Comment by chintal** [comment]
In my experience something like sphinx is probably the best bet. Doxygen is good, but tends to be hard to coax into a non-C-documenting structure. I'll be happy to help with that if you like.
