### ISSUE TITLE
No repository for Ubuntu 21.10 Impish Indri

### ISSUE THREAD

**Issue by jonathanrwatts** [gerbera/gerbera#2133]
Just upgraded to (K)Ubuntu 21.10 Impish Indri, and of course there's no repository.  I was able to compile from source using the same packages I used for 21.04 Hirsute Hippo (see #1509  ).

**Comment by whyman** [comment]
@jonathanrwatts Weve published for impish, if you feel like it, please test it and let us know (we dont run ubuntu)

**Comment by jonathanrwatts** [comment]
Yep, I can now update from the debian-git/impish repository.  Thanks!
