### ISSUE TITLE
Filesystem restriction ?

### ISSUE THREAD

**Issue by Adirelle** [gerbera/gerbera#214]
There are security implication to serving files from the filesystem as Gerbera does. Even if gerbera is limited by file permissions, I'd better be sure it wouldn't even show files to the user. Would it be possible to restrict Gerbera to a part of the filesystem (kinda like a chroot) ?

**Comment by v00d00** [comment]
You could just run it in a chroot?

**Comment by Adirelle** [comment]
Yes but it would yet need /etc/passwd, binaries, libraries, configuration, working directories, log files, which would all be visible. Maybe chroot was a bad example, it would be more like Apache's DocumentRoot.

**Comment by v00d00** [comment]
What about disabling the UI?

You can add folders via the config file if needed?

**Comment by cweiske** [comment]
The web interface (both old and new) makes it very easy to traverse the whole filesystem of the server. I also don't like that.

**Comment by elmodaddyb** [comment]
Perhaps few ways to accomplish filesystem security.

1. Add a `RootDirectory` to the **systemd** daemon that runs gerbera
```
[Service]
RootDirectory=/gerbera/runtime
```

2. Mark certain directories as inaccessible in **systemd**
```
[Service]
InaccessibleDirectories=/home
```

3. Create a `config.xml` solution where the `filesystem` view starts with the configured **tree**

> I think 1 is BEST, 2 is OK, and 3 is POOR.  

Third option leaves a gap whereby the gerbera daemon has complete access to protected directories within the code.

**Comment by elmodaddyb** [comment]
Could also run Gerbera as a Docker container and use volumes to protect it.

**Comment by cweiske** [comment]
Option 3 is the one that can be implemented in gerbera correctly, as apache and other daemons do it, too.
All others depend on a certain init daemon.

**Comment by elmodaddyb** [comment]
Yea, I suppose that's the true systematic way to solve it.  The code has a lot of defaulting back to the **root** directory when `parentId` is not defined.

The system could support a **single** `<MediaRoot>` property in config.xml without too much trouble.  Once you get into multiple roots, then likely a DB configurable solution would be best.

**Comment by pamapa** [comment]
With the commit https://github.com/gerbera/gerbera/commit/b99a548c15c31c27fc27c3ba1db45b60fbc42c53 a lot of system directories are no longer allowed to browse/add
