### ISSUE TITLE
m3u playlists driving me crazy

### ISSUE THREAD

**Issue by ckris1** [gerbera/gerbera#2144]
I've mentioned this some time ago in an issue I've opened for slow MySQL performance.
Back then it was just a "mild issue" but now it I'm so frustrated that I'm close to give up gerbera :-(

I'm using a shell script (running on Linux here) which every night scans my complete music library, then creates a randomized m3u file holding 200 titles. Doing this, I can just run the playlist on some client and always have a new mix of music.
But gerbera just does not get it :-(

In theory, it should notice that the m3u file has changed, using Inotify. Works as expected.
But for whatever reason that playlist in gerbera then is not what it is supposed to be. It is some random mix of the current playlist file, the previous one or something in between.

Please, how can this be fixed? I want the previous playlist replaced with the current one. Happens once a day.
I wasn't able to get this to work.

Is there a way to simply delete the current playlist in the gerbera DB, then read the new one maybe? All this obviously in an automated way for my case. When I delete the playlist from the GUI, then create a new one, all seems to be fine.

Thanks!

**Comment by KarlStraussberger** [comment]
Did you already try to remove the file on the disk, wait for some secs and then recreate it as mentioned.

The dynamic folder feature does not - yet - support random.

**Comment by ckris1** [comment]
I have tried many combinations.

* Delete the file, wait for 5min, recreate it.
* Delete the file, wait for 5min, recreate it, "touch" it again.
* Stop gerbera, delete the file, create it, start gerbera
* "touch" the file, stop gerbera, start gerbera, "touch" again

Nothing solves the issue. The fun part is that Inotify correctly notices the file change, gerbera responds to that, but the contents of that playlist in the gerbera DB still is a mix of old an new.

Speaking of, there is add-file. But no counter part like remove file (or remove container).
Is there a specific reason for that? Having such a thing probably would fix my problem....

**Comment by KarlStraussberger** [comment]
This sound like a recipe to reproduce and then fix the issue. Don't get mad before this.

**Comment by ckris1** [comment]
I worked around it for now. I used to (re)create that playlist named 

000-All-Metal-short.m3u

every night. Instead of that, I now use this format

00`date +%d`-All-Metal-short.m3u

Since that is a "new" playlist, gerbera treats it as such and has no problem with displaying the right content.

BUT it's still not OK. Although I delete the old playlist every night gerbera does not notice that. The file is gone, but in the DB it still exists. Shouldn't the files get cleaned up (Inotify as mentioned before) and disappear from the DB?
My workaround will work for a month, then the names will get recycled and I'll be back to the original problem....

**Comment by tommyp-vr4** [comment]
Auto-creating random playlists is a really cool feature that I had asked about a few months back.  Can you share what you are doing?  Or maybe the gerbera folks can add a random playlist feature like this?

**Comment by whyman** [comment]
> though I delete the old playlist every night gerbera does not notice that. The file is gone, but in the DB it still exists. Shouldn't the files get cleaned up (Inotify as mentioned before) and disappear from the DB?

Yes, this should be the behaviour, something to investigate.

> Auto-creating random playlists is a really cool feature

A solution to this problem would be to add another extension to the [Dynamic Containers](https://docs.gerbera.io/en/stable/config-server.html?#containers) support to allow "N random entries" from the results of the query, or perhaps "random" sorting with a maximum limit to entries.

**Comment by KarlStraussberger** [comment]
Give me a week or so, I've got some ideas already

**Comment by ckris1** [comment]
> Auto-creating random playlists is a really cool feature that I had asked about a few months back. Can you share what you are doing? Or maybe the gerbera folks can add a random playlist feature like this?

sure, see my shell script below. It's quite simple.

My folder for all music is $MUSIC
The playlists are stored in $PLAYLIST

First I find all folders under $MUSIC, put them into a list. I exclude three of them.
Then walking through all those folders all mp3 and flac files are found and written into a playlist having the same name as that subfolder,

Next I create a playlist with all titles (never used, it's over 20000 titles)
Finally I take the first 200 entries of that list. Since the list is randomized, I get a new playlist with 200 titles every day.

All m3u files are generated every day (so I have to do nothing special when I add new music to $MUSIC, it just gets picked up on the next run). But I only update those m3u which actually have changed. Gerbera has the issues with that we're talking about here.

If you want to use the script below or parts of it, note that the parts with the grey background actually is embedded in backticks. 

-----



#!/usr/bin/bash

date
MUSIC="/LV1/music/"
PLAYLIST="/LV1/music/playlists"
TEMP="/tmp/pl"

mkdir $TEMP
rm -rf $MUSIC/playlists/00*
#sleep 60

cd $MUSIC
echo "finding all music.."

ls -1|egrep -v "playlists|__Non-Metal|__FLAC" > /tmp/musiclist.tmp
cd $PLAYLIST
OIFS="$IFS"
IFS=$'\n'
echo "creating new playlists"
for f in `cat /tmp/musiclist.tmp`;do
        find ../$f | egrep -i "mp3$|flac$" | sort > ${TEMP}/$f.m3u
done
IFS="$OIFS"
echo "creating superlist"
find ..| egrep -i "mp3$|flac$" | egrep -v "playlists|__Non-Metal|__FLAC"|/bin/sort -R > /tmp/stage.1
grep -v __Non-Metal /tmp/stage.1 > ${TEMP}/All-Metal.m3u
rm /tmp/stage.1
echo "making shortlist"
head -200 ${TEMP}/All-Metal.m3u > ${TEMP}/00`date +%d`-All-Metal-short.m3u
echo "all playlists created..."
echo "----------------------------------"

#to avoid issues with Gerbera, only those m3u files which actually have changed are updated.

cd $TEMP
for f in *m3u;do
        if [ -e "$PLAYLIST/$f" ];then
                OLDM3U=`md5sum "$PLAYLIST/$f"|cut -d" " -f1`
                NEWM3U=`md5sum "$f"|cut -d" " -f1`
                if [ $OLDM3U == $NEWM3U ];then
                        #echo "no changes for $f, will keep old file"
                        true
                else
                        echo "file $f has changed or was added, will copy it!"
                        cp "$f" $PLAYLIST
                fi
        else
                echo "file $f was added, will copy it!"
                cp "$f" $PLAYLIST
        fi
done

rm -rf $TEMP
#systemctl stop gerbera && sleep 62 && systemctl start gerbera
#sleep 300
#touch /LV1/music/playlists/*
echo "all done"
date

**Comment by ckris1** [comment]
sorry for the unformatted script, that's what github makes out of it when pasting into a message.

**Comment by KarlStraussberger** [comment]
> 
> 
> sorry for the unformatted script, that's what github makes out of it when pasting into a message.

I added some backticks. Improve layout!

**Comment by ckris1** [comment]
thanks you, how do I do that? I can't see any type of "code" or "vanilla" setting (guess I'm just an idiot again....)

**Comment by KarlStraussberger** [comment]
![Screenshot_20211112-173650.png](https://user-images.githubusercontent.com/23654788/141502056-e1a5641a-0987-45af-b1e7-a7688b74ab57.png)

**Comment by ckris1** [comment]
insert code........too obvious for me, as it seems ;-(

**Comment by KarlStraussberger** [comment]
Here it is.

You need to set `<playlist-script create-link="yes">` if not already done. If you have a custom playlist-import script you need to apply the change as well.

The functionality never really worked (or was crippled ages ago)

**Comment by KarlStraussberger** [comment]
You have to remove the old playlist manually otherwise the import does not work.

**Comment by ckris1** [comment]
will try, thanks.

Now, I'm not sure if it's related  -how about the "deleted but not disappearing"-playlists?
Is this a different issue?

**Comment by ckris1** [comment]
Ah, sorry, I thought this was about the playlist with the mix of old and new content when replacing a playlist with the same file name but different titles.

**Comment by KarlStraussberger** [comment]
It should be gone as well.

**Comment by ckris1** [comment]
v1.9.2-171-g2243be58 is the right version?

**Comment by KarlStraussberger** [comment]
yes

**Comment by ckris1** [comment]
okay. Installed, playlist deleted and imported. So far, so good. When creating a new playlist, it seems it is processed properly.

Buuuuut.....one more thing. I not sure if I've reported that before.
The playlist as seen in Gerbera mostly has the same order of files the m3u file has. But not completely.
Some songs are not where they should be but seem to get appended to the end of the playlist while it's processed.

So say the m3u is:

Song1
Song2
Song3
Song4
Song5

Then in gerbera it will be something like that:

Song1
Song2
Song4
Song5
Song3

Or similar in whatever way. As I've said, I have 200 songs in that list created every day, so there is quite a number of them affected. It's not important, the list is random'd anyway. Gerbera just makes it a bit different random.
I havn't figured out any pattern behind that, though.

**Comment by KarlStraussberger** [comment]
Is this still present? Might have been caused by the fact that playlists haven't been deleted.

**Comment by ckris1** [comment]
still present.
On last night's playlist created, 25 out of 200 titles are not at the expected slot.

In other words, the 200th title is on position 175 in Gerbera, 176-200 are random titles out of the list.
I see no pattern, they are "just titles", no fancy characters or whatever
