### ISSUE TITLE
Feature Request: Run script when connecting to media renderer

### ISSUE THREAD

**Issue by thomasschmiedl** [gerbera/gerbera#215]
I load some JPEG's from the internet to my Panasonic TV via Gerbera and the TV plays a background sound when the JPEG's are displayed. It's possible to deactivate this sound, but these setting will not saved permanently.

There's a remote control app for Panaonic-TV. Is it possible to run a script in Gerbera, when the TV enters/connects to Gerbera (in my case when pressed "Viera Tools" -> "Media Server")?

**Comment by v00d00** [comment]
I'm not sure this is something we can look at in the short to medium term. That said, if you do come up with a patch it will be welcome!
