### ISSUE TITLE
[Support] How to debug javascript?

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#2157]
Adding two files manually from the "file system" web interface screen with the "Add item" button does not work. I see the files themselves in the `mt_cds_object` mysql table, but no entries for them as virtual items.
They should get virtual items from my custom import script that worked since gerbera was called mediatomb, but they don't.

Now the question is how I could debug this.
My first idea was that maybe javascript is not compiled in, but it is:
```
$ gerbera --compile-info | grep JS
WITH_JS=YES
```

When running gerbera and clicking on "add item" in the web interface, nothing is logged when running without `-D`.
When running gerbera with debugging enabled (`-D`), I get some output:
```
debug: [server.cc:485] createRequestHandler(): Filename: /content/interface?req_type=add&object_id=2f7661722f73706f6f6c2f6d757369632f45696e7a656c6e65732f446172756465202d2053616e6473746f726d2e6d7033&GerberaSID=6d9e78c5-15e4-424f-9421-3685d552b90a
debug: [upnp_headers.cc:65] addHeader(): Adding header: 'Cache-Control: no-cache, must-revalidate'
debug: [upnp_headers.cc:65] addHeader(): Adding header: 'SameSite: Lax'
debug: [add.cc:44] process(): add: start
debug: [thread_runner.h:135] lockGuard(): ThreadRunner: Guard for ContentTaskThread - addTask
debug: [thread_runner.h:125] notify(): ThreadRunner: Notifying ContentTaskThread
debug: [add.cc:64] process(): add: returning
debug: [thread_runner.h:135] lockGuard(): ThreadRunner: Guard for ContentTaskThread - getCurrentTask
debug: [content_manager.cc:1810] run(): running add file task with path /var/spool/music/Einzelnes/Darude - Sandstorm.mp3 recursive: true
debug: [mysql_database.cc:288] select(): SELECT `f`.`id`, `f`.`ref_id`, `f`.`parent_id`, `f`.`object_type`, `f`.`upnp_class`, `f`.`dc_title`, `f`.`location`, `f`.`location_hash`, `f`.`auxdata`, `f`.`update_id`, `f`.`mime_type`, `f`.`flags`, `f`.`part_number`, `f`.`track_number`, `f`.`service_id`, `f`.`bookmark_pos`, `f`.`last_modified`, `f`.`last_updated`, `rf`.`upnp_class`, `rf`.`location`, `rf`.`auxdata`, `rf`.`mime_type`, `rf`.`service_id`, `as`.`persistent` FROM `mt_cds_object` `f` LEFT JOIN `mt_cds_object` `rf` ON `f`.`ref_id` = `rf`.`id` LEFT JOIN `mt_autoscan` `as` ON `as`.`obj_id` = `f`.`id`  WHERE `f`.`location_hash` = 647163951 AND `f`.`location` = 'F/var/spool/music/Einzelnes/Darude - Sandstorm.mp3' AND `f`.`ref_id` IS NULL LIMIT 1
debug: [web_request_handler.cc:183] open(): output-----------------------{"success":true,"task":{"id":1,"cancellable":true,"text":"Importing: /var/spool/music/Einzelnes/Darude - Sandstorm.mp3"}}
debug: [mysql_database.cc:288] select(): SELECT `item_id`, `property_name`, `property_value`  FROM `mt_metadata` WHERE `item_id` = 53942
debug: [sql_database.cc:2392] retrieveResourcesForObject(): SQLDatabase::retrieveResourcesForObject SELECT `item_id`, `res_id`, `handlerType`, `options`, `parameters`, `size`, `duration`, `bitrate`, `sampleFrequency`, `nrAudioChannels`, `resolution`, `colorDepth`, `protocolInfo`, `resFile`, `type`, `fanArtObject`, `fanArtResource`, `bitsPerSample`, `dc:language`, `sec:acodec`, `sec:vcodec`  FROM `grb_cds_resource` WHERE `item_id` = 53942 ORDER BY `res_id`
debug: [mysql_database.cc:288] select(): SELECT `item_id`, `res_id`, `handlerType`, `options`, `parameters`, `size`, `duration`, `bitrate`, `sampleFrequency`, `nrAudioChannels`, `resolution`, `colorDepth`, `protocolInfo`, `resFile`, `type`, `fanArtObject`, `fanArtResource`, `bitsPerSample`, `dc:language`, `sec:acodec`, `sec:vcodec`  FROM `grb_cds_resource` WHERE `item_id` = 53942 ORDER BY `res_id`
debug: [thread_runner.h:95] wait(): ThreadRunner: Waiting for ContentTaskThread
debug: [server.cc:485] createRequestHandler(): Filename: /content/interface?req_type=void&GerberaSID=6d9e78c5-15e4-424f-9421-3685d552b90a
debug: [upnp_headers.cc:65] addHeader(): Adding header: 'Cache-Control: no-cache, must-revalidate'
debug: [upnp_headers.cc:65] addHeader(): Adding header: 'SameSite: Lax'
debug: [thread_runner.h:135] lockGuard(): ThreadRunner: Guard for ContentTaskThread - getCurrentTask
debug: [web_request_handler.cc:183] open(): output-----------------------{"success":true}
```

But no item is actually added.

Then I added a "print("cweiske-import.js");" statement at the beginning of my import script, but that seemed to do nothing. The debug output in the log did not change.

----

So: What is the correct way to debug the javascript and get debugging messages?

(Version: Gerbera UPnP Server v1.9.2-144-ga0100cdd)

**Comment by whyman** [comment]
Hey @cweiske

Adding a print line should work as you expect. I just tested locally and get output similar to

`2021-11-12 08:48:49.829   info: [js_functions.cc:48] js_print(): cweiske-import.js`

I would check that JS is enabled in your config, and that the import script is pointing where you would expect.

```xml
<virtual-layout type="js">
  <import-script>/path/to/file...
```

The script is loaded at startup and reused so make sure you restart the daemon when you make changes.

**Comment by cweiske** [comment]
It is :(

When running with `-D` the following config is dumped into the log:
```
     <scripting script-charset="UTF-8">
       <common-script>/usr/local/share/gerbera/js/common.js</common-script>
       <playlist-script>/usr/local/share/gerbera/js/playlists.js</playlist-script>
       <virtual-layout type="js">
         <import-script>/etc/gerbera/import-cweiske.js</import-script>
       </virtual-layout>
     </scripting>
```

The path to the file is correct because when I intentionally break it, gerbera exits:
> error: [/usr/local/src/gerbera/src/config/config_setup.cc:226] resolvePath Error: File '/etc/gerbera/import-cweiske.js.doesnotexist' does not exist

The javascript file is ok because when I intentionally break it (syntax error), gerbera exits:
> error: Failed to load script: SyntaxError: parse error (line 4)
> error: ContentManager virtual container layout: [/usr/local/src/gerbera/src/content/scripting/script.cc:380] _load Error: Scripting: failed to compile /etc/gerbera/import-cweiske.js
> error: Activating ContentService failed [/usr/local/src/gerbera/src/content/scripting/script.cc:380] _load Error: Scripting: failed to compile /etc/gerbera/import-cweiske.js

**Comment by whyman** [comment]
That is indeed odd! The only thing I can think of is some issue with the common script, as that is loaded before the import script itself.

Are you using the default common script?
You may need to update it to match from master, or some recent git revision.

You can also try the same debugging steps on that file that you tried for the import js.

**Comment by KarlStraussberger** [comment]
We added a custom-script option which is loaded between common-script and import-script so you can accumulate all your changes there. Functions from custom-script overwrite functions from common-script.

**Comment by cweiske** [comment]
My full scripting config:
```
    <scripting script-charset="UTF-8">
      <common-script>/usr/local/share/gerbera/js/common.js</common-script>
      <playlist-script>/usr/local/share/gerbera/js/playlists.js</playlist-script>
      <virtual-layout type="js">
        <import-script>/etc/gerbera/import-cweiske.js</import-script>
      </virtual-layout>
    </scripting>
```

common.js is ok. I tested it with non-existing and syntax error:
> info: Unable to load /usr/local/share/gerbera/js/common.js.404: [/usr/local/src/gerbera/src/util/tools.cc:477] readTextFile Error: Could not open /usr/local/share/gerbera/js/common.js.404: Datei oder Verzeichnis nicht gefunden
> info: Unable to load /usr/local/share/gerbera/js/common.js: [/usr/local/src/gerbera/src/content/scripting/script.cc:380] _load Error: Scripting: failed to compile /usr/local/share/gerbera/js/common.js

**Comment by KarlStraussberger** [comment]
Can you share your script in the same way. The bad thing is that some issues in javascript do not raise an error at all.

**Comment by cweiske** [comment]
I've added it to http://p.cweiske.de/772#import-cweiske.js
There is a print() statement directly at the beginning which does not show up in the logs, so I suspect the script does not run at all.

**Comment by KarlStraussberger** [comment]
The print statement should be visible in the early logs on startup (when the script file is loaded)

**Comment by cweiske** [comment]
It does not.
Shouldn't it only be run when a file gets imported?

**Comment by KarlStraussberger** [comment]
There are two things that changed lately

1. instead of `obj.meta` you need to use `obj.metaData` which is an array of values instead of a single concatenated string. See https://docs.gerbera.io/en/stable/scripting.html#orig.metaData
2. `addCdsObject` no longer supports paths. It expects the second argument to be an objectId returned from `addContainerTree`.  `addContainerTree` takes a list of obj-like entries describing the container hierarchy. See https://docs.gerbera.io/en/latest/scripting.html#addCdsObject

**Comment by KarlStraussberger** [comment]
> It does not. Shouldn't it only be run when a file gets imported?

No. That runs on startup when JS is initialised. During init all functions are loaded into the JS environment in addition to the ones linked to C++ code. For each file only the `import-script` is executed (that's why all the functions have been moved to common.js)

May happen that the messages are not printed on startup.

**Comment by cweiske** [comment]
Thanks to your hints I managed to nail it down:
- Adding a `print()` statement to `common.js` gave output (even when not in debugging mode) during startup: ```gerbera[49365]: 2021-11-12 21:16:49   info: common.js```
- Removing everything except a print statement from my import-script, I still did not get any output when clicking "add" in the web UI file system view
- I noticed that there was an entry in the `mt_cds_object` table for that file already. When removing it from the database and then clicking "add" in the web UI file system view, my cweiske-import.js file got triggered and I saw the output in the log.

So my failure was to think that clicking "add" would re-trigger the import script, which it did not.

**Comment by whyman** [comment]
@cweiske great news!

**Comment by cweiske** [comment]
Now I also get the errors during import, as @KarlStraussberger explained about the backwards compatibility break:
> error: Invalid parent id passed to addCdsObject: 0

I think this is very unfortunate, because this will break the script of *everyone* who ever customized the import.

**Comment by KarlStraussberger** [comment]
I agree with you, thus we kept compatibility for about a year.

But we had to give it up in favour of metadata in the container tree and multi-valued metadata. The js interfacing code became anreadable and incomprehensible.

**Comment by cweiske** [comment]
Thanks for your help!
