### ISSUE TITLE
Gerbera UI - Improve Support for Disabled UI

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#216]
The new UI should support disabled UI similar to existing UI. 

- Show **disabled** UI message
- Disable all menu links
- Hide login form

The new Gerbera UI  sufficiently reports a message that the UI is disabled but does not disable interactions.

**Comment by elmodaddyb** [comment]
I have the changes in a local branch and plan to submit a PR in the next few days following some code cleanup.

**Comment by elmodaddyb** [comment]
Here is a screenshot of the view when the **UI is disabled** as per server configuration

<img width="817" alt="gerbera-ui-disabled" src="https://user-images.githubusercontent.com/8599799/34399695-cccaa8d4-eb57-11e7-8367-51e818a0d92c.png">

```xml
<server>
    <ui enabled="no" show-tooltips="yes">
      ...
    </ui>
</server
```
Here is the [TravisCI build](https://travis-ci.org/elmodaddyb/gerbera/builds/322424744), will submit PR soon.

_Any feedback or suggestions?_

**Comment by v00d00** [comment]
I guess hide the menu items also?

**Comment by elmodaddyb** [comment]
Yep, that makes sense.  Will do that and submit PR soon.

**Comment by elmodaddyb** [comment]
Here is the updated UI look.

<img width="403" alt="gerbera-ui-disabled" src="https://user-images.githubusercontent.com/8599799/34428275-034a55fa-ec19-11e7-8cc0-432528e016bd.png">

I will review the code once more and submit PR.
