### ISSUE TITLE
PPA & No file at /var/lib/gerbera/gerbera.html

### ISSUE THREAD

**Issue by Armagedonsky** [gerbera/gerbera#217]
Hi.

Elementary OS (based on Ubuntu). 
Installed the PPA.  "Gerbera" in GUI opens Firefox with this address "file:///var/lib/gerbera/gerbera.html" which results in "Firefox can't find the file at /var/lib/gerbera/gerbera.html." No files in directory  /var/lib/gerbera/

**Comment by elmodaddyb** [comment]
Hello @Armagedonsky - We had a similar issue a while back.  It was an issue with the Ubuntu build.

https://github.com/gerbera/gerbera/issues/167

Can you see if it is helpful?

**Comment by v00d00** [comment]
@Armagedonsky probably you just need to start the service (e.g `systemctl start gerbera`).

The file gets created when Gerbera is first run.

**Comment by v00d00** [comment]
I'm guessing this solved your issue, if you are still having trouble, let us know.
