### ISSUE TITLE
Document best practices for import script customization

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#2181]
Customizing the import script is non-trivial because there are some pitfalls that one needs to know. They should be documented, or a how-to guide be written in the manual.

The problems I am aware of:
- gerbera needs to be restarted when the import script is changed
- during startup, gerbera scans the whole library. This will take some time if you have 10ks of files
- The import script cannot be triggered with the "add" button in the web interface (and after restarting, the session ID is lost, so you have to reload the web interface anyway before actions work)

Notes:
- The import script can be triggered by running "touch /path/to/file.ogg"
- To speed up startup, use a second database with a nearly-empty directory structure. (This increases the bar to just test some changes. Better would be if there was some "--dont-scan-known-files" option for startup, or a way to not restart gerbera if the script changes)

Do the developers have some more tips? I'd make a patch for the documentation then.

**Comment by KarlStraussberger** [comment]
Just go ahead https://docs.gerbera.io/en/stable/scripting.html#index-0 would be the right place

**Comment by KarlStraussberger** [comment]
Most important: Point out to put all the changes in `custom-script` file so nothing is overwritten on update.
