### ISSUE TITLE
Numbering of playlist items does not work

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#2196]
still present.
On last night's playlist created, 25 out of 200 titles are not at the expected slot.

In other words, the 200th title is on position 175 in Gerbera, 176-200 are random titles out of the list.
I see no pattern, they are "just titles", no fancy characters or whatever

_Originally posted by @ckris1 in https://github.com/gerbera/gerbera/issues/2144#issuecomment-971594654_

**Comment by KarlStraussberger** [comment]
@ckris1 let's split this off.

I added PR #2195 which does not solve the issue but may help to find its cause. There is an option to show the track numbers in the ui which is enabled by default. If you pull the patch you can see the track numbers of your playlist items and we may find the issue.

The patch changes the playlist import functin as well because it messed up the numbering (found after seeing the numbers).

**Comment by ckris1** [comment]
okay, will try. But it's not in master branch, yet?

**Comment by KarlStraussberger** [comment]
No, it's an open PR and I forgot to look at the tests so it's not even green at the moment.

**Comment by KarlStraussberger** [comment]
Feel free to merge the PR. I will be faster to provide changes this way

**Comment by ckris1** [comment]
not really, I had no time.
I now have installed v1.9.2-171-g2243be58, is that OK?

**Comment by KarlStraussberger** [comment]
Not sure, introduced at least on issue before v1.9.2-240 (which is current head)

**Comment by ckris1** [comment]
well it was merged to master and I have "Show Track Numbering" under UI

BUT where do I see the track numbers? I havn't figured that out, yet :-O

**Comment by ckris1** [comment]
btw, it says "default value" (with no value) and the box next to that is empty in UI settings

**Comment by KarlStraussberger** [comment]
The UI settngs got a flaw as well 😢 

Go to the database tab it should list the contents of the folders with numbers now, also for playlists.

**Comment by ckris1** [comment]
then I must be blind.
I am on the DB tab, have database->Playlists->All Playlists expanded.
I see subfolders with my playlists, select one. One the right side I have the song title and the icons for download/edit/delete.

Nothing else, I'm afraid. Does this only work after rebuilding the lists maybe?

**Comment by KarlStraussberger** [comment]
Check out your `config.xml` and modify `<ui enabled="yes" show-numbering="yes"... >`

**Comment by ckris1** [comment]
<ui enabled="yes" show-tooltips="yes" show-numbering="yes">

makes no difference, though. Where should those track numbers show up, next to the song title in the db playlist view?

**Comment by ckris1** [comment]
`<ui enabled="yes" show-tooltips="yes" show-numbering="yes">`

**Comment by KarlStraussberger** [comment]
In front of the song title. Does your `webroot`-folder point to source or installation (/usr/local ...)?

**Comment by ckris1** [comment]
/usr/share/gerbera/web, installed as /usr/share/gerbera

**Comment by KarlStraussberger** [comment]
So you did `make install` and the files in that folders were properly updated? I'm running out of ideas.

**Comment by ckris1** [comment]
I'm building on another machine, install there, then take over (tar) what was created to the actual machine.
So it should be fine, everything works, UI is okay. Just no track titles.

**Comment by KarlStraussberger** [comment]
I wonder whether there are any leftovers from older versions that cause trouble

**Comment by ckris1** [comment]
I did a completely fresh install now, makes no difference :-(

**Comment by KarlStraussberger** [comment]
If you don't see numbers, there may be one hard reason: There are no numbers:
- Do you see track numbers in albums?
- Did you import the files with a custom playlist script?

**Comment by ckris1** [comment]
no custom script

Regarding track numbers....you're giving me a hard time here :-)
I do not know whether I see something or not when I have no clue what to look for.
Or, in other words, if there never were track numbers, I don't know how it would look like when they are there.
So far I'd say "no numbers at all". Do you have a screenshot for me as example?

**Comment by KarlStraussberger** [comment]
![grafik](https://user-images.githubusercontent.com/23654788/144565012-89f8b669-738a-4964-8771-7451a04cda78.png)
![grafik](https://user-images.githubusercontent.com/23654788/144564897-0a1d6400-cbc7-4d0a-84aa-9458979feaf4.png)

**Comment by ckris1** [comment]
Thanks
I never had that and I also have (and never had) no icons.

![screen](https://user-images.githubusercontent.com/76666498/144575840-2420af3a-ee95-43a9-95ab-7f9b7aa17427.jpg)

**Comment by KarlStraussberger** [comment]
The icons are extracted from albumart which is embedded in the media file or cover files in the folder of the media (if enabled, https://docs.gerbera.io/en/latest/config-import.html#resources).

**Comment by ckris1** [comment]
hmm....I see the albumart stuff on clients which play the files from gerbera, but not in the gerbera UI. So generally it's there.

Looking a the link above, I'm not using cover.* files anywhere. How does the config look like for reading the albumart from the mp3 or flac files directly? Saying that, the impact on performance during import might be quite noticable...

**Comment by ckris1** [comment]
uhm.....apologies....it's quite embarrassing, but as usual the problem was in front of the screen.
My script for moving a newly built gerbera from the dev machine to the one actually running it had a typo, so the binary wasn't updated :-(

Track numbers are there now, will investigate on the playlist thing this weekend.....

**Comment by KarlStraussberger** [comment]
Good to have solved the issue on the ui. Old binary means also issues in import still present!

**Comment by ckris1** [comment]
...and there wasn't much to investigate, it is quite obvious.
Remember the playlist I'm changing daily holds 200 titles.
They are in sequence, but some are missing. They all get appended then at the end of the playlist, see screenshot.

Building a new playlist shows the same but the numbers are random, so it's not like "track #11 always is appended after 200 or so". It can be any numbers. Also the number of titles which are misplaced is random. Can be 10, can be 30.


![screen](https://user-images.githubusercontent.com/76666498/144596701-cb6193e5-6b9b-4875-ac46-99fbaecf2b4e.jpg)

**Comment by KarlStraussberger** [comment]
Can you check whether the parent folder is of type `object.container.playlistContainer`. There are two folder types that trigger sorting: `object.container.playlistContainer` and `object.container.album.musicAlbum`

**Comment by ckris1** [comment]
no, the folder where all my playlists are stored is Container.object.container. That is true for both "Playlists" and "All Playlists"

![screen](https://user-images.githubusercontent.com/76666498/144659100-7ad15d2f-d564-48a9-b35e-d392f6de1d12.jpg)

**Comment by KarlStraussberger** [comment]
Did you check the folder properties?

![grafik](https://user-images.githubusercontent.com/23654788/144659453-393e9dcb-cbee-4ddc-b7b8-7ea73c955c75.png)

**Comment by ckris1** [comment]
well, the All Playlists is like this:

![screen](https://user-images.githubusercontent.com/76666498/144659862-a0e5babc-dd88-4819-8a9d-b163f2575e49.jpg)

The playlist with the strange sorting is different:

![screen1](https://user-images.githubusercontent.com/76666498/144659902-476e6c68-cec0-4a75-b764-37a64b40a1b5.jpg)

**Comment by KarlStraussberger** [comment]
That's what it should be. The tree does not matter, but the last folder has to be `playlistContainer`.

**Comment by ckris1** [comment]
then......it does not work as expected :-)
Let me try to create a playlist with 100 entries instead....

**Comment by KarlStraussberger** [comment]
There should not be any gaps in the numbers.

**Comment by ckris1** [comment]
even with only 15 files the order is off like described before...

**Comment by KarlStraussberger** [comment]
can you share an extract of your playlist file

**Comment by ckris1** [comment]
sure, but I'd prefer to send it to you by e-mail if possible.

**Comment by KarlStraussberger** [comment]
Of course.
