### ISSUE TITLE
extraction of UTF-8 encoded aux-data leads to truncation 

### ISSUE THREAD

**Issue by gjudtmann** [gerbera/gerbera#223]
upon testing gerbera to replace mediatomb I stepped across the following issue:

my use case: 

- gerbera 1.1 from debian testing repositories

- flac files with vorbis comments UTF-8

aux data are truncated at the end by the number of non ASCII characters the string is containing
example debug output:
`2017-12-31 16:42:22   DEBUG: [src/metadata/taglib_handler.cc:514] extractFLAC(): Adding auxdata: TPE1 with value PARSONS Geoffrey, BÄR Ola`

here the "f" from Olaf is missing at the end caused by the Ä in BÄR

I remember having had the issue with mediatomb a couple of years ago but do not remember the details of the solution or workaround.
This issue for mediatomb is described in
[https://sourceforge.net/p/mediatomb/bugs/78/](https://sourceforge.net/p/mediatomb/bugs/78/)

**Comment by v00d00** [comment]
Thanks for reporting!

**Comment by ghlupe2** [comment]
I can still see this behavior when importing auxdata WORK tag from a flac file:

> JS: WORK--->Carmen: Acte II, No. 18. Finale : « Holà ! Carmen ! Holà ! Holà ! » (Zuniga, Don José, Carmen, Dancaïre, Remendado, les Boh [7 characters missing]

When importing the same tag from an mp3 file, all is okay:

> JS: TIT1--->Carmen: Acte II, No. 18. Finale : « Holà ! Carmen ! Holà ! Holà ! » (Zuniga, Don José, Carmen, Dancaïre, Remendado, les Bohémiens)

**Comment by v00d00** [comment]
@ghlupe2 can you raise a new issue, with a debug log of an import ideally?

**Comment by ghlupe2** [comment]
Thanks for your reply, I'll try to do so, normally I start gerbera as a service (user gerbera) and 
`tail -f syslog | grep gerbera `
in an other terminal. Need to find out how to increase log level in this environment.

**Comment by ghlupe2** [comment]
https://github.com/gerbera/gerbera/issues/420#issue-402679800

No problem thanks to the excellent documentation :-) http://docs.gerbera.io/en/latest/daemon.html#troubleshooting
