### ISSUE TITLE
Warning when checking Impish repository for updates

### ISSUE THREAD

**Issue by jonathanrwatts** [gerbera/gerbera#2256]
Every time I run `sudo apt update` I get the following warning:

`W: Skipping acquisition of configured file 'main/source/Sources', as repository 'https://gerbera.jfrog.io/artifactory/debian-git impish InRelease' does not seem to provide it (sources.list entry misspelt?)`

Gerbera still seems to update properly, so I'm not sure if this is important or not.

**Comment by whyman** [comment]
This is because we haven't published a tagged release for impish yet
