### ISSUE TITLE
gerbera requires libupnp 1.8.3 or above ...

### ISSUE THREAD

**Issue by count00zero** [gerbera/gerbera#226]
Hi guys,

when building gerbera from source I'm confronted with a very odd/curious problem!
Although I tried the "included" pupnp 1.8.3 (via scripts/install) I failed to build:

-- Found UPnP: /usr/lib/libupnp.so (found version "1.8.1")
CMake Error at CMakeLists.txt:353 (message):
  gerbera requires libupnp 1.8.3 or above.

Then, I decided to build pupnp from source; and even then; same story.

currently I'm using /usr/lib/libupnp.so which is a symlink to /usr/lib/libupnp.so.13.0.0

Is there anybody out there with a possible solution/workaround?

THANKS a LOT!

BR,
count

**Comment by elmodaddyb** [comment]
@count00zero - Issue #182 is open for Gerbera to be compliant with **pupnp-master** branch.  Fortunately **gerbera-master** is updated to 1.8.3 version of `pupnp`, and the CMake check introduced, as you see the error.

You can check your `CMakeCache.txt` to see **where** the UPNP library and includes are coming from?  Also can check `LD_LIBRARY_PATH` to see if you have anything interesting.

I had a similar issue to yours, but was due to over-lap installs different versions of libupnp.  Manual cleanup of *.so, includes, pkgconfig was required to clear the errors.

Let me know if you have any luck.

Thanks,
Eamonn

**Comment by count00zero** [comment]
@elmodaddyb : Thanks! Your hint about "over-lap installs different versions of libupnp" was the solution ... uninstalled all the different versions, rebuilt upnp and gerbera and voila: IT WORKS

Thanks a lot!!!

**Comment by Martii** [comment]
Having the same issue here but if I remove my distro version of 1.6.17 I'll lose some functionality in VLC. *(would prefer not to and encounter dependcy h3ll)*

1. Should I open a new issue?
2. If not... a little new to the cmake arena and not sure what to set if anything.

Here's some session bits:
``` sh-session
-- Found UPnP: /usr/lib64/libupnp.so (found version "1.6.17") 
CMake Error at CMakeLists.txt:347 (message):
  gerbera requires libupnp 1.8.3 or above.
```

``` sh-session
lib64 # ls libupnp* -al
lrwxrwxrwx 1 root root     21 Feb 16 05:16 libupnp-1.8.so -> libupnp-1.8.so.10.1.0*
lrwxrwxrwx 1 root root     21 Jan 23 07:58 libupnp-1.8.so.10 -> libupnp-1.8.so.10.1.0*
-rwxr-xr-x 1 root root 204304 Aug 14  2017 libupnp-1.8.so.10.1.0*
lrwxrwxrwx 1 root root     16 Feb 16 04:59 libupnp.so -> libupnp.so.6.3.1*
lrwxrwxrwx 1 root root     16 Jan 21  2017 libupnp.so.6 -> libupnp.so.6.3.1*
-rwxr-xr-x 1 root root 151048 Dec 15  2014 libupnp.so.6.3.1*
```

Tried to go to http://pupnp.sourceforge.net/ but they are down for migration.

My distro has v1.0.0 of this project as a package and *it was working until today* where I get:

``` sh-session
2018-02-16 05:45:12    INFO: Configuration check succeeded.
2018-02-16 05:45:12 WARNING: IP is null
Exception raised in [src/server.cc:135] upnp_init(): upnp_init: UpnpInit failed
2018-02-16 05:45:12   ERROR: main: upnp error -203
2018-02-16 05:45:12   ERROR: Could not bind to socket.
2018-02-16 05:45:12    INFO: Please check if another instance of Gerbera or
2018-02-16 05:45:12    INFO: another application is running on port -1.
2018-02-16 05:45:12   ERROR: upnp_cleanup: UpnpUnRegisterRootDevice failed
Exception raised in [src/server.cc:260] shutdown(): upnp_cleanup: UpnpUnRegisterRootDevice failed
```

All I did today was run a distro update. I do run *bind* for a caching DNS server *(which was updated)* but other than that not much on it. Network is configured with IPv4 and a IPv6 set to `link-local` *(actually had this set to None in KDE configuration but put it back to my distros default)*. My ethernet device is `eno1` as configured on default installation/rolling updates. Firewall allows everything currently.

Any pointers would be much appreciated... and presume I'm a noobie please *(which I am sort of... so not familiar with what was said above about `LD_LIBRARY_PATH`)*. Have nothing in my `env | grep "LD_LIBRARY_PATH"`.

Thanks and sorry about tagging on here... didn't see anything in [CONTRIBUTING.md](https://github.com/gerbera/gerbera/blob/ab340f5e41995d592baf39ed682ff23a71ea0f93/CONTRIBUTING.md) regarding etiquette. 😸 

Ref(s):
* http://docs.gerbera.io/en/latest/config-server.html *(read this... no such animal in the config.xml here)*
* and a bunch of other things via a general search both in a search engine as well as GitHub

**Comment by elmodaddyb** [comment]
@Martii - Sorry to hear about the trouble using Gerbera.  Perhaps we can figure out a solution.

Here are some suggestions.

### LD_LIBRARY_PATH

`LD_LIBRARY_PATH` is a list of directories to search for dynamic libraries(pupnp is one such library).  If you are familiar with `PATH` variable for searching for binary files, `LD_LIBRARY_PATH` is similar in concept, but for libraries (*.so)  Take a look at this [post for a better explanation](https://unix.stackexchange.com/questions/354295/what-is-the-default-value-of-ld-library-path).

The `/scripts/install-pupnp18.sh` script will install to `/usr/local` prefix by default, unless you are running **FreeBSD**. The gerbera build [uses CMake to lookup the libraries for **pupnp**](https://github.com/gerbera/gerbera/blob/master/CMakeLists.txt#L342) and uses the default library paths.

> You can change the **first** lookup path by setting the value of `LD_LIBRARY_PATH`

Here's a good post on how to set the value:

[How to set the environmental variable LD_LIBRARY_PATH in linux](https://stackoverflow.com/questions/13428910/how-to-set-the-environmental-variable-ld-library-path-in-linux)

This may allow you to run both versions of pupnp side-by-side...compiling Gerbera on a specific version of the library.  In the event that the installation clobbers the existing library files (headers + so's).  Then it will probably require a meticulous cleanup of the `*/include` and `*/lib` affected folders to get back to a stable setup of **1.6** or **1.8** respectively.

### Binding on PORT

The error you received of 
```
2018-02-16 05:45:12   ERROR: main: upnp error -203
```
is from the underlying **pupnp** library saying it cannot bind on the port number. Its a bit misleading, as this could mean 2 possible ports (either the Gerbera port, or the UDP 1900 port).  In the version at 2b904bb54ddb9615dd9242d8ff6a5ce8ec8526cc we improved the alerting here to include language about both...

##### Figure out what ports are bound

Run the command `netstat -lnp` to show you all bound ports on your linux instance

##### Manually specify a port for Gerbera
This should not be necessary as the underlying **pupnp** library should use an arbitrary port starting at _49152_.  It might be that your system is blocking ports by some type of security setup or running process?

Example configuration for manually specifying a port would look like:

```xml
<config>
   <server>
      <port>49153</port>
   </server>
</config>
```

Let me know if you have any success with either issue.
