### ISSUE TITLE
Improved script debugging

### ISSUE THREAD

**Issue by tcrass** [gerbera/gerbera#227]
Hi there,

I am currently facing the problem of a Gerbera installation perfectly scanning my video collection when starting up, but failing to properly reflect changes during run-time. For instance, when renaming or adding a video file while Gerbera is already running, I find a message "ERROR: Exception caught: Script: failed to execute script" in the system journal, but no further information _why_ the script's execution failed. Maybe I just missed the place where to increase Gerbera's debug level -- if not, I'd appreciate if generally some more detailed information could be written to the journal about the underlying cause of a script execution failure.

Apart from that, I'm *so* happy that MediaTomb lives on in the form of Gerbera -- I just *love* the possibility to create my own library layout through custom import scripts! :) (And have I mentioned already that I very much prefer the friendly Gerbera logo over the morbid scull of MediaTomb...?)

Cheers --

-- Torsten

**Comment by elmodaddyb** [comment]
@tcrass - you can try to append `--debug` to the gerbera command and it runs in debug mode with verbose logs.

My guess is that duktape is running the import script, but having troubles.  The debug logs may help reveal the flaw.

**Comment by tcrass** [comment]
Eamon,

seems I made a mistake when replying to the e-mail I received from you upon my initial posting I'll just re-post my replies here...

--------8<--------

Eamonn,

> @tcrass <https://github.com/tcrass> - you can try to append |--debug| to the gerbera command and it runs in debug mode with verbose logs.

thanks, that did the trick! I was expecting a debug level setting somewhere in the config.xml file, didn't think of the command line...

Cheers --

    Torsten 

--------8<-------

OK,

seems I'm running into trouble because the variable "object_script_path" is null when a change in a video file is detected and the import script gets called for the changed file. I must admit I just re-used a line of code involving that variable without understanding its meaning since I couldn't find any documentation about its purpose. So could you please clarify for me what data is supposed to be available in "object_script_path"? (It doesn't get set in import.js nor in common.js.)

Thanks --

    Torsten 

--------8<--------

OK, it seems object_script_path initially contains the "root" path to a media directory as specified in the <autoscan><directory>...</directory></autoscan> section of config.xml. Here's the result of an additional print(...)-statement I inserted into the addVideo(obj) function:

  JS: object_script_path = /mnt/data/movies

When a video file changes, I get:

  JS: object_script_path = null

So... is this a bug or a feature? ;)

Cheers --

    Torsten

**Comment by elmodaddyb** [comment]
Awesome job debugging.  I think I was able to figure out a bit further.
I assumed you have a Autoscan Directory, with a INOTIFY??

If so, perhaps the bug is the following:

1. Autoscan Inotify is calling [_WRITE, MOVE, CREATE_](https://github.com/gerbera/gerbera/blob/master/src/autoscan_inotify.cc#L240)
2. ContentManager::addFile is called, but [`check_path`](https://github.com/gerbera/gerbera/blob/master/src/content_manager.cc#L1316)  returns **FALSE** and doesn't set `rootpath`
3. This will result in `rootpath == nullptr`....I think.
4. A new task is created with a rootpath == nullptr
5. Layout is run against the task->getPath() and results in NULLPTR

```c++
int ContentManager::addFile(zmm::String path, bool recursive, bool async,
    bool hidden, bool lowPriority, bool cancellable)
{
    String rootpath;
    if (check_path(path, true))
        rootpath = path;
    return addFileInternal(path, rootpath, recursive, async, hidden, lowPriority, 0, cancellable);
}
```

These are some big guesses on my part without debugging...so it might be helpful to know more details around the scenario.  Is INOTIFY being used here?

Thanks,
Eamonn

**Comment by tcrass** [comment]
Eamon, 

you guessed right -- the directory under question is monitored trough inotify. If it's of any help, here's my config.xml:

    <?xml version="1.0" encoding="UTF-8"?>
    <config version="2" xmlns="http://mediatomb.cc/config/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mediatomb.cc/config/2 http://mediatomb.cc/config/2.xsd">
    
    <server>
        <pc-directory upnp-hide="yes"/>

        <ui enabled="yes" show-tooltips="yes">
        <accounts enabled="no" session-timeout="30">
            <account user="gerbera" password="gerbera"/>
        </accounts>
        </ui>
        <name>Priamos</name>
        <udn>9d37f254-0ba0-5166-a481-dc2ea73a0f33</udn>
        <home>/var/lib/gerbera</home>
        <webroot>/usr/local/share/gerbera/web</webroot>
        
        <alive>90</alive>
        <storage>
        <sqlite3 enabled="yes">
            <database-file>gerbera.db</database-file>
        </sqlite3>
        <mysql enabled="no">
            <host>localhost</host>
            <username>gerbera</username>
            <database>gerbera</database>
        </mysql>
        </storage>
        <protocolInfo extend="no"/>
        
        
        
        
        <extended-runtime-options>
        <mark-played-items enabled="no" suppress-cds-updates="yes">
            <string mode="prepend">*</string>
            <mark>
            <content>video</content>
            </mark>
        </mark-played-items>
        </extended-runtime-options>
    </server>
    <import hidden-files="no">

        <filesystem-charset>UTF-8</filesystem-charset>
        <metadata-charset>UTF-8</metadata-charset>
        <autoscan use-inotify="auto">
                <directory location="/mnt/data/movies" mode="inotify" level="full" recursive="yes"/>
                <directory location="/mnt/data/audio" mode="inotify" level="full" recursive="yes"/>
        </autoscan>

        <scripting script-charset="UTF-8">
        <common-script>/usr/local/share/gerbera/js/common.js</common-script>
        <playlist-script>/var/lib/gerbera/js/playlists.js</playlist-script>
        <virtual-layout type="js">
            <import-script>/var/lib/gerbera/js/import.js</import-script>
        </virtual-layout>
        </scripting>

        <mappings>
        <extension-mimetype ignore-unknown="no">
            <map from="mp3" to="audio/mpeg"/>
            <map from="ogx" to="application/ogg"/>
            <map from="ogv" to="video/ogg"/>
            <map from="oga" to="audio/ogg"/>
            <map from="ogg" to="audio/ogg"/>
            <map from="ogm" to="video/ogg"/>
            <map from="asf" to="video/x-ms-asf"/>
            <map from="asx" to="video/x-ms-asf"/>
            <map from="wma" to="audio/x-ms-wma"/>
            <map from="wax" to="audio/x-ms-wax"/>
            <map from="wmv" to="video/x-ms-wmv"/>
            <map from="wvx" to="video/x-ms-wvx"/>
            <map from="wm" to="video/x-ms-wm"/>
            <map from="wmx" to="video/x-ms-wmx"/>
            <map from="m3u" to="audio/x-mpegurl"/>
            <map from="pls" to="audio/x-scpls"/>
            <map from="flv" to="video/x-flv"/>
            <map from="mkv" to="video/x-matroska"/>
            <map from="mka" to="audio/x-matroska"/>
            
            
            
            
        </extension-mimetype>
        <mimetype-upnpclass>
            <map from="audio/*" to="object.item.audioItem.musicTrack"/>
            <map from="video/*" to="object.item.videoItem"/>
            <map from="image/*" to="object.item.imageItem"/>
            <map from="application/ogg" to="object.item.audioItem.musicTrack"/>
        </mimetype-upnpclass>
        <mimetype-contenttype>
            <treat mimetype="audio/mpeg" as="mp3"/>
            <treat mimetype="application/ogg" as="ogg"/>
            <treat mimetype="audio/ogg" as="ogg"/>
            <treat mimetype="audio/x-flac" as="flac"/>
            <treat mimetype="audio/x-ms-wma" as="wma"/>
            <treat mimetype="audio/x-wavpack" as="wv"/>
            <treat mimetype="image/jpeg" as="jpg"/>
            <treat mimetype="audio/x-mpegurl" as="playlist"/>
            <treat mimetype="audio/x-scpls" as="playlist"/>
            <treat mimetype="audio/x-wav" as="pcm"/>
            <treat mimetype="audio/L16" as="pcm"/>
            <treat mimetype="video/x-msvideo" as="avi"/>
            <treat mimetype="video/mp4" as="mp4"/>
            <treat mimetype="audio/mp4" as="mp4"/>
            <treat mimetype="video/x-matroska" as="mkv"/>
            <treat mimetype="audio/x-matroska" as="mka"/>
        </mimetype-contenttype>
        </mappings>
        <online-content>
        <YouTube enabled="no" refresh="28800" update-at-start="no" purge-after="604800" racy-content="exclude" format="mp4" hd="no">
            <favorites user="gerbera"/>
            <standardfeed feed="most_viewed" time-range="today"/>
            <playlists user="gerbera"/>
            <uploads user="gerbera"/>
            <standardfeed feed="recently_featured" time-range="today"/>
        </YouTube>
        </online-content>
    </import>
    <transcoding enabled="no">
        <mimetype-profile-mappings>
        <transcode mimetype="video/x-flv" using="vlcmpeg"/>
        <transcode mimetype="application/ogg" using="vlcmpeg"/>
        <transcode mimetype="application/ogg" using="oggflac2raw"/>
        <transcode mimetype="audio/x-flac" using="oggflac2raw"/>
        </mimetype-profile-mappings>
        <profiles>
        <profile name="oggflac2raw" enabled="no" type="external">
            <mimetype>audio/L16</mimetype>
            <accept-url>no</accept-url>
            <first-resource>yes</first-resource>
            <accept-ogg-theora>no</accept-ogg-theora>
            <agent command="ogg123" arguments="-d raw -o byteorder:big -f %out %in"/>
            <buffer size="1048576" chunk-size="131072" fill-size="262144"/>
        </profile>
        <profile name="vlcmpeg" enabled="no" type="external">
            <mimetype>video/mpeg</mimetype>
            <accept-url>yes</accept-url>
            <first-resource>yes</first-resource>
            <accept-ogg-theora>yes</accept-ogg-theora>
            <agent command="vlc" arguments="-I dummy %in --sout #transcode{venc=ffmpeg,vcodec=mp2v,vb=4096,fps=25,aenc=ffmpeg,acodec=mpga,ab=192,samplerate=44100,channels=2}:standard{access=file,mux=ps,dst=%out} vlc:quit"/>
            <buffer size="14400000" chunk-size="512000" fill-size="120000"/>
        </profile>
        </profiles>
    </transcoding>
    </config>

And here's my import script:

    // MediaTomb import script for Priamos
    // Based on original import script.

    var AUDIO_PREFIX = 'Audio';
    var IMAGE_PREFIX = 'Photos';
    var VIDEO_PREFIX = 'Video';

    function addAudio(obj) {

        if (obj.location.match(/^.*?\/audio\//i)) {


            var dir = getRootPath(object_script_path, obj.location);
            dir.shift();

            if (!dir[0].match(/^X-/)) {

                var desc = '';
                var artist_full;
                var album_full;

                // first gather data
                var title = obj.meta[M_TITLE];
                if (!title) {
                    title = obj.title;
                }

                var artist = obj.meta[M_ARTIST];
                if (!artist) {
                    artist = 'Unknown';
                    artist_full = null;
                }
                else {
                    artist_full = artist;
                    desc = artist;
                }

                var album = obj.meta[M_ALBUM];
                if (!album) {
                    album = 'Unknown';
                    album_full = null;
                }
                else {
                    desc = desc + ', ' + album;
                    album_full = album;
                }

                if (desc) {
                    desc = desc + ', ';
                }

                desc = desc + title;

                var date = obj.meta[M_DATE];
                if (!date) {
                    date = 'Unknown';
                }
                else {
                    date = getYear(date);
                    desc = desc + ', ' + date;
                }

                var genre = obj.meta[M_GENRE];
                if (!genre) {
                    genre = 'Unknown';
                }
                else {
                    desc = desc + ', ' + genre;
                }

                var description = obj.meta[M_DESCRIPTION];
                if (!description) {
                    obj.meta[M_DESCRIPTION] = desc;
                }

                var track = obj.meta[M_TRACKNUMBER];
                var trackTitle;
                if (!track) {
                    track = '';
                    trackTitle = title;
                }
                else {
                    if (track.length < 2) {
                        track = '0' + track;
                    }
                    trackTitle = track + " - " + title;
                }
                obj.title = trackTitle;

                var chain = new Array(AUDIO_PREFIX);
                chain = chain.concat(dir);
                addCdsObject(obj, createContainerChain(chain));

                chain = new Array(AUDIO_PREFIX, '- Artists -', artist, 'All Songs');
                obj.title = title;
                addCdsObject(obj, createContainerChain(chain));

                if (dir[1].search(/^Hör/) >= 0) {
                    chain = new Array(AUDIO_PREFIX, '- Authors -', artist, album);
                    obj.title = trackTitle;
                    addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ALBUM);
                }
                else {
                    chain = new Array(AUDIO_PREFIX, '- Artists -', artist, album);
                    obj.title = trackTitle;
                    addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ALBUM);

                    chain = new Array(AUDIO_PREFIX, '- Albums -', album);
                    obj.title = trackTitle;
                    addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ALBUM);
                }
            }
        }
    }


    function addVideo(obj)
    {
        //var chain = new Array('Video', 'All Video');
        //addCdsObject(obj, createContainerChain(chain));

    print("object_script_path = " + object_script_path);

        if (obj.location.match(/^.*?\/(movies|video)\//i)) {

            var dir = getRootPath(object_script_path, obj.location);
            dir.shift();

            var chain = new Array(VIDEO_PREFIX);
            chain = chain.concat(dir);

            addCdsObject(obj, createContainerChain(chain));
        }

    }

    function addImage(obj)
    {

        if (obj.location.match(/^.*?\/(images|photos)\//i)) {

            var dir = getRootPath(object_script_path, obj.location);
            dir.shift();

            var lastSegment = dir[dir.length - 1];

            if (!lastSegment.match(/^\_/) || lastSegment.match(/^\_slides/i)) {

                var chain = new Array(IMAGE_PREFIX);
                chain = chain.concat(dir);
                addCdsObject(obj, createContainerChain(chain));

                var date = obj.meta[M_DATE];
                if (date)
                {
                    var dateParts = date.split('-');
                    if (dateParts.length > 1)
                    {
                        var year = dateParts[0];
                        var month = dateParts[1];

                        chain = new Array(IMAGE_PREFIX, '- By Date - ', year, month);
                        addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER);
                    }
                }
            }
        }
    }


    // main script part

    if (getPlaylistType(orig.mimetype) == '') {
        var arr = orig.mimetype.split('/');
        var mime = arr[0];

        var obj = orig;
        obj.refID = orig.id;

        if (mime == 'audio') {
            addAudio(obj);
        }

        if (mime == 'video')
        {
            addVideo(obj);
        }

        if (mime == 'image')
        {
            addImage(obj);
        }

        if (orig.mimetype == 'application/ogg')
        {
            if (orig.theora == 1)
                addVideo(obj);
            else
                addAudio(obj);
        }

    }


Thanks --

-- Torsten

**Comment by v00d00** [comment]
Can you add another print at the top of the script to see if it is set? I can see code unsetting it there is an error.

**Comment by tcrass** [comment]
v00d00,

sorry for the delay, I currently have a terribly lot of work to do...

Anyway, I put an additional print statements right at the top of the import.js script, and it seems as though object_script path is unset right from the beginning when it gets called after a file change was detected:

    Jan 19 21:36:47 priamos gerbera[28615]: 2018-01-19 21:36:47   ERROR: Exception caught: Script: failed to execute script
    Jan 19 21:36:47 priamos gerbera[28615]: Exception raised in [src/scripting/script.cc:304] _execute(): Script: failed to execute script
    Jan 19 21:36:49 priamos gerbera[28615]: 2018-01-19 21:36:49      JS: Top! object_script_path = null
    Jan 19 21:36:49 priamos gerbera[28615]: 2018-01-19 21:36:49      JS: Here! object_script_path = null
    Jan 19 21:36:49 priamos gerbera[28615]: 2018-01-19 21:36:49      JS: Processing /mnt/data/movies/Dokumentation/Biologie/Costa_Rica.mp4

Hope that gives any more insight...

-- Torsten

**Comment by v00d00** [comment]
@tcrass I guess we can close this one now?

**Comment by tcrass** [comment]
> @tcrass <https://github.com/tcrass> I guess we can close this one now?

Yes, we can! :)

Cheers --

	Torsten
