### ISSUE TITLE
copyright/license comments in new source files

### ISSUE THREAD

**Issue by astylos** [gerbera/gerbera#228]
I'm guessing the old MediaTomb copyright/license comments in existing source files are now considered out of date, so what is expected in new source files?

**Comment by elmodaddyb** [comment]
@astylos - I pushed code changes for the new UI components a few weeks back.

Here is an example --> [gerbera.app.js](https://github.com/gerbera/gerbera/blob/master/web/js/gerbera.app.js#L1)

@v00d00 - maybe with the new docs generator it should be improved in some way?

**Comment by v00d00** [comment]
Yeah I was thinking we need to go through and update the copyright notices. All the original code is still owned by the original mediatomb authors, so should be fine.

New files should look something like

```
/*GRB*
    Gerbera - https://gerbera.io/
    <<FILE>> - this file is part of Gerbera.
    Copyright (C) 2016-2018 Gerbera Contributors
    Gerbera is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License version 2
    as published by the Free Software Foundation.
    Gerbera is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with Gerbera.  If not, see <http://www.gnu.org/licenses/>.
    $Id$
*/
```

@elmodaddyb We should probably drop Gena Batyan , Sergey 'Jin' Bostandzhyan  Leonhard Wimmer from the new UI files. Its your copyright 👍

**Comment by astylos** [comment]
OK, thanks for the responses.
