### ISSUE TITLE
CMAKE script doesnt check for libpugixml dependency

### ISSUE THREAD

**Issue by BobManMasher** [gerbera/gerbera#2283]
Just been trying to compile V1.9.2 on Debian 11 Bullseye. CMAKE cleared without any errors but the make failled with an error as it couldn't find pugixml. Just loaded libpugixml and compile has got further.  Is it possible to adda check for this dependency?
Cheers - Bob

**Comment by whyman** [comment]
Hey Bob, it certainly should find pugixml. 

https://github.com/gerbera/gerbera/blob/539cf137d2f09403105b3da872bfbc02a40d02f0/CMakeLists.txt#L390

Can you paste your cmake log?

You may want to clear your cmake build directory to start from a clean slate.

**Comment by BobManMasher** [comment]
Will do that later Ian - just had the same problem with duktape-dev.  I have just installed the dev packages for those and it's off on another run. Duktape caused the biggest headache as it changes name between debian versions so my deb 10 compile wouldn't install on Deb 11. I was a bit lazy setting up Deb 11  for compiling and didn't manually check the dependency list and just used cmake to point out whats missing.

**Comment by KarlStraussberger** [comment]
Hi Bob, you may just try the build-deb.sh script. It has it already build in.

**Comment by whyman** [comment]
Going to assume this is resolved

**Comment by BobManMasher** [comment]
Hi - sorry for the delay - yes please close. The issue was resolved by clearing the cmake build directory.  I did look at the script - but didn't use it in the end as I had done a number of substitutions to modules and I was only about two libs missing at this stage. Anyway, 1.9.2. compiled and working perfectly on the test system and about to go live on my main server - thanks as ever for the help and Merry Christmas

**Comment by whyman** [comment]
Merry Christmas Bob!
