### ISSUE TITLE
Debian 11 armv7l Error in UI

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#2291]
Not sure whether to comment on this one or create a new issue, but I get the same issue again with current **master**. Running on Debian 11 armv7l.

![image](https://user-images.githubusercontent.com/63122/144604413-ecbe64a5-5855-4f5f-a571-f801d0824b66.png)

_Originally posted by @a-st in https://github.com/gerbera/gerbera/issues/105#issuecomment-985488604_

**Comment by KarlStraussberger** [comment]
The original issue is far to old to be related or a regression

**Comment by KarlStraussberger** [comment]
Do you get any error message in gerbera server log?

May be related to file permissions or installation paths.

**Comment by a-st** [comment]
Thanks for creating a new issue. This might also be related to #2216. Going to fetch and attach the debug logs from the server.

**Comment by a-st** [comment]
[gerbera.log](https://github.com/gerbera/gerbera/files/7649855/gerbera.log)

**Comment by KarlStraussberger** [comment]
Please ensure that gerbera user has access to `/usr/share/gerbera/web` and its subdirectories. If you installed from some online repository ensure `that /usr/share/gerbera/web/vendor/popper/popper.js` has version 1.16.1

**Comment by a-st** [comment]
I checked with cURL and the `Content-Length` header clearly looks off

```
$ curl -v 'http://192.168.178.2:49152/content/interface?req_type=auth&action=get_config'
*   Trying 192.168.178.2:49152...
* Connected to 192.168.178.2 (192.168.178.2) port 49152 (#0)
> GET /content/interface?req_type=auth&action=get_config HTTP/1.1
> Host: 192.168.178.2:49152
> User-Agent: curl/7.77.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< CONTENT-LENGTH: 1735354600
< Accept-Ranges: bytes
< CONTENT-TYPE: application/json; charset=UTF-8
< DATE: Fri, 03 Dec 2021 16:13:10 GMT
< LAST-MODIFIED: Thu, 01 Jan 1970 00:00:00 GMT
< SERVER: Linux/3.2.0-6-nas5xx, UPnP/1.0, Portable SDK for UPnP devices/17.5.0
< X-User-Agent: redsonic
< Cache-Control: no-cache, must-revalidate
< SameSite: Lax
< CONNECTION: close
<
{"success":true,"config":{"accounts":true,"enableNumbering":true,"enableThumbnail":true,"enableVideo":false,"show-tooltips":true,"poll-when-idle":false,"poll-interval":2,"have-inotify":true,"items-per-page":{"default":25,"option":[10,25,50,100]},"actions":{"action":[]},"friendlyName":"Gerbera","version":"1.9.2-58e93ac"}}* transfer closed with 1735354278 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 1735354278 bytes remaining to read
```

**Comment by KarlStraussberger** [comment]
Seems to be related to your UPnP lib: `SERVER: Linux/3.2.0-6-nas5xx, UPnP/1.0, Portable SDK for UPnP devices/17.5.0` vs. `SERVER: Linux/5.3.18-lp152.95-default, UPnP/1.0, Portable SDK for UPnP devices/1.14.12`

**Comment by whyman** [comment]
Did you build libupnp with cmake? It's known to be broken on 32bit. Should be fine with autotools

**Comment by neheb** [comment]
@whyman got more details?

**Comment by neheb** [comment]
@KarlStraussberger that 17 version number looks bogus. I think it happens with the cmake build.

**Comment by whyman** [comment]
@neheb no support for "largefile", so you end up with 32bit off_t, while Gerbera does have support so ours is 64bit

**Comment by neheb** [comment]
Sounds like they need meson.

**Comment by neheb** [comment]
to clarify, meson does not allow you to disable largefile. It's always on.

**Comment by whyman** [comment]
FYI we will have ARM in our Debian repo now(as of #2386), would appreciate if you could test to see if using a package helps

**Comment by a-st** [comment]
@whyman Thanks a lot, this build works like a charm 👍

**Comment by whyman** [comment]
Great news! Thanks @a-st
