### ISSUE TITLE
New UI: Invalid session id

### ISSUE THREAD

**Issue by v00d00** [gerbera/gerbera#230]
When trying to access file system after you have restarted the Gerbera process you get a invalid session id" warning.

![image](https://user-images.githubusercontent.com/345034/34641107-bd482f52-f2f6-11e7-8e11-ec45fc34b86e.png)

Could it fetch a new session to save a manual refresh?

**Comment by elmodaddyb** [comment]
Yep, I encounter this as well.  Right now there is no impl. to clear the `SID` cookie & refresh.  It was complicated to **know** which method might result in an `invalid session` response.  However, now we have `GERBERA.Updates.errorCheck()` checking ALL ajax responses....so it should be easy to hook into this error.

Presently you will have to force refresh your browser to clear the SID cookie.

I will implement the fix.

**Comment by v00d00** [comment]
Awesome, can we make the new UI the default too?

**Comment by elmodaddyb** [comment]
We are all set here, I have fixes completed to reload session.  I will push this change...then open a new ticket to move `/gerbera.html` to `/index.html`  There are a few implementation changes to allow `/` to work as the default in `GERBERA.App.reload()`
