### ISSUE TITLE
TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.

### ISSUE THREAD

**Issue by ngosang** [gerbera/gerbera#2312]
I saw this trace in my logs but I can not reproduce the issue anymore.

`TagLib: ID3v2::Tag::read() - Duplicate ID3v2 tags found.`

 I guess some file in my collection has malformed metadata. This trace has 2 issues:
* It is the only trace in my logs without the timestamp and log level. It looks like you are using print instead of the logger.
* With traces in info level I don't know which file is wrong.

Since I don't know how to reproduce the issue I can not provide debug traces or test a fix.

**Comment by KarlStraussberger** [comment]
This message comes from TagLib. It is not really helpful but we do not get anything pointing to an error from TagLib. I think there are something link environment variables or build flags to get verbose message

**Comment by ngosang** [comment]
If it can not be fixed in Gerbera you can close.
