### ISSUE TITLE
HTTP interface not available when using hostname

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#2326]
I have a host name entry in my DNS server `mediatomb.home.cweiske.de` that points to the server running gerbera.

Using the browser to access gerbera's web interface via the IP address works: `http://192.168.3.3:49152`.
Using the host name does not work: `http://mediatomb.home.cweiske.de:49152/`

curl says:
```
url -vi http://mediatomb.home.cweiske.de:49152
*   Trying 192.168.3.3:49152...
* Connected to mediatomb.home.cweiske.de (192.168.3.3) port 49152 (#0)
> GET / HTTP/1.1
> Host: mediatomb.home.cweiske.de:49152
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

This did work with 1.9.2 and earlier, but the git version since 2 or 4 weeks is broken.

Gerbera version: `v1.9.2-274-gffb6e173`

**Comment by whyman** [comment]
I suspect you have upgraded your libupnp version?

**Comment by ngosang** [comment]
Same issue here.
Gerbera master ffb6e173c065e8833a970d8905cb6886e45ac681 
PUPNP=1.14.12

```
curl -vvv http://myserv:49494/
*   Trying 192.168.1.191:49494...
* Connected to myserv (192.168.1.191) port 49494 (#0)
> GET / HTTP/1.1
> Host: myserv:49494
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server


curl -vvv http://192.168.1.191:49494/
*   Trying 192.168.1.191:49494...
* Connected to 192.168.1.191 (192.168.1.191) port 49494 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.191:49494
> User-Agent: curl/7.80.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< CONTENT-LENGTH: 25834
< Accept-Ranges: bytes
< CONTENT-TYPE: text/html
< DATE: Sat, 11 Dec 2021 16:47:59 GMT
< LAST-MODIFIED: Sat, 13 Nov 2021 13:07:40 GMT
< SERVER: Linux/5.10.63-v7l+, UPnP/1.0, Portable SDK for UPnP devices/1.14.12
< X-User-Agent: redsonic
< CONNECTION: close
< 
<!DOCTYPE html>
...
```

**Comment by KarlStraussberger** [comment]
There has been a change to libpupnp, only allowing ip calls to avoid spoofed calls. The calkback to verify other calks is not implemented yet.

**Comment by KarlStraussberger** [comment]
Best is to hide web ui behind a reverse proxy

**Comment by whyman** [comment]
For future reference, here is is the interface to be implemented (from pupnp master): 

```c
/*
 * \brief Callback for validating HTTP requests HOST header values.
 *
 * @param hostname the value in the request HOST header.
 * @return An integer representing one of the following:
 *     \li \c UPNP_E_SUCCESS: a request with the HOST header set to hostname
 *                            should be processed.
 *     \li \c UPNP_E_BAD_HTTPMSG the request should be rejected.
 */
typedef int (*WebCallback_HostValidate)(const char *hostname, void *cookie);

/*
 * \brief Set callback for validating HTTP requests HOST header values.
 *
 * @param callback the host validating callback function or NULL.
 * @param cookie the chocolate you like.
 */
EXPORT_SPEC void UpnpSetHostValidateCallback(
        UpnpLib *p, WebCallback_HostValidate callback, void *cookie);

/*
 * \brief Enable or disable literal IP redirection.
 *
 * @param enable Zero to disable (default) non-zero to enable.
 */
EXPORT_SPEC void UpnpSetAllowLiteralHostRedirection(UpnpLib *p, int enable);``

**Comment by ngosang** [comment]
Why are you using libupnp as webserver for the web UI? I suppose it's for convenience (to reuse code) but it makes more sense to have a different webserver in a different port for the Web UI. You will be able to fix this issue and more and be sure the UI will keep working in the next releases of libupnp.

**Comment by KarlStraussberger** [comment]
The webserver logic is in libpupnp so if we would have to do it on our own or link some other lib. Sounds easy but becomes nasty with duplicate code for web and upnp.

**Comment by ngosang** [comment]
I fixed it in  Traefik replacing Host header. Maybe is useful for someone but this is just a workaround.
```yaml
http:
  routers:
    gerbera:
      entryPoints:
      - web
      middlewares:
      - change-host-header # fix for https://github.com/gerbera/gerbera/issues/2326
      service: serv1-gerbera
      rule: Host(`gerbera.home`)

  services:
    serv1-gerbera:
      loadBalancer:
        servers:
        - url: http://192.168.1.191:49494/

  middlewares:
    change-host-header:
      headers:
        customRequestHeaders:
          Host: "192.168.1.191:49494"
```

**Comment by ngosang** [comment]
@whyman the fix is working but I have some complains.

1. The hostname validation prints the warning trace but it's not blocking the requests to the UI (all requests are working no matter the hostname). Is that expected?
```
2022-01-09 13:07:01 warning: Rejected attempt to load host 'gerbera.home' as it does not match configured virtualURL: ''. See https://docs.gerbera.io/en/stable/config-server.html#virtualurl
```

2. Some devices in my network use the IP instead of the hostname. I think you should allow all IP:PORT requests:
```
2022-01-09 13:13:01 warning: Rejected attempt to load host '192.168.1.191:49494' as it does not match configured virtualURL: 'http://gerbera.home/'. See https://docs.gerbera.io/en/stable/config-server.html#virtualurl
```

3. I configured the virtualURL [as in the example](https://docs.gerbera.io/en/stable/config-server.html#virtualurl) but I see `//` at the end of the URL. I can remove the slash from the config but I think It should be done by you when you load the config to make it more user-friendly.
```
2022-01-09 13:12:59   info: The Web UI can be reached by following this link: http://gerbera.home//
```
