### ISSUE TITLE
Database import hangs on .m3u files

### ISSUE THREAD

**Issue by jonathanrwatts** [gerbera/gerbera#2333]
I'm using Gerbera (the latest from `debian-git`, currently `v1.9.2-279-g1aab4a1b`) to stream music to my Xbox One.  I've been ripping FLACs with `abcde`, and having it automatically create an .m3u playlist for each CD.  When Gerbera tries to import these CDs (whether from an automatic import or a manual one), it imports a random number of tracks and then hangs on the .m3u file--the web interface just says `Importing: /<path to .m3u>/<album name>.m3u` (with the appropriate path and album name) with the spinning icon indicating it's busy on the status line until Gerbera is stopped.  If I then restart Gerbera and tell it to import again, it will typically add one more track and then hang on the .m3u file again.

Gerbera also has to be force-stopped when I shutdown or try to restart it once it has hung like this.  It still streams music just fine in this state.

I only started ripping CDs again about a week ago, so I'm not sure how long this problem has existed (it was fine about 6 months ago, the last time I did any ripping).  FYI, I'm running Kubuntu 21.10 now (6 months ago I was on 21.04).

Additional info:  I'm using the SQLite database, not MySQL.

**Comment by whyman** [comment]
Thanks for the report!

Can you run gerbera with `--debug` and provide us the log file when you attempt the import?

Thanks!

**Comment by jonathanrwatts** [comment]
I have Gerbera setup to run in daemon mode through `systemd` (so the config file is in `/etc/gerbera` and the database is in `/var/lib/gerbera`).  How do I start it with `--debug`, and where will the log file be located?

**Comment by jwatzk** [comment]
I saw this behaviour too, but usually i do not use m3u files and so i removed them.

**Comment by KarlStraussberger** [comment]
> I have Gerbera setup to run in daemon mode through `systemd` (so the config file is in `/etc/gerbera` and the database is in `/var/lib/gerbera`).  How do I start it with `--debug`, and where will the log file be located?

Stop gerbera service. Copy the command from the systemd unit file and run it from command line also adding `-l /tmp/gerbera-debug.log`. You may have to change permissions on files in `/etc/gerbera`. Other option: tweak the unit file.

**Comment by jonathanrwatts** [comment]
Okay, I modified the systemd unit file to log debug info, restarted gerbera, then removed an album (Adele's 21) and re-added it.  Here's the logfile:  [https://drive.google.com/file/d/1iw3MOn6wrv5DEE5B5Iy2MtIUUD__YAaq/view?usp=sharing](url)

One thing I noticed is that if I manually add _just_ the .m3u file by itself, it seems to work just fine.  It's only when I try to add the entire directory at once that it gets stuck.

**Comment by KarlStraussberger** [comment]
I cannot see any line indicating a playlist entry being created.

Can you please exchange you common.js file by the one attached and rerun your test in hope for some more printouts.

[common.zip](https://github.com/gerbera/gerbera/files/7747128/common.zip)

**Comment by KarlStraussberger** [comment]
I suppose I got hold of the problem: Double locking of a mutex in case of new directory with playlist, where the playlist is added before all files are done.

Can you try #2344

**Comment by jonathanrwatts** [comment]
Sorry I didn't get around to trying the alternate `common.js`; things have been a bit hectic with the holidays.  I'm afraid I'm not very familiar with GitHub, so you'll have to explain how to try #2344 (I've just been using the `debian-git` repository for updates)....

**Comment by KarlStraussberger** [comment]
I just merged the change - no big deal - so you can test the debian package.

**Comment by whyman** [comment]
I wonder if we should build the Debian packages for PRs, but just not push them, then the debs can be downloaded as CI artifacts

**Comment by KarlStraussberger** [comment]
Would be an idea for the more recent deb releases. (Folks still on 18.04 don't tend to run test software.)

I don't know how this impacts our total build performance.

**Comment by jonathanrwatts** [comment]
Just did a quick test with v1.9.2-283-g386dc1fd, and was able to add 2 albums with .m3u playlists successfully (including Adele's 21, the one I've been testing with).  Looks good!

**Comment by KarlStraussberger** [comment]
Thank you for confirming.
