### ISSUE TITLE
Version number when building from git is misleading

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#2342]
Took me a while to figure out that gerbera v1.9.2-135-gad0c9e13 (as reported by `gerbera --version`) actually points to git commit ad0c9e13.

What is the extra `g` for?

**Comment by KarlStraussberger** [comment]
g is for git. That's what git returns and is supplemented by the commit number for easier identification. Which is the main goal here - allow identification without further work-

**Comment by whyman** [comment]
Yeah, this is the output of `git describe`

> The "g" prefix stands for "git" and is used to allow describing the version of a software depending on the SCM the software is managed with. This is useful in an environment where people may use different SCMs.

https://git-scm.com/docs/git-describe#_examples
