### ISSUE TITLE
systemd script problem

### ISSUE THREAD

**Issue by Menion2k** [gerbera/gerbera#235]
Hi all
There is a problem with the systemd script included in the PPA repository
For granting the root privileges in the pre-post Exec, the "+" syntax is used (together the -)

> ExecStartPre=-+/sbin/route add -net 239.0.0.0 netmask 255.0.0.0 $MT_INTERFACE
ExecStartPre=-+/sbin/ifconfig $MT_INTERFACE allmulti

But, even if this should be correct, for some reason it prompt an error:

```
journalctl -u gerbera.service -b
gen 12 12:28:44 orangepipc2 systemd[1]: [/lib/systemd/system/gerbera.service:11] Executable path is not absolute, ignoring: -+/sbin/route add -net 239
gen 12 12:28:44 orangepipc2 systemd[1]: [/lib/systemd/system/gerbera.service:12] Executable path is not absolute, ignoring: -+/sbin/ifconfig $MT_INTER
ge
```
For the moment I have removed the -+ and used

`PermissionsStartOnly=true`

It is ok, since so far there is no "ExecReload", what is not clear to me is the reason of the error in systemctl

**Comment by v00d00** [comment]
One for @stephen-czetty.

**Comment by v00d00** [comment]
I'm going to close this as there is not much we can do with it, I would recommend trying the systemd file we ship in the git repo.
