### ISSUE TITLE
SAT>IP URL support

### ISSUE THREAD

**Issue by retrofan1979** [gerbera/gerbera#2357]
Hi, when trying to add an external SAT>IP url to Gerbera, it skips all the text after the & sign, so the URL cannot be played with DLNA devices.

Example:
http://xxx.xxx.x.xxx/?freq=370&msys=dvbc&sr=6900&mtype=256qam&pids=0,16,17,20,5900,5901,6001,5911
Will be:
http://xxx.xxx.x.xxx/?freq=370

Please add support for & sign so it will be recognized by Gerbera. Thank you!

**Comment by retrofan1979** [comment]
![image](https://user-images.githubusercontent.com/30625590/147819757-f815560b-dfb5-4547-b010-1204e3b17a8d.png)

**Comment by retrofan1979** [comment]
![image](https://user-images.githubusercontent.com/30625590/147819838-0e5164cb-8a0b-47a2-b579-98650ebe3587.png)

Removed the ip-address.

**Comment by whyman** [comment]
Thanks for the report.

It looks like you are using a really old version of Gerbera. Can you try it with 1.9.2?

**Comment by retrofan1979** [comment]
You mean with cloning from Github? I will try later this day, thanks!
I got this version from default repository for Raspberry Pi 4.

**Comment by whyman** [comment]
I tried it just now on my git build and it seems to work as expected:

![image](https://user-images.githubusercontent.com/345034/147825228-a3630399-163c-4d22-8ec3-b25460b90f42.png)

**Comment by retrofan1979** [comment]
O, that's sounds great!
I tried to compile Gerbera 1.9.2. but I have Cmake 3.16 and it requires 3.18.
Tried to update on Pi4, but without luck until now.

**Comment by retrofan1979** [comment]
Maybe 1.9.2 is somewhere around already compiled for Raspberry Pi?

**Comment by whyman** [comment]
I think it's available over at deb-multimedia

**Comment by retrofan1979** [comment]
I tried some packages from there indeed, but which one should I pick? I use buster armhf. It all ends up with errors.

**Comment by ingo-h** [comment]
@retrofan1979 You may ask a question at https://raspberrypi.stackexchange.com/ ?

**Comment by retrofan1979** [comment]
Thanks, but no thanks. I now know it's fixed in a newer version of Gerbera. I don't need it atm.
