### ISSUE TITLE
Search does not respect ContainerID

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#2364]
Another search issue.

Gerbera v1.9.2-290-g1ec9b7ce
Hi-Fi Cast v1.127

It looks like the ContainerID of the Search action is not being respected.

Hi-Fi Cast is generating a search with the following parameters.
> 2022-01-03 14:20:08.729  debug: [upnp_cds.cc:171] doSearch(): Search received parameters: ContainerID [83] SearchCriteria [upnp:class derivedfrom "object.item.audioItem.musicTrack"] StartingIndex [0] RequestedCount [30] RequestedCount [30]

It is attempting to a get a list of all tracks in a given container. In this case, an album that was marked as searchable upon import.

Gerbera converts the search to the follow query.
> 2022-01-03 14:20:08.729  debug: [sql_database.cc:1029] search(): Search count resolves to SQL [SELECT COUNT(DISTINCT "c"."id") FROM "mt_cds_object" "c" INNER JOIN "mt_metadata" "m" ON "c"."id" = "m"."item_id" INNER JOIN "grb_cds_resource" "re" ON "c"."id" = "re"."item_id" WHERE (LOWER("c"."upnp_class") LIKE LOWER('object.item.audioItem.musicTrack%')) AND ("c"."flags" & 2 = 2 OR "c"."object_type" != 1)]

This returns all the entries in the database since the ContainerID was not respected.

Gerbera should be mapping ContainerID to parent_id but its more complicated than that.

In my DB, ContainerID 83 points to a virtual item. The album which was marked searchable.
![image](https://user-images.githubusercontent.com/6924622/147983400-dd779875-049f-465e-a119-d97c219a8bb3.png)
But it only contains virtual objects that reference the actual track items.
![image](https://user-images.githubusercontent.com/6924622/147983580-6ce8d78d-923f-4590-a344-0003e2a57b98.png)

The actual tracks have a parent_id of 80
![image](https://user-images.githubusercontent.com/6924622/147983678-9cab2584-d945-46a1-8031-7f840b69f1ec.png)
which is the ID of the physical container
![image](https://user-images.githubusercontent.com/6924622/147983719-dc03821f-86b6-49fa-a26c-f70e50f71d4b.png)

**Comment by KarlStraussberger** [comment]
Thank you for reporting and investigating.

I'm quite sure the sql statement to solve this issue is really complicated.

Actually, search is running on physical items because they carry all the metadata etc. So we need to filter the result set by the virtual tree.

**Comment by mill1000** [comment]
Apparently SQL supports recursive queries. Took a few attempts but I think I've found a query that might be workable for searching any container.

The basic structure looks like this
```sql
WITH containers AS (SELECT id, ref_id, parent_id, location FROM mt_cds_object WHERE parent_id = <containerID>

UNION ALL

SELECT o.id, o.ref_id, o.parent_id, o.location FROM mt_cds_object AS o INNER JOIN containers AS c ON o.parent_id = c.id
)
SELECT * FROM containers c LEFT JOIN mt_cds_object AS o ON c.ref_id = o.id 
-- Apply search parameters here likely
WHERE (LOWER(o.upnp_class) LIKE LOWER('object.item.audioItem.musicTrack%')) 
```

Might take a bit to work it into the code.

**Comment by mill1000** [comment]
Here's a more fleshed out version that properly handles a container with physical or virtual items.
```sql
-- Find all children of parent_id
WITH containers AS (SELECT * FROM mt_cds_object WHERE parent_id = 85
UNION
SELECT o.* FROM mt_cds_object AS o JOIN containers AS c ON o.parent_id = c.id
),
-- Find all physical items and de-reference any virtual item (i.e. follow ref-id)
items AS (SELECT * from containers AS c WHERE ref_id IS NULL
UNION
SELECT o.* FROM containers AS c JOIN mt_cds_object AS o ON c.ref_id = o.id
) 
-- Filter items as you would
SELECT * FROM items AS i
WHERE (LOWER("i"."upnp_class") LIKE LOWER('object.item.audioItem.musicTrack%')) AND ("i"."flags" & 2 = 2 OR "i"."object_type" != 1)
```

**Comment by KarlStraussberger** [comment]
That's really great. Only awaiting time to be included in code base.
