### ISSUE TITLE
Tracks get skipped 

### ISSUE THREAD

**Issue by braveheuel** [gerbera/gerbera#2373]
Hello!

I am running Gerbera (1.9.2-bullseye1) on a Debian Bullseye server.
When I try to play a directory with my EasyOne IP-R1 media player, it skips every second track. E.g first "01-Intro" is finished, in the player it shows shortly that it plays "02-Second" track, but then immediately jumps to track "03-third" track. The third track is then played correctly. The fourth track then is skipped again and track five is playing fine.
The funny thing is, if I manually jump back to the track (which was skipped), it plays fine.
This is very annoying if you want to hear an audiobook.
The player is running fine with other media server (I tried, for example, minidlna).
I tried to catch some debug output for this case.

Is there anything known like this? Can I do something about this?
[jumping-tracks.log](https://github.com/gerbera/gerbera/files/7806988/jumping-tracks.log)

**Comment by KarlStraussberger** [comment]
Thank you for your report.

I cannot see any issue from the log.

We recently fixed some issues with iradio based devices. If you are able to build yourself or run the latest docker image, you may try to enable the clients flag for iradio. See https://docs.gerbera.io/en/latest/config-clients.html

**Comment by braveheuel** [comment]
Thanks for the fast response.

I have now tried out the -git-Version for Debian Bullseye (v1.9.2-299-g9d23b5b7) and added the client configuration:

```
  <clients enabled="true">
          <client ip="192.168.1.118" flags="0x08"></client>
  </clients>
```

and also `flags="IRADIO"`. Still no luck, every second track is skipped.

I am not sure if the configuration flag is taken, as the debug log just says:

```
Jan 04 17:40:05 arthur gerbera[494541]: 2022-01-04 17:40:05.334  debug: [upnp_clients.cc:182] getInfo(): client info: 192.168.1.118:55282 'FSL DLNADOC/1.50 UPnP Stack/1.0' -> 'Manual Setup for IP 192.168.1.118' as None
```
were I would not expect "None". Is that correct when I set the flag?

What I've noticed in the logs: The Agent String for the same device seems to change every now and then:

```
Jan 04 17:40:01 arthur gerbera[494541]: 2022-01-04 17:40:01.860  debug: [upnp_clients.cc:182] getInfo(): client info: 192.168.1.118:54350 'FSL DLNADOC/1.50 UPnP Stack/1.0' -> 'Manual Setup for IP 192.168.1.118' as None
Jan 04 17:40:02 arthur gerbera[494541]: 2022-01-04 17:40:02.362  debug: [upnp_clients.cc:182] getInfo(): client info: 192.168.1.118:50051 'NSPlayer/8.0.0.3801' -> 'Manual Setup for IP 192.168.1.118' as None
Jan 04 17:40:02 arthur gerbera[494541]: 2022-01-04 17:40:02.895  debug: [upnp_clients.cc:182] getInfo(): client info: 192.168.1.118:50052 'NSPlayer/8.0.0.3801' -> 'Manual Setup for IP 192.168.1.118' as None
Jan 04 17:40:05 arthur gerbera[494541]: 2022-01-04 17:40:05.334  debug: [upnp_clients.cc:182] getInfo(): client info: 192.168.1.118:55282 'FSL DLNADOC/1.50 UPnP Stack/1.0' -> 'Manual Setup for IP 192.168.1.118' as None
```

One time it is "NSPlayer/8.0.0.3801", the other time it is "FSL DLNADOC/1.50 UPnP Stack/1.0".
Might that harm?

**Comment by KarlStraussberger** [comment]
It's quite normal that player report different Agents on browse and play requests - the rely on multiple libraries. That's why configuration by IP becomes necessary to handle everything with the same extension.

Your issue sounds really strange to me, so we need to investigate a bit deeper:
- Try to increase alive interval (https://docs.gerbera.io/en/stable/config-server.html#alive). Eg. Sony PS 4 gets annoyed by the SSDP packet
- Try to capture a bit of the network traffic when it's time for the "second" track

**Comment by braveheuel** [comment]
The issue seemed also really strange to me. I've also reset and also hard resetted the media player, but the error still occured.

Increasing the alive interval seems to fix this issue. I've tried several folders and it didn't occur for now.

Thanks for your fast help @KarlStraussberger!

Closing the issue
