### ISSUE TITLE
Transcoding is not being started for particular device

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#2380]
I have a section like this in my config to differentiate between two particular devices:

```
  <clients enabled="yes">
    <client userAgent="DLNADOC/1.50 SEC_HHP_[TV] SAMTV7/1.0 UPnP/1.0"
            flags="SAMSUNG|SAMSUNG_BOOKMARK_MSEC|0x100"></client>
    <client userAgent="INTEL_NMPR/2.1 DLNADOC/1.50 dma/3.0 alphanetworks"
            flags="0x200"></client>
  </clients>
```

Then, I have transcoding profile bound to the first device only like this:

```
  <transcoding enabled="yes">
    <mimetype-profile-mappings allow-unused="yes">
      <transcode mimetype="video/x-msvideo" using="ffmpeg"/>
    </mimetype-profile-mappings>
    <profiles allow-unused="yes">
      <profile name="ffmpeg" enabled="yes" type="external" client-flags="0x100">
        <mimetype>video/mpeg</mimetype>
        <accept-url>yes</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>yes</accept-ogg-theora>
        <agent command="ffmpeg" arguments="-y -i %in -f mpeg -qscale 0 %out"/>
        <buffer size="14400000" chunk-size="512000" fill-size="120000"/>
      </profile>
    </profiles>
  </transcoding>
```

Now, this setup works as expected and the first device gets transcoded content, while the second device receives original content.

To debug another transcoding issue (#2377) I've changed one line of transcoding profile and removed `client-flags`:

```
      <profile name="ffmpeg" enabled="yes" type="external">
```

I expected that now both devices should receive transcoded content. However, only the first device gets transcoded content. The second device gets original content. For the second device, no transcoding process is started and I can see that the content is original (for example, I can seek which I can't do with transcoded content).

What could be the problem?

**Comment by KarlStraussberger** [comment]
I cannot see any obvious issue. My first guess would be `mimetype` which my be unsupport on your device. You may also try to supply a `dlna-profile` like `AVC_MP4_EU` in case your player get's confused by mimetype `mpeg` in conjunction with `AVI` as profile.

**Comment by whyman** [comment]
We send both the transcoded stream and the non-transcoded stream as resources to the clients, so I guess yours is picking the one it prefers.

You can [hide the original resource](https://docs.gerbera.io/en/stable/transcoding.html#hiding-original-resource), if you want.

**Comment by KarlStraussberger** [comment]
With the latest head we now support filtering by device and codec. Maybe you can give that a try?

**Comment by kyak** [comment]
One quick question. There is now `client-flags` setting in both `profile` and `transcode` sections. It is not clear where is the best place to specify `client-flags` because there is a one-to-one relation between `profile` and `transcode`. So `client-flags` should only be specified in one of there, but not both.

**Comment by KarlStraussberger** [comment]
It's available in both and does the same. You should use it in transcodw section. It may be removed from profile.

**Comment by kyak** [comment]
I guess I won't open a separate issue for that.

So far I haven't changed my gerbera config, just upgraded from 6ef0648b to ff1d37e8.

I have only one active transcoding profile for `video/x-msvideo`:

      <transcode mimetype="video/x-msvideo" using="ffmpeg" />

What I observe now is that transcoding kicks in for files that are definitely not `video/x-msvideo` (e.g. x264/.mkv files).

I'm hesitant to change anything else and try out your new filter settings until I figure out this regression.

**Comment by KarlStraussberger** [comment]
Your observation was quite correct. Forgot to add the check for the mimetype again (after testing for the dlna profile) ☹️
Sorry for the inconvenience - thanks for reporting.

**Comment by kyak** [comment]
I have troubles understanding this section of documention: https://docs.gerbera.io/en/stable/config-import.html?#contenttype-dlnaprofile

For example, I have an `.mkv` file, with mimetype of `video/x-matroska`, sec:acodec is `aac`, sec:vcodec is `hevc`.

From documenation, it looks like I need something like this:

```
<contenttype-dlnaprofile>
	<map from="mkv-hevc-aac" to="WHAT DO I PUT HERE"/>
</contenttype-dlnaprofile>
```

Is it some arbitraty string that I put to `<map to= ...`, and then use this in `source-profile`?

**Comment by KarlStraussberger** [comment]
You can chose from (valid DLNA profiles found in some other place, hopefully understood by your devices)
- AVC_MKV_MP_HD_AAC_MULT5
- AVC_MKV_MP_HD_AC3
- AVC_MKV_MP_HD_MPEG1_L3
- AVC_MKV_HP_HD_AAC_MULT5
- AVC_MKV_HP_HD_AC3
- AVC_MKV_HP_HD_MPEG1_L3
- AVC_MKV_MP_HD_DTS
- AVC_MKV_MP_HD_EAC3
- AVC_MKV_HP_HD_DTS
- AVC_MKV_HP_HD_EAC3
- AVC_MKV_HP_HD_MLP

This is also the value to use for `source-profile`

**Comment by kyak** [comment]
It looks like my transcoding profile indeed has some effect; it's just that transcoding doesn't start. Matching by the IP didn't change anything. But running with `--debug` revealed something interesting.

Here is how the XML resource looks like for a supported mkv file encoded with x264/aac, which is completely supported by the device and plays fine:

`<res bitrate="441183" duration="0:11:06.552" nrAudioChannels="2" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_PN=MKV;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01700000000000000000000000000000" resolution="1280x720" sampleFrequency="44100" sec:acodec="aac" sec:vcodec="h264" size="294071609">http://192.168.1.2:49152/content/media/object_id/15242/res_id/0/group/default/ext/file.mkv</res>
`

And here is the XML resource for the transcoded content, which is originally the mkv file encoded with hevc/aac. This is how I figured out that the transcoding profile indeed does something (at least I can clearly see that I can affect the resource by manipulating profile):


`<res duration="0:11:17.627" nrAudioChannels="2" protocolInfo="http-get:*:video/x-matroska;rate=1411200;channels=2:DLNA.ORG_PN=MKV;DLNA.ORG_OP=00;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=01700000000000000000000000000000" sampleFrequency="1411200">http://192.168.1.2:49152/content/media/object_id/15350/res_id/none/group/default/pr_name/hevc/tr/1/ext/file.mkv</res>`

In this case, I deliberately set the encoding profile to specify `<mimetype>video/x-matroska</mimetype>` . But I also tried other mimetypes and I can see that it affects the resulting resource string in XML.

One big difference is that the transcoded resource doesn't specify audio and video codec, unlike the supported resource example shown above.

Could it be that my device simply doesn't support resource that doesn't specify audio and video codec?

**Comment by kyak** [comment]
> It's more likely that it does not support `DLNA.ORG_OP=00;DLNA.ORG_CI=1` -> no pausing and transcoded

Should I play around and try to change these flags to see how it works for this device? Or is there a better alternative?

**Comment by KarlStraussberger** [comment]
If you want to do some try and error development, feel free!

**Comment by kyak** [comment]
And it started to work after I have switched to libnpupnp from libupnp.

I made some minor changes to config, too (like making sure ffmpeg command line was correct), but I don't think it is related. I can confirm that codec and device filtering work.

I could try switching back to libupnp to double check, but frankly I'd rather not do it.

Thanks Karl and gerbera devs!
