### ISSUE TITLE
Web Error: 400 no session id given

### ISSUE THREAD

**Issue by ferrvittorio** [gerbera/gerbera#2392]
Hi, how to troubleshoot 
`2022-01-27 17:13:50 warning: Web Error: 400 no session id given`

Cannot access to web UI

**Comment by KarlStraussberger** [comment]
Can you be so kind to tell us your gerbera version, operating system and browser.

**Comment by ferrvittorio** [comment]
Hi,
I have respectively
`Gerbera v1.9.2-311-gc8820a86`
and
`Linux desktop 5.4.173-1-MANJARO #1 SMP PREEMPT Thu Jan 20 09:45:52 UTC 2022 x86_64 GNU/Linux`
and
`Chrome Versione 97.0.4692.99 (Build ufficiale) (a 64 bit)`

I tried to set "thumbnails=on" in config file and then web ui got broken, gerbera server seems to work fine across my internal network (= smart tv can see directories, see files, ask for video streams)

`[aaa@desktop ~]$ gerbera
2022-01-28 09:29:05   info: Gerbera UPnP Server v1.9.2-311-gc8820a86 - http://gerbera.io/
2022-01-28 09:29:05   info: Copyright 2016-2021 Gerbera Contributors.
2022-01-28 09:29:05   info: Gerbera is free software, covered by the GNU General Public License version 2
2022-01-28 09:29:05   info: Loading configuration from: /home/aaa/.config/gerbera/config.xml
2022-01-28 09:29:05   info: Checking configuration...
2022-01-28 09:29:05   info: Configuration check succeeded.
2022-01-28 09:29:05   info: Loading 0 configuration items from database
2022-01-28 09:29:05   info: Loading autoscan location: /home/aaa/Pubblici; recursive: true, last_modified: 2022-01-27 16:12:06
2022-01-28 09:29:05   info: Initialising UPnP with interface: <unset>, port: <unset>
2022-01-28 09:29:05   info: IPv4: Server bound to: 192.168.1.33:49152
2022-01-28 09:29:05   info: IPv6: Server bound to: fe80::9b1c:e11f:320c:259c:49152
2022-01-28 09:29:05   info: IPv6 ULA/GLA: Server bound to: :49153
2022-01-28 09:29:05   info: Will send UPnP Alive advertisements every 60 seconds
2022-01-28 09:29:05   info: The Web UI can be reached by following this link: http://192.168.1.33:49152
2022-01-28 09:29:26 warning: Web Error: 400 no session id given
2022-01-28 09:29:26 warning: Web Error: 400 no session id given
`

**Comment by KarlStraussberger** [comment]
You mean, you added `show-thumbnail="yes"` to the section `ui` in the config file :smile:

Your output is from the backend, so we can try two things
- run gerbera ui in an incognito Chrome window to avoid any caching issue
- look at the web console in Chrome (e.g. press F12 key) in case of some scripting issue.

**Comment by Gedeon90** [comment]
I can confirm the same issue with Chrome  97.0.4692.99
However no issues if I connect from Edge  97.0.1072.76

**Comment by KarlStraussberger** [comment]
Can you please share the output from your web console?

**Comment by Gedeon90** [comment]
I've reload the pages with Ctrl+f5 and no issues right now. Console seems totally clean.
I guess you're right about some caching issue.

Sorry about the confusion

**Comment by whyman** [comment]
Possibly could be a conflict with the cookie SID similar to https://github.com/gerbera/gerbera/issues/2058

**Comment by KarlStraussberger** [comment]
I doubt that any other site uses `GerberaSID`. :smile:

Are you calling the site by ip or hostname?

**Comment by Gedeon90** [comment]
By IP, but It could be related with accesing the server in a docker before/after a quick restart, so the cookie isn't totally reliable between very first startup and next ones.

**Comment by ferrvittorio** [comment]
Hi.
I honestly worked around by uninstalling "gerbera-git (aur)" and switching to "gerbera (community)"
Not useful for troubleshooting, but helpful for solving my problem fast

:)

![Istantanea_2022-02-02_08-15-24](https://user-images.githubusercontent.com/22936074/152110551-510b0417-c6d9-4ab3-b9d0-1c7f50152146.png)

**Comment by KarlStraussberger** [comment]
If you restart the server the cookie is not valid anymore. You need to refresh the web page to get a new cookie!

**Comment by Hospes** [comment]
I'm osrry but I'm having the same issue. And f5 is not helping. Also it's just saying:
```
no session id token
```
![Screenshot 2022-09-18 224843](https://user-images.githubusercontent.com/3521464/190925681-fed33344-f394-4b57-86cf-5d9fce845682.png)

I have installed latest 1.11.0 on Ubuntu 20.04
![Screenshot 2022-09-18 224933](https://user-images.githubusercontent.com/3521464/190925705-94fdba30-e7b5-4d52-942f-0f2e254765c1.png)

**Comment by KarlStraussberger** [comment]
Did you try incognito mode in case of stale caches?

**Comment by Hospes** [comment]
> Did you try incognito mode in case of stale caches?

Yes, I've tried it. Also I've tried another browser, but nothing works for me :(

**Comment by KarlStraussberger** [comment]
> > Did you try incognito mode in case of stale caches?
> 
> Yes, I've tried it. Also I've tried another browser, but nothing works for me :(

@Hospes
From another issue I deduce the question: did you update from an older version from another source?

**Comment by Hospes** [comment]
@KarlStraussberger 
i'm using your ubuntu repository, so yeah I've updated from old version. I don't remember what version was previously installed, but last updated was before 24 February.
Interesting thing that service actually working, except of webui 😄

**Comment by KarlStraussberger** [comment]
@Hospes That might be because your old installation was in `/usr/` and ours is in `/usr/local`. You need to check or set `<webroot>` in `config.xml`

**Comment by Hospes** [comment]
I already have it
![Screenshot 2022-10-04 113536](https://user-images.githubusercontent.com/3521464/193773730-27905eed-f4d1-476f-9ee9-852821ad0e22.png)

**Comment by KarlStraussberger** [comment]
Did you clean out the contents of `/usr/share/gerbera/`?
Are the contents of `/usr/local/share/gerbera` readable by the service user and match the stuff from 1.11.0 tag?

**Comment by Hospes** [comment]
@KarlStraussberger you mean I should delete `/usr/share/gerbera` folder ? This folder still exists and there is some files

> Are the contents of `/usr/local/share/gerbera` readable by the service user and match the stuff from 1.11.0 tag?
Yeah this folder and included content are readable by all users in the system. What you mean match stuff from 1.11.0 tag ?

**Comment by KarlStraussberger** [comment]
> Yeah this folder and included content are readable by all users in the system. What you mean match stuff from 1.11.0 tag ?

Do all files match: https://github.com/gerbera/gerbera/tree/v1.11.0/web

**Comment by Hospes** [comment]
@KarlStraussberger yeah I've checked subfolders and seems like all files exists

**Comment by KarlStraussberger** [comment]
That leaves me with a lot of question marks and no answers! 🧠

**Comment by Hospes** [comment]
@KarlStraussberger I'm sorry just don't know what info can help you 😄 
Anyway it's just fine I can use it as is right now hope next update will fix when new package will update file maybe that's gonna help. Service is working and even more with last update I finnally see thumbnails on my TV 🎉  so I don't really care about UI actually. I've just set folders to autoscan in config file. Anyway thank you for your time. 🍻
