### ISSUE TITLE
Add seek support for transcoded media

### ISSUE THREAD

**Issue by nroach44** [gerbera/gerbera#240]
I'm not sure of the specifics, but it appears some users on the old Mediatomb forum managed to get MT to report to the script the time that the transcoding should skip to.

https://sourceforge.net/p/mediatomb/discussion/440750/thread/b5651334/
and
https://sourceforge.net/p/mediatomb/discussion/773778/thread/b9c7f9e0/?limit=25#64c1

Is it possible this can get added in at some point?

**Comment by lyallp** [comment]
My LG TV is unable to do seek on mkv files. Every time I try seek, the video restarts from the beginning. Pausing is fine.
I am unsure if this is a config issue or a bug.
Seek works on m4v and I could swear it used to work in Mediatomb.
Suggestions on where to look welcomed! :)

**Comment by elmodaddyb** [comment]
@lyallp - I think the way **seek** works with UPNP is that the renderer client sends the `# of bytes` as a request header to advance on the file it is playing.  We would have to see if the `# bytes to seek` is translated somehow to the transcoded position on the original file.

Gerbera DEBUG mode may reveal(_i didnt check_) the incoming request from the UPNP renderer client, but likely you'll need to wireshark the data to/from the endpoints.

**Comment by lyallp** [comment]
@elmodaddyb - I ran gerbera with debug and it appears that mkv is being transcoded using ffmpeg.
It appears mkv (via mappings below), ends up being transcoded by my video2mpeg config...
```
    <mappings>
      <extension-mimetype ignore-unknown="no">
...snip...
        <map from="mka" to="audio/x-matroska"/>
        <map from="mkv" to="video/x-matroska"/>
...snip...
```

```
     <profile name="video2mpeg" enabled="yes" type="external">
        <mimetype>video/mpeg</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <hide-original-resource>yes</hide-original-resource>
        <accept-ogg-theora>yes</accept-ogg-theora>
        <sample-frequency>48000</sample-frequency>
        <audio-channels>2</audio-channels>
        <agent command="ffmpeg" arguments="-i %in -vcodec mpeg2video -b 4096k -r 25 -acodec mp2 -ab 192k -ar 48000 -ac 2 -async 1 -f dvd -threads 2 -y %out"/>
        <buffer size="10485760" chunk-size="262144" fill-size="524288"/>
      </profile>
```
I guess, mp4 files didn't need transcoding and that is why the seek worked. I find it weird that I seem to have these recollections of mkv files also having seek work... brain fade...

**Comment by lyallp** [comment]
Ignore me. I re-encoded the mkv file using the following command and seek works.

`ffmpeg -loglevel warning -i "$INPUT" -f matroska -preset slow -tune film -map_metadata -1 -vcodec libx264  -r 25 -crf 22 -ab 384k -acodec ac3 -s hd480 -metadata title="$INPUT" "$INPUT".mkv`

Ok, the mkv increased in size a little but what's a few MB to get seek/rewind! :)

**Comment by lyallp** [comment]
I am confused now, mkv files that I thought didn't work, now work. I have to investigate more, maybe it was my TV? I will update if I find anything more, but in the mean time, ignore my posts (I could delete them but I think it's better to leave them for the moment)

**Comment by lyallp** [comment]
Really weird, after a restart of gerbera and/or TV, my seek/rewind stopped working where it was working before. mkv files that I had previously successfully performed seeks on simply restart from the beginning now. I am unsure as to what the sequence of events that led to a working arrangement. 
Investigation continues...
FYI: Seek works fine in VLC.

**Comment by lyallp** [comment]
Hmm.. Changing the metadata about the video files in the UI from video/x-matroska to video/mp4 enabled seek on most mkv files, the ones that don't play I simply re-encode using the ffmpeg command shown above.
So, I tweaked my config to map mkv to video/mp4 instead of video/x-matroska, touched all my mkv files to force gerbera to rescan them and things seem to be ok so far... will report back if any additional info comes to light.

**Comment by v00d00** [comment]
It would be interesting to see the packet capture between the gerbera server and your TV for MP4 vs MKV.

**Comment by lyallp** [comment]
I have a wireshark capture between the TV and my PC, where I view 2 identical sample files.
I edited the mimetype in the Gerbera GUI to video/x-matroska and video/mp4.
I then used Smartshare on my LG TV to watch each file and attempt seeks then stopped watching immediately after the test..
The video/x-matroska file did not seek but simply restarted on each attempt.
The video/mp4 file allowed seek back and forth, multiple times.
Gzipped, it's 123MB.
[Uploaded to Dropbox.](https://www.dropbox.com/s/wubk32gl3mq304y/gerbera_to_LG_TV_2_Mkv_Files_one_as_mp4_other_as_x-matroska.pcapng.gz?dl=0)

**Comment by elmodaddyb** [comment]
@lyallp - I didnt look through your file posted, but I **did** run a scan on my computer.

> Once the movie is playing the 2 machines are in constant streaming communication over TCP with not much useful info...

When you execute a **seek** command on your media renderer, in this case your TV...it should be creating a new HTTP-GET request to the server.  The media renderer has to figure out the amount of bytes to tell the server to **seek** to (i am not clear yet how this happens).

In my case, I recorded a wireshark with the following info when i hit the FFWD button:

```
Hypertext Transfer Protocol
    GET /content/media/object_id/11/res_id/0/ext/file.mp4 HTTP/1.1\r\n
    Host: 0.0.0.0:49152\r\n
    Accept: */*\r\n
    Accept-Language: en_US\r\n
    User-Agent: VLC/3.0.0-rc2 LibVLC/3.0.0-rc2\r\n
    If-Unmodified-Since: Sat, 12 Sep 2015 06:02:46 GMT\r\n
    Range: bytes=3045410-\r\n
    \r\n
    [Full request URI: http://0.0.0.0:49152/content/media/object_id/11/res_id/0/ext/file.mp4]
    [HTTP request 1/1]
```

The key here, I think is the `Range: bytes=3045410-\r\n` header which i think is the seek offset (_just guessing_)

If you have ability to debug the gerbera source you could add a logger line to the `UpnpVirtualDir_set_SeekCallback` method in [`server.cc`](https://github.com/gerbera/gerbera/blob/master/src/server.cc#L524) and see what your TV is producing....if anything.

I will try to run a MKV file and see the results.  Are these MKV files being transcoded?

**Comment by elmodaddyb** [comment]
**update** - I encoded a `video/x-matroska` file and seek works as expected from VLC media renderer.  Transcoding turned OFF.

@lyallp - did you figure out an adequate transcoding `<profile>` for MKV?

**Comment by lyallp** [comment]
I was wondering, I have a map of file suffix .mkv to mimetype video/mp4 which works.
I have no transcoding profile for mp4 so the default streaming is used, I guess.
I have a transcode profile for x-matroska to video2mpeg, which is as follows
```
    <profile name="video2mpeg" enabled="yes" type="external">
        <mimetype>video/mpeg</mimetype>
        <accept-url>yes</accept-url>
        <first-resource>yes</first-resource>
        <hide-original-resource>yes</hide-original-resource>
        <accept-ogg-theora>yes</accept-ogg-theora>
        <sample-frequency>48000</sample-frequency>
        <audio-channels>2</audio-channels>
        <agent command="ffmpeg" arguments="-i %in -vcodec mpeg2video -b 4096k -r 25 -acodec mp2 -ab 192k -ar 48000 -ac 2 -async 1 -f dvd -threads 2 -y %out"/>
        <buffer size="20971520" chunk-size="524288" fill-size="1048576"/>
	</profile>
```
Whilst this transcode works, I see no scope for sending 'seek' information to ffmpeg, hence, as an outsider looking in, I don't see transcoding supporting seek.

So, I guess I will remove the video/x-matroska transcoding profile, return the file suffix .mkv to video/x-matroska and things will continue to work without me 'fiddling' with mimetypes in the gerbera UI.

**Comment by elmodaddyb** [comment]
Great investigation!  It looks like ffmpeg can seek using `-ss` but this works in sexigesimal... not bytes ... would have to see how/if it could translate into that somehow??!

**Comment by lyallp** [comment]
ffmpeg can seek but I see no support such as %seek parameters, like %in and %out, from gerbera.

**Comment by v00d00** [comment]
@zajca are you sure you are transcoding?

**Comment by v00d00** [comment]
Closing this as it seems to be client specific, if there is something concrete we can do, please let us know!
