### ISSUE TITLE
DSD sent as PCM 352800 Hz

### ISSUE THREAD

**Issue by fandangos** [gerbera/gerbera#2401]
I've been digging this issue with DLNA and DSD for a while. 
This isn't just a Gerbera issue, other software have the same problem, including ReadyDLNA, Serviio, Tonido, Twonky, except the ancient UMS (Universal Media Server). 

I'm aware there's no guideline to streaming DSD over DLNA and Gerbera uses the safe path of sending it as audio/x-dsd, even if the content is DSF and DFF. 

The problem is that renderers like JRiver, Bubble UPnP, USB Audio Player Pro (on android) read the metadata information from the server that I'm guessing uses ffmpeg that reads on the DSF/DFF files and put out at the max PCM it has available as 352khz to output this content to DSD capable DACs.
So, DSD is converted to PCM even when it should not. 

The workaround I found was to change the profile to audio/x-dsf and to show it as *.dsf. 

With default settings DSF/DFF files are streamed as track.dsd, changing it to track.dsf forces Jriver, USB Audio Player Pro to output as DSD. 
But as I cannot read the internals of the player and as the metadata sent by the server is the same I'm not 100% sure if it's not just packing the PCM container and outputing as DSD, which Jriver is capable of with it's DSP studio. 

Here you can see an example with Bubble UPnP
<a href="https://ibb.co/mNMDwBp"><img src="https://i.ibb.co/8YSKpBk/dsd2.jpg" alt="dsd2" border="0"></a>

And as I mentioned, this isn't the case with UMS
<a href="https://ibb.co/3SQ1r2B"><img src="https://i.ibb.co/gthyjNz/dsd3.jpg" alt="dsd3" border="0"></a>

if this can be solved by the end user, please, let me know as Gerbera seems to be the most reliable DLNA media server so far.

**Comment by neheb** [comment]
I don't think Gerbera does any transcoding by default. The metadata is most definitely handled by ffmpeg as there doesn't seem to be any other available: https://github.com/gerbera/gerbera/blob/master/src/metadata/metadata_handler.cc#L115 . Note the audio part.

I don't see anything in src/metadata/ffmpeg_handler that implies transcoding.

**Comment by fandangos** [comment]
it's not transcoding, the file goes intact.

I'm not familiar with DLNA but I believe that along with mime type and other DLNA specific information there's some kind of metadata involved that is send with the file. 
That's why it's the same file but the player will play it as PCM because of this metadata sent along with the file. 

I don't have much more information to why, I can only especulate but as I showed in the screen captures, Universal Media Server is doing it correctly. 

By the way, my Denon receiver that can play DLNA over the network, does play it correctly without any modification but other players as I mentioned will not, like Jriver and USB Audio Player Pro, which I believe are the standard for playing DSD on Windows/Linux and Android, respectively.

**Comment by neheb** [comment]
you mentioned mimetype manipulations earlier. does editing config.xml work?

**Comment by KarlStraussberger** [comment]
You started out in the right place. First you need to map the extensions to different mimetypes. Then you're able to set its contenttype also which might be picked up by the dlnaprofile.

Excerpt of config.xml:
```
<extension-mimetype >
    <map from="dsd" to="audio/x-dsd"/>
    <map from="dff" to="audio/x-dsf"/>
    <map from="dsf" to="audio/x-dsf"/>
</extension-mimetype>
<mimetype-contenttype>
    <treat mimetype="audio/x-dsd" as="dsd"/>
    <treat mimetype="audio/x-dsf" as="dsf"/>
</mimetype-contenttype>
<contenttype-dlnaprofile>
    <map from="dsd" to="DSD"/>
    <map from="dsf" to="DSF"/>
</contenttype-dlnaprofile>
```

In case you do not have separate extensions, remove the above `extension-mimetype` settings completely and leave it to mime detection Calling `file --mime-type` to see what output to expect (the files have to be reimported after changing the mapping).

If dlna profile DSD does not work, there is a list at http://download.zenwalk.org/x86_64/testing/serviio-2.1/config/profiles.xml which may do the trick. Gerbera does not remap the extension depending on the content type.

Good luck

**Comment by fandangos** [comment]
The result is the same as I was getting at first.

The audio play as it should but information is wrong.

<a href="https://ibb.co/2gM0nwx"><img src="https://i.ibb.co/bzvjWxT/Screenshot-20220204-095901-Bubble-UPn-P.jpg" alt="Screenshot-20220204-095901-Bubble-UPn-P" border="0"></a>

Removing extension-mimetype result in files not showing under Audio, so no metadata at all. 

<a href="https://ibb.co/CK0MqhH"><img src="https://i.ibb.co/YBjy6pL/Screenshot-20220204-101233-Bubble-UPn-P.jpg" alt="Screenshot-20220204-101233-Bubble-UPn-P" border="0"></a>

Both ways do work and the file is played as it should, I'm considering using the last solution, no metadata at all, this will output the file as is and leave the player to not use any missinformation. 

Looking at UMS source on git, I can see that it's sending DSD as audio/x-dsf or audio/x-dff. 

https://github.com/UniversalMediaServer/UniversalMediaServer/blob/a25fdfea0643d1118641ffc5b7375b16631eb04e/src/main/external-resources/renderers/DefaultRenderer.conf

I fail to see what's causing this difference. 
If nothing else, I'll close this as I'm clueless.

**Comment by KarlStraussberger** [comment]
```
<extension-mimetype >
    <map from="dsd" to="audio/x-dsd"/>
    <map from="dff" to="audio/x-dff"/>
    <map from="dsf" to="audio/x-dsf"/>
</extension-mimetype>
<mimetype-contenttype>
    <treat mimetype="audio/x-dsd" as="dsd"/>
    <treat mimetype="audio/x-dff" as="dff"/>
    <treat mimetype="audio/x-dsf" as="dsf"/>
</mimetype-contenttype>
<contenttype-dlnaprofile>
    <map from="dsd" to="DSD"/>
    <map from="dsf" to="DSF"/>
    <map from="dff" to="DFF"/>
</contenttype-dlnaprofile>
```

You may play around with the dlna profiles.

**Comment by whyman** [comment]
So what is the sample rate of the DSF file? I assume it is not 352800Hz?

**Comment by fandangos** [comment]
Tried playing with the config.xml file without sucess. 

Not, it's not. 352800 Mhz is still under PCM specifications.

There are several DSD sample rates, normally refered to a DSD64, DSD128, DSD256 and DSD512. 
Those numbers refer to how many times it is compared to a CD sample rate. 
So DSD64 is 64 x 44100 = 2822400Hz, so 2.82Mhz. 

DSD128 is 5644800Hz, so 5.64Mhz. 
DSD256 is 11289600Hz, so 11.28Mhz
and finally DSD512 is 22579200Hz, so 22.57Mhz.

**Comment by whyman** [comment]
@fandangos Can you try the patch?

You can either build from source or try a git build docker image, or possibly we can build a deb package if thats helpful.

**Comment by fandangos** [comment]
@whyman 

I'm using Gerbera as a docker on unraid. 
So I pulled this one: `docker pull gerbera/gerbera:sha-269eb0f` (v1.9.2-322-g269eb0fd).

Does it include your patch? 
If it does:
While I'm getting `warning: Web Error: 400 no session id given` which is unrelated but just saying. 

And I can't do anything on the webui, I was able to remove the database and start refresh.

It's the same for sample rate. The only difference I see now is that tagged *.dsf files do show the metadata for the cover art, i.e. 400x300. 

But still 352Hz on Bubble UPnP. 

IF it does not: is it possible to grab a docker image ready or do I need to compile one?

**Comment by neheb** [comment]
The latter. The fix for this only recently made it in master.

**Comment by whyman** [comment]
We don't push PR builds to docker hub unfortunately, perhaps we should as we build them 😅

You can checkout the branch and do a docker build if that's an option

**Comment by fandangos** [comment]
Ok, clock, 4 hours in trying to compile it.....

How do you build with libupnp! with at least version 1.14.6 on ubuntu, 
if:
```
Package: libupnp-dev
Version: 1:1.8.4-2ubuntu2
```
is the latest version available?

I've found 1.14.2 but it's for Alpine. 
Latest for Debian is also 1.14.5 which won't satisfy the condition. 


Anyway.... IF, you have a enviroment ready to compile this PR, and could kindly provide a linux binary, I would gladly test it :)

or point me to a libupnp 1.14.6 deb and I can see how far I can go.

**Comment by KarlStraussberger** [comment]
You can find a build script under `scripts/debian` which should do the job. It downloads and build the required libs. You'd better uninstall the regular packages.

**Comment by neheb** [comment]
@fandangos https://github.com/gerbera/gerbera/pull/1868

I recommend building with libnpupnp from that PR. the libupnp wrap is quite basic and potentially broken.

**Comment by whyman** [comment]
Which architecture is your server on @fandangos? x86? Arm?

**Comment by fandangos** [comment]
@whyman x86, please, but I was actually able to compile it and run on a VM running Ubuntu.

@KarlStraussberger 
install-pupnp.sh:
`
./bootstrap: 11: autoreconf: not found
`

and build-deb.sh
`
./build-deb.sh: line 104: TZ: unbound variable
`
so I commented
`#ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone`

and it compiled and gave me a deb package which I installed.

and no luck, this isn't fixed yet:
<a href="https://ibb.co/5TqdPfR"><img src="https://i.ibb.co/D43NZSR/a05435c1-2d4d-4b62-a553-d869ab7f26a7.jpg" alt="a05435c1-2d4d-4b62-a553-d869ab7f26a7" border="0"></a>

I believe I've compiled the right branch:
`Gerbera UPnP Server v1.7.0-1016-g6b636d44`

Even changing the mime-type to .dsf still shows 8Hz.

**Comment by KarlStraussberger** [comment]
It should report `info: Gerbera UPnP Server v1.9.2-330-gaf76e8ed - http://gerbera.io/` if you ran a `git clone ...` in your VM. What's the exact `cat /etc/os-release` of that VM?

**Comment by fandangos** [comment]
hum....

I did 
`$ git clone https://github.com/whyman/gerbera.git`
and 
`$ git checkout ffmpeg-sample-rate-tweak`

and now
```
bahamut@ubuntu:~/gerbera$ git branch|grep "*"
* ffmpeg-sample-rate-tweak
```

Isn't that the branch with the PR?

**Comment by KarlStraussberger** [comment]
Your checkout should get the right code and is the reason why the version tag does not match. Fine.

Did you remove all the dev-packages of fmt, spdlog, pupnp and taglib?

Stupid question: Did you empty/remove the database before restart?

You may remove the build-deb directory and rerun the build with `build-deb.sh HEAD` which also builds other libs from code.

**Comment by fandangos** [comment]
No I have not removed the packages I installed with apt install. 

I don't have a gerbera server on this VM, I installed it just to compile Gerbera. 
I use a docker container on another server with unraid for my music. 

So, yeah, brand new database. 

I'll try to compile again with build-deb.sh HEAD as you mentioned and post the results later.

**Comment by whyman** [comment]
It might just be a logic error, can you post your debug log when you import the file? `--debug` will turn that on.

**Comment by fandangos** [comment]
when compiling with `[debug.log](https://github.com/gerbera/gerbera/files/8026846/debug.log)`

```
Scanning dependencies of target ebml
[  4%] Building CXX object CMakeFiles/ebml.dir/src/EbmlContexts.cpp.o
[ 12%] Building CXX object CMakeFiles/ebml.dir/src/EbmlCrc32.cpp.o
[ 12%] Building CXX object CMakeFiles/ebml.dir/src/EbmlDate.cpp.o
[ 16%] Building CXX object CMakeFiles/ebml.dir/src/EbmlElement.cpp.o
[ 20%] Building CXX object CMakeFiles/ebml.dir/src/EbmlDummy.cpp.o
[ 29%] Building CXX object CMakeFiles/ebml.dir/src/EbmlBinary.cpp.o
[ 29%] Building CXX object CMakeFiles/ebml.dir/src/EbmlFloat.cpp.o
[ 33%] Building CXX object CMakeFiles/ebml.dir/src/Debug.cpp.o
[ 37%] Building CXX object CMakeFiles/ebml.dir/src/EbmlHead.cpp.o
[ 41%] Building CXX object CMakeFiles/ebml.dir/src/EbmlMaster.cpp.o
[ 45%] Building CXX object CMakeFiles/ebml.dir/src/EbmlSInteger.cpp.o
[ 54%] Building CXX object CMakeFiles/ebml.dir/src/EbmlStream.cpp.o
[ 54%] Building CXX object CMakeFiles/ebml.dir/src/EbmlString.cpp.o
[ 58%] Building CXX object CMakeFiles/ebml.dir/src/EbmlSubHead.cpp.o
[ 62%] Building CXX object CMakeFiles/ebml.dir/src/EbmlUInteger.cpp.o
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp: In member function ‘virtual filepos_t libebml::EbmlString::ReadData(libebml::IOCallback&, libebml::ScopeMode)’:
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:147:41: error: ‘numeric_limits’ is not a member of ‘std’
  147 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize() + 1] : nullptr;
      |                                         ^~~~~~~~~~~~~~
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:147:67: error: expected primary-expression before ‘>’ token
  147 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize() + 1] : nullptr;
      |                                                                   ^
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:147:70: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  147 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize() + 1] : nullptr;
      |                                                                      ^~~
      |                                                                      std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlEndian.h:41,
                 from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlTypes.h:38,
                 from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlString.h:41,
                 from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:38:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:157:17: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
  157 |       delete [] Buffer;
      |                 ^~~~~~
[ 66%] Building CXX object CMakeFiles/ebml.dir/src/EbmlUnicodeString.cpp.o
make[2]: *** [CMakeFiles/ebml.dir/build.make:238: CMakeFiles/ebml.dir/src/EbmlString.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp: In member function ‘virtual filepos_t libebml::EbmlUnicodeString::ReadData(libebml::IOCallback&, libebml::ScopeMode)’:
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:312:41: error: ‘numeric_limits’ is not a member of ‘std’
  312 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize()+1] : nullptr;
      |                                         ^~~~~~~~~~~~~~
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:312:67: error: expected primary-expression before ‘>’ token
  312 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize()+1] : nullptr;
      |                                                                   ^
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:312:70: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  312 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize()+1] : nullptr;
      |                                                                      ^~~
      |                                                                      std::max
In file included from /usr/include/c++/11/algorithm:62,
                 from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlEndian.h:41,
                 from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlTypes.h:38,
                 from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlUnicodeString.h:43,
                 from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:40:
/usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
 3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
      |     ^~~
/home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:323:17: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
  323 |       delete [] Buffer;
      |                 ^~~~~~
make[2]: *** [CMakeFiles/ebml.dir/build.make:277: CMakeFiles/ebml.dir/src/EbmlUnicodeString.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/ebml.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

build again without `HEAD` argument:
```
CPackDeb Debug: Found dependency: libavcodec58 (>= 7:4.4), libavformat58 (>= 7:4.4), libavutil56 (>= 7:4.4), libc6 (>= 2.34), libcurl4 (>= 7.16.2), libebml5 (>= 1.3.4-2~), libexif12 (>= 0.6.21-1~), libffmpegthumbnailer4v5, libgcc-s1 (>= 3.0), libmagic1 (>= 5.12), libmatroska7 (>= 1.6.3), libmysqlclient21 (>= 8.0.11), libsqlite3-0 (>= 3.6.5), libstdc++6 (>= 11), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4) from output shlibs:Depends=libavcodec58 (>= 7:4.4), libavformat58 (>= 7:4.4), libavutil56 (>= 7:4.4), libc6 (>= 2.34), libcurl4 (>= 7.16.2), libebml5 (>= 1.3.4-2~), libexif12 (>= 0.6.21-1~), libffmpegthumbnailer4v5, libgcc-s1 (>= 3.0), libmagic1 (>= 5.12), libmatroska7 (>= 1.6.3), libmysqlclient21 (>= 8.0.11), libsqlite3-0 (>= 3.6.5), libstdc++6 (>= 11), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4)
CPackDeb:Debug: CPACK_TOPLEVEL_DIRECTORY          = '/home/bahamut/gerbera/scripts/debian/build-deb/_CPack_Packages/Linux/DEB'
CPackDeb:Debug: CPACK_TOPLEVEL_TAG                = 'Linux'
CPackDeb:Debug: CPACK_TEMPORARY_DIRECTORY         = '/home/bahamut/gerbera/scripts/debian/build-deb/_CPack_Packages/Linux/DEB/gerbera-v1.7.0-1016-g6b636d44-Linux'
CPackDeb:Debug: CPACK_OUTPUT_FILE_NAME            = 'gerbera_1.7.0+1016~20220206134019-impish1_amd64.deb'
CPackDeb:Debug: CPACK_OUTPUT_FILE_PATH            = '/home/bahamut/gerbera/scripts/debian/build-deb/gerbera_1.7.0+1016~20220206134019-impish1_amd64.deb'
CPackDeb:Debug: CPACK_PACKAGE_FILE_NAME           = 'gerbera-v1.7.0-1016-g6b636d44-Linux'
CPackDeb:Debug: CPACK_PACKAGE_INSTALL_DIRECTORY   = 'gerbera v1.7.0-1016-g6b636d44'
CPackDeb:Debug: CPACK_TEMPORARY_PACKAGE_FILE_NAME = '/home/bahamut/gerbera/scripts/debian/build-deb/_CPack_Packages/Linux/DEB/gerbera_1.7.0+1016~20220206134019-impish1_amd64.deb'
CPackDeb:Debug: CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION = 'ON'
CPackDeb:Debug: CPACK_DEBIAN_PACKAGE_SOURCE       = ''
CPack: - package: /home/bahamut/gerbera/scripts/debian/build-deb/gerbera_1.7.0+1016~20220206134019-impish1_amd64.deb generated.

```

debug.log attached to the comment.

**Comment by fandangos** [comment]
@whyman can you be more specific to latest? 

Should I git clone and checkout the same branch, `ffmpeg-sample-rate-tweak`?

**Comment by fandangos** [comment]
It's fixed:

<a href="https://ibb.co/Z6qjxZc"><img src="https://i.ibb.co/Gvz6RhC/dsdfix.jpg" alt="dsdfix" border="0"></a>

Good work whyman.
I haven't tested with DSD128 to 512.

But with DSD64 it works.

**Comment by neheb** [comment]
> when compiling with `HEAD`
> 
> ```
> Scanning dependencies of target ebml
> [  4%] Building CXX object CMakeFiles/ebml.dir/src/EbmlContexts.cpp.o
> [ 12%] Building CXX object CMakeFiles/ebml.dir/src/EbmlCrc32.cpp.o
> [ 12%] Building CXX object CMakeFiles/ebml.dir/src/EbmlDate.cpp.o
> [ 16%] Building CXX object CMakeFiles/ebml.dir/src/EbmlElement.cpp.o
> [ 20%] Building CXX object CMakeFiles/ebml.dir/src/EbmlDummy.cpp.o
> [ 29%] Building CXX object CMakeFiles/ebml.dir/src/EbmlBinary.cpp.o
> [ 29%] Building CXX object CMakeFiles/ebml.dir/src/EbmlFloat.cpp.o
> [ 33%] Building CXX object CMakeFiles/ebml.dir/src/Debug.cpp.o
> [ 37%] Building CXX object CMakeFiles/ebml.dir/src/EbmlHead.cpp.o
> [ 41%] Building CXX object CMakeFiles/ebml.dir/src/EbmlMaster.cpp.o
> [ 45%] Building CXX object CMakeFiles/ebml.dir/src/EbmlSInteger.cpp.o
> [ 54%] Building CXX object CMakeFiles/ebml.dir/src/EbmlStream.cpp.o
> [ 54%] Building CXX object CMakeFiles/ebml.dir/src/EbmlString.cpp.o
> [ 58%] Building CXX object CMakeFiles/ebml.dir/src/EbmlSubHead.cpp.o
> [ 62%] Building CXX object CMakeFiles/ebml.dir/src/EbmlUInteger.cpp.o
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp: In member function ‘virtual filepos_t libebml::EbmlString::ReadData(libebml::IOCallback&, libebml::ScopeMode)’:
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:147:41: error: ‘numeric_limits’ is not a member of ‘std’
>   147 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize() + 1] : nullptr;
>       |                                         ^~~~~~~~~~~~~~
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:147:67: error: expected primary-expression before ‘>’ token
>   147 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize() + 1] : nullptr;
>       |                                                                   ^
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:147:70: error: ‘::max’ has not been declared; did you mean ‘std::max’?
>   147 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize() + 1] : nullptr;
>       |                                                                      ^~~
>       |                                                                      std::max
> In file included from /usr/include/c++/11/algorithm:62,
>                  from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlEndian.h:41,
>                  from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlTypes.h:38,
>                  from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlString.h:41,
>                  from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:38:
> /usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
>  3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
>       |     ^~~
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlString.cpp:157:17: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
>   157 |       delete [] Buffer;
>       |                 ^~~~~~
> [ 66%] Building CXX object CMakeFiles/ebml.dir/src/EbmlUnicodeString.cpp.o
> make[2]: *** [CMakeFiles/ebml.dir/build.make:238: CMakeFiles/ebml.dir/src/EbmlString.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp: In member function ‘virtual filepos_t libebml::EbmlUnicodeString::ReadData(libebml::IOCallback&, libebml::ScopeMode)’:
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:312:41: error: ‘numeric_limits’ is not a member of ‘std’
>   312 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize()+1] : nullptr;
>       |                                         ^~~~~~~~~~~~~~
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:312:67: error: expected primary-expression before ‘>’ token
>   312 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize()+1] : nullptr;
>       |                                                                   ^
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:312:70: error: ‘::max’ has not been declared; did you mean ‘std::max’?
>   312 |     auto Buffer = (GetSize() + 1 < std::numeric_limits<std::size_t>::max()) ? new (std::nothrow) char[GetSize()+1] : nullptr;
>       |                                                                      ^~~
>       |                                                                      std::max
> In file included from /usr/include/c++/11/algorithm:62,
>                  from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlEndian.h:41,
>                  from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlTypes.h:38,
>                  from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/ebml/EbmlUnicodeString.h:43,
>                  from /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:40:
> /usr/include/c++/11/bits/stl_algo.h:3467:5: note: ‘std::max’ declared here
>  3467 |     max(initializer_list<_Tp> __l, _Compare __comp)
>       |     ^~~
> /home/bahamut/gerbera/scripts/debian/libebml-1.4.2/src/EbmlUnicodeString.cpp:323:17: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
>   323 |       delete [] Buffer;
>       |                 ^~~~~~
> make[2]: *** [CMakeFiles/ebml.dir/build.make:277: CMakeFiles/ebml.dir/src/EbmlUnicodeString.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/ebml.dir/all] Error 2
> make: *** [Makefile:149: all] Error 2
> ```
> 
> build again without `HEAD` argument:
> 
> ```
> CPackDeb Debug: Found dependency: libavcodec58 (>= 7:4.4), libavformat58 (>= 7:4.4), libavutil56 (>= 7:4.4), libc6 (>= 2.34), libcurl4 (>= 7.16.2), libebml5 (>= 1.3.4-2~), libexif12 (>= 0.6.21-1~), libffmpegthumbnailer4v5, libgcc-s1 (>= 3.0), libmagic1 (>= 5.12), libmatroska7 (>= 1.6.3), libmysqlclient21 (>= 8.0.11), libsqlite3-0 (>= 3.6.5), libstdc++6 (>= 11), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4) from output shlibs:Depends=libavcodec58 (>= 7:4.4), libavformat58 (>= 7:4.4), libavutil56 (>= 7:4.4), libc6 (>= 2.34), libcurl4 (>= 7.16.2), libebml5 (>= 1.3.4-2~), libexif12 (>= 0.6.21-1~), libffmpegthumbnailer4v5, libgcc-s1 (>= 3.0), libmagic1 (>= 5.12), libmatroska7 (>= 1.6.3), libmysqlclient21 (>= 8.0.11), libsqlite3-0 (>= 3.6.5), libstdc++6 (>= 11), libuuid1 (>= 2.16), zlib1g (>= 1:1.1.4)
> CPackDeb:Debug: CPACK_TOPLEVEL_DIRECTORY          = '/home/bahamut/gerbera/scripts/debian/build-deb/_CPack_Packages/Linux/DEB'
> CPackDeb:Debug: CPACK_TOPLEVEL_TAG                = 'Linux'
> CPackDeb:Debug: CPACK_TEMPORARY_DIRECTORY         = '/home/bahamut/gerbera/scripts/debian/build-deb/_CPack_Packages/Linux/DEB/gerbera-v1.7.0-1016-g6b636d44-Linux'
> CPackDeb:Debug: CPACK_OUTPUT_FILE_NAME            = 'gerbera_1.7.0+1016~20220206134019-impish1_amd64.deb'
> CPackDeb:Debug: CPACK_OUTPUT_FILE_PATH            = '/home/bahamut/gerbera/scripts/debian/build-deb/gerbera_1.7.0+1016~20220206134019-impish1_amd64.deb'
> CPackDeb:Debug: CPACK_PACKAGE_FILE_NAME           = 'gerbera-v1.7.0-1016-g6b636d44-Linux'
> CPackDeb:Debug: CPACK_PACKAGE_INSTALL_DIRECTORY   = 'gerbera v1.7.0-1016-g6b636d44'
> CPackDeb:Debug: CPACK_TEMPORARY_PACKAGE_FILE_NAME = '/home/bahamut/gerbera/scripts/debian/build-deb/_CPack_Packages/Linux/DEB/gerbera_1.7.0+1016~20220206134019-impish1_amd64.deb'
> CPackDeb:Debug: CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION = 'ON'
> CPackDeb:Debug: CPACK_DEBIAN_PACKAGE_SOURCE       = ''
> CPack: - package: /home/bahamut/gerbera/scripts/debian/build-deb/gerbera_1.7.0+1016~20220206134019-impish1_amd64.deb generated.
> ```
> 
> debug.log: `[debug.log](https://github.com/gerbera/gerbera/files/8026846/debug.log)`

Build with -DWITH_MATROSKA=OFF. libebml has a bug with GCC11. I think the meson PR is also impacted by it.

**Comment by fandangos** [comment]
Ok. 

But it's done now. 
So, if this gets merged, how long to show up in docker gerbera:gerbera? 

Can I close the issue now? There's anything else to test?

**Comment by KarlStraussberger** [comment]
Thank you for testing and confirming.

Leave it open. It get's closed automatically as soon as the PR is merged.

**Comment by fandangos** [comment]
I don't want to impose but since you are fixing DSD playback, would it be possible to add cover art support on dsf files that have embeded artwork?

or cover art support for dsd files if cover.jpg is present?

I have tested here in both scenarios there's no cover art for albums. 

Since this is a feature request, I don't think this should be made into a new open issue here.

**Comment by KarlStraussberger** [comment]
For embedded cover art we rely on taglib which would need further investigation (create new issue to track our thoughts)

For external files I recommend reading https://docs.gerbera.io/en/latest/config-import.html#resources.
