### ISSUE TITLE
Gerbera 1.9.2 update - unable to find repositories

### ISSUE THREAD

**Issue by geno11x11** [gerbera/gerbera#2418]
Having just updated my **OpenSuse LEAP 15.2** server to 15.3, I attempted to also update **Gerbera** 1.8 to 1.9.2, which is labeled as Experimental. The installation failed with the following error message:
```

**Software installation

The installation has failed. For more information, see the log file at /var/log/YaST2/y2log. Failure stage was: Adding Repositories
Error Message

An error occurred while attempting to subscribe to the required repositories. Review the yast2 logs for more information.
The following repositories could not be added
https://download.opensuse.org/repositories/SUSE:/SLE-15-SP3:/Update/
https://download.opensuse.org/repositories/SUSE:/SLE-15-SP1:/Update/pool/
https://download.opensuse.org/repositories/SUSE:/SLE-15-SP2:/GA/pool/
https://download.opensuse.org/repositories/SUSE:/SLE-15-SP2:/Update/pool/
https://download.opensuse.org/repositories/SUSE:/SLE-15-SP3:/GA/pool/
https://download.opensuse.org/repositories/SUSE:/SLE-15:/Update/pool/**
```

Using the paths listed above, I found that the URL's are indeed broken. Please update the repository URLs.

Thanks,
Geno

**Comment by KarlStraussberger** [comment]
I have to disappoint you, but SuSE packages are not maintained by the gerbera team. You need to cantact SuSE folks or the author of the package.

NB: You can try to add the repo at https://download.opensuse.org/repositories/multimedia:/apps/15.3/ manually (`zypper ar ...`)

**Comment by geno11x11** [comment]
No disappointment, I'm just am not familiar with who handles what... 

But your link **did the trick!** Gerbera is up and running.

Thanks once again!
