### ISSUE TITLE
The '--debug' arg makes the docker container to crash at startup

### ISSUE THREAD

**Issue by SmartPhoneLover** [gerbera/gerbera#2419]
Hello, I would like to report an issue when enabling the '--debug/-D' argument. If not set, the container works as expected.

The Docker container fails to start when this arg is enabled, showing the following error in terminal:
`/usr/local/bin/docker-entrypoint.sh: exec: line 26: illegal option --`

What could be the reason?

Thank you.

**Comment by fandangos** [comment]
hey @KarlStraussberger I'm the one who asked @SmartPhoneLover how to run the docker inside unraid with debug output. 

I'm having tons of crashes with Gerbera without a stout output that I need to further investigate to give a proper log. 

This is how the docker runs on unraid:
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Gerbera' --net='host' -e TZ="America/Sao_Paulo" -e HOST_OS="Unraid" -e 'TCP_PORT_49494'='49494' -e 'UDP_PORT_1900'='1900' -v '/mnt/user/MUSIC/Hi-RES/':'/content':'ro' -v '/mnt/user/appdata/gerbera/config.xml':'/var/run/gerbera/config.xml':'rw' -v '/mnt/user/appdata/gerbera':'/var/run/gerbera':'rw' 'gerbera/gerbera'`

if we add:
`root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name='Gerbera' --net='host' -e TZ="America/Sao_Paulo" -e HOST_OS="Unraid" -e 'TCP_PORT_49494'='49494' -e 'UDP_PORT_1900'='1900' -v '/mnt/user/MUSIC/Hi-RES/':'/content':'ro' -v '/mnt/user/appdata/gerbera/config.xml':'/var/run/gerbera/config.xml':'rw' -v '/mnt/user/appdata/gerbera':'/var/run/gerbera':'rw' 'gerbera/gerbera' --debug`

it gives the output mentioned in this issue. 

Do you see anything wrong in the way unraid calls the docker container?

**Comment by fandangos** [comment]
Ok, 

I'll see if I can get it to crash while debuging. 

The error that got me 3 to 5 crashes was:

`terminate called after throwing an instance of 'std::out_of_range' what(): stoi`

while scanning. 
I'll see what else I can find here.
