### ISSUE TITLE
File Listing resets scrollbar on page selection

### ISSUE THREAD

**Issue by iansebryk** [gerbera/gerbera#2447]
when you choose a page number from underneath the file listing, it resets the scrollbar to the beginning, hiding your current page.  you then have to scroll back to where you can see the highlighted page number to choose another.  where did the 'next' and 'prev' go from earlier editions??

**Comment by KarlStraussberger** [comment]
Thank you for reporting.

What version and browser are you using? Can you provide some screenshot to illustrate your issue.

**Comment by iansebryk** [comment]
no problem.  here you go:
![Gerbera-UI-issues](https://user-images.githubusercontent.com/1943574/155182260-42b7c419-b434-4a54-956c-f0cead20996b.jpg)

**Comment by KarlStraussberger** [comment]
Good that we reworked the layout on the right side, so you can change the number of items and select the grid layout which brings it all to a smaller area. 
![grafik](https://user-images.githubusercontent.com/23654788/155187304-74cf6c57-e541-4582-b442-9edaa3000c8b.png)

Anyway the issue with the scrollbar still exists.

**Comment by iansebryk** [comment]
i'll update and give it a shot. 👍  good luck, and thank you for all your work.  i'll provide feedback when this gets patched.
