### ISSUE TITLE
Release 1.10?

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#2449]
Lots of nice UI stuff gone in, decent amount of bugs squashed.

**Comment by KarlStraussberger** [comment]
I'm looking forward to this, if time allows.

**Comment by whyman** [comment]
Thanks! I was going to get to this today, but you beat me to it! Great work.

**Comment by KarlStraussberger** [comment]
> Thanks! I was going to get to this today, but you beat me to it! Great work.

I started this to calm my feelings about Ukraine. Maybe we should start dedicating releases like notepad++ (https://notepad-plus-plus.org/news/)
