### ISSUE TITLE
Docker image for 1.10.0?

### ISSUE THREAD

**Issue by ngosang** [gerbera/gerbera#2457]

**Comment by KarlStraussberger** [comment]
Should be there by now. Building takes some time

**Comment by KarlStraussberger** [comment]
https://hub.docker.com/r/gerbera/gerbera/tags?name=1.

**Comment by whyman** [comment]
Yeah, it takes some time to publish because compilng C++ under QEMU is not quick!

**Comment by ngosang** [comment]
Great release, thank you!
Gerbera has become the best UPnP media server out there.
