### ISSUE TITLE
Systemd: wrong target without MySql / NullPointer

### ISSUE THREAD

**Issue by elgorro** [gerbera/gerbera#2458]
https://github.com/gerbera/gerbera/blob/be8273cf8528a33f11f263bb64419356c9d19a54/CMakeLists.txt#L537 it should be `network-online.target` also.

> Feb 25 05:55:36 linuxkasten gerbera[1120]: 2022-02-25 05:55:36   info: Configuration check succeeded.
> Feb 25 05:55:36 linuxkasten gerbera[1120]: 2022-02-25 05:55:36   info: Loading 0 configuration items from database
> Feb 25 05:55:36 linuxkasten gerbera[1120]: 2022-02-25 05:55:36   info: Loading autoscan location: /mnt/media/musik; recursive: true, last_modified: 2020-01-26 00:>
> Feb 25 05:55:36 linuxkasten gerbera[1120]: 2022-02-25 05:55:36   info: Initialising UPnP with interface: <unset>, port: 49999
> Feb 25 05:55:37 linuxkasten gerbera[1120]: [*** LOG ERROR #0001 ***] [2022-02-25 05:55:37] [] {string pointer is null}
> Feb 25 05:55:38 linuxkasten gerbera[1120]: [*** LOG ERROR #0002 ***] [2022-02-25 05:55:38] [] {string pointer is null}
> Feb 25 05:55:40 linuxkasten gerbera[1120]: 2022-02-25 05:55:40   info: IPv4: Server bound to: :49999
> Feb 25 05:55:40 linuxkasten gerbera[1120]: 2022-02-25 05:55:40   info: IPv6: Server bound to: fe80::a1a5:5dfb:4128:ef85:49999
> Feb 25 05:55:40 linuxkasten gerbera[1120]: 2022-02-25 05:55:40   info: IPv6 ULA/GLA: Server bound to: :50000
> Feb 25 05:55:40 linuxkasten gerbera[1120]: 2022-02-25 05:55:40   info: The Web UI can be reached by following this link: http://:49999/

**Comment by KarlStraussberger** [comment]
Thank you for reporting. I think this is more a dependency on the distro than on the database service. Gerbera cannot run without network up! What's your distro?

**Comment by elgorro** [comment]
Arch 64 Bit with systemd
