### ISSUE TITLE
Gerbera Ubuntu repo is not being updated

### ISSUE THREAD

**Issue by St3ll4rM4n** [gerbera/gerbera#2468]
It looks like for some period of time Gerbera Ubuntu repo is not being updated.

It doesn't contain recent 1.10 release nor the GIT versions.

https://gerbera.jfrog.io/
curl -fsSL https://gerbera.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -
sudo apt-add-repository https://gerbera.jfrog.io/artifactory/debian

https://docs.gerbera.io/en/stable/install.html

When this can be available?

Thanks.

**Comment by whyman** [comment]
Oh interesting, the job to build those packages is not failing so I wonder what is going wrong

**Comment by jonathanrwatts** [comment]
When I go to [https://gerbera.jfrog.io/](url) I get prompted to login now, which didn't used to happen, and there seems to be no link to actually set up an account; I suspect this issue may be related....

**Comment by whyman** [comment]
Yeah, I dropped the git repo to clear some space as we were over our storage quota, but it didn't seem to help

**Comment by whyman** [comment]
Okay, the git repo should be populated with an up to date build now.

We just need to figure out how to re-run the new pipeline for an old tag if possible.
