### ISSUE TITLE
tracks in wrong order in one client

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#2480]
### Discussed in https://github.com/gerbera/gerbera/discussions/2475

<div type='discussions-op-text'>

<sup>Originally posted by **hmoffatt** March  8, 2022</sup>
I'm using Gerbera with Yamaha MusicCast devices. I find that the tracks within an album are shown in alphabetical order in the Yamaha app, not track order. However, they're shown in the right order in the Gerbera web interface, and Yamaha shows them in the correct order when I see them on an Airsonic server or Synology Media Server.

They also show up in the right order in "Bubble UPnP" on Android from the Gerbera. Just not in MusicCast.

It doesn't matter if the files are MP3 or OGG or FLAC. Even if the files have numbers in their filenames, they end up in alphabetical track name order in the MusicCast app.

Any ideas?
</div>

**Comment by hmoffatt** [comment]
I created #2479 for this with some more details.

**Comment by whyman** [comment]
So you did!
