### ISSUE TITLE
Sorting order

### ISSUE THREAD

**Issue by Dreadeath** [gerbera/gerbera#2483]
Hi, I'm not sure if my issue related to Gerbera, but after recent update to 1.10.0 I found out that sorting on my LG TVs (WebOS) has changed - now it is showing files before folders. How can I revert it? Thanks.

**Comment by whyman** [comment]
Could you possibly try a git build a sorting fix went in recently and it would be good to know if it helps here too

**Comment by Dreadeath** [comment]
I get this message when starting git build: 
error: Mysql: error while updating db: mysql_error (1050): "Table 'grb_playstatus' already exists"; query: CREATE TABLE `grb_playstatus`

**Comment by whyman** [comment]
Okay thanks for testing. Is there a way you can get is a packet capture when the TV makes the request?

**Comment by KarlStraussberger** [comment]
You can also try to run gerbera with `--debug` to get more output what's happening on our side. Look for `browse` or `search`.

**Comment by Dreadeath** [comment]
Ok, I'll try.

**Comment by KarlStraussberger** [comment]
I was unfortunate (from the point of view of the bank account) and had to get a new TV set which ended up being a LG device. I just reproduced the issue and hope it's fixes with the PR.

**Comment by whyman** [comment]
We should fundraise to buy some Samsung's 😅
