### ISSUE TITLE
Playlist items are not returned from uPNP searches

### ISSUE THREAD

**Issue by ljr55555** [gerbera/gerbera#2492]
**_Summary:_**  Playlist items are not returned from searches initiated on my uPNP client. The playlist is visible when browsing the Gerbera web UI under Playlists->All Playlists->Playlist Name and Playlists->Directories->Playlists->Playlist Name

**_Action:_** In a uPNP client, search using the criteria `upnp:class = "object.container.playlistContainer" and dc:title = "Playlist Name"`,

**_Expected Results:_**  Playlist matching search criteria is returned
**_Actual Results:_**  No results are returned

**_Investigation:_**  
From the Gerbera debug log, the search being executed is:

`SELECT DISTINCT "c"."id", "c"."ref_id", "c"."parent_id", "c"."object_type", "c"."upnp_class", "c"."dc_title", "c"."mime_type"
        , "c"."flags", "c"."part_number", "c"."track_number", "c"."location", "c"."last_modified", "c"."last_updated"
FROM "mt_cds_object" "c"
INNER JOIN "mt_metadata" "m" ON "c"."id" = "m"."item_id"
INNER JOIN "grb_cds_resource" "re" ON "c"."id" = "re"."item_id"
WHERE (LOWER("c"."upnp_class")=LOWER('object.container.playlistContainer')) AND (LOWER("c"."dc_title")=LOWER('Playlist Name'))
ORDER BY "c"."dc_title" ASC;`

The playlists do not have a row in the grb_cds_resource table, so the "INNER JOIN" means the query returns no records.

I am able to work around this issue by manually inserting playlist items into the grb_cds_resource table

`INSERT INTO grb_cds_resource (item_id, res_id, handlerType) VALUES (1235555,0,0);`

It seems like either playlist items need to be added to the grb_cds_resource table or the query should use a left outer join with grb_cds_resource.

**Comment by KarlStraussberger** [comment]
Thank you for that precise report. I'm sure that, based on your analysis, there is a solution to that problem.

**Comment by KarlStraussberger** [comment]
It's been a bit more complicated but I hope the PR solves your issue.

Backgroud: There is a searchable flag which avoids duplicate entries in virtual layout to be returned (https://docs.gerbera.io/en/stable/config-server.html#upnp).

**Comment by ljr55555** [comment]
Thanks for the quick response -- we built Gerbera from the master branch (blew away the database to start from scratch), and a quick test shows that playlists are now showing up in the search results. I've got to look at the documentation update to see about excluding some of these duplicates from the search results!

**Comment by KarlStraussberger** [comment]
Thank you for your confirmation.
