### ISSUE TITLE
Bookmark file is only readable by the user who launched Gerbera

### ISSUE THREAD

**Issue by Itrimel** [gerbera/gerbera#2493]
On my system (Arch Linux), I have configured Gerbera to run under its own user (`gerbera`).

Since the last update to v1.10.0, I can't open the bookmark file to the web session, as its permissions are set to -rw------, so itr is not readable by my personal section.

After a bit of digging in the code, the bookmark creation codes uses `GrbFile::writeTextFile`
https://github.com/gerbera/gerbera/blob/33c6a24608543d02bd98b477adf63ddbfa155e24/src/server.cc#L287-L296

 which was changed recently to add https://github.com/gerbera/gerbera/blob/33c6a24608543d02bd98b477adf63ddbfa155e24/src/util/grb_fs.cc#L151

This change seems intentional (so just changing the permissions in `writeTextFile` is maybe not right) , but at the same time I feel like the bookmark file should be readable by everyone on the system ?

**Comment by KarlStraussberger** [comment]
The bookmark file should only be used by the internal web server and is therefore hidden to every other user. Based on some code quality warnings we slightly tried to increase security

**Comment by Itrimel** [comment]
This seems to be in conflict with the documentation ?

In the server configuration, in the bookmark item, it is written that `The bookmark file offers an easy way to access the user interface, it is especially helpful when the server is not configured to run on a fixed port` .
