### ISSUE TITLE
1.9.2 - somewhere there is hardcoded value to /usr/share/gerbera/sqlite3-upgrade.xml

### ISSUE THREAD

**Issue by baranowb** [gerbera/gerbera#2501]
As per above, only way around is to create ln -s to /usr/share/gerbera from custom location.

**Comment by whyman** [comment]
Nothing should be hardcoded, you can configure the directories.

Check out for example https://docs.gerbera.io/en/stable/config-server.html#home and https://docs.gerbera.io/en/stable/config-server.html#webroot

**Comment by KarlStraussberger** [comment]
DId you already try https://docs.gerbera.io/en/stable/config-server.html#storage `upgrade-file`? I'm not sure, but it should be there in 1.9.2 already.

**Comment by KarlStraussberger** [comment]
I still try to remember whether there was an issue that the path was not taken from config or that the missing file in deployment caused trouble. So you'd best upgrade to 1.10.

**Comment by baranowb** [comment]
Will check during weekend. 1.9 is what dnf repo had and I was in a rush sort of.

**Comment by whyman** [comment]
Any news @baranowb?
