### ISSUE TITLE
Build failure with upnp 1.14 from git

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#2506]
When using pupnp branch-1.14.x (specifically, I'm using this commit: https://github.com/pupnp/pupnp/commit/90768d2f867a97294693578fc9c4e31ccea50459) gerbera (latest git) fails to build with the following:

> [ 76%] Building CXX object CMakeFiles/libgerbera.dir/src/util/upnp_headers.cc.o
/home/user/build/gerbera-git/src/util/upnp_headers.cc:29:10: fatal error: UpnpExtraHeaders.h: No such file or directory
   29 | #include <UpnpExtraHeaders.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by KarlStraussberger** [comment]
Seems your trying to build with current pupnp master which is not supported at the moment. 1.16 branch was dropped making our preparations void.

**Comment by kyak** [comment]
> Seems your trying to build with current pupnp master which is not supported at the moment. 1.16 branch was dropped making our preparations void.

I'm building with upnp branch-1.14.x, not master. I understand that you only support 1.14 release. Consider this as a heads-up that the latest 1.14 branch (not the 1.14 release) is not working.

**Comment by neheb** [comment]
upstream getting rid of UpnpExtraHeaders.h in branch-1.14x sounds weird.

**Comment by neheb** [comment]
I see. Upstream introduced this bug: https://github.com/pupnp/pupnp/commit/4dcfdba8470485d7b54a99c993808316b0d0b3cf

If you build with Automake, it should still work.

**Comment by kyak** [comment]
I have created an issue upstream.

**Comment by KarlStraussberger** [comment]
Still sounds like an issue in `libpupnp`. Gerbera does not use free directly.

**Comment by neheb** [comment]
@kyak there's also libnpupnp if needed.

**Comment by kyak** [comment]
> @kyak there's also libnpupnp if needed.

I was hesitant to try libnpupnp because gerbera uses libupnp by default and it looks almost like a recommendation from gerbera devs.

I'll check it out and see how it works with gerbera.

**Comment by kyak** [comment]
> I'll check it out and see how it works with gerbera.

And it works without problems so far, so I'll stick to libnpupnp.

I guess this issue can be closed.

**Comment by whyman** [comment]
Lets keep this open as a reminder that potentially the next release will break stuff.

**Comment by whyman** [comment]
https://github.com/pupnp/pupnp/commit/ec5ce781dac43413f026b3a070c7400aeb8e0116
