### ISSUE TITLE
gerbera looking for transcoding command for disabled profiles

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#2517]
Even if a transcoding profile is disabled,

> <profile name="vlcmpeg" **enabled="no"** type="external">

gerbera reports configuration error like this:

> error: Error in configuration, transcoding profile: could not find transcoding command "vlc" in $PATH
error: [/gerbera-git/src/config/config_setup.cc:91] std::string ConfigSetup::getXmlContent(const pugi::xml_node&, bool) Error: Invalid /config/transcoding/profiles/profile/agent/attribute::command value 'vlc'

This has to do with some recent changes and been introduced somewhere between 6ef0648b and ff1d37e8

**Comment by KarlStraussberger** [comment]
It's been a deliberate change to parse the config for disabled profile that can be enabled via web ui.

Changed behaviour so it does only warn on startup if profile is diabled.

**Comment by kyak** [comment]
Thanks, I confirm that it has now become a warning instead of an error. The message looks weird though:

"warning: Error in configuration, could not find  command "vlc" in $PATH"
