### ISSUE TITLE
Music file search fails on file names with spaces

### ISSUE THREAD

**Issue by lisa50469** [gerbera/gerbera#2519]
Music/Lenny LeBlanc/Lenny LeBlanc-There Is None Like You.mp3: No such file or directory

**Comment by KarlStraussberger** [comment]
Thank you for reporting. Can you give us some more details:
- Gerbera version?
- Operating System/Distribution version?
- What kind of autoscan type are you using?
- When did you get that message?
- Can you reproduce the message with other files as well?

**Comment by lisa50469** [comment]
Linux Ubuntu 20.04 server.
Looks like it was fixed in 1.8.2
Songs now show up that do have spaces in the names.
