### ISSUE TITLE
Gerbera 1.10.0 shows direcories with no test and are not selectable on a Loewe TV

### ISSUE THREAD

**Issue by jgeiss66** [gerbera/gerbera#2537]
The directories show no text. Selecting any of these directories has no effect.

This error does not occur on other devices like Fairphone using VLC.

Version 1.9.2 works on Loewe TV.

**Comment by jgeiss66** [comment]
This is a photo of the Loewe TV using Gerbera 1.10
![NoText](https://user-images.githubusercontent.com/51959112/161421898-df267006-6e51-4aa8-a5df-2aed15983984.jpg)
.

**Comment by jgeiss66** [comment]
This is a photo of the Loewe TV using Gerbera 1.9.2
![Text](https://user-images.githubusercontent.com/51959112/161421921-b0955dd1-15c7-4426-8f5a-5bdb8de8d0ad.jpg)
.

**Comment by jgeiss66** [comment]
This is the traffic (captures with wireshark) between Gerbera 1.10 and Loewe TV.
One text extract of this traffic shows no result
[Traffic_1.10.pcapng.gz](https://github.com/gerbera/gerbera/files/8404221/Traffic_1.10.pcapng.gz)
.

**Comment by jgeiss66** [comment]
This is the traffic (captures with wireshark) between Gerbera 1.9 and Loewe TV.
One text extract of this traffic shows one result: Adirectory named "Audio"
[Traffic_1.9.pcapng.gz](https://github.com/gerbera/gerbera/files/8404222/Traffic_1.9.pcapng.gz)
.

**Comment by whyman** [comment]
Thanks for the detailed report @jgeiss66!

**Comment by jgeiss66** [comment]
Diffing the text extracts shows a "/&amp;gt;" in the error case (1.10) and "&amp;gt;" in the good case (1.9.2).

**Comment by whyman** [comment]
How are you installing Gerbera?

**Comment by jgeiss66** [comment]
I am using Gentoo Linux. So, I use "emerge gerbera".

**Comment by whyman** [comment]
I could reproduce this on `1.10` with your payloads, thanks for providing them.

The good news is that your issue is already fixed on the master branch.

**Comment by whyman** [comment]
You might want to try applying https://github.com/gerbera/gerbera/commit/7bb7422d2d815a2ec929e88d64c360c39e577ff2 as user patch

**Comment by jgeiss66** [comment]
I tried the -9999 ebuild and it works. Thank you very much.
