### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#2539]
Seems like the composite keys fix is a pretty important one to get out.

Do we have anything more we want to include for 1.11.0?

**Comment by KarlStraussberger** [comment]
I've got some changes regarding `dc::date` (based on #2531) which we should include after #2532

**Comment by KarlStraussberger** [comment]
I already prepared the changelog two weeks ago but the flow of issues stopped me from doing the release

```
### v1.10.1

- Add Clients to database
- add throw_fmt_system_error define
- Allow agent to not exist if profile is disabled.
- bool simplifications
- Bump minimist from 1.2.5 to 1.2.6 in /gerbera-web
- CI: build-deb: Pass API key to docker env
- CI: build-deb: Pass API key to docker env, again
- clang-tidy
- clang-tidy: member function const
- clang-tidy: replace push with emplace_back
- clang-tidy: use move
- convert function to static
- doc/install.rst: add Buildroot
- doc/install.rst: drop Entware
- Ensure search sort by title
- Find DNLA profiles by resource attributes
- Fix playlist parser error
- Fix sorting by composed keys
- Fix tag matches with ffmpeg_handler
- Fix: Repair broken Mysql statements
- Improve readability of attributes
- Increase DukTape version
- pass shared_ptr by value
- Playlist: Handle end of file properly
- README: Bump required npupnp version
- Refactor handling of network addresses
- remove pointless parentheses
- remove reference parameter
- replace bzero with {}
- ResourceAttribute new style enum
- Restore friendly name in UI
- simplify some bools
- Sort containers first
- Split out URL handling methods to UrlUtils namespace
- Store Playback Status in new table
- string to string_view conversion
- Support filtering transcoding profiles
- Support parsing function for config values
- Support searching playlists containers
- ThreadRunner: Drop system-threads config
- Try to fix paths-ignore
- UI Prettier Modals, badges
- unused parameter for throw
- Update Duktape version for bookworm
- use to_integer
- WavPack: Get metadata with original library
- WebTests: Update node packages
```

**Comment by neheb** [comment]
gerbera still leaks memory with matroska files.

**Comment by whyman** [comment]
I thought that was a libebml issue?

**Comment by neheb** [comment]
I have no idea. I know it’s fixed with a 2 line patch.

**Comment by KarlStraussberger** [comment]
> I thought that was a libebml issue?
>>I have no idea. I know it’s fixed with a 2 line patch.

From our perspective we free everything we acquire. Even from digging into ebml code I cannot see the source for the gap, so it may even be a false positive. If it is a problem, it only occurs during import, so a quick restart after import solves the problem.

The two line patch slows down import significantly!

**Comment by neheb** [comment]
> > I thought that was a libebml issue?
> > > I have no idea. I know it’s fixed with a 2 line patch.
> 
> From our perspective we free everything we acquire. Even from digging into ebml code I cannot see the source for the gap, so it may even be a false positive. If it is a problem, it only occurs during import, so a quick restart after import solves the problem.
> 
> The two line patch slows down import significantly!

with matroska files, sure.

**Comment by whyman** [comment]
@KarlStraussberger When do you think we should cut this?

**Comment by KarlStraussberger** [comment]
I think we could merge #2604 #2565 and if you get it done #2606 and then wait for 5 days.
