### ISSUE TITLE
net-misc/gerbera-1.10.0 crashing with map std::out_of_range

### ISSUE THREAD

**Issue by AlexPuchmayr** [gerbera/gerbera#2552]
Gerbera is crashing with std::out_of_range, which is usually raised when accessing a non-existing element in a read-only map.

Evironment:
gentoo linux, amd64, running in virtual machine
Version 1.10.0 (from gentoo's portage tree)
Music collection on NFS share, with inotify-autoscan enabled entries
Running as non-root (user 'gerbera', group 'gerbera')

Gerbera seems to run normally for a while and after a few minutes (or even seconds) it crashes with the unhandled std::out_of_range exception.

Backtrace from gdb:
[Thread 0x7fffebfff640 (LWP 22461) exited]
[Thread 0x7fffe9cf8640 (LWP 22465) exited]
[Thread 0x7fffd7fff640 (LWP 22468) exited]
[Thread 0x7fffeb7fe640 (LWP 22462) exited]
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at

Thread 6 "gerbera" received signal SIGABRT, Aborted.
0x00007ffff5a88b8e in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff5a88b8e in raise () from /lib64/libc.so.6
#1  0x00007ffff5a72548 in abort () from /lib64/libc.so.6
#2  0x00007ffff5ce0865 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6
#3  0x00007ffff5cebb98 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6
#4  0x00007ffff5cebc03 in std::terminate() () from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6
#5  0x00007ffff5cebe84 in __cxa_throw () from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6
#6  0x00007ffff5ce30c7 in std::__throw_out_of_range(char const*) () from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6
#7  0x00005555556df7b6 in std::__detail::_Map_base<int, std::pair<int const, std::shared_ptr<AutoscanInotify::Wd> >, std::allocator<std::pair<int const, std::shared_ptr<AutoscanInotify::Wd> > >, std::__detail::_Select1st, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::at (this=this@entry=0x55555584ccb0, __k=@0x7ffff105b99c: 1473) at /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/include/g++-v11/bits/hashtable_policy.h:759
#8  0x00005555556da6b4 in std::unordered_map<int, std::shared_ptr<AutoscanInotify::Wd>, std::hash<int>, std::equal_to<int>, std::allocator<std::pair<int const, std::shared_ptr<AutoscanInotify::Wd> > > >::at (__k=@0x7ffff105b99c: 1473, this=0x55555584ccb0) at /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/include/g++-v11/bits/unordered_map.h:997
#9  AutoscanInotify::unmonitorDirectory (this=0x55555584cba0, path=filesystem::path "/data/music/Unsorted" = {...}, adir=std::shared_ptr<AutoscanDirectory> (use count 1, weak count 0) = {...})
    at /usr/src/debug/net-misc/gerbera-1.10.0/gerbera-1.10.0/src/content/autoscan_inotify.cc:550
#10 0x00005555556dc5dd in AutoscanInotify::monitorUnmonitorRecursive (this=0x55555584cba0, startPath=..., unmonitor=true, adir=std::shared_ptr<AutoscanDirectory> (use count 1, weak count 0) = {...}, 
    startPoint=<optimized out>, followSymlinks=true) at /usr/src/debug/net-misc/gerbera-1.10.0/gerbera-1.10.0/src/content/autoscan_inotify.cc:453
#11 0x00005555556dce06 in AutoscanInotify::threadProc (this=0x55555584cba0) at /usr/src/debug/net-misc/gerbera-1.10.0/gerbera-1.10.0/src/content/autoscan_inotify.cc:112
#12 0x00007ffff5d17fc0 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/11.2.1/libstdc++.so.6
#13 0x00007ffff7eebd50 in start_thread () from /lib64/libpthread.so.0
#14 0x00007ffff5b4bbaf in clone () from /lib64/libc.so.6

**Comment by whyman** [comment]
Hey @AlexPuchmayr,

Can you test a master build and tell us if it helps?

**Comment by AlexPuchmayr** [comment]
Tested it with gergera-9999 (which is actually master) - still the same. Same crash at same position.

**Comment by KarlStraussberger** [comment]
Patch is on its way. You may try #2556 to confirm.

**Comment by AlexPuchmayr** [comment]
Tested #2556 for several hours now -- no more out-of-range exceptions encountered.
I think it solves the problem.

**Comment by KarlStraussberger** [comment]
Great. I can clean up the code then 👍
