### ISSUE TITLE
WebOS 5 LG NanoCell 65nano866na Does not get thumbnails using dlna client

### ISSUE THREAD

**Issue by Hyper200** [gerbera/gerbera#2557]
Hi there,

I'm trying to figure out what i might be doing wrong with gerbera which is stopping the thumnails showing on the dlna client.

I know the thumbnails are being generated, as the i can see them using VLCs dnla client. I know the tv can display the thumbnails as it worked on qnap DLNA Server.

I captured the debug logging from the DLNA client request on the webos server trying to show the thumnail as i browse into the directory, it does not show and the log is below:

[webos.txt](https://github.com/gerbera/gerbera/files/8476904/webos.txt)

I came across another issue which has a pull request with <protocolInfo extend="yes"/> but this does not seem to fix my issue.

Any advice would be great

Thank you

Joe.

**Comment by whyman** [comment]
Hi Joe, thanks for reporting!

Can you tell us which OS/Arch you are on, how you are installing Gerbera (docker/package), which version of Gerbera you have installed?

I can see from your log file we are sending along the information to your TV: 
```
&lt;upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0" dlna:profileID="JPEG_TN"&gt;http://192.168.1.250:49152/content/media/object_id/53043/res_id/1/rh/6&lt;/upnp:albumArtURI&gt;
```
Would it possible for you to get a copy of what the QNAP server is sending so we can do a comparison?

**Comment by Hyper200** [comment]
Hi Whyman,

Gebera according to the ubuntu package list is 

ii  gerbera                               1.9.2-focal1                       amd64        UPnP Media Server

Its running on Ubuntu 

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

I could see in the requests as well it looked like it was being sent, I have a few tcpdumps, looking at the requests they are largely diffrent 

[gerbera_webos.xml.txt](https://github.com/gerbera/gerbera/files/8479839/gerbera_webos.xml.txt)
[qnap_webos.xml.txt](https://github.com/gerbera/gerbera/files/8479840/qnap_webos.xml.txt)
[qnap_xml.xml.txt](https://github.com/gerbera/gerbera/files/8479841/qnap_xml.xml.txt)
[gerbera_vlc.xml.txt](https://github.com/gerbera/gerbera/files/8479842/gerbera_vlc.xml.txt)

I managed to capture the xml for the responses to the post, i hope this is what you are looking for - the qnap doesn't have a detail log as gebera so i've had to use tcpdump and grab the details out, i can seee there are diffrence headers attached to the res 

Qnap protocolinfo
`<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=00900000000000000000000000000000">`

Gebera Protocolinfo
`<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=01;DLNA.ORG_CI=0" resolution="128x53">`

I've no idea if this is the cause just a diffrence i've spotted.

Thanks

Joe.

**Comment by whyman** [comment]
Thanks Joe, We will take a look at those dumps/logs later.

In the mean time you might want to try the latest Gerbera version to see if it helps, `1.10` is the latest.

**Comment by Hyper200** [comment]
No worries - If i can do anything else to help please let me know, other than than this thumnail issue i really enjoy using gerbera, its great!

Do you know if/when 1.10 will be relased to the ubutnu repos? If its not going to be soon i'll build it.

Thanks

**Comment by Hyper200** [comment]
Looks like 1.10 fixed my issues - Thanks very much!

**Comment by whyman** [comment]
Awesome news!
