### ISSUE TITLE
Gerbera crashes when trying to generate thumbnails of certain .jpg images files

### ISSUE THREAD

**Issue by Nuromi-pm** [gerbera/gerbera#2562]
When in the database view of the Web UI, if I navigate to a directory that contains some JPG images files and after that, navigate to any other directory, it will pop up the message `The system encountered an error`. And if I try to make any other actions in the Web UI after that, it will pop up the message `invalid session id` until I reload the browser tab.

This only happen with some and not all JPG files. I attach a random one that I took from the internet, with which I can reproduce the bug.

![image](https://user-images.githubusercontent.com/86095293/163287235-a1b30041-4041-4301-a50a-322fcbfa4211.jpg)

OS: Debian 11 Bullseye.
Gerbera version: 1.10.0 installed from the .deb of this GitHub releases page.

**Comment by KarlStraussberger** [comment]
I was able to load the picture with current head. Can you to test that out as well? Which layout are you using: buildin or javascript?

If `invalid session id` appears you need to reload the browser page. If you open the brower console (F12) you may find further hints about the cause of the problem.

**Comment by Nuromi-pm** [comment]
It seems that when `<ffmpegthumbnailer enabled="yes">` in the /etc/gerbera/config.xml file, gerbera crashes when trying to generate the thumbnails of this JPG image for some reason.

Here is the output of the terminal when gerbera crash:

`[mjpeg @ 0x7fccbc109dc0] unable to decode APP fields: Invalid data found when processing input`
`[mjpeg @ 0x7fccbc109dc0] unable to decode APP fields: Invalid data found when processing input`
`[mjpeg @ 0x7fccbc109780] unable to decode APP fields: Invalid data found when processing input`
`[mjpeg @ 0x7fccbc109780] unable to decode APP fields: Invalid data found when processing input`
`[mjpeg @ 0x7fccbc00f5c0] unable to decode APP fields: Invalid data found when processing input`
`[mjpeg @ 0x7fccbc00f5c0] unable to decode APP fields: Invalid data found when processing input`
`[mjpeg @ 0x7fccbc108d00] unable to decode APP fields: Invalid data found when processing input`
`[mjpeg @ 0x7fccbc108d00] unable to decode APP fields: Invalid data found when processing input`
`[swscaler @ 0x7fccbc0aedc0] deprecated pixel format used, make sure you did set range correctly`
`terminate called after throwing an instance of 'std::logic_error'`
`  what():  decodeVideoFrame() failed: frame not finished`

**Comment by KarlStraussberger** [comment]
What's your version of ffmpegthumbnailer?

**Comment by Nuromi-pm** [comment]
ffmpegthumbnailer 2.1.1 which is the one that comes in the debian repositories.
https://packages.debian.org/bullseye/ffmpegthumbnailer

**Comment by Nuromi-pm** [comment]
I confirm that it can happen with other upnp clients like vlc for Android and not only with the Web UI, it just wasn't noticeable because systemd restarts gerbera almost immediately after crashing and the web interface was the only one that gave me an error when it happened.

**Comment by KarlStraussberger** [comment]
From the looks of it, we need to catch errors from ffmpegthumbnailer and skip the handler.

**Comment by whyman** [comment]
You could also try the [`<workaround-bugs>no</workaround-bugs>`](https://docs.gerbera.io/en/stable/config-extended.html#ffmpegthumbnailer&highlight=workaround) option, not sure if it will help.
