### ISSUE TITLE
Debian Build broken

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#2563]
```
fatal: unsafe repository ('/build' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /build
```

Any clue?

**Comment by whyman** [comment]
https://github.com/actions/checkout/issues/760#issuecomment-1097963832

Fix for some windows git CVE broke it....

**Comment by KarlStraussberger** [comment]
So it's worth waiting (also with the next release)

**Comment by whyman** [comment]
For the release we want that workflow to work so the tagged packages get built.

Not sure what the problem is, something to do with file permissions.

Maybe we can add the suggested `git config --global --add safe.directory /build` before the script is run in the container
