### ISSUE TITLE
error: Activating ContentService failed

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#2567]
After upgrading from aecadfeb to c2c07def, there is now the following problem:

> error: Activating ContentService failed [/home/user/build/gerbera-git/src/content/autoscan_list.cc:49] int AutoscanList::_add(const std::shared_ptr<AutoscanDirectory>&, std::size_t) Error: Attempted to add same autoscan path twice
error: Failed to start LibUPnP: Unknown error code error code: 500
error: UpnpUnRegisterClient failed (-116)
error: UpnpUnRegisterRootDevice failed (-116)

**Comment by KarlStraussberger** [comment]
If you start with a new database it should work. Or remove all persistent autoscan entries from the database

**Comment by whyman** [comment]
Ouch, yes this is a case that was missed. I wonder if we need a migration to delete the "from config" autoscans that ended up in the DB

**Comment by kyak** [comment]
Thanks! The error has turned into warning. Now i got even more warning-error messages :)

> warning: Error in configuration, could not find  command "vlc" in $PATH

> warning: [gerbera-git/src/content/autoscan_list.cc:49] int AutoscanList::_add(const std::shared_ptr<AutoscanDirectory>&, std::size_t) Error: Attempted to add same autoscan path twice: /home/user/path

**Comment by whyman** [comment]
Thanks for testing the git build @kyak, it really helps us improve Gerbera!

**Comment by RichardCipher** [comment]
I'm having the same issue. It says warning but autoscan does not work. If I can simply clear the database I'd rather do that. Any chance I get some direction on that? Thanks.

`warning: Web Error: 800 Error: [/build/src/content/autoscan_list.cc:49] int AutoscanList::_add(const std::shared_ptr<AutoscanDirectory>&, std::size_t) Error: Attempted to add same autoscan path twice: /mnt/vault/torrents`

**Comment by KarlStraussberger** [comment]
If you migrate from an older version it is recommended to clear the database anyway.

**Comment by RichardCipher** [comment]
Can you give me a brief synopsis on how to do this? It would be greatly appreciated.

**Comment by KarlStraussberger** [comment]
If you are using sqlite database, just remove the db file and the backup. For mysql you have to delete all tables from the gerbera database.

Afterwards the first run recreates the database and imports all media files again (at least if you use the config.xml approach).

**Comment by RichardCipher** [comment]
How do I know which one I'm using? And where would that db file be located in ubuntu? Thanks again this is great information.

`gerbera --version
Gerbera UPnP Server 1.12.0
`

**Comment by RichardCipher** [comment]
I blew away the gerbera.db file, restarted, and still getting the same error.

` warning: [/build/src/content/autoscan_list.cc:49] int AutoscanList::_add(const std::shared_ptr<AutoscanDirectory>&, std::size_t) Error: Attempted to add same autoscan path twice: /mnt/vault/torrents`

**Comment by KarlStraussberger** [comment]
Did you delete the backup file also? Can you check your autoscan entries in config.xml?

**Comment by RichardCipher** [comment]
There is no backup file. I wrote an autoscan myself, but even when it is blank, and the gui tries to create one, I have the same issue.

`    <autoscan use-inotify="auto">
      <directory location="/mnt/vault/torrents" mode="timed" level="full" recursive="yes" hidden-files="no" interval="600"/>
    </autoscan>
`

**Comment by RichardCipher** [comment]
So when I comment out the autoscan in the config I get this:

` error: unhandled unchanged option /import/autoscan/timed/directory[0]/attribute::recursive != /import/autoscan
2022-12-01 07:32:04  error: unhandled unchanged option /import/autoscan/timed/directory[0]/attribute::interval != /import/autoscan`

**Comment by RichardCipher** [comment]
How is this possible when I deleted the database file?

` info: Loading 2 configuration items from database`

**Comment by KarlStraussberger** [comment]
Looks like you still have a database file lying around. The backup is in the same folder as the database file ending with `.backup`. 

You may need to check your docker params to see where the database file is put.

**Comment by RichardCipher** [comment]
There's no backup file, and I'm not using docker. Or it's using some database file in some other directory other than where my config.xml is?

**Comment by RichardCipher** [comment]
Wow, good call. It was using a db file in my home for some strange reason. I blew that away and it recreated the database and everything seems to be working. Thanks so much! Next time I upgrade gerbera, hopefully this bug fix is in there and it happens "gracefully". lol. Thanks again!

**Comment by RichardCipher** [comment]
I still get that error if I try to autoscan from the gui more than 1 time, but whatever, I just won't do that. lol.
