### ISSUE TITLE
libexif: Non-exif JPEG size parsing not working

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#2595]
![image](https://user-images.githubusercontent.com/345034/163878813-237c40c2-d136-4620-a7b9-b8a5585f184f.png)

Broken thumbnail for some reason, incorrect resolution for both thumbnail and the main content.

**Comment by neheb** [comment]
does exiv2 work fine?

**Comment by whyman** [comment]
Havent tried exiv2, the files are all valid, I think it something to do with the fallback manual parsing code in `jpeg_resolution.cc`
