### ISSUE TITLE
Timed autoscan does not work

### ISSUE THREAD

**Issue by DoraDeu** [gerbera/gerbera#2602]
Gerbera version: 1.9.2
OS: Debian Bullseye
Media source type: Samba share (read only)
Symptom: Autoscan does not run properly and new/removed files are not reflected in the database
Description:
The source of my media files is a samba share that is read-only mounted. Inside the share I have the folder "audio" and "video".
As the files are not located at the local file system I understand that I can´t use inotify to automatically update the db after adding/removing media files. That ´s why I tried to setup timed autoscan entries. 
I first tried it via the config file but after it did not work I commented it out and tried it via the web interface.
The autoscan entry for the "audio" folder can be found in the syslog with an entry like this:
`... info: Loading autoscan location: /mnt/mediathek/audio; recursive: true, last_modified: 2022-04-09 02:38:44`

The autoscan entry for the "video" folder has the following syslog entries:
`... info: Loading autoscan location: /mnt/mediathek/video; recursive: true, last_modified: 2097-12-31 21:59:59`

I have not idea where this data in the future comes from. The system time is set up properly. I also created the complete db a couple times but always end up with that date. I guess that Gerbera gets confused by this date and does not check the file system anymore.

Does anybody see a way how I can fix this?

**Comment by KarlStraussberger** [comment]
Thank you for the report.

I don't remember any autoscan issues with 1.9.2 (which is almost a year old). So I'd ask you to check the filesystem for a file that actually has that date. Sometimes systems do as expected and we don't check the timestamps for sanity.

If you are running other services on docker you may also have the timesync issue which can be found in our history as well.

**Comment by DoraDeu** [comment]
Thank you for your hint!
I found an mkv file with the modification date "2097-12-31 21:59:59".  So I fixed that date and removed the file from the db and added it again.
This date is still logged as last_modified date for the autoscan entry.
So I have three more questions:
1. Do I now have to re-create the complete DB to get rid of this entry (takes about a day for the import)?
2. As I can´t guarantee that this will never happen again that a file has a modification date in the future: Is there a way to modify Gerbera in order to be resistant related to the last modification dates of files?
3. Am I right that the disks will spin up from the sleeping status each number of seconds that are configured for the autoscan entry?
4. Isn´t there a command or a functionality in the web UI to trigger the re-scan for new/moved/removed files manually?

**Comment by KarlStraussberger** [comment]
>     1. Do I now have to re-create the complete DB to get rid of this entry (takes about a day for the import)?

You can remove the entries form the "PC Directory" which should remove it altogether. Then readd it (see 4.)

>     2. As I can´t guarantee that this will never happen again that a file has a modification date in the future: Is there a way to modify Gerbera in order to be resistant related to the last modification dates of files?

That's something to consider. We'll track it with this issue

>     3. Am I right that the disks will spin up from the sleeping status each number of seconds that are configured for the autoscan entry?

There is no other way to detect new files than to scan the disc's content, except inotify. You may increase the interval for rescan to something like a day and simply restart gerbera after you added new files.

>     4. Isn´t there a command or a functionality in the web UI to trigger the re-scan for new/moved/removed files manually?

On the web UI you can go to the filesystem view and manually add files.
