### ISSUE TITLE
Error (1621) on Bose Soundtouch 30 apps part 2

### ISSUE THREAD

**Issue by mergality** [gerbera/gerbera#2616]
Hi again!

For the first part see previous thread [here](https://github.com/gerbera/gerbera/issues/1080).
Looks like site at Bose forum died, but I managed to find its remnants [here](https://web.archive.org/web/20201129112041/https://community.bose.com/t5/SoundTouch-Archive/UPnP-with-Soundtouch-30/td-p/220160).

I kept running the 1.3.2 release up until now, but for some reason videos were importing inconsistently, so I've tried to upgrade to a later release. Of course the Bose SoundTouch library error 1621 came back with new versions.
I'm no longer using custom import script because I'm happy with how virtual folders are created by default.

I'm now running gerbera on Linux Mint 20.3 (Ubuntu Focal) (amd64).
I've tried using versions: 1.8.2, 1.9.1, 1.9.2 and now I'm on 1.10. I've deleted and rebuilt database between version changes to no avail.

Again VLC and my Philips TV doesn't seem to have any problems reading music virtual folders.

Strangely, with Bose app I can view some virtual folders. I've been experimenting to pinpoint the root of the issue but I'm not sure I'm seeing a pattern here. I've been adding music directories gradually and again it's hit or miss. Sometimes I can't access a genre even if only one artist is there but I can view that music via the Album folder. Some music with non English characters work and some doesn't, I don't think that characters are a problem.
If I add enough music directories to the library I can only browse Genre folder (not that long of a list) with the app but I'm only able to view some of my genres.
I have a suspicion this **might** be down to number of items in a specific virtual folder, but nothing certain, because I've copied known to be working album contents so it had over 130 mp3 files in it and it still worked.
 
Any ideas?

**Comment by KarlStraussberger** [comment]
Can you try running gerbera with `--debug` because the log shows us what your Bose app requests.

**Comment by whyman** [comment]
This is probably relevant: https://forum.minimserver.com/showthread.php?tid=5487

> It looks like the URLs that MinimServer generates for streaming the tracks in this album are too long for your Bose player. This is a known issue with some players that limit the maximum length of URLs that they can handle.

**Comment by mergality** [comment]
> This is probably relevant: https://forum.minimserver.com/showthread.php?tid=5487
> 
> > It looks like the URLs that MinimServer generates for streaming the tracks in this album are too long for your Bose player. This is a known issue with some players that limit the maximum length of URLs that they can handle.

Thanks whyman, but that's the exact thread I found about a year ago (linked in the first issue posted). I'll do some more digging but to me gerbera URLs are quite short thanks to unique IDs in the database that are called in the db.

**Comment by mergality** [comment]
> Can you try running gerbera with `--debug` because the log shows us what your Bose app requests.

Hi Karl!
See debug output in the file below.
First 2 requests in the Genre folder for "Folk Metal" and "Ambient" were successful on the Bose app, 3rd for "Christmas Songs" resulted in 1621 error.
I'm not really sure what to look for in the output though.

[gerbera_debug.txt](https://github.com/gerbera/gerbera/files/8598779/gerbera_debug.txt)

**Comment by whyman** [comment]
@mergality I would guess that all `Michael Bublé` is not working?

**Comment by mergality** [comment]
@whyman Can't really tell if that's the issue. Other artists/songs also have have issues showing. I've selected relatively "small" genres in my library.
Another example in the next file - Artist folder req that also fails with 1621.

[gerbera_debug2.txt](https://github.com/gerbera/gerbera/files/8598807/gerbera_debug2.txt)

**Comment by KarlStraussberger** [comment]
I found one other thing that may cause the effect: `&amp;`

Some of your artists and albums contain an `&`. This is encoded as `&amp` and may break your clients decoding of the message. Try to change the tags to get rid of the `&` and have a look (with inotify you do not have to reimport).

**Comment by mergality** [comment]
@KarlStraussberger
I'll try replacing chars in some music of the library and see if that's the problem, but why those same songs would work beautifully on databases build with versions 1.3.2 and 1.3.5?

**Comment by KarlStraussberger** [comment]
There are plenty of changes in string handling, external xml libs, character conversion to name just a few. 1.3.2 is a long way back with respect to the code base. Thanks for trying.

**Comment by whyman** [comment]
Do you have a working 1.3.5 around still? Would be good to get a packet capture

**Comment by KarlStraussberger** [comment]
Maybe you can also run it with `--debug` (or `-D`) to give us the insights that used to be created back then.

**Comment by alexistr** [comment]
Hi I'have the same issue with boose soundtouch 10. 
Thank to your comments I've realized all the album with track name containing single quote (') where leading to the error 1621.
I've replaced it and no more problem.
Now I'm looking for a way to make it automatic and specific to boose client so I don't have to bother anymore.

**Comment by KarlStraussberger** [comment]
So it may also be the string limit that causes the error. Can you try with one ' whether it still works. 

String limit is something that nowadays can be configured on a per-device base (https://docs.gerbera.io/en/latest/config-clients.html#client)

**Comment by alexistr** [comment]
Even with just one ' in the meta boose soundtouch gaves the 1621 error.
But when I delete ' from filename as well and now I'dont even need upnp-string-limit in my config.
Delete ' from meta and filename seems to be a working workaround for me.

**Comment by mergality** [comment]
Hi!
Now with some time off for holidays I finally tried fiddling with Gerbera again.
Unfortunately setting upnp-string-limit by itself didn't workout for me.
@alexistr Did removal of the apostrophe and upnp-string-limit combined made it work for you or both fixed the issue independently?

> Maybe you can also run it with `--debug` (or `-D`) to give us the insights that used to be created back then.

I've installed 1.3.2 and rebuilt the database - as previously it works perfectly with Bose app.
See the log file with Christmas Songs genre requests from the app in the attached file for comparison. 
[gerbera.log](https://github.com/gerbera/gerbera/files/10281449/gerbera.log)

**Comment by KarlStraussberger** [comment]
I think that difference may prove the suspicious tick theory.

1.3.2: `Rockin&amp;apos; Around `
1.10: `Rockin' Around`

In 1.3.2 xml code was part of gerbera, now we rely on pugixml which itself does handle apos on parse but not on output.

Obviously Bose is one of a few that requires strict xml here. This will give us a new client flag.

**Comment by alexistr** [comment]
@mergality  i removed ' both from meta and filename and my soundtouch is working fine since.  upn-string-limit did not solve the problem. A single ' and I got the 1621 error

**Comment by KarlStraussberger** [comment]
@mergality @alexistr  can any of you test the new PR #2766 before I merge it, please?

**Comment by mergality** [comment]
> @mergality @alexistr can any of you test the new PR #2766 before I merge it, please?
Thanks Karl for taking a quick action, but I think I'm out of my comfort zone here to make it happen. For the better part of the afternoon I tried pulling that commit and I'm not sure I got it right (probably not) and I'm stuck now on a cmake error asking for Taglib at least 1.12, when I just went and installed 1.13.
I'm afraid without step by step instruction for Ubuntu 20.04 (so a Debian Bullseye) this is as far as I can go following wiki documentation and online tutorials.

**Comment by KarlStraussberger** [comment]
Thanks for trying.

With regards to taglib, you may have one installed via `apt` which is under `/usr` and hides the self-build under `/usr/local`. Try `apt remove taglib*`.

There is a set of install-scripts under `scripts` which should make life easier to you.

There is also a `build-deb.sh` script under `scripts/debian`.

**Comment by KarlStraussberger** [comment]
It's hard to keep all the instructions up to date when your build env is set up. But as always, volunteers with fresh knowledge are welcome to point out changes required.

**Comment by mergality** [comment]
Hi Karl!
Looks like your latest update works beautifully with Bose app!
All needed now is the following lines to be added to:
` <clients enabled="yes">
    <client ip="your_speaker_ip" flag="STRICTXML"></client>
 </clients> `
Thank you very much!
