### ISSUE TITLE
Web UI - Background Color in Modal

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#263]
I loaded up the latest style changes.  Wow it is awesome! But saw the header [background-color](https://github.com/gerbera/gerbera/blob/master/web/assets/theme/gerbera.css#L56) impacts the **modal**

<img width="364" alt="screen shot 2018-03-12 at 9 00 21 pm" src="https://user-images.githubusercontent.com/8599799/37316959-7be5b3ca-2638-11e8-83d8-90d845c10eed.png">

I wanted to see if the **background-color** was needed elsewhere to fix appropriately?  

Any ideas?

**Comment by v00d00** [comment]
Yeah I spotted that, but got distracted messing around with flexbox stuff... Not sure where its needed.

**Comment by elmodaddyb** [comment]
I will push a change to the css. Sadly I messed up my gerbera fork something awful  so gotta fix that first before doing another PR

> my guess is the **background-color** is only applicable to the body tag, and should be moved out of the `h`eaders block.
