### ISSUE TITLE
Files are not being added

### ISSUE THREAD

**Issue by SubZero77** [gerbera/gerbera#2633]
I installed Gerbera on Centos 8. The web interface works. I select File system and the "Media" folder for the example and click Add Item. At this moment, a green inscription "Successfully added item" appears at the bottom and nothing else happens. The same situation happens with any other directories. Where is the file upload dialog or something similar? How do I add files?
The command "systemctl status gerbera.service" shows in the last line gerbera[1057]: Exception raised in [src/filesystem.cc:111] readDirectory(): could not list directory /root : Access denied
p.s. my browser is Chrome

**Comment by whyman** [comment]
The `gerbera` user will need to have file permissions to access whatever files you are trying to access.

Also please make sure you are running a recent build. The latest version is `1.11.0`

**Comment by SubZero77** [comment]
[root@dlna01 ~]# gerbera -v
Gerbera UPnP Server version 1.3.5 - http://gerbera.io/

**Comment by KarlStraussberger** [comment]
Outdated by now.
