### ISSUE TITLE
Bad bounding server for web UI

### ISSUE THREAD

**Issue by gkzsolt** [gerbera/gerbera#265]
I had a working Gerbera server installed on a Debian Jessie. After installing a VPN server on the machine (and rebooting), Gerbera started to bound to 10.8.0.1:
`[...]  INFO: Server bound to: 10.8.0.1`
, which is the first address on the OpenVPN subnet. This is of course not working, as my local subnet is 192.168.1.X, and the Debian machine is on 192.168.1.7 (to which Gerbera correctly bound previously.)
I looked at configuration options in config.xml, but no success. 
What can I do?

**Comment by v00d00** [comment]
You can use the `--interface` and/or `--ip` options

**Comment by gkzsolt** [comment]
Thanks, I figured it out in the meantime. The reaction time is amazing on this forum;)
