### ISSUE TITLE
Gentoo Gerbera 1.11.0 SQL Error

### ISSUE THREAD

**Issue by hipco** [gerbera/gerbera#2655]
Default Installation with Gentoo Linux produces a segmentation fault and prevents starting the daemon.

`2022-06-08 12:52:45.442  debug: [sqlite_database.cc:479] run(): no such table: mt_internal_setting
2022-06-08 12:52:45.443  debug: [sqlite_database.cc:406] waitForTask(): SQLITE3: (1, : 1) no such table: mt_internal_setting
Query: SELECT "value" FROM "mt_internal_setting" WHERE "key" = 'db_version' LIMIT 1
error: no such table: mt_internal_setting`

After importing the schema, a different error is logged and the service doesn't start up either with a segmentation fault.

`sqlite3 /var/lib/gerbera/gerbera.db < /usr/share/gerbera/sqlite3.sql`

`INSERT INTO "mt_internal_setting" VALUES('db_version', '19');
error: table "mt_cds_object" already existsINSERT INTO "mt_internal_setting" VALUES('db_version', '19');
error: table "mt_cds_object" already exists
2022-06-08 13:00:11.904  debug: [sqlite_database.cc:353] shutdownDriver(): start
`

Almost equal errors if I use a mysql database. Any ideas what I'm missing?

**Comment by KarlStraussberger** [comment]
It looks like your config points to different locations for the init scripts that they are not executed on startup. For Sqlite you should be able to start without a db file - delete the file and backup and start gerbera with --debug once again.

The init db script does not contain all required commands to set up the database.

**Comment by hipco** [comment]
I use the default gerbera gentoo package with default package paths. I just added the use flag debug. As you mentioned I deleted the database but sadly with the same result.

`error: no such table: mt_internal_setting`

So I created the default sqlite3 gerbera db and inserted db_version values into the mt_internal_settings table. And voila the service starts up.

`sqlite3 /var/lib/gerbera/gerbera.db < /usr/share/gerbera/sqlite3.sql`
`chown gerbera:gerbera /var/lib/gerbera/gerbera.db`
`sqlite3 /var/lib/gerbera/gerbera.db `
`sqlite> INSERT INTO "mt_internal_setting" VALUES('db_version', '19');`
