### ISSUE TITLE
What ports should be open for gerbera on a firewall?

### ISSUE THREAD

**Issue by gkzsolt** [gerbera/gerbera#266]
I opened 49152/tcp (and written it to _port_ config in config.xml), but noticed that the daemon uses also some other ports:
`# netstat -pln | grep gerbera`
`tcp        0      0 192.168.1.7:49152       0.0.0.0:*      LISTEN    3652/gerbera`
`udp        0      0 127.0.0.1:42574         0.0.0.0:*                3652/gerbera`
`udp        0      0 0.0.0.0:1900            0.0.0.0:*                3652/gerbera`
although `42574` is variable. So I opened also 1900/udp, although I am not sure it is needed.

**Comment by v00d00** [comment]
Hi,

You can set the HTTP server port with `--port`, libupnp will use >=49152 otherwise. The `1900/udp` is needed for SSDP.

Not sure on the other port though, I would have to check the libupnp source, probably HTTPU, not sure we can influence libupnps range though.

**Comment by gkzsolt** [comment]
Thank you.

**Comment by elgorro** [comment]
The Random Port comes from (Avahi-Daemon)[https://wiki.archlinux.org/index.php/Avahi] and this can/(should)[https://bbs.archlinux.org/viewtopic.php?id=253717] be disabled and a other mDNS-Service enabled, like (Systemd-Resolved integrated)[https://wiki.archlinux.org/index.php/Systemd-resolved#mDNS]! Very helpfull for running Gerbera (and OS) with firewall protection.
