### ISSUE TITLE
No album sub-containers per artist created in "builtin"

### ISSUE THREAD

**Issue by Pythocrates** [gerbera/gerbera#2663]
When trying to rebuild my complete audio library after an upgrade (1.11.0 on Ubuntu 22.04 from JFrog) I ran into the issue that no containers were built in "Audio/Artists/my-artist" for the respective albums when using the "builtin" layout. Instead, all tracks ended up directly in the "Audio/Artists/my-artist" container.
Using the "js" layout worked, however.

I think the culprit is the typo/copy-paste bug in line 365 below. At least it would explain why the tracks ended up in the wrong container. Not sure if anything else is wrong because I do not have a build environment on this machine...

https://github.com/gerbera/gerbera/blob/15c02090d01c7f73ed3ab1636cb4879a0b7a9a6d/src/content/layout/builtin_layout.cc#L361-L367

**Comment by KarlStraussberger** [comment]
Thank you for uncovering. There is a nice github feature: Edit files on Web :smile:

**Comment by Pythocrates** [comment]
Yes, I know. But - even though it is a tiny change - I was rather hesitant to contribute something I did not even try to build. Thanks for fixing it. And: Thanks for the great software! :+1:

**Comment by neheb** [comment]
...wow. Good catch.
