### ISSUE TITLE
How do I run Gerbera as myself instead of user Gerbera?

### ISSUE THREAD

**Issue by jenia** [gerbera/gerbera#2668]
Hello.

I;d like to try running Gerbera as myself so that it'll have access to my folders.

Is Gerbera meant to be used like that? Can I simply change:

    /usr/lib/systemd/system/gerbera.service

And set it to run as myself:

```
[jenia@jenia movies]$ cat /usr/lib/systemd/system/gerbera.service
[Unit]
Description=Gerbera Media Server
After=network.target network-online.target

[Service]
Type=simple
User=jenia
Group=gerbera
ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

So long story short, is it a good idea to run Gerbera daemon as myself?

**Comment by KarlStraussberger** [comment]
That's a question of Linux principles. Normally you distinguish between system accounts and personal accounts (as W*s does as well). If you run a service under your user this presents a security risk.

Best solution is a group with READ access to your media. You're member of that group also and can easily decide (with `chgrp`) which files are visible in your network!
