### ISSUE TITLE
Remove Audio Video etc and changing root folder

### ISSUE THREAD

**Issue by jobsidi** [gerbera/gerbera#2678]
How to remove virtual dirs from the root? Ok, i delete it manually using webUI from database, but those appear again when i add new file. Also i want to see content of for example PC Directory\cinema in the root of upnp server and not to do additional 2 clicks like now to do click on PC Directory then click on cinema and only then i see all my content. I want to click just once and get list of all content without additional folders.

**Comment by KarlStraussberger** [comment]
This is the idea of individual virtual layouts (https://docs.gerbera.io/en/stable/config-import.html#scripting). So you'd better hide PC Directory (https://docs.gerbera.io/en/stable/config-server.html#pc-directory) and play around with the import script.

**Comment by aleho** [comment]
Is there an actual way of removing the `content` directory and putting everything into the first item in the chain?

I've gotten as far as this script, but it actually adds an object below the root, e.g. `Video/content/folder_1`.

`JS
function addVideo(obj) {
    const dir = getRootPath(object_script_path, obj.location);
    const chain = {
        video: { title: 'Video', objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER, metaData: [] },
    };
    
    chain.video.metaData[M_CONTENT_CLASS] = [ UPNP_CLASS_VIDEO_ITEM ];
    
    if (dir.length > 0) {
        var tree = [chain.video];
        for (var i = 0; i < dir.length; i++) {
            tree = tree.concat({ title: dir[i], objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER });
        }
        tree[tree.length-1].metaData = [];
        tree[tree.length-1].res = obj.res;
        tree[tree.length-1].aux = obj.aux;
        tree[tree.length-1].refID = obj.id;
        addCdsObject(obj, addContainerTree(tree));

    } else {
        // add to root container
        addCdsObject(obj, addContainerTree([chain.video]));
    }
}
```

**Comment by KarlStraussberger** [comment]
The path is relative to the autoscan dir. You may just overwrite `getRootPath` in a custom js file or play around with settings described in  https://docs.gerbera.io/en/stable/config-import.html#layout

**Comment by aleho** [comment]
Thanks, that worked for me!

```XML
    <scripting script-charset="UTF-8">
      <common-script>/usr/local/share/gerbera/js/common.js</common-script>
      <custom-script>/var/run/gerbera/custom.js</custom-script>
      <playlist-script>/usr/local/share/gerbera/js/playlists.js</playlist-script>
      <virtual-layout type="js">
        <import-script>/usr/local/share/gerbera/js/import.js</import-script>
      </virtual-layout>
    </scripting>
```

```JS
function addVideo(obj) {
    const dir = getRootPath(object_script_path, obj.location);
    const chain = {
        video: { title: 'Video', objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER, metaData: [] },
    };

    chain.video.metaData[M_CONTENT_CLASS] = [ UPNP_CLASS_VIDEO_ITEM ];

    if (dir[0] === 'content') {
        dir.shift();
    }

    if (dir.length > 0) {
        var tree = [chain.video];
        for (var i = 0; i < dir.length; i++) {
            tree = tree.concat({ title: dir[i], objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER });
        }
        tree[tree.length-1].metaData = [];
        tree[tree.length-1].res = obj.res;
        tree[tree.length-1].aux = obj.aux;
        tree[tree.length-1].refID = obj.id;
        addCdsObject(obj, addContainerTree(tree));

    } else {
        // add to root container
        addCdsObject(obj, addContainerTree([chain.video]));
    }
}
```
