### ISSUE TITLE
 error: Inotify thread caught exception

### ISSUE THREAD

**Issue by ngosang** [gerbera/gerbera#2686]
Gerbera 1.11.0 Docker / Linux
Checking the logs I saw this trace. There are no more traces in the same day so I can't provide more info. Gerbera seems working well as usual.
`2022-08-05 14:39:26  error: Inotify thread caught exception: [/gerbera_build/src/database/sql_database.cc:1510] std::shared_ptr<CdsObject> SQLDatabase::createObjectFromRow(const string&, const std::unique_ptr<SQLRow>&) Error: tried to create object without at least one resource`

**Comment by KarlStraussberger** [comment]
If it does not happen on a regular basis it's hard to guess. Maybe some volume that was not accessible for docker.

**Comment by ngosang** [comment]
I'm closing since I can not reproduce the issue and it didn't happen in the last 30 days.
