### ISSUE TITLE
Query string built but not executed

### ISSUE THREAD

**Issue by gburca** [gerbera/gerbera#269]
https://github.com/gerbera/gerbera/blob/2f6dcb5e941dce3ace651394cfa86b862becaa77/src/storage/sql_storage.cc#L1416

**Comment by gburca** [comment]
I'm fixing it as part of the switch to std::ostringstream, but in case that commit doesn't make it this is a reminder of what needs to be addressed.

**Comment by gburca** [comment]
Fixed in a2e3748. This can be closed once that commit is merged.

**Comment by v00d00** [comment]
Its merged now.
