### ISSUE TITLE
Roku hides incompatible media, does not show when transcoding is enabled.

### ISSUE THREAD

**Issue by Plet53** [gerbera/gerbera#2691]
Target Device: Roku/4400X
Host: 5.18.16-arch1-1

Have attempted both with "Hide original resource" and "first-resource" enabled in config, both separately and together. Please advise.

**Comment by whyman** [comment]
Can you provide a debug log?

**Comment by Plet53** [comment]
...Naturally the moment I open an issue it decides to function. Had configured via the web interface and not `config.xml` at the time, adding the format to `config.xml` worked.

**Comment by KarlStraussberger** [comment]
Event with web UI config changes it may be necessary to restart the server
