### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by asanDD** [gerbera/gerbera#2699]
Hi, 
found a little typo in the documentation.

In the documentation https://github.com/gerbera/gerbera/blob/master/doc/config-import.rst
the attribute "media-type" of the "autoscan" option is described as follows:
mediatype="Music|AudioBook"

But the definition of the attribute in https://github.com/gerbera/gerbera/blob/master/src/config/config_definition.cc
is as follows:
std::make_shared<ConfigIntSetup>(ATTR_AUTOSCAN_DIRECTORY_MEDIATYPE,
        "attribute::media-type", "config-import.html#autoscan",
        to_underlying(AutoscanDirectory::MediaType::Any), AutoscanDirectory::makeMediaType)

**Comment by KarlStraussberger** [comment]
Thank for pointing to this. Will fix it with next PR.
