### ISSUE TITLE
Logging level on gerbera server?

### ISSUE THREAD

**Issue by gkzsolt** [gerbera/gerbera#270]
Hi,
I wandered what is filling my filesystem on a server, and it turned up to be gerbera dumping tons of debug messages to syslog and daemon.log (it come close to 50M in 1-2 days, which filled my log2ram 50M filesystem). How can I prevent this? I was looking for some logging level setting, but have seen only the "--debug - Enable debug log output" command line option. Is it possible to set up command line options for the daemon process?

Thanks,

**Comment by gkzsolt** [comment]
Gerbera is started with: 
`ExecStart=/usr/local/bin/gerbera -c /etc/gerbera/.config/gerbera/config.xml`
in the systemd gerbera.service, so --debug is not used, just is being used... How can I supress it?

**Comment by elmodaddyb** [comment]
That is strange that the system is writing `log_debug(...)` statements without the `--debug` flag

`ConfigManager::setStaticArgs` is setting the **debug_logging** flag based on the `--debug` switch.

During restart the system does not send the flag, but instead defaults to the method signature, which is also false --> [ConfigManager::setStaticArgs](https://github.com/gerbera/gerbera/blob/master/src/config_manager.h#L233)

I will try spawning the application in systemd daemon to see how it reacts.

**Comment by v00d00** [comment]
@gkzsolt Which version are you running, master or 1.1?

**Comment by gkzsolt** [comment]
Seems to be master.

`# gerbera --version

Gerbera UPnP Server version 1.2.0_alpha - http://gerbera.io/

===============================================================================
Gerbera is free software, covered by the GNU General Public License version 2

Copyright 2016-2018 Gerbera Contributors.
Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
===============================================================================
Compile info:
-------------
WITH_MAGIC=1
WITH_MYSQL=1
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=1
WITH_TAGLIB=1
WITH_AVCODEC=1
WITH_FFMPEGTHUMBNAILER=0
WITH_EXIF=1
WITH_EXIV2=0
WITH_PROTOCOL_EXTENSIONS=1
WITH_LASTFM=0
WITH_LOGGING=
WITH_DEBUG_LOGGING=

Git info:
-------------
Git Branch: refs/heads/master
Git Commit: ab340f5e41995d592baf39ed682ff23a71ea0f93
`
Btw, in the last days it does not really log to the mentioned logs, I don't know if because of "changed usage patterns", or demo effect... ;)

**Comment by gkzsolt** [comment]
Sorry to not have checked the preview ;)

**Comment by v00d00** [comment]
Should be sorted in latest mater, make sure to delete your cmake build directory and re-run cmake.
