### ISSUE TITLE
Autoscan from GUI does not "recognize" Audio

### ISSUE THREAD

**Issue by mnlipp** [gerbera/gerbera#2703]
I have configured structured layout. That's the only change besides server name and uuid. It's 1.11.0.

All test have been made with gerbera stopped, the db removed and gerbera restarted.

 * "Add Item" from the GUI works as expected
 * "Add Autoscan" (tested both timed an inotify) adds the items to "database/PC Directory" but not to "Audio" (or any sub directory)
     * There are some small video or image files in my music directory. These do show up in the database under Photos or Videos
 * Configuring autoscan in `config.xml` works as expected

**Comment by KarlStraussberger** [comment]
Just tried it with my current head version and it works as expected.

Can you try to provide some useful output if gerbera was run with --debug

**Comment by mnlipp** [comment]
> Can you try to provide some useful output if gerbera was run with --debug

What do you consider useful? I have started gerbera with --debug and copied any output starting with the "Add Autoscan" action in the GUI. Now I have a > 800k file that does not contain the word "error". Although I think it does not contain any personal information besides the title of the one album that I have added, I don't think I should copy/paste it here. Can I send it to you?

**Comment by KarlStraussberger** [comment]
You can attach it here or send it via mail.

**Comment by KarlStraussberger** [comment]
From the log it looks to me that you have "builtin" layout (at least it is initialized). Maybe you can also send me your config.xml.

**Comment by mnlipp** [comment]
Sure. I've tried the "js" as well. However, it resulted in strange names such as "--Albums--" and each track of an album appeared as separate album. Actually, I had expected that I get the same result if I don't change the import script. But this is a different issue.

**Comment by KarlStraussberger** [comment]
> Layout types are only available with "js" layout. If there is a problem with the structured layout in js that is an issue for itself.

Somehow the layout does not seem to be used at all. Need to dig a bit deeper!

**Comment by KarlStraussberger** [comment]
While reworking the autoscan dialog i fixed a problem that the object_id was no set so maybe you can try #2710

**Comment by Julien-Blanc-tgcm** [comment]
I can confirm this does not work with #2710  applied. Adding one-time works fine, adding with autoscan results in very few (i have a quite huge database, so i selected a « timed » refresh) audio items added.

System is debian bookworm, gerbera compiled by hand from master.

**Comment by KarlStraussberger** [comment]
New attempt #2717

**Comment by Julien-Blanc-tgcm** [comment]
Tried that, but unfortunately this is not better. I can confirm that image files are imported correctly, but not audio files.

I will make a new attempt with full trace enabled.

**Comment by KarlStraussberger** [comment]
Can you check out the details.
![grafik](https://user-images.githubusercontent.com/23654788/195076612-83dac1f3-fab3-4c94-a7c9-a5501f3ada12.png)

**All Audio** has to be enabled if you do not have config-mapping of audio-mime types.

**Comment by KarlStraussberger** [comment]
After sending you the hint, I found the culprit!

**Comment by Julien-Blanc-tgcm** [comment]
Yes, this fixes the issue for me. Thanks !
