### ISSUE TITLE
Wrong sort order for audio files inside « Directories » virtual folder

### ISSUE THREAD

**Issue by Julien-Blanc-tgcm** [gerbera/gerbera#2707]
Gerbera version 1.9.2 (but from what i see, master should be affected as well).

I have a music collection arranged the following way :

```
<root directory>
 +-- Artist 1
        +---- Album1
                   +----- Song 1
                   +----- ....
                   +----- Song n
        +---- ....
        +---- Album n
                   +----- Song 1
                   +----- ...
 +-- Artist N
       .....
```

When adding this directory to the library, recursively, i can see under the « Audio/Directories » virtual folder the following hierarchy:

```
+-- Artist 1
        +---- Album1
                   +----- Song 
```

which is exactly what i want. The problem is that the songs are sorted alphabetically instead of being sorted by track number (even if the filename contains the track number). This means that the following folder:
```
01 - foo.mp3
02 - bar.mp3
03 - eeh.mp3
04 - zaz.mp3
```

gets displayed as

```
bar
eeh
foo
zaz
```

The order of the tracks is not preserved. It should be. The following patch:
```
--- a/src/database/sql_database.cc
+++ b/src/database/sql_database.cc
@@ -884,7 +884,10 @@ std::vector<std::shared_ptr<CdsObject>> SQLDatabase::browse(BrowseParam& param)
                 orderQb = sortParser.parse();
             }
             if (orderQb.empty()) {
-                orderQb = browseColumnMapper->mapQuoted(BrowseCol::dc_title);
+                orderQb = fmt::format("{},{},{}", 
+                                     browseColumnMapper->mapQuoted(BrowseCol::part_number),
+                                     browseColumnMapper->mapQuoted(BrowseCol::track_number),
+                                     browseColumnMapper->mapQuoted(BrowseCol::dc_title));
             }
             return orderQb;
```

fixes the issue for v1.9.2 (should be adapted for master, i'll make a PR if you think that's the right way to fix that). I have no clue if it breaks some other use cases (it solves mine).

**Comment by KarlStraussberger** [comment]
This should not be necessary if the virtual structure is correct.

Gerbera automatically sorts by part and track if the parent container is an album or playlist.

https://github.com/gerbera/gerbera/blob/3b93d362ec33f738868a4e896a2c9ee8e9d7a92a/src/upnp_cds.cc#L91-L92

If you are using subtype of musicAlbum it does not work in 1.9,2 but does in current head.

**Comment by Julien-Blanc-tgcm** [comment]
Thanks for the reply. I'm using builtin layout. From the database content, i have the impression that two entries are created, one for the Albums virtual folder (in which everything is sorted correctly), and one for the Directories one (where wrong sort order occurs).

I'll try to reproduce with master, and keep you informed.

**Comment by KarlStraussberger** [comment]
Which directory are you talking about? Under "PC Directory" gerbera shows all files so we cannot assume that a track number is available. That's what the virtual layout is used for. If the problem happens under "Audio" please double check the parent folder - it should be of upnp class `object.container.album.musicAlbum`

**Comment by Julien-Blanc-tgcm** [comment]
I'm talking about the `V/Audio/Directories` virtual folder.

```
sqlite> select * from mt_cds_object where id=20;
id|ref_id|parent_id|object_type|upnp_class|dc_title|location|location_hash|auxdata|update_id|mime_type|flags|part_number|track_number|service_id|last_modified|last_updated
20||12|1|object.container|Directories|V/Audio/Directories|3261617994||3||1|||||1663914250
sqlite> 
```

```
sqlite> select * from mt_cds_object where parent_id=20;
id|ref_id|parent_id|object_type|upnp_class|dc_title|location|location_hash|auxdata|update_id|mime
_type|flags|part_number|track_number|service_id|last_modified|last_updated
178||20|1|object.container|Dalmak|V/Audio/Directories/Dalmak|699656939||1||1|||||1663913718
```

So obviously the upnp class is missing for item 178. I guess this is why it is not sorted. Note that i am using the default builtin layout, without any special tweak. Under `V/Audio/Albums` the entry is correct:

```
172||15|1|object.container.album.musicAlbum|Dalmak|V/Audio/Albums/Dalmak|620805280||1||3|||||1663
913718
```
