### ISSUE TITLE
UI Screen of Firefox and Kbuntu 22.04

### ISSUE THREAD

**Issue by pwl256** [gerbera/gerbera#2709]
When I have the lar=test version of Gerbera running my UI screen is as per the attached. Which is nothing like the documentation nor is it usable.
I can load my library by using the <import> tags in the config.xml but can not add any other directories using the UI.

I don't believe  I have got it set up wrongly but can someone help me or correct this if its an error
![Gerbera_database_Screenshot_20220926_172030](https://user-images.githubusercontent.com/11042118/192330803-b24c892a-da95-40c1-8994-3d76fe454ed0.jpg)
![Gerbera_filesystem_Screenshot_20220926_172144](https://user-images.githubusercontent.com/11042118/192330810-323bdac6-7219-47a7-926c-fd15360a2734.jpg)
My config is :-

[config.txt](https://github.com/gerbera/gerbera/files/9648022/config.txt)

**Comment by KarlStraussberger** [comment]
Thank you for sharing your problems.

First of all it is interesting to us which gerbera version is running on your system (run `gerbera --compile-info`) - there seems to be an 1.11.0 in your screenshot. Also the version of Firefox could be of importance to us.

On the other hand it looks like the style `gerbera.css` was scrambled or broken (just compare with the one under `web/assets/theme`). Also check out the web console of the browser (F12 in Firefox) for strange messages and errors.

**Comment by pwl256** [comment]
Firefox Version :  105.0.1 (64-bit)

Gerbera:

Gerbera UPnP Server 1.11.0
Copyright 2016-2022 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_NPUPNP=NO
WITH_MAGIC=ON
WITH_MYSQL=ON
WITH_CURL=ON
WITH_INOTIFY=YES
WITH_JS=ON
WITH_TAGLIB=ON
WITH_AVCODEC=ON
WITH_FFMPEGTHUMBNAILER=ON
WITH_EXIF=ON
WITH_EXIV2=ON
WITH_MATROSKA=YES
WITH_WAVPACK=ON
WITH_SYSTEMD=ON
WITH_LASTFM=OFF
WITH_DEBUG=ON
WITH_TESTS=OFF

Git info:
-------------
Git Branch: HEAD
Git Commit: d73d8c1346213d784753c02ea771970500e0df2a

When Gerbera is showing F12 has no effect in Firefox

However using Development tools etc I have captured the gerbera.css that is in the Web page.I have attached it here as delivered-gerbera-css.txt
[delivered_gerbera_css.txt](https://github.com/gerbera/gerbera/files/9649786/delivered_gerbera_css.txt)

No obvious errors or warnings are displayed.

The O/S is Ubuntu 22.04 with Kernel 5.15.0-48-generic #54-Ubuntu

**Comment by KarlStraussberger** [comment]
Did you try with another browser?

**Comment by KarlStraussberger** [comment]
Is it possible that one of your extension blocks the page?

**Comment by pwl256** [comment]
I have run FF in safe-mode - which I understand turns off all extensions and add-ons and the results are the same.

**Comment by KarlStraussberger** [comment]
I have no clue what's broken. Where did you get the package from?

Might as well be a permission problem. Does the gerbera user have access to all files (esp. gerbera.css)? Does the config `webroot` point to the right directory?

**Comment by pwl256** [comment]
I have checked permissions. Gerbera is the group owner/writer/reader of all the files /usr/share/gerbera....
The webroot is pointing to the approriate directory.

**Comment by KarlStraussberger** [comment]
I just saw that you have accounts enabled. Could you try without?

**Comment by pwl256** [comment]
If I have account enable="no" there is no link from menu to anything except the external documentation

**Comment by KarlStraussberger** [comment]
Did you have an older version installed before? Looks all too weird.

Maybe you try to get the complete `web` subtree.

**Comment by pwl256** [comment]
There was an older version present and I upgraded the O/S from 20.04 to 22.04 - that installed a new version of Gerbera.
I can tyr removing gerbera completely and installing it afress and see if that changes anything.

**Comment by pwl256** [comment]
Right seems FIXED.
I unistalled gerbera
Then ensured I had removed every reference to gerbera in the whole system
/etc/gerbera   /usr/share etc.
Re-installed 
And it seems to be working now.
I will confirm once the database is built - 30Gig plus of audio plus pictures and videos

**Comment by KarlStraussberger** [comment]
In most setups gerbera is installed under /usr/local, which may have caused the effect.
