### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by leonzon** [gerbera/gerbera#271]
using linuxmint 18 , 
cannot get it to work
have installed the dependencies as instructed, but the two .sh for librupnp and taglib do not work
even if i do proceed, the browser says file var... cannot be found
have tried systemctl to start it and the init.d service start
no luck

**Comment by astylos** [comment]
Gerbera won't work without libupnp or taglib so you need to sort those two issues. What errors do they give? 

⁣

**Comment by v00d00** [comment]
Perhaps try the [PPA](https://launchpad.net/%7Estephenczetty/+archive/ubuntu/gerbera)?

**Comment by v00d00** [comment]
@leonzon any luck?
Can you post some log files or more description of what you tried?

**Comment by leonzon** [comment]
hi, im sorry, i didnt see these messages. i installed from the ppa, but i read through the install instructions here. ive actually wiped and reinstalled lm18.x since so I cant provide log files. sorry guys. if it helps, the two sh files did not work for me inititally, so i installed cmake i think and something with the c++ libraries didnt compile properly.

**Comment by v00d00** [comment]
Okay, thanks!

**Comment by elmodaddyb** [comment]
If I get some free time I will roll a VM of Linux Mint 18 to see how it goes.
