### ISSUE TITLE
Gerbera "prematurely shutting down"

### ISSUE THREAD

**Issue by hornetster** [gerbera/gerbera#2715]
Having issues recently, not sure what brought it on, but when starting Gerbera, get message "prematurely shutting down".
```
gerbera.service - Gerbera Media Server
     Loaded: loaded (/etc/systemd/system/gerbera.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-10-03 19:58:58 AEST; 28min ago
       Docs: man:gerbera(1)
             https://gerbera.io/
   Main PID: 47648 (gerbera)
      Tasks: 3 (limit: 9060)
     Memory: 9.6M
        CPU: 179ms
     CGroup: /system.slice/gerbera.service
             └─47648 /usr/bin/gerbera -c /etc/gerbera/config.xml

Oct 03 19:58:58 mEdIa1 systemd[1]: Started Gerbera Media Server.
Oct 03 19:58:58 mEdIa1 gerbera[47648]: 2022-10-03 19:58:58   info: Gerbera UPnP Server 1.11.0 - http://gerbera.io/
Oct 03 19:58:58 mEdIa1 gerbera[47648]: 2022-10-03 19:58:58   info: Copyright 2016-2022 Gerbera Contributors.
Oct 03 19:58:58 mEdIa1 gerbera[47648]: 2022-10-03 19:58:58   info: Gerbera is free software, covered by the GNU General Public Licen>
Oct 03 19:58:58 mEdIa1 gerbera[47648]: 2022-10-03 19:58:58   info: Loading configuration from: /etc/gerbera/config.xml
Oct 03 19:58:58 mEdIa1 gerbera[47648]: 2022-10-03 19:58:58   info: Checking configuration...
Oct 03 19:58:58 mEdIa1 gerbera[47648]: 2022-10-03 19:58:58   info: Configuration check succeeded.
Oct 03 19:58:58 mEdIa1 gerbera[47648]: 2022-10-03 19:58:58   info: Running an automatic database upgrade from database version 12 to>
Oct 03 19:58:58 mEdIa1 gerbera[47648]: 2022-10-03 19:58:58  error: prematurely shutting down.
```
Where is the database, when running as a service? Is this the issue?
How do I capture a log?
How do I do a totally fresh install? ie remove all traces, and reinstall...

What is the problem?

**Comment by KarlStraussberger** [comment]
You original gerbera version was a bit older already, so you'd best delete the database
- sqlite: remove /etc/gerbera/gerbera.db
- mysql: drop all the tables in the gerbera database

**Comment by hornetster** [comment]
Thanks.
Have ended up totally uninstalling/reinstalling. Running as a service, removed the /var/lib/gerbera directory, and the /etc/gerbera directory, but when starting, only seems to get to "Configuration check suceeded", and won't progress from there.
Believe apache is installed correctly (running other web services), and was all working, I beleive, at least up until I updated from 20.04 to 22.04... (did have issues with apache, but believe that is all good now...?)
Thanks.

**Comment by KarlStraussberger** [comment]
First of all, gerbera does not need apache.

All files are specified in config.xml. If there is no absolute path the database is in <home>. The packages in the distros are outdated, so you should download from jfrog or use the docker container.
