### ISSUE TITLE
Docker latest isn't the most recent image

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#2720]
Perhaps this is on purpose but I was a bit caught off guard.

The `latest` Docker image tag is pointing to the v1.11.0 release. There have been some critical fixes between the last release and main branch.

**Comment by KarlStraussberger** [comment]
The latest tag points to the lastest official release which is 1.11. If time allows and no more major issues show up, I will create a new major soon.

**Comment by mill1000** [comment]
Indeed. Just some alternative ideas to consider to make fetching the HEAD easier.

- A `stable` tag could point to the latest release, and latest points to the most recent image.
- A `newest` tag that points to the most recent image.

**Comment by KarlStraussberger** [comment]
I would be lovely if you could provide a PR that works like you describe!
