### ISSUE TITLE
New Ubuntu installation: No UI +Long waiting time for closing gerbera

### ISSUE THREAD

**Issue by bernid** [gerbera/gerbera#2725]
Hello, 
I've just installed gerbera on my Ubuntu 22.04 x64 machine. I have two issues:
1. No web browser user interface.
In my /etc/gerbera/config.xml I have:
```
  <server>
    <ui enabled="yes" show-tooltips="yes">
      <accounts enabled="no" session-timeout="30">
        <account user="gerbera" password="gerbera" />
      </accounts>
    </ui>
```
So I assume That I shoud see: 

`INFO: The Web UI can be reached by following this link .....`
line reviewing status the massages but it doesn't. I see only:
```
ela@akacja:~$ sudo systemctl status gerbera
● gerbera.service - Gerbera Media Server with MySQL
     Loaded: loaded (/lib/systemd/system/gerbera.service; disabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-10-20 05:20:18 CEST; 3s ago
   Main PID: 3989 (gerbera)
      Tasks: 2 (limit: 8978)
     Memory: 9.3M
        CPU: 89ms
     CGroup: /system.slice/gerbera.service
             └─3989 /usr/bin/gerbera -c /etc/gerbera/config.xml

Oct 20 05:20:18 akacja systemd[1]: Started Gerbera Media Server with MySQL.
Oct 20 05:20:18 akacja gerbera[3989]: 2022-10-20 05:20:18   info: Gerbera UPnP Server 1.11.0 - http://gerbera.io/
Oct 20 05:20:18 akacja gerbera[3989]: 2022-10-20 05:20:18   info: Copyright 2016-2022 Gerbera Contributors.
Oct 20 05:20:18 akacja gerbera[3989]: 2022-10-20 05:20:18   info: Gerbera is free software, covered by the GNU General Public L>
Oct 20 05:20:18 akacja gerbera[3989]: 2022-10-20 05:20:18   info: Loading configuration from: /etc/gerbera/config.xml
Oct 20 05:20:18 akacja gerbera[3989]: 2022-10-20 05:20:18   info: Checking configuration...
Oct 20 05:20:18 akacja gerbera[3989]: 2022-10-20 05:20:18   info: Configuration check succeeded.
```
2. Long waiting time for closing
When I want to stop gerbera: 
`sudo systemctl stop gerbera`
it's take 90 sec. How can I speed up shutdown of gerbera?

**Comment by bernid** [comment]
Thanks for the answer. 
My home Ubuntu server has the following network interfaces:
```
ela@akacja:~$ ip addr show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 50:3e:aa:04:5a:62 brd ff:ff:ff:ff:ff:ff
    inet 10.10.10.1/24 brd 10.10.10.255 scope global enp2s0
       valid_lft forever preferred_lft forever
    inet6 fe80::523e:aaff:fe04:5a62/64 scope link
       valid_lft forever preferred_lft forever
3: enp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 70:85:c2:f7:da:ab brd ff:ff:ff:ff:ff:ff
    inet 192.168.15.244/24 brd 192.168.15.255 scope global enp3s0
       valid_lft forever preferred_lft forever
    inet6 fe80::7285:c2ff:fef7:daab/64 scope link
       valid_lft forever preferred_lft forever
4: wlp4s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e4:ce:8f:52:c9:89 brd ff:ff:ff:ff:ff:ff
    inet 10.10.11.1/24 brd 10.10.11.255 scope global wlp4s0
       valid_lft forever preferred_lft forever
    inet6 fe80::e6ce:8fff:fe52:c989/64 scope link
       valid_lft forever preferred_lft forever
5: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 10.8.0.1 peer 10.8.0.2/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::2faa:9be0:7c8c:a0c7/64 scope link stable-privacy
       valid_lft forever preferred_lft forever
```
enp3s0 is a WAN, enp2s0 -LAN;  wlp4s0 -WLAN

See more details from gerbera debug log:
https://www.dropbox.com/s/4xgos7hklgzrt4t/gerbera_log_debug.txt?raw=1

Why the Gerbera UI doesn't start?

**Comment by KarlStraussberger** [comment]
First of all: If you want wireless devices to stream media files you need some bonding device on top of `enp2s0` and `wlp4s0` for broadcasting ssdp packages to work (See; https://docs.gerbera.io/en/stable/run.html#network-setup  The commands are still old style - made a mental note to update).

For testing you 
- should add `<interface>enp2s0</interface>` to your config (right below home)
- should also run `rm /home/ela/gerbera.db*` to get rid of a potentially broken database
- should make sure that the gerbera user has write access to `/home/ela`!

**Comment by bernid** [comment]
Thanks, 
Web UI has started.
My wifi laptop and LG TV (wifi) has been recognized. See:
[https://www.dropbox.com/s/unb1xy84ociwiri/gerb.jpg?raw=1](url)

However TV does not see the Gerbera server.

**Comment by KarlStraussberger** [comment]
If you want to stream over the wifi network, check the wifi router how it handles broadcast.

Did you enable multicast on your wifi device `wlp4s0`?

Did you already import files that can be streamed? My LG Media Player browses all data on the server to build up an index and it may happen that it hides empty libraries.

**Comment by bernid** [comment]
I have reinstalled Gerbera with current, existing linux user (I delated gerbera user). I connected TV to the LAN   using ethernet cable. 
After that everything works fine. Thanks for support.
