### ISSUE TITLE
After upgrade to 1.11.0 gerbera will not start, table grb_cds_resource already exists

### ISSUE THREAD

**Issue by NormHenderson** [gerbera/gerbera#2728]
This appears to be some kind of database issue. I am running mysql 8.0.29 on Ubuntu 20.04.3.
`gerbera -D -f /etc/gerbera` fails to start:
2022-10-23 09:04:03   info: Gerbera UPnP Server 1.11.0 - http://gerbera.io/
2022-10-23 09:04:03   info: Copyright 2016-2022 Gerbera Contributors.
2022-10-23 09:04:03   info: Gerbera is free software, covered by the GNU General Public License version 2
2022-10-23 09:04:03   info: Loading configuration from: /etc/gerbera/config.xml
2022-10-23 09:04:03   info: Checking configuration...
2022-10-23 09:04:03   info: Configuration check succeeded.
2022-10-23 09:04:03   info: Running an automatic database upgrade from database version 12 to version 13...
2022-10-23 09:04:03  error: Mysql: error while updating db: mysql_error (1050): "Table 'grb_cds_resource' already exists"; query: CREATE TABLE ``grb_cds_resource`` (
            ``id`` int(11) primary key auto_increment,
            ``item_id`` int(11) NOT NULL,
            ``res_id`` int(11) NOT NULL,
            ``handlerType`` int(11) NOT NULL,
            ``options`` text default NULL,
            ``parameters`` text default NULL,
            CONSTRAINT ``grb_cds_resource_fk`` FOREIGN KEY (``item_id``) REFERENCES ``mt_cds_object`` (``id``) ON DELETE CASCADE ON UPDATE CASCADE
        ) ENGINE=MyISAM CHARSET=utf8

In mysql I tried:
`use gerbera;
drop table grb_cds_resource;
show tables;` (that table is not listed, trying the command on which gerbera fails:)
`CREATE TABLE ``grb_cds_resource`` ( ``id`` int(11) primary key auto_increment,
    ->             ``item_id`` int(11) NOT NULL,
    ->             ``res_id`` int(11) NOT NULL,
    ->             ``handlerType`` int(11) NOT NULL,
    ->             ``options`` text default NULL,
    ->             ``parameters`` text default NULL,
    ->             CONSTRAINT ``grb_cds_resource_fk`` FOREIGN KEY (``item_id``) REFERENCES ``mt_cds_object`` (``id``) ON DELETE CASCADE ON UPDATE CASCADE
    ->         ) ENGINE=MyISAM CHARSET=utf8;`
ERROR 1050 (42S01): Table 'grb_cds_resource' already exists

`show tables;` (indeed the table now exists)

`show create table grb_cds_resource;` (looks like the constraint is there also):
grb_cds_resource | CREATE TABLE ``grb_cds_resource`` (
  ``id`` int NOT NULL AUTO_INCREMENT,
  ``item_id`` int NOT NULL,
  ``res_id`` int NOT NULL,
  ``handlerType`` int NOT NULL,
  ``options`` text,
  ``parameters`` text,
  PRIMARY KEY (``id``),
  KEY ``grb_cds_resource_fk`` (``item_id``)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 |

I suppose I could update db_version from 12 to 13 in mt_internal_setting however I'm not sure what other database upgrades may be missing. Help please!

**Comment by KarlStraussberger** [comment]
All database updates are in /usr/local/share/gerbera. However, if you're upgrading from such an old version, it's better to drop all the tables and have the created from scratch - column order, etc.

Also you should reimport all your media to fully benfit from new features.

**Comment by NormHenderson** [comment]
Thank you!
