### ISSUE TITLE
process exits on exiv2 errors

### ISSUE THREAD

**Issue by mtdcr** [gerbera/gerbera#273]
```
terminate called after throwing an instance of 'Exiv2::BasicError<char>'
  what():  This does not look like a TIFF image
```
```
gerbera.service: Main process exited, code=killed, status=6/ABRT
gerbera.service: Failed with result 'signal'.
```
Unfortunately, I have no idea which file is causing this error.

**Comment by v00d00** [comment]
Can you run it under GDB and get us a backtrace?

**Comment by ausil** [comment]
terminate called after throwing an instance of 'Exiv2::BasicError<char>'
  what():  /srv/nfs/Media/Musica/70s on 1 Disk - Best of the 70s (146 files)/cover back.jpg: The file contains data of an unknown image type

Thread 14 "gerbera" received signal SIGABRT, Aborted.
[Switching to Thread 0xaedec370 (LWP 2684)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	  return ret;
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0xb65e725c in __GI_abort () at abort.c:79
#2  0xb6811e38 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0xb680f8c8 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0xb680f93c in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0xb680fca8 in __cxxabiv1::__cxa_throw (obj=obj@entry=0xb0d047d8, tinfo=0xb6bcde84 <typeinfo for Exiv2::BasicError<char>>, dest=0xb69f0130 <Exiv2::BasicError<char>::~BasicError()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0xb6a34e44 in Exiv2::ImageFactory::open (path="/srv/nfs/Media/Musica/70s on 1 Disk - Best of the 70s (146 files)/cover back.jpg", useCurl=useCurl@entry=true) at /usr/src/debug/exiv2-0.26-12.fc29.arm/src/image.cpp:854
#7  0x00499bd8 in Exiv2Handler::fillMetadata (this=this@entry=0xaedeba04, item=...) at /usr/include/c++/8/bits/char_traits.h:285
#8  0x0049b180 in MetadataHandler::setMetadata (item=...) at /usr/src/debug/gerbera-1.1.0-6.20180413git2f6dcb5.fc29.arm/src/zmm/ref.h:42
#9  0x00473acc in ContentManager::createObjectFromFile (this=this@entry=0x599e38, path=..., magic=magic@entry=true, allow_fifo=allow_fifo@entry=false) at /usr/src/debug/gerbera-1.1.0-6.20180413git2f6dcb5.fc29.arm/src/zmm/ref.h:42
#10 0x0047f498 in ContentManager::_addFile (this=this@entry=0x599e38, path=..., rootpath=<error reading variable: Cannot access memory at address 0x0>, recursive=recursive@entry=false, hidden=hidden@entry=false, task=...)
    at /usr/src/debug/gerbera-1.1.0-6.20180413git2f6dcb5.fc29.arm/src/content_manager.cc:495
#11 0x0047f9f0 in ContentManager::addFileInternal (this=this@entry=0x599e38, path=..., rootpath=..., recursive=recursive@entry=false, async=async@entry=false, hidden=false, lowPriority=lowPriority@entry=false, 
    parentTaskID=parentTaskID@entry=0, cancellable=cancellable@entry=true) at /usr/src/debug/gerbera-1.1.0-6.20180413git2f6dcb5.fc29.arm/src/zmm/ref.h:53
#12 0x004813a0 in ContentManager::_rescanDirectory (this=this@entry=0x599e38, containerID=<optimized out>, containerID@entry=5558, scanID=-1224742664, scanID@entry=0, scanMode=(unknown: 5645896), scanMode@entry=ScanMode::INotify, 
    scanLevel=scanLevel@entry=ScanLevel::Full, task=...) at /usr/src/debug/gerbera-1.1.0-6.20180413git2f6dcb5.fc29.arm/src/autoscan.h:170
#13 0x00481c08 in CMRescanDirectoryTask::run (this=0xb0d0cbd0) at /usr/src/debug/gerbera-1.1.0-6.20180413git2f6dcb5.fc29.arm/src/zmm/ref.h:48
#14 0x00480480 in ContentManager::threadProc (this=0x599e38) at /usr/src/debug/gerbera-1.1.0-6.20180413git2f6dcb5.fc29.arm/src/content_manager.cc:1259
#15 0x004809c8 in ContentManager::staticThreadProc (arg=<optimized out>) at /usr/src/debug/gerbera-1.1.0-6.20180413git2f6dcb5.fc29.arm/src/content_manager.cc:1279
#16 0xb6f974b0 in start_thread (arg=0xaedec370) at pthread_create.c:486
#17 0xb66a6b28 in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by v00d00** [comment]
This should be fixed in the referenced commit, are you running 1.2?

**Comment by ausil** [comment]
rpm -q gerbera
gerbera-1.1.0-6.20180413git2f6dcb5.fc29.armv7hl
looks like fedora needs an update
