### ISSUE TITLE
Fails to build on Fedora 38

### ISSUE THREAD

**Issue by limburgher** [gerbera/gerbera#2737]
Works fine on 37, on 38 we get:

<snip>

-- Found CURL: /usr/lib64/libcurl.so (found version "7.86.0")  
-- Found Taglib: /usr/lib64/libtag.so (found suitable version "1.12", minimum required is "1.12") 
-- Found LibMagic: /usr/lib64/libmagic.so  
-- Found EXIF: /usr/lib64/libexif.so (found version "") 
-- Found LibExiv2: /usr/lib64/libexiv2.so (found version "0.27.5") 
-- Found EBML: /usr/lib64/libebml.so  
-- Found Matroska: /usr/lib64/libmatroska.so  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.12") 
-- Could NOT find Systemd (missing: SYSTEMD_FOUND) 
CMake Error at CMakeLists.txt:572 (message):
  Systemd not found
-- Configuring incomplete, errors occurred!

**Comment by KarlStraussberger** [comment]
Seems your system is missing `systemd`

**Comment by neheb** [comment]
```
find_package(Systemd)
```

looks like a mistake. Gerbera does not use libsystemd at all.

**Comment by KarlStraussberger** [comment]
It's used to detect systemd in order to install the systemd unit file.

There is a cmake switch WITH_SYSTEMD to disable it.

**Comment by xvitaly** [comment]
https://github.com/gerbera/gerbera/blob/d257c0dfacfd358c4bc405ee85e22c50a05a0104/cmake/FindSystemd.cmake#L11 - it tries to find systemd.pc, but systemd only provides libsystemd.pc.

**Comment by xvitaly** [comment]
Oops, `systemd.pc` is provided by the main systemd package, not systemd-devel.

**Comment by xvitaly** [comment]
Fixed https://src.fedoraproject.org/rpms/gerbera/c/0f909036341f6a5a815006802f09ff65b3034c56?branch=rawhide. This issue can be closed.
