### ISSUE TITLE
Gerbera is outdated in most Linux distributions

### ISSUE THREAD

**Issue by ngosang** [gerbera/gerbera#2738]
I just notice Gerbera is outdated in several Linux distributions. Maybe you can get in touch with the maintainers or become maintainers yourself. The first time I installed Gerbera in Debian the experience was terrible. Now I'm using Docker and Gerbera is really good but the first impression matters when you install a new software.
https://repology.org/project/gerbera/versions

**Comment by KarlStraussberger** [comment]
The problem is that many distros focus on frontend features and reduce their efforts on services and required libraries like upnp.

As each of us has to earn his living from other work, we always welcome maintainers for more targets and programming support.

**Comment by flavorgold1** [comment]
This is why I use `gerbera` via `docker compose` in `network_mode: host`.

**Comment by xcom169** [comment]
Arch recently moved Gerbera from AUR to official repos. ☺️

**Comment by whyman** [comment]
Wow, thats right! We made it to Arch community repo https://archlinux.org/packages/community/x86_64/gerbera :tada:

**Comment by whyman** [comment]
We actually host Debian Repos and Ubuntu repos, as suggested if your Distros's gerbera is too old we suggest docker installation instead.

Practically we do not have the time to package for every distro, and appreciate downstreams are busy.
