### ISSUE TITLE
Windows Explorer not displaying Gerbera 1.12 contents

### ISSUE THREAD

**Issue by 1a2m3** [gerbera/gerbera#2756]
Running Gerbera on FreeBSD. uname -a output:

```
root@mediatomb:~ # uname -a
FreeBSD mediatomb 13.1-RELEASE-p2 FreeBSD 13.1-RELEASE-p2 n245412-484f039b1d0 TRUENAS  amd64
```

After updating Gerbera to 1.12, Windows Explorer is not showing any database contents. Gerbera is present in My Computer, but when opening it in Explorer, it takes a very long time to load and in the end shows up as empty.

![image](https://user-images.githubusercontent.com/65949266/204915581-925152d2-c953-4681-bba7-a4fbd2000a85.png)

![image](https://user-images.githubusercontent.com/65949266/204915649-7efd5401-4ee6-4e7e-9a28-3c6f7feec686.png)

![image](https://user-images.githubusercontent.com/65949266/204915681-1f7d69a5-acfc-4785-84e8-d482d53d723c.png)

Gerbera sees my computer as the following client: 

<html><body>

IP Address | Host Name | Group | Profile | User Agent | Match Type | Match Pattern | Client Type | First Seen | Last Seen | Quirk Flags
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
192.168.1.xxx | 192.168.1.xxx | default | Standard UPnP | Microsoft-Windows/10.0 UPnP/1.0 Microsoft-DLNA DLNADOC/1.50 | UserAgent | UPnP/1.0 | StandardUPnP | Wed Nov 30 12:14:03 2022 | Wed Nov 30 13:39:58 2022 | None

</body>
</html>

I tried deleting the database and recreated it, but that didn't do anything. Restarted Gerbera service, restarted the host system it is running on, but still Explorer show nothing.

Web interface shows contents just fine. 

![image](https://user-images.githubusercontent.com/65949266/204917179-06edcd54-4bdc-488e-a8ac-3e995be3e9f7.png)

WD TV Live media player also sees Gerbera and its contents just fine as well.

Previous version was accessible via Windows Explorer just fine, but something is broken in v 1.12.

**Comment by KarlStraussberger** [comment]
Thank you for the hint. I tried myself and got the same result. I'm not sure whether this is a Windows issue or a gerbera issue because we only get two requests: `IsAuthorized` and `IsValidated` and there was no change in that code for ages.

**Comment by KarlStraussberger** [comment]
It seems that explorer does not understand ui8 datatype in service descriptions.

You can fix the issue by changing `ui8` to `ui4` in `share/gerbera/web/cds.xml`

**Comment by 1a2m3** [comment]
> It seems that explorer does not understand ui8 datatype in service descriptions.
> You can fix the issue by changing `ui8` to `ui4` in `share/gerbera/web/cds.xml`

Unfortunately that didn't do anything. 

What did help however, is deleting old `gerbera-config.xml` I've been using since the beginning, and copying over new `gerbera-config.xml`. With the new config file Explorer sees contents regardless of `ui8` or `ui4` data type in `share/gerbera/web/cds.xml`.

![gerbera-explorer-ok](https://user-images.githubusercontent.com/65949266/205190836-db58e857-6cfd-4399-9991-8edd093acf09.png)

If you need, I can provide my old and new config xml files, if that will help you figure out what settings prevent Windows Explorer from seeing Gerbera contents.

**Comment by KarlStraussberger** [comment]
The service needs a restart after the change. Maybe that did the trick.
