### ISSUE TITLE
Permission problem

### ISSUE THREAD

**Issue by dln949** [gerbera/gerbera#278]
When I try to navigate to a directory in the Filesystem tab, I get an error message saying I do not have permission to access the directory.  I am logged in as the administrative user.  I am running Ubuntu 17.10.  The attached image file shows the error message I am getting.  

How do I fix this problem?  WHY is it a problem, I don't  understand why I am getting this error message.  

Thanks for any help.  
![error](https://user-images.githubusercontent.com/8601150/38346318-d9f72ec0-3859-11e8-9fb7-d0ec661042c6.png)

**Comment by elmodaddyb** [comment]
That is an unfortunate error.   Perhaps the  `gerbera` process running the web server may be running as a different user that doesn’t have perms?

Can you see what details the process is running under?  The command below will find the running gerbera process. 

```
ps aux | grep gerbera
```

**Comment by dln949** [comment]
Here is the output, can't say that I understand it......  

main19@system19:~$ ps aux | grep gerbera
gerbera  16992  0.0  0.1 1067432 13184 ?       Ssl  22:56   0:00 /usr/bin/gerbera -c /etc/gerbera/config.xml -l /var/log/gerbera -e eth0
main19   20022  0.0  0.0  14352  1080 pts/0    S+   23:06   0:00 grep --color=auto gerbera
main19@system19:~$

**Comment by dln949** [comment]
Thanks for your help!  When I ran the command you suggested, I saw that the permission setting on the /media directory was set to allow no access at all for anyone not in the root group.  I changed the settings for "Others" to be r-x, and now the problem has gone away.
