### ISSUE TITLE
How to make gerbera service start as part of system startup

### ISSUE THREAD

**Issue by dln949** [gerbera/gerbera#279]
I am running Ubuntu 17.10.  After looking through the documentation, I still don't understand how I can control whether gerbera starts when the Ubuntu system starts.  How do I do that?

**Comment by elmodaddyb** [comment]
Yea, I agree with you...there is a bit of gap in the documentation for configuring Gerbera under Ubuntu.

I made some assumptions you may need to verify.

1. Your system has a startup script under `/etc/init.d/gerbera`
2. You want Gerbera to startup as a daemon

Maybe you can use the `update-rc.d` command to add the startup script to a specific run level.

Here is a good tutorial to understand the capability [https://www.debuntu.org/how-to-managing-services-with-update-rc-d/]().

Here is an example, _it has not been tested_.

```
./update-rc.d gerbera defaults
```

Let me know if this helps?

**Comment by v00d00** [comment]
17.10 runs systemd.

To start: `sudo systemctl start gerbera`
To stop `sudo systemctl stop gerbera`

To start at boot `systemctl enable gerbera`
To remove start at boot `systemctl disable gerbera`
