### ISSUE TITLE
Screeshot npm task - Blank screenshots

### ISSUE THREAD

**Issue by v00d00** [gerbera/gerbera#280]
I ran the screenshot update task, but I ended up with black pngs :-1:  Should have checked them before I committed, see: 7df94d24a0668cb365d2df1f1e8a76e7d42aaa93

Chrome popped up and was doing things so I assumed everything was OK.

`Chrome 65.0.3325.181 ` `Chromedriver 2.37`

Do I need to do something else to make it work?

**Comment by elmodaddyb** [comment]
@v00d00 - Please excuse the lack of documentation around the `npm doc:screenshot` task.  It is a bit of a work in progress to make it cross-platform.

_I think I encountered the blank screen before when the Chrome window is not in focus??_

> If that doesnt work then...

There are 2 aspects.

1. Selenium Driver - takes screenshot of browser, dumping file to directory
2. Jimp manipulates image file to size, and crop

I think the black screen is a **selenium driver issue**.  However, I run same specs on my linux machine and it produces screenshots.

If you can try the following it might help isolate the problem.
1. Focus one test using `test.it.only(...`
2. Disable `Jimp` manipulation, obtaining just the selenium screen

Here's a sample:

```javascript
  test.it.only('for [login] field entry', function (done) {
    var fileName = DEFAULT_FOLDER_STORE + 'login-field-entry.png'
    loginPage.username('gerbera')
    loginPage.takeScreenshot(fileName).then(function () {
      // Jimp.read(fileName).then(function (image) {
      //   image.resize(1280, 1024)
      //   image.crop(0, 0, 1270, 100).write(fileName)
         done()
      // });
    })
  })
```
I will also work to see what reproduces black screenshots...

**Comment by elmodaddyb** [comment]
New screenshot test UI will require `home.page.js` to be updated with new mock task with params:

```javascript
this.mockTaskMessage = function (msg) {
    return driver.executeScript('return $(\'#toast\').toast(\'showTask\', {message: "'+ msg +'", type: "info", icon: "fa-refresh fa-spin fa-fw"});')
}
```

**Comment by elmodaddyb** [comment]
some of the coordinates in Jimp are also incorrect due to UI changes.
