### ISSUE TITLE
Docker image is not able to render thumbnails from movies because of missing jpeg-support

### ISSUE THREAD

**Issue by sven-probst** [gerbera/gerbera#2800]
The docker image is not able to render thumbnails from movies because of missing jpeg-support.

This can easy be fixed by attached patch. The config is already perfect to render images.

```
diff --git a/Dockerfile b/Dockerfile
index 2adb57e7..e5ce5100 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,6 +7,7 @@ RUN apk add --no-cache  \
     curl-dev \
     duktape-dev \
     ffmpeg4-dev \
+    jpeg-dev \
     file-dev \
     fmt-dev \
     g++ \
```

**Comment by whyman** [comment]
Seems sensible enough

**Comment by KarlStraussberger** [comment]
@sven-probst which is the correct runtime package `jpeg` or `libjpeg`

**Comment by sven-probst** [comment]
libjpeg-turbo is the installed apk

**Comment by KarlStraussberger** [comment]
@sven-probst Can you take a look at #2801. please

**Comment by sven-probst** [comment]
works like a charm
