### ISSUE TITLE
Duplicated albums in HEOS App (Android/iOS) when using gerbera

### ISSUE THREAD

**Issue by gobater** [gerbera/gerbera#2805]
I listen to the music of my DLNA Server into my HEOS devices (Denon).

The way that gerbera manages its database, confuses the HEOS App. As I can see in the "common.js" file, the albums are added twice into the database.

First below "Artist"
```
    obj.title = track + title;
    for (i = 0; i < artCnt; i++) {
        chain.artist.title = artist[i];
        chain.artist.searchable = true;
        container = addContainerTree([chain.audio, chain.allArtists, chain.artist, chain.album]);
        addCdsObject(obj, container);
    }
```
and second below "All Albums"
```
    chain.album.searchable = true;
    container = addContainerTree([chain.audio, chain.allAlbums, chain.album]);
    obj.title = track + title;
    addCdsObject(obj, container);
```

I guess, that the UPNP CDS does not reference the same (same ID) Album Container twice. Probably it adds two different containers (with different IDs) referencing the same physical files.

Because gerbera offers those containers with a different object ID, "smart" DLNA clients like HEOS (which is able to dynamically create the content of the "Albums" category) confuse the content on the server and thinks that there are two albums with the same name (see screenshot)

Other DLNA servers (like the one included in my FritzBox or minidlna), show also the albums under two different categories (verified with BubbleUpnp) but the HEOS App does not show them as duplicated. Probably they reference the same ID

gerbera:
![Screenshot HEOS App with gerbera](https://user-images.githubusercontent.com/23657567/221379735-557b3b24-1d8e-49a6-9945-62aba5301b76.png)

minidlna:
![Screenshot HEOS App with minidln](https://user-images.githubusercontent.com/23657567/221381233-4d914d68-c90e-402d-a789-b8f465c3e5d6.png)

**Comment by KarlStraussberger** [comment]
Hello,
thanks for the detailled dsscription of your issue. I think there is a simple solution to this (my HEOS does not duplicate albums).

You need to set
`<upnp searchable-container
-flag="yes">` in your `config.xml` (https://docs.gerbera.io/en/latest/config-server.html#upnp). It only works if you imported your media with gerbera 1.9.x or later (version is just a guess; the later the better)

The `upnp` section should already be there.

**Comment by gobater** [comment]
Hi @KarlStraussberger ,
Thanks for your answer, that made the trick! Now I don't see anymore those duplicates and everything seems to look like I expected :-)
Somehow weird, I'm using latest Gerbera (1.12.1) (fresh install) and the upnp section was not available in my "config.xml", maybe it's missing in the 'bullseye' package from the repos... 

I guess this is a HEOS specific topic, right? Maybe a Troubleshooting section in the documentation mentioning this for configuration tweak for HEOS devices could help other users in the future...

I would have never figured it by myself without you. Thanks!

How is the sorting in the Albums list made? Somehow "La Estación Seca" appears before "La danza de Araña" (notice uppercase 'E' and lowercase 'd'). Does the publication year have any influence on it?
