### ISSUE TITLE
follow-symlinks option does not work (v1.12.1)

### ISSUE THREAD

**Issue by gobater** [gerbera/gerbera#2806]
When the Folder I try to import into my library is a symlink, the follow-symlink option (UI or Config File) does not work (Gerbera v1.12.1)

It's not a permissions issue. The ACLs allow gerbera user to access tte symlink and the target folder. Importing the target folder directly works.

**Comment by KarlStraussberger** [comment]
As it works (disabled) on my side: can you give some more details
- config.xml
- file system structure
- expected behaviour
- observed behaviour
- operating system incl. distro and flavours
- logs while importing (e.g. rename link)

**Comment by gobater** [comment]
Somehow I tried it again and it works (at least via config file). Not sure what I did different this time :-(

Thank you for your support

**Comment by gobater** [comment]
I've been able to reproduce. The issue is an "UI-only issue".
Steps to reproduce:
1. Stop gerbera
2. Backup your database (/var/lib/gerbera/gerbera.db)
3. Delete your database
4. Comment out all the autoscan directories in config file (/etc/gerbera/config.xml)
5. Start gerbera
6. Navigate with your webbrowser to the Gerbera UI and go to the "File System" tab.
7. Then, select in the left (filesystem tree) a folder that is a symlink (in my case /media/dlna) and press the "+" icon in the right (add item). Note that the UI is able to see the content of the symlink
8. In the navigation bar, go now to "Database" and verify that no items have been added.

![image](https://user-images.githubusercontent.com/23657567/230298874-7d64e214-86de-4d31-be14-c283b6d925c7.png)

If instead of selecting the symlink (/media/dlna), I select a folder below ("/media/dlna/Bad Religion") all the folders below are scanned and included into the database.

If I redo exactly the same but instead of using "/media/dlna" using the folder where the symlink is pointing to (/mnt/usb-stick/media) it works without issues. All subfolders get added.

**Comment by KarlStraussberger** [comment]
First of all to have the same effect as the config file entry you need to use the second icon (Add Autoscan Item).

Second, there is an issue in https://github.com/gerbera/gerbera/blob/e474734302609863cab9dd0efe86b70e400cdd46/src/web/add.cc#L53-L54 which does not set followSymlinks.

**Comment by KarlStraussberger** [comment]
Maybe you can confirm that the fix resolves your issue.

**Comment by gobater** [comment]
I will double check and provide feedback asap, but I am quite sure that I've also tried the second Icon (Add autoscan) and selected all relevant options (follow symlinks and recursive).
Add Item (first icon) already works recursive for me: adding "/media/dlna/Bad Religion", which does not contain any files (only subfolders containing files) works fine.
My music library is organized as follows:
/ Artist / Year - Album / tracks.mp3

I will try the original release again and also the patch mentioned above and provide feedback

**Comment by gobater** [comment]
So, I can confirm, that using the second icon (Add autoscan item) it works as expected (exactly like it does via config file, as you correctly mentioned).
I will give a try to the patch ad provide feedback 👍🏻
