### ISSUE TITLE
My old Philips smart TV can't see Gerbera server anymore

### ISSUE THREAD

**Issue by xcom169** [gerbera/gerbera#2816]
Hello All,

My old Philips smart TV can't see Gerbera server anymore.  Is it possible to switch legacy mode on for a client?

**Comment by KarlStraussberger** [comment]
There is no old or new version of upnp.

So, the question is: when did it last work? Did you change the network/firewall settings, router or update your os?

Please include
- gerbera version
- os version / distro / container
- gerbera logs (--debug)
- gerbera config.xml server section

**Comment by xcom169** [comment]
Ethernet was wrong not Gerbera..
