### ISSUE TITLE
Items with empty date/year tags get date metadata populated by file modification time

### ISSUE THREAD

**Issue by mill1000** [gerbera/gerbera#2823]
I have a number of items in my library that do not have any date or year tags. I refer to these as items with "unknown" year. In my custom import script I tried to group these items into an Unknown year/decade container, but discovered each item has it's date metadata field populated with the file modification time.

Here's at least 2 case I found where this happens. I'm unaware of what the original intent behind this choice is but it's making it difficult to properly organize the library.
https://github.com/gerbera/gerbera/blob/63ff8e785ad4d631e519874523d5e31afcfa8933/src/database/sql_database.cc#L1457-L1458
https://github.com/gerbera/gerbera/blob/63ff8e785ad4d631e519874523d5e31afcfa8933/src/content/import_service.cc#L508-L509

**Comment by mill1000** [comment]
As a workaround, I'm performing a check for mtime dates by assuming it's a full ISO8601timestamp with this lazy regex.
```js
  var date = get(obj.metaData[M_DATE]);

  if (/.*T.*/.test(date)) {
    // Date appears to be a file modification time, ignore it
    date = "Unknown"
  }
```

**Comment by KarlStraussberger** [comment]
As far as I remember, it came in because missing dates broke sorting and searching.

**Comment by KarlStraussberger** [comment]
Added a config option to block the behaviour. The reasons was some device with a sort request for "+dc:date" which does not work with empty date. So, if you set `<import default-date="no">` now and reimport everything you cannot sort those item.
