### ISSUE TITLE
JFrog is killing off their free tier in 30 DAYS! Need to find a new DEB host

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#2829]
Per this lovely email:

> Hi Ian,
>
> We have an important update to share. We’re sunsetting our JFrog Free Tier service. This means your JFrog account is scheduled for deactivation in 30 days from now, and your data will be permanently removed.
> 
> To avoid losing access to your instance and data, we encourage you to easily upgrade to a paid account by visiting MyJFrog.
> 
> Please feel free to book some time with me, I am more than happy to answer all of your questions and help you with an upgrade if needed.

**Comment by KarlStraussberger** [comment]
This is really 💩 . I'm not using debian myself so I'm not familiar with any hosting thereof.

The other option would be to start some fundraising to get a paid account.

**Comment by whyman** [comment]
Yeah its very crap! Hopefully I will get some time to look at it.

I have applied for the jfrog OSS program, but havent had any response yet.

**Comment by whyman** [comment]
It still seems to be up, so I guess the OSS sponsorship went through in time.

Thanks jfrogn
