### ISSUE TITLE
Transcoding of flac files is not working

### ISSUE THREAD

**Issue by summerroman** [gerbera/gerbera#2830]
Hello together,

because one of my DLNA clients - my television "Metz Clarea 47TW08" - doesn't support the "flac" audio format, I tried to configure transcoding of "flac" files to "wav" ("pcm") on my Gerbera server.
I'm using the current Gerbera version 1.12.1 inside of a  Docker container (gerbera/gerbera 1.12.1-transcoding) on my QNAP NAS TS-453Be in the container station.
There I configured transcoding for the mime types "audio/flac" and "audio/x-flac" to "audio/mpeg" (mp3) and "audio/x-wav" (pcm) (see my attached [config.xml](https://github.com/gerbera/gerbera/files/11715072/config.txt)).

After I configured the transcoding, the flac files appeared on my television but did not play with the error message (translated from german): "The file could not be played! (file not found)"
So I guess, the mime type mapping was right.
 
Inside of the sysout [log](https://github.com/gerbera/gerbera/files/11715073/gerbera-error.log), I noticed that an exception in the `FileRequestHandler` class at line `79` appeared: `Requested resource 2147483647 does not exist`
Scrolling up in the log file, the file `/content/media/object_id/560/res_id/2147483647/pr_name/ogg2mp3/tr/1/ext/file.mp3` should be created for transcoding, but after I looked inside of the file system, the file was not there. The content directory was completely empty. (But I'm not sure if this is the cause, because the documentation says, the transcoding is done on the fly.) 

I also checked the transcoding command like described inside of gerbera documentation and in my opinion it works correctly.

Perhaps you can help me by the solution of this problem because I'm not sure if this is an configuration issue or an issue inside of the sources.

Thank you for your help.

Kind regards

Roman Summer

**Comment by KarlStraussberger** [comment]
Thank you for your detailed report. It seems that transcoding broke in some place when reworking resource handling and nobody reported since.

Basically the fix should be quite easy so I can provide a quick PR which I hope you will be able to test on your NAS.

Metz used to be a really great brand!

**Comment by summerroman** [comment]
Thank you for your answer and the quick fix.

If I understand the fix right with my limited C++ knowledge (beause I'm mainly a Java and Oracle Forms developer), in the case of transcoding the resource identifier is negative and the transmitted transcoding profile is not empty. This was not checked correctly because the transcoding profile was not considered in the case of determining the resource on the file system. Is that right?

Furthermore if I want to test the fix in my docker container, is there a description building the gerbera container with transcoding tools from the master branch or is there a version on docker hub or somewhere which points to the current master branch? In the [documentation](https://docs.gerbera.io/en/stable/compile.html#build-docker-container-on-ubuntu) I only found the commands for building the container without the transcoding tools `vlc` and `ffmpeg`.

One question beside this, is it possible to configure transcoding only for a single client e.g. based on the `client-flags` by defining the client by ip address? (This is because all my other devices support flac natively and I don't know how good its implementation of mime type choosing is.)
I read about this in the documentatuion [here](https://docs.gerbera.io/en/stable/config-transcode.html) and [here](https://docs.gerbera.io/en/stable/config-clients.html) but I'm not sure if I am limited to the predefined client flags or if I can specify my own ones by name (e.g. `SAMSUNG`) and or id (like `0x100` or  `0x200`).

Thank you for your reply and have a nice day :-)

Roman

**Comment by summerroman** [comment]
Can I also use `gerbera/gerbera:edge-transcoding` on 
[Docker Hub](https://hub.docker.com/layers/gerbera/gerbera/edge-transcoding/images/sha256-06b4e1d7f6a05817e70650eac67d98cd78f9470b7ecbfd3a1fd89b1c892580ba?context=explore) for testing the fix?

**Comment by KarlStraussberger** [comment]
Yes, that is the latest and includes the fix.

**Comment by summerroman** [comment]
Thank you for the information. I will test it and give you a feedback.

**Comment by summerroman** [comment]
Yesterday I found the time to test the fix of the issue.

The good news is that the fix solves the problem inside of the `FileRequestHandler` so that the transcoding starts.

After that I had some trouble finding the right transcoding command. At least I found the following command which I tested on my Ubuntu desktop system:

`<agent command="vlc" arguments='-I dummy --sout #transcode{acodec=s16l,samplerate=44100,channels=2}:standard{access=file,mux=wav,dst=%out} %in vlc://quit' />`

A little bit confusing was, that I had to quote the transcode command on my desktop system like this:

**terminal 1**
1. make the fifo
`mkfifo out.pcm `
2. start transcoding
`vlc -I dummy --sout "#transcode{acodec=s16b,ab=192,samplerate=44100,channels=2}:standard{access=file,mux=pcm,dst=out.pcm}" in.flac vlc://quit`

**terminal 2**
3. play the file with vlc (the command vlc out.pcm described in the troubleshooting section of the documentation did not work!)
`vlc - < out.pcm`

Executing the configuration on gerbera:edge-transcoding I ran into the problem, that transcoding restats ever and ever because the defined buffer has not been filled (see the attached (ans zipped) [gerbera-log.zip](https://github.com/gerbera/gerbera/files/11753287/gerbera-edge-debug.zip) beginning at line `240927` and [config.xml](https://github.com/gerbera/gerbera/files/11753272/config.xml.txt) for details). On my network audio player (Denon DNP-730AE) I tested with, the buffer fill status was around `30%`. 

`2023-06-14 22:45:56.489  trace: [thread_runner.h:124] notify(): ThreadRunner: Notifying BufferHelperThread`
`2023-06-14 22:45:56.489  trace: [buffered_io_handler.cc:94] threadProc(): buffer fill level: 0.20%  (bufSize: 1048576; a: 0; b: 2048)`

So could there be a problem with the BufferHelperThread or is this already a problem with the transcoding command?!

`2023-06-14 22:45:54.459  trace: [process_executor.cc:77] ProcessExecutor(): Launching process: vlc -I dummy --sout #transcode{acodec=s16l,samplerate=44100,channels=2}:standard{access=file,mux=wav,dst=/tmp/grb-tr-30d12721-e10c-43be-ae7a-38ee2d297737} /media/music/Country/Faith Hill - The Hits/01 - Red Umbrella.flac vlc://quit`

I also tried to disable buffering by setting the buffer values (`size`, `chunk-size` and `fill-size`) to `0`. But this run into an error.  Testing with gerbera in version `1.10` the problem is the same (since gerbera version `1.11.0` there seemed to be the bug in the `FileRequestHandler`).

Now I'm a little bit confused by finding the next step of the analysis. Perhaps you can read something out of the log file.
