### ISSUE TITLE
transcoding to audio/x-wav failed: transcoding buffer not filled completely (see issue #2830) 

### ISSUE THREAD

**Issue by summerroman** [gerbera/gerbera#2833]
Hello together,

Yesterday I found the time to test the fix of the issue #2830. This issue has been closed, so I created a new one because a follow up problem appeared.

The good news is that the fix solves the problem inside of the `FileRequestHandler` so that the transcoding starts.

After that I had some trouble finding the right transcoding command. At least I found the following command which I tested on my Ubuntu desktop system:

`<agent command="vlc" arguments='-I dummy --sout #transcode{acodec=s16l,samplerate=44100,channels=2}:standard{access=file,mux=wav,dst=%out} %in vlc://quit' />`

A little bit confusing was, that I had to quote the transcode command on my desktop system like this:

**terminal 1**
1. make the fifo
`mkfifo out.pcm `
2. start transcoding
`vlc -I dummy --sout "#transcode{acodec=s16b,ab=192,samplerate=44100,channels=2}:standard{access=file,mux=pcm,dst=out.pcm}" in.flac vlc://quit`

**terminal 2**
3. play the file with vlc (the command vlc out.pcm described in the troubleshooting section of the documentation did not work!)
`vlc - < out.pcm`

Executing the configuration on gerbera:edge-transcoding I ran into the problem, that transcoding restats ever and ever because the defined buffer has not been filled (see the attached (ans zipped) [gerbera-log.zip](https://github.com/gerbera/gerbera/files/11753287/gerbera-edge-debug.zip) beginning at line `240927` and [config.xml](https://github.com/gerbera/gerbera/files/11753272/config.xml.txt) for details). On my network audio player (Denon DNP-730AE) I tested with, the buffer fill status was around `30%`. 

`2023-06-14 22:45:56.489  trace: [thread_runner.h:124] notify(): ThreadRunner: Notifying BufferHelperThread`
`2023-06-14 22:45:56.489  trace: [buffered_io_handler.cc:94] threadProc(): buffer fill level: 0.20%  (bufSize: 1048576; a: 0; b: 2048)`

So could there be a problem with the BufferHelperThread or is this already a problem with the transcoding command?!

`2023-06-14 22:45:54.459  trace: [process_executor.cc:77] ProcessExecutor(): Launching process: vlc -I dummy --sout #transcode{acodec=s16l,samplerate=44100,channels=2}:standard{access=file,mux=wav,dst=/tmp/grb-tr-30d12721-e10c-43be-ae7a-38ee2d297737} /media/music/Country/Faith Hill - The Hits/01 - Red Umbrella.flac vlc://quit`

I also tried to disable buffering by setting the buffer values (`size`, `chunk-size` and `fill-size`) to `0`. But this run into an error.  Testing with gerbera in version `1.10` the problem is the same (since gerbera version `1.11.0` there seemed to be the bug in the `FileRequestHandler`).

Now I'm a little bit confused by finding the next step of the analysis. Perhaps you can read something out of the log file.

_Originally posted by @summerroman in https://github.com/gerbera/gerbera/issues/2830#issuecomment-1592415787_

**Comment by KarlStraussberger** [comment]
DId you just try reducing the fill size.

Next to it I see changes in the vlc command ()it has to be `vlc://quit` now -> documentation update required!). Is it correct to have the `%in`after the `--sout` option (either documentation update or issue here)?

_The quotes are necessary because on shell level braces are syntax elements._

**Comment by KarlStraussberger** [comment]
You may also add a `-vv` to your command to see more `vlc` output

**Comment by summerroman** [comment]
Thank you for your reply.

Because of your hints, I reduced the fill-size to 1024 bytes and changed the agent line to the following:
`<agent command="vlc" arguments="-I dummy -vv --sout #transcode{acodec=s16l,samplerate=44100,channels=2}:standard{access=file,mux=wav,dst=%out} %in vlc://quit" />`

Testing the transcoding again, I noticed, that the vlc command was executed again and again as long the player tried to  play the stream to be transdoded. Here the output of the vlc command: 
[vlc.out.txt](https://github.com/gerbera/gerbera/files/11769303/vlc.out.txt)

There, I saw the following warning at demuxing:
```
[00007f2a008a83d0] main demux meta debug: looking for meta reader module matching "any": 2 candidates
[00007f2a008a83d0] main demux meta debug: using meta reader module "taglib"
[00007f29fab82850] main demux debug: removing module "taglib"
[00007f2a00d20630] main input debug: `file:///media/music/Country/Faith%20Hill%20-%20The%20Hits/01%20-%20Red%20Umbrella.flac' successfully opened
[00007f2a00d20630] main input debug: Buffering 0%
[00007f2a00d20630] main input debug: switching to async mode
[00007f2a00d20630] main input debug: Buffering 9%
[00007f2a00d20630] main input debug: Buffering 18%
[00007f2a00d20630] main input debug: Buffering 27%
[00007f2a00d20630] main input debug: Buffering 37%
[00007f2a00d20630] main input debug: Buffering 46%
[00007f2a00d20630] main input debug: Buffering 55%
[00007f2a00d20630] main input debug: Buffering 65%
[00007f2a00d20630] main input debug: Buffering 74%
[00007f2a00d20630] main input debug: Buffering 83%
[00007f2a00d20630] main input debug: Buffering 92%
[00007f29facc9c00] flac demux packetizer warning: discarding bytes as we're over framesize 14001, 20794
[00007f29facc9c00] flac demux packetizer debug: emulated sync word
[00007f2a00d20630] main input debug: Stream buffering done (1114 ms in 0 ms)
```

So, I guess there seeems to be a problem in the transcoding process by vlc.

**Comment by summerroman** [comment]
After this, I tried transcoding with the following changed options and transcoding worked!
`<agent command="ffmpeg" arguments="-loglevel debug -i %in -f wav -ar 44100 -ac 2 -y %out" />`
`<accept-url>no</accept-url>`

Looking at the player, the title info begins to switch through the titles (so it shows other titles than currently played and switched through them!).

**Comment by summerroman** [comment]
Using the following settings the transcoding feature works on my Metz TV which doesn't support the flac format natively. I transcode to mp3 because the device doesn't support wav/pcm correctly:

```
  <transcoding enabled="yes">
    <mimetype-profile-mappings>
      <transcode mimetype="audio/x-flac" using="audio2mp3" />
      <transcode mimetype="audio/flac" using="audio2mp3" />
    </mimetype-profile-mappings>
    <profiles>
      <profile name="audio2mp3" enabled="yes" type="external">
        <mimetype>audio/mpeg</mimetype>
        <dlna-profile>MP3</dlna-profile>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource> 
        <hide-original-resource>no</hide-original-resource>
        <accept-ogg-theora>no</accept-ogg-theora>
        <sample-frequency>44100</sample-frequency>
        <audio-channels>2</audio-channels>
        <agent command="ffmpeg" arguments="-loglevel debug -vn -i %in -ab 320k -f mp3 -y %out" />
        <thumbnail>yes</thumbnail>
        <buffer size="1048576" chunk-size="131072" fill-size="262144" />
      </profile>
    </profiles>
  </transcoding>
```

Important is here, the `-vn` option in the ffmpeg command which tells ffmpeg to skip cover art because this will lead to an error.

Because my other players supports the flac format natively and because of performance reasons, I wanted to enable transcoding only for one special client. I issue #1738 I saw, that you already used client flags for this but I don't know which own flag I can use in the client and transcoding configuration (or do I have to use a global flag like `STRICTXML|0x100` ) The documentation says I have to use an integer value (like `1` ?)

**Comment by summerroman** [comment]
With the following configuration entries it works for me, but I'm not shure if the client flag `STRICTXML` is right:

```
<config>
<!--
... 
-->
  <transcoding enabled="yes">
    <mimetype-profile-mappings>
      <transcode mimetype="audio/x-flac" client-flags="STRICTXML" using="audio2mp3" />
      <transcode mimetype="audio/flac" client-flags="STRICTXML" using="audio2mp3"  />
    </mimetype-profile-mappings>
    <profiles>
      <profile name="audio2mp3" enabled="yes" type="external">
        <mimetype>audio/mpeg</mimetype>
        <dlna-profile>MP3</dlna-profile>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource> 
        <hide-original-resource>no</hide-original-resource>
        <accept-ogg-theora>no</accept-ogg-theora>
        <sample-frequency>44100</sample-frequency>
        <audio-channels>2</audio-channels>
        <agent command="ffmpeg" arguments="-loglevel error -vn -i %in -ab 320k -f mp3 -y %out" />
        <thumbnail>yes</thumbnail>
        <buffer size="1048576" chunk-size="131072" fill-size="262144" />
      </profile>
    </profiles>
  </transcoding>
  <clients enabled="yes">
    <client ip="172.16.0.115" flags="STRICTXML"></client>
  </clients>
</config>
```

**Comment by KarlStraussberger** [comment]
This sounds really promising.

The client flags that enable special handling are listed under https://docs.gerbera.io/en/latest/supported-devices.html 

If you want to avoid this, you can use something link `0x1000`. It should be some hex number to avoid collision with defined values.

**Comment by KarlStraussberger** [comment]
As a quite natural effect transcoded streams cannot be searched because they are created in chunks in the buffer and dropped after being used.

**Comment by summerroman** [comment]
Thank you for your reply.

If I understand it right, I can use some hexadecimal values as unnamed flags not defined in the `supported devices` like `0x1000` or `0x200`. So I will try this.

Regarding to your information about the search inside of transcoded streams, I only want to clearyfy that the sentence "play/pause and back / forward stops working" meant that navigating to the next or previous track didn't work in the case of the transcoding configuration with audio/x-wav (LPCM). 

In addition I think it could be useful for other users to add some example transcoding configurations to the documentation (like complete profile xml elements). What do you think about this?

**Comment by KarlStraussberger** [comment]
I already prepared some stuff (incl config_generator). If you want to contribute, post it here and I'll add it once my current PR is done.

**Comment by summerroman** [comment]
Okay. I'll prepare something and will add it as comment to this issue.
