### ISSUE TITLE
FLAC not playing on Deneon X2200W (when using virtualURL)

### ISSUE THREAD

**Issue by count00zero** [gerbera/gerbera#2835]
Dear Devs,

I have got a very unusual problem, which doesn't leave any trace even when complied with debug and debugmode enabled ...
When I use <virtualURL>https://my.music.private/Gerbera</virtualURL> then my Denon AVR-X2200W is not able to play FLAC files at all (filetype error), but I can access gerbera web-ui (and listen to the flacs via my nginx reverse proxy from anywhere).

When I delete the config-line regarding <virtualURL> my Denon AVR-X2200W plays FLAC files just fine (but of course the abilty to play the music files via web-ui outside my local network is not working because the file-link refers to the local ip:port.

As I mentioned: I did not see a difference in the debug-log.
To reproduce the error cleanly I deleted the DB after enabling/disabling <virtualURL>

If anyone can reproduce that behaviour or even find a solution, I would be grateful!

**Comment by KarlStraussberger** [comment]
Hello,

Maybe you can share the configs you mention so we don't have to guess. Also your gerbera version is of interest.

As far as I know the AX-2200W does not support upnp.

**Comment by KarlStraussberger** [comment]
I suppose it's the `https`. Your Denon may not be able to read the resource. I'm not sure whether we can apply the virtualUrl to browse responses as well. But the same code creates the content on the web UI. I commented it out myself without the time for further investigation.

**Comment by count00zero** [comment]
I see! It's not that important, just a little inconvenience and I was just curios why mp3 are played in that setting and flac are not.
Thank you!

**Comment by KarlStraussberger** [comment]
If it's the https, it should for all or for none. So the issue is hidden somewhere else.

**Comment by KarlStraussberger** [comment]
I just added a PR that allows to set `virtualURL` for internal requests and `externalURL` for web requests.

**Comment by count00zero** [comment]
Wow, that sounds great! Thank you!!!!

**Comment by count00zero** [comment]
Works like a charm, thank you again!
