### ISSUE TITLE
Upon restart Gerbera rescans directories - adding new containers

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#284]
### Current Behavior
1. Add new recursive autoscan of video folder
   - files add successfully & recursively
2. Restart Gerbera
3. Rescan of autoscan occurs
4. All subdirectories of autoscan directory added as top-level directories

### Example

**Adding:**
```
/parent
```

**Results in**
```
/parent
/parent/child
/parent/child2
```
#### After Restart
```
/parent
/parent/child
/parent/child2
/child [incomplete set]
/child2 [incomplete set]
```

**Comment by elmodaddyb** [comment]
Not sure yet on root cause, but working to recreate.

**Comment by elmodaddyb** [comment]
The `ScanLevel::Full` supports re-scanning of files changed by Last Modified Scan time.

So system is working OK, although it does have an odd behavior.

> Workaround - Using `ScanLevel::Basic`

I look more to see if there is any fault in the last update time for `ScanLevel::Full` and will close if all looks well.

**Comment by elmodaddyb** [comment]
...found out how everything is working.

Autoscan timestamp is updated when `SingletonManager` shuts down the `ContentManager` singleton.
  - The system loops over all autoscans, and updates last timestamp.

Currently unable to pin-down why `SingletonManager` is not always fired when the `gerbera` process is stopped.  However, on the occasions where the `gerbera` process ends without shutting down the `ContentManager` singelton, this issue occurs. Autoscans are not updated, and **new** autoscans will have a last modified date of `0`.

> I will keep looking to see why `SIGTERM` sent from **systemd** does not cause Gerbera to finalize the singletons.

**Comment by v00d00** [comment]
The singletons are a mess frankly and we need to get rid of them :-1:

**Comment by elmodaddyb** [comment]
@v00d00 & @tcrass - Rest assured, this issue was my own doing :(  Sorry for my confusion.

When debugging using GDB causes the SIGINT signal to be blocked.  As such Gerbera process does not shutdown as expected when stopping the process.

When running in standalone process **without gdb** all is well for this scenario.

Please excuse the clutter.

Thanks,

Eamonn
