### ISSUE TITLE
"Server Statistics" are empty, despite of media files

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#2855]
Just eye candy, yet: after upgrade to 1.12 the Server Stats are all empty, while the Config Status shows the correct number of playable files, files that are actually playable on a client.
Also, there are no scroll-bars on screens with lower resolution.
I am usually running Chrome, stock snap on Ubuntu22.04, though when using Firefox everything works.

**Comment by KarlStraussberger** [comment]
Do you have 1.12.0 or 1.12.1?

Are there any log messages? Did you delete the database or upgrade?

**Comment by udippel** [comment]
```
2023-08-12 11:04:22   info: Gerbera UPnP Server 1.12.1 - http://gerbera.io/
2023-08-12 11:04:22   info: Copyright 2016-2022 Gerbera Contributors.
2023-08-12 11:04:22   info: Gerbera is free software, covered by the GNU General Public License version 2
2023-08-12 11:04:22   info: Loading configuration from: /home/udippel/.config/gerbera/config.xml
2023-08-12 11:04:22   info: Checking configuration...
2023-08-12 11:04:22   info: Configuration check succeeded.
2023-08-12 11:04:22   info: Running an automatic database upgrade from database version 19 to version 20...
2023-08-12 11:04:22   info: Database upgrade to version 20 successful.
2023-08-12 11:04:22   info: Loading 0 configuration items from database
...
```
No database deletion. Just apt update && apt upgrade.

**Comment by udippel** [comment]
Similar to my other remarks, looks like a conceptual inconsistency. When the Server Stats on the start page are all empty, though the Server Stats on the config page show all media files, I'd start at looking at the database read routine(s). There seem to be two different ones.

**Comment by udippel** [comment]
Strange enough, on my PC the web page (Chrome) remains blank, despite of a number of 'Reload's, while on my Android (Chrome) the numbers show up immediately. 
I have even logged out of gerbera on the PC, and logged in again, still all white. 
So it is not a database problem, rather a problem of allocating the html according to browser detection?

**Comment by udippel** [comment]
Okay, one step further: 
On an identical install on an older laptop of a screen of 1280x800, the numbers also don't show. 
And one indication of a webpage bug: due to the low resolution, only the upper left part of the screen is visible. There are no scrollbars to scroll down to the hidden items. 
(Only in case if helpful: Chromium Version 115.0.5790.110 (Official Build) snap (64-bit))

On Firefox, however, everything works, numbers and scroll bars.

**Comment by udippel** [comment]
No explanation so far: it works after I cleaned up and disabled the cloud-init, and changed the netplan to a fixed IP. 
Will explore this later.

**Comment by udippel** [comment]
Reverting to the original, at install time autogenerated /etc/netplan/00-installer-config.yaml
```
# This is the network config written by 'subiquity'
network:
  ethernets:
    enp4s0:
      dhcp4: true
  version: 2
```
the numbers once again disappear. (I know this sounds strange, but I can't help it - the cloud-init does not make any difference.) So the DHCP-machine doesn't get the numbers. Instead, it looks like

![image](https://github.com/gerbera/gerbera/assets/50265752/b30de314-6ff0-4c0c-bfab-82daf73402f1)

**Comment by udippel** [comment]
Then I did exactly nothing, except of setting the dhcp back to 'no', sudo reboot, and the display looks like this:
![image](https://github.com/gerbera/gerbera/assets/50265752/9476695b-df69-4315-aecf-3b0cd763d379)

**Comment by KarlStraussberger** [comment]
If you use dhcp it may bind to localhost or some other default ip before the lease has arrived. If you set the interface `libpupnp` waits for the interface to come up.

**Comment by udippel** [comment]
I know close to nothing about UPnP; though as a networker I'm not convinced. Why? Because Firefox running in parallel to Chrome does a good job. Or is this a wrong assumption?

**Comment by udippel** [comment]
Bueno. For the sake of trying, I re-instated the auto-generated 00-installer-config.yaml (which I have kept like usual), did a reboot (with gerbera taken out of the autostart), issued the two commands (route add ... ifconfig) for the specific interface enp4s0, checked with route and ifconfig that the modifications had taken place, started gerbera, and still the same behaviour: Chrome showing the empty table, while the parallel session of Firefox is okay.

We'd be hard pressed to file this as a bug of Chrome, I guess ... .

**Comment by udippel** [comment]
Something IS wrong:
Made a fresh install of ubuntu 22.04, command line, no GUI, from scratch.
Nothing but installing and updating gerbera. DHCP. Everything came up properly (okay, gerbera --create-config didn't create the dirs, and no config, so I had to create these, and redirect the stuff into config.xml), starting, and everything looked fine. Wow!
Then I moved the machine to a fxed IP, started gerbera:
```
2023-08-15 19:23:19   info: Copyright 2016-2022 Gerbera Contributors.
2023-08-15 19:23:19   info: Gerbera is free software, covered by the GNU General Public License version 2
2023-08-15 19:23:19   info: Loading configuration from: /home/.../config.xml
2023-08-15 19:23:19   info: Checking configuration...
2023-08-15 19:23:19   info: Configuration check succeeded.
2023-08-15 19:23:19   info: Loading 0 configuration items from database
2023-08-15 19:23:19   info: Initialising UPnP with interface: <unset>, port: <unset>
2023-08-15 19:23:19   info: IPv4: Server bound to: 192.168.1.220:49152
2023-08-15 19:23:19   info: IPv6: Server bound to: fe80::280:64ff:feea:8b5a:49152
2023-08-15 19:23:19   info: IPv6 ULA/GLA: Server bound to: :0
2023-08-15 19:23:19   info: Will send UPnP Alive advertisements every 60 seconds
2023-08-15 19:23:20   info: The Web UI can be reached by following this link: http://192.168.1.220:49152
```
... and now it looks like this:
![image](https://github.com/gerbera/gerbera/assets/50265752/9533c61f-cb3d-462d-86f8-2c586e96adb6)

**Comment by KarlStraussberger** [comment]
That screenshot looks like some years ago, which indicates that you've got a mixed installation.

Best approach to clean that up:
- uninstall gerbera (back up the config)
- uninstall libupnp
- look for remaining traces (dirs, files, links) and delete them manually. Check /usr and /usr/local, maybe others
- reinstall 1.12.1

It is very likely that the update from 1.1 to 1.11 to 1.12 causes trouble. Especially, 1.1 was not done by the gerbera team.

**Comment by KarlStraussberger** [comment]
You can easily drop the old files from /etc/gerbera and copy the new ones.

**Comment by udippel** [comment]
Will try tomorrow. 
Now, what about the config.xml? Those from /etc/gerbera? Copied to .config, or redirecting the gerbera --create-config output? (They ARE different by 1,5 kByte)

**Comment by KarlStraussberger** [comment]
You should use the one created with --create-config, change the name, interface and home path to your prefrences.

My config.xml is in /etc/gerbera and my systemd `gerbera.service` calls 

```
/usr/local/bin/gerbera -c /etc/gerbera/config.xml
```
I also have the database there.

**Comment by udippel** [comment]
Okay, a very clean slate! En détail:
- fresh install ubuntu server 22.04 from 22.04.2 installer, using DHCP
- (reboot after install), then apt get update/upgrade
- add gerbera resources, as described as first version under "Ubuntu/Mint"
- apt get update/upgrade
- apt get install gerbera
- gerbera --create-config | Only shows the file, creates no directories (.config/gerbera didn't and don't exist)
- mkdir .config/gerbera
- gerbera --create-config > .config/gerbera/config.xml
- (basic mods on user and name)
- $ gerbera --debug --logfile firstrun.log -> minor inconvenience: "warning: [main.cc:249] main(): Log dir  missing"
- Web-UI works perfectly okay
- Change to fixed IP (netplan apply)
- Web-UI works perfectly okay!

So i think you were right after all. Sorry for have taken your time. Very much suggest to modify the webpage accordingly, though! (The description on the Arch webpage seems partially more up to date.)
After some 5+ trials, I can only suggest, to NEVER try any update!

**Comment by udippel** [comment]
Tried on another box,  though encountered a difference: in the first one, a gerbera.db-wal had been autocreated at gerbera start, in the second one not. What does it do, and where is the difference, please?

**Comment by KarlStraussberger** [comment]
That file is part of the sqlite database and only available at runtime. It depends on the sqlite version and defaults whether and where it shows up.
