### ISSUE TITLE
gerbera behind docker bridge / ssdp location

### ISSUE THREAD

**Issue by Jaywann** [gerbera/gerbera#2857]
I am running gerbera from a docker image and with a slightly custom network config. As all containers are in a dedicated subnet and behind a linux bridge some adjustments to the configuration needed to be made. The goal is to run it without host mode networking.

Ich have successfully set up proxying the upnp multicast packages to the outside of the container using igmpproxy but the SSDP localtion string still advertises the IP of the local docker network 172.16.x.x not the lan 192.168.x.x as the LOCATION:

    NOTIFY * HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): NOTIFY * HTTP/1.1\r\n]
            [NOTIFY * HTTP/1.1\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: NOTIFY
        Request URI: *
        Request Version: HTTP/1.1
    HOST: 239.255.255.250:1900\r\n
    CACHE-CONTROL: max-age=180\r\n
    LOCATION:  http://172.16.3.11:49494/description.xml\r\n

Is there any way to configure the ssdp part of gerbera to broadcast a masked other than the one seen on the interface?

**Comment by KarlStraussberger** [comment]
That part of the protocol is handled by libpupnp. They use the own ip. You might need to pass that through some udp capable reverse proxy. Never tried that.

**Comment by KarlStraussberger** [comment]
You may also try to set the presentation url.

**Comment by Jaywann** [comment]
Thanks for the hints. I ended up using netsed redirecting all traffic to it and doing a simple string replacement there. Still some kinks to work out but the traffic is showing up on the client side with the correct IPs in the localtion field.
