### ISSUE TITLE
Brew/Homebrew package

### ISSUE THREAD

**Issue by v00d00** [gerbera/gerbera#286]
We should investigate what is needed to create one, to allow the MacOS users an easier time to install.

> \<jammi\> hi, I'm unable to build gerbera on macos sierra. followed the instructions and did basic troubleshooting, but no avail
> \<jammi\> actually, removed everything in the build directory, managed to compile it
> \<jammi\> yeah, seems to work now. consider a brew formula or something, since this wasn't easy nor straight-forward to install, especially with slightly different instructions in the github readme vs the other docs on your site

**Comment by elmodaddyb** [comment]
Great Idea!!!  I've been running Gerbera on macOS for a while.  I will see what information I can find.

**Comment by elmodaddyb** [comment]
I started to look into this and found:

1. Adding our package to Homebrew is simply PR to the Homebrew project
2. Creating a package for Gerbera consists of a declarative ruby file
3. The ruby file can be a pure compilation of a Gerbera Tag, a combination of other Homebrew formula's, etc.

I will give this a try in spare time to see how complicated it is.  I only wonder about the compilation dependencies like `taglib`, `libupnp`, `duktape`.

> Will keep you posted

**Comment by elmodaddyb** [comment]
Hello All,

Making good progress on this issue...

### COMPLETED 

1. Created `duktape.rb` formula for homebrew
2. Created `pupnp.rb` formula for homebrew
3. Created `gerbera.rb` formula for homebrew

I added them as a **gist** for now...but will open PR to [homebrew-core](https://github.com/Homebrew/homebrew-core) soon.

[https://gist.github.com/elmodaddyb/a7947ee61d05a5bdd137ba564fcb1898](https://gist.github.com/elmodaddyb/a7947ee61d05a5bdd137ba564fcb1898)

### PENDING

* Awaiting confirmation from **pupnp** team to include a homebrew formula for their library

**Comment by v00d00** [comment]
Im surprised there isn't a homebrew for libupnp, as a fair few apps use it.

**Comment by elmodaddyb** [comment]
@v00d00 - libupnp does exist but only 1.6.25

**Comment by elmodaddyb** [comment]
I was able to **re-use** `libupnp` to update the formula to use **1.8.3**.

I also started the process for the `duktape` formula.

Checkout the [duktape-formula](https://github.com/elmodaddyb/homebrew-core/commit/b88a6022a4f239a46cc7b1c8664f4788324eb361) that I plan to submit to homebrew-core.

If no objections, i will submit PR later this week.

**Comment by elmodaddyb** [comment]
**Step 1:** Submitted new PR for `duktape` library in homebrew
[https://github.com/Homebrew/homebrew-core/pull/28480](https://github.com/Homebrew/homebrew-core/pull/28480)

> I will follow up with `libupnp@1.8.3`....then `gerbera` 👍

**Comment by apjanke** [comment]
Hi! Active Homebrew contributor here.

As a way of testing out your formula before going right to a PR on core Homebrew, you might want to try [creating your own Tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) instead of just a gist and testing the formula there for a while before having someone submit it to core. (E.g. create a `gerbera/homebrew-gerbera` or `elmodaddyb/homebrew-gerbera` repo tap and stick it there.) That way you can work with and play around with the entire install process for a while.

**Comment by elmodaddyb** [comment]
@apjanke - Thanks for your feedback and assistance.  I am new to homebrew system implementation.

I will review the tap setup link you provided!

**Comment by elmodaddyb** [comment]
Looks like `libupnp` is dependency for `gmediaserver` and `djmount`.  So my fancy PR failed to build 👎  [https://github.com/Homebrew/homebrew-core/pull/28620](https://github.com/Homebrew/homebrew-core/pull/28620).

I guess I'll have to update the two dependencies first!!!

**Comment by v00d00** [comment]
@elmodaddyb that is awesome! Shall we add a note to the README to point at that? Or are you planning on waiting until its in the core repo?

**Comment by elmodaddyb** [comment]
I am thinking of the following steps

1. Change ownership of `elmodaddyb/homebrew-gerbera` to the @gerbera org. 

2. Update README for gerbera Tap usage

3. Continue, as non critical-path introduction of libraries to `homebrew-core`

**Comment by v00d00** [comment]
Yes, great idea.

**Comment by elmodaddyb** [comment]
@v00d00 - I transferred the `homebrew-gerbera` repository, and will update readme as next step.

When time permits, can you confirm you have permissions to administer the repo?  I've seen some issues with GitHub transfer in this regard.  Since transferring, I lost admin rights access 😢 

Thanks,

Eamonn

**Comment by v00d00** [comment]
Should be sorted, Ive added "Team Gerbera" as admin on the repos.

**Comment by v00d00** [comment]
Lets close this as its been merged. If anyone has problems, please open a new issue.
