### ISSUE TITLE
Consider using release assets

### ISSUE THREAD

**Issue by diizzyy** [gerbera/gerbera#2875]
Earlier this year GitHub announced that generated source archives are only stable for a year, this will likely cause major issues for anyone trying to package Gerbera longterm. Please consider uploading release source code archives.

Reference:
https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/

**Comment by Rogach** [comment]
I read the referenced article, and it looks like it's incorrect to conclude that "generated source archives are only stable for a year". To quote from the article:

> We presently have no intent to change either format, as we have a new appreciation for the magnitude of the impact this change would have.
> ... In the future, if we intend to change either archive format, we’ll provide six months’ notice in documentation, and on the blog and changelog.

So they explicitly guarantee that the format will stay stable for a long time, and they have no plans of ever changing it, and they will give plenty of advance notice if they still decide to change it.

**Comment by KarlStraussberger** [comment]
It's only about the hashes changing because zip changes. No need to worry in the first place, but still some useful hints to consider.

**Comment by diizzyy** [comment]
Since pretty much all packaging distros checksum files (and upstream usually provide checks for validation) it may lead to breakage which has happened before on GitHub so it would be nice if that could be avoided especially now when they're explicity saying that they don't care if it breaks.

**Comment by Rogach** [comment]
Looks like they explicitly say that they do care:

> ... as we have a new appreciation for the magnitude of the impact this change would have.

Using archive links is much more convenient, so in absence of actual planned compression changes it seems wasteful to start uploading tarballs manually.

**Comment by diizzyy** [comment]
I'm going to guess you don't validate downloads and/or package software based on your reply. The first line in that blog even confirms this exact issue and why they needed to make a policy out of it in the first place.

**Comment by Rogach** [comment]
Your guess is incorrect. I'm actually a maintainer of several packages, and I was hit by "this exact issue" when it happened (because I do indeed validate downloads). So I do understand the problem you are describing.

And from my perspective using the archive links is much more convenient, because it explicitly points to a tag or commit, instead of some random archive that was uploaded. This makes it much easier to establish provenance.

If/when GitHub decides to change their archive output, it wouldn't be that hard for me to update the checksums. Especially given 6 months notice.

**Comment by whyman** [comment]
I dont think as a project we have the bandwith for this when there is no pressing issue as it stands. If this change we look at it.
