### ISSUE TITLE
gerbera scanning for non-existent directory not found in config.xml

### ISSUE THREAD

**Issue by iansebryk** [gerbera/gerbera#2880]
trying to debug why gerbera is no longer findable by my DLNA client, and found this in the syslog:

```
error: _rescanDirectory: Failed to read /mnt/pub/movies/tv-series, No such file or directory
```

have no idea where this came from!  i cannot find it in `config.xml`, it's not a valid path on the system, and i have no idea where else to look.  the docs are pretty slight and not very helpful.  i've combed through what IS there and looked in every file i could think of... no luck.  i've been through every option on the webUI; still nothing.  i don't know why this is stopping my server have no idea where to look next.  it's irritating as hell.

**Comment by KarlStraussberger** [comment]
To look at the right place it always helps to know your gerbera version, distro and package source.

There is no hardcoded autoscan directory, so the entry must either be in filesystem ui or config ui.

Another option may be a symbolic link to the directory. If you normally don't use symbolic links you can disable them with `follow-symlinks` (https://docs.gerbera.io/en/stable/config-import.html#import) option.

**Comment by iansebryk** [comment]
whoops!  you're correct.  apologies.  running Deb10 Buster and Gerbera 1.3.2 and using the deb-multimedia source for apt.

**Comment by KarlStraussberger** [comment]
That is quite old already. You should migrate to our jfrog repo instead.

The symlink theory is still unresolved.

**Comment by iansebryk** [comment]
i had the jfrog repo, but i recall disabling it because of some key error or inability to resolve.  it's been a while...  but if you're saying it's good, i'll give it another go.  to be sure i'm getting the correct one, would you please post a link?  thank you.

**Comment by KarlStraussberger** [comment]
The link is here https://docs.gerbera.io/en/latest/install.html#ubuntu-mint

**Comment by iansebryk** [comment]
i just ran the repos from the links.  after update, gerbera still @ version 1.3.2.  *shrug*  and i actually says to use deb-multimedia for Buster.  on top of that, it says that the Buster repos will be behind.  but to me 1.8 vs 1.3 is a bit too far...

bottom line:  after update, DLNA no longer detects the server at all and the WebUI is no longer accessible despite enabling it in the config.  lovely.  oddly, the non-existent file is no longer being scanned for...

**Comment by iansebryk** [comment]
okay.  ripped the whole damn thing out.  cleaned every nook and cranny... aaaand it's back:

```
 error: monitorUnmonitorRecursive: Failed to read /mnt/pub/movies/tv-series, No such file or directory
```
what the heck is `monitorUnmonitorRecursive` and how do i change what it's looking for??

**Comment by KarlStraussberger** [comment]
Obviously you ran into the issue that the removal of deb-multimedia installations is not perfect... Maybe we should remove it from the documentation or at least mark it as outdated (which happens.

I'm quite sure that you have a dangling link in you media directory. You can find it by running with `--debug`` and look at the messaegs before the exception. Also you can try to set `follow-symlinks="no"` to make sure that my suspicion is correct.

**Comment by iansebryk** [comment]
run with `--debug`??  how?  i tried modifying the service file:
```text
ExecStart=/usr/bin/gerbera --debug -c /etc/gerbera/config.xml
```
but i get the same messages.  and where does `follow-symlinks` get set?  it isn't in the `config.xml` file.

**Comment by iansebryk** [comment]
well... fork.  you were correct.  i didn't see it because the user i was checking didn't have permission to see it.  thanks.  i'll note this for future; in this and other things.  👍

**Comment by iansebryk** [comment]
i guess this is closed.

**Comment by KarlStraussberger** [comment]
Thank you for updating the issue.

Now that we know of this, I updated the error message to display the parent directory also. In case of regular files this is part of the path, except for symlinks.

**Comment by iansebryk** [comment]
for what it is worth, i tried it with `follow-symlinks="yes"' and still got the error.  so either the link pointed nowhere (probably) or the feature has a booboo.  :D

**Comment by KarlStraussberger** [comment]
You'd better try `follow-symlink="no"` to avoid the error message.
