### ISSUE TITLE
Media import enhancements

### ISSUE THREAD

**Issue by BenGig** [gerbera/gerbera#289]
Based on the abcbox() function for common.js (https://github.com/gerbera/gerbera/pull/287), I'd like to propose some enhancements for the import.js script.

With the current script, activating  `<virtual-layout type="js">` does not change the appearance of the media presentation, it looks the same as with `<virtual-layout type="builtin">`, thus hiding the potential of Gerbera.

I installed Mediatomb in 2010 and have customized the import function to structure the artists/album/tracks/genre to look as shown below. While the builtin structure works for 'intelligent' clients which do their own classification and sorting, long lists are impracticable with streaming devices with small displays and limited scrolling capabilities. Also smartphone clients gain from the structure, browsing is very handy. To me, this flexibility was always the most favored feature of this software.

My proposal is to submit an enhanced import.js which, when activated, produces the structure shown below. I also would write a page for the docs on how to customize the import. I have added further item branches which are not for general use but could be the base for personal optimizations.

Example for branch "Artists":

* --all--
  * (all bands alphabetically)
* -0-9-
* -ABCDE-
  * --all --
    * (all bands with first letter A-E)
  * A
    * --all--
      * (all bands with first letter A)
    * ABC      <------ Band name here, not abcbox :)
      * -all-
        * (all songs of band here)
      * How to be a Zillionaire (1985)
        * (songs from Zillionare)
      * The Lexicon of Love (1985)
        * (songs from Lexicon of Love)
  * B
    * --all--
      * (all bands with first letter B)
    * Bad Religion
      * -all-
        * (all songs of band here)
      * Against the Grain (1990)
        * (songs)
      * Generator (1995)
        * (songs)
  * C

**Comment by v00d00** [comment]
There is absolutely nothing stopping us from shipping multiple layout scripts, and actually I think that is a quite nice idea, and a nice way to show the flexibility we offer.

I think keeping the non-js and default js layout the same makes sense to avoid surprises when switching between them, but having multiple provided JS layouts solves that problem.

Sound good?

**Comment by elmodaddyb** [comment]
@BenGig - Awesome job with this enhancement.  I merged this code and ran `import_structured` as the import script.  The library is organized quite nicely!

**Comment by v00d00** [comment]
Looks like this can be closed, thanks @BenGig
