### ISSUE TITLE
Access through reverse proxy not working

### ISSUE THREAD

**Issue by DJ-Key** [gerbera/gerbera#2898]
I can't acess the server web gui through a nginx reverse proxy(Nginx Proxy Manager)
and when i try to configure the `<virtualURL>http://dlna.xy.z/</virtualURL>` it works but my Samsung smart tv can't play any files so i haven't put the url in.
Locally i can acces the Web Gui.
My gerbera server 1.12.1 is running on an Ubuntu Server 22.04.3 LTS
xy.z is only as example. And i've modified the mt-icons in /usr/share/gerbera/web/icons for custom Images on my Samsung Smart tv Series 7(UE55RU7402UXXH)

**Comment by KarlStraussberger** [comment]
That's why we added #2836 (external) to mask the address. Virtual url is more or less intended for container environments

**Comment by DJ-Key** [comment]
And how do i add this? I Installd gerbera through apt.
I added ´<externalURL>http://dlna.djkey.me/</externalURL>´ to the /etc/gerbera/config.xml but it's still not working.

**Comment by DJ-Key** [comment]
Here my steps after setting up the Server and update && full-upgrade

1: Implementing NAS Storage:
    1  sudo nano /etc/fstab
    2  sudo nano /root/.credentials
    3  sudo apt-get install cifs-utils
2: Adding repository
    6  sudo curl -fsSL https://gerbera.jfrog.io/artifactory/api/gpg/key/public |                                                                                     sudo apt-key add -
    7  sudo apt-add-repository https://gerbera.jfrog.io/artifactory/debian
3: To Prevent Errors with inotify
    8  echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf &&                                                                                     echo fs.inotify.max_queued_events=524288 | sudo tee -a /etc/sysctl.conf && echo                                                                                     fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sys                                                                                    ctl -p
4: Update & install Gerbera
   12  sudo apt update
   13  sudo apt dist-upgrade
   14  sudo apt install gerbera

**Comment by KarlStraussberger** [comment]
New gerbera repository now containing up to date builts
