### ISSUE TITLE
Gerbera can't find m3u8 file

### ISSUE THREAD

**Issue by hollysheep** [gerbera/gerbera#2906]
Gerbera should be able to find normal m3u and m3u8 with Extended layout. My m3u8 is created by ffmpeg and looks like this:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:4
#EXT-X-MEDIA-SEQUENCE:2
#EXTINF:4.000000,
stream2.ts
#EXTINF:0.440000,
stream3.ts
#EXT-X-ENDLIST
```

Gerbera doesn't find the m3u8 and the ts files. The only file that is recognized is a matroska file.

**Comment by KarlStraussberger** [comment]
What version of Gerbera (gerbera --version) are you using on what distribution?

**Comment by hollysheep** [comment]
Its Version 1.1.0 in ubuntu 20.04.

**Comment by hollysheep** [comment]
I installed 1.12 now and tried it again with the same playlist. VLC on android can play the playlist but my smart tv can't. The tv wants to play the files within the playlist not the playlist itself. So i guess its a client problem.

I tried to map the extention m3u8 to video file

`<map from="m3u8" to="video/x-matroska"/>`

and restarted gerbera but without any effect.

**Comment by KarlStraussberger** [comment]
The playlist only works if the player is accessing the disk. The tv needs to retrieve the file via http. When importing playlists Gerbera creates a virtual directory containing all the referenced files. Normally, your tv should work with that.

**Comment by hollysheep** [comment]
The video files are in the playlist's directory. When i add /home/user/folder to gerbera with a playlist and 2 video files stream2.ts and stream3.ts. This should work?

I can play the video files but not the playlist. when i open the playlist it looks like opening a folder and i see the videos.

**Comment by KarlStraussberger** [comment]
That's how it works
