### ISSUE TITLE
1.2.0 Release

### ISSUE THREAD

**Issue by v00d00** [gerbera/gerbera#291]
Reminder issue to do the release. Will be tomorrow most likely.

**Comment by Martii** [comment]
Look forward to this... although my distro might be a little slower and I still haven't had much time to compile this.

A Massive Thank You for everything you all do with this!!! :smile_cat:

**Comment by v00d00** [comment]
Been a bit delayed due to some personal life stuff, and suffering with some RSI. I hope to be able to look at doing the the release this weekend...

**Comment by elmodaddyb** [comment]
This upcoming release will be a great production!  Many improvements lately 🏆

**Comment by v00d00** [comment]
Released! https://github.com/gerbera/gerbera/releases/tag/v1.2.0
