### ISSUE TITLE
Line number missing for javascript errors

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#2913]
I updated Gerbera from 1.12.1 to current git master (bac67efe18c384255f15d2526623983e71b2f8f6), had a strange bug with my kitchen radio, deleted all database tables and started gerbera. Now I get javascript errors all over the place:

> error: Failed to execute script /etc/gerbera/import-cweiske.js: TypeError: cannot read property 'res' of undefined
> error: [/usr/local/src/gerbera/gerbera-git/src/content/scripting/script.cc:430] void Script::_execute() Error: Script: failed to execute script

Unfortunately it does not tell me in which line the error occurs - this would be very helpful for debugging.
The stack trace would also help to see nesting.

https://duktape.org/api#duk_pcall

**Comment by cweiske** [comment]
Replacing `duk_safe_to_string` with `duk_safe_to_stacktrace` gives better errors, and falls back to `duk_safe_to_string` if there is no stacktrace.

Now I get:
```
error: Failed! to execute script /etc/gerbera/import-cweiske.js: TypeError: cannot read property 'res' of undefined
     at [anon] (duk_hobject_props.c:2621) internal
     at addImage (/usr/local/share/gerbera/js/common.js:998)
     at global (/etc/gerbera/import-cweiske.js:328) preventsyield
error: [/usr/local/src/gerbera/gerbera-git/src/content/scripting/script.cc:430] void Script::_execute() Error: Script: failed to execute script
```

**Comment by KarlStraussberger** [comment]
The fix is great.

There have been vast changes to the scripting mechanism. You may have to create a wrapper like https://github.com/gerbera/gerbera/blob/master/scripts%2Fjs%2Fimport.js
