### ISSUE TITLE
Duplicate albums when artists are different

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#2917]
I have a christmas compilation CD with songs from multiple artists. The default import script creates multiple album entries, and the web UI shows them as duplicates:
![2023-12-17 Auswahl_001](https://github.com/gerbera/gerbera/assets/59036/75ebbeb5-6fc3-4676-bf96-7a4ce59636da)

Internally the albums have different names:
```
V/Audio/Albums/Merry Christmas@Dean Martin@2016
V/Audio/Albums/Merry Christmas@Frank Sinatra@2016
```

The same happens for "Unknown" album:
```
V/Audio/Albums/Unknown@Ich + Ich@2023
V/Audio/Albums/Unknown@Nathan Evans@2021
```

This is not helpful at all.

This happens with current git master, 820a513f95027a7c38080a6ea45c61719dae2988.

**Comment by cweiske** [comment]
This is related to #1440 and caused by #2783 ("Make virtual folders unique by path")

**Comment by cweiske** [comment]
Maybe using the folder path on disk would be better suited than the artist name.

**Comment by cweiske** [comment]
This can be fixed in configuration with:
```
<import>
    <virtual-directories>
      <key metadata="dummy"/>
    </virtual-directories>
</import>
```
which resets everything as it was before #2783.

Unfortunately there does not seem to be a metadata key that contains the folder.

Using `M_UPNP_DATE` as key fixes the duplication problem for compilations, but not for "Unknown" album songs.

**Comment by KarlStraussberger** [comment]
Did you set `AlbumArtist` for this? If it is not set the import script gets the `Artist` and there are the duplicates.

Maybe it's a better idea to set `AlbumArtist` to unknown or the location - at least for that part of the layout.

**Comment by cweiske** [comment]
My audio files almost never have an albumartist set.

**Comment by KarlStraussberger** [comment]
Added "LOCATION" key so that original path can be used to identify identical folders. Hope that helps

**Comment by cweiske** [comment]
When using 
```
<virtual-directories>                                                                                                                                                                     
      <key metadata="LOCATION"/>
```
I do not get any `@` in the `mt_cds_object.location` column for virtual folders - so it does not seem to work.

**Comment by KarlStraussberger** [comment]
Did you add the line `chain.album.location` to your script

**Comment by cweiske** [comment]
I tried it with the stock javascript import files, which should set it. I'll debug further.

**Comment by cweiske** [comment]
I compiled a fresh copy of gebera git on my laptop, created a fresh configuration file with `gerbera ----create-config´ and only configured database, import dir and virtual-directories: [config.xml.gz](https://github.com/gerbera/gerbera/files/13805383/config.xml.gz)

There are two problems:

1. The docs show "virtual-directories" below "mappings" on https://docs.gerbera.io/en/latest/config-import.html#virtual-directories, which is wrong - the tag must directly be below `import`: 
![2024-01-01 Auswahl_001](https://github.com/gerbera/gerbera/assets/59036/0466e42d-a7f7-4ed6-b86f-7f040d56afe7)

2. `<key metadata="LOCATION"/>` does nothing. For testing I also added the genre - which is then visible in `mt_cds_object.location` - but not the location value:

```
    <virtual-directories>
      <key metadata="DUMMY"/>
      <key metadata="M_GENRE"/>
      <key metadata="LOCATION"/>
```

location column:
- `V/Audio/Artists/2raumwohnung/36 Grad@Pop`

I use and did not touch the default import scripts.

**Comment by KarlStraussberger** [comment]
Sorry, there was no location because I forgot to push that part of my changes (been working on too many things in parallel)

**Comment by cweiske** [comment]
I still do not get `LOCATION` filled with 8616675f4e4982624186c7a3946cfae4c9169ee9.

**Comment by KarlStraussberger** [comment]
It's only added for `chain.album` in normal `importAudio` layout or in `importAudioInitial`.
