### ISSUE TITLE
Virtual albums have no cover art image in non-grb import mode

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#2918]
The virtual albums and artists have no images in the web UI, with latest git master (820a513f95027a7c38080a6ea45c61719dae2988), a fresh database and the standard import scripts.
The albums in the "PC directory" show a cover image.
![2023-12-17 gerbera-no-art-album](https://github.com/gerbera/gerbera/assets/59036/bbbf2c61-d467-4c3f-84e6-4cb5e3d7a059)

I once fixed that with 
```
<import>
  <resources>
    <container parentCount="2" minDepth="1"/>
  </resources>
</import>
```
but that does not seem to work anymore.

Maybe this is related to #2827.

Note: I get cover art for albums and artists when switching to [grb mode](https://docs.gerbera.io/en/latest/config-import.html#import).
```
<import import-mode="grb">
```

**Comment by TheMarstonConnell** [comment]
I've tried with both `grb` and `mt` and have this same issue. However different albums are missing their album art depending on which I use.

My testing was:
1. I filled a directory with music.
2. Started gerbera fresh with a custom config (mt, then grb after seeing this thread, then mt again)
3. Got a result like this 

Album view:
<img width="396" alt="image" src="https://github.com/gerbera/gerbera/assets/34043723/757c4f23-4d56-4931-a551-b00d46896ef4">

Directory view:
<img width="542" alt="image" src="https://github.com/gerbera/gerbera/assets/34043723/385408bd-ad94-4f18-9c99-74b88c79ef4b">
