### ISSUE TITLE
Playlists (actually ids) are unstable

### ISSUE THREAD

**Issue by mnlipp** [gerbera/gerbera#2923]
Two weeks ago, I created some playlist with content from gerbera using vlc. Everything was fine. I uploaded them to gerbera.

Today, most titles on the playlist don't work anymore. Shouldn't the ids used in the URLs in the playlist be stable?

**Comment by KarlStraussberger** [comment]
That's one of the goals of the new `grb` import mode.

But as soon as you rename folders or files they are getting a new id.

You may create the playlist referencing the files on your box and let gerbera host the playlist (it creates virtual folders for each playlist)

**Comment by mnlipp** [comment]
Thanks for the fast reply, but sorry, I don't get it...

> But as soon as you rename folders or files they are getting a new id.

I didn't rename any of the folder or files that were referenced by the playlist

> You may create the playlist referencing the files on your box and let gerbera host the playlist (it creates virtual folders for each playlist)

Isn't this what I did when I created the playlist with vlc and uploaded it? Is there any way to create a stable playlist?

**Comment by KarlStraussberger** [comment]
If you are using a UPnP client it inserts the ids in the URL. These URLs are not accessable from the server side. You need to add the physical paths to your files in the playlist.

**Comment by mnlipp** [comment]
Finally got it:

* Playlist created by a client contain URLs to the server
* When such a playlist is scanned, gerbera simply copies the URL in the generated playlist (in database)
* If the URL isn't stable, your playlist will rot.

Workaround:

* Assemble the playlist (a file with absolute filenames) on the server
* If you want to add a complete album, use `ls -d /directory/*`
* Make gerbera import the created playlist. It then creates a plalyit with URLs in "database".
