### ISSUE TITLE
Docker - ffmpegthumbnailer was not compiled with jpeg support for photo

### ISSUE THREAD

**Issue by Maikl963** [gerbera/gerbera#2927]
In OpenWrt running Docker, I don't have photo previews and there is an error in the log:

warning: Thumbnail generation failed for file /content/riverpe.jpg: ffmpegthumbnailer was not compiled with jpeg support

Is there anything I can do to fix this?

![image](https://github.com/gerbera/gerbera/assets/102465228/a04269f9-9e49-4065-8ffa-8392f66abdb4)

**Comment by KarlStraussberger** [comment]
This is already fixed in current head #2801
