### ISSUE TITLE
Crash on start of gerbera-1.12.1-2.4

### ISSUE THREAD

**Issue by jimishol** [gerbera/gerbera#2936]
The commands "gerbera" or "gerbera --compile-info" crashe and displayed output is just the following one line

~ ❯ gerbera --compile-info
gerbera: symbol lookup error: gerbera: undefined symbol: _ZN6spdlog7details7log_msgC1ENS_10source_locEN3fmt2v917basic_string_viewIcEENS_5level10level_enumES6_
~ ❯ 

I use gerbera for years. It must not have more than one month that it seemed to work properly.
I am on x86_64 opensuse tubleweed. Installed version is gerbera-1.12.1-2.4
libupnp17 is also installed from the source code of libupnp-1.14.18-1.1
I did not compiled anything, the above and gerbera are installed from my distribution.

**Comment by KarlStraussberger** [comment]
That's a problem of tumbleweed. The spdlog version does not match it has to be recompiled on the distros side.

**Comment by andreasstieger** [comment]
This is actually a build failure, see #2839, fixed by #2840
