### ISSUE TITLE
Gerbera 2.0.0 for MacOS

### ISSUE THREAD

**Issue by St3ll4rM4n** [gerbera/gerbera#2951]
Great work guys on 2.0.0 release and finally there is recent spdlog and fmt support in MacOs. Well done!!!

May I ask you to update MacOS formula in your GitHub please?

https://github.com/gerbera/homebrew-gerbera

Thanks!

**Comment by KarlStraussberger** [comment]
Thanks for the hint, I'm not in the half eaten fruit world. Hope it works.
