### ISSUE TITLE
National character issues in MacOS. error: iconv: Illegal byte sequence

### ISSUE THREAD

**Issue by St3ll4rM4n** [gerbera/gerbera#2952]
Hi guys,

I use Gerbera in one of my MacOS setup and it has some trouble with national characters.

I see in gerbera.log the following:
```
2024-01-07 14:52:00  error: iconv: Illegal byte sequence
2024-01-07 14:52:00  error: iconv: ?adowany could not be converted to new encoding: invalid character sequence!

```
Also, directories and filenames are broken in gerbera UI both in filesystem and database section.

I can see the file names and directories properly with the right character encoding in terminal and also MacOS Finder app. Files are also properly displayed while shared over the network via SMB (Samba).

Any thoughts, ideas? Is this a bug?

I have following setup:
ProductName:	macOS
ProductVersion:	12.7.2
BuildVersion:	21G1974
Gerbera 2.0.0 (the same is also with <2.0.0 versions).
Terminal environment "set": LC_CTYPE=UTF-8

Thanks

**Comment by KarlStraussberger** [comment]
There are several setting for charsets under the `<import>` config section, e.g. see https://docs.gerbera.io/en/stable/config-import.html#filesystem-charset.

You may try `Latin-1` if appropriate

**Comment by St3ll4rM4n** [comment]
Thanks for the hint.
I added the following two lines to <import> section.

```
    <filesystem-charset>UTF-8</filesystem-charset>
    <metadata-charset>UTF-8</metadata-charset>
```

That solved the problem.

What is interesting is the same config is working in Ubuntu. So, I guess from some reason MacOS version can't recognise encoding properly, so it needs to be forced in the config.

**Comment by KarlStraussberger** [comment]
It is likely that the default encoding of the OS is kicking in here. Window$ is still hanging on some old ANSI-based stuff.
