### ISSUE TITLE
gerbera 2.0 - upnp container sort

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#2970]
I want to have all my containers alphabetically sorted. This works for some hierarchies, but not for all.
Top level looks like this:

![image](https://github.com/gerbera/gerbera/assets/10534549/26e91731-edd0-4bfb-994c-c44e62ee2f40)

Below 02 all artists ar sorted alphabetically, but the next level is not sorted:

![image](https://github.com/gerbera/gerbera/assets/10534549/5a967f89-5dd7-4f19-9fab-7101e1dc8814)

How can I get all levels sorted alphabetically?

**Comment by nobanzai** [comment]
Did the behaviour change in gerbera 2.0? Because I didn't change anything in my addAudio script and the config file regarding upnp-classes. Before everything was sorted alphabetically.

**Comment by KarlStraussberger** [comment]
Yes, there was a change to take class into account.

**Comment by nobanzai** [comment]
I use

`      audio: { title: 'Audio', objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER, metaData: [] },
      artist: { title: artist[0], objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER_MUSIC_ARTIST, metaData: [], res: obj.res, aux: obj.aux, refID: obj.id },
      allArtists: { title: '01 - Artists (all)', objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER },
      albumartist: { title: albumartist, objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER_MUSIC_ARTIST, metaData: [], res: obj.res, aux: obj.aux, refID: obj.id },
      allAlbumArtists: { title: '02 - Album Artists (all)', objectType: OBJECT_TYPE_CONTAINER, upnpclass: UPNP_CLASS_CONTAINER },
`

What should I use instead?

**Comment by nobanzai** [comment]
Ok, got it - using upnpclass: UPNP_CLASS_CONTAINER for all containers gives the desired results.
Is there a description for the existing upnp contaioner classes?

**Comment by KarlStraussberger** [comment]
https://docs.gerbera.io/en/stable/scripting.html#constants

**Comment by nobanzai** [comment]
Thx, but then I don't understand the sort behaviour for UPNP_CLASS_CONTAINER_MUSIC_ARTIST mixed with UPNP_CLASS_CONTAINER containers - there is no special treatment for both classes, but containers of these classes aren't sorted alphabetically among each other? Instead all UPNP_CLASS_CONTAINER containers are sorted alphabetically and then all UPNP_CLASS_CONTAINER_MUSIC_ARTIST containers?
Looks like this:

![image](https://github.com/gerbera/gerbera/assets/10534549/230d89c5-7780-44fc-a6e2-f6696803093a)

**Comment by KarlStraussberger** [comment]
As said, the sorting is `upnp_class, title` which means that all `UPNP_CLASS_CONTAINER` are forming a group and all item in this group are sorted by title. The same with `UPNP_CLASS_CONTAINER_MUSIC_ARTIST`.

The group `object.container` is put before `object.container.person.musicArtist`. Try to add these in some spreadsheet and sort by the two columns.

**Comment by nobanzai** [comment]
Ah, no I didn't really understand that before, but of course then this sort order is absolutly clear.
One more question: Do I have any advantage using these classes besides the sort order?

**Comment by KarlStraussberger** [comment]
Support for container and file types is depending on the client, that's why we try to be exact. `upnp:class` is a more sophisticated concept than file extensions from desktop systems.

**Comment by nobanzai** [comment]
Not sure, if I understand, why upnp:class is more sophisticated, and what I can do with this sophistication. Can you elaborate, please?

**Comment by KarlStraussberger** [comment]
File systems typically distinguish files and folders. UPnP defines multiple subtypes and clients may support these.
- album folders show cover art and release date
- genre/artist folders show up in genre/artist search
- video files are not shown on audio players
And so on...

**Comment by nobanzai** [comment]
Thx again!
