### ISSUE TITLE
gerbera 2.0: No Container parent for Item playlist_name

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#2971]
On import of playlists i get "No Container parent for Item playlist_name" for all of my playlists.
Despite the message also for the *first* playlist, this one is imported, though.
I don't have own jscripts for importing playlists, so this must be a problem of the distributed jscripts.

The only config parms regarding playlists in my config.xml are:

```
<playlist-charset>UTF-8</playlist-charset>
...
<playlist create-link="yes">importPlaylist</playlist>
...
        <treat mimetype="audio/x-mpegurl" as="playlist"/>
        <treat mimetype="audio/x-scpls" as="playlist"/>

```

**Comment by nobanzai** [comment]
In this case I stopped gerbera, removed the database and restarted gerbera.
So this is happens dureing the initial scan.

**Comment by KarlStraussberger** [comment]
#2977

**Comment by KarlStraussberger** [comment]
Can you try out our current head, whether the issue still exists.

**Comment by nobanzai** [comment]
Is there an rpm to install or do I have to compile it myself? I am not sure, I have a development system to build any binary for the target machine. The target machine itself doesn't have a build system.

**Comment by KarlStraussberger** [comment]
Sorry, there is no rpm. If you build yourself it would be great.

**Comment by nobanzai** [comment]
No, sorry, I don't have any machine, I could build gerbera for the target machine.
All machines with buld systems are Tumbleweed, not Leap and have much newer versions of everything.

**Comment by nobanzai** [comment]
Sorry, but problem still exists with latest openSUSE Leap Version:

error: [import_service.cc:420] createItems(): No Container parent for Item ...

I'm not sure, though, if the fix is part of this version (gerbera-2.0.0-lp155.46.1.x86_64).

**Comment by KarlStraussberger** [comment]
That's still 2.0.0. So the need for wrapping up a 2.0.1 arises.

**Comment by nobanzai** [comment]
Works again - thx a lot.

**Comment by nobanzai** [comment]
And the problem reappeared:
`2024-11-22 20:54:04.951  error: [import_service.cc:547] createItems(): No Container parent for Item /home/archiv/sound/Michaels_PlayLists/sky.fm-Classic_Rock.m3u`
