### ISSUE TITLE
JFROG artifactory disabled

### ISSUE THREAD

**Issue by gobater** [gerbera/gerbera#2983]
Since a few days I'm constantly getting errors when running "apt update".

It turns out JFROG disabled Gerbera's free subscription.

The following image appears when navigating to: gerbera.jfrog.io
![image](https://github.com/gerbera/gerbera/assets/23657567/a8031924-18f2-4090-96d2-42e8b33fce7a)

**Comment by KarlStraussberger** [comment]
#2967

**Comment by gobater** [comment]
@KarlStraussberger , sorry for duplicating. Did check of existing issues, not for discussions
