### ISSUE TITLE
Install gerbera

### ISSUE THREAD

**Issue by DJ-Key** [gerbera/gerbera#2984]
When i use 
curl -fsSL https://gerbera.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -
sudo apt-add-repository https://gerbera.jfrog.io/artifactory/debian
or
curl -fsSL https://gerbera.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -
sudo apt-add-repository https://gerbera.jfrog.io/artifactory/debian-git
and then 
apt install gerbera
it installs an very old version (gerbera (1.1.0+dfsg-3ubuntu4))

**Comment by KarlStraussberger** [comment]
#2967
