### ISSUE TITLE
ToDo: Renew Docker OSS Subscription

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#2990]
> We would like to kindly remind you that your current subscription to the Docker-Sponsored Open Source Program is set to expire in 45 days

Leaving this here so I remember to submit the form and we keep our unlimited pulls on docker hub

**Comment by whyman** [comment]
Form submitted....

**Comment by whyman** [comment]
I did the form a while ago and never got anything, so submitted it again and got a confirmation email this time :facepalm: 

> Dear Ian whyman,We want to express our gratitude for your interest in renewing your membership with the Docker-Sponsored Open Source Program. Your renewal application has been received and is now in review. 

So now we wait.

**Comment by whyman** [comment]
Finally confirmed!

**Comment by KarlStraussberger** [comment]
Great!!! 🙌
