### ISSUE TITLE
Common.js Box Setup for Dates Uses Config Parameter Video/allYears

### ISSUE THREAD

**Issue by ljr55555** [gerbera/gerbera#2998]
Starting at line 1014 in common.js, there are two sections that define date-based views. Each of the two checks that a configuration parameter is enabled. In the first section, commented as years, `boxSetup['Video/allYears']` is checked. In the second section, commented as dates, the same `boxSetup['Video/allYears']` value is checked.  

![gerbera-video-allyears](https://github.com/gerbera/gerbera/assets/24596267/2a5028a3-d121-4c35-90f7-a76f3f949031)

The analogous section for images, starting at line 1113 tests `boxSetup['Image/allYears']` in the 'years' block and `boxSetup['Image/allDates']` in the 'dates' block
![gerbera-images-allyears](https://github.com/gerbera/gerbera/assets/24596267/758199f7-1d17-4e30-bbfa-76c3ce43a48a)

I believe line 1025 should check if `boxSetup['Video/allDates']` is enabled.

**Comment by KarlStraussberger** [comment]
The copy and paste department.

Thanks for reporting and fixing.
