### ISSUE TITLE
meta-data mkv

### ISSUE THREAD

**Issue by alainstark** [gerbera/gerbera#30]
This is an example of a mkv file with meta-data.

[metadata.mkv.zip](https://github.com/v00d00/mediatomb/files/697566/metadata.mkv.zip)

This is the [matroska documentation for tagging](https://matroska.org/technical/specs/tagging/index.html) files.
And this is the [cover art matroska documentation](https://matroska.org/technical/cover_art/index.html).

The goal is to enhance mediatomb metadata handler to use these mkv meta-data.

**Comment by whyman** [comment]
Fixed with #540
