### ISSUE TITLE
debian gerbera build -> undefined symbol

### ISSUE THREAD

**Issue by prinz3nroll3** [gerbera/gerbera#3001]
hello,
i want to build gerbera on my own.
i download gerbera from github and use the buld script.
after execute the build_deb.sh i install the package.
but after running the bin i got the following error. i am on debian 12.5.

`sudo /usr/local/bin/gerbera -c /home/user/.gerbera/gerbera.xml `

Error:
`/usr/local/bin/gerbera: undefined symbol: _ZN3fmt2v712format_errorD1Ev`

Some ideas?

**Comment by KarlStraussberger** [comment]
You've got a pre-installed libfmt which conflict with the one build by the `build_deb.sh`. If you uninstall libfmt with `apt`, your problem should be gone.

**Comment by prinz3nroll3** [comment]
Hello,
i ve removed all libfmt files on disk, see:
`/var/lib/dpkg/info/libfmt9:amd64.md5sums`
`/var/lib/dpkg/info/libfmt9:amd64.shlibs`
`/var/lib/dpkg/info/libfmt9:amd64.triggers`
`/var/lib/dpkg/info/libfmt9:amd64.list`
`find: ‘/run/user/1000/gvfs’: Keine Berechtigung`
`find: ‘/run/user/139/gvfs’: Keine Berechtigung`
`/usr/share/doc/libfmt9`
`/home/user/Downloads/gerbera_and_build/gerbera/scripts/debian/fmt-10.2.1/build/libfmt.a`

after that i installed libfmt install-fmt.sh see
`/var/lib/dpkg/info/libfmt9:amd64.md5sums`
`/var/lib/dpkg/info/libfmt9:amd64.shlibs`
`/var/lib/dpkg/info/libfmt9:amd64.triggers`
`/var/lib/dpkg/info/libfmt9:amd64.list`
`find: ‘/run/user/1000/gvfs’: Keine Berechtigung`
`find: ‘/run/user/139/gvfs’: Keine Berechtigung`
`/usr/share/doc/libfmt9`
`/usr/local/lib/libfmt.so.10.2.1`
`/usr/local/lib/libfmt.so.10`
`/usr/local/lib/libfmt.so`
`/home/user/Downloads/gerbera_and_build/gerbera/scripts/fmt-10.2.1/build/libfmt.so.10`
`/home/user/Downloads/gerbera_and_build/gerbera/scripts/fmt-10.2.1/build/libfmt.so`
`/home/user/Downloads/gerbera_and_build/gerbera/scripts/fmt-10.2.1/build/libfmt.so.10.2.1`
`/home/user/Downloads/gerbera_and_build/gerbera/scripts/debian/fmt-10.2.1/build/libfmt.a`

if i start the gerbera service i got the following error:
`/usr/local/bin/gerbera: error while loading shared libraries: libfmt.so.7: cannot open shared object file: No such file or directory`

after that i create an symlink
`usr/lib/x86_64-linux-gnu# ln -s /usr/local/lib/libfmt.so /usr/lib/x86_64-linux-gnu/libfmt.so.7`

i am uncertain why gerbera want libfmt version 7. after creating the link i got the 
`/usr/local/bin/gerbera: undefined symbol: _ZN3fmt2v712format_errorD1Ev`

**Comment by KarlStraussberger** [comment]
You should properly **uninstall** the libfmt package which will finally remove the /usr/lib/x86_64-linux-gnu/libfmt.so.7, then run the `build_deb.sh` again. The problem is the search order for libraries, so the one build by our script under `/usr/local/lib` is not picked because there is one under `/usr/lib`.

**Comment by prinz3nroll3** [comment]
hello,
installed libfmt
`/usr/local/lib/libfmt.so.10.2.1`
`/usr/local/lib/libfmt.so.10`
`/usr/local/lib/libfmt.so`
`/usr/local/lib/libfmt.a`


i ve removed the link and the old packages, rebuild the debian package but after that i got the same error:
`/usr/local/bin/gerbera: error while loading shared libraries: libfmt.so.7: cannot open shared object file: No such file or directory`

**Comment by prinz3nroll3** [comment]
the package name:
`gerbera (2.0.0+38~20240122230006-bookworm1)`

**Comment by prinz3nroll3** [comment]
hello,
thanks for the help, i ve build gerbera the standard way, now gerbera is running and i ve to change the apache2 config.
