### ISSUE TITLE
Gerbera 2.0 autoscan in config.xml does not work

### ISSUE THREAD

**Issue by EricdeWaal** [gerbera/gerbera#3008]
I added  the following in config.xml, after <magic-file>`</magic-file>`

```
<autoscan use-inotify="yes">
  <directory location="/data/Music" recursive="yes" hidden-files="no" media-type="Music"/>
</autoscan>
```

With or without ' media-type="Music" ', this completely messes up the output. Just some years at the highest level, and under each year some (apparently random) tracks.

Configuration: default Gerbera generated, only changes: database=mysql and home=/var/lib/gerbera
OS: Debian 11 (bookworm), gerbera (1:2.0.0-dmo0~bpo12+2) - [amd64] - [Stable-backports/bookworm-backports] from Deb Multimedia.

**Comment by KarlStraussberger** [comment]
I suppose this is the issue we already solved. The 2.1 isn't far away. In the meantime, you may try to get hold of some development (testing build).

**Comment by EricdeWaal** [comment]
Thank you, looking forward to 2.1!
I'll post another issue regarding strutured layout as a new item today.
