### ISSUE TITLE
Box Layout settings without effect with "builtin" virtual-layout

### ISSUE THREAD

**Issue by gobater** [gerbera/gerbera#3012]
Setting **enabled** to false in any of the _box_ entries in _box-layout_ does not have any effect when using **builtin** virtual-layout

Example, the following entry in the config file has no effect
`<box key="Audio/allSongs" title="All Songs" class="object.container" enabled="false"/>`

*Branch*: master
*Commit*: becd5b545187cff450e843efb536ea2d9aefb725

@KarlStraussberger, I have managed to have an efficient way to develop and debug gerbera in my Windows machine using Docker and CLion. If you give me a hint where to look, I can try to fix it by myself. I guess it's in "builtin_layout.cc", right?

**Comment by gobater** [comment]
@KarlStraussberger , I fixed it by myself.

Could you please have a look to my PR: https://github.com/gerbera/gerbera/pull/3013 and give some feedback?
Then I would continue with Video, Images...

**Comment by gobater** [comment]
if builtin is just a fallback, maybe we should consider changing the defaults :-)
Nevertheless, fallback or not, we need to align both. Currently may of those options are not used (even in JS)

**Comment by KarlStraussberger** [comment]
Builtin is intended for small boxes without space for js. They may differ. I'm nit sure about enabling js by default.

When introducing the box-layout, the goal was to hide "new" containers, but feel free to apply it to "old" ones as well.

**Comment by gobater** [comment]
Done, and also fixed a bug in Apple Trailers (Genres)
