### ISSUE TITLE
How to get old structured layout back on Gerbera 2.0?

### ISSUE THREAD

**Issue by EricdeWaal** [gerbera/gerbera#3022]
For Gerbera 1.x, I had in my config file:
`<virtual-layout type="js" audio-layout="Structured">
	<structured-layout skip-chars="" album-box="26" artist-box="7" genre-box="6" track-box="26" div-char="-"/>`
That gave me a simple alphabet based pre-selection which is absolutely necessary for a large music collection.

If I try that for version 2.0, I get full lists of all artists, albums, etc which is unworkable. The former structured-layout options no longer seem to work.
So how can I get my previous layout back?

System: 
Debian 12 (Bookworm), 
Gerbera 1:2.0.0-dmo0~bpo12+2 from Stable-backports/bookworm-backports http://www.deb-multimedia.org/dists/stable-backports/
import-mode: default (not set in config file)

**Comment by KarlStraussberger** [comment]
It's just that the configuration has changed here. Your scripting section has to look like this
```
    <scripting script-charset="UTF-8">
      <script-folder>
        <common>/usr/local/share/gerbera/js</common>
      </script-folder>
      <import-function>
        <playlist>importPlaylist</playlist>
        <meta-file>importMetadata</meta-file>
        <audio-file>importAudioStructured</audio-file>
        <video-file>importVideo</video-file>
        <image-file>importImage</image-file>
        <trailer>importTrailer</trailer>
      </import-function>
      <structured-layout skip-chars="" album-box="26" artist-box="7" genre-box="6" track-box="26" div-char="-"/>
```

This is an adapted default configuration optained by `gerbera --create-config`.  The box sizes have gone to the boxlayout `size=...`. Just create the default and copy the section to your personal config.

**Comment by KarlStraussberger** [comment]
Now you may even translate your folder names 😄

**Comment by EricdeWaal** [comment]
Thanks for your quick reply!

Is `<virtual-layout type="builtin">` not missing in the above, and should it not be set to structured?

> The box sizes have gone to the boxlayout size=.... Just create the default and copy the section to your personal config.
I'm not quite sure where to put this and what it does. Should I enter siz="7" for the artisst box for example?

**Comment by KarlStraussberger** [comment]
You're right.
It's just a quick excerpt.  It has to be `<virtual-layout type="js">`. Otherwise the structured layout is not available at all.
