### ISSUE TITLE
gpg: no valid OpenPGP data found

### ISSUE THREAD

**Issue by claudiobizzotto** [gerbera/gerbera#3026]
Got this error while running `apt update` on Ubuntu Jammy (22.04).

Are you guys still using JFrog? [The landing page](https://gerbera.jfrog.io) says _"JFrog's Free-Tier subscription has been deactivated."_

**Comment by KarlStraussberger** [comment]
We are. we even tried to update the subscription but they don't even respond to our request

Closing this because of a long list of duplicates #2988
