### ISSUE TITLE
1.2 launching as daemon

### ISSUE THREAD

**Issue by b4r0z** [gerbera/gerbera#303]
the status command output read:
Process: 28494 ExecStart=/usr/local/bin/gerbera -c /etc/gerbera/config.xml (code=exited, status=1/FAILURE)

but if I do /usr/local/bin/gerbera -c /etc/gerbera/config.xml everything seems fine.

I've been following the info http://docs.gerbera.io/en/latest/daemon.html# but mine is an ARMv71 device.

Any suggestion for a fix?

**Comment by v00d00** [comment]
Perhaps check the systemd journal and see if you got any errors, something like `journalctl -u gerbera -b`

**Comment by b4r0z** [comment]
```
May 21 16:35:53 bananapipro systemd[1]: Started Gerbera Media Server with MySQL.
May 21 16:35:53 bananapipro gerbera[15061]: 2018-05-21 16:35:53    INFO: Gerbera UPnP Server version 1.2.0 - http://gerbera.io/
May 21 16:35:53 bananapipro gerbera[15061]: 2018-05-21 16:35:53    INFO: ===============================================================================
May 21 16:35:53 bananapipro gerbera[15061]: 2018-05-21 16:35:53    INFO: Gerbera is free software, covered by the GNU General Public License version 2
May 21 16:35:53 bananapipro gerbera[15061]: 2018-05-21 16:35:53    INFO: Copyright 2016-2018 Gerbera Contributors.
May 21 16:35:53 bananapipro gerbera[15061]: 2018-05-21 16:35:53    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
May 21 16:35:53 bananapipro systemd[1]: gerbera.service: Main process exited, code=exited, status=1/FAILURE
May 21 16:35:53 bananapipro systemd[1]: gerbera.service: Unit entered failed state.
May 21 16:35:53 bananapipro systemd[1]: gerbera.service: Failed with result 'exit-code'.
May 21 16:35:59 bananapipro systemd[1]: gerbera.service: Service hold-off time over, scheduling restart.
May 21 16:35:59 bananapipro systemd[1]: Stopped Gerbera Media Server with MySQL.

**Comment by b4r0z** [comment]
p.s.:
MySQL? It should be using sqlite, according to config.xml. Is it relevant?

**Comment by elmodaddyb** [comment]
Can you confirm the following items:

1. `gerbera` binary is being launched with a system user as defined in the Systemd unit file...
`gerbera.service`
```
[Service]
Type=simple
User=gerbera
Group=gerbera
```

2.  **gerbera** user has permissions to launch the binary
3.  **gerbera** user has permissions to read the `config.xml`
4.  **gerbera** user has permissions to read/write the `<home>` path specified in config.xml

Thanks,
Eamonn

**Comment by b4r0z** [comment]
It looks like somehow I fixed it.
I guess the problem was the `<home>` path in config.xml which was `/root/.config/gerbera` not accessible by the user gerbera.
I've been creating a new `/home/gerbera` dir to be used has home path and now it seems like the daemon is starting without complaing.

thank you!

**Comment by elmodaddyb** [comment]
@b4r0z - We recently added the `--create-config` option in an effort to eliminate a **write** condition by the daemon against `config.xml`.  It seems likely that the automated prefill of the `<home>` field value during this operation is a continued issue.

I am working to find a way to provide more detail about incorrect `<home>` value and/or eliminate this behavior.  Sorry for any challenges you faced.

**Comment by b4r0z** [comment]
@elmodaddyb no problem at all, it was fun. thank you for your time

**Comment by b4r0z** [comment]
ps
should I close the issue?

**Comment by b4r0z** [comment]
@elmodaddyb no problem, it was fun. thank you for your time.

should I close the issue?

**Comment by elmodaddyb** [comment]
Closing as I will work on a better signal for invalid `<home>` when running daemon mode

1. Better signal on errors
2. Better documentation on generating config.
