### ISSUE TITLE
CDS updates

### ISSUE THREAD

**Issue by compguy284** [gerbera/gerbera#305]
From what I can tell CDS updates have not been working since 054b39f .
In `src/server.cc` either `cmgr->subscription_update(updateString);` should be `cds->subscription_update(updateString);` or the cds one needs to be added.

**Comment by elmodaddyb** [comment]
@compguy284 - Can you help me understand how CDS update occurs?  I am not familiar with the terminology.

Thanks,

**Comment by compguy284** [comment]
All I know is that with `<mark-played-items enabled="yes" suppress-cds-updates="no">` in my mediatomb config I could play a video and then re-browse the directory and the `*` would be there at the front of the filename, but with gerbera that does not happen.
