### ISSUE TITLE
Artist field sometimes not populated in Browse request

### ISSUE THREAD

**Issue by TheMarstonConnell** [gerbera/gerbera#3056]
I am building a UPNP controller currently, and when browsing through the `Albums` folder, only some of my albums have `upnp:artist` fields even though in Gerbera, all of them do.

Gerbera album metadata view:
<img width="1141" alt="image" src="https://github.com/gerbera/gerbera/assets/34043723/2a393d9a-9319-46b3-afcb-44a039b37393">

Returned XML:
```xml
<container id="49070" parentID="20" restricted="1" childCount="9">
	<dc:title>Amok</dc:title>
	<upnp:class>object.container.album.musicAlbum</upnp:class>
	<dc:date>2013</dc:date>
	<upnp:date>2013</upnp:date>
	<upnp:albumArtURI>http://192.168.4.77:49494/content/media/object_id/49064/res_id/1/ext/file.jpg</upnp:albumArtURI>
</container>
```

**Server**
<img width="674" alt="image" src="https://github.com/gerbera/gerbera/assets/34043723/50a6b9ef-04dd-489d-9373-bb0ce502ce1e">
Gerbera Version: Docker: `gerbera/gerbera:sha-b8cf924`

**Comment by whyman** [comment]
That is interesting! Can you attach a debug log?

**Comment by TheMarstonConnell** [comment]
> That is interesting! Can you attach a debug log?

Hey, I'm running it inside docker, where would I find the log files, a search for *.log doesn't show anything and there's nothing in my gerbera folder

**Comment by KarlStraussberger** [comment]
It is album artist that's exported. You can tweak with album properties https://docs.gerbera.io/en/latest/config-server.html#upnp

**Comment by TheMarstonConnell** [comment]
> It is album artist that's exported. You can tweak with album properties https://docs.gerbera.io/en/latest/config-server.html#upnp

Sorry I don't really understand, from what I can tell, nothing is exported, there is no album artist in the XML that gets returned either.

**Comment by KarlStraussberger** [comment]
That's been too brief - wrote in a hurry.

You've got two options
- change your files to contain album artist to get album artist populated (js layout may do that)
- modify the configuration to use `M_ARTIST` (see https://github.com/gerbera/gerbera/blob/b8cf92485a7f85aef2a628562f5c48cc653e033b/src/config/config_definition.cc#L257)

**Comment by TheMarstonConnell** [comment]
Ah thank you very very much, this solved my issue!
