### ISSUE TITLE
2.1.0-18-g2d5a0f95 doesn't work

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3077]
Now I come to exactly the point discussed earlier: I can't surf to any rescue package. 
apt update && upgrade made me sitting on v2.1.0-18-g2d5a0f95. And it doesn't work. It comes with the no-database starting screen and  a blue `<html><body><h1>404 Not Found</h1></body></html>` at the blue status line. 
And since there is no available pool of packages, I can't do what I had preferably done earlier: pick a new version, download it, store it, install it. And if it has problems, uninstall and install the previous package. 
Instead the most recent package was shoved down my throat and the earlier package is gone. 
I'm sure you agree that this isn't the method of choice for bleeding edge software? 

I'd be most happy to receive a link to my previously working 2.1.0-16-g5da4105a.

And, please let's solve this thingy about packages being browseable.

P.S.: This is the line that keeps creeping up at the log: 
`2024-05-04 23:22:05  error: [/build/src/server.cc:591] std::unique_ptr<RequestHandler> Server::createRequestHandler(const char*) const Error: No valid handler type in /content/interface?req_type=auth&action=get_config&GerberaSID=90ea267c-5826-4754-90be-bcf65b9928b2`

**Comment by KarlStraussberger** [comment]
Please consider clearing your browser cache.

**Comment by udippel** [comment]
Done, and works. Thanks, and sorry for not trying in the first place. It was the first time ever that this was necessary.

Please, let's keep on working on browseable repositories, though! I'd rather try new versions at will, not at auto update.
