### ISSUE TITLE
Add note for Ubunutu Bionic Beaver (18.04) to installation notes (non PPA install)

### ISSUE THREAD

**Issue by EraYaN** [gerbera/gerbera#309]
Since the standard PPA does not include a candidate package for `bionic` and the project is in the ["main" repo](https://launchpad.net/ubuntu/+source/gerbera) now. The documentation might need a note on that for some newer versions of Ubuntu. The version seems to be up to date with the PPA (1.1.0).

**Comment by v00d00** [comment]
@stephen-czetty Is the repo maintainer, I would chat to him.

**Comment by emk2203** [comment]
I have exchanged emails with @stephen-czetty just a day ago about that. He wants to update the PPA later this week.

**Comment by stephen-czetty** [comment]
Because I had managed to bork up the versioning so much in the original ppa, I have retired that one and created a new one at ppa:stephenczetty/gerbera-updates.  It contains a 1.2.0 build for bionic, and is based on the 1.1.0 ubuntu build.

Sorry that took so long, I have had a busy year. :)

**Comment by elmodaddyb** [comment]
Great work with supporting the PPA.  I tried to build from source all the needed libraries, and just ran into bunch of issues.

🎉

**Comment by v00d00** [comment]
@elmodaddyb Have you updated the Docs with the new repo?

**Comment by elmodaddyb** [comment]
Yea, I thought the same...will do in the next day.

**Comment by Paul-Ver** [comment]
I believe this is related:
On 18.04 I couldn't do "apt-get install gerbera"
I searched and found the website: https://packages.ubuntu.com/bionic/gerbera 
By adding 'http://nl.archive.ubuntu.com/ubuntu' to '/etc/apt/sources.list'

And by doing 'apt-get update' I could do 'apt-get update install gerbera'.
Seems to work nicely, I was a bit confused by the systemd unit using config from '/etc/gerbera/config.xml' and not '/home/user/.config/gerbera/'

But further than that, confirmed that it works fine under 18.04

**Comment by v00d00** [comment]
Docs were updated in #337
