### ISSUE TITLE
"Cannot add inotify watch: Permission denied" for new folders (`cp -a`)

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3090]
**Describe the bug**
When copying a new music album from my Laptop or Desktop onto my home server's NFS share, Gerbera immediately detects the new folder and tries to add it. It fails with
> warning: Cannot add inotify watch for /data/media/Music/Alben/Coldplay/Viva la Vida or Death and All His Friends: Permission denied
> warning: Cannot add inotify watch for /data/media/Music/Alben/Coldplay/Viva la Vida or Death and All His Friends: Permission denied
> error: Failed to iterate /data/media/Music/Alben/Coldplay/Viva la Vida or Death and All His Friends, Permission denied

When the copy operation is finished, the permissions on the server are correct and Gerbera can read the files in the directories.
I suspect this has something to do with how NFS (or the `cp` tool) handles new folders.

It would be nice if Gerbera would wait for some seconds when a new folder is found and a permission error is encountered, and try again.

**To Reproduce**

0. Share a folder via NFS with second machine. `/etc/exports/` shows:
```
/data/media  boo(rw,sync,no_wdelay,no_subtree_check,no_root_squash,insecure_locks,anonuid=0,anongid=100)
```
1. Use that folder with Gerbera:
```
    <autoscan use-inotify="yes">
      <directory location="/data/media/Music/" mode="inotify" recursive="yes"/>
    </autoscan>
```
2. Copy new music album via NFS into that folder using `cp -a`.
3. Gerbera fails to add inotify watch and fails to scan folder

**Expected behavior**
Gerbera should wait a bit until the directory changes have "settled" and only start its work then.

**Server (please complete the following information):**
 - OS: Debian 12
 - Gerbera Version: v2.1.0-28-g9dd54a98
 - Versions of libraries: 
 - Source: self built from git

**NFS client**
 - Device: Debian 12
 - Client app: mate-terminal

**Comment by udippel** [comment]
What's your take on it? Is it really a NFS problem; or rather a timing problem that could happen to any copy process if said process was actually slow enough?
(Sorry for asking, but in my setup here, though somewhat close, it'd be quite cumbersome to try.)

This 'wait some time' bothers me. Stuff like that tends to fail. We'd better be waiting for a 'ready' flag, like 'process finished'. Controlling sequence instead of arbitrary (and presumably often unnecessary) wait times. 

To me it looks like permissions are set only after finishing copying; while the import method inotify starts recognizing / indexing / whatever once the first inode signals a change. I could be very wrong here, though that's what i understand.

**Comment by KarlStraussberger** [comment]
First of all _Permission Denied_ is quite clear in it's meaning.

The only way we can solve your problem, is to delay after it happened. This could be controlled by some configurable retry count on the autoscan directory. I'm not sure about the effect on the regular import, which does not bother me as long as it's disabled by default.

**Comment by KarlStraussberger** [comment]
Hope, I got it right. Maybe you can try it out before it's merged.

**Comment by cweiske** [comment]
It really seems that the permissions are set afterwards.

Here a 415ms NFS copy operation seen on the client:
```
$ time cp -a ~/Music/neu/ogg/Erhard\ Dietl/Die\ Olchis\ und\ der\ schwarze\ Pirat .
real	0m0,415s
```

The directory list on the server looks that way (nanoseconds after the `-`):
```
09:05:29-343432811
drwx------ 2 cweiske cweiske 4.0K May 21 09:05 Die Olchis und der schwarze Pirat

09:05:29-672953081
drwx------ 2 cweiske cweiske 4.0K May 21 09:05 Die Olchis und der schwarze Pirat

09:05:29-783264982
drwxr-xr-x 2 cweiske cweiske 4.0K Sep 13  2023 Die Olchis und der schwarze Pirat
```

At the end of the 400ms the permissions are set.

----

Gerbera does [not listen to permission changes](https://github.com/gerbera/gerbera/blob/v2.1.0/src/content/autoscan_inotify.cc#L63) via inotify:
```
events = IN_CLOSE_WRITE | IN_CREATE | IN_MOVED_FROM | IN_MOVED_TO | IN_DELETE | IN_DELETE_SELF | IN_MOVE_SELF | IN_UNMOUNT;
```

It would be possible via `IN_ATTRIB`: https://www.man7.org/linux/man-pages/man7/inotify.7.html

**Comment by udippel** [comment]
Thanks for confirming my point.

It was to be expected to work like this, since the file copying ought to have some semaphore about it to avoid race conditions etc. 
Therefore finishing the copy process; that is setting access permissions, is probably the most suitable trigger to start indexing. 
Waiting for arbitrary times is not very sensible; and running circles until it works isn't much better. Rather, it is prone to secondary bugs: Imagine something goes wrong - and anything that can go wrong will go wrong one day - it would run in circles for eternity if the copy process fails at some point. Or, again, a limited arbitrary number of rounds: again unconvincing. 
Preferably is a singular flag 'copying finished' to initiate the import process, like what you described. 
And once import fails at this moment, informing the user is a suitable thing to do.

**Comment by KarlStraussberger** [comment]
> 
> It would be possible via `IN_ATTRIB`: https://www.man7.org/linux/man-pages/man7/inotify.7.html

I was considering that already. But the change is even more complex and in normal operation we get updates without change of file content. On the other side, you do not change your permissions regularly?

**Comment by udippel** [comment]
Sorry, but I'm not into the depths of the copying process at all. Just looking from an overall perspective. It is probably obvious that the preferred procedure is "copying successfully finished" -> "start indexing". If this isn't easy to do, tant pis!

**Comment by cweiske** [comment]
The problem does not occur when using `cp -r`, only when using `cp -a`.

A "normal" `cp -r` creates the directory and closes it, while `cp -a` does the same, but afterwards changes the attributes.

# `cp -r`
`cp -r` immediately sets the correct permissions:
```
drwxr-xr-x 2 cweiske cweiske 4.0K May 21 14:48 ExampleAlbum
```

```
# inotifywait --monitor -r /data/media/tmp/
/data/media/tmp/ CREATE,ISDIR SmallAlbum
/data/media/tmp/ OPEN,ISDIR SmallAlbum
/data/media/tmp/ ACCESS,ISDIR SmallAlbum
/data/media/tmp/ CLOSE_NOWRITE,CLOSE,ISDIR SmallAlbum
/data/media/tmp/SmallAlbum/ CREATE 1.ogg
/data/media/tmp/SmallAlbum/ ATTRIB 1.ogg
/data/media/tmp/SmallAlbum/ ATTRIB 1.ogg
/data/media/tmp/SmallAlbum/ MODIFY 1.ogg
/data/media/tmp/SmallAlbum/ CLOSE_WRITE,CLOSE 1.ogg
```

# `cp -a`
`cp -a` on the other hand first sets permissions for the user only:
```
drwx------ 2 cweiske cweiske 4.0K May 21 14:56 ExampleAlbum
```
and later changes them:
```
drwxr-xr-x 2 cweiske cweiske 4.0K May 21 14:48 ExampleAlbum
```

```
# inotifywait --monitor -r /data/media/tmp/
/data/media/tmp/ CREATE,ISDIR SmallAlbum
/data/media/tmp/ OPEN,ISDIR SmallAlbum
/data/media/tmp/ ACCESS,ISDIR SmallAlbum
/data/media/tmp/ CLOSE_NOWRITE,CLOSE,ISDIR SmallAlbum
/data/media/tmp/SmallAlbum/ CREATE 1.ogg
/data/media/tmp/SmallAlbum/ ATTRIB 1.ogg
/data/media/tmp/SmallAlbum/ ATTRIB 1.ogg
/data/media/tmp/SmallAlbum/ MODIFY 1.ogg
/data/media/tmp/SmallAlbum/ ATTRIB 1.ogg
/data/media/tmp/SmallAlbum/ ATTRIB 1.ogg
/data/media/tmp/ ATTRIB,ISDIR SmallAlbum
/data/media/tmp/SmallAlbum/ ATTRIB,ISDIR 
/data/media/tmp/ ATTRIB,ISDIR SmallAlbum
/data/media/tmp/SmallAlbum/ ATTRIB,ISDIR 
/data/media/tmp/ ATTRIB,ISDIR SmallAlbum
/data/media/tmp/SmallAlbum/ ATTRIB,ISDIR 
/data/media/tmp/SmallAlbum/ CLOSE_WRITE,CLOSE 1.ogg
```

**Comment by udippel** [comment]
Beat me to it, well done, wanted to look at the same source tonight!
However, can you confirm the '`-a`'? I think it is just a concatenation of some parameters with some '`-r/R`'? I mean for the change of title, and the inherent logic?

**Comment by cweiske** [comment]
Thank you so much @KarlStraussberger!
