### ISSUE TITLE
`<box enabled="true|false">` or yes/no?

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3098]
**Describe the bug**
While trying to validate my configuration file for #3092 I had to fix the config2.xsd file and saw that 
```
<xs:attribute name="enabled" type="boolean" default="true"/>
```
and the docs also say https://docs.gerbera.io/en/stable/config-import.html#box
> enabled="false"
> Optional
> Default: “true”

All other "enabled" attributes use yes/no, and the XSD boolean type only allows yes and no as values.

I suggest the allowed values for `box enabled` attribute are also changed to yes and no.

**Comment by KarlStraussberger** [comment]
In fact, all boolean values allow `true`/`false` as well as `yes`/`no`. Except `use-inotify` which only allows (up to now) only `yes`/`no. So feel free to clean that up.
