### ISSUE TITLE
FreeBSD 11.1 "make" installation step can't find uuid/uuid.h

### ISSUE THREAD

**Issue by djbelly** [gerbera/gerbera#310]
Installing ossp-uuid doesn't help.

However, it compiles and works if `/usr/include/uuid.h` is copied to `/usr/include/uuid/uuid.h`.

**Comment by v00d00** [comment]
Which version/tag are you trying to build?

**Comment by djbelly** [comment]
Thank you for the followup. It’s the current master. Here’s what I saw.

[ 10%] Building CXX object CMakeFiles/libgerbera.dir/src/config/config_generator.cc.o
/root/gerbera/src/config/config_generator.cc:32:10: fatal error: 'uuid/uuid.h'
      file not found
#include <uuid/uuid.h>
         ^~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.

And if I: # mkdir /usr/include/uuid && ln -s /usr/include/uuid.h /usr/include/uuid/
It compiles, installs, and runs.

**Comment by elmodaddyb** [comment]
@djbelly - This is my mistake, forgot to wrap the UUID import with BSD specifc stuff (similar to config_manager.cc)

```config_generator.cc
#ifdef BSD_NATIVE_UUID
#include <uuid.h>
#else
#include <uuid/uuid.h>
#endif
```
