### ISSUE TITLE
Key mismatch

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3107]
What is going on? Key change intentionally? Because of a compromise?

```
Get:6 https://pkg.gerbera.io/debian-git jammy/main amd64 Packages [593 B]
Err:6 https://pkg.gerbera.io/debian-git jammy/main amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:593 [weak]
   - SHA256:694bf4aa82ff2e439d415c4e3a079efaaf966237ec63dacb9a48b02272eb194b
   - SHA1:fde6dfc8dc041d8c2f26261adf9df02978057112 [weak]
   - MD5Sum:16a4008eae4cf60bf226b76930172af7 [weak]
  Hashes of received file:
   - SHA256:c6476f7462d28ef42a0ed2a255d9e4838c96c61dcb011472c7f48c86f76607a2
   - SHA1:abaf5db1915e8739bceb6cfed91b6ac9e54d4fbf [weak]
   - MD5Sum:84cb1d0dde20e69f06b2fc068ac5e361 [weak]
   - Filesize:593 [weak]
  Last modification reported: Fri, 31 May 2024 16:47:03 +0000
  Release file created at: Fri, 31 May 2024 16:02:35 +0000
```
If not intentionally, why not write the original back? 
If intentionally, let us users update.
If compromised, inform the users to quickly remove the compromised key. 

Please, provide some details!

**Comment by KarlStraussberger** [comment]
There is an issue with that repo

```
Repository is locked by another user:  at host 06433ec7a862 (phase-1)
```

I hope it resolves by itself...

**Comment by udippel** [comment]
Resolved by itself or not. 
For someone with a knowledge of security, it doesn't instill confidence when the key CHANGES, respectively can be changed by some 'another user'. Unavailable would be okay. That can happen. Though returning just another key ... ? Injecting malware through one channel doesn't limit the potential intrusion to just one package ... .

**Comment by KarlStraussberger** [comment]
Just to make things clear: as an unpaid open source community, we are relying on infrastructure provided to us for free. We are not maintaining all of it and only see part of it in configurations.

In case of your problem, it seems that any of our upload tasks got stuck and blocked the creation of hashes, making the download invalid - which is high security.

Before blaming us for things we cannot fully control, I ask you to analyse the issue to gain better understanding. If you do not do say, stay with reporting the facts. Thank you.

**Comment by udippel** [comment]
Of course it usually is a repository error. I was simply lead to believe something else due to that "... locked by another user ...". As you wrote, it looks like it couldn't be updated properly. And surely, once it can provide 'clean' files it will resolve itself. 
My excuses for the noise. Now waiting for the next clean update ... .

**Comment by KarlStraussberger** [comment]
@whyman Can you take a look at the repo. The lock does not go away automatically.

**Comment by whyman** [comment]
Hrm, Ive manually deleted the lock files. Would be interesting to know the cause, a failed upload or something?

**Comment by whyman** [comment]
No key change or compromise that I am aware of, FWIW.

**Comment by whyman** [comment]
No key change or compromise that I am aware of, FWIW.
