### ISSUE TITLE
Gerbera not found by TechniSat DigitRadio 580

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3115]
**Describe the bug**
The Gerbera UPnP server does not get discovered by a TechniSat DigitRadio 580 anymore after updating to the latest git version.

A `git bisect` told me the responsible commit is 2d5a0f9501d9f41e5f958577f5e933a2758e4ed6:
```
# git bisect bad
2d5a0f9501d9f41e5f958577f5e933a2758e4ed6 is the first bad commit
commit 2d5a0f9501d9f41e5f958577f5e933a2758e4ed6
Author: Ian Whyman <ian@gerbera.io>
Date:   Wed May 1 21:40:04 2024 +0100

    Server: Handle all HTTP via virtualdir
```

All the following commits up to fc9191543faacc37c8745faf6d7186b647990b19 expose this problem.

**To Reproduce**

0. Start Gerbera
1. Scan for UPnP servers on the DigitRadio
2. Loading spinner is shown for 10 minutes

**Expected behavior**
The UPnP server is found and shown on the radio.

**Server (please complete the following information):**
 - OS: Debian 12
 - Gerbera Version: since v2.1.0-18
 - Source: self built

**Media client (please complete the following / remove not applicable:**
 - Device: TechniSat DigitRadio 580 (Frontier Smart / Frontier Silicon chipset)

**Comment by cweiske** [comment]
I see that it fetches the following files:
- `/upnp/description.xml`
- `/upnp/mr_reg.xml`

but it does not show the server.

**Comment by cweiske** [comment]
The differences in the supplyment of the `mr_reg.xml` file are:
- content-length header is missing now
- `CONTENT-TYPE: application/xml`, previously it was `text/xml`
- `LAST-MODIFIED: Thu, 01 Jan 1970 00:00:00 GMT` while previously it had the current date: `LAST-MODIFIED: Tue, 04 Jun 2024 06:37:30 GMT`
- XML does not have the XML header anymore: `<?xml version="1.0" ?>`

HTTP requests and responses: 
[mr_reg-broken.txt](https://github.com/user-attachments/files/15543655/mr_reg-broken.txt)
[mr_reg-ok.txt](https://github.com/user-attachments/files/15543656/mr_reg-ok.txt)

**Comment by whyman** [comment]
This is a fantastic bug report, thanks so much, I wish they were all this good.

**Comment by KarlStraussberger** [comment]
I already found some flaws...

**Comment by KarlStraussberger** [comment]
All of the sudden browsing with Windows Explorer works again
