### ISSUE TITLE
Dynamic placeholder for last played videos

### ISSUE THREAD

**Issue by vinod4dev** [gerbera/gerbera#3120]
Users sometimes start playing movies &  pause it to resume later . In the meanwhile  they might jump to another movies/series and might want to resume playback of the previous item or one of  the last played items  i.e. hop between content  .

 Gerbera already tracks  lastplayed status of an item and I see it is nested deep inside a json array as part of the metadata field ( as noted from the json response on the web UI) . It fetches this from grb_playstatus table .

I tried configuring a dynamic folder on similar lines as "Last updated" ( upnp:class derivedfrom "object.item" and last_updated > "@ last7" )  using the syntax  "upnp:class derivedfrom object.item.metadata.metadata and exists lastPlayed" and then sorted by lastPlayed .But it gave no results .  Either my search  syntax is wrong or may be we cannot query the metadata currently . 

Suggest to add this feature and enable the configuration by default  for ease of use so that users could simply resume playback with 1 or 2 clicks instead of navigating & trying to recall the file they last played .

**Comment by KarlStraussberger** [comment]
This is a very nice idea.

In fact, we return that detail not the way it is stored. So the feature will involve some database coding.

**Comment by KarlStraussberger** [comment]
There's going to be `upnp:lastPlaybacktime` and `upnp:playCount` which can be used in searches and dynamic containers. Including sorting support.

**Comment by vinod4dev** [comment]
Great . I just updated from 2.3 to 2.4  .I'll give this a shot .. Cheers
