### ISSUE TITLE
External Link (URL) via Web UI creates wrong DB entry

### ISSUE THREAD

**Issue by Smartsmurf** [gerbera/gerbera#3122]
Running Gerbera v2.1.0-59-gcb21b7e3 

Add Item

Type: External Link (URL)
Title: test
Location: http://myserver.local/file.mp4
Class: object.item.videoItem
Description: more test
Mimetype: video/mp4
Protocol: http-get

When opening the file then the browser gets redirected to:

http://gerbera-server:49152/http%3A%2F%2Fmyserver.local%2Ffile.mp4

The logfile shows:
2024-06-11 01:14:12.782  error: [server.cc:622] operator()(): Exception: [/home/builder/src/gerbera/src/server.cc:604] std::unique_ptr<RequestHandler> Server::createRequestHandler(const char*) const Error: No valid handler type in /http:/myserver.local/file.mp4

**Comment by KarlStraussberger** [comment]
I cannot reproduce the issue. What browser are you using. What's your os, package source? (See bug template for further questions)

**Comment by Smartsmurf** [comment]
Server (please complete the following information):

    OS: Ubuntu 22.04
    Gerbera Version: v2.1.0-59-gcb21b7e3
    Versions of libraries: [e.g. taglib, libexiv2]
    Source: self built

cmake ../ -DWITH_MAGIC=ON -DWITH_MYSQL=OFF -DWITH_CURL=ON -DWITH_INOTIFY=ON -DWITH_JS=OFF -DWITH_TAGLIB=ON -DWITH_AVCODEC=ON -DWITH_EXIF=ON -DWITH_EXIV2=OFF -DWITH_MATROSKA=ON -DWITH_SYSTEMD=ON -DWITH_NPUPNP=ON -DWITH_FFMPEGTHUMBNAILER=ON -DWITH_DEBUG=OFF -DWITH_TESTS=OFF -DCMAKE_INSTALL_PREFIX=/usr

Media client (please complete the following / remove not applicable:

    Device: Ubuntu 22.04
    Client app: FireFox
    Browser: FireFox

**Comment by Smartsmurf** [comment]
Update: installed the latest release v2.1.0 using the amd64.deb package. This works. So something must be broken in my dev environment.

Thanks for looking into my issue and sorry for inconvenience.

**Comment by KarlStraussberger** [comment]
There are two common fail reasons:
- The config file is pointing to the wrong "web" directory (`<webroot>/usr/share/gerbera/web</webroot>`)
- The web directory contains old javascript files that are loaded instead of the new ones.
