### ISSUE TITLE
Rescan library functionality  problem

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3123]
(We had a similar discussion last year, on how to redo the database content only, without rm the database; thereby not losing settings.)

Found yesterday that 8 out of 9 files in (at least) one directory was missing in the database, while being available on the physical drive. The normal debug/log that I always redirect into a file showed some bad errors. Reasons unknown, though on my side, nothing to do with gerbera. (see first part of attachment)

Hoping for a reboot, to rescan the directories, find those files and re-add them to the database. It found other trouble (see attachment). 

With another restart the matter was settled log-wise, but the files still missing.

Next, a restart with --debug. I don't understand what exactly is going on (see attachment), but those files do show up during the scan, and yet fail to be seen in the database. 
(Edit: To be precise: I'm not talking about the Ironside directory, but the two files of Police Squad, that are not listed in the Database View any longer. They show up at the initial scan after restart of gerbera, and show up at Rescan Library. So the functionality seems correct, but the re-addition to the database, respectively the detection that they are missing in the database seems flawed.)
Also, the overall number of files in the overview hasn't changed since the days before this disappearance of the database entries. Seemingly, this number isn't calculated, but stored after a change that gerbera is aware of? 
With 10.000+ files, I don't know if this effects more that this single directory.

I'd still be happy to have a chance of a Rescan Library [from scratch] that doesn't require rm. 

I'll leave everything at this point, so that a further debug could be possible in case of a request of specific data. 
Version: 2.1.0-41-g833e54a6

[no_find_1.log](https://github.com/user-attachments/files/15786507/no_find_1.log)

**Comment by KarlStraussberger** [comment]
This looks like some major issues with your disk. Unreadable dirs and files are not gerberas fault. The ffmpeg message means that the files are flawed and gerbera does not get data to create the virtual layout.

If you want to rescan, delete everything from "PC Directory" and restart gerbera.

If you reboot with removable devices make sure gerbera does not start too early.

**Comment by udippel** [comment]
Thanks a bunch! - That's exactly what I wrote, "nothing to do with gerbera", and what I was looking for: a rescan from scratch. Finally I know how to that, and that makes me very happy!

It might still be fortunate to have a visible option additionally to Rescan Library, which seemingly doesn't notice missing database entries and probably just scans for new files, to re-create the database. 
I had the autoscan directory under PC Directory deleted, restarted, and then actually all files were picked up; including all the problems in the file system, but that didn't bother me since I only wanted to confirm that the database can be  recreated from scratch through this method. It can, great!
