### ISSUE TITLE
error: 'GrbLogger' does not name a type

### ISSUE THREAD

**Issue by count00zero** [gerbera/gerbera#3139]
Last successful build was right before june 13th; so I guess the following commit did something?
https://github.com/gerbera/gerbera/commit/fb914d9b55a6751a3b97a7e9d59eccf83e23f9f7

[ 78%] Building CXX object CMakeFiles/libgerbera.dir/src/util/logger.cc.o
/opt/_Build/gerbera-git/src/util/logger.cc:131:1: error: ‘GrbLogger’ does not name a type
  131 | GrbLogger GrbLogger::Logger;
      | ^~~~~~~~~
make[2]: *** [CMakeFiles/libgerbera.dir/build.make:1644: CMakeFiles/libgerbera.dir/src/util/logger.cc.o] Fehler 1
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/libgerbera.dir/all] Fehler 2
make: *** [Makefile:156: all] Fehler 2

**Comment by whyman** [comment]
Can you post your build options please?

**Comment by count00zero** [comment]
yeah, of course and thanks for the support!!

cmake .. -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIV2=1 -DWITH_SYSTEMD=0 -DWITH_DEBUG=0 -DWITH_MATROSKA=1 -DWITH_WAVPACK=1

**Comment by count00zero** [comment]
thx a lot! You guys are stars :-)
