### ISSUE TITLE
Change -cc in Edit Details to unmodified display

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3148]
[This is a continuation of #3143]

Having looked more deeply into the matter, I think that we don't treat the -cc correctly. According to e.g. [(https://www.metadata2go.com/file-info/codec-tag)], `codec_tag` s could be interpreted as 'human readable values'. 
However, an extended research has turned up a large batch of usage of the FourCC to steer decoders through non-alphanumeric bit masks. [(https://learn.microsoft.com/en-us/windows/win32/medfound/audio-subtype-guids)] is an example. Maybe not directly related to the video data underlying #3143, it does show that encoding as printables can be misleading.
Other examples can be found in [https://ffmpeg-devel.ffmpeg.narkive.com/FC3ikTjg/4xm-audio-codec-tag], showing that something like "JPEG" can be useful, but that `codec_tag` s do not necessarily need to be human readable. 

Therefore, my primary suggestion is, to either remove the codec_tag "`-cc`") altogether, or going back to it actually displaying the Hex-values as such, like what was visible in 88. 
Reason for removing it altogether is, naturally, not confusing the user for bit-controlled formats, like `0x001b`. A LUT makes no sense, with 32 bit, anyone can create codec_tags of his own choice, to steer decoders on the side of users as he likes. A provider could theoretically use such codec_tags to control a decoder delivered to end users. 
Against dropping this detail: it does make some sense to display a somewhat useful information, e.g. `mp4v`, provided the codec_tag offers that information.

**Comment by KarlStraussberger** [comment]
We display this information in the details page of a media file. If it happens that the encoder wrote some non-printable bit-masks we display this by the chosen (json compatible) solution with leading \.

**Comment by udippel** [comment]
It's your decision, though IMHHO not so good and sensible. 
If - like in many cases - the hex values are non-printable, the rendering to 'grinning faces' serves no purpose and rather produces confusion. 
I do understand you prefer to show MIME types, whatever. If the value contains some decoding control bits instead, let's better show nothing.
