### ISSUE TITLE
2.2.0 doesn't honor my '<port>' setting

### ISSUE THREAD

**Issue by stheine** [gerbera/gerbera#3153]
**Describe the bug**

I want to run on a different port than the default 49494, so I have configured server/port in the config.xml.
but this is not honored by the server and it still comes up on the default.

**To Reproduce**

this is a snipped from my config.xml
```
  <server>
    <name>Gerbera (Filme)</name>
    <port>59158</port>
    <udn>uuid:a795cd7e-2515-4187-9b0c-c2223cc85803</udn>
    <home>/gerbera_home</home>
```

```
2024-07-13 09:21:58   info: Initialising UPnP with interface: <unset>, port: 49494
2024-07-13 09:21:58   info: IPv4: Server bound to: 192.168.6.5:49494
2024-07-13 09:21:58   info: IPv6: Server bound to: fe80::f2d4:e2ff:fef4:3e27:49494
2024-07-13 09:21:58   info: IPv6 ULA/GLA: Server bound to: 2002:5fd0:56ed:0:f2d4:e2ff:fef4:3e27:49494
2024-07-13 09:21:58   info: The Web UI can be reached by following this link: http://192.168.6.5:49494
```

you can see other values from my config are used:
![image](https://github.com/user-attachments/assets/f35702fd-8035-4901-96a2-2688d7ae0d9f)

**Expected behavior**
I want to be able to configure the server/port.

**Server (please complete the following information):**
 - OS: docker, gerbera/gerbera:latest
 - Gerbera Version: 2.2.0
 - Versions of libraries: whatever is in that docker image
 - Source: docker.hub

**Comment by KarlStraussberger** [comment]
Please try to run gerbera with `--debug --check-config` to see any warning pointing to the issue.

You may also try setting the `interface` to force libpupnp to  use the correct network device.

**Comment by KarlStraussberger** [comment]
It's in Dockerfile to set up the container correctly

https://github.com/gerbera/gerbera/blob/master/Dockerfile#L122-L128

**Comment by stheine** [comment]
I'm using the docker container from docker hub ( https://hub.docker.com/r/gerbera/gerbera ), so I have no control over the Dockerfile.
also, I cannot map the port container-internal port to an different external port, due to the `network_mode: host` configuration that's required to run in docker (for the broadcast port 1900).

isn't it simply a bug in gerbera, that it doesn't honor the port from config.xml?
or shouldn't the Dockerfile cmd not contain the `--port` to use gerbera's default setting instead, which would then allow setting in config.xml?

```
 $ docker-compose exec gerbera-filme /bin/sh
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:06 /sbin/tini -- docker-entrypoint.sh gerbera --port 49494 --config /var/run/gerbera/config.xml
    7 gerbera   0:31 gerbera --port 49494 --config /var/run/gerbera/config.xml
 6720 root      0:00 /bin/sh
 6727 root      0:00 ps
/ # grep -e server -e 'port>' /var/run/gerbera/config.xml
  <server>
    <port>59158</port>
  </server>
  </import>
```

**Comment by KarlStraussberger** [comment]
The semantics is that command line overrides config.xml

You can run the docker image with `docker run --expose <your-port> gerbera:latest gerbera --port <your-port> ...`

**Comment by stheine** [comment]
ok, thanks. I didn't remember that I could overwrite the startup command in docker cli or docker-compose.yml.

so not I'm setting the command to
`/sbin/tini -- docker-entrypoint.sh gerbera --config /var/run/gerbera/config.xml`
making it not specify a port in the command line, so it falls back to the default or config.xml and uses the one from there.

this ok as a workaround.

but I think it should go into the documentation of https://hub.docker.com/r/gerbera/gerbera . for some reason you have defined that this docker image runs on port 49494, instead of the default (automatic >= 49152), and without the workaround the port cannot be changed, and the documented configuration ( https://docs.gerbera.io/en/stable/config-server.html#port ) does not work.

**Comment by KarlStraussberger** [comment]
The readme already mentions the port. This can be slightly improved as any documentation.

**Comment by stheine** [comment]
thanks for the doc updates.
