### ISSUE TITLE
Log warning when import script does not return an array

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3162]
**Describe the bug**
We went on a wild bug hunt at #3091 because my custom import script (that worked with gerbera 2.0.0) missed some changes needed for 2.2.0.
My import script did offload the tasks to the original `addAudio` function but swallowed the return value.

Gerbera should log a warning when an import script does not return an array but null/void.

**To Reproduce**
0. Create custom import script that has no return value.
1. Touch a file to let gerbera reindex it
2. File will vanish from virtual index.

**Expected behavior**
gerbera should write a log message that warns the user about the import script function not returning an array.

**Comment by KarlStraussberger** [comment]
You just detected the flaw in the change. I was thinking that javascript (like other scripting languages) always returns the result of the last command. After checking with the specs and duktape documentation there is a solution on its way.
