### ISSUE TITLE
https://pkg.gerbera.io/: Error 404

### ISSUE THREAD

**Issue by zz0rk** [gerbera/gerbera#3165]
**Describe the bug**
I am trying to access precompiled packages from https://pkg.gerbera.io/. When I am trying to access the page, I am getting a 404 error. The object cannot be found.

**To Reproduce**
0. Relevant config: [e.g. import mode, layout mode]
not applicable
1. Start service with config [relevant config]
not applicable
2. Action on client or filesystem
not applicable
3. See error
Open https://pkg.gerbera.io/

**Expected behavior**
https://pkg.gerbera.io/ opens with a list of precompiled packages.

**Server (please complete the following information):**
none of the below are applicable
 - OS: [e.g. Ubuntu:20.04]
 - Gerbera Version: [e.g. 2.0]
 - Versions of libraries: [e.g. taglib, libexiv2]
 - Source: [e.g. jfrog, self built]

**Media client (please complete the following / remove not applicable:**
none of the below are applicable
 - Device: [e.g. iPhone6, Samsung TV, HEOS Multi room]
 - Client app: [e.g. BubbleUpnp, Foobar2000, Kodi]
 - Browser: [e.g. chrome, safari]

**Additional context**

**Comment by KarlStraussberger** [comment]
Sorry for the inconvenience but at the moment you cannot browse the packages. But after adding the repo to your system it automatically picks the right package. See https://docs.gerbera.io/en/stable/install.html#ubuntu-mint

**Comment by zz0rk** [comment]
Is this Ubuntu/Mint only? I am running Debian 12. Thanks, Karl

**Comment by KarlStraussberger** [comment]
It contains Debian as well.

**Comment by zz0rk** [comment]
See https://docs.gerbera.io/en/stable/install.html#ubuntu-mint repository.
