### ISSUE TITLE
LFS issue on 32-bit systems

### ISSUE THREAD

**Issue by whitefalk** [gerbera/gerbera#317]
With gerbera 1.2 and libupnp 1.8.3 I have the following issue:
On 32-bit systems videos stop at a point in time where 2GB is size is reached.
Tested on: 
xubuntu 18.04 x86 -> failed, (video terminates)
archlinux-arm armv7 -> failed, 
gentoo amd64 (nomultilib) -> works, (video plays to end)
kubuntu  18.04 amd64-> works

looking at the (32 bit) binary of gerbera and libupnp symbols fopen64, fseek64 and so on are seen, so LFS seems to be configured properly.
I would suspect some kind of issue with type "long int" or size_t as they have different size on 32-bit/64-bit platforms.

I so far can't trace through gerbera/libupnp to find the source of the issue.

I would debug if I get some hints.

Cheers!

**Comment by v00d00** [comment]
Is this transcoding? Or regular file playback?

**Comment by whitefalk** [comment]
In the config transcoding is not enabled. This happens when I play a video on a TV, but I also tried VLC on windows as a playback device.
Where should I start debugging this at all?
I'm not convinced that this is not upnp-s fault, as for example their samples don't compile (bad makefile, but non the less) on 32-bit, so I guess it was never tested.

**Comment by v00d00** [comment]
So we register virtual callbacks in https://github.com/gerbera/gerbera/blob/09c3d57349b5a3f33fc474d2866a8ff0fa858253/src/server.cc#L458

There are commented out debug lines, which will help you see what calls libupnp is making into us.

**Comment by whitefalk** [comment]
Hi,

Thank you for the hint, I found what I was looking for quickly after that! I looked through the code and found the issue, although I had no time to test it completely. The bug seems to be in libupnp since 2010. The libupnp included with mediatomb did not have this issue.

They cast off_t (8 Bytes with LFS) to size_t (4 Bytes on 32-bit Linux) and that causes files above 2GB to be played only to 2GB.

**Comment by elmodaddyb** [comment]
Great job investigating. I’ve run files greater than 2gb, but only on x86_64. :/

**Comment by v00d00** [comment]
For future readers, @whitefalk has raised this with upstream pupnp: https://github.com/mrjimenez/pupnp/issues/81

**Comment by whitefalk** [comment]
Maybe when it's fixed in pupnp, gerbera should throw a warning, or do a version check of pupnp .
