### ISSUE TITLE
Error message in Docker container

### ISSUE THREAD

**Issue by matthiasklabe** [gerbera/gerbera#3172]
**Describe the bug**
having a look into the log of the container i find following entry which will "refreshed" ever couple of seconds

"2024-08-03 21:07:24  error: Exception: [/gerbera_build/src/server.cc:622] std::unique_ptr<RequestHandler> Server::createRequestHandler(const char*) const Error: No valid handler type in /service/recordings/get"

**To Reproduce**
unfortunatelly never tested it on AMD64 hardware, all trys on ARM run into same issue

**Expected behavior**
no messages like this , because it writes endless logs which fills my SSD

**Server (please complete the following information):**
Hardware: RaspberryPi 5 / 8GB with OS: Bookworm 64 headless
Docker 27.1.1.
Portainer: 2.20.3 (sts) 

- used "docker-compose.yml"

 version: "2.2"
services:
  gerbera:
    image: gerbera/gerbera
    container_name: minidlna
    network_mode: host
    environment:
      - TZ=Europe/Berlin
    volumes:
      - gerbera-config:/var/run/gerbera
      - data:/mnt/content:ro
    restart: unless-stopped

volumes:
  gerbera-config: {}
  data: {}

**Media client (please complete the following / remove not applicable:**
 - Device: Android Samsung S22
 - Client app: Hi-Fi Cast
 - Browser: n.a

**Additional context**
stream itself is working, but error message srives me crazy...not sure what to do here

**Comment by KarlStraussberger** [comment]
The message points to a client that requests an unknown address.

Do you have other containers/servers running that may be the real target.

**Comment by matthiasklabe** [comment]
Thanks for Quick Response. No, there are no other client asking unknown adress.

At docker machine following container running:
- Unifi Controller
- MongoDB
- Freeradius/Daloradius
- Pihole

no conflicts, all applications are working fine.
Maybe I can try to switch off all not needed Clients...this will bring more details.

Let me try it tomorrow and write back, if tested.

**Comment by matthiasklabe** [comment]
Hello again, I checked the issue and figured out:

192.168.X.Y | MR401B.fritz.box | default | Unknown | Zenterio/0x800D-2024.1.139.2-1243 | None |   | None | 

My mediareceiver from Telekom is causing the issue...maybe it is looking for some space for recording.

Is there any option to exclude clients in GERBERA?

**Comment by KarlStraussberger** [comment]
The proper way for a client is to check the supported services and send their requests afterwards. Blocking such clients is an option which is not YET implemented.

**Comment by KarlStraussberger** [comment]
You can try it out if you switch to the latest container storage

**Comment by matthiasklabe** [comment]
Thanks for the info, I tried to pull latest image with ":latest", but it was not loading a fresh image. Because reason is more clear now, I  can wait till final release

**Comment by matthiasklabe** [comment]
[#3172.pdf](https://github.com/user-attachments/files/16501658/3172.pdf)

I added a PDF with all information. Hope this helps and please excuse my missing knowledge here

**Comment by KarlStraussberger** [comment]
Now you should be able to test this.

First of all you need to add the following lines to you `config.xml` (e.g. after the `</server>` closing tag)
```
<clients enabled="yes">
  <client userAgent="Zenterlo" allowed="no"/>
</clients>
```

Afterwards run `docker pull gerbera/gerbera:edge-transcoding` to get the latest version.

After starting gerbera the messages should disappear.

**Comment by matthiasklabe** [comment]
worked! also excluded my fritzbox.... THX
