### ISSUE TITLE
Apple Trailers Discontinued

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#3178]
**Describe the bug**
Apple merged trailers into AppleTV making our integration obsolete

**To Reproduce**
0. Go to https://trailers.apple.com/trailers/home/xml/current.xml
1. It is redirected to https://tv.apple.com/
2. There is no trailer data in the web page resources anymore

**Expected behavior**
Remove Gerbera Support for apple trailers

**Comment by KarlStraussberger** [comment]
Just wanted to improve the configuration and found it's dead...

**Comment by whyman** [comment]
I always wondered how useful it was anyway 😂

**Comment by KarlStraussberger** [comment]
Activated it to get SEGFAULTs for a lifetime.
