### ISSUE TITLE
MySQL database

### ISSUE THREAD

**Issue by nrietsch** [gerbera/gerbera#318]
Hi,

I'm using Ubuntu 16.04 with MySQL server 5.7

I modified the /etc/gerbera/config.xml file as follow:
```
    <storage>
      <sqlite3 enabled="no">
        <database-file>gerbera.db</database-file>
      </sqlite3>
      <mysql enabled="yes">
        <host>localhost</host>
	<port>3306</port>
	<database>gerbera</database>
        <username>username</username>
	<password>password</password>
      </mysql>
    </storage>
```

This is based on the following article:
https://wiki.gentoo.org/wiki/Gerbera#MySQL

`<host>` has been set to 'localhost' and its IP address
`<port>` has been omitted and set to 3306 (default MySQL port)
`<username>` is set to the proper username with the required access:
GRANT ALL ON gerbera.* TO 'username'@'localhost' IDENTIFIED BY 'password';

Tried to start the gerbera service with the database but no tables
Tried to start gerbera witht the table structure taken from /usr/share/gerbera/mysql.sql
Tried to start gerbera witht the table structure taken from https://github.com/gerbera/gerbera/blob/master/config/mysql.sql

In each case, the service will not start and I cannot locate any useful log saying why.

Is there something missing in the documentation or am I doing something wrong?

**Comment by nrietsch** [comment]
Update...

When running the following:
gerbera -c /etc/gerbera/config.xml

I'm getting this:
 ERROR: You enabled MySQL storage in configuration, however this version of Gerbera was compiled without MySQL support!

gerbera --version
Gerbera UPnP Server version 1.1.0 - http://gerbera.io/

===============================================================================
Gerbera is free software, covered by the GNU General Public License version 2

Copyright 2016-2017 Gerbera Contributors.
Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
===============================================================================
Compile info:
-------------
WITH_MAGIC=1
WITH_MYSQL=0
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=0
WITH_TAGLIB=1
WITH_AVCODEC=0
WITH_FFMPEGTHUMBNAILER=0
WITH_EXIF=1
WITH_EXIV2=0
WITH_PROTOCOL_EXTENSIONS=1
WITH_LASTFM=0
WITH_LOGGING=
WITH_DEBUG_LOGGING=

**Comment by elmodaddyb** [comment]
Hello @nrietsch - Unfortunate news.  It looks like the runtime version of Gerbera is compiled **without mysql** via `WITH_MYSQL=0`.

Can you help me to understand how you installed Gerbera runtime?  Was it from a package manager?

**Comment by nrietsch** [comment]
I ran `add-apt-repository -y ppa:stephenczetty/gerbera`, followed by `apt-get update` and finally `apt-get install -y gerbera`

That's it....

**Comment by v00d00** [comment]
If the PPA doesnt provide MySQL in their build, there is not much we can do Im afraid.

Its likely MySQL support will be dropped in the future anyway, as SQLite works well and is less complex.

You could contact @stephen-czetty as he is the PPA guy.
