### ISSUE TITLE
Blank UI

### ISSUE THREAD

**Issue by michalpu143** [gerbera/gerbera#3180]
When opening UI of Gerbera, I just see upper panel and introductory text, nothing else. Clicking on login returns 404. Here is a screenshot

![image](https://github.com/user-attachments/assets/34bc0324-1f32-48e8-930e-3e886d139f2f)

Here is journal of Gerbera service

![image](https://github.com/user-attachments/assets/4f9db8b8-e20a-4688-8ee6-d1432fed5200)

I am using the automatically generated config, with var/lib/gerbera as folder for DB and enp6s0 as network interface.

Server:
 - OS: Kubuntu:24.04
 - Gerbera Version: 2.0.0
 - Source: apt

**Comment by KarlStraussberger** [comment]
So the problem may have been the missing access to the disk for the gerbera user.

**Comment by KarlStraussberger** [comment]
I am quite sure it would have worked without adding autoscan directories but it pointed you the correct way. The problem may be in the initial way the gerbera user was created on your system. Which is hard to find out afterwards.
