### ISSUE TITLE
Bi-directional checks of database integrity

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3188]
I wrote on September 8th, 2023:

> I am convinced that whatever system, in general, a database cleanup is most useful. Especially when you have easy access to all files in said physical directory. Matching physical entries with virtual entries, and vice versa virtual entries with physical entries. 

We are not there, yet. 
Incidentally, I hit this topic again, with the minimal test install from #3138.
Some 10 minutes after `cp`-ing a single additional file into the Autoscan directory, gerbera bailed out. It had fallen over the Jamaïque_6_8... . (Let's for the time forget, why.)

What is going on since then, and to be followed easily due to the basic install with minimal files, is that the `Jamaïque_6_8...` is not listed any more in the database, while it is still available in the `Autoscan` directory. Any way of restarting gerbera or whatnot has not achieved to bring it back into the Database view. 
This is precisely what I had in mind in my posting from last year. Here we deal with some 8 or 9 files, where it becomes obvious that `Database` view does not reflect the physical folder; and is seemingly unable to update itself. Of course, a fresh complete `Autoscan` (as I learned with removing the PC directory) would sort the problem. But with thousands of files in hundreds of folders, a user will never know, if all files are actually listed in the Database. 
Therefore this RFE: To be able to check the integrity in **both** directions. 

I have restarted gerbera, and made a screenshot of the `File System` view, as well as the `Database` view. The `Jamaïque_5_8..` IS missing; to be remembered it was the example file that I had `rm`-ed to see if the removal had been noticed, and reflected in the Database view. But the `Jamaïque_6_8...` is happily lying around in the test_dir directory:

_Originally posted by @udippel in https://github.com/gerbera/gerbera/discussions/2864#discussioncomment-6952529_

![image](https://github.com/user-attachments/assets/217878ec-4490-47a8-b3c7-2651311db80a)
![image](https://github.com/user-attachments/assets/9c29adb7-68dc-4ea2-b265-e09cdf5e3f64)

For completeness:
```
$ ls -l test_dir/J* 
-rw-rw-r-- 1 mine mine 67595580 Jul 24 20:07 test_dir/Jamaïque_1_8_1494-1920.mp3
-rw-rw-r-- 1 mine mine 69793109 Jul 24 20:13 test_dir/Jamaïque_2_8_1930-1940.mp3
-rw-rw-r-- 1 mine mine 68204478 Jul 24 20:17 test_dir/Jamaïque_3_8_1940-1950.mp3
-rw-rw-r-- 1 mine mine 58516823 Jul 25 08:48 test_dir/Jamaïque_4_8_1950-1954.mp3
-rw-rw-r-- 1 mine mine 60968539 Jul 25 13:12 test_dir/Jamaïque_6_8_1957-1960.mp3
-rw-rw-r-- 1 mine mine 66184533 Jul 25 13:07 test_dir/Jamaïque_7_8_1960-1965.mp3
-rw-rw-r-- 1 mine mine 68086216 Jul 25 13:01 test_dir/Jamaïque_8_8_1965-1970.mp3
```

**Comment by KarlStraussberger** [comment]
If you are referring to the virtual layout, this cannot be done because the user has the option to remove single items manually via Web UI. I am quite sure if we do recreate an item automatically that would not be an expected behaviour.

For me it is a normal process that you restart import from scratch if there was an issue in the first run. The fastest way to fix your discrepancy is to remove the item from PC directory tree and re-start or go to the filesystem view and add the item manually.

**Comment by udippel** [comment]
I talk about physical layout. The physical file is there, you can see it in the `File System`view (see above). The user can expect it to show up in the virtual layout (`Database`), because of the Autoscan of that directory. At least as long as it hasn't been excluded by the user via web interface ('`Delete item`').

It wasn't the first run, rather no. 5 or 8, when a file was added physically by `cp` at 17:45. Some minutes later, around 17:52, another file got 'lost', for whatever reason (I attach the normal log of the failed process). 
Without visual comparison (of hundreds or thousands of files or folders) the user would never become aware that at least one file that was accessible in the Database view or via a DNLA client earlier, has disappeared without user's intent. That surely is not expected behaviour. 

Of course, if a user **knew** about an issue, he could always start from scratch. But: How would he know about an issue?? (Except by seeing the obvious, due to less than a dozen items in this specific test install.)
 
Of course it is open to discussion, if this replenishment of the database should be done automatically; or if it was better to inform the user about discrepancies. 
At least, there ought to be a method to identify such discrepancies beyond visual inspection.
[failing_Jama.log](https://github.com/user-attachments/files/16648133/failing_Jama.log)

**Comment by udippel** [comment]
Let's reformulate this completely: Since there is a (physical) file called Jamaïque_6_8_1957-1960.mp3 in the Autoscan directory, that is however not visible in the Database view, why would gerbera not pick this file up and add it to the database items in the Autoscan folder test_dir?
I have asked debug to show me all occurrences of Jamaïque_6_8_1957-1960.mp3 after a gerbera start, within the first few minutes of activity.
Please find the output attached.
[why_no_pickup.log](https://github.com/user-attachments/files/16649901/why_no_pickup.log)

**Comment by KarlStraussberger** [comment]
The synchronisation between physics and "PC Directory" takes at each restart of gerbera. For this to work your database has to be consistent. Obviously, your failing import broke it. 

Please try to provide reproduction steps as required in the bug report template.

**Comment by udippel** [comment]
If it DOES take place at each restart, and vice versa, that is checking that files in the database still exist physically,and in this case it was only hampered by a (not yet) explained corruption of the database, this case is of course closed. 
Thanks or the explanation!
