### ISSUE TITLE
Gerbera's UI is disabled. If you did not expect this, please check your configuration.

### ISSUE THREAD

**Issue by gabriellluz** [gerbera/gerbera#319]
Hi, the error below persists when accessing the Web interface:
**Gerbera's UI is disabled. If you did not expect this, please check your configuration.**

OS: Ubuntu 18.04, 64-bit

Here's my config file (only the UI part):
```
<?xml version="1.0" encoding="UTF-8"?>
<config version="2" xmlns="http://mediatomb.cc/config/2" xmlns:xsi="http://www.w3.org/2$
  <!--
     See http://gerbera.io or read the docs for more
     information on creating and using config.xml configuration files.
    -->
  <server>
    <ui enabled="yes" show-tooltips="yes">
      <accounts enabled="yes" session-timeout="30">
        <account user="gerbera" password="gerbera"/>
      </accounts>
    </ui>
    <name>gerbera</name>
    <udn>uuid:d28779e5-eda4-4453-9f2f-afcac1f97311</udn>
    <home>/home/gaia/.config/gerbera</home>
    <webroot>/usr/share/gerbera/web</webroot>
```
**I've tried disabling and re-enabling the UI and restarting services but it won't work.**
Also, my Gerbera installation is using the same Config file as above.

**Comment by elmodaddyb** [comment]
Indeed that is strange.  Let me look at the code to see if there is some odd behavior there.

**Comment by elmodaddyb** [comment]
It looks like the page you are landing on is the the `disabled.html`.  The bookmark generation code will output the `disabled.html` link when it see the UI is disabled.  Also if the server returns a **900** which is produced by directly reading the `/server/ui[enabled]` XML.

[https://github.com/gerbera/gerbera/blob/master/src/config_manager.cc#L1450](https://github.com/gerbera/gerbera/blob/master/src/config_manager.cc#L1450)

Can you confirm the contents of the bookmark file?
`/home/gaia/.config/gerbera/gerbera.html`

That may help confirm the code is reading the config.xml properly.

**Comment by elmodaddyb** [comment]
I ran a Ubuntu Bionic 18.04 VM, built gerbera 1.3.0alpha from source and it worked OK with clean config.xml.

Can you help in what version of Gerbera is running

```
$ gerbera --version
```

**Comment by gabriellluz** [comment]
Hi there.
gerbera --version
                                                                                                                                                                            
```
Gerbera UPnP Server version 1.1.0 - http://gerbera.io/                                                                                                                      
                                                                                                                                                                            
===============================================================================                                                                                             
Gerbera is free software, covered by the GNU General Public License version 2                                                                                               

Copyright 2016-2017 Gerbera Contributors.
Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
===============================================================================
Compile info:
-------------
WITH_MAGIC=1
WITH_MYSQL=1
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=1
WITH_TAGLIB=1
WITH_AVCODEC=1
WITH_FFMPEGTHUMBNAILER=1
WITH_EXIF=1
WITH_EXIV2=1
WITH_PROTOCOL_EXTENSIONS=1
WITH_LASTFM=0
WITH_LOGGING=
WITH_DEBUG_LOGGING=

```

**Comment by gabriellluz** [comment]
HI there.
I hit `sudo nano  /home/gaia/.config/gerbera/gerbera.html`
The file is empty.

**Comment by elmodaddyb** [comment]
Thanks for the additional details. I will build 1.1.0 from a tag and see what behavior I get with bionic.

**Comment by elmodaddyb** [comment]
@gabriellluz - I built 1.1.0 from source and running in Bionic Beaver it worked OK. Enabled/Disabled UI and it worked as expected.

> Can you confirm the permissions for the `config.xml` file and the user which is running the `gerbera` process?

```
-rw-r--r-- 1 gerbera gerbera 6375 Jun 27 07:16 config.xml
```

Did you compile 1.1 from source or download from package manager?

**Comment by gabriellluz** [comment]
Hi there. I've downloaded from a package manager called Synaptic.
I'm a linux newbie so I can install some things but I still don't know how to uninstall them without a package manager. I'm still learning.

**Comment by tjme** [comment]
FWIW: I initially had similar problems with a similar setup (Gerbera 1.1.0 on Kubuntu 18.04), but it is in fact now working well. After making a few corrections to the gerbera.service file, I was surprised the web interface was still reporting the UI as disabled, even when I refreshed the page. It was not until I deleted the /disabled.html from the end of the URL that it correctly displayed a working web UI. Perhaps you are making a similar mistake?

**Comment by abourget** [comment]
I'm using the default Ubuntu install, and it fails with this message. Unclear what to tweak to enable it back.

**Comment by elmodaddyb** [comment]
I will try to install via the PPA with Bionic Beaver.  I previously tried to build new `deb` packages from scratch to get a later build available.  however this ended in SEG FAULTS galore.

I may have time this weekend to troubleshoot further.

**Comment by mervynj** [comment]
I have the same problem as OP. Same method of installation and same error.
I tried deleting the disabled.html file as suggested by tjme but Gerbera just brought up a Error 404.
I await the answer one. Thanks

**Comment by elmodaddyb** [comment]
I built a fresh VM of Ubuntu 18.04...then installed gerbera
```
$ sudo apt install gerbera
```

This installed the `v1.1.0` version of Gerbera....and then visited the site:

```
http://<ip>:49152
```

Received the `Gerbera's UI is disabled...`

### Solution

Modify the file `/etc/gerbera/config.xml`  set the 

```xml
<ui enabled="yes"...
```

### Restart Gerbera

```
$ systemctl stop gerbera
$ systemctl start gerbera
```

**Comment by mervynj** [comment]
Thank you elmodaddyb, I tried this last night and it didn't work, but tonight it does. I must have done something wrong. Anyway, it is working for me. Thanks

**Comment by klaus7** [comment]
I experienced the same problem. It had something to do with the browser cache. After adapting the config file I had to clear the cache. Then I finally could start the web UI.

**Comment by klaus7** [comment]
Ok, one thing to keep in mind on Ubuntu and thanks to @tjme for the hint with the service file: The config file used is not under `~/.config/gerbera/config.xml` but under `/etc/gerbera/config.xml` as can be seen in `/etc/systemd/system/multi-user.target.wants/gerbera.service`

**Comment by Martii** [comment]
@elmodaddyb 

Re: https://github.com/gerbera/gerbera/issues/319#issuecomment-408567052

Had to do this on my my Bionic test server. Although I don't recall ever loading the system service... just using the PPA. I have been, since April, launching gerbera manually from the command line and a few weeks back is when I installed a platform with Ubuntu. Anyhow that seems to have solved the UI failing in the last few days. So a belated thank you even though I'm wondering how the system service was initialized and activated by itself. :)

**Comment by gabriellluz** [comment]
That problem is not happening anymore.

**Comment by gabriellluz** [comment]
Can I close it?

**Comment by gabriellluz** [comment]
I've fixed it by updating it to the latest version.
