### ISSUE TITLE
Remove "error: Failed to read" from standard log at inotify

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3195]
When deleting a file from outside of the gerbera Web interface with some system call, rm, this massage pops up in the standard log. 
Since this log is a nice  indication of proper function, it would be a pity to clutter it with dangerously-sounding error messages. 
We don't inform about additions to a folder in autoscan at all (IMHO correctly), we should likewise accept the removal of a file from some autoscan directory with the same grace.

This is what inotify is for. An action taken correctly, and initiated by inotify, is no error.

**Comment by KarlStraussberger** [comment]
Can you please provide a proper bug report with the full message and the actions taken, so it's possible to reproduce.

**Comment by udippel** [comment]
Thought it was obvious. Sorry.
Running about the most recent ...40 ... .
rm a file in the autoscan directory. It properly disappears from gerbera, everything okay.
The standard log comes up with a line per file deleted, with the message in the title written in quotes, followed by the directory and filename, where the initial of the filename is substituted by a dot. 
If you rm 35 files, the log shows 35 error messages like the one described.
It's not real bug, but AFAIAC, it can be misleading and could be dropped.

**Comment by cweiske** [comment]
The log messages from adding and removing the "test" directory are ("info: import" is from my own import script, the error is from gerbera):
```
2024-09-06 08:43:18   info: import: /data/media/Music/test/Taylor Swift - Midnights - 03 - Anti‐Hero.ogg
2024-09-06 08:43:28  error: Failed to read /data/media/Music/test: No such file or directory
```

**Comment by KarlStraussberger** [comment]
In #3209 , I updated the error message to identify the place where it is created. It should only appear if an existing file was accessed. Let's see the full reason of the message to hide it in the correct situation.

**Comment by cweiske** [comment]
I `rm -r`'d a folder and gerbera v2.2.0-52-g26ad170f logs: 
```
2024-09-12 20:05:33  error: Failed to read /data/media/Music/test/Best Of - CD 1 for event None: No such file or directory
```

**Comment by KarlStraussberger** [comment]
The event `None` is the beast. Seems that some extra events get passed through.

**Comment by udippel** [comment]
Maybe I'm too fast, but 2.2.0-58-g2bf44f1d still throws a
`error: Failed to read /myhome/mydir/.ophia-Loren---Portrat-einer-Diva2024-09-02.ts.removing for event MOVED_TO: No such file or directory`
I'm writing in, because before it looked slightly different: `... removing: No such file or directory`. The event wasn't indicated.
The function is still perfectly okay: the file disappeared from view immediately.

**Comment by KarlStraussberger** [comment]
You're too fast, but the message says you've moved the file and that's not covered by the fix anyway. What kind of command are you running.

**Comment by udippel** [comment]
You're right. In this case, it wasn't `'rm`'-ed, but sent to nirwana by "`Remove`" in `tvheadend`. And actually it IS gone for good. I don't know which command precisely `tvheadend` implements. 
Any file that I `rm` manually now behaves properly: it doesn't produce any more error.

**Comment by udippel** [comment]
Here is what I'd consider as explanation:
https://tvheadend.org/d/8820-remove-is-implemented-how
tvheadend seems to `rename` followed by `delete`. 

The result isn't perfect, but the problem doesn't lie with gerbera, and I can live easily with a log warning for only the files coming from tvheadend.
