### ISSUE TITLE
Using import mode "grb", Gerbera does not import nor create thumbnails for images

### ISSUE THREAD

**Issue by EricdeWaal** [gerbera/gerbera#3196]
Since version 2, Gerbera does not import (99%) of my images. Only 2 out of 24 directories are shown.
"systemctl status gerbera" during import shows errors like:
"Aug 24 13:42:03 nas.local gerbera[23178]: 2024-08-24 13:42:03 warning: Failed to generate resource for thumbnail: /data/Foto/2011Zermatt/Zermatt_3096.jpg [./src/config/config_manager.cc:497] virtual IntOptionType ConfigManager::getIntOption(ConfigVal) const Error: opt>"

For import mode "mt" it still works, but with the same kind of erors.

**Server (please complete the following information):**
 - OS: Debian Linux 12
 - Gerbera Version: 2.2.0
 - Source: deb multimedia

Relevant part of my config:
```
  <import hidden-files="no" import-mode="mt">
    <magic-file></magic-file>
    <autoscan use-inotify="yes" inotify-attrib="yes">
     <directory location="/data/Muziek" mode="inotify" recursive="yes" hidden-files="no" media-type="Aidio|Music|AudioBook"/>
     <directory location="/data/Film" mode="inotify" recursive="yes" hidden-files="no" media-type="Video|Movie|MusicVideo"/>
     <directory location="/data/Foto" mode="inotify" recursive="yes" hidden-files="no" media-type="Image|Photo"/>
   </autoscan>
   <scripting script-charset="UTF-8">
      <script-folder>
        <common>/usr/share/gerbera/js</common>
      </script-folder>
      <import-function>
        <playlist>importPlaylist</playlist>
        <meta-file>importMetadata</meta-file>
        <audio-file>importAudioStructured</audio-file>
        <video-file>importVideo</video-file>
        <image-file>importImage</image-file>
        <trailer>importTrailer</trailer>
      </import-function>
      <virtual-layout type="js" audio-layout="Structured">
        <boxlayout>
          <box key="Audio/allAlbums" title="Albums" class="object.container" />
          <box key="Audio/allArtists" title="Artists" class="object.container" />
          <box key="Audio/allAudio" title="All Audio" class="object.container" />
          <box key="Audio/allComposers" title="Composers" class="object.container" />
          <box key="Audio/allDirectories" title="Directories" class="object.container" />
          <box key="Audio/allGenres" title="Genres" class="object.container" />
          <box key="Audio/allSongs" title="All Songs" class="object.container" />
          <box key="Audio/allTracks" title="All - full name" class="object.container" />
          <box key="Audio/allYears" title="Year" class="object.container" />
          <box key="Audio/audioRoot" title="Audio" class="object.container" />
          <box key="Audio/artistChronology" title="Album Chronology" class="object.container" />
          <box key="AudioInitial/abc" title="ABC" class="object.container" />
          <box key="AudioInitial/allArtistTracks" title="000 All" class="object.container" />
          <box key="AudioInitial/allBooks" title="Books" class="object.container" />
          <box key="AudioInitial/audioBookRoot" title="AudioBooks" class="object.container" />
          <box key="AudioStructured/allAlbums" title="-Album-" class="object.container" size="26" />
          <box key="AudioStructured/allArtistTracks" title="all" class="object.container" />
          <box key="AudioStructured/allArtists" title="-Artist-" class="object.container" size="7" />
          <box key="AudioStructured/allGenres" title="-Genre-" class="object.container" size="6" />
          <box key="AudioStructured/allTracks" title="-Track-" class="object.container" size="26" />
          <box key="AudioStructured/allYears" title="-Year-" class="object.container" />
          <box key="Video/allDates" title="Date" class="object.container" />
          <box key="Video/allDirectories" title="Directories" class="object.container" />
          <box key="Video/allVideo" title="All Video" class="object.container" />
          <box key="Video/allYears" title="Year" class="object.container" />
          <box key="Video/unknown" title="Unknown" class="object.container" />
          <box key="Video/videoRoot" title="Video" class="object.container" />
          <box key="Image/allDates" title="Date" class="object.container" />
          <box key="Image/allDirectories" title="Directories" class="object.container" />
          <box key="Image/allImages" title="All Photos" class="object.container" />
          <box key="Image/allYears" title="Year" class="object.container" />
          <box key="Image/imageRoot" title="Photos" class="object.container" />
          <box key="Image/unknown" title="Unknown" class="object.container" />
          <box enabled="false" key="Trailer/trailerRoot" title="Online Services" class="object.container" />
          <box enabled="false" key="Trailer/appleTrailers" title="Apple Trailers" class="object.container" />
          <box enabled="false" key="Trailer/allTrailers" title="All Trailers" class="object.container" />
          <box enabled="false" key="Trailer/allGenres" title="Genres" class="object.container" />
          <box enabled="false" key="Trailer/relDate" title="Release Date" class="object.container" />
          <box enabled="false" key="Trailer/postDate" title="Post Date" class="object.container" />
          <box enabled="false" key="Trailer/unknown" title="Unknown" class="object.container" />
          <box key="Playlist/playlistRoot" title="Playlists" class="object.container" />
          <box key="Playlist/allPlaylists" title="All Playlists" class="object.container" />
          <box key="Playlist/allDirectories" title="Directories" class="object.container" />
        </boxlayout>
    </virtual-layout>
    </scripting>
```

**Comment by EricdeWaal** [comment]
And with import-mode "mt", no thumbs are shown in the web-gui or output for video. Although they are still there (from the previous "grb" import) in directory /var/lib/gerbera/cache-dir/data/Film

**Comment by KarlStraussberger** [comment]
As far as I remember deb multimedia messed up with their build. Can you post the output of `gerbera --compile-info`

**Comment by EricdeWaal** [comment]
Hi,

compile-info shows:

Gerbera UPnP Server 2.2.0
Copyright 2016-2024 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_NPUPNP=1
WITH_MAGIC=ON
WITH_MYSQL=1
WITH_CURL=ON
WITH_INOTIFY=ON
WITH_JS=ON
WITH_TAGLIB=1
WITH_AVCODEC=OFF
WITH_FFMPEGTHUMBNAILER=1
WITH_EXIF=ON
WITH_EXIV2=1
WITH_MATROSKA=ON
WITH_WAVPACK=OFF
WITH_SYSTEMD=ON
WITH_LASTFM=OFF
WITH_DEBUG=ON
WITH_DEBUG_OPTIONS=ON
WITH_TESTS=OFF

I cannot find a .deb package on Github like you had for 2.1.0: https://github.com/gerbera/gerbera/releases/tag/v2.1.0
Is this correct?

And as said, I have `<home>/var/lib/gerbera</home>` in my config. Is this correct if Gerbera runs as a daemon, at rhe start of the system?

**Comment by KarlStraussberger** [comment]
I remembered correctly, the problem is `WITH_AVCODEC=OFF`.

We've got a new repo https://docs.gerbera.io/en/stable/install.html#debian

Changing repos may trigger other issues https://docs.gerbera.io/en/stable/troubleshooting.html#installation

**Comment by EricdeWaal** [comment]
Hi, it seems like the repo you mention here:
"We've got a new repo https://docs.gerbera.io/en/stable/install.html#debian"
does not exist (404 error)!

**Comment by marillat** [comment]
@KarlStraussberger  By default  WITH_AVCODEC is set to OFF
https://github.com/gerbera/gerbera/blob/v2.2.0/CMakeLists.txt#L35C1-L35C79

AVCODEC need to be changed to ON by default ?

**Comment by KarlStraussberger** [comment]
@marillat yes. It's good for metadata and thumbnails.

**Comment by marillat** [comment]
A PR is needed ? :)

**Comment by KarlStraussberger** [comment]
@marillat You may even consider using our CMakePresets. Avoids missing out options, risks failing builds due to missing libraries.

**Comment by KarlStraussberger** [comment]
> A PR is needed ? :)

Where?

**Comment by marillat** [comment]
> @marillat You may even consider using our CMakePresets. Avoids missing out options, risks failing builds due to missing libraries.



> > A PR is needed ? :)
> 
> Where?

To enable ffmpeg support by default ?

**Comment by KarlStraussberger** [comment]
You need to do that in your setup to add ffmpeg dependency.

**Comment by marillat** [comment]
Yes, but ffmpeg is disabled in the `CMakeLists.txt` file. So I can add what I want, ffmpeg is still not working.

**Comment by KarlStraussberger** [comment]
Both are off by default. You are setting only one. The bug, if any, is that you can do that without a warning.

**Comment by marillat** [comment]
@KarlStraussberger In my packages now both are set to ON

**Comment by KarlStraussberger** [comment]
Some dependency issue with ffmpeg?

**Comment by KarlStraussberger** [comment]
https://github.com/gerbera/gerbera/blob/master/scripts%2Fdebian%2Fbuild-deb.sh

**Comment by marillat** [comment]
> Some dependency issue with ffmpeg?
This work for me.
If options are set to ON find_package is called with REQUIRED so you can't miss a dependency

**Comment by EricdeWaal** [comment]
@marillat does this mean that the packages on your (deb-multimedia.org](http://www.deb-multimedia.org/dists/stable-backports/main/binary-amd64/package/gerbera, Build-Date: 25 August 2024) should work now?

@KarlStraussberger do you still intend to set your own repo on https://pkg.gerbera.io/, as mentioned in the documentation?
Now there is nothing.

**Comment by marillat** [comment]
@EricdeWaal yes, package version 1:2.2.0-dmo4 and 1:2.2.0-dmo0~bpo12+2

https://pkg.gerbera.io/ return a 404

**Comment by KarlStraussberger** [comment]
> @EricdeWaal yes, package version 1:2.2.0-dmo4 and 1:2.2.0-dmo0~bpo12+2
> 
> https://pkg.gerbera.io/ return a 404

It is there, you just have to add it, like the doc says. The landing page is still in progress.

**Comment by EricdeWaal** [comment]
I can confirm that installing from the https://pkg.gerbera.io/ actually works, and that this version also correctly handles thumbnsails for images and video.
Thanks @KarlStraussberger and @marillat !
