### ISSUE TITLE
Gerbera 2.2 does not remove deleted files until restart

### ISSUE THREAD

**Issue by satarsa** [gerbera/gerbera#3199]
I am sorry if this issue has been reported already.
**Describe the bug**
I have an imported directory which is auto-scanned via INotify.  If I put a new video file there, it appears in both gerbera-2.1 and 2.2 immediately, no issues there, but if I delete the file, it is removed from the list only by gerbera-2.1, but gerbera-2.2 still shows it in the list until it is restarted.

**To Reproduce**
0. Copy a new video file into an auto-scanned directory.
1. Delete it.

**Expected behavior**
Gerbera 2.1 shows the file in the list after creation and removes it after deleting.
Gerbera 2.2 shows the file in the list after creation but keeps it after deleting until the program is restarted.

**Server (please complete the following information):**
 - OS: Gentoo
 - Gerbera Version: 2.2

**Media client (please complete the following / remove not applicable:**
 - Device: Independent on the device, only the version matters

**Comment by KarlStraussberger** [comment]
It's fixed already.
#3192
