### ISSUE TITLE
Warn user if `udn` is unset

### ISSUE THREAD

**Issue by jerome-pouiller** [gerbera/gerbera#3200]
I have noticed Gerbera (probably I should say `libupnp`) does not send SSDP notifications if `udn` value in unset (eg `<udn/>`) in `config.xml`. Maybe it would make sense to detect the issue and display a warning on start?

**Comment by jerome-pouiller** [comment]
FYI, #2891 describes the issue the user can encounter.

**Comment by jerome-pouiller** [comment]
I copied the configuration from `/usr/share/doc/gerbera/examples/config.xml`... Probably I am not the only one to do that :-/

**Comment by KarlStraussberger** [comment]
So the problem is in the way the package maintainer builds it for the distro. Because there is no such file in gerbera source. Which means, that in addition to the change in settings we should include some words in the troubleshooting page.
