### ISSUE TITLE
New files in autoscandir not added: Failed to iterate /dir, Permission denied

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3202]
**Describe the bug**
I ripped a CD on my PC and copied the album directory on the NFS share I mounted from my home server. The home server runs gerbera, and it failed to pick up the new files.

Log entries:
```
2024-09-05 07:32:54  error: Failed to iterate /data/media/Music/Alben/Taylor Swift/The Tortured Poets Department, Permission denied
2024-09-05 07:32:54 warning: Cannot add inotify watch for /data/media/Music/Alben/Taylor Swift/The Tortured Poets Department: Permission denied
2024-09-05 07:32:54 warning: Cannot add inotify watch for /data/media/Music/Alben/Taylor Swift/The Tortured Poets Department: Permission denied
```

It seems the problem from #3090 and #3092 is back :(.

**To Reproduce**

0. Relevant config: import-mode=grb, autoscan directory mode=inotify, recursive=yes
1. Start gerbera
2. Copy multiple files with Gnome files application to the NFS share
3. See error in log

**Expected behavior**
Files get imported properly.

**Server (please complete the following information):**
 - OS: Debian 12
 - Gerbera Version: v2.2.0-git+f779dfa5
 - Source: self built

**Additional context**
I tested it with a directory with a single file in it, copying it with `cp -a` to the NFS share - the error did not appear.

When copying a directory with 8 files in it, the error appeared. So it seems to be a timing problem - when `cp -a` sets the permissions of the directory (see [my cp-a comment](https://github.com/gerbera/gerbera/issues/3090#issuecomment-2122592240)) quickly enough, gerbera does not show the problem.
When network transfer is slow enough, the problem appears.

**Comment by KarlStraussberger** [comment]
There is not much we can do about that. You may try the `retry-count` to get the files imported but we have to rely on the system to send the signal at the right point in time. It does send it as soon as the file is created, because it does not know that our process has not sufficient permissions to read it immediately after creation. In fact, I'm using a sticky bit on the folder, seems to set the permission right away.

**Comment by cweiske** [comment]
Neither using `chmod +s` (setuid) nor `chmod +t` (sticky) on the parent folder where I copy the new album folders into solve the problem here.

**Comment by KarlStraussberger** [comment]
It's hard to come by this kind of issue. Everything is working as expected but we are too fast.
- You are dropping the file
- The system creates the inotify event
- We are checking the file and get permission denied
- The permissions are changed
- are you are not using the option `<autoscan inotify-attrib="yes">` we do not get that information

**Comment by cweiske** [comment]
I did not know (or forgot) about inotify-attrib. If the solution is so easy I'll enable it.

**Comment by cweiske** [comment]
It works! Thank you!
