### ISSUE TITLE
config: `<profiles allow-unused="yes">` does not work

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3207]
**Describe the bug**
I have `<profiles allow-unused="yes">` in my configuration and two profiles. One is marked as `enabled="no"` and is not referenced by a `mimetype-profile-mappings`.

When starting gerbera I get:
```
Sep 06 17:40:02 dojo gerbera[2926081]: 2024-09-06 17:40:02  error: Error in configuration: you specified a mimetype to transcoding profile mapping, but no match for profile "audio2pcm" exists
Sep 06 17:40:02 dojo gerbera[2926081]: 2024-09-06 17:40:02  error: [/usr/local/src/gerbera/gerbera-git/src/config/setup/config_setup_transcoding.cc:554] std::shared_ptr<ConfigOption> ConfigTranscodingSetup::newOption(const pugi::xml_node&) Error: Init /transcoding transcoding failed 'transcoding'
```

When I comment out the ununsed profile gerbera starts normal.

**To Reproduce**

0. Have a config with a transcoding profile that is not referenced by a mimetype-profile-mappings/transcode
1. Start gerbera
2. See error

**Expected behavior**
I do not have to comment out profiles if I don't use them.

**Server (please complete the following information):**
 - OS: Debian 12
 - Gerbera Version: v2.2.0-46-gc7c93474
 - Source: self built

**Additional context**
Documentation: https://docs.gerbera.io/en/stable/config-transcode.html#profiles

**Comment by KarlStraussberger** [comment]
There is also a setting "allow-unused" for `mimetype-profile-mappings`

https://docs.gerbera.io/en/stable/config-transcode.html#mimetype-profile-mappings

**Comment by KarlStraussberger** [comment]
Can you try #3208 found some strange logic in the code.

**Comment by cweiske** [comment]
#3208 fixes the problem. I now get a warning instead of an error:
> 2024-09-08 11:28:03 warning: You specified a mimetype to transcoding profile mapping, but no match for profile "audio2pcm" exists

----

I don't know what `<mimetype-profile-mappings allow-unused="yes">` would actually mean.
An unused `<profile>` is a profile that has no entry in `<mimetype-profile-mappings>`, but what is an unused mimetype-profile-mapping?

**Comment by KarlStraussberger** [comment]
This is the copy and paste pattern of software development. The code was already there and nobody thought about a better name like `allow-mapping-to-be-invalid`. Will at least give the documentation some improvement.

**Comment by cweiske** [comment]
Thank you!
