### ISSUE TITLE
Crash on UPnP search with unclosed string

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3211]
**Describe the bug**
When doing a UPnP search request with an unclosed string, gerbera crashes:
```
upnp:class = "object.container.album.musicAlbum" and upnp:lastPlaybackTime > "2024-09-01
```

(Closing double quote is missing)

(I tried to find out how to build a [container](https://docs.gerbera.io/en/stable/config-server.html#containers) that shows the last played albums).

**To Reproduce**

1. Start gerbera on server
2. Start `gupnp-av-cp` on desktop PC
3. Right-click gerbera server, select "search"
4. Input `upnp:class = "object.container.album.musicAlbum" and upnp:lastPlaybackTime > "2024-09-01` and press return
5. Gerbera crashes with `Main process exited, code=killed, status=11/SEGV`

**Expected behavior**
No crash

**Server (please complete the following information):**
 - OS: Debian 12
 - Gerbera Version: v2.2.0-52-g26ad170f
 - Source: self built

**Comment by KarlStraussberger** [comment]
> For the 'fun' of it: alas confirmed with ...50... .

You can even try 1.1 and will find it there as well!

**Comment by udippel** [comment]
I didn't try to be funny, neither cynic. Some 15 years ago, I used to be quite active in sanitization of user input. It has and will probably remain a step-child, because it doesn't actually 'sell'. It serves no new functionalities, and the user gains seemingly nothing from it. Only, when it is (not) too late. 
Haven't been active for the last 12 years, I wonder if by now some libraries exist, through which one can run user input, to throw away generically wrong input? Escapes, odd numbers of quotes, silly SQL commands, and so forth.

**Comment by cweiske** [comment]
Gerbera does not crash anymore, it logs a warning now:
```
2024-09-13 09:11:52 warning: [/usr/local/src/gerbera/gerbera-git/src/database/search_handler.cc:339] std::unique_ptr<ASTQuotedString> SearchParser::parseQuotedString() Error: Failed to parse search criteria - expecting a double-quote
```

**Comment by KarlStraussberger** [comment]
That's intended. Thank you

**Comment by udippel** [comment]
8 out of 10, I'd say. The client says: 
![image](https://github.com/user-attachments/assets/7c7a2f32-d2c1-4abd-9815-965a1b77a5eb)
The user is barely the wiser. Question: How difficult would it be to push the error text to the user, and giving out 
![image](https://github.com/user-attachments/assets/d8e33dd4-07ae-4398-a045-c70101566c91)
instead?

**Comment by KarlStraussberger** [comment]
> 8 out of 10, I'd say. The client says: ![image](https://private-user-images.githubusercontent.com/50265752/367256263-7c7a2f32-d2c1-4abd-9815-965a1b77a5eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjU2NzAsIm5iZiI6MTcyNjIyNTM3MCwicGF0aCI6Ii81MDI2NTc1Mi8zNjcyNTYyNjMtN2M3YTJmMzItZDJjMS00YWJkLTk4MTUtOTY1YTFiNzdhNWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExMDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzM2E5M2ZhNDZjMGVjZDlhZGE2YzMxZjgxNTNjMjA2MzFmNmE4YWU0N2U0NzAyM2FjMjNmMDRlM2JjNWM0OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lK1pv3B00T_PIaGUnL1MTSrMbuotf-jt-5bp2f4SawU) The user is barely the wiser. Question: How difficult would it be to push the error text to the user, and giving out ![image](https://private-user-images.githubusercontent.com/50265752/367258499-d8e33dd4-07ae-4398-a045-c70101566c91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMjU2NzAsIm5iZiI6MTcyNjIyNTM3MCwicGF0aCI6Ii81MDI2NTc1Mi8zNjcyNTg0OTktZDhlMzNkZDQtMDdhZS00Mzk4LWEwNDUtYzcwMTAxNTY2YzkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDExMDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NTRjMGQxMWFiNjk4ZTIyMjhmMGYzMmQ5MmQxMTRjODk2NjFmZjQ5MGJiM2I4NjJiYmNmODBhMjAxYmM0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3LffAuqnu-Ap3C9KqaPY5xTpev6U4xb_h8HIIaunlNA) instead?

I am already thinking of this

**Comment by cweiske** [comment]
#3221 returns the error message to the client now:
![2024-09-16 Auswahl_001](https://github.com/user-attachments/assets/d631422a-a43b-4805-9285-bf65595676d3)
