### ISSUE TITLE
Failed to execute INSERT INTO "grb_client"

### ISSUE THREAD

**Issue by berndklug1107** [gerbera/gerbera#3216]
Hi all!
gerbera.log gets massive error messages due to an "execute INSERT INTO gerb_client" in combination with fritz7530 router and ax1200 repeater (connected as cable bridge) and I have no idea how to get this fixed. maybe someone already had this problem or knows where to get more info to fix it.
Thank you

[config.txt](https://github.com/user-attachments/files/16978746/config.txt)
[gerbera.log](https://github.com/user-attachments/files/16978915/gerbera.log)

**Comment by KarlStraussberger** [comment]
As you are already using a dev build you can easily upgrade to the latest version. It fixes the IPv6 parsing error which might help here. Also you can block all fritz clients with 
```
<clients enabled="yes">
   <client userAgent="FRITZ" allowed="no"/>
    ...
</clients>
```

**Comment by berndklug1107** [comment]
thank you, upgrade was good :-)

**Comment by cweiske** [comment]
Duplicate of #3205.
