### ISSUE TITLE
Gerbera not starting: option 57 not set

### ISSUE THREAD

**Issue by lolo101** [gerbera/gerbera#3230]
**Describe the bug**
I just updated my system and Gerbera was updated to version 2.3.0

Since then Gerbera does not start

Full log: 
```
sept. 22 15:10:45 nordine systemd[1]: gerbera.service: Scheduled restart job, restart counter is at 9362.
sept. 22 15:10:45 nordine systemd[1]: Started Gerbera Media Server.
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Gerbera UPnP Server 2.3.0 - https://gerbera.io/
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Copyright 2016-2024 Gerbera Contributors.
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Gerbera is free software, covered by the GNU General Public License version 2
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Loading configuration from: /etc/gerbera/config.xml
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Parsing configuration...
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Configuration load succeeded.
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Validating configuration...
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Configuration check succeeded.
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46   info: Loading 11 configuration items from database
sept. 22 15:10:46 nordine gerbera[63608]: 2024-09-22 15:10:46  error: [/usr/src/debug/gerbera/gerbera-2.3.0/src/config/config_manager.cc:486] virtual std::string ConfigManager::getOption(ConfigVal) const Error: option 57 not set
sept. 22 15:10:46 nordine systemd[1]: gerbera.service: Main process exited, code=exited, status=1/FAILURE
sept. 22 15:10:46 nordine systemd[1]: gerbera.service: Failed with result 'exit-code'.
```
I believe the emphasis should be on "option 57" Which one is it?
When I look at file _config_val.h_ there is an enum and I believe it's the ordinal of the enum constant, right?
It's hard to identify ordinal 57 because enum constants are conditioned.
As I use sqlite3 and not mySql I believe the `HAVE_MYSQL` directive is not set.
However, `HAVE_FFMPEGTHUMBNAILER` should be set as I indeed have a `ffmpegthumbnailer` element in the configuration file.
In this case, option 57 should be `SERVER_EXTOPTS_FFMPEGTHUMBNAILER_CACHE_DIR`

Here is the relevant part in the config file:
```
      <ffmpegthumbnailer enabled="no">
        <thumbnail-size>128</thumbnail-size>
        <seek-percentage>5</seek-percentage>
        <filmstrip-overlay>yes</filmstrip-overlay>
        <workaround-bugs>no</workaround-bugs>
        <image-quality>8</image-quality>
      </ffmpegthumbnailer>
```

**To Reproduce**
just boot and see Gerbera struggling to start

**Expected behavior**
Gerbera starts without error and my media are available across the LAN

**Server (please complete the following information):**
 - OS: Arch Linux
 - Gerbera Version: 2.3.0
 - Versions of libraries: which one?
 - Source: ffmpeg? Not sure where I could find what I'm expected to insert here

**Media client (please complete the following / remove not applicable:**
 - Device: N/A
 - Client app: mostly VLC
 - Browser: N/A

**Additional context**

**Comment by KarlStraussberger** [comment]
Can you run `gerbera --compile-info`.

I suspect that your distro found a loophole of compile settings that we did not think about.

You may also try to delete the entries from `grb_config_value` table with `sqlite3` (first back it up)

**Comment by linux019** [comment]
Same problem on arch, deleted DB at first
```
Gerbera UPnP Server 2.3.0
Copyright 2016-2024 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_NPUPNP=OFF
WITH_MAGIC=ON
WITH_MYSQL=OFF
WITH_CURL=ON
WITH_INOTIFY=ON
WITH_JS=ON
WITH_TAGLIB=ON
WITH_AVCODEC=1
WITH_FFMPEGTHUMBNAILER=1
WITH_EXIF=ON
WITH_EXIV2=ON
WITH_MATROSKA=ON
WITH_WAVPACK=OFF
WITH_SYSTEMD=ON
WITH_LASTFM=OFF
WITH_DEBUG=ON
WITH_DEBUG_OPTIONS=ON
WITH_TESTS=OFF
```

gerbera --check-config gerbera.xml 
...
2024-09-22 20:29:54   info: Configuration load succeeded.
2024-09-22 20:29:54   info: Validating configuration...
2024-09-22 20:29:54   info: Configuration check succeeded.

**Comment by KarlStraussberger** [comment]
That's strange because FFMPEG (aka AVCODEC) is on as well.

I improved the log message, so that the next time we know the text of the option from config-definition.

I'd love to have a build similar to yours with the new code to make sure, we got it fixed.

**Comment by KarlStraussberger** [comment]
The issue happens after config check, which makes it even harder to detect.

**Comment by gobater** [comment]
Same here with Option 65

**Comment by gobater** [comment]
with latest git, a different error appears:

2024-09-23T09:38:30.929971+02:00 raspberrypi gerbera[7892]: 2024-09-23 09:38:30  error: [/build/src/config/config_manager.cc:487] virtual std::string ConfigManager::getOption(ConfigVal) const Error: string option 70='/server/extended-runtime-options/ffmpegthumbnailer/cache-dir' not set


Gerbera UPnP Server v2.3.0-5-gd897e096
Copyright 2016-2024 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info:
-------------
WITH_NPUPNP=OFF
WITH_MAGIC=ON
WITH_MYSQL=ON
WITH_CURL=ON
WITH_INOTIFY=ON
WITH_JS=ON
WITH_TAGLIB=ON
WITH_AVCODEC=ON
WITH_FFMPEGTHUMBNAILER=ON
WITH_EXIF=ON
WITH_EXIV2=ON
WITH_MATROSKA=ON
WITH_WAVPACK=ON
WITH_SYSTEMD=ON
WITH_LASTFM=OFF
WITH_DEBUG=ON
WITH_DEBUG_OPTIONS=ON
WITH_TESTS=OFF

Build info:
-----------
USING_PUPNP
UPNP_HAVE_TOOLS
HAVE_NL_LANGINFO
HAVE_SETLOCALE
HAVE_INOTIFY
HAVE_JS
HAVE_MYSQL
HAVE_CURL
HAVE_TAGLIB
HAVE_WAVPACK
HAVE_MAGIC
HAVE_FFMPEG
HAVE_AVSTREAM_CODECPAR
HAVE_FFMPEGTHUMBNAILER
HAVE_LIBEXIF
HAVE_EXIV2
HAVE_MATROSKA
GRBDEBUG
TOMBDEBUG

Git info:
---------
Git Branch: refs/heads/master
Git Commit: d897e09638640dcb55be4ec1a0d5f2fbeabcd2de

**Comment by gobater** [comment]
Additional Info: with the original 2.3.0 I've been able to solve the problem enabling ffmpeg thumbnailer in the configuration
Before (bug):
`<ffmpegthumbnailer enabled="no">`
After (problem solved):
`<ffmpegthumbnailer enabled="yes">`

**Comment by KarlStraussberger** [comment]
So at least half of the PR worked: we know the actual troublemaker.

**Comment by lolo101** [comment]
@KarlStraussberger 
For the record:
```
$ gerbera --compile-info

Gerbera UPnP Server 2.3.0
Copyright 2016-2024 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_NPUPNP=OFF
WITH_MAGIC=ON
WITH_MYSQL=OFF
WITH_CURL=ON
WITH_INOTIFY=ON
WITH_JS=ON
WITH_TAGLIB=ON
WITH_AVCODEC=1
WITH_FFMPEGTHUMBNAILER=1
WITH_EXIF=ON
WITH_EXIV2=ON
WITH_MATROSKA=ON
WITH_WAVPACK=OFF
WITH_SYSTEMD=ON
WITH_LASTFM=OFF
WITH_DEBUG=ON
WITH_DEBUG_OPTIONS=ON
WITH_TESTS=OFF
```
I confirm that the commit fixed the issue :+1: 

Thank you very much!

**Comment by KarlStraussberger** [comment]
Merci.

**Comment by gobater** [comment]
Just confirming that gerbera v2.3.0-6-gd15693fd solved the issue.
@KarlStraussberger does the debian package repository (standard, not git) contain more than on version of the packages? Before the problem was solved in -git, I wanted to downgrade to 2.2.0 but either only 2.3.0 was available or I was doing something wrong.

**Comment by KarlStraussberger** [comment]
@gobater sorry, I don't know the setting of the deb repo @whyman maintains it.

**Comment by whyman** [comment]
We dont delete the old versions, the files are still there, but I dont think apt can see them because the index can only contain the most recent

**Comment by gobater** [comment]
Thx for checking. Might be possible that the index only contains the latest. I tried manually to specify the version via command line and it did no work.
Nevertheless,  the problem is fixed on master 👍🏻
