### ISSUE TITLE
Media Players unable to find or show media items (libupnp ThreadPoolAdd too many jobs: 100)

### ISSUE THREAD

**Issue by zz0rk** [gerbera/gerbera#3236]
**Describe the bug**
I upgraded from 2.2 to 2.3. The upgrade was successful. I am able to access the GUI. The dB is populated (media items for audio, movies, tv shows are listed). I use foobar mobile and VLC on iOS; and volumio. Foobar is unable to find my gerbera server on my network even with a fully qualified path (http://ip_address:49152/description.xml). VLC is able to see the server and I am able to navigate the folder structure, but no media items are listed to select. Volumio is unable to find the server. I've rebooted the service several times. I see my iOS client listed under 'Clients' in the GUI. It seems that at the time when the client first connects it throws an  error: libupnp ThreadPoolAdd too many jobs: 100. The time stamp for when the client connects and the error occurs seems to coincide. I haven't made any changes to my configuration prior to the upgrade. Nothing has changed in my network infrastructure. I am able to access my media using NFS without problems. I haven't upgraded iOS (it's the latest version) or any of the media players. I am able to play back media from the gerbera GUI.

**To Reproduce**
0. Relevant config: [e.g. import mode, layout mode]
no configuration changes prior to upgrade from 2.2. to 2.3
1. Start service with config [relevant config]
N/A
2. Action on client or filesystem
The client is unable to find the server on my network or unable to list any media items from the dB
3. See error
libupnp ThreadPoolAdd too many jobs: 100

**Expected behavior**
I would expect my media players to be able to connect to my gerbera server and/or list media items after the upgrade as before.

**Server (please complete the following information):**
 - OS: [e.g. Ubuntu:20.04]
Debian 12
 - Gerbera Version: [e.g. 2.0]
 2.3
 - Versions of libraries: [e.g. taglib, libexiv2]
 ?
 - Source: [e.g. jfrog, self built]
 https://docs.gerbera.io/en/stable/install.html > installation instructions for Debian

**Media client (please complete the following / remove not applicable:**
 - Device: [e.g. iPhone6, Samsung TV, HEOS Multi room]
 iOS 17.6.1 and Volumio (based on Debian)
 - Client app: [e.g. BubbleUpnp, Foobar2000, Kodi]
 Foobar, VLC, Volumio
 - Browser: [e.g. chrome, safari]
 N/A

**Additional context**

**Comment by udippel** [comment]
This might be not too much of help, but eventually useful:
I have noticed something likewise, though always successful: Whichever client, BubbleUPnP, VLC, etc. the gerbera media server - contrary to all others on the network - takes loooong to show. Sometimes I have to click the UPnP category in VLC, search services in BubbleUPnP, before finally the gerbera device comes up. 
And neither seem to remember one way or another, and I have to redo all this a few hours later. 

It might be useful to confirm that your gerbera REALLY never shows?

**Comment by KarlStraussberger** [comment]
The point is, that the problem lies in libpupnp which is part of the distro in most cases.

@zz0rk can you try to find out the version and the build config.

**Comment by zz0rk** [comment]
@udippel
> ... the gerbera media server - contrary to all others on the network - takes loooong to show. 

The Gerbera server is showing in VLC immediately. I can navigate folders and sub folders. When I first posted none of the media files populated. Even after waiting for several minutes. The gear wheel just kept on spinning, but nothing happened; or it stopped spinning, but the folder remained empty. Today, it sometimes does list the media files, other times it doesn't. Closing VLC and then reopening it works sometimes but not consistently. Yet, the Gerbera server always shows immediately and consistently. I haven't upgraded VLC and there's no upgrade available.

Foobar Mobile doesn't show the Gerbera server at all. It can't discover it and even when adding the server as a bookmark (http://192.168.1.206:49152/description.xml) it can't discover it. This is still the same behavior after upgrading to the latest version today.

Thank you muchly for your feedback.

**Comment by zz0rk** [comment]
@KarlStraussberger 

> The point is, that the problem lies in libpupnp which is part of the distro in most cases.
> 
> @zz0rk can you try to find out the version and the build config.

Here you go. I am not sure how to determine the build config. Please let me know if you need anything else. Thank you!

apt show libupnp13
Package: libupnp13
Version: 1:1.8.4-2
Priority: optional
Section: libs
Source: pupnp-1.8
Maintainer: James Cowgill <jcowgill@debian.org>
Installed-Size: 330 kB
Depends: libc6 (>= 2.15), libixml10 (>= 1:1.8.0)
Homepage: http://pupnp.sourceforge.net/
Tag: role::shared-lib
Download-Size: 145 kB
APT-Manual-Installed: no
APT-Sources: http://deb.debian.org/debian bookworm/main amd64 Packages
Description: Portable SDK for UPnP Devices, version 1.8 (shared library)
 The Portable SDK for UPnP Devices (libupnp) provides developers with an
 API and open source code for building control points, devices, and
 bridges that are compliant with Version 1.0 of the Universal Plug and
 Play Device Architecture Specification - see http://www.upnp.org/ for
 specifications.

**Comment by zz0rk** [comment]
Apparently there may be partly an issue with Foobar Mobile as well.
https://hydrogenaud.io/index.php/topic,126664.new.html#new

**Comment by KarlStraussberger** [comment]
https://github.com/pupnp/pupnp/pull/451

**Comment by Entropy512** [comment]
Question:  Looking at the CI artifacts, the "edge" tag of the Docker container ( https://hub.docker.com/layers/gerbera/gerbera/edge/images/sha256-2f9f0333d16f74866c202c8f48363ba7f3cae0ef81f415f487044b589cd61620?context=explore ) should include commit #3244 - yet even after upgrading to Edge I'm getting the log spam of "libupnp ThreadPoolAdd too many jobs: 100"

docker-ce is installed from Docker's package repo ( https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository ) on x86_64 (host is Ubuntu 24.04)

This behavior started after adding a directory with a very large number of images (more than 66,000) - Gerbera was handling around 1500 videos fine prior to this.  After adding those images, any attempt to access them leads to Kodi running on a Chromecast with Google TV hanging and eventually Gerbera becoming unresponsive via upnp (however the web UI continues functioning).  Even without attempting to access that directory, Gerbera is spamming the logs with the ThreadPoolAdd error.

Upgrading from "latest" tag to "edge" did not fix the issue even though that commit indicates it should have.

**Comment by KarlStraussberger** [comment]
In fact, I had too many local changes and the update of the libpupnp was not in the the package, yet. #3251 now contains it and the messages should go away.

**Comment by Entropy512** [comment]
Yup.  That fixes the spam.  Unfortunately, it turns out that was a red herring (Kodi still hangs and causes Gerbera to stop responding to UPnP when loading the pictures directory), so I need to do some more testing/investigation before filing a new issue.
