### ISSUE TITLE
Wrong 'indexing' (duplicated artists) due to Album Artist field content

### ISSUE THREAD

**Issue by gobater** [gerbera/gerbera#3239]
**Describe the bug**
Gerbera creates duplicated artists names because of "AlbumArtist" field in mp3tag.
In case the tags of two different mp3 files contain the same artist but different albumartist, gerbera creates two different entries in the tree.

**To Reproduce**
Use the standard JS import scripts (without any customisation)

I have created a demo "library" for purpose of reproduction. See belowThe tags of my mp3 files
![image](https://github.com/user-attachments/assets/467de10c-64f8-4979-bdca-590529cf3257)

As you can see, there are 3 Tracks for Aerosmith:
1. Album Artist is "Aerosmith"
2. Album Artist is "Soundtrack"
3. No Album Artist

Additionally, a similar case occurs with the following 3 tracks. Notice that the last of them, contains 2 artists: "Extremoduro" and "Albert Pla"

**Current behavior**
Gerbera creates two artist folder for Aerosmith (the first one containeing tracks 1 and 3, and the second containing track 2-soundtrack) --> see below

![image](https://github.com/user-attachments/assets/44863128-ba3a-4be6-a921-959f1b9af141)

**Expected behavior**
My expectation would be that only an "Aerosmith" folder is created in the tree, with 3 albums. --> see below
![image](https://github.com/user-attachments/assets/9166feb6-8a76-41f3-9391-a187c782d27e)

In case of the track with multiple artists, my expectation is that gerbera shows the album on all artists (as it does), but without creating a new entry

I will provide a fix for the JS code that fixes it. However, I would need expect support in the review to ensure that everything I'm doing is correct.

**Server (please complete the following information):**
 - OS: Raspberry Pi. Bookworm
 - Gerbera Version: v2.3.0-6-gd15693fd

**Comment by gobater** [comment]
To get the expected behavior, comment line 535 (in common.js)
```
// chain.artist.metadata[M_ALBUMARTIST] = albumArtist;
```

**Comment by KarlStraussberger** [comment]
The key to the folder is `<virtual-directories>`. You may achieve your desired behaviour by

```
<virtual-directories>
  <key metadata="M_ARTIST"/>
</virtual-directories>
```

**Comment by gobater** [comment]
Unfortunately does not work. Still two artists with name "Albert Pla"... --> notice that one of the two tracks has an additional artist
![image](https://github.com/user-attachments/assets/cc410dbc-2d0c-4fcc-94ea-94f0ef661188)

**Comment by KarlStraussberger** [comment]
Should be there. Maybe in the server something is missing.

**Comment by gobater** [comment]
I don't get you... Something missing like...?
It shall be quite easy to reproduce and debug. Let me know if you don't manage and need some test files.

When I hover over the two folders in the web frontend I can see different messages:
* "AlbertPla@AlbertPla ..." --> Seems Artist@Artist
* "AlbertPla@Extremoduro ..." --> Seems Artist[x]@Artist[...]
So basically, there track having multiple artists is not imported correctly

**Comment by KarlStraussberger** [comment]
The problem seems to be that all artists are concatenated. So the script may only set one in the M_ARTIST array instead of all. Might be an option to use  another M_... like M_ACTOR for your purpose.

**Comment by gobater** [comment]
Yes, it seems that only the first one is set, but thats wrong, right? I suppose it shall set the right one (in my case the second)... I'm not sure putting them all would result in anything meaningful. I could "understand" people willing to have tracks with two artists in a "new" artist that is the combination of all (and not put the tracks below each of the artists, which is what I desire...) --> that would introduce the permutation problem...

I've been playing around and I think the only solution I've found satisfactory (for me) is to unset "M_ALBUMARTIST" in the metadata of the artist chain.

Doing as you suggested before (setting the metadata key for virtual directories to 'M_ARTIST') makes it even worst than I though...  look what it does when I have a "Various Artists" album...
![image](https://github.com/user-attachments/assets/a8d08084-51b0-41ed-a11a-83a8e16f7606)

**Comment by KarlStraussberger** [comment]
I just had the idea to introduce something like "M_ARTIST_1" but that is only working if the "correct" artist is the first in the list. In fact that's how it's working at the moment: The first artist found is picked the remaining ones are ignored. I will change that to get the concatenation in as well. The current version will become the "_1" option but that is not deterministic as long as we do not sort artists in the script (TODO as well). But nomally the main artist is the first and the contributing ones follow.

To get you problem solved you have to identify the correct artist and set it as M_ALBUMARTIST or M_ACTOR and get that as key for the folder.

**Comment by gobater** [comment]
Honestly I think this requires some more 'reflexion' before going straight into coding...

Why shall the main artist be first?
What if there is no "main" artist? I am sure there are many cases where the collaboration is 50-50

Think about the Genre array... is the first value more valid than the following?
MusicBee is treating all Artists/Genres "equally".
What is the benefit of having in the artist container a metadata element called "AlbumArtist"? It does not feel very intuitive to me, and much less to set it to something different than the artist name

**Comment by KarlStraussberger** [comment]
The point is that the whole tree should be called AlbumArtists, because there is no point listing albums under regular artists (in modern times we only have tracks that do not belong to any album - yet).

If we go along this line of thought, the "new" artists section will directly contain titles, no albums. Here it is clear that each artists shows up separately.

On the other side the "AlbumArtist" tree only contains entries that have M_ALBUMARTIST set, if there are multiple values, they have to be concatenated, but they should be identical for the whole album.

**Comment by gobater** [comment]
You might be right, but that's a complete different discussion :-) The problem here is the handling that gerbera does when multiple "artists" are available.

I think the idea behind AlbumArtist tag is to have only "one". The id3 standard does not mention anything about having more than one performer in TPE2 (in contrast to TPE1).
I like to think about "Album Artist" as the answer to the following question: "where would you find this album in a record shop? (back in the old days)"... so e.g. VVAA tribute albums to AC-DC, would have "AlbumArtist" tag set "AC-DC".
The same applies somehow to Soundtracks --> TPE2 = "Soundtrack"

That's the way I am tagging my files, but I fully understand that not everybody sticks (or has to stick) to that.

I cannot imagine (m)any people willing (in my situation) to have two different artists named "Albert Pla", "Aerosmith" or whoever else... so I guess that shall be "standard" feature of gerbera. -> one could argue if the soundtracks performed by "Aerosmith" shall be listed below Aerosmith (Artist) or "Soundtrack" (AlbumArtist) or both...

**Comment by KarlStraussberger** [comment]
I will change it to allow restriction by container type.

Thus, it will default to adress the initial problem: duplicate albums (like "Best of Metal") or reeditions ("Black Album", remastered). The remaining cotainers will just be found by name.

NB: got quite some backlog built up during 2 weeks of traviling in France
