### ISSUE TITLE
gerbera dies too easily with wrong search parameters

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3245]
Quite some time ago I had suggested to introduce a Search function on the start page. Now it is there! Congratulations!

I wonder, however, if it should - for the moment - remain there. Searching with UPnP-syntax is one thing (I managed once), but my next efforts failed because of gerbera crashing for misspelled / empty search strings. My suggestion: as long as the search engine isn't robust enough to bump out of a wrong search syntax, eventually better enable/disable this search; or hide it somewhere off the first page.

**Comment by KarlStraussberger** [comment]
Can you please give examples of broken queries. If not, the bug is pointless.

If we hide new feature they will never be used and stay faulty forever. If the server crashes it also crashes of you use your favourite UPnP client. Thus, showing the page may contribute to fixing these bugs!

**Comment by udippel** [comment]
(I agree with you fully, about the report eventually being pointless. However, often enough a pull request on new features has already been issued, a specific shortcoming is already known, and so forth. Then all the efforts are not needed, and only clutter space. 
Please, allow also in future to 'just test the waters' before writing extensive reports, filled with screen shots, in the first place. )

Query: "dc:title contains "antomas""
and
Sort: "-dc:title"
make 2.3.0-12-g2c0fa369 die without any indication in the normal log. 
```
2024-10-11 14:28:48 warning: Web Error: 400 invalid session id
2024-10-11 14:41:02   info: Daemonized.
```
Logged in again, in between the two lines, and repeated that not very clever search. gerbera went out without entry in the log, and no more process ("ps") left.

**Comment by KarlStraussberger** [comment]
There seems to be some other reason for you crash. I tried several versions and my server is still running,

**Comment by udippel** [comment]
I had tried half a dozen of times, with slightly different search terms. And it failed invariably. 
With ....14 ... it is the first time that it comes back and asks for something more intriguing ("... another container ..."). 
I suggest we assume that the crash was related to another of the known, resolved, issues and close this one, too..
