### ISSUE TITLE
Length/Size indication is gone from Database view

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3246]
IMHHO, I was most happy with the indication of basic file details, like playtime, resolution, in the Database view. In 2.3.0-12 this seems to be gone (by default?). Or does it need a new, extra, setting?

**Comment by KarlStraussberger** [comment]
For future consideration: when posting bugs, please use the template and provide screenshots to ease understanding the issue.

**Comment by udippel** [comment]
I totally agree, in principle, with your request and your criticism. 
Sometimes, however, I think that the issue is quite obvious, and difficult to roll back, like in this case. 

I see that you already have issued a pull request. Therefore I leave out details. Whenever things are unclear, never hesitate to ask, though, please!
