### ISSUE TITLE
2.3.0-12-g2c0fa369 does not deliver anything from the web client, including downloads, however with a client like BubbleUPnP it works

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3248]
Before, clicking on an item in the web interface, would bring up a player (video in this case), or playing audio for an audio resource. Now it doesn't do anything of this sort any longer. The resource can still be accessed with a client like BubbleUPnP.
![image](https://github.com/user-attachments/assets/3310da06-706f-4b3f-b61e-4f632f55f4e5)

Additionally, it is not possible to download that resource any longer. 
![image](https://github.com/user-attachments/assets/b9e6692f-e9df-476c-aaa7-093f5c6083cc)

The browser window will try to download an .html file (which the resource isn't):
![image](https://github.com/user-attachments/assets/8b289d94-59b8-431e-9229-633bf526a916)
and 
![image](https://github.com/user-attachments/assets/e117e05e-aaa1-4bfe-8cf3-c99eac81b7d9)
, and the standard log will state:
`2024-10-11 15:01:09  error: Exception: [/build/src/server.cc:631] std::unique_ptr<RequestHandler> Server::createRequestHandler(const char*, const std::shared_ptr<Quirks>&) const Error: No valid handler type in /undefined`
This is not a singular case but applies to any object.

In this case, the object has following characteristics:
![image](https://github.com/user-attachments/assets/fcb33675-71ee-471a-93d4-c2f4ee7e94d4)

**Comment by KarlStraussberger** [comment]
This is the same issue. The data for the links is not sent to the ui.
