### ISSUE TITLE
A file found by gerbera later is shown as not found

### ISSUE THREAD

**Issue by udippel** [gerbera/gerbera#3253]
Since the drive in question is set to `ro`, when gerbera finds a file, it ought to be able to retrieve it. 
(This is totally minor, though it ought not happen.)
`2024-10-17 10:08:54  error: Exception: [/build/src/request_handler/file_request_handler.cc:109] virtual bool FileRequestHandler::getInfo(const char*, UpnpFileInfo*) Error: Failed to open /Audio/Albums/Ao Vivo@2002: No such file or directory`

I tried hard to debug this by finding the respective Album respective file, from where this was taken:
```
$ locate "Ao Vivo" | grep 200
$
```
There is no "Vivo" in conjunction with "m3u" neither. 

As I wrote, this is no big thing. Nevertheless, it seems to point to some inconsistency between import and the actual ability to retrieve some media.

**Comment by KarlStraussberger** [comment]
This seems to be a virtual directory, so the question is which triggers the message.  Is there an information about that particular file on the web ui?

**Comment by udippel** [comment]
No, unfortunately not. To be honest, I'm not into this stuff for daily usage. I think the 2002 comes from some metatag (taglib? if we use it?), and gerbera assembled this as album. I was just scrolling through albums listed, when it occurred.

Tried to repeat the matter, intensely, with the web ui; but no luck. With BubbleUPnP, however, the error popped up again. Not playing, just scrolling by. There are 16 files (tracks) in that album, and all show, in the web ui as well as in BubbleUPnP. 

Another error püpped up as well; I include it here though it comes from a very different corner of gerbera:
`2024-10-18 19:17:27  error: Exception: [/build/src/util/grb_fs.cc:166] FILE* GrbFile::open(const char*, bool) Error: Could not open /usr/share/gerbera/web/vendor/tether/tether.min.js.map: No such file or directory`
That's more my piece of cake, and I can confirm that it doesn't exist. 
```
ls -l /usr/share/gerbera/web/vendor/tether/
-rw-r--r-- 1 root root   237 Oct 18 14:09 tether-2.0.0.min.css
-rw-r--r-- 1 root root 21873 Oct 18 14:09 tether-2.0.0.min.js
```
is the closest we get, with ... 23 ...

**Comment by udippel** [comment]
I'd like to get to the bottom of this. 
Here is some more:
In the virtual albums, I have more than 1 "Ao vivo". One is the @2002; another one @2009:  (at mouse over)
![image](https://github.com/user-attachments/assets/cd7eb510-1acf-4781-acdc-395ab5ae53ab)

Strangely enough, the files are there, playable, but their "edit" views are different: Those in the @2002 directory all have a broken image on top, those in the @2009 folders not:
![image](https://github.com/user-attachments/assets/4b5b3e44-dd78-4984-9d13-d82f11104d5a)

![image](https://github.com/user-attachments/assets/a0716508-6edb-4d79-9162-d579f309ff95)

I wonder, which image is supposed to be shown up there? Unfortunately, I didn't manage to see the underlying HTML of this "Edit"-PopUp. So I can't say as of now, which image is written into the HTML code, but unavailable.

**Comment by udippel** [comment]
Thanks. Same here with broken images.

**Comment by nobanzai** [comment]
I got rid of the duplicates by adding

`    <virtual-directories>
      <key metadata="location"/>
    </virtual-directories>
`
to config.xml.
As for the broken images: It seems to be caused by wrong permissions, certain file names for album art files and so on.
I could get rid of a few of them by correcting that.

But both are separate cases and have nothing to do with the error messages mentioned above.
I get the error messages even after repairing the duplicates and for folders, that don't contain image files.

**Comment by udippel** [comment]
This is not a principally static, but dynamic system.
Rectifying individual errors therefore is useless.
At some point of import or assembly something goes haywire. I THINK at
assembly, due to the broken images at the top of Details.

**Comment by KarlStraussberger** [comment]
I am not sure how this comes to be: A virtual folder lost its image and so the virtual location is used as path to the image.

The patch get rid of the message, but still UI shows the missing/no image
