### ISSUE TITLE
docker user id 100 in container -> user "messagebus" on host

### ISSUE THREAD

**Issue by zenhighzer** [gerbera/gerbera#3260]
Hi, 

I am pretty new to docker, etc. 
Running gerbera as container while bind-mounting a content-directory (permissions on host are: drwxr-x---(750) for user:group "zen:zen") results in permission error...  i have to change my "host"-content-directory-owners to user "messagebus", because it seems that in containers gebera is running with id 100 which is in fact the messagebus-user on my host... 

Is there a way to change this? I would like to keep my owners/group to "zen:zen" and bind this directory to gerbera... 
I would like to avoid permissions like "754" (others=read) 

Can you help me finding a solution? 
Thanks and Best Regards
Zen

**Comment by KarlStraussberger** [comment]
I found some hints how to fix that issue. Takes some time...
