### ISSUE TITLE
Issue on gerbera.db

### ISSUE THREAD

**Issue by pjcau** [gerbera/gerbera#3262]
**Describe the bug**
I cannot start the service and I cannot go in webserver I deleted the /var/lib/gerbera/gerbera.db, but it cannot be create again

**To Reproduce**
0. Relevant config: [e.g. import mode, layout mode]
1. Start service with config [relevant config]
2. Action on client or filesystem
3. Nov 03 01:59:37 raspberrypi systemd[1]:
```
gerbera.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 01:59:37 raspberrypi systemd[1]: gerbera.service: Failed with result 'exit-code'.
Nov 03 01:59:42 raspberrypi systemd[1]: gerbera.service: Scheduled restart job, restart counter is at 101.
Nov 03 01:59:42 raspberrypi systemd[1]: Stopped gerbera.service - Gerbera Media Server with MySQL.
Nov 03 01:59:42 raspberrypi systemd[1]: Started gerbera.service - Gerbera Media Server with MySQL.
Nov 03 01:59:42 raspberrypi gerbera[13234]: 2024-11-03 01:59:42   info: Gerbera UPnP Server 2.3.0 - https://gerbera.io/
Nov 03 01:59:42 raspberrypi gerbera[13234]: 2024-11-03 01:59:42   info: Copyright 2016-2024 Gerbera Contributors.
Nov 03 01:59:42 raspberrypi gerbera[13234]: 2024-11-03 01:59:42   info: Gerbera is free software, covered by the GNU General Public License version 2
Nov 03 01:59:42 raspberrypi gerbera[13234]: 2024-11-03 01:59:42   info: Loading configuration from: /etc/gerbera/config.xml
Nov 03 01:59:42 raspberrypi gerbera[13234]: 2024-11-03 01:59:42   info: Parsing configuration...
Nov 03 01:59:42 raspberrypi gerbera[13234]: 2024-11-03 01:59:42  error: [/build/src/config/setup/config_setup_path.cc:103] std::filesystem::__cxx11::path ConfigPathSetup::resolvePath(std::filesystem::__cxx11::path) const Error: Parent directory '/var/lib/gerbera/gerbera.db' does not exist for '/config/server/storage/sqlite3/database-file'
Nov 03 01:59:42 raspberrypi systemd[1]: gerbera.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 01:59:42 raspberrypi systemd[1]: gerbera.service: Failed with result 'exit-code'.
```
And
```
sudo systemctl status gerbera.service
● gerbera.service - Gerbera Media Server with MySQL
     Loaded: loaded (/lib/systemd/system/gerbera.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2024-11-03 02:03:38 CET; 652ms ago
    Process: 15028 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml --syslog (code=exited, status=1/FAILURE)
   Main PID: 15028 (code=exited, status=1/FAILURE)
        CPU: 178ms
```
**Expected behavior**

**Server (please complete the following information):**
 - OS: [e.g. Debian:12]
 - Gerbera Version: [e.g. 2.3]

**Media client (please complete the following / remove not applicable:**
 - Device: [e.g. iPhone6, Samsung TV, HEOS Multi room]
 - Client app: [e.g. BubbleUpnp, Foobar2000, Kodi]
 - Browser: [e.g. chrome, safari]

**Additional context**

**Comment by KarlStraussberger** [comment]
Error: Parent directory '/var/lib/gerbera/gerbera.db' does not exist

Please create `/var/lib/gerbera` and make sure that it is writable for the gerbera user.

**Comment by pjcau** [comment]
Can you send a tutorial o write the command here?Thank youInviato da iPhoneIl giorno 3 nov 2024, alle ore 08:56, Karlchen ***@***.***> ha scritto:﻿
Error: Parent directory '/var/lib/gerbera/gerbera.db' does not exist
Please create /var/lib/gerbera and make sure that it is writable for the gerbera user.

**Comment by pjcau** [comment]
Ok, can you should write all steps or link to a tutorial?

Thank you

**Comment by pjcau** [comment]
OK, great now it works. But I cannot enter to webserver 
that's the error on console
http://192.168.1.12:49152/content/interface?req_type=auth&return_type=xml&sid=e30f8753-bfcf-4f32-bf8e-248e6512dd04&action=get_token
