### ISSUE TITLE
error: iconv:  <text>   could not be converted to new encoding: invalid character sequence!

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#3263]
openSUSE Leap 15.6, gerbera 2.2.0

When importing files I get lots of

"error: iconv:  <text>   could not be converted to new encoding: invalid character sequence!""

messages, but they don't tell me what files are causing them.
This behaviour exists for a long time now, it is not new in 2.2.0, but it is a bit annoying especially when trying to find the real errors.
Could you please add the location to these messages?
TIA!

**Comment by KarlStraussberger** [comment]
You can set the charset in the library-options: https://docs.gerbera.io/en/latest/config-import.html#charset

Depending on your default locale you should go for Latin-1 if your metadata contains umlauts.

**Comment by nobanzai** [comment]
Unfortunately I have different chars sets in some of the jpg files.
So I'd better convert everything to UTF according to my default locale en_US.UTF-8.
Thx for your answer.

**Comment by mehturt** [comment]
Even though this ticket is closed, I think that the original ask was not considered:
> When importing files I get lots of ... messages, but they don't tell me what files are causing them.

I have similar errors during my import (music files) and I don't know what file they are coming from.  It would help me if the offending file name was reported as part of the error message.
