### ISSUE TITLE
logger with name 'rotate_logger' already exists

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#3271]
gerbera 2.3.0 on openSUSE Leap 15.6

When running gerbera with --rotatelog, I get:

`Nov 13 15:58:19 server gerbera[22480]: terminate called after throwing an instance of 'spdlog::spdlog_ex'
Nov 13 15:58:19 server gerbera[22480]:   what():  logger with name 'rotate_logger' already exists
`

**Comment by KarlStraussberger** [comment]
Thank you, obviously never tried that option 😮‍💨
