### ISSUE TITLE
online-content example

### ISSUE THREAD

**Issue by diman82** [gerbera/gerbera#328]
Please provide example(s) of online-content (besides the already embedded 'Youtube').
Couldn't find anything in the corresponding doc [section](http://docs.gerbera.io/en/latest/config-online.html).

**Comment by elmodaddyb** [comment]
The latest code base (_1.3.0_alpha_) supports 2 types of online content services (_YouTube removed_):
* AppleTrailers
* SopCast

```xml
<import>
  <online-content>
    <AppleTrailers enabled="[yes,no]" refresh="[seconds]" purge-after="[seconds]" 
       update-at-start="[yes,no]"
       resolution="[640,720p]"/>
    <SopCast enabled="[yes,no]" refresh="<int>" purge-after="<int>" update-at-start="[yes,no]"/>
  </online-content>
</import>
```

SopCast URL is pointing to:
```c++
#define SOPCAST_CHANNEL_URL             "http://www.sopcast.com/gchlxml"
```

AppleTrailers points to:
```c++
#define ATRAILERS_SERVICE_URL_640            "http://www.apple.com/trailers/home/xml/current.xml"
#define ATRAILERS_SERVICE_URL_720P       "http://www.apple.com/trailers/home/xml/current_720p.xml"
```

> I haven't tried this but interpreted it from the code.

I am actively working on Radio Channel playlist processing, but it will be some time before its ready.

**Comment by elmodaddyb** [comment]
@diman82 - did you have any luck with online content? If no other issues or suggestions let’s close this issue?

**Comment by diman82** [comment]
@elmodaddyb  Please leave it for several days more, I'll try to check it very soon..

**Comment by elmodaddyb** [comment]
@diman82 - I posted the example for `online-content` configuration to the documentation and it is published to the documentation site:

http://docs.gerbera.io/en/latest/config-online.html

> If you encounter any issues or questions please post back.  Closing this issue for now.

Thanks,

Eamonn
