### ISSUE TITLE
Gerbera Web UI don't work in Ubuntu 24.10

### ISSUE THREAD

**Issue by cafaia** [gerbera/gerbera#3288]
Hello everybody!

I changed my Operating System, now I'm using Ubuntu 24.10, but Gerbera doesn't work properly on it. When trying to add files to my database via the web page I cannot see the fields for this. I tried to add the media through the config.xml file in the autoscan part, but then Gerbera doesn't stop working...

**To Reproduce**
0. Relevant config: even if I use the default settings I don't see a proper web page;
1. Start service with config: systemctl enable gerbera and systemctl start gerbera
2. Action on client or filesystem: I can't see anything where I can add the files to my database;
3. See error: I have at the address http://192.168.1.10:49154/, regardless of the browser I use, a completely broken web page;

**Expected behavior**
I was hoping to have a functional web page where I could navigate between my file system and my database.

**Server (please complete the following information):**
 - OS: Ubuntu:24.10
 - Gerbera Version: 2.2.0+dfsg-1build1
 - Versions of libraries: libupnp17t64-1:1.14.19-2ubuntu1
 - Source: binary program from the distribution itself.
![Captura de tela de 2024-12-01 11-06-24](https://github.com/user-attachments/assets/259fd159-227c-4709-ad51-5b2f92b11bd9)

**Comment by KarlStraussberger** [comment]
This look very like other situations after an incompatible update. Your old and new installation paths are different, so the caches and the configuration do not reflect the latest data. Please take a look at https://docs.gerbera.io/en/latest/troubleshooting.html#installation

**Comment by cafaia** [comment]
Hello!

Thank you very much for your attention, I really appreciate it! But when I read what you sent me I realized that it doesn't fit my case, because my installation is from scratch...

When it came to reloading the page, clearing the cache and opening in an incognito window, none of this worked, unfortunately...

Thanks again and big hug!

**Comment by KarlStraussberger** [comment]
As I am not quite sure about the quality of the version `2.2.0+dfsg-1build1` package und debian, can you try out our latest build https://docs.gerbera.io/en/latest/install.html#debian 
```
wget -O - https://pkg.gerbera.io/public.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/gerbera-keyring.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/gerbera-keyring.gpg] https://pkg.gerbera.io/debian-git/ $(lsb_release -c --short) main" | sudo tee /etc/apt/sources.list.d/gerbera.list >/dev/null
sudo apt-get update
sudo apt-get install gerbera
```

**Comment by Ubermensch85** [comment]
Debian Trixie: i have the same problem with web UI
![2024-12-03T09:49:32,241268300+01:00](https://github.com/user-attachments/assets/0411fd79-a6d7-49bf-94ee-9a47eb625023)

**Comment by cafaia** [comment]
> As I am not quite sure about the quality of the version `2.2.0+dfsg-1build1` package und debian, can you try out our latest build https://docs.gerbera.io/en/latest/install.html#debian
> 
> ```
> wget -O - https://pkg.gerbera.io/public.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/gerbera-keyring.gpg >/dev/null
> echo "deb [signed-by=/usr/share/keyrings/gerbera-keyring.gpg] https://pkg.gerbera.io/debian-git/ $(lsb_release -c --short) main" | sudo tee /etc/apt/sources.list.d/gerbera.list >/dev/null
> sudo apt-get update
> sudo apt-get install gerbera
> ```

Hello Karl!

I followed these procedures but it didn't work, I believe it's not for SystemD, because I get this:
Failed to start gerbera.service: Unit gerbera.service not found.

Big hug!

**Comment by KarlStraussberger** [comment]
> > As I am not quite sure about the quality of the version `2.2.0+dfsg-1build1` package und debian, can you try out our latest build https://docs.gerbera.io/en/latest/install.html#debian
> > ```
> > wget -O - https://pkg.gerbera.io/public.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/gerbera-keyring.gpg >/dev/null
> > echo "deb [signed-by=/usr/share/keyrings/gerbera-keyring.gpg] https://pkg.gerbera.io/debian-git/ $(lsb_release -c --short) main" | sudo tee /etc/apt/sources.list.d/gerbera.list >/dev/null
> > sudo apt-get update
> > sudo apt-get install gerbera
> > ```
> 
> Hello Karl!
> 
> I followed these procedures but it didn't work, I believe it's not for SystemD, because I get this: Failed to start gerbera.service: Unit gerbera.service not found.
> 
> Big hug!

Systemd should be enabled in debian build. Can you run `gerbera --compile-info` and share the output.

**Comment by KarlStraussberger** [comment]
> Debian Trixie: i have the same problem with web UI ![2024-12-03T09:49:32,241268300+01:00](https://private-user-images.githubusercontent.com/127672496/391883391-0411fd79-a6d7-49bf-94ee-9a47eb625023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjA0MzgsIm5iZiI6MTczMzIyMDEzOCwicGF0aCI6Ii8xMjc2NzI0OTYvMzkxODgzMzkxLTA0MTFmZDc5LWE2ZDctNDliZi05NGVlLTlhNDdlYjYyNTAyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMDAyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODljMmVmYmI3NDk0NjliYWU5ZjhmZTk2MTc3N2YwYzQwODlhNWNlN2RlZTk0ODZkOTk2MzgxYmYyYThjNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ayTVMX_sFKwZOadevRWKymzbAEZV12PoIR16d48_ChQ)

We did not build 2.3 packages for 24.10. Where is the installation package from. Seems that the fonts are not available,

**Comment by Ubermensch85** [comment]
> > Debian Trixie: i have the same problem with web UI ![2024-12-03T09:49:32,241268300+01:00](https://private-user-images.githubusercontent.com/127672496/391883391-0411fd79-a6d7-49bf-94ee-9a47eb625023.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjA0MzgsIm5iZiI6MTczMzIyMDEzOCwicGF0aCI6Ii8xMjc2NzI0OTYvMzkxODgzMzkxLTA0MTFmZDc5LWE2ZDctNDliZi05NGVlLTlhNDdlYjYyNTAyMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QxMDAyMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODljMmVmYmI3NDk0NjliYWU5ZjhmZTk2MTc3N2YwYzQwODlhNWNlN2RlZTk0ODZkOTk2MzgxYmYyYThjNDMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ayTVMX_sFKwZOadevRWKymzbAEZV12PoIR16d48_ChQ)
> 
> We did not build 2.3 packages for 24.10. Where is the installation package from. Seems that the fonts are not available,

`ubermensch@debian:~$ dpkg -s gerbera
Package: gerbera
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 7493
Maintainer: Christian Marillat <marillat@deb-multimedia.org>
Bugs: mailto:marillat@deb-multimedia.org
Architecture: amd64
Source: gerbera-dmo
Version: 1:2.3.0-dmo2
Depends: libavcodec61 (>= 10:7.1), libavformat61 (>= 10:7.1), libavutil59 (>= 10:7.1), libc6 (>= 2.38), libcurl3t64-gnutls (>= 7.16.2), libduktape207 (>= 2.7.0), libebml5 (>= 1:1.4.5), libexif12 (>= 0.6.21-1~), libexiv2-28 (>= 0.28.0), libffmpegthumbnailer4v5 (>= 1:2.2.3), libfmt10 (>= 10.1.1+ds1), libgcc-s1 (>= 3.0), libmagic1t64 (>= 5.12), libmariadb3 (>= 3.0.0), libmatroska7 (>= 1:1.7.1), libnpupnp13t64 (>= 1:6.2.0), libpugixml1v5 (>= 1.14~), libspdlog1.12-fmt10, libsqlite3-0 (>= 3.6.5), libstdc++6 (>= 14), libtag1v5 (>= 1.12~beta~1), libuuid1 (>= 2.16), adduser, sysvinit-utils (>= 3.05-4~), fonts-font-awesome (>= 5.0.10+really4.7.0~dfsg), libjs-jquery-ui (>= 1.13.2+dfsg)
Pre-Depends: init-system-helpers (>= 1.54~)
Conffiles:
 /etc/init.d/gerbera 0f6daf7f0487963ecb5c99e46d023619
 /etc/logrotate.d/gerbera 530a50788ee91140c3ccf619999d7c03
Description: UPnP MediaServer
 Gerbera is an UPnP MediaServer with a nice web user interface based on
 MediaTomb. It allows you to stream your digital media through your home
 network and listen to/watch it on a variety of UPnP compatible devices.
 .
 Gerbera implements the UPnP MediaServer V 1.0 specification that can be
 found on https://www.upnp.org/. The current implementation focuses on parts
 that are required by the specification, however Gerbera's functionality is
 extended to cover the optional parts of the spec as well.
Homepage: https://gerbera.io/
ubermensch@debian:~$ 
`

**Comment by KarlStraussberger** [comment]
> libnpupnp13t64

@Ubermensch85 same here: Please try to install our built and make sure no references to old paths are in you config files. Also clear the browser cache.

**Comment by KarlStraussberger** [comment]
> Hello Karl!
> 
> I ran in a terminal, since this version doesn't have SystemD support, 'gerbera -c /etc/gerbera/config.xml' and everything worked fine!
> 
> If you can get this same version with SystemD support, I'd love it!
> 
> Thank you for everything and a big hug!

Thanks for confirming that. We need to find out why SystemD support was not detected correctly.

**Comment by KarlStraussberger** [comment]
@cafaia 
SystemD support is now also in testing images.

Import times are normal on first run
