### ISSUE TITLE
Sony BluRay only browses folders and does not see files

### ISSUE THREAD

**Issue by cafaia** [gerbera/gerbera#3291]
**Describe the bug**
After a long period of time to create my database, I have 5 TB of songs, when I access Gerbera through my BluRay Player I can only browse the folders, but they are all empty, unlike what happens with MConnect on my cell phone, where I can browse and put them to listen to on my BluRay Player by rendering.

**To Reproduce**
0. Relevant config: I tested with the default configuration with a few changes only and with my own configuration from other versions of Gerbera, both did not work.
2. Start service with config: I start the service with 'systemctl start gerbera' on my computer.
3. Action on client or filesystem: When browsing folders on a client, my Sony bluray player, I only see the folders and they are all empty.
4. See error: The folders, which contain music, appear as having no items.

**Expected behavior**
I was hoping I could see and hear the songs by browsing my BluRay Player.

**Server (please complete the following information):**
 - OS: Ubuntu 24.10
 - Gerbera Version: 2.3.0+50~20241202123743-oracular1
 - Versions of libraries: libexiv2-27-0.27.6-1build1
 - Source: binary from Team Gerbera

**Media client (please complete the following / remove not applicable:**
 - Device: PC Dell
 - Client app: BluRay Player Sony - BDP S6200
 - Browser: Chromium

**Comment by cafaia** [comment]
Below I send images with the navigation sequence through the folders on my Sony bluray player.
![IMG_20241205_094729118](https://github.com/user-attachments/assets/f79a6798-d760-4670-9105-3be90245140e)
![IMG_20241205_094757923_HDR](https://github.com/user-attachments/assets/b12fda71-7fc2-4897-b487-63be7d6cd611)
![IMG_20241205_094827558_HDR](https://github.com/user-attachments/assets/14a7145e-e48d-469b-b5e9-b38607f44f1a)
![IMG_20241205_094856750_HDR](https://github.com/user-attachments/assets/6fce1938-1aa3-4442-923c-77b54a6f22f7)
![Screenshot_20241205-095007](https://github.com/user-attachments/assets/f54800b7-3de6-4f4e-9a4a-5b2022fd6977)

**Comment by KarlStraussberger** [comment]
I haven't used that one for ages so it still showed mobile devices long gone. And I had the same issue  - until I cleared all renderers under network settings.

The solution is the cache Sony builts up: it requested the wrong containers. Seem the cache is just by name - oops.

**Comment by cafaia** [comment]
Hello Karl!

I understand your point, but wouldn't there be a way to enable the file extension in Gerbera?

Thank you very much for your help and a big hug!

**Comment by KarlStraussberger** [comment]
There is no way to tell a client to clear its cache.

**Comment by cafaia** [comment]
Hello Karl!

What a shame! I loved using the navigation system through the BluRay Player client... What can I do?

**Comment by cafaia** [comment]
Hello Karl!

What a shame! I loved using the navigation system through the BluRay Player client... What can I do?

Before I used Gentoo as my Operating System and Gerbera version 2.2.0 with only the 'magic' flag enabled and everything worked fine... Is this a change in version 2.3.0 then?

Thanks again and big hug!

**Comment by KarlStraussberger** [comment]
It's just a bug in the blueray software. After your cleared the renderers from the player it reloads everything.

**Comment by cafaia** [comment]
Hello Karl!

Now everything worked out, I did what you told me and everything went well, so thank you very much!

Big hug!
