### ISSUE TITLE
Gerbera dumping core using extended mimetype defintion in a profile

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#3302]
```
      <profile
        name="mh-mp2mp3"
        enabled="yes"
        type="external"
      >
        <mimetype value="audio/mpeg">
          <mime-property key="audioCodec" resource="mp3"/>
        </mimetype>
...

```
leads to a core dump.
Not sure, if key="audioCodec" is valid, but Gerbera deinitively shouldn't dump core because of this.

Gerbera version is gerbera-2.3.0-lp156.51.1.x86_64

**Comment by KarlStraussberger** [comment]
It's the resource. Confg check now terminates correctly
