### ISSUE TITLE
Technisat DigitRadio 580 does not see audio files

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#3312]
**Describe the bug**
After upgrading from 2.3.0 to latest master, my kitchen radio does not show audio files anymore - only folders.

`git bisect` told me that filters (#3233) are the culprit:
```
root@dojo:/usr/local/src/gerbera/gerbera-git# git bisect good
1b2adbc835953e70a0c0c65c9f86bb30d6a9bc70 is the first bad commit
commit 1b2adbc835953e70a0c0c65c9f86bb30d6a9bc70
Author: Karlchen <k_straussberger@netzland.net>
Date:   Tue Sep 24 16:41:27 2024 +0200

    UPnP: Add support for filters

 src/content/import_service.cc |   2 +-
 src/upnp/cont_dir_service.cc  |  22 +++++---
 src/upnp/upnp_common.h        |   1 +
 src/upnp/xml_builder.cc       | 126 ++++++++++++++++++++++++++++++++++--------
 src/upnp/xml_builder.h        |  77 ++++++++++++++++++++------
 test/core/test_upnp_xml.cc    |  10 ++--
 6 files changed, 184 insertions(+), 54 deletions(-)
```

(with this commit, even folders are not visible anymore).

VLC shows the audio files and can play them.

In #2894 and #2920 I had the same symptoms - missing audio files.

**Debugging**
Using the same technique as #2920 I see:
```
$ curl "digira/fsapi/SET/netRemote.misc.fsDebug.component?pin=1234&value=14"
<fsapiResponse>
<status>FS_OK</status>
</fsapiResponse>

$ curl 'digira/fsapi/SET/netRemote.misc.fsDebug.traceLevel?pin=1234&value=5'
<fsapiResponse>
<status>FS_OK</status>
</fsapiResponse>

$ telnet digira 514
[...]
(Thread2): [6014853.033959] AVB    (3): Browse for '61426', from 0, max 100 items, server 'f42aa029-7c99-47d2-b6ed-53b9e06cc3a8'
(Thread2): [6014853.034310] AVB    (4): Using sort criteria '+upnp:originalTrackNumber'
(Thread2): [6014853.046812] AVB    (4): Invoking AVB_REQTYPE_BROWSE request (b0c4e418 b0c4e418)
(Thread2): [6014853.440068] AVB    (4): MSCPResponseSink_ContentDirectory_Browse: Detected mismatch with number of objects returned=15 and
(Thread2): [6014853.442182] AVB    (5): (MS_BrowseResponded) errorCode=0
(Thread2): [6014853.442691] AVB    (3): Browse OK - 15 matches, 15 returned, 0 copied
(Thread2): [6014853.442883] AVB    (3): TotalMatches = 15
```

Under normal circumstances, all the files are "copied"/displayed.

The DIDL lite (obtained with `gupnp-av-cp`) shows the date as
```
<dc:date>2016-12-17T18:57:00+0100</dc:date>
```
which was a problem already in #2920. With #2937 FrontierSilicon radios should automatically get timezone-free dates.

The automatic quirk flag for simple dates or the flag does not seem to work anymore.

**To Reproduce**

1. Start gerbera
2. Use kitchen radio to browse the UPnP folder list, select folder which has audio files in the web UI
3. See error: `<Leer>`

**Expected behavior**
The radio can see the audio files.

Configuration defaults should keep devices working after a gerbera update.

**Server (please complete the following information):**
 - OS: Debian 12
 - Gerbera Version: 12634b06668033391847a9e12722ce45d9ffad8c
 - Source: self built

**Media client (please complete the following / remove not applicable:**
 - Device: Technisat DigitRadio 580

**Comment by cweiske** [comment]
My conclusion is of course wrong; the gupnp-av-cp sends a different user agent and thus does not get the same response as my radio.

**Comment by cweiske** [comment]
By using ssh remote capture in wireshark I managed to get the DIDL-lite returned to the kitchen radio - the date indeed has a timezone:
```
    <dc:date>2016-12-17T18:57:00+0100</dc:date>
```

**Comment by cweiske** [comment]
Manually setting the flag does not help. Seems the flag is broken:
```
  <clients enabled="yes">
    <client ip="192.168.3.46" flags="SIMPLE_DATE"></client>
    </clients>
```

**Comment by KarlStraussberger** [comment]
Can you check out the clients page, please.

**Comment by KarlStraussberger** [comment]
Also try to set debug-mode xml

**Comment by cweiske** [comment]
I setup a fresh test instance of gerbera on my laptop and tried it with the kitchen radio:

The clients web page says
```
192.168.3.46 / digira / default
FSL DLNADOC/1.50 UPnP Stack/1.0
Technisat DigitRadio 580 / UserAgent / FSL DLNADOC/1.50
FSL
SIMPLE_DATE
```

but the XML returned (as shown by gerbera itself with `--debug-mode xml` contains the date with timezone:
```
2024-12-21 19:30:02.555  debug: [xml_builder.cc:372] renderObject(): Object Filters upnp:searchClass
2024-12-21 19:30:02.555  debug: [xml_builder.cc:373] renderObject(): Container Filters *
2024-12-21 19:30:02.555  debug: [xml_builder.cc:374] renderObject(): Resource Filters protection, duration, protocolInfo
2024-12-21 19:30:02.558  debug: [xml_builder.cc:1170] buildProtocolInfo(): protocolInfo: http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01700000000000000000000000000000
2024-12-21 19:30:02.558  debug: [xml_builder.cc:1170] buildProtocolInfo(): protocolInfo: http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=00800000000000000000000000000000
2024-12-21 19:30:02.559  debug: [xml_builder.cc:500] renderObject(): Rendered DIDL: <item id="692" parentID="691" restricted="1">
  <dc:title>Why Wait</dc:title>
  <upnp:class>object.item.audioItem.musicTrack</upnp:class>
  <dc:description>Amazon.com Song ID: 213109218</dc:description>
  <upnp:originalTrackNumber>4</upnp:originalTrackNumber>
  <upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0" dlna:profileID="JPEG_TN">http://192.168.3.5:49152/media/object_id/692/res_id/1/ext/file.jpg</upnp:albumArtURI>
  <res id="692.0" duration="0:03:41.283" protocolInfo="http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01700000000000000000000000000000">http://192.168.3.5:49152/media/object_id/692/res_id/0/group/default/ext/file.mp3</res>
  <res id="692.1" protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=00800000000000000000000000000000">http://192.168.3.5:49152/media/object_id/692/res_id/1/ext/file.jpg</res>
  <dc:date>2011-05-15T00:56:49+0200</dc:date>
</item>
```

----

My main gerbera instance shows a different user agent, and even this test instance temporarily had a different user agent before I deleted the database, but that's probably a different problem:
```
192.168.3.46 / digira / default
POSIX, UPnP/1.0, Intel MicroStack/1.0.2777
Standard UPnP / UserAgent / UPnP/1.0
```

**Comment by cweiske** [comment]
Ha. The user agent also changed on my test instance, and the entry in the clients list got a new "first seen" date.

**Comment by cweiske** [comment]
But also here with a custom client config (see [above](https://github.com/gerbera/gerbera/issues/3312#issuecomment-2555875895)) gerbera outputs dates with timezone. The clients table shows
```
Custom Setup for IP 192.168.3.46
SIMPLE_DATE
```

**Comment by KarlStraussberger** [comment]
> Ha. The user agent also changed on my test instance, and the entry in the clients list got a new "first seen" date.

The user agent change is quite normal. Most of the devices use a different upnp library for ssdp (discovery) and upnp. Don't know why.

**Comment by KarlStraussberger** [comment]
In fact the filter broke it. The date is not added in the regular loop so it's forced in the end - util now without simple date handling

**Comment by cweiske** [comment]
Thank you for fixing it so fast - it works now.
