### ISSUE TITLE
Error starting server with  v2.3.0-66-g88fd254a

### ISSUE THREAD

**Issue by schafdog** [gerbera/gerbera#3321]
Was running gerbera/gerbera:edge-transcoding v2.3.0-24-g74a39b0c in a docker container on Debian 12, but is having issues with external sub titles on a LG TV, so pulled today which got me  v2.3.0-66-g88fd254a

Now the server fails to start with a no descriptive error message:

2024-12-25 10:57:30  error: Logic error parsing config file '/var/run/gerbera/config.xml': stoi

`gerbera  | 2024-12-25 10:58:31   info: Gerbera UPnP Server v2.3.0-66-g88fd254a - https://gerbera.io/
gerbera  | 2024-12-25 10:58:31   info: Copyright 2016-2024 Gerbera Contributors.
gerbera  | 2024-12-25 10:58:31   info: Gerbera is free software, covered by the GNU General Public License version 2
gerbera  | 2024-12-25 10:58:31   info: Loading configuration from: /run/gerbera/config.xml
gerbera  | 2024-12-25 10:58:31   info: Parsing configuration...
gerbera  | 2024-12-25 10:58:31   info: Configuration load succeeded.
gerbera  | 2024-12-25 10:58:31  error: Logic error parsing config file '/var/run/gerbera/config.xml': stoi`

Tried removing the config.xml but even with the generated file the server failed to start.

I overlooked it was edge-transcoded.

**Comment by schafdog** [comment]
Went back to 2.3-transcoding and the config works again

**Comment by KarlStraussberger** [comment]
Could you find out which part of your config file did cause the error? Starting `gerbera --check-config --debug` may help to identify the problem.
