### ISSUE TITLE
CENTOS 7 Packaging

### ISSUE THREAD

**Issue by lukesoft76** [gerbera/gerbera#335]
Hello everybody,

i have packaged Gerbera 1.2.0 for CENTOS 7.
Using the Fedore29 SRPMS, i was able to make a rebuild for CENTOS 7.

Unfortunately, libUPNP, duktabe, taglib also need to get updated.

If someone is interested, please let me know.

Regards,
Lukesoft

**Comment by v00d00** [comment]
Hi @lukesoft76 

Have you got a repository set up at all for CENTOS 7 at all?

If so please open a PR for our [Install Docs](https://github.com/gerbera/gerbera/blob/master/doc/install.rst).

Thanks!

**Comment by lukesoft76** [comment]
Hi v00d00,

currently, i don't have a repository. Can you explain what a "PR" is?

Regards,
L.

**Comment by antenore** [comment]
@lukesoft76 just edit the page at https://github.com/gerbera/gerbera/edit/master/doc/install.rst and then click on the button "Propose File Change" with a meaningful comment. 
 
I think this way it's easier for you than anything else.

**Comment by lukesoft76** [comment]
Ok, pull request is stated!
Changes for install.rst have been commited.

**Comment by lukesoft76** [comment]
What's the next step?

**Comment by elmodaddyb** [comment]
I was trying to find a reputable 3rd party repository for CentOS but could not find one that matched up.
https://wiki.centos.org/AdditionalResources/Repositories
