### ISSUE TITLE
Cleanup Stale Documentation Files

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#340]
The centralization of documentation to `README.md` and to the [read-the-docs](http://docs.gerbera.io/en/latest/) means we can cleanup some of the old documentation.

* `doc/readme.lyx`
* `doc/doxygen.conf`
* `/README.old`

**Comment by elmodaddyb** [comment]
@v00d00 - Do you agree these files are redundant?

**Comment by v00d00** [comment]
I would keep the doxygen just in case, but the others can go.

You have done such an excellent job with the new docs :+1:
