### ISSUE TITLE
Invalid URL: -> UPnP Media Server for 2018 (Based on MediaTomb) https://gerbera.io

### ISSUE THREAD

**Issue by jacksnodgrass** [gerbera/gerbera#341]
gerbera.io from: 

UPnP Media Server for 2018 (Based on MediaTomb) https://gerbera.io

on the github gerbera/gerbera page does not map to an ip address. 

Makes one think that this project is dead. 

- jack

**Comment by elmodaddyb** [comment]
Related to https://github.com/gerbera/gerbera.io/issues/4

**Comment by v00d00** [comment]
Yeah, sorry, its on my todo list, but have been on holidays, will sort it this weekend!

**Comment by v00d00** [comment]
![Its Alive!](https://media.giphy.com/media/YEL7FJP6ed008/giphy.gif)


:tada: :tada:
