### ISSUE TITLE
Web UI Edit Item - Causes SIGSEGV when String is Empty with macOS Clang

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#343]
Hello,

I came across a strange **undefined behavior** on **Apple Clang 9.1.0.9020039**.  Any insight from more experienced C++ developers would be helpful.  It seems like I am missing a simple solution...

### Scenario
Compile Gerbera on Apple macOS, run the UI and attempt to edit a item that has an **empty** description field.  The overlay never loads...

### Behavior
The application will hang with a `EXC_BAD_ACCESS` and CPU will stay steady until the process is killed.

### Analysis

It looks like this line is **undefined behavior** in the C++ specification when the pointer is `NULL`.  This happens when the `zmm::String` has no value.

https://github.com/gerbera/gerbera/blob/master/src/zmm/strings.h#L244

A simple test in Apple macOS proves it is not Gerbera, but underlying c++ undefined behavior.(_or maybe just my compile flags??_)

```c++
#include "gtest/gtest.h"
#include <ostream>

TEST(SimpleTest, BadAccessInClang) {
  std::ostringstream buf;
  char* a = nullptr;
  buf << a;   // <------ EXC_BAD_ACCESS
  printf("Result ---> %s", buf.str().c_str());
}
```

> This undefined behavior works OK on Linux hosts (g++, etc)

Here are some references that lead me to think this is **UB** scenario.

https://stackoverflow.com/questions/7019454/why-does-stdcout-output-disappear-completely-after-null-is-sent-to-it

https://stackoverflow.com/questions/23283772/is-printing-a-null-pointer-undefined-behavior

> In the wilderness here with C++ 🌳 ⛺️

**Comment by elmodaddyb** [comment]
The below works, but seems rather barbaric 🍖 

from `strings.h`
```c++
template <typename T>
std::basic_ostream<T> &operator<<(std::basic_ostream<T> &oss, const zmm::String &s) {
  #if defined(__clang__)
    if(s != nullptr) oss << s.c_str();
  #else
    oss << s.c_str();
  #endif
    return oss;
}
```

Something more elegant is desirable... 🤔

**Comment by gburca** [comment]
Section **27.7.3.6.4 Character inserter function templates** of the C++14 standard says:

*Requires:* `s` shall not be a null pointer.

And `s` refers to the `char *` (and friends) argument of `basic_ostream ... operator<<(..., const char* s)`.

I'd recommend the equivalent of:

```c++
oss << (s.c_str() == nullptr ? "" : s.c_str());
```

with no conditional compilation. Just because it works on some platforms is no reason to rely on UB.

**Comment by elmodaddyb** [comment]
@gburca - Thank you for the insight....makes the approach clear.
:trophy:
