### ISSUE TITLE
libupnp8 in alternate directory

### ISSUE THREAD

**Issue by Menion2k** [gerbera/gerbera#345]
Hi
One of the reasons why even Ubuntu Bionic ships the libupnp6 is that for some weird reasons, they have changed some APIs, breaking the compatibility with a number of applications.
If we use the gerbera scripts for packaging it, the package overwrites the include files causing problem if someone attempts to compile other applications (old applications still run since the library filename are different).
A workaround is to avoid using the scripts and compile libupnp8 with another prefix (i.e /usr/libupnp8) and use the -DPC_UPNP_INCLUDEDIR -DPC_UPNP_LIBDIR to point to the custom directory

**Comment by v00d00** [comment]
Does it install a pkgconfig file also? It could just be a case of looking for some more names.

**Comment by Menion2k** [comment]
Whatever it is, the problem is that it overwrites the header file of libupnp on the distribution one (libupnp6) breaking all the compilation with applications using libupnp6.
They just cannot exist in the same directory

**Comment by v00d00** [comment]
When the pupnp 1.8 release was done, these files were named so as to not clash.

However the VLC guys complained it didn't make sense as code can handle either version, so it got reverted.

So now the libraries are slotted, but the headers etc are not.

In Gentoo we work around it ([ebuild here](https://gitweb.gentoo.org/repo/gentoo.git/diff/net-libs/libupnp/libupnp-1.8.3-r1.ebuild?id=c0b9e2e92c9549415dcb0e3a24f1b7804e398766)), so we could do something similar. But it feels a bit our of the Gerbera project scope.

**Comment by Menion2k** [comment]
Also my suggestion is a workaround. The original sin is the removal and modification of public API in libupnp

**Comment by v00d00** [comment]
True -- lets close this and we can point people to this issue if they run into the same thing.

If you are here from the future: we advise Debian users to install the `libupnp10` package instead of from source.
