### ISSUE TITLE
Document ffmpegthumbnailer cache-dir option

### ISSUE THREAD

**Issue by amak79** [gerbera/gerbera#347]
The ffmpegthumbnailer `cache-dir` [option](https://github.com/gerbera/gerbera/commit/5d7dd7a75072860480d2cea24cebf2a144a85b9e) is [undocumented](http://docs.gerbera.io/en/latest/config-extended.html#ffmpegthumbnailer). Please add a description for this option.

**Comment by v00d00** [comment]
Hi @amak79.

Perhaps you could make this change and open a pull request for this?
