### ISSUE TITLE
PPA Error: No Release file

### ISSUE THREAD

**Issue by kcthrn** [gerbera/gerbera#348]
**OS**: Ubuntu 16.04.5 (xenial)

I added `ppa:stephenczetty/gerbera-updates`, then did `sudo apt update` and got this error:
```
E: The repository 'http://ppa.launchpad.net/stephenczetty/gerbera-updates/ubuntu xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by v00d00** [comment]
@stephen-czetty Any comments?

**Comment by stephen-czetty** [comment]
I didn't do a package for xenial in that ppa.  It's a little more
complicated as it'll need backports for several dependencies.  I can give
it a shot at some point, maybe this weekend, but no promises.

-Steve

**Comment by v00d00** [comment]
Closing this one as @stephen-czetty is looking at it.

**Comment by lastonpl** [comment]
The same same for groovy (Ubuntu 20.10)
