### ISSUE TITLE
Want indicator for 'added item'

### ISSUE THREAD

**Issue by stheine** [gerbera/gerbera#357]
I'm currently looking at Gerbera 1.2.0.

When I'm in the FileSystem view, I would like to see any indication on what directories I have flagged by 'Add Item' or 'Add Autoscan Item'. Currently there is nothing.
What would happen if I would add a directory using 'Add Item' multiple times?
Is 'recursive' always set in 'Add Item'? In 'Add Autoscan Item' I'm asked if I want recursive or not.

**Comment by elmodaddyb** [comment]
This is a great feature idea.  Visibility of the added items would be helpful from the filesystem view.

#### To answer your other questions...

> What would happen if I would add a directory using 'Add Item' multiple times?

Gerbera finds the filesystem object in the virtual database and will not re-add multiple items.

> Is 'recursive' always set in 'Add Item'?

Yes --> [add.cc](https://github.com/gerbera/gerbera/blob/master/src/web/add.cc#L62)

> In 'Add Autoscan Item' I'm asked if I want recursive or not.

Yes, you can choose to be recursive here through the UI [web_autoscan.cc](https://github.com/gerbera/gerbera/blob/master/src/web/web_autoscan.cc#L116)

**Comment by stheine** [comment]
I just found this 'autoscan' indicator in the 'database/PC Directory' tree:
![image](https://user-images.githubusercontent.com/19614566/46579619-a7044900-ca15-11e8-8519-6602bf2c7338.png)

This clearly goes in the right direction. I just would love to see this in the filesystem tree as well.

**Comment by cweiske** [comment]
The file list also should show an indicator if the file is already known by Gerbera, not only the tree.

**Comment by KarlStraussberger** [comment]
Files are normally imported by autoscan, so if a file is missing it was deleted manually. On the other hand it is quite expensive with respect to calculation to check each file.

**Comment by KarlStraussberger** [comment]
I fully unserstand your issue but it means adding a feature that impacts runtime for rare situations which can also be solved by reimporting part of the files
