### ISSUE TITLE
How to configure the database tree layout?

### ISSUE THREAD

**Issue by stheine** [gerbera/gerbera#359]
In the database view, for 'Audio' there are Albums/ All - full name/ All Audio/ Artists/ Composers/ Genres/ Year.

But in 'Video' there is only All Video and Directories.

Assumed that I wanted a 'Directories' folder in 'Audio', what would be necessary to get that?

In 'Audio/Year/<year>' I get the list of songs. I would prefer to get the list of Albums from that year. Could I get that?

**Comment by elmodaddyb** [comment]
@stheine - The Gerbera system uses the Duktape API to run Javascript for importing items into the database library.  You should be able to modify the `import.js` script to suit that need.

1. Create a new **container chain** that represents your desired folder structure in the database view

> Perhaps something like below added to `addAudio(...)`

```javascript
function addAudio(obj) {
...
...
   // Let's assume  --->  obj.location = "/home/gerbera/myfile.mp3"

   var firstDirectory = obj.location.split('/')[1]  <-- choose the right index here...
   var chain = ['Audio', 'Directories', firstDirectory];
   addCdsObject(obj, createContainerChain(chain));
```

```
   // would create a structure of folders like:

   |---Audio
          |---Directories
                 |---home
                        |---myfile.mp3
```

The gerbera system includes all meta-data captured using **taglib** and also some of the file information....

> Take a look at [script.cc](https://github.com/gerbera/gerbera/blob/master/src/scripting/script.cc#L540) to see what other **object** attributes are added to the scripting runtime.
