### ISSUE TITLE
--cfgdir option

### ISSUE THREAD

**Issue by leviwheatcroft** [gerbera/gerbera#360]
running `gerbera -h` in v1.2.0 installed from the ubuntu ppa includes an option `--cfgdir` in it's output.

This option seems to be ignored, should it be removed from the output of `gerbera -h` ?

**Comment by Martii** [comment]
Hmmm ... was thinking about running two instances and that switch would be handy since Kodi has some odd ways of showing me my media... and to separate series from features media too.

**Comment by leviwheatcroft** [comment]
Well, it might have been a little presumptive of me to think that this should just be removed from the help output. It still get's parsed in main.cc, I just had a look to see where that option might be used in the code but c is just plain arcane to me.

**Comment by elmodaddyb** [comment]
@leviwheatcroft - Yes, it seems the option `--cfgdir` does not work by itself as an option.

You must configure both `--home` and `--cfgdir` together for it to concatenate properly.

```
$ gerbera --cfgdir .config/gerbera --home /home/gerbera 
```

Take a look at how [config_manager.cc](https://github.com/gerbera/gerbera/blob/master/src/config_manager.cc#L109) combines the 2 values.

When I [refactored to support configuration generator](https://github.com/gerbera/gerbera/commit/d8636c2bcaf2b8af72f80b3a61b871d251dba448#diff-b996f9888a37dfe2e68d0ee0da5193efL108), I neglected to notice this combination which is not easy to use as you mention.

When I run with _both_ options configured, it **does work**....however, running from latest master.

> Let me know if you have success with both options set?

**Comment by leviwheatcroft** [comment]
Can confirm running with both options does work. I don't actually have a use for this, I was trying to debug another issue and noticed that this seemed broken.
