### ISSUE TITLE
UI should indicate server <name>

### ISSUE THREAD

**Issue by stheine** [gerbera/gerbera#363]
I have multiple instances of gerbera running on my server, hosting different kinds of media (adult musik, childrens audio books, adult movies, childrens movies) to be able to select a specific library (listening to random music, not suddenly ending up in my daughter's audio books).
these are running on different [ports] just fine, and I have assigned a different [name] for each. so I can easily select the wanted library in the player.

I would love the UI indicate what [name] I have assigned to the current instance, so I don't get confused managing these different instances.

**Comment by elmodaddyb** [comment]
Hello @stheine - The system already supports a custom name via `config.xml` XPATH = `/server/name`

This is only leveraged for the UPNP display of the media-server.

> We could extend that configuration to the `title` of the UI?  What do you think?

**Comment by stheine** [comment]
sorry, in the original issue, I use &lt;/&gt; - but these got interpreted as html...

> The system already supports a custom name via config.xml XPATH = /server/name
> We could extend that configuration to the title of the UI? What do you think?

yes, I already set that XPATH - and yes, adding that to the title would be great.
I would love to have it in this header somewhere, because then it'd be visible always while the UI is open:
![image](https://user-images.githubusercontent.com/19614566/46585831-435e3800-ca76-11e8-8f3e-6ef689e11e18.png)

**Comment by elmodaddyb** [comment]
@stheine - Do you think overriding the title with a custom name is sufficient(_visible when hover_)?

> or should it be more prominent?

![image](https://user-images.githubusercontent.com/8599799/46900938-835b5b80-ce78-11e8-8bb7-b3979cd381b0.png)
Feedback welcome...

**Comment by v00d00** [comment]
Perhaps add the name in as title in the header next to the logo? Perhaps in brackets?

**Comment by elmodaddyb** [comment]
Ok will try a few different layouts and post back.

**Comment by Martii** [comment]
Titlebars may not always be shown, depending on the device accessing the pages, so in the UI might be helpful too.

**Comment by stheine** [comment]
This is how my brower looks currently, having three tabs with different gerbera instances open:
![image](https://user-images.githubusercontent.com/19614566/46918394-0512cc80-cfd2-11e8-8ab4-351848937d5d.png)
there is no indication of which one is which.

I mocked this a little by HTML modification in my browser:
![image](https://user-images.githubusercontent.com/19614566/46918441-a7cb4b00-cfd2-11e8-9812-412cad555b28.png)

I added the `name` into the `Home` link (and I don't care if it's part of the link or not, just to have it in the header somewhere).
I changed the html `<title>` to hold the instance name.
I even changed the title, truncating `Gerbera Media Server` down to `gerbera` to have more space available for the instance name. That might get important with more open tabs, and the browser might shrink them.
while typing this, I realize that the default user, running the default config, would have a title like `gerbera [gerbera]`, which looks a little weird as well... so you might want to display that instance name only of changed from the default.

while changing that I even realized that in the `<title>` you name it `Gerbera Media Server` and in the header line you name it `gerbera`, one it capitalized, the other one lower case, one has the `Media Server` suffix, the other one doesn't. you might want to clean out that inconsistency.


after all, this whole topic is not that important... it's only relevant, during the first few days/ weeks, for the few users who might set up multiple instances, until everything is set up and running - because then you'd be unlikely to often log into the ui.

**Comment by Martii** [comment]
> ... because then you'd be unlikely to often log into the ui.

A couple of things:

Firstly I'm using my distro's version of this so it's a little older on *gerbera* but until I get a chance to check all dependencies and do a major compile of the HEAD I'm stuck with the default. 

Secondly since I use Kodi as a front end for UPnP and it has some peculiarities with interacting with this previous version of *gerbera*. One being under Directories... new titles added with iNotify seem to only get added to the directories lists and bumps anything else out from an initial scan. Quite annoying and frustrating. So I usually get to view all sources which is horrendously large... hence why I eventually need to do instances to do a little pre-filtering.

Resulting for these particular versions quirks sometimes I have to log into the UI, dump the db and readd everything. Granted this may be fixed in a newer release but if it shows up in a newer release of *gerbera* I would still be needing to log into the UI. I haven't even had a moment of free time to set up multiple instance myself. :\ Just a few minutes here and there to type some sentences in this project with my 2 cents but I am watching on points that I need to eventually do. So I appreciate the insight. :)

**Comment by elmodaddyb** [comment]
> One being under Directories... new titles added with iNotify seem to only get added to the directories lists and bumps anything else out from an initial scan.

That sounds very frustrating...Thanks for all the feedback.  I will try iNotify testing in the future.

All thoughts and comments are valuable, whenever you can spare time!

**Comment by elmodaddyb** [comment]
Hello All,

Good news, this feature is done.  Here is a sample

![gerbera-friendly-name](https://user-images.githubusercontent.com/8599799/48036212-4b70cc80-e135-11e8-964d-bd9ab591c838.png)

I will write up a few tests for checks/balances and will have PR soon.

> Feedback Welcome!

Thanks,

Eamonn

**Comment by stheine** [comment]
looks good to me. thanks!

**Comment by v00d00** [comment]
> Hello,
> 
> I was able to get the front-end UI tested completely. Unfortunately, the server side is difficult to test due to **singleton** of `ConfigManager` and `SessionManager` used within the `IOHandler` implementations.
> 
> > The lifecycle of the unit test destroys memory references ahead of the dtors of the singletons...so `malloc` errors abound.
> 
> Any thoughts or ideas.... confused

This is why the singletons suck, to be honest we need to remove them entirely. But its no small task!

**Comment by elmodaddyb** [comment]
Yea, all the new code for streaming radio is *singleton* free 🆓  once I create a reasonable integration test for the server, it will be ready for PR.

**Comment by stheine** [comment]
thanks. I can confirm the fix!
