### ISSUE TITLE
UI shows duplicate folder structure in database while scanning/ adding files

### ISSUE THREAD

**Issue by stheine** [gerbera/gerbera#364]
I added files in the filesystem location that's added to the database. then I restart the gerbera server (I don't trust the timed autoscan yet to determine my changes automatically).

then I open the UI and open the database/Audio folder.

at the bottom of the screen, I see the 'Importing' statements coming in.

the database/Audio is flickering, updating the numbers (which is ok), and sometimes displays duplicate entries below (which is not ok):
![image](https://user-images.githubusercontent.com/19614566/46585686-13159a00-ca74-11e8-8813-bfaff029fc14.png)

**Comment by elmodaddyb** [comment]
@stheine - Thanks for reporting this issue.  The UI receives updates from the server, which consists  a list of **updated** IDs.  The UI then attempts to recurse upwards the tree to the highest parent, and then refresh that folder.

My guess is that this recursive refresh approach produces odd output when lots of IDs are being updated.

> Once the autoscan is complete, if you reload the UI, does it show proper tree hiearchy?

**Comment by stheine** [comment]
just a sidenote:

> then I restart the gerbera server (I don't trust the timed autoscan yet to determine my changes automatically).

I added more and gave gerbera the time to auto-detect them, and they automatically arrived. so the autoscan works fine!

**Comment by elmodaddyb** [comment]
I think I may have determined a possible root cause. 

When the system receives update IDs it **hides** the parent folder then appends the child tree elements. Then expands the parent. I don’t see where it removes the old child content. The ui just hides and appends then shows. 

https://github.com/gerbera/gerbera/blob/master/web/js/jquery.gerbera.tree.js#L113

I will see if I can write a fix where it clears the appropriate Updated id container instead. 

It is full TDD (~95% coverage) with selenium and jasmine specs if you want to have a go.

**Comment by elmodaddyb** [comment]
So, I tried this change and it appears to function as expected:

```javascript
collapse: function (element) { 
  element.children('span').first()
    .removeClass(this.options.config.openIcon)
    .addClass(this.options.config.closedIcon)
  // element.parent().find('ul.list-group').css('display', 'none')
  element.find('ul.list-group').remove()
},

```

https://github.com/gerbera/gerbera/blob/master/web/js/jquery.gerbera.tree.js#L113

However, facing some struggles running the specs to verify it doesnt break anything.  Will continue work on this soon.

**Comment by elmodaddyb** [comment]
Hello All,

Good News, this bug is fixed.  I also updated the nodejs test project to latest versions.  The latest versions revealed numerous gaps in async timing and mocking accuracy.  These too are fixed. 🛠

I plan to run the soak test for 1-2 days then submit the PR.

> @stheine thanks for all the detail, really made this bug an easy find/fix.

**Comment by elmodaddyb** [comment]
@v00d00 - Sorry for the delay on this.  I have the fix, but updating the NPM packages is going slower than expected.

I may try to just update the code to fix the issue...and leave the NPM updates for later.  I will try to post a PR later this week.

**Comment by elmodaddyb** [comment]
Hello All,

Sorry it took so long to get this fix into pull request.  A simple one-line change revealed numerous AJAX issues in the test suite, which I just recently found time to resolve. :hourglass_flowing_sand: :snail: 

Thanks for the patience with the issue.

- Eamonn

**Comment by stheine** [comment]
I updated gerbera to the latest trunk and the database view looks more stable now, even when indexing new data. thanks!
