### ISSUE TITLE
Tutorial - Gerbera + Google Drive and OneDrive support for live streaming directly

### ISSUE THREAD

**Issue by gabriellluz** [gerbera/gerbera#367]
Hi there.

I'm using Gerbera with rclone, which allows me to watch content directly from OneDrive or Google Drive. I didn't try with others, but 2 years ago I've used rclone with Amazon Drive and it used to work like a charm.
Below, you can find a tutorial. You can try that with Windows using WinFSP but it's not working for me even with a 35mb adsl connection. I'm afraid WinFSP is not working properly with rclone when using Windows.

In order to be better than the other DLNA servers, it'd be great if Gerbera could make a small wizard on the web ui so that it does all the rclone config automatically.

Ubuntu Server:
Installing rclone
curl https://rclone.org/install.sh | sudo bash

**Adding a cloud provider**
Open a terminal windows
Type:
`rclone config`

```
Current remotes:

Name                 Type
====                 ====

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> 
```

Type n to add a new cloud provider (Google Drive, OneDrive etc)

Now type the name. Choose a simple and non capitalized name (ie mygoogledrive instead of MyGoogleDrive)

`name>`

```
Type of storage to configure.
Choose a number from below, or type in your own value
 1 / Amazon Drive
   \ "amazon cloud drive"
 2 / Amazon S3 (also Dreamhost, Ceph, Minio)
   \ "s3"
 3 / Backblaze B2
   \ "b2"
 4 / Dropbox
   \ "dropbox"
 5 / Encrypt/Decrypt a remote
   \ "crypt"
 6 / Google Cloud Storage (this is not Google Drive)
   \ "google cloud storage"
 7 / Google Drive
   \ "drive"
 8 / Hubic
   \ "hubic"
 9 / Local Disk
   \ "local"
10 / Microsoft OneDrive
   \ "onedrive"
11 / Openstack Swift (Rackspace Cloud Files, Memset Memstore, OVH)
   \ "swift"
12 / SSH/SFTP Connection
   \ "sftp"
13 / Yandex Disk
   \ "yandex"
```

Type "drive" for Google Drive or "onedrive" for OneDrive.

Press ENTER. Do not type anything for client_id> and client_secret>

Next, press Y if you're running rclone on the same machine or not sure or N if you're running it through SSH/server/headless machine.

```
Remote config
Use auto config?
 * Say Y if not sure
 * Say N if you are working on a remote or headless machine or Y didn't work
y) Yes
n) No
y/n> 
```

If we type Y, a browser windows will open. If you're not logged to Google Drive or OneDrive, it will ask you to login. Now authorize Rclone to access your files.

> Success
> Go back to rclone to continue

```
Your authorization code.
y) Yes this is OK
e) Edit this remote
d) Delete this remote
y/e/d>
```

If it shows a fuzzy code as your authorization code, type y.
We're done.

_Mounting your Google Drive/OneDrive folder_

First, you have to create a folder so that we can see our Cloud's files inside that folder, so create a folder inside your home folder or anywhere you want.
I've created a folder called gabigoogledrive inside my home folder so I can use the command line below in a terminal:

Type:

> rclone mount mygoogledrive: /home/$USERNAME$/gabigoogledrive &

Note: replace $USERNAME$ with your name, let's say, "kevin" or "admin".
Now, it's simple. Open Gerbera UI and add your Google Drive or OneDrive folders.

If you want to make your linux distro to start rclone automatically you can create a cron job or a systemd service. I'd rather use a cron job with exactly the same line above.

**Troubleshooting**

_What if Gerbera can't see my folder?_
It's possible that Gerbera can't see a Cloud folder. All you have to do is add the  --allow-other option with the same command line:

> rclone mount mygoogledrive: /home/$USERNAME$/gabigoogledrive --allow-other &

Now you just have to add your mount folder to Gerbera.

**Comment by v00d00** [comment]
@gabriellluz This is great, perhaps you could make it into a page on the docs?

**Comment by gabriellluz** [comment]
Yes. But I don't know how to do it. I also don't know if the authors like the idea.
