### ISSUE TITLE
loading on arm fails

### ISSUE THREAD

**Issue by ausil** [gerbera/gerbera#375]
I am attempting to run gerbera on Fedora 29 for armhfp, I have tested the same version build for x86_64 and the interface loaded fine so it is related to arm. when i load the interface I get an error message that shows only { when loading with debugging enabled I saw "2018-11-20 01:51:17   DEBUG: [src/server.cc:421] create_request_handler(): Filename: /content/interface?req_type=auth&action=get_config, Path: (null)" when going to that url I get a json error in the browser "SyntaxError: JSON.parse: end of data while reading object contents at line 1 column 2 of the JSON data"  the rawdata shows as only { 

I would appreciate some help in debugging what is going wrong

**Comment by elmodaddyb** [comment]
@ausil - Can you verify which version of Gerbera your are running using `gerbera --compile-info`

I recently ran into a similar weirdness with string memory reference behavior on Apple Clang.

https://github.com/gerbera/gerbera/issues/343

In the issue #343, it was related to buffer concatenation `<<` of a `nullptr` value during the XML to JSON conversion.  In Linux works fine, but in Apple Clang results in very strict C++ specification **undefined behavior**.

> I wonder if your issue is something similar for ARM.

I do not have an ARM chip system so cannot debug, but perhaps debugging [xml_to_json.cc](https://github.com/gerbera/gerbera/blob/83ad73529fa5d8b261618b5792b9fc9517b2470c/src/mxml/xml_to_json.cc#L40), would reveal which element is failing to parse into JSON format.

I am only guessing but if you have a build prior to https://github.com/gerbera/gerbera/commit/60f70b108f874197a56e7a56aad7dc8c592e21d1 then likely this is similar issue.

**Comment by ausil** [comment]
gerbera --compile-info

Gerbera UPnP Server version 1.2.0 - http://gerbera.io/

===============================================================================
Gerbera is free software, covered by the GNU General Public License version 2

Copyright 2016-2018 Gerbera Contributors.
Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
===============================================================================
Compile info:
-------------
WITH_MAGIC=1
WITH_MYSQL=0
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=1
WITH_TAGLIB=1
WITH_AVCODEC=0
WITH_FFMPEGTHUMBNAILER=0
WITH_EXIF=1
WITH_EXIV2=1
WITH_PROTOCOL_EXTENSIONS=1
WITH_SYSTEMD=1
WITH_LASTFM=1
WITH_DEBUG=1
WITH_TESTS=0

**Comment by ausil** [comment]
i built from commit 31db8a1a23e36c99e4e54bcf7174cf0cf43c9d42 which is the current git head, it fails the same. I will try run in gdb and set some breakpoints to examine the variables

**Comment by v00d00** [comment]
Can you paste your full build log too?

**Comment by v00d00** [comment]
Build log looks fine. We picked up large file support as expected.

Did you build your own libupnp too? If so please try it with a 1.8.4 build, and check it also picks up LFS.

**Comment by ausil** [comment]
the fedora spec file for libupnp has 

%if 0%{?__isa_bits} == 32
  --disable-largefile \
%endif

so large file support is disabled. should I disable in gerbera or is there no good reason to disable it on 32 bit arches?

**Comment by ausil** [comment]
okay I rebuilt libupnp 1.8.3 with large file support and it is working. 1.8.4 bumped the soname so I did not go there yet. I did have to disable samples as it failed to build with 
`make[3]: Entering directory '/builddir/build/BUILD/libupnp-1.8.4/upnp/sample'
gcc -DHAVE_CONFIG_H -I. -I../.. -I../../upnp/inc  -I../../upnp/inc -I../../ixml/inc -I./common/ -I./tvcombo   -pthread -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -Os -c -o linux/tv_combo-tv_combo_main.o `test -f 'linux/tv_combo_main.c' || echo './'`linux/tv_combo_main.c
make[3]: Leaving directory '/builddir/build/BUILD/libupnp-1.8.4/upnp/sample'
In file included from ../../upnp/inc/upnp.h:402,
                 from ./common/sample_util.h:49,
                 from linux/tv_combo_main.c:32:
../../upnp/inc/FileInfo.h:22:2: error: #error libupnp uses large file support, so users must do that, too
 #error libupnp uses large file support, so users must do that, too
  ^~~~~
make[3]: *** [Makefile:584: linux/tv_combo-tv_combo_main.o] Error 1
make[3]: *** Waiting for unfinished jobs....`

which may be a bug in the Makefile that largefile support is not getting passed through,  however it makes me question if that should be changed, and if not should we also use an option on 32 bit arches of gerbera to disable large file support?

**Comment by v00d00** [comment]
You almost certainly want large file support, otherwise big files (think HD movies) will fail after 2GB.

**Comment by ausil** [comment]
@kwizart I am going to enable large file support on 32 bit arches to fix this. Do you have any objections?

**Comment by kwizart** [comment]
@ausil 
Seems like I've set this option while updating from 1.6.25 to 1.8.3, unfortunately I haven't put the reason of this at that time.
So if it's build (and run), it should be fine.

**Comment by ausil** [comment]
I think this issue can now be closed
