### ISSUE TITLE
Everything is Unknown

### ISSUE THREAD

**Issue by gaydenko** [gerbera/gerbera#377]
Hi! Under (Manjaro/AUR) Linux I have added to Gerbera 1.2.0 a directory tree with flac files. But afrer they were scanned it seems nothing metadata is recognized except for files as files themselves. Just look at the media library tree. Other servers I have tried recognize the flacs without problems. Autogenerated config is in use.
![gerbera01](https://user-images.githubusercontent.com/3740016/49109036-be83e380-f29a-11e8-8fdb-dcad41a81f9c.png)

**Comment by gaydenko** [comment]
Have found: I must add `<treat mimetype="audio/flac" as="flac"/>` to config.

**Comment by v00d00** [comment]
That should be in the default configuration? Where did your original config come from?
