### ISSUE TITLE
How to generate album with year

### ISSUE THREAD

**Issue by gaydenko** [gerbera/gerbera#381]
Hi! It seems album extracted form obj.meta is just an album title. I have tried to attach 'upnp:date' property to album (or obj) without any effect - client (BubbleUPnP) still doesn't get album's year. How to attach a year? This chain is in use:
```js
    chain = ['Audio', genre, artist, album];
    obj.title = title;
    addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ALBUM);
```

**Comment by elmodaddyb** [comment]
@gaydenko - There is an example of how the music gets parsed with `M_DATE` metadata field.

https://github.com/gerbera/gerbera/blob/master/scripts/js/import.js#L57

The `obj` is the virtual object that is saved into the Gerbera Database, and the `chain` is the folder hierarchy for the various containers (e.g. folders) displayed in the UPNP view.

**Comment by elmodaddyb** [comment]
If you are working through creation of a script the system binds a helpful `print` function where you can output the field values to the gerbera server system console.

https://github.com/gerbera/gerbera/blob/master/src/scripting/script.cc#L51

**Comment by gaydenko** [comment]
@elmodaddyb ,

> There is an example of how the music gets parsed with M_DATE metadata field

That `date` is used just for description rather for album container. But the problem has got another nature: client is expecting `upnp:date` attached to album.

**Comment by gaydenko** [comment]
I haven't touch C++ code during ages, but this code fragment seems to look strange:

https://github.com/gerbera/gerbera/blob/master/src/storage/sql_storage.cc#L956-L963

We define `metadata` ref pointing to `NULL`. Then it isn't used in the method. Then we create new `metadata` initialising it with new dictionary. And, again, is isn't used anywhere.

At least it isn't used to insert any album and date data.
Can anybody, please, explain?

**Comment by gaydenko** [comment]
I have look at database, and album object contains dc:date metadata. OTOH fetching DIDL-Lite info for a track contains `dc:date`, while for album it contains nothing date-related.

**Comment by elmodaddyb** [comment]
@gaydenko - Your help is much appreciated.  We recently added conductor and composer elements to the UPNP XML.  I wonder if we should also add `upnp:date`.  However, we would still need to sort out the storage issue you mentioned to guarantee the data is actually available to send out in XML.

**Comment by elmodaddyb** [comment]
I was able to get this working and rendering out the proper XML for the UPNP clients.

https://github.com/elmodaddyb/gerbera/commit/1ad24868cc7b44ebe83d7f77156ea5b0dc52e587

**Do you have any insight how this can be tested and validated?  What behavior is expected when rendering out `<upnp:date>`**

> Any insight would be a great help for testing it before the PR.

```xml
<u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
  <Result>
    <DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">
      <container id="12345" parentID="12344" restricted="1" childCount="11">
        <dc:title>-all-</dc:title>
        <upnp:class>object.container.person.musicArtist</upnp:class>
      </container>
      <container id="4567" parentID="3456" restricted="1" childCount="11">
        <dc:title>Container Title (2001)</dc:title>
        <upnp:class>object.container.album.musicAlbum</upnp:class>
        <dc:creator>Artist Creator</dc:creator>
        <upnp:composer>None</upnp:composer>
        <upnp:Conductor>None</upnp:Conductor>
        <upnp:orchestra>None</upnp:orchestra>
        <!-- NEWLY ADDED -->
        <upnp:date>2001-01-01</upnp:date>
        <!-- NEWLY ADDED -->
      </container>
    </DIDL-Lite>
  </Result>
  <NumberReturned>2</NumberReturned>
  <TotalMatches>2</TotalMatches>
  <UpdateID>0</UpdateID>
</u:BrowseResponse>
```

**Comment by gaydenko** [comment]
@elmodaddyb , unfortunately I'm useless here.

**Comment by gaydenko** [comment]
It has nothing with presenting album name. On entering albums list top bar got icon to sort albums. Tapping on the last one results in popup of radio check list with `Year Asc.` and `Year Desc.` items. Selecting one of them must result in an appropriate albums sorting.

**Comment by elmodaddyb** [comment]
@gaydenko - The changes I made seem to have fixed this issue, and I was able to sort the albums by `Year Asc.` and `Year Desc.`.

> Thanks for the insight.

I plan to rollback the change to confirm it truly solves the problem....then will post a PR.

Thanks,

Eamonn

**Comment by elmodaddyb** [comment]
Hello All, 

To confirm, I tested by reverting the `upnp:year` code.  It reproduces the issue discussed with BubbleUPNP.

> I will create a few tests and submit a PR to fix this issue soon.

Thanks,

Eamonn

**Comment by elmodaddyb** [comment]
Issue is fixed, merging latest upstream and should have a PR today!!

**Comment by gaydenko** [comment]
Probably I do something wrong, but I wasn't able to get it working, but have got core dump:
```
Dec 16 01:13:35 nas systemd-coredump[26390]: Process 26387 (gerbera) of user 987 dumped core.
                                             
                                             Stack trace of thread 26387:
                                             #0  0x00007f3051c58d7f raise (libc.so.6)
                                             #1  0x00007f3051c43672 abort (libc.so.6)
                                             #2  0x00007f3051e6e58e _ZN9__gnu_cxx27__verbose_terminate_handlerEv (li>
                                             #3  0x00007f3051e74dfa _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so>
                                             #4  0x00007f3051e74e57 _ZSt9terminatev (libstdc++.so.6)
                                             #5  0x00007f3051e750ac __cxa_throw (libstdc++.so.6)
                                             #6  0x00007f3051e73d08 __cxa_bad_cast (libstdc++.so.6)
                                             #7  0x00005654861e93ed n/a (gerbera)
                                             #8  0x00005654861e2014 n/a (gerbera)
                                             #9  0x00007f3051c45223 __libc_start_main (libc.so.6)
                                             #10 0x00005654861e6a3e n/a (gerbera)
Dec 16 01:13:35 nas audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=gerbera comm="system>
Dec 16 01:13:35 nas systemd[1]: gerbera.service: Failed with result 'core-dump'.
Dec 16 01:13:35 nas systemd[1]: gerbera.service: Main process exited, code=dumped, status=6/ABRT
Dec 16 01:13:34 nas audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@16>
Dec 16 01:13:34 nas systemd[1]: Started Process Core Dump (PID 26389/UID 0).
Dec 16 01:13:34 nas gerbera[26387]:   what():  std::bad_cast
Dec 16 01:13:34 nas gerbera[26387]: terminate called after throwing an instance of 'std::bad_cast'
```

**Comment by elmodaddyb** [comment]
@gaydenko - I think recent changes to the command line arguments has broken the options on the command line.

#394  is open and I am posting a fix for consideration.

> If you remove any command line options, it will workaround the current issue.

**Comment by gaydenko** [comment]
@elmodaddyb , thanks, I have subscribed that issue to be notified.

**Comment by gaydenko** [comment]
I was able to start current master tip, but still has problems. I have deleted `gerbera.db` forcing full rescan. Then I have looked at DIDL response with gupnp-av-cp - yes, now an album container contains `upnp:date` element, but it text value is `None`. So, probably some scanning issue takes place. The albums in test definitely contain needed meta tags: say, MPD uses them without any problems.

**Comment by elmodaddyb** [comment]
@gaydenko - The system requires a few things to work properly

1. The meta-data is added at scan time, so likely any existing items need to be rescanned
2. The `import` script used needs to set the [`obj.meta[M_UPNP_DATE]`](https://github.com/gerbera/gerbera/blob/master/scripts/js/import.js#L62) field based on the taglib date
3. The taglib date for the album actually comes from the previously scanned music track
   * So all items in the folder need the ID3 Tag = Year, for it to pick up on the container album

> When I received 'None' it was because the MP3 file truly did not have a **ID3 tag - Year** value.  I used [EasyTag](https://wiki.gnome.org/Apps/EasyTAG) to view all the files and apply the proper tagging.

**Comment by gaydenko** [comment]
@elmodaddyb , yes, after adding a year to meta all is OK, thanks!

**Comment by v00d00** [comment]
I guess we should we add the changes to the default import (non script) and the default js version?

**Comment by elmodaddyb** [comment]
Yes, it is added to the `import.js` and the `import-structured.js`

> I will submit PR to cover the `fallback_layout.cc`
