### ISSUE TITLE
no subtitles

### ISSUE THREAD

**Issue by alcsms** [gerbera/gerbera#390]
I have a LG 49UB8550 tv that accesses the Gerbera 1.2 server on UbuntuServer. The video runs without subtitles. Files with .srt extension have the same name as the .mkv file and I can not get the subtitles to appear. Using nero home essentials the subtitles appear but nero has to be in windows and I have a movie server in linux. Can anybody help me??

**Comment by bouwew** [comment]
I have seen this as well on my LG TV. When playing an mkv with embedded subs, these are shown. But not srt-files. 
I suppose this has nothing to do with Gerbera but more with the (limited) capabilities of the player on the TV.

**Comment by pczolee** [comment]
I have the same problem, but not just with lg tv, it in not working with vlc or kodi as well. So, I think there is some gerbera related problem, because for example with minidlna (readymedia) it is working.

**Comment by v00d00** [comment]
I'm not sure how happy you are with Wireshark, but it would be great to get network capture from a working server, so we can figure out what Gerbera is not sending.

A dump of the Gerbera traffic would be nice also

**Comment by pczolee** [comment]
Hello. Well, if you give me a small help (howto) use the wireshark, and how can I dump gerbera traffic, I will do it!
Thanks

**Comment by v00d00** [comment]
I think google could give a better guide than me on wireshark usage 😂

We would be looking for TCP traffic on the same port as Gerbera is using.

**Comment by elmodaddyb** [comment]
I checked this a while back regarding subtitles and found that Gerbera only adds the subtitles to video types when the Samsung TV header **hack** is enabled via configuration.  which i think limits its capability to only support Samsung TVs.

https://github.com/gerbera/gerbera/issues/104#issuecomment-367164148

via code...

https://github.com/gerbera/gerbera/blob/master/src/file_request_handler.cc#L220

> I don't think UPNP supports subtitles, Samsung does through their proprietary extension to DLNA. I wonder if minidlna is doing some magical transcoding of the SRT + video.

**Comment by pczolee** [comment]
Well, now with samsung hack enabled, the vlc working well! But the kodi is still not, and my lg tv isn't as well. The interesting thing is that with minidlna my lg tv understanding the srt and using it without any problem. In my opinion you should have a look how the minidlna doing this, and implement to gerbera...
Thanks

**Comment by v00d00** [comment]
Can you try it with a `1.3.1` build?

**Comment by bouwew** [comment]
I just upgraded to the most recent code on github: commit cffe7baac6f7d5694ec7c4bd7e3687d0a31e5a39.
I can confirm that the subtitles now work on my LG OLED55C7V 😄 

Thanks, great job!!

**Comment by v00d00** [comment]
![](https://media0.giphy.com/media/diUKszNTUghVe/giphy.gif)

**Comment by Neocazen** [comment]
Hello Whyman.
     External subtitles are not played on my LG TV. I have data from wireshark. Can you help me if possible?
[https://my.pcloud.com/publink/show?code=XZvk2skZ2iI5YERKhAjuI4QVQYsPVVASuuAk](url)

**Comment by zvargams** [comment]
Hello @whyman - reviving this older thread, as I finally managed to compile Gerbera for ARM, and tried to play a media with an external .srt sub. No luck. :( It does work fine with embedded subs (mkv), but the .srt is like it wasn't even there.

`Gerbera UPnP Server version 1.7.0_git - http://gerbera.io/

===============================================================================
Gerbera is free software, covered by the GNU General Public License version 2

Copyright 2016-2020 Gerbera Contributors.
Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
===============================================================================
Compile info
-------------
WITH_MAGIC=1
WITH_MYSQL=0
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=1
WITH_TAGLIB=1
WITH_AVCODEC=1
WITH_FFMPEGTHUMBNAILER=0
WITH_EXIF=1
WITH_EXIV2=0
WITH_PROTOCOL_EXTENSIONS=
WITH_SYSTEMD=1
WITH_LASTFM=0
WITH_DEBUG=1
WITH_TESTS=0

Git info:
-------------
Git Branch: refs/heads/master`

This shall be the latest and greatest version. Do you have an idea what to check to troubleshoot this issue? Thank you.

**Comment by KarlStraussberger** [comment]
In order to get subtitles recognised, you need add some lines to the `import` section of your configuration (e.g. after `autoscan`):
```
<resources>
  <subtitle>
    <add-file name="%filename%.srt"/>
  </subtitle>
  <resource>
    <add-file name="%filename%.srt"/>
  </resource>
</resources>
```
%filename% is replaced the the movie file name. Modify the pattern to your needs.

**Comment by zvargams** [comment]
Whoa, that was easy, thank you @KarlStraussberger ! :) 

I believe this is the beginning of a beautiful friendship - finally a DLNA server which makes external subs work! :)
