### ISSUE TITLE
Many Flac music files not being registered by autoscan. How best to debug?

### ISSUE THREAD

**Issue by incansvl** [gerbera/gerbera#401]
OS: Debian 10 Buster
DB: MariaDB 10.3.11
Gerbera: 1.1.0 (from Debian repo)

I have just installed Gerbera for the first time.

Having pointed a recursive autoscan at my music liibrary (roughly 3,500 tracks, 90%+ are FLAC) I realised that only a proportion of the tracks were being registered by Gerbera and made available in the metadata-based branches of the Database tree for UPNP players to see.

I.e. i can see my music tracks in the "PC Directory" branch, but only a few appear under Artist or Album categories.

I found a bug reported here indicating that the config file only has mappings for files of MIME type "audio/x-flac" (which is true), so I added copies of the relevant lines for the type "audio/flac" (which is what my system identifies them as) but this made no difference.

This is what i've found so far with some poking around:

1. The music tracks are being found by the system. Searching the database with-
`select count(*) from mt_cds_object where location like 'F/%';`
gives a count of 5532 files. (Note it doesn't seem to be possible to Remove or "Un-Add" folders from the scan list, so it's possible by now I have some folders being scanned multiple times).

2. I ran the server under debug and dumped the output into a log file, but I couldn't see any smoking guns there like file access errors.

3. Looking at one artist where I have 44 tracks (Anastacia) in the filesystem, but only one is picked up by Gerbera, i had a look at the database entries for the track that was registered, vs one that wasn't, and there's a big difference in the amount of metadata that has been stored:

```
select * from mt_cds_object where location like '%Left Outside%'\G
*************************** 1. row ***************************
           id: 74731
       ref_id: NULL
    parent_id: 48192
  object_type: 2
   upnp_class: object.item.audioItem.musicTrack
     dc_title: 02 - Left Outside Alone.flac
     location: F/share/music/Library/Anastacia/Anastacia/02 - Left Outside Alone.flac
location_hash: 1915074686
     metadata: dc%3Atitle=Left%20Outside%20Alone&upnp%3Aartist=Anastacia&upnp%3Aalbum=Anastacia&dc%3Adate=2004-01-01&upnp%3Agenre=Rock%2FPop&dc%3Adescription=Anastacia%2C%20the%20self-titled%20third%20album%20from%20the%20former%20wedding%20singer%20picks%20up%20where%20Freak%20of%20Nature%20left%20off%2C%20completing%20her%20transformation%20from%20disco-pop%20diva%20to%20full-on%20rock%20goddess%2E%20%22Seasons%20Change%22%20opens%20the%20album%20with%20a%20nu-metal%20guitar%20riff%20and%20pretty%20much%20sets%20the%20tone%20for%20the%20other%2011%20songs%2E%20Lead%20single%20%22Left%20Outside%20Alone%22%20demonstrates%20the%20diversity%20of%20Anastacia%27s%20voice%3A%20she%20starts%20off%20very%20pronounced%20in%20an%20Evanessence%20style%20before%20going%20back%20to%20her%20old%20self%2E%20Sadly%2C%20the%20vocals%20are%20more%20restrained%20than%20usual%2C%20with%20only%20a%20few%20songs%20showing%20off%20her%20range%2E%20The%20ballad%20%22Heavy%20on%20my%20Heart%22%20builds%20to%20some%20dynamic%20choruses%2C%20reminiscent%20of%20Joe%20Cocker%27s%20screaming%20rendition%20of%20%22With%20a%20Little%20Help%20from%20My%20Friends%22%20but%20the%20only%20time%20Anastacia%20really%20lets%20loose%20is%20on%20%22Sexy%20Single%22%2C%20where%20her%20distinctive%20nasal%20vibrato%20loosens%20up%20and%20puts%20a%20real%20feel%20into%20the%20music%2E%20It%27s%20a%20shame%20there%20are%20none%20of%20the%20funk%20or%20disco%20numbers%20that%20made%20her%20debut%20so%20explosive%20but%20with%20such%20a%20unique%20voice%2C%20Anastacia%20could%20sing%20anything%20and%20it%20would%20sound%20great%2E%20--David%20Trueman&upnp%3AoriginalTrackNumber=2&upnp%3Aartist%40role%5BAlbumArtist%5D=Anastacia
      auxdata: NULL
    resources: 0~protocolInfo=http-get%3A%2A%3Aaudio%2Fflac%3A%2A&size=27197114&bitrate=105649&duration=00%3A04%3A17%2E4&sampleFrequency=44100&nrAudioChannels=2&resolution=1000x1000~~|2~protocolInfo=http-get%3A%2A%3Aimage%2Fjpeg%3A%2A~rct=aa~
    update_id: 0
    mime_type: audio/flac
        flags: 1
 track_number: 2
   service_id: NULL
1 row in set (0.000 sec)

MariaDB [gerbera]> select * from mt_cds_object where location like '%Seasons Change%'\G
*************************** 1. row ***************************
           id: 48292
       ref_id: NULL
    parent_id: 48192
  object_type: 2
   upnp_class: object.item.audioItem.musicTrack
     dc_title: 01 - Seasons Change.flac
     location: F/share/music/Library/Anastacia/Anastacia/01 - Seasons Change.flac
location_hash: 4024251914
     metadata: upnp%3AoriginalTrackNumber=1
      auxdata: NULL
    resources: 0~protocolInfo=http-get%3A%2A%3Aaudio%2Fflac%3A%2A&size=29786366&duration=00%3A04%3A17%2E6&bitrate=115624&sampleFrequency=44100&nrAudioChannels=2&resolution=1000x1000~~
    update_id: 0
    mime_type: audio/flac
        flags: 1
 track_number: NULL
   service_id: NULL
1 row in set (0.023 sec)
```

This looks like a clue, if Gerbera can't read the track metadata it looks like it gives up trying to classify the file. The thing is, I use one application to rip, tag, and organise all my music (MediaMonkey on a Windows PC) and all the files in this album would have been ripped and tagged at the same time. They look identical in MediaMonkey as far as the metadata is concerned. The track-specific items vary of of course, but all the tracks ARE tagged.

'm happy to provide more info or do some more digging on this if someone can point me in the right direction as regards what information the devs might need to diagnose the problem.

Note i'm not really up to compiling + installing latest versions from source, which I understand might limit the options.

**Comment by elmodaddyb** [comment]
This is an interesting issue.  The metadata handler processes the ID3 tags for FLAC file in 2 phases.

### Populating from Taglib
1. Populate the generic tag data - [metadata_handler.h](https://github.com/gerbera/gerbera/blob/master/src/metadata_handler.h#L105)
2. Populate the auxdata tags defined in the `config.xml` via `/import/library-options/id3/auxdata`

> Based on your data it looks like the Generic Tags populated for both (**Option 1**)

Since `auxdata` is `NULL` I suspect that this is not configured at all.

### Import workflow
1. Extract `metadata` using taglib for a given CdsObject
2. Populate `metadata` into Duktape API (for scripting import)
3. Object manipulated via `import.js` (_assuming JSLayout_)
4. CdsObject re-parsed and imported into SqlStorage (_MariaDB in your case_)

### Troubleshooting Further
> This does not require compiling or code changes

1. Update `config.xml` and set the virtual layout import type to `js`
     ```xml
     <import hidden-files="no">
         <scripting script-charset="UTF-8">
           <common-script>/home/gerbera/scripts/js/common.js</common-script>
           <playlist-script>/home/gerbera/scripts/js/playlists.js</playlist-script>
           <virtual-layout type="js">   <!-- Change to js type -->
              <import-script>/home/gerbera/scripts/js/import.js</import-script>
           </virtual-layout>
         </scripting>
      </import>
     ```
2. Update the `import.js` script for `addAudio` function and print all the metadata that is getting found by **taglib**
     ```javascript
      for (var metaProp in obj.meta) {
         print('Property --->' + metaProp);
         print('Value ------>' + obj.meta[metaProp];
       }
     ```

This will tell whether the meta data is getting read by the system.  The last time we saw an error similar to this, it was due to some invalid CHARSET within the tag information.

Hope this gives you some guidance on how to proceed....

Thanks,

Eamonn

**Comment by v00d00** [comment]
The other thing to do would be to try a 1.2 or git version.

**Comment by incansvl** [comment]
Ok, I made the changes requested by **elmodaddyb**, ran the server, then added a folder containing 3 albums with a total of 48 tracks.

```
018-12-29 23:19:09    INFO: Gerbera UPnP Server version 1.1.0 - http://gerbera.io/
2018-12-29 23:19:09    INFO: ===============================================================================
2018-12-29 23:19:09    INFO: Gerbera is free software, covered by the GNU General Public License version 2
2018-12-29 23:19:09    INFO: Copyright 2016-2017 Gerbera Contributors.
2018-12-29 23:19:09    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2018-12-29 23:19:09    INFO: ===============================================================================
2018-12-29 23:19:09    INFO: Loading configuration from: /etc/gerbera/config.xml
2018-12-29 23:19:09    INFO: Checking configuration...
2018-12-29 23:19:09    INFO: Setting filesystem import charset to UTF-8
2018-12-29 23:19:09    INFO: Setting metadata import charset to UTF-8
2018-12-29 23:19:09    INFO: Setting playlist charset to UTF-8
2018-12-29 23:19:09 WARNING: You enabled the YouTube feature, which allows you
                             to watch YouTube videos on your UPnP device!
                             Please check http://www.youtube.com/t/terms
                             By using this feature you may be violating YouTube
                             service terms and conditions!

2018-12-29 23:19:09    INFO: Configuration check succeeded.
2018-12-29 23:19:09    INFO: Initialized port: 49152
2018-12-29 23:19:09    INFO: Server bound to: 192.168.0.40
2018-12-29 23:19:09    INFO: The Web UI can be reached by following this link: http://192.168.0.40:49152/
2018-12-29 23:19:51      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:51      JS:    Value: 6
2018-12-29 23:19:51      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:51      JS:    Value: 1
2018-12-29 23:19:51      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:51      JS:    Value: 2
2018-12-29 23:19:51      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:51      JS:    Value: 3
2018-12-29 23:19:51      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:51      JS:    Value: 4
2018-12-29 23:19:51      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:51      JS:    Value: 5
2018-12-29 23:19:51      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:51      JS:    Value: 7
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 8
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 9
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 10
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 11
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 12
2018-12-29 23:19:52      JS: Property: dc:title
2018-12-29 23:19:52      JS:    Value: Left Outside Alone
2018-12-29 23:19:52      JS: Property: upnp:artist
2018-12-29 23:19:52      JS:    Value: Anastacia
2018-12-29 23:19:52      JS: Property: upnp:album
2018-12-29 23:19:52      JS:    Value: Anastacia
2018-12-29 23:19:52      JS: Property: dc:date
2018-12-29 23:19:52      JS:    Value: 2004-01-01
2018-12-29 23:19:52      JS: Property: upnp:genre
2018-12-29 23:19:52      JS:    Value: Rock/Pop
2018-12-29 23:19:52      JS: Property: dc:description
2018-12-29 23:19:52      JS:    Value: Anastacia, the self-titled third album from the former wedding singer picks up where Freak of Nature left off, completing her transformation from disco-pop diva to full-on rock goddess. "Seasons Change" opens the album with a nu-metal guitar riff and pretty much sets the tone for the other 11 songs. Lead single "Left Outside Alone" demonstrates the diversity of Anastacia's voice: she starts off very pronounced in an Evanessence style before going back to her old self. Sadly, the vocals are more restrained than usual, with only a few songs showing off her range. The ballad "Heavy on my Heart" builds to some dynamic choruses, reminiscent of Joe Cocker's screaming rendition of "With a Little Help from My Friends" but the only time Anastacia really lets loose is on "Sexy Single", where her distinctive nasal vibrato loosens up and puts a real feel into the music. It's a shame there are none of the funk or disco numbers that made her debut so explosive but with such a unique voice, Anastacia could sing anything and it would sound great. --David Trueman
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 2
2018-12-29 23:19:52      JS: Property: upnp:artist@role[AlbumArtist]
2018-12-29 23:19:52      JS:    Value: Anastacia
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 3
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 4
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 5
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 6
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 7
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 8
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 9
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 10
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 11
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 12
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 1
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 1
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 2
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 3
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 4
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 5
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 6
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 7
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 8
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 9
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 10
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 11
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 12
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 14
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 16
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 17
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 18
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 19
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 20
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 13
2018-12-29 23:19:52      JS: Property: upnp:originalTrackNumber
2018-12-29 23:19:52      JS:    Value: 15
^C2018-12-29 23:20:27    INFO: Gerbera shutting down. Please wait...
2018-12-29 23:20:27    INFO: Gerbera exiting. Have a nice day.

As you can see, this indicates the tag information has not been read from 47 of the tracks, only one has a populated set of tags, which is very strange when, as noted before) each album would have been ripped and tagged in a single session using the same application (MediaMonkey).

I guess I we need to look at the tags in more detail to see what's going on. Is there a preferred tool to do this with (presumably a Linux native application to avoid linux<>Windows file format  and charset questions)?

I could probably post a couple of tracks somewhere so you could have a look, but (a) Flac files are quite big; and (b) I don't want to fall foul of copyright issues.
```

**Comment by incansvl** [comment]
Re:

> 1.     Populate the generic tag data - metadata_handler.h
> 2.     Populate the auxdata tags defined in the config.xml via /import/library-options/id3/auxdata

Questions-

1. Do you really mean Gerbera only reads ID3 tags?
2. My config.xml doesn't have any options for auxdata, should it? (the default template doesn't have any auxdata definitions).

I did some reading on tagging of FLAC files, and I gather the standard format for FLAC tags is to use Vorbis comments. ID3 (v1 and v2) tags are effectively "tolerated but foreign" content, FLAC decoders can choose whether to interpret them, but they should skip ID3 tag frames if they don't intend to use them.

I still haven't found a tagging tool that will tell me exactly what is in my file tags. I have been using MediaMonkey and Logitech Media Server (previously SlimServer), and just today I tried MP3tag on the PC. All of these tools show the "good" and "bad" files as being tagged equivalently, but all 3 explicitly say they support all 3 tag formats.

I'm guessing, but if my files MOSTLY use pure Vorbis comments (the officially supported format for FLAC), but the one "good" file happend to duplicate the same information in an ID3 tag, would this give the behaviour i'm seeing?, if no processing of auxdata had been defined?

If so, does that mean i have to hand-roll my own auxdata processsing spec for FLAC (Vorbis format) tags, then use these to populate the virtuial library?

**Comment by v00d00** [comment]
We support vorbis comments in FLAC.

You shouldn't need any auxdata configuration.

**Comment by v00d00** [comment]
If you are happy to, could you to mail me a couple of files? thev00d00 at gentoo dot org. Thanks!

**Comment by incansvl** [comment]
Thanks for the feedback. One concern though- I thought i'd already made this change (after reading the issue about x-flac vs. flac MIME types), so in theory I shouldn't still be seeing the problem.

Questions-

1. Does it matter whether the x-flac references remain in the config file?
2. Does it matter which order the two specs for FLAC file types (x-flac vs. flac) appear in (i.e. does one "treat" line override another)?
3. I note there is no file extension mapping rule for the _.flac_ extension. My guess would be the system would use the MIME type from the "file" command first, and only use the mappings defined in the config file as a fallback if the file command doesn't give a type, or maybe that is wrong, and we need a `<map>` rule in here?

My current config file is below (with a couple of key details obscured). This approach (adding a new entry for audio/flac underneath the corresponding one for audio/x-flac) seemed sensible, as it means I don't lose any existing configuration, but maybe I tripped over an effect where one line masks or overrides the other?

```
<?xml version="1.0" encoding="UTF-8"?>
<config version="2" xmlns="http://mediatomb.cc/config/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocatio
n="http://mediatomb.cc/config/2 http://mediatomb.cc/config/2.xsd">
  <!--
     See http://gerbera.io or read the docs for more
     information on creating and using config.xml configuration files.
    -->
  <server>
    <ui enabled="yes" show-tooltips="yes">
      <accounts enabled="yes" session-timeout="120">
        <account user="******" password="******"/>
      </accounts>
    </ui>
    <name>Gerbera [hostname]</name>
    <udn>uuid:769ad51a-c8c7-494a-b426-************</udn>
    <home>/var/lib/gerbera</home>
    <webroot>/usr/share/gerbera/web</webroot>
    <!--
        How frequently (in seconds) to send ssdp:alive advertisements.
        Minimum alive value accepted is: 62

        The advertisement will be sent every (A/2)-30 seconds,
        and will have a cache-control max-age of A where A is
        the value configured here. Ex: A value of 62 will result
        in an SSDP advertisement being sent every second.
    -->
    <alive>1800</alive>
    <storage>
      <sqlite3 enabled="no">
        <database-file>gerbera.db</database-file>
      </sqlite3>
      <mysql enabled="yes">
        <host>localhost</host>
        <username>gerbera</username>
        <database>gerbera</database>
      </mysql>
    </storage>
    <protocolInfo extend="no"/><!-- For PS3 support change to "yes" -->
    <!--
       Uncomment the lines below to get rid of jerky avi playback on the
       DSM320 or to enable subtitles support on the DSM units
    -->
    <!--
    <custom-http-headers>
      <add header="X-User-Agent: redsonic"/>
    </custom-http-headers>

    <manufacturerURL>redsonic.com</manufacturerURL>
    <modelNumber>105</modelNumber>
    -->
    <!-- Uncomment the line below if you have a Telegent TG100 -->
    <!--
       <upnp-string-limit>101</upnp-string-limit>
    -->
    <extended-runtime-options>
      <ffmpegthumbnailer enabled="no">
        <thumbnail-size>128</thumbnail-size>
        <seek-percentage>5</seek-percentage>
        <filmstrip-overlay>yes</filmstrip-overlay>
        <workaround-bugs>no</workaround-bugs>
      </ffmpegthumbnailer>
      <mark-played-items enabled="no" suppress-cds-updates="yes">
        <string mode="prepend">*</string>
        <mark>
          <content>video</content>
        </mark>
      </mark-played-items>
    </extended-runtime-options>
  </server>
  <import hidden-files="no">
    <scripting script-charset="UTF-8">
      <common-script>/usr/share/gerbera/js/common.js</common-script>
      <playlist-script>/usr/share/gerbera/js/playlists.js</playlist-script>
<!--  <virtual-layout type="builtin"> -->
      <virtual-layout type="js">
        <import-script>/usr/share/gerbera/js/import.js</import-script>
      </virtual-layout>
    </scripting>
    <mappings>
      <extension-mimetype ignore-unknown="no">
        <map from="mp3" to="audio/mpeg"/>
        <map from="ogx" to="application/ogg"/>
        <map from="ogv" to="video/ogg"/>
        <map from="oga" to="audio/ogg"/>
        <map from="ogg" to="audio/ogg"/>
        <map from="ogm" to="video/ogg"/>
        <map from="asf" to="video/x-ms-asf"/>
        <map from="asx" to="video/x-ms-asf"/>
        <map from="wma" to="audio/x-ms-wma"/>
        <map from="wax" to="audio/x-ms-wax"/>
        <map from="wmv" to="video/x-ms-wmv"/>
        <map from="wvx" to="video/x-ms-wvx"/>
        <map from="wm" to="video/x-ms-wm"/>
        <map from="wmx" to="video/x-ms-wmx"/>
        <map from="m3u" to="audio/x-mpegurl"/>
        <map from="pls" to="audio/x-scpls"/>
        <map from="flv" to="video/x-flv"/>
        <map from="mkv" to="video/x-matroska"/>
        <map from="mka" to="audio/x-matroska"/>
        <!-- Uncomment the line below for PS3 divx support -->
        <!-- <map from="avi" to="video/divx"/> -->
        <!-- Uncomment the line below for D-Link DSM / ZyXEL DMA-1000 -->
        <!-- <map from="avi" to="video/avi"/> -->
      </extension-mimetype>
      <mimetype-upnpclass>
        <map from="audio/*" to="object.item.audioItem.musicTrack"/>
        <map from="video/*" to="object.item.videoItem"/>
        <map from="image/*" to="object.item.imageItem"/>
        <map from="application/ogg" to="object.item.audioItem.musicTrack"/>
      </mimetype-upnpclass>
      <mimetype-contenttype>
        <treat mimetype="audio/mpeg" as="mp3"/>
        <treat mimetype="application/ogg" as="ogg"/>
        <treat mimetype="audio/ogg" as="ogg"/>
        <treat mimetype="audio/x-flac" as="flac"/>
        <treat mimetype="audio/flac" as="flac"/>
        <treat mimetype="audio/x-ms-wma" as="wma"/>
        <treat mimetype="audio/x-wavpack" as="wv"/>
        <treat mimetype="image/jpeg" as="jpg"/>
        <treat mimetype="audio/x-mpegurl" as="playlist"/>
        <treat mimetype="audio/x-scpls" as="playlist"/>
        <treat mimetype="audio/x-wav" as="pcm"/>
        <treat mimetype="audio/L16" as="pcm"/>
        <treat mimetype="video/x-msvideo" as="avi"/>
        <treat mimetype="video/mp4" as="mp4"/>
        <treat mimetype="audio/mp4" as="mp4"/>
        <treat mimetype="video/x-matroska" as="mkv"/>
        <treat mimetype="audio/x-matroska" as="mka"/>
      </mimetype-contenttype>
    </mappings>
    <online-content>
      <YouTube enabled="no" refresh="28800" update-at-start="no" purge-after="604800" racy-content="exclude" format="mp4" hd="no
">
        <favorites user="gerbera"/>
        <standardfeed feed="most_viewed" time-range="today"/>
        <playlists user="gerbera"/>
        <uploads user="gerbera"/>
        <standardfeed feed="recently_featured" time-range="today"/>
      </YouTube>
    </online-content>
  </import>
  <transcoding enabled="no">
    <mimetype-profile-mappings>
      <transcode mimetype="video/x-flv" using="vlcmpeg"/>
      <transcode mimetype="application/ogg" using="vlcmpeg"/>
      <transcode mimetype="application/ogg" using="oggflac2raw"/>
      <transcode mimetype="audio/x-flac" using="oggflac2raw"/>
      <transcode mimetype="audio/flac" using="oggflac2raw"/>
    </mimetype-profile-mappings>
    <profiles>
      <profile name="oggflac2raw" enabled="no" type="external">
        <mimetype>audio/L16</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>no</accept-ogg-theora>
        <agent command="ogg123" arguments="-d raw -o byteorder:big -f %out %in"/>
        <buffer size="1048576" chunk-size="131072" fill-size="262144"/>
      </profile>
      <profile name="vlcmpeg" enabled="no" type="external">
        <mimetype>video/mpeg</mimetype>
        <accept-url>yes</accept-url>
        <first-resource>yes</first-resource>
        <accept-ogg-theora>yes</accept-ogg-theora>
        <agent command="vlc" arguments="-I dummy %in --sout #transcode{venc=ffmpeg,vcodec=mp2v,vb=4096,fps=25,aenc=ffmpeg,acodec
=mpga,ab=192,samplerate=44100,channels=2}:standard{access=file,mux=ps,dst=%out} vlc:quit"/>
        <buffer size="14400000" chunk-size="512000" fill-size="120000"/>
      </profile>
    </profiles>
  </transcoding>
</config>
```

**Comment by v00d00** [comment]
>     Does it matter whether the x-flac references remain in the config file?
No, they do not conflict.

>     Does it matter which order the two specs for FLAC file types (x-flac vs. flac) appear in (i.e. does one "treat" line override another)?
No, they are individual mappings.

>     I note there is no file extension mapping rule for the .flac extension. My guess would be the system would use the MIME type from the "file" command first, and only use the mappings defined in the config file as a fallback if the file command doesn't give a type, or maybe that is wrong, and we need a <map> rule in here?
Your thinking is correct, and it looks like mime type detection is failing, so this was going to be my suggestion if the initial change didn't work.

**Comment by incansvl** [comment]
Success!

Adding a `<map>` rule for the .flac extension finally got things working. I can now look into writing some custom indexing rules, Maybe partially replicating the SlimServer/Logitech Media Server index structure i'm familiar with, which is what I was hoping to do in the first place.

Thanks for your help in resolving this.

**Comment by incansvl** [comment]
I ran some db queries that selected random sets of "bad" tracks (ones where the metadata doesn't read) and noticed a possible pattern-

In the first set of 10 randomly selected bad tracks, 4 had track names containing either an apostrophe (') or a double quote (").

I haven't proved it yet, but it looks to me as if there could be a character set issue. I'm suspicious these characters have not been encoded in either vanilla ASCII or UTF-8 (I assume some Windows-specific code set could be in use given that the files were ripped and tagged on a PC).

This would align with the comment by **elmodaddyb** above about charset issues.

Now, i'm fairly certain MediaMonkey uses MS Access as its internal database, and from what i've read Access uses UTF-8 as the internal charset by default, so i'm not clear how a non-UTF-8 charset would be getting into the mix.

However, if this is the case, it woudl be surprising if i was the only user seeing this. As an English speaker, only a small proportion of my music or podcast files have non- ASCII accented characters in the filename, but for users in other European or asian countries this would be the norm.

**Comment by v00d00** [comment]
I think more likely we have an SQL escaping problem. Both " and ' are ascii characters so should be fine from an encoding perspective for ascii, latin-1 or utf8.

As an interesting test could you try the same but with a sqlite dB?

**Comment by incansvl** [comment]
I ran the scan/import with SQLlite as the d/b, and confirmed that it does pick up all the items, so this confirms your suspicion that it's a MySQL/MariaDB interface problem.

I tweaked the Gerbera import script to export some debugging info into Excel, which I have sent to Ian. What I see so far is-

1. There are a tiny number of files with "non-ASCII" characters in the title (where i'm crudely defining "non-ASCII" to mean characters with a char code <32 (decimal) or >255). Some of these words are accented european names etc., however there are only 6 or 7 of those, which can't explain the thousands of files that fail the import under MySQL.
2. There is no obvious "trigger" that causes a file to fail to import. Quite a few names containing apostrophes fail, but many others also fail that have plain (and sometimes quite short) file names.
3. You will also see several tracks succeeding and others failing within the same album folder. Combine this with the fact that the import works under SQLlite, and I think we can rule out anything like permissions problems on the music library folders/files.
4. Re-running the import doesn't change the outcome, so it's deterministic (i.e. not a performance-related timing issue).

(Excel report file provided via email)

**Comment by v00d00** [comment]
I tried to reproduce this your original sample set with a mysql back-end DB but couldn't manage to do so :-1:

**Comment by incansvl** [comment]
I assume there is something different between our two configs. My guess is you're running a recent dev build of gerbera?

I wonder if there's any point comparing the rest of the setup in detail, or do I need to try and install something close to the same version you are running?

**Comment by v00d00** [comment]
Yes I was testing with the latest git build, and it would be great if you could try it on that also, as there is a fair chance it will fix it.

**Comment by brandoninvergo** [comment]
I'm also having this problem. I'm finding that the metadata for a number of the flac files is not being read, causing them all to be lumped into the "Unknown" category (i.e. they're added to the database but with no metadata they are not being properly organized).

Digging into it using `metaflac`, I have identified a difference between working and non-working examples. All of the working examples have `minimum blocksize` and `maximum blocksize` values of 4096. All of the non-working examples have a different value (4608). According to the [flac spec](https://xiph.org/flac/documentation_format_overview.html), this can be between 2-6k samples, but 4096 is the default. According to the man page for the `flac` command, 4608 is a valid value.

The 4608 blocksize was added by the [soundconverter](https://soundconverter.org) program, and it doesn't appear to be configurable. As a test, I created a new flac file from one of the original wav files using the reference `flac` commandline program, which applies the default blocksize of 4096. I tagged the new flac file as usual using kid3, added it to my gerbera music directory and voila, the file metadata was correctly recognized.

So, it appears that Gerbera is hard-coded to look for flac blocksizes of 4096 and not any of the other valid values (see man flac(1)).

**Comment by brandoninvergo** [comment]
Nevermind, scratch that. To be complete, I used `flac` to encode a new flac file with a blocksize of 4608 from the original wav. Gerbera is able to recognize this.

It appears that `soundconverter` is doing something when it encodes flac files that Gerbera doesn't like. The annoying thing is that if I use `flac` to re-encode the files created by `soundconverter`, Gerbera still doesn't recognize them. I need to create new files from the wav files themselves.

**Comment by KarlStraussberger** [comment]
Another contribution to this issue: #2477
