### ISSUE TITLE
Convert client-side code to ES6 standards

### ISSUE THREAD

**Issue by elmodaddyb** [gerbera/gerbera#404]
Similar to #326 and #299 - Update the client-side `/web/js/gerbera*.js` code base to use ES6 standard.

* Include new features like `const` and `let`
* Use **arrow** notation for cleaner code
* Use semi-colon ending lines

http://es6-features.org

**Comment by v00d00** [comment]
Yay semicolons!

**Comment by v00d00** [comment]
What is browser support for ES6 like?

**Comment by elmodaddyb** [comment]
It looks like all the major browsers support the ES6 features

https://kangax.github.io/compat-table/es6/

**Comment by elmodaddyb** [comment]
I started this conversion and it is going well.  I upgraded to bootstrap 4, so need to work out some overlay bugs, but progress is steady.

**Comment by Martii** [comment]
> I upgraded to bootstrap 4

Good luck and look forward to it. We tried this several times with our existing popovers right aligned and it still doesn't work in all browsers. Granted it's another dependency now but still. :smile_cat:

**Comment by elmodaddyb** [comment]
I completed the conversion of all the *gerbera* javascripts to ES6 Modules.  Still some remaining cleanup work, but the primary objective is complete and working!! 🎉 

> We can run the old code along-side new modules using `<script nomodule ... >` feature which will make the update backwards compatible for some time.

**Comment by elmodaddyb** [comment]
All the Unit & E2E tests are running green.  There is some `async` consistency issues with the test suites that still needs cleaned up.

> I was able to leverage webpack during test runtime which consolidates a lot of ad-hoc behavior throughout the test suite.  Webpack supports loading JSON, along with `karma-fixtures` allows for cleaner use of mock & fixture data.

**Comment by elmodaddyb** [comment]
This story is complete.  I was able to make the system run with both ES6 module support and classic `nomodule` support.  This results in duplicate code base, but allows the integration of ES6 modules without risk to the runtime, should it NOT support ES6 modules.  We can decide to eliminate the *classic* mode after some time...

> All recent browsers support ES6 modules.
https://caniuse.com/#search=module

**Comment by v00d00** [comment]
I wouldn't bother worrying about the older browsers if it's going to create duplicate code.

**Comment by elmodaddyb** [comment]
I will run the app for a few days, doing a bunch of UI operations, to confirm everything is stable.

> Integration Suite, E2E, Unit tests all PASS :shipit:

**Comment by elmodaddyb** [comment]
Everything appears to be operational.  I plan to do some light documentation an diagrams and will submit a PR for this update!

> It is quite a large PR, as all UI code is restructured (_behavior is still the same_)

**Comment by elmodaddyb** [comment]
Everything is done here, I have merged latest master and all is well.

> The PR has `65 files changed` so I hope it is not too much risk at one time.

Should we stage the PRs in smaller chunks, or go for it all in one?

**Comment by v00d00** [comment]
Either is fine in my view, smaller ones may be easier to understand, but probably not worth the hassle unless its easy to do.

**Comment by elmodaddyb** [comment]
I will try to do an incremental delivery and see how it goes.

**Comment by v00d00** [comment]
@elmodaddyb is this ready to merge?

**Comment by elmodaddyb** [comment]
@v00d00 - I submitted PR #472 - I tried to separate the implementation conversion, but support for ES6 modules within ES5 requires a transpiler to be used, like browserify.

Its a doozy of a PR!! 📦 Your patience is appreciated.

**Comment by cweiske** [comment]
Now that #472 is merged, can this be closed?
