### ISSUE TITLE
Build error - today (30/12/018)

### ISSUE THREAD

**Issue by bouwew** [gerbera/gerbera#405]
Hi,

I noticed several updates since my last visit.
I git-pulled the updates, updated pupnp and cmake to newer versions on my system (headless Debian, up-to-date) and then started Cmake and make -j4. This happens:

`system:~/gerbera/build$ cmake ../../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_LASTFM=1
-- Looking for BSD native UUID
-- Looking for libuuid
-- Looking for libuuid - found
-- Found Sqlite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Looking for native inotify
-- Looking for native inotify - found
-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib/x86_64-linux-gnu
-- MySQL client libraries: /usr/lib/x86_64-linux-gnu/libmysqlclient_r.so
-- Found TagLib: -L/usr/local/lib -ltag
-- Found LASTFMLIB: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/bouwew/gerbera/build
system:~/gerbera/build$ make -j4
Scanning dependencies of target libgerbera
[  4%] Building CXX object CMakeFiles/libgerbera.dir/src/autoscan.cc.o
[  4%] Building CXX object CMakeFiles/libgerbera.dir/src/atrailers_service.cc.o
[  4%] Building CXX object CMakeFiles/libgerbera.dir/src/atrailers_content_handler.cc.o
[  4%] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
In file included from /home/bouwew/gerbera/src/zmm/zmm.h:37:0,
                 from /home/bouwew/gerbera/src/zmm/zmmf.h:35,
                 from /home/bouwew/gerbera/src/exceptions.h:35,
                 from /home/bouwew/gerbera/src/singleton.h:35,
                 from /home/bouwew/gerbera/src/timer.h:35,
                 from /home/bouwew/gerbera/src/autoscan.h:36,
                 from /home/bouwew/gerbera/src/autoscan.cc:32:
/home/bouwew/gerbera/src/zmm/strings.h:35:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.
CMakeFiles/libgerbera.dir/build.make:134: recipe for target 'CMakeFiles/libgerbera.dir/src/autoscan.cc.o' failed
make[2]: *** [CMakeFiles/libgerbera.dir/src/autoscan.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/bouwew/gerbera/src/zmm/zmm.h:37:0,
                 from /home/bouwew/gerbera/src/zmm/zmmf.h:35,
                 from /home/bouwew/gerbera/src/mxml/mxml.h:35,
                 from /home/bouwew/gerbera/src/atrailers_service.h:38,
                 from /home/bouwew/gerbera/src/atrailers_service.cc:34:
/home/bouwew/gerbera/src/zmm/strings.h:35:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.
CMakeFiles/libgerbera.dir/build.make:110: recipe for target 'CMakeFiles/libgerbera.dir/src/atrailers_service.cc.o' failed
make[2]: *** [CMakeFiles/libgerbera.dir/src/atrailers_service.cc.o] Error 1
In file included from /home/bouwew/gerbera/src/zmm/zmm.h:37:0,
                 from /home/bouwew/gerbera/src/zmm/zmmf.h:35,
                 from /home/bouwew/gerbera/src/exceptions.h:35,
                 from /home/bouwew/gerbera/src/common.h:36,
                 from /home/bouwew/gerbera/src/cds_resource.h:35,
                 from /home/bouwew/gerbera/src/cds_objects.h:37,
                 from /home/bouwew/gerbera/src/atrailers_content_handler.h:43,
                 from /home/bouwew/gerbera/src/atrailers_content_handler.cc:35:
/home/bouwew/gerbera/src/zmm/strings.h:35:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.
CMakeFiles/libgerbera.dir/build.make:86: recipe for target 'CMakeFiles/libgerbera.dir/src/atrailers_content_handler.cc.o' failed
make[2]: *** [CMakeFiles/libgerbera.dir/src/atrailers_content_handler.cc.o] Error 1
In file included from /home/bouwew/gerbera/src/zmm/zmm.h:37:0,
                 from /home/bouwew/gerbera/src/zmm/zmmf.h:35,
                 from /home/bouwew/gerbera/src/exceptions.h:35,
                 from /home/bouwew/gerbera/src/common.h:36,
                 from /home/bouwew/gerbera/src/action_request.h:38,
                 from /home/bouwew/gerbera/src/action_request.cc:32:
/home/bouwew/gerbera/src/zmm/strings.h:35:20: fatal error: optional: No such file or directory
 #include <optional>
                    ^
compilation terminated.
CMakeFiles/libgerbera.dir/build.make:62: recipe for target 'CMakeFiles/libgerbera.dir/src/action_request.cc.o' failed
make[2]: *** [CMakeFiles/libgerbera.dir/src/action_request.cc.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/libgerbera.dir/all' failed
make[1]: *** [CMakeFiles/libgerbera.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

Am I doing something wrong? Or is this a bug in the code?

**Comment by v00d00** [comment]
@elmodaddyb is right. That said I thought CMake should bail in this case, so we should check that.

**Comment by bouwew** [comment]
This is what my system says:
`system:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18+deb9u1' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1)
`

**Comment by bouwew** [comment]
I read some info online, saying:
You can use command-line flag -std to explicitly specify the C++ standard. For example,

-std=c++14, or -std=gnu++14 (C++14 with GNU extensions), default mode for GCC 6.1 and above.
-std=c++17, or -std=gnu++17 (C++17 with GNU extensions), experimental.

No idea though how to get this to work, though. Need to search some more...

**Comment by v00d00** [comment]
You will need ≥=gcc7

**Comment by bouwew** [comment]
Thanks for your guidance.

I have upgraded gcc to: gcc version 8.2.0 (Debian 8.2.0-13) and rebooted the VM.

Unfortunately, the errors are still there.

**Comment by bouwew** [comment]
Cmake shows this:
-- The C compiler identification is GNU 8.2.0
-- The CXX compiler identification is GNU 6.3.0

I guess the CXX-line is the culprit? Should I install/upgrade another package? Which one?

**Comment by cweiske** [comment]
I also had the error
```
CMake Error at CMakeLists.txt:294 (message):
  gerbera requires C++17 Optional to be available.  Check your compiler is
  >=GCC 7.1 or >=libc++ 5
```

And after emptying the build directory is was gone.
