### ISSUE TITLE
Playlist entries missing album name and artist

### ISSUE THREAD

**Issue by grb43** [gerbera/gerbera#406]
My uPnP clients (e.g. TV, VLC) don't display the album name or artist when playing playlists with local audio entries.

They display when the files are played individually. And the album name and artist are displayed when the same playlists are served by MiniDLNA or Ampache.

Looking back I can see this was raised indirectly at Issue #31, and a new function, getCdsObject, was added to the playlist parser  (Commit 0182b60...). The intention was that getCdsObject enabled a playlist.js script to access an audio object's metadata to add it to the database; similar to the way import.js handles new audio objects.

To date, getCdsObject doesn't appear to have been documented and the playlist.js script hasn't been modified to allow it to fully populate the database.

Could this be added as enhancement? It would help to round out an otherwise great application.

**Comment by elmodaddyb** [comment]
Hello @grb43 

#413 is merged via 7b10cb7d9bb0144ddba70c6ec59af4a915149aa6 to `origin/master`.

> Does `copyObject` and `getCdsObject` support address this issue?  I tested OK with sample playlist, but would like your confirmation regarding the issue.

Thanks,

Eamonn

**Comment by grb43** [comment]
Hi @elmodaddyb 
Compiled and ran latest.
Tests
   -  New playlists (100 mp3) of files already in database. Result: all metadata available.
   -  New playlists (20 files) of files not in database. Result: files added to database and metadata available.

So all looks fine
Thank you
Graeme

**Comment by elmodaddyb** [comment]
@grb43. That is great news. Thanks again for the great work!!
