### ISSUE TITLE
Gerbera not installing via apt Ubuntu 16.0.4 LTS x86_64

### ISSUE THREAD

**Issue by kevdagoat** [gerbera/gerbera#412]
I have successfully installed Gerbera on my old media server but the time has come to update it with a newer machine, which resulted in issues.

I followed [this](http://docs.gerbera.io/en/latest/install.html) guide to install gerbera, but it errors out saying:
```root@xxx:/home/xxx# apt-get install gerbera
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gerbera : Depends: libjs-bootstrap (>= 3.3.7) but it is not going to be installed
           Depends: libjs-jquery (>= 3.1) but 1.11.3+dfsg-4 is to be installed
           Depends: libjs-jquery-ui (>= 1.12.1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
apt-add-repository and apt update work fine:
```add-apt-repository ppa:stephenczetty/gerbera-updates
 If you previously used the old PPA, you're going to want to remove all the related packages from your system.
 More info: https://launchpad.net/~stephenczetty/+archive/ubuntu/gerbera-updates
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpehw93i1j/secring.gpg' created
gpg: keyring `/tmp/tmpehw93i1j/pubring.gpg' created
gpg: requesting key 828C83D0 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpehw93i1j/trustdb.gpg: trustdb created
gpg: key 828C83D0: public key "Launchpad PPA for Stephen Czetty" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
```
apt update:
```Hit:1 http://archive.canonical.com/ubuntu xenial InRelease
Hit:2 http://ppa.launchpad.net/deluge-team/ppa/ubuntu xenial InRelease
Hit:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:4 http://ppa.launchpad.net/stephenczetty/gerbera-updates/ubuntu xenial InRelease
Hit:5 http://au.archive.ubuntu.com/ubuntu xenial InRelease
Hit:6 http://au.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:7 http://au.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:8 https://packages.gitlab.com/gitlab/gitlab-ee/ubuntu xenial InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
```

MediaTomb installs fine.

**Comment by v00d00** [comment]
@elmodaddyb Ubuntu 16.04 only has versions: `libjs-bootstrap 3.3.6` `libjs-jquery 1.11.3` `libjs-jquery-ui 1.10.1
`

Is that good enough for the UI? Or does @stephen-czetty need to package them?

**Comment by elmodaddyb** [comment]
Gerbera has the following

Jquery 3.2.1
Jquery ui 1.12.1
Bootstrap 4.0.0-beta

These are packaged within gerbera, so I am not sure how this package works if it is installing them as dependencies.

**Comment by stephen-czetty** [comment]
I didn't really test the xenial back port, but I'm surprised the package
manager allowed it with invalid dependencies.

I'll try to take a look at it tonight or tomorrow.

-Steve

**Comment by kevdagoat** [comment]
Thanks :)

**Comment by kevdagoat** [comment]
Was just wondering about this. How is it going :) 

Is there any alternate method i can use to install (like build from source)?

And are there any guides for setting up transcode on the fly??

**Comment by stephen-czetty** [comment]
So it's finally fixed.  I did, indeed, have to provide updated versions of jquery, jquery-ui, and bootstrap.  Hopefully, they won't break anything else in xenial proper.  Use at your own risk. :)

**Comment by kevdagoat** [comment]
Thanks again guys! All working.

Btw, love the new web interface layout!!!
![image](https://user-images.githubusercontent.com/42062334/51716171-bbc52500-2076-11e9-8d75-f37be9a251ba.png)
