### ISSUE TITLE
What is the gerbera server called in a client like Rhythmbox?

### ISSUE THREAD

**Issue by dln949** [gerbera/gerbera#414]
I have the gerbera server running on one machine.  In the config file for the "name" tag I have the default of "Gerbera".  

On another machine I am running Rhythmbox 3.4.2.  In Rhythmbox, what will the gerbera server be called?  I assmed "Gerbera".  I am seeing entries in Rhythmbox, but I do not see anything called "Gerbera".  I have attached a screenshot to show the (useless) names I am seeing in Rhythmbox.  

Is there some additional setup I need to do in clients - like Rhythmbox - to have the gerbera server listed?  

![screenshot from 2019-01-13 12-00-29](https://user-images.githubusercontent.com/8601150/51088960-aae9ea80-172b-11e9-83fd-19e3055e3c51.png)

**Comment by v00d00** [comment]
It would be "Gerbera" by default.

Can you find the server on any other clients?

**Comment by dln949** [comment]
> It would be "Gerbera" by default.
> 
> Can you find the server on any other clients?

Yes I do, and it is called "Gerbera"  

So, should I conclude there is something about how gerbera and Rhythmbox work - or don't work - together?

**Comment by v00d00** [comment]
I've never used Rhythmbox as a client. But if it's working with another client, it suggests that Rhythmbox is having a problem. Perhaps it needs a plugin or something.
