### ISSUE TITLE
Cant start service

### ISSUE THREAD

**Issue by inkoqnito** [gerbera/gerbera#415]
Hello,
I cant get gerbera to work, i have an config in /etc/gerbera/config.xml and its owned by the user gerbera. But when i try to start the service i get the following error message:
```

● gerbera.service - Gerbera Media Server
   Loaded: loaded (/usr/lib/systemd/system/gerbera.service; enabled; vendor preset:>
   Active: activating (auto-restart) (Result: exit-code) since Fri 2019-01-18 18:16>
  Process: 22502 ExecStart=/usr/bin/gerbera --cfgdir etc (code=exited, status=1/FAI>
 Main PID: 22502 (code=exited, status=1/FAILURE)
```

And if i tries to start it in terminal with gerbera -c /etc/gerbera/config.xml  it seems to launch but i cant see no link to the webui? i get:

```
2019-01-18 18:19:23    INFO: Gerbera UPnP Server version 1.2.0 - http://gerbera.io/
2019-01-18 18:19:23    INFO: ===============================================================================
2019-01-18 18:19:23    INFO: Gerbera is free software, covered by the GNU General Public License version 2
2019-01-18 18:19:23    INFO: Copyright 2016-2018 Gerbera Contributors.
2019-01-18 18:19:23    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2019-01-18 18:19:23    INFO: ===============================================================================
2019-01-18 18:19:23    INFO: Loading configuration from: /etc/gerbera/config.xml
2019-01-18 18:19:23    INFO: Checking configuration...
2019-01-18 18:19:23    INFO: Setting filesystem import charset to UTF-8
2019-01-18 18:19:23    INFO: Setting metadata import charset to UTF-8
2019-01-18 18:19:23    INFO: Setting playlist charset to UTF-8
2019-01-18 18:19:23    INFO: Configuration check succeeded.
```

I earlier tried to use gerbera and that time i worked flawlessly but this time around it seems like i have forgotten somthing?

/Isak

**Comment by elmodaddyb** [comment]
Yea, this is not informative message, but I think you should verify that gerbera user has read/write permission to th `<home>` location specified in `config.xml`

> we could probably improve the messaging here.

**Comment by inkoqnito** [comment]
I made sure that the /home/inkoqnito/gerbera is owned by gerbera.

```
<name>Gerbera</name>
      <udn>uuid:0befb851-c73a-4327-80ed-2fc7b142778e</udn>
      <home>/home/inkoqnito/.config/gerbera</home>
      <webroot>/usr/share/gerbera/web</webroot>
```

`ownership of '/home/inkoqnito/.config/gerbera' retained as gerbera:gerbera`


What i can see so is the home owned by user gerbera, i dont know what i am missing? is it the webroot that could be the problem? and i also see that /usr/bin/gerbera seems to cause an error?

**Comment by elmodaddyb** [comment]
You could get more details by trying to launch gerber as the **gerbera** user and with debug turned on:

```
$ su gerbera
$ /usr/bin/gerbera -c /home/inkognito/.config/gerbera/config.xml --debug
```

**Comment by etiennemo** [comment]
:+1: exactly the same issue,  logs are stopping at the line:
 staticThreadProc(): Sqlite3Storage::staticThreadProc - exiting thread

My process is stuck and I have to kill it

**Comment by elmodaddyb** [comment]
I think the root of this issue has to do with access to the directory tree which holds the configuration....I am thinking it might be best to store the configuration in a common location like `/usr/local/share/gerbera`  but need to investigate how to create the DB in a standards way, etc.

> Any ideas?

**Comment by xcom169** [comment]
I think this is because of the gerbera system user

**Comment by Neocazen** [comment]
Good evening
     I am having this same problem. (version gerbera 1.5 Ubuntu 19.10)
     Compiled installation does not generate gerbera.db, gerbera.html.
     I changed the path to / var / lib / gerbera where I already had the file and it is working, however, not to not restart if given command by the terminal. Having to restart the computer
     How to solve?

**Comment by Neocazen** [comment]
Good evening...
 Some solution for that. I have the same problem in version 1.5. Gerbera is not generating 'gerbera.db or gerbera.html'. If the '~ / .config / gerbera' folder is mine, install .db and .html but, auto scanning leaves my series out of their respective folders.

**Comment by whorfin** [comment]
Somewhere between v1.4.0ish and now, path handling has changed.
I used to run `gerbera ... -m /home -f gerbera`, and that would result in config files read from and database generated in `/home/gerbera`.  With this current version, gerbera was trying to generate the database and the `gerbera.html` files in `/home`.  And obviously failing.  The failure looked just like yours:
```
2019-01-19 23:26:31   DEBUG: [src/storage/sqlite3/sqlite3_storage.cc:273] staticThreadProc(): Sqlite3Storage::staticThreadProc - exiting thread
```
with gerbera then hanging hard and requiring a `kill -9`.

changing to `gerbera ... -m /home/gerbera -f .` solved the problem

It would have been helpful had gerbera warned of the access failure in `/home` for the database.  It does warn of trouble with `gerbera.html` if it makes it that far.

Hope this can help someone.

**Comment by KarlStraussberger** [comment]
Outdated
