### ISSUE TITLE
how to change the interface

### ISSUE THREAD

**Issue by shanggdlk** [gerbera/gerbera#419]
Hi, all,

I want to change the default Ethernet card settings from eth0 to a wireless card (enp1s0). I check online and find there are some hints: sudo vim /etc/default/gerbera, and change the INTERFACE accordingly. 

However, I check this file and did not find any variable called INTERFACE. There is only one variable called EXTRAARGS. Could you point out how to make it?

Thanks!

**Comment by v00d00** [comment]
Hi @shanggdlk 

You can set in the [server section of your `config.xml`](
http://docs.gerbera.io/en/latest/config-server.html?highlight=interface#interface)

Alternatively the option you are looking for is `-e enp1s0` or  `--interface enp1s0`.

The method of getting your init system to give those to gerbera varies per distro though. But I would imagine adding it to `EXTRAARGS` may well work

**Comment by shanggdlk** [comment]
Thank you, @v00d00 . I did not find the folder gerbera in ~/.config. For the third method you mentioned, does it mean EXTRAARGS = "enp1s0" in /etc/default/gerbera? Thank you!

**Comment by v00d00** [comment]
Your config file is likely /etc/gerbera/config.xml

As I mentioned EXTRAARGS is distro specific so I am not certain. That said it's probably the entire --interface eth0 you want
