### ISSUE TITLE
How to import TXXX:fieldname id3 auxdata tags

### ISSUE THREAD

**Issue by ghlupe2** [gerbera/gerbera#421]
In [ID3v2.4](url)  TXXX:fieldname is used for "user defined text information" like

> TXXX:SCRIPT
> TXXX:Writer
> TXXX:CATALOGNUMBER
> TXXX:BARCODE
> TXXX:MusicBrainz Album Type
> TXXX:MusicBrainz Album Release Country

My config.xml defines some of these:
```
    <library-options>
      <id3>
         <auxdata>
            <add-data tag="TXXX:MusicBrainz Album Release Country"/>
            <add-data tag="TXXX:MusicBrainz Album Type"/>
            <add-data tag="TXXX"/>
         </auxdata>
      </id3>
    </library-options>
```
Both TXXX:MusicBrainz fields get ignored and the TXXX line randomly picks the TXXX:SCRIPT field (see attached debug log):
> JS: TXXX--->[SCRIPT] SCRIPT Latn

Some years ago when using MediaTomb I applied [this patch](https://sourceforge.net/p/mediatomb/discussion/440751/thread/7c616a73/#794d) manually and it did the trick. Unfortunately I have no clue how to use modern software development tools, so any help will be highly appreciated.

[ghlupe2_debug.log](https://github.com/gerbera/gerbera/files/2791955/ghlupe2_debug.log)

**Comment by v00d00** [comment]
As delayed update, thank you for the MP3 file. I will update the issue once I get time to look into it.

**Comment by v00d00** [comment]
I've found the problem (we only ever look at the first frame in the list). But wont be able to work on it as my house is getting renovated so my desk is out of action for a week or two...

**Comment by ghlupe2** [comment]
Thanks for the update and good luck with the renovation!
