### ISSUE TITLE
Gerbera installation stays at configuration check succeeded

### ISSUE THREAD

**Issue by mailforsachin** [gerbera/gerbera#427]
I have followed the install [guide](http://docs.gerbera.io/en/latest/install.html)  to install gerbera and then used the generate [configuration](http://docs.gerbera.io/en/latest/config-generate.html#generateconfig) to generate the configuration file.

When I run the command

gerbera -c /etc/gerbera/config.xml

I get the following message 

xx@xx:/etc/systemd/system$ gerbera -c /etc/gerbera/config.xml
2019-02-23 14:11:36    INFO: Gerbera UPnP Server version 1.2.0 - http://gerbera.io/
2019-02-23 14:11:36    INFO: ===============================================================================
2019-02-23 14:11:36    INFO: Gerbera is free software, covered by the GNU General Public License version 2
2019-02-23 14:11:36    INFO: Copyright 2016-2018 Gerbera Contributors.
2019-02-23 14:11:36    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2019-02-23 14:11:36    INFO: ===============================================================================
2019-02-23 14:11:36    INFO: Loading configuration from: /etc/gerbera/config.xml
2019-02-23 14:11:36    INFO: Checking configuration...
2019-02-23 14:11:36    INFO: Setting filesystem import charset to UTF-8
2019-02-23 14:11:36    INFO: Setting metadata import charset to UTF-8
2019-02-23 14:11:36    INFO: Setting playlist charset to UTF-8
2019-02-23 14:11:36    INFO: **Configuration check succeeded.**

and it stops there. What may I have missed? I followed the instructions accurately.

My machine specification is as below

Operating System: Ubuntu 18.04.2 LTS
            Kernel: Linux 4.15.0-45-generic
      Architecture: x86-64

Some troubleshooting

xx@xx:/etc/systemd/system$ which gerbera
/usr/bin/gerbera
xx@xx:/etc/systemd/system$ sudo vi gerbera.service
xx@xx:/etc/systemd/system$  sudo systemctl daemon-reload
xx@xx:/etc/systemd/system$ systemctl start gerbera
xx@xx:/etc/systemd/system$ systemctl status gerbera
● gerbera.service - Gerbera Media Server
   Loaded: loaded (/etc/systemd/system/gerbera.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2019-02-23 14:23:54 IST; 3s ago
  Process: 18141 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml (code=exited, status=1/FAILURE)
 Main PID: 18141 (code=exited, status=1/FAILURE)
xx@xx:/etc/systemd/system$ /usr/bin/gerbera -c /etc/gerbera/config.xml
2019-02-23 14:24:11    INFO: Gerbera UPnP Server version 1.2.0 - http://gerbera.io/
2019-02-23 14:24:11    INFO: ===============================================================================
2019-02-23 14:24:11    INFO: Gerbera is free software, covered by the GNU General Public License version 2
2019-02-23 14:24:11    INFO: Copyright 2016-2018 Gerbera Contributors.
2019-02-23 14:24:11    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2019-02-23 14:24:11    INFO: ===============================================================================
2019-02-23 14:24:11    INFO: Loading configuration from: /etc/gerbera/config.xml
2019-02-23 14:24:11    INFO: Checking configuration...
2019-02-23 14:24:11    INFO: Setting filesystem import charset to UTF-8
2019-02-23 14:24:11    INFO: Setting metadata import charset to UTF-8
2019-02-23 14:24:11    INFO: Setting playlist charset to UTF-8
2019-02-23 14:24:11    INFO: **Configuration check succeeded.**

I was on Mediatomb before and when I got the Ubuntu upgrade from 16.x to 18.x, Mediatomb vanished(No more maintained as you are already aware). 

The document says we can su as gerbera but by default it is not allowing if you follow the instructions.
I had to change the below to allow shell login
gerbera:x:121:129:Gerbera Media Server,,,:/var/lib/gerbera:**/bin/bash**

Here is the config permissions(777)
-rwxrwxrwx 1 gerbera gerbera 6746 Feb 23 13:57 /etc/gerbera/config.xml 

Installing gerbera from Ubuntu software redirects me to page that says disabled.html

Please assist.

**Comment by elmodaddyb** [comment]
In the config.xml, verify the `home` location is readable/writeable by the gerbera account.

**Comment by mailforsachin** [comment]
Thanks 777 resolved the issue but I am still getting it difficult to set it as a daemon.

Things I have tried.


mysuer@myuser:~/.config$ sudo systemctl daemon-reload
mysuer@myuser:~/.config$ sudo systemctl start gerbera
mysuer@myuser:~/.config$ sudo systemctl status gerbera
● gerbera.service - Gerbera Media Server
   Loaded: loaded (/etc/systemd/system/gerbera.service; enabled; vendor preset: 
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-02-24 19
  Process: 4238 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml (code=exit
 Main PID: 4238 (code=exited, status=1/FAILURE)
lines 1-5/5 (END)
mysuer@myuser~/.config$ sudo systemctl enable gerbera
Synchronizing state of gerbera.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable gerbera
Removed /etc/systemd/system/multi-user.target.wants/gerbera.service.
Created symlink /etc/systemd/system/multi-user.target.wants/gerbera.service → /etc/systemd/system/gerbera.service.
mysuer@myuser:~/.config$ sudo systemctl status gerbera
● gerbera.service - Gerbera Media Server
   Loaded: loaded (/etc/systemd/system/gerbera.service; enabled; vendor preset: 
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-02-24 19
  Process: 4326 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml (code=exit
 Main PID: 4326 (code=exited, status=1/FAILURE)


sudo vi /etc/systemd/system/gerbera.service is as below

[Unit]
Description=Gerbera Media Server
After=network.target

[Service]
Type=simple
User=gerbera
Group=gerbera
ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
~                                                                               
~          
**-rwxrwxrwx 1 root root  235 Feb 24 19:25  gerbera.service**

**Comment by elmodaddyb** [comment]
Can you try adding the long list option to systemctl to show more details?
```
$ systemctl status gerbera.service --full
```

If that does not provide details perhaps the logging journal will have some details:

_View the logging journal for the system unit._
```
$ journalctl -u gerbera.service
```

**Comment by mailforsachin** [comment]
I see errorno 130

Feb 25 08:22:32 myuser systemd[1]: gerbera.service: Service hold-off time over, scheduling restart.
Feb 25 08:22:32 myuser systemd[1]: gerbera.service: Scheduled restart job, restart counter is at 8913.
Feb 25 08:22:32 myuser systemd[1]: Stopped Gerbera Media Server.
Feb 25 08:22:32 myuser systemd[1]: Started Gerbera Media Server.
Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32    INFO: Gerbera UPnP Server version 1.2.0 - http://gerbera.io/
Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32    INFO: ===============================================================================
Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32    INFO: Gerbera is free software, covered by the GNU General Public License version 2
Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32    INFO: Copyright 2016-2018 Gerbera Contributors.
Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32    INFO: ===============================================================================
Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32    INFO: Loading configuration from: /etc/gerbera/config.xml
Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32    INFO: Checking configuration...
**Feb 25 08:22:32 myuser gerbera[20943]: 2019-02-25 08:22:32   ERROR: Permission denied: /home/myuser/.config/gerbera (errno: 130)**
Feb 25 08:22:32 myuser systemd[1]: gerbera.service: Main process exited, code=exited, status=1/FAILURE
Feb 25 08:22:32 myuser systemd[1]: gerbera.service: Failed with result 'exit-code'.
**myuser@myuser:~/.config/gerbera$ ls -ld /home/myuser/.config/gerbera 
drwxrwxrwx 2 gerbera gerbera 4096 Feb 25 08:15 /home/myuser/.config/gerbera**
myuser@myuser:~/.config/gerbera$ 
myuser@myuser:~/.config/gerbera$ ls -ld  /etc/gerbera/config.xml
**-rwxrwxrwx 1 gerbera gerbera 6746 Feb 23 13:57 /etc/gerbera/config.xml**
myuser@myuser:~/.config/gerbera$

**Comment by KarlStraussberger** [comment]
Outdated
