### ISSUE TITLE
How to compile gerbera with versionsort?

### ISSUE THREAD

**Issue by cafaia** [gerbera/gerbera#431]
Hello everyone!

The Gerbera program when organizing my files it sorts the files in alphabetical order, but I'd like it organized in versionsort, how to do it?

Thanks!

**Comment by v00d00** [comment]
Hey,

Im not sure this is supported? How would we implement it?

**Comment by cafaia** [comment]
Hey,

I also do not know if there is this feature, I believe we have to have this in source code:

scandir (container, &namelist, 0, alphasort)

We have to have the 'scandir' function, but I did not find it...
With best regards!

**Comment by cweiske** [comment]
Where in gerbera are they shown in the wrong way?

**Comment by cafaia** [comment]
The files are displayed incorrectly on my device because I don't use virtual folders.

**Comment by cweiske** [comment]
I still do not understand where the files appear in a list.
Do they appear in the gerbera web interface? Please post a screenshot showing the problem.
Which configuration did you make to disable virtual folders?

**Comment by cafaia** [comment]
I will send images of how the music files appear when numbered like this 1,2,3,...,10,11...
![screen](https://github.com/user-attachments/assets/dcc5f6b5-55de-4a96-9f58-00120adcf966)
![WhatsApp Image 2024-08-14 at 15 23 46](https://github.com/user-attachments/assets/6f6413b6-f75a-44bb-a935-2f930fd6e9b8)

I disabled virtual folders with this setting (/etc/gerbera/config.xml):

      <virtual-layout type="disabled">
        <import-script>/usr/share/gerbera/js/import.js</import-script>
      </virtual-layout>

**Comment by cweiske** [comment]
Ok, so this is about listings in the "PC directory". Thank you for the clarification.

**Comment by KarlStraussberger** [comment]
Sorting is done in quite generic on the database layer which is relying on indexes for speed. The versionsort can be achieved with `order by cast(title as integer), title` breaking speed and generic coding. Also it only works if the number is at the beginning. I simply updated my files with `foobar2000` renaming `number(%track%,3)` (or so).

On the other side you may create a simple layout script which keeps the filesystem hierarchy and adds the digits where required. The hide the pc directory and enjoy.

**Comment by KarlStraussberger** [comment]
Virtual layout also brings in album container which sort by track numbers as per definition.

**Comment by cafaia** [comment]
Hello KarlStraussberger!

Thank you very much for the clarifications and suggestions, I really appreciate it!

I have this on another media server, where I compiled by versionsort and not by alphasort:

![WhatsApp Image 2024-08-14 at 15 50 45](https://github.com/user-attachments/assets/f97023db-c3d8-4ed2-b873-c56e911b3f86)

**Comment by cweiske** [comment]
Ok, can we close this issue now?
The PC directory lists files in alphabetical order, which will not be changed.
If you want different handling, write your own virtual directory import script and disable the PC directory.

**Comment by KarlStraussberger** [comment]
The best solution I can think of is, that we create folders as albums if there is some sort of configuration active: As soon as there is one file in it, it becomes an album - also for the PC Directory. I remember some similar discussion.

**Comment by KarlStraussberger** [comment]
#3186 Automatically sets the container type to album depending on the items in it
