### ISSUE TITLE
CURL error when compiling on Debian Stretch

### ISSUE THREAD

**Issue by bouwew** [gerbera/gerbera#432]
I tried to upgrade just now. When issuing the CMAKE-command, I get this error:

```
CMake Error at /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.13/Modules/FindCURL.cmake:74 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:449 (find_package)
```

"which CURL" gives nothing, "which curl" gives "/usr/bin/curl"

Also, before this, I had to upgrade CMAKE, as the version was too low. This installed libcurl4 so I had to upgrade CURL as well. Both via "-t testing" as the versions in Debian Stretch are too old.

**Comment by v00d00** [comment]
Hi,

Which version of Gerbera are you trying to build?

**Comment by bouwew** [comment]
Latest version that was on github 5 day ago.
I just do a "git pull" and then perform a rebuild.

**Comment by bouwew** [comment]
Never mind, I solved it after some determined googling. Several dependencies were missing after installing curl from Debian testing.
