### ISSUE TITLE
"The system encountered an error" - SEGFAULT

### ISSUE THREAD

**Issue by ksoviero** [gerbera/gerbera#435]
I installed version 1.2 from the official PPA, but I've run into a bit of a show stopper. When I try to start the service with the default config: https://gist.github.com/ksoviero/53ecda981c0c9778ccd7ce384874c318

I get the error "The system encountered an error" at the bottom of the UI, and then the server immediately segfaults: https://gist.github.com/ksoviero/05c3de060271ee2b4dfc7610010ab2bf

Same error, but with debug output enabled: https://gist.github.com/ksoviero/d85fc70a22a8e090fce6297deb591666

**Comment by elmodaddyb** [comment]
SEGFAULT is pretty hard to determine.  Do you have any details *what* you were doing at the time it faulted?

I have encountered a few seg-faults, and only be able to find it by getting a backtrace using gdb.

https://www.gnu.org/software/gcc/bugs/segfault.html

**Comment by v00d00** [comment]
@ksoviero any news on getting a backtrace?

**Comment by damanbaird** [comment]
this happened to me too restarted a couple of times just to see if it changed.

**Comment by elmodaddyb** [comment]
@damanbaird - can you run with `--debug` to perhaps reveal any details on what is happening at the time of the segfault?

**Comment by whyman** [comment]
This was likely due to the borked libupnp version.
