### ISSUE TITLE
Enable pause and forward feature again

### ISSUE THREAD

**Issue by cafaia** [gerbera/gerbera#444]
Hello everyone!

I use Gentoo and in ebuild 9999 I put this:

EGIT_COMMIT="4cfe60d9212fe353027e68e3d46efc0d998a8cef"

Because this commit has two very good features: pause and forward on my blu ray-player sony.
I saw that these features no longer exist, would you put them back again?

Thanks!

**Comment by cafaia** [comment]
Correcting my mistake above: these features do not exist in the version of gerbera-1.3.0-r1 in Gentoo, but they exist in the live version (9999).

**Comment by v00d00** [comment]
Hi @cafaia Can you pinpoint more which commit caused you this issue? That commit looks pretty unrelated.

I'm also still not entirely sure what you mean by this.

**Comment by cafaia** [comment]
Hi @v00d00 I ran several tests and identified the commit without the ability to fast forward, pause, rewind, and stop in my blu ray-player:

- c7a81fb41e446ee67b3eac90e2caecd6de651a16: I do not have the resources;
- 36a31c9e5b0a94f0af8189ed374c625d59653468: I do not have the resources;
- 20ff8eb7a9a8ec89748fface1db04dd26902573e: I have the resources.

With the program of this commit I can forward, rewind, pause and stop the music on my blu ray-player sony.

**Comment by v00d00** [comment]
So https://github.com/gerbera/gerbera/commit/20ff8eb7a9a8ec89748fface1db04dd26902573e fixed it?  And does it work for you with the most recent commit?

**Comment by cafaia** [comment]
Yes, the commit 20ff8eb7a9a8ec89748fface1db04dd26902573e fixed it. I tested the commit 7e9f4e1988ca91b921767b14d25d09c4b865cf00 and it works for me too. But I've seen that some commits have and others do not have this feature, because I use the live version I see that these features come and go.

**Comment by cafaia** [comment]
Hi, @v00d00 ! Do you want me to do more tests? Tell me which test is to do and I do with the greatest pleasure!

**Comment by v00d00** [comment]
@cafaia Thanks for confirming the latest head works. I guess we need to release a `1.3.1`.

**Comment by v00d00** [comment]
@cafaia Thanks for the reports and investigation, you are a very helpful community member :+1: 

I haved tagged [v1.3.1](https://github.com/gerbera/gerbera/releases/tag/v1.3.1) which has that fix and some others, I will push the 1.3.1 build into the Gentoo tree shortly.
