### ISSUE TITLE
Running the 1.3.1 tar file has 1.4.0alpha startup logo

### ISSUE THREAD

**Issue by gpbenton** [gerbera/gerbera#445]
I get this when I start my docker container, built by downloading from the 1.3.1 tar file.  

app_1  | 2019-04-05 19:31:13    INFO: Gerbera UPnP Server version 1.4.0alpha - http://gerbera.io/

Its only a small problem provided the 1.3.1 tar files are actually 1.3.1 and not 1.4.0alpha :-)

**Comment by v00d00** [comment]
Thanks for reporting this, the 1.3.1 tag was off by one commit. Fixed now!
