### ISSUE TITLE
Video tags parsed but not included in interface

### ISSUE THREAD

**Issue by chiraag-nataraj** [gerbera/gerbera#448]
So I have MP4 files with iTunes-style tags (inserted using AtomicParsley) that were ripped from DVDs I own. `mediainfo`, `vlc` `mpv` see the tags properly on the original file (before I upload to my Raspberry Pi):
```
General
Complete name                            : The Son S1 D2 E1.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/iso2/mp41)
File size                                : 842 MiB
Duration                                 : 42 min 51 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 2 747 kb/s
Collection                               : The Son
Season                                   : 1
Part                                     : 5
Track name                               : No Prisoners
Encoded date                             : UTC 2019-04-12 11:55:53
Tagged date                              : UTC 2019-04-12 12:29:46
Writing application                      : HandBrake 1.2.2 2019022400
```
`mediainfo` also correctly sees the metadata once I transferred the file to my Raspberry Pi. `gerbera` definitely sees the metadata:
```
metadata/taglib_handler.cc:589] extractMP4(): TagLibHandler: mp4 file has no 'covr' item2019-04-12 08:24:56   DEBUG: [src/metadata/taglib_handler.c
metadata/ffmpeg_handler.cc:222] fillMetadata(): Running ffmpeg handler on /media/files/Videos/The Son/S1/D1/The Son S1 D1 E3.mp4
metadata/ffmpeg_handler.cc:95] addFfmpegMetadataFields(): Identified metadata title: Second Empire
metadata/ffmpeg_handler.cc:151] addFfmpegResourceFields(): Added duration: 00:42:15.5
metadata/ffmpeg_handler.cc:159] addFfmpegResourceFields(): Added overall bitrate: 246108 kb/s
metadata/ffmpeg_handler.cc:178] addFfmpegResourceFields(): FourCC: 7634706d = mp4v
metadata/ffmpeg_handler.cc:188] addFfmpegResourceFields(): Added resolution: 720x480 pixel
metadata/ffmpeg_handler.cc:199] addFfmpegResourceFields(): Added sample frequency: 48000 Hz
metadata/ffmpeg_handler.cc:205] addFfmpegResourceFields(): Added number of audio channels: 6
metadata/fanart_handler.cc:78] fillMetadata(): Running fanart handler on /media/files/Videos/The Son/S1/D1/The Son S1 D1 E3.mp4
metadata/fanart_handler.cc:59] getFolderName(): Folder name: /media/files/Videos/The Son/S1/D1
metadata/fanart_handler.cc:67] getFanArtPath(): /folder.jpg: missing
metadata/fanart_handler.cc:67] getFanArtPath(): /poster.jpg: missing
```
but I see the filename instead of the title in the interface (or when I'm browsing on a UPnP client). Indeed, asking Bubble UPnP to bring up the metadata for the file yields nothing.

I'm sure I'm messing something up, since I'm new to editing video metadata, but it's odd to me that `gerbera` sees the metadata but doesn't display it. Am I missing something here?

**Comment by chiraag-nataraj** [comment]
Additionally, opening the file itself through `sshfs` + `vlc` _also_ works. That is, when I access the file directly, I have no problems seeing the metadata. It's only when I go through `gerbera` that I seem to lose the metadata I've put in.

**Comment by v00d00** [comment]
Hi,

Gerbera doesn't support metadata extraction from tagged video files yet.

I have been planning on working on TV/Movies support for some time, but tidying up the existing code has taken most of my time.

**Comment by chiraag-nataraj** [comment]
Hi @v00d00.

Interesting. It certainly _discovers_ the metadata though (at least basic stuff like title), which is the odd part. Is the issue that it's not using it to set up Artist/Album/whatever virtual folders?

**Comment by ghlupe2** [comment]
Hi chiraag-nataraj,

maybe [this ](http://docs.gerbera.io/en/latest/config-import.html#ffmpeg) function that wasn't documented befor yesterday, together with [scripting](http://docs.gerbera.io/en/latest/scripting.html) is what you need?

**Comment by twdkeule** [comment]
How do I access the elements added to aux_data from `orig.aux` in the JS code?

**Comment by KarlStraussberger** [comment]
`orig.aux` is a dictionary, so you have to use `orig.aux['YOURTAG']` to get its value

**Comment by twdkeule** [comment]
Ok, thanks. The documentation mentions that it's an array, so I was confused.

**Comment by KarlStraussberger** [comment]
@whyman To me this issue is closed

**Comment by whyman** [comment]
Feel free to close things @KarlStraussberger :+1:
