### ISSUE TITLE
Weird CONNECTION header

### ISSUE THREAD

**Issue by bubbleguuum** [gerbera/gerbera#449]
What's up with that CONNECTION header not properly formatted (appended to Accept-Ranges):

Using gerbera 1.2.0 from this PPA: ppa:stephenczetty/gerbera-updates

```
$wget -S --spider http://127.0.0.1:49152/content/media/object_id/834/res_id/0/ext/file.mp3 
Spider mode enabled. Check if remote file exists.
--2019-04-17 14:28:41--  http://127.0.0.1:49152/content/media/object_id/834/res_id/0/ext/file.mp3
Connecting to 127.0.0.1:49152... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  CONTENT-LENGTH: 5932308
  Accept-Ranges: bytes
  CONTENT-TYPE: audio/mpeg
  DATE: Wed, 17 Apr 2019 14:28:41 GMT
  LAST-MODIFIED: Tue, 16 Apr 2019 17:19:38 GMT
  SERVER: Linux/4.15.0-47-generic, UPnP/1.0, Portable SDK for UPnP devices/1.8.3
  X-User-Agent: redsonic
  Content-Disposition: attachment; filename="02 - Fhernando - HeartBeat _Single Version_.mp3"
  Accept-Ranges: bytesCONNECTION: close
Length: 5932308 (5.7M) [audio/mpeg]
Remote file exists.
```

**Comment by v00d00** [comment]
@bubbleguuum Thanks for reporting, clearly missing a newline there.

P.S. I love BubbleUPnP, its awesome!

**Comment by v00d00** [comment]
Which version of Gerbera are you running?

**Comment by bubbleguuum** [comment]
Thank you for your appreciation of BubbleUPnP!

Maybe this issue has been fixed since 1.2.0 ?

**Comment by elmodaddyb** [comment]
I think this was fixed via ---> https://github.com/gerbera/gerbera/pull/320

and further improvements for header support via ---> 
https://github.com/gerbera/gerbera/commit/eeeb8338137f1bb2df89deed612e939b4af6eeca#diff-5020e963c32d49dfd3530ceedb414319

> As @v00d00 mentioned 1.3.+ should have it all!! 🏆

**Comment by v00d00** [comment]
Closing this as it looks like the [PPA](https://launchpad.net/~stephenczetty/+archive/ubuntu/gerbera-updates) has been updated to `1.3.1`!

Please reopen if you notice a problem with the new version.
