### ISSUE TITLE
Connecting with digital camera

### ISSUE THREAD

**Issue by runningopenloop** [gerbera/gerbera#458]
Hi, I'm a bit unsure of the capabilities of UPnP here and a bit ignorant to what I'm doing...  With gerbera, should I be able to connect my Canon S110 camera to the server, then transfer pictures directly to my PC?

My Canon S110 camera doesn't seem to deteect the gerbera UPnP server.

Similar to:
https://support.usa.canon.com/kb/index?page=content&id=ART139119
After setting up, this seems to work... while they pitch their software in the video below, I could just browse the images on the camera.
https://www.youtube.com/watch?v=-xcwUAVdpCg

**Comment by v00d00** [comment]
Hi @runningopenloop 

Gerbera doesn't allow uploads, only downloads.

From the link you provided it looks like your camera _includes_ a UPnP _sever_ so you would need a UPnP _client_ to view them over the network.
