### ISSUE TITLE
No cover art on mp3 with docker container

### ISSUE THREAD

**Issue by Thomas-8-Bit** [gerbera/gerbera#459]
For now i've tried various docker-conteriner-builds of gerbera and also a self build container. All versions work fine except of showing cover art of mp3 files to any dlna-client. 

If i use an bare metal installation on the same host, everything works fine. Within die container i get no error-message even i use debug mode and libtag is installed in the container.

Is there anyone got this working or have an idea where to look? l

**Comment by elmodaddyb** [comment]
The album artwork attempts to generate the image resource 2 different ways.

* First - If the resource is a container, lookup for an album artwork in the directory
* Second - If the resource is a mp3, mp4, flac, fan-art, external url - look for the artwork by looping through resources within that container.

> In both cases the system uses the `virtualUrl` value to generate a URL
[upnp_xml.cc](https://github.com/gerbera/gerbera/blob/master/src/upnp_xml.cc#L194)

This may result in the resource URL being sent to the UPNP control point to actually contain the `docker network` name, not the externally bridged network IP.

> You could try running the docker container with the `--net=host` option to use the **HOST** network.

This would expose the docker container to the host network, so beware you need to handle any network concerns on your own.

**Comment by Thomas-8-Bit** [comment]
Hi elmodaddyb,

thank you for your tips. I've used --net=host to be sure, that the network will work correct. I've doublechecked hostname and ip-address of the container-installation and it is exactly the same as the host it runs on.

**Comment by elmodaddyb** [comment]
@Thomas-8-Bit - Great progress and info.  My guess is something odd with the DIDL-LITE XML resource being sent to the UPNP client.  If you set your running gerbera container with `--debug` it should log out the XML sent out to the UPNP client.

> You could then potentially access the URL directly of the album art resource to see if it returns what you expect.

I will try to setup something that works, but have not used album artwork before...

**Comment by elmodaddyb** [comment]
OK, I was able to troubleshoot this behavior...and think that there is actually a bug here with generating the proper URL for the Album Artwork resource.

### Issue
The `didl-lite` XML generated looks like it is missing the `virtualUrl` for the album artwork:

```xml
<upnp:albumArtURI xmlns:dlna="urn:schemas-dlna-org:metadata-1-0" dlna:profileID="JPEG_TN">
   /media/object_id/300/res_id/1/rct/aa
</upnp:albumArtURI>
<upnp:albumArtURI>
    http://127.0.0.1:49152/content/media/object_id/270/res_id/0
</upnp:albumArtURI>
```

If your client chooses the 1st resource, it won't get anything back...I think the `aa` resource is the problem, you are facing....

### Root Cause

The UPNP xml generation was fixed for external URLs due to a gap in the URL generation with the base content virtual path...

https://github.com/gerbera/gerbera/pull/433

It looks like we also need to account for the `virtualUrl` in the Album Art generation...

https://github.com/gerbera/gerbera/blob/master/src/upnp_xml.cc#L869

...so

```c++
aa->setText(url);
```
> becomes...

```c++
aa->setText(virtualUrl + url);
```

> Even without this fix, the album artwork is retrieved using the second entry...so not sure how docker is involved...

**Comment by Thomas-8-Bit** [comment]
Ok. Thank you for testing on it. Then i will test with the change to upnp_xml.cc. But i'm not at home since thursday. So it has to wait until then.

**Comment by v00d00** [comment]
Interesting that we have two entries for `upnp:albumArtURI` there!  It is allowed by the [spec](http://www.upnp.org/specs/av/UPnP-av-ContentDirectory-v4-Service.pdf) but didnt realise we where doing it?

What are the two entries, the first like the expected `/rct/aa` entry, the second is a link to what?

**Comment by elmodaddyb** [comment]
Yea, the resource generation has a bunch of todos, as well as a comment saying that it is using 0th + 1 to automatically add album art, which needs refactor. 

The second entry is a file resource JPG handler that pulls the similar file resource. Like the thumbnails.
