### ISSUE TITLE
Gerbera via nginx-proxy: not working anymore

### ISSUE THREAD

**Issue by count00zero** [gerbera/gerbera#467]
Hi.

since the last time I pulled the source and built gerbera (2019-05-13) my proxying via nginx isn't working anymore!
My Gerbera is set up behind nginx via the location /Gerbera/
As soon as I am selecting "Database" or "Filesystem" my Browser is defaulting to /index.html which can't be found because "/Gerbera/" is missing.

Is there anything I can do??

THANKS and BR,
count

**Comment by elmodaddyb** [comment]
That's a bummer, You might be able to use `try_files` to accomplish it.

```
location /index.html {
    try_files $uri /Gerbera/index.html;
}
```
This assumes, your root server path, does not have a similarly named `index.html`

If you can access the `Cookie` header in nginx, you may also be able to identify **gerbera** requests via the `SID` cookie.

> http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

**Comment by elmodaddyb** [comment]
I will rework the *logoff* script to see if we can just use a relative path `index.html` instead of `/index.html`

https://github.com/gerbera/gerbera/blob/0c5e31718fb6c1ae2926c1b19efb4825073ad760/web/js/gerbera.auth.js#L154

**Comment by count00zero** [comment]
> 
> 
> That's a bummer, You might be able to use `try_files` to accomplish it.
> 
> ```
> location /index.html {
>     try_files $uri /Gerbera/index.html;
> }
> ```
> 
> This assumes, your root server path, does not have a similarly named `index.html`
> 
> If you can access the `Cookie` header in nginx, you may also be able to identify **gerbera** requests via the `SID` cookie.
> 
> > http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

Hi and thank's!
If I try it that way; the following result is generated ...
![gerbera](https://user-images.githubusercontent.com/14225157/57771893-62abfa80-7714-11e9-8382-7fcf1b177ef3.jpg)

**Comment by elmodaddyb** [comment]
yea, i figured this would happen.  Essentially all the JS files need to be proxied too.  

You could add a base-href to the `index.html` like:

`<base href="/Gerbera"/>`

All the JS files have relative path, so they should pick up the Base HREF appropriately.

If you do not want to modify the index.html file you can create a glob proxy rule in NGINX to push any base references over to `/Gerbera/` via nginx rules.

**Comment by count00zero** [comment]
I did the changes to index.html, but unfortunately the outcome is the same (image I added above).
What I don't understand is, what changed ... 3 weeks ago it worked; now it doesn't anymore.

As I don't want to mess with my current nginx-proxy-setup I will use the frontend just in my network internally and access it directly.

Thanks for GERBERA cause' I'm loving it and this issue is really minor :)

**Comment by elmodaddyb** [comment]
Ok, I have a wild guess...

On April 22nd, we updated the jQuery dependency to 3.4.0.  This changed the path of the JS file.

https://github.com/gerbera/gerbera/commit/d345c33d73102758f33132851d47a46e78c26e05#diff-d23fe9001e474c96419c8f2519cbef67

It may be possible that your browser is still using the cached `index.html` which points to `3.2.1` file.  However, cache involved, you should still have this file in your browser cache.

> I opened the app using cleared cache and everything appears to work, albeit without a reverse proxy like NGINX.

**Comment by count00zero** [comment]
Thanks for the hint!
I cleared the cache and tried everything: no change.
Installed a different browser from scratch => tadaaa .... works again like a charm!!
THANK YOU!!
