### ISSUE TITLE
Would like the user interface to display the version number

### ISSUE THREAD

**Issue by stheine** [gerbera/gerbera#468]
I'm running a number of gerbera instances. and when you publish a new release, I need to update them all.
to make it easier to find what's updated already and what not, I'd love if the user interface would display the current version number.

current, my workaround is to go to the system and run `head CMakeLists.txt`, as that seems to be the place holding the version number.

**Comment by v00d00** [comment]
I agree this would be a nice thing to have

**Comment by v00d00** [comment]
@elmodaddyb I guess the easiest way for this will be similar to the CMake flags stuff you put together, e.g. templated file filled in by CMake?

**Comment by elmodaddyb** [comment]
The system presently reads `config` from the server into the UI.
https://github.com/gerbera/gerbera/blob/master/web/js/gerbera.app.js#L106

We can add a config item similar to the way we did `friendlyName`.

> Where in the UI would the version be shown?  Any suggestions?

**Comment by stheine** [comment]
@elmodaddyb 
`pi-hole` has it at the bottom of the page always.
`grafana` has it at the bottom of the page on the login screen, and at the top of the `Help` menu once you're logged in.

if you want to do it similar, you might want to introduce a bottom bar, holding such kinds of information (eg the `Report an issue` link could go there).
if you don't want to change the page layout, I would recommend the top right, left of `Documentation`, so you'd have `<version>   Documentation   Report an Issue`.

**Comment by elmodaddyb** [comment]
Thanks for the suggestions.

I was able to get it to the UI rather easily.  Below you can see config now has the `version` attribute from the server.

<img width="397" alt="Screen Shot 2019-05-15 at 7 31 26 AM" src="https://user-images.githubusercontent.com/8599799/57772541-aa665e00-76e3-11e9-939f-04e1208a1e4b.png">

I will put together some mock-ups and post back a few examples for review...

**Comment by elmodaddyb** [comment]
I think this looks really awesome!!!  Feedback welcome!!

<img width="415" alt="Screen Shot 2019-05-15 at 9 07 59 PM" src="https://user-images.githubusercontent.com/8599799/57819266-af63f580-7755-11e9-883c-fc22a9b33105.png">

**Comment by elmodaddyb** [comment]
This feature is complete, with approval of the positioning!!

> Let me know what you think...

**Comment by stheine** [comment]
very good, thank you!
