### ISSUE TITLE
i can't go enter the webpage.

### ISSUE THREAD

**Issue by gerberanub** [gerbera/gerbera#470]
i can open this main page http://192.168.0.2:49152/index.html

and there are two links

add some files
and
view indexed files

but none of both two links are not working.
i clicked it but nothing happened.

plz help me

**Comment by elmodaddyb** [comment]
out of the box, a default `config.xml` requires a login.  The main links only become clickable once you have logged in (_based on the config.xml_)

Here is a UI walkthrough:

http://docs.gerbera.io/en/latest/ui.html

**Comment by gerberanub** [comment]
i still get errors. i edited

> out of the box, a default `config.xml` requires a login. The main links only become clickable once you have logged in (_based on the config.xml_)
> 
> Here is a UI walkthrough:
> 
> http://docs.gerbera.io/en/latest/ui.html

thank u for your replay.
but i still get errors
i edited /root/.config/gerbera/config.xml like below
  --> 
- <server>
- <ui enabled="yes" show-tooltips="yes">
- <accounts enabled="yes" session-timeout="30">
  <account user="gerbera" password="1111" /> 
  </accounts>
  </ui>
  <name>Gerbera</name> 
  <udn>uuid:9171f257-18e3-4261-8ff3-97f208b959d4</udn> 
  <home>/root/.config/gerbera</home> 
  <webroot>/usr/share/gerbera/web</webroot> 

i entered user and password but nothing happened
