### ISSUE TITLE
Video Icons disappeared

### ISSUE THREAD

**Issue by Martii** [gerbera/gerbera#471]
Heyo,

Sometime in the last day or so the icons aren't being served *anymore* I think from gerbera.

Here's my current system stats:

#### SERVER
``` console
$ uname -a
Linux server 4.18.0-20-generic #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ apt-cache madison gerbera
   gerbera | 1.3.1-1~ppa2~bionic1 | http://ppa.launchpad.net/stephenczetty/gerbera-updates/ubuntu bionic/main amd64 Packages

$ apt-cache madison kid3-qt
   kid3-qt |    3.5.1-1 | http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

#### CLIENT
``` console
$ uname -a
Linux client 4.18.0-20-generic #21~18.04.1-Ubuntu SMP Wed May 8 08:43:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ apt-cache madison kodi
      kodi | 2:17.6+dfsg1-1ubuntu1 | http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

<a href="https://user-images.githubusercontent.com/114709/58136458-54198380-7beb-11e9-99fa-984e92788dbb.png"><img src="https://user-images.githubusercontent.com/114709/58136458-54198380-7beb-11e9-99fa-984e92788dbb.png" alt="Kodi list with missing icons" title="Click to enlarge... Kodi list with missing icons" width="196" height="112"/></a>

As far as I know neither Kodi or Gerbera were updated... however there have been a lot of system level updates *(Python, networking, etc)*. 

* Tried system reboot... no change, still missing.
* Tried new temp Kodi profile and relinked Kodi sources... no change, still missing.

Everything plays fine just no icon images from the mp4's. They were there two days ago for sure as I go into this source on a daily basis. So I thought I'd start here. :)

Since this is a production system I'm not able to try out beta's/current HEAD *(Had zero time to even try again to compile the current HEAD)* 

Any recommendations on what to try out? TIA :smile_cat:

**Comment by elmodaddyb** [comment]
@Martii - I think recently the Bionic package for Gerbera was updated in the PPA.

We also recently fixed an issue in v1.4.0 which was introduced which broke the icons

https://github.com/gerbera/gerbera/issues/459

> I think 1.4.0alpha has the fix you need, but the Bionic package is @ 1.3.1

**Comment by v00d00** [comment]
@Martii Are you happy to try a git build and let us know if it works?

**Comment by Martii** [comment]
@v00d00

Some time next week is more agreeable since I'm heading out the door later today and will be busy through our holiday here until Tuesday... last time I tried to build gerbera it didn't go well but my networks changed a lot since then and maybe the dependencies will come through better on round 2. So in short yes but next week. :) ... unless you meant a .deb file for me to try... I might be able to squeeze that in on Thursday of this week if so.

**Comment by elmodaddyb** [comment]
I was able to troubleshoot this and identified why the icons are not showing.

### Root Cause
The system adds `upnp:AlbumArtURI` when the resource handler matches an MP3 (_presumably to support cover art, etc_).
https://github.com/gerbera/gerbera/blob/master/src/upnp_xml.cc#L867

### Solution

1. Add condition to allow FFMPEG thumbnail to be served as album art 

```c++
if (handlerType == CH_FFTH || handlerType == CH_ID3 || ...
```
2. Serve album art if the handler is for FFMPEG Thumbnails
```c++
if (rct == ID3_ALBUM_ART || handlerType == CH_FFTH) {
  ... // serve <upnp:AlbumArtURI> resource
```

Let me know what you think, the bug fix is really simple, but not sure if this is logical solution.

> I tested this on VLC & Kodi

**Comment by elmodaddyb** [comment]
OK, digging further, it looks like MP4 Taglib handler will add the `ID3_ALBUM_ART` resource into the database, if it has `covr` tag.
https://github.com/gerbera/gerbera/blob/master/src/metadata/taglib_handler.cc#L273

However, if the system must generate a FFMPEG thumbnail, this ID3 content handler will not suffice.

**Comment by Martii** [comment]
@v00d00 
Current HEAD of 2ccfe12ebc962a5f1ec81b8c3a2ead536b1c9ea8 was successfully built *(Quick start build instructions for K/Ubuntu 16.04 vs. 18.04 are a bit off as are required/optional dependencies but got them resolved I believe)* is showing me a video icon here on my dev station. I'll add some more test files of various media and perhaps do some screenshots in a while.

**Comment by Martii** [comment]
Here is the screenshot and better yet some test sources for cross-compatibility checks.

Test platform is Kubuntu 18.0.4 however Windows 7 VM is used for additional check on thumbnailing the icons. See window decorations for which one is which.

NOTES:
* Item 1 is the AVI. As we all might know .avi doesn't support thumbnail icons in the metadata from last look. Windows 7 is generating one with the "hidden files" with a thumnail icon of the second hand with `1`.
* Item 2 is the MP4. Thumbnail icon was set to a screencap of the second hand with `2`.
* Item 3 is the MKV. Thumbnail icon was set to a screencap of the second hand with `3`. Might be a bug with this distros version of MKV with .mkv but I usually use .mp4's... so loosely related perhaps?

Refs:
* <a href="https://user-images.githubusercontent.com/114709/58455040-8f312080-80dd-11e9-8b72-a92405103e21.png"><img src="https://user-images.githubusercontent.com/114709/58455040-8f312080-80dd-11e9-8b72-a92405103e21.png" alt="Linux and Windows screencap of test videos" title="Click to enlarge... test video thumbnails screencap in Kodi 17.x" width="191" height="106"/></a>
* [~327.5KiB SHA256: 61b95d1f80125a8de1dc755ba3518f7b74eb32341c270d56f8813995dbf794f1  clock.zip
](https://github.com/gerbera/gerbera/files/3225897/clock.zip) *(These are just transcoded with some default settings... probably too high compared to the source but quick and dirty)* :smile_cat: 


Sys stats:
``` console
$ apt-cache madison mkvtoolnix-gui
mkvtoolnix-gui |   19.0.0-1 | http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

$ # Remainder of system stats identical to initial report above.
```

**Comment by Martii** [comment]
So:

``` console
$ apt-cache madison gerbera
   gerbera | 1.3.2-1~ppa1~bionic1 | http://ppa.launchpad.net/stephenczetty/gerbera-updates/ubuntu bionic/main amd64 Packages
```
... restores the .mp4 video icons *(Thank you :)* but .mkv seem to still be missing although I've never used them until this issue. 

Don't know if you want a special issue for that or just use this one since it's fully documented
