### ISSUE TITLE
Documentation on how to use TXXX

### ISSUE THREAD

**Issue by tommyp-vr4** [gerbera/gerbera#474]
This is more of a documentation thing and not really an issue.  Can the gerbera.io website be updated to include how to use the TXXX id3 tag?  Since most folks probably won't use it, maybe it's best to have it in an "advanced setup" or something along those lines.  There was an older issue #421 that has some info, but I'm not sure how to use it in conjunction with an import.js.

**Comment by ghlupe2** [comment]
Let's say, you wanted to use the release type and country information from MusicBrainz, you would add to config.xml 
```
    <library-options>
      <id3>
         <auxdata>
            <add-data tag="TXXX:MusicBrainz Album Release Country"/>
            <add-data tag="TXXX:MusicBrainz Album Type"/>
         </auxdata>
      </id3>
    </library-options>
```
and in your import script you would refer to this information like

```
         var albumCountry = obj.aux['TXXX:MusicBrainz Album Release Country'];
         var albumType = obj.aux['TXXX:MusicBrainz Album Type']; 
```
(see [MusicBrainz Tag Mappings](https://picard.musicbrainz.org/docs/mappings/))

I'm a github noob but will try to create an according documentation pull request.

**Comment by tommyp-vr4** [comment]
Thanks ghlupe2.  Now that TXXX works, I can finally use those tags on my import scripts!

**Comment by v00d00** [comment]
Closed with #475

**Comment by ghlupe2** [comment]
Just a small remark, while opening issue #759 I noticed that the TXXX label is part of the value output, e.g.

JS: TXXX:WORK--->**WORK** Come Together
JS: TXXX:Writer--->**Writer** John Lennon Paul McCartney

which requires further scripting effort for users.
Sorry for not commenting on that much earlier.

**Comment by tommyp-vr4** [comment]
Yes, there was some extra scripting required.  I'm not a programmer but messed around enough to make this work for me.  I use a MOOD tag to separate my files out.  Maybe there's a better way?  I don't know.  

My config.xml has this:
          <add-data tag="MOOD"/>
          <add-data tag="TXXX:Mood"/>

My import.js has this:
//  get mood.  bandaids required to strip off "Mood " from mp3 tags.  flac files read in fine.  mood1 is for flacs.  mood2 is for mp3s.
    var mood1 = obj.aux['MOOD'];
    var mood2 = obj.aux['TXXX:Mood'];
    if (!mood1) {mood1 = '';}
    if (!mood2) {mood2 = '';} else {mood2 = mood2.replace("Mood ", "");} 
    mood=mood1 + mood2;
    if (!mood) {
        mood = 'Unassigned';
    } else {
//        desc = desc + ', ' + mood;
        both = 'both';
    }
