### ISSUE TITLE
deb of gerbera 1.3 for ubuntu 18.04

### ISSUE THREAD

**Issue by JeroenED** [gerbera/gerbera#478]
Hi,

Version 1.3.1 introduced an issue with cover art (already fixed now) which I really hate.

Is there anyone who has a backup the deb of 1.3 for ubuntu 18.04/mint 19?

Thanks in advance.
Jeroen

Sorry for making this non-issue. I had no idea how to make my request differently.

**Comment by v00d00** [comment]
Ive just tagged [v1.3.2](https://github.com/gerbera/gerbera/releases/tag/v1.3.2), so hopefully @stephen-czetty will kindly provide new builds.

**Comment by JeroenED** [comment]
@stephen-czetty please? :Puppy-eyes:

**Comment by stephen-czetty** [comment]
I have it queued up to work on this weekend. :)

**Comment by JeroenED** [comment]
Thanks for the update @stephen-czetty
