### ISSUE TITLE
How to enhance this import code

### ISSUE THREAD

**Issue by JeroenED** [gerbera/gerbera#480]
Hi there,

I have following snipped in my import.js script. This code makes that I have a artist container with the artist's albums as its contents.

```JS

    chain = ['Audio', 'Artists', albumartist];
    addCdsObject({objectType: OBJECT_TYPE_CONTAINER}, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ARTIST);

    chain = ['Audio', 'Artists', albumartist, album];
    obj.title = track + title;
    addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_ALBUM);
```

The issue I have with it is that it creates errors.
```
Jun 18 13:28:43 apple-juice gerbera[18143]: 2019-06-18 13:28:43      JS: processing: /mnt/ExtHDD/Muziek/Ks Choice/The Essential/136 Until Im Fine.mp3
Jun 18 13:28:43 apple-juice gerbera[18143]: 2019-06-18 13:28:43   ERROR: tried to add a container or tried to update a non-virtual container via _addUpdateObject; is this correct?
Jun 18 13:28:43 apple-juice gerbera[18143]: Exception raised in [src/storage/sql_storage.cc:353] _addUpdateObject(): tried to add a container or tried to update a non-virtual container via _addUpdateObject; is this correct?
```

What could be a better way to have a artist container with the artist's albums as contents? (aka no errors)

PS. HiFi Cast takes account of UPNP_CLASS_CONTAINER_MUSIC_ARTIST to show a different icon and different lay-out for this container

PS2: Currently script does its work, it's just inconvenient to see this error. Meanwhile I updated the script to only create this container if new albumartist making the error appear much less. Still stays an inconvenience.

**Comment by KarlStraussberger** [comment]
Fixed with #1218
