### ISSUE TITLE
gerbera not processing parts of config.xml

### ISSUE THREAD

**Issue by Ilikeflowers** [gerbera/gerbera#486]
Good day,
first of all, thank you for the great work! Gerbera seems to be the Media-Server I really need, especially because of the Upnp search funktion.

But I have a little issue with the config, though.
Somehow, Gerbera seems to ignore the following parts of the config file, put at the end of the file:
```
[...]
<autoscan use-inotify="yes">                                                                                                
<directory location="/volume1/music" mode="inotify" interval="30"  
level="basic" recursive="yes" hidden-files="no"/>
</autoscan>
<pc-directory upnp-hide="yes"/>   
</config>
```

This results in the pc-directory beeing shown and in the music folder not beeing scanned.
What am I doing wrong?

**Comment by v00d00** [comment]
Autoscan needs to go under the "import" tag

**Comment by Ilikeflowers** [comment]
Ah, got it! Thanks a lot! :-)
