### ISSUE TITLE
Wrong metadata linked to songs using sqlite3

### ISSUE THREAD

**Issue by pcerny** [gerbera/gerbera#487]
I have installed gerbera 1.3.2 backed by sqlite3 on ubuntu 18.04. I modified import.js script to serve my needs. During the process I did several times the following from web UI:
- recursive import of music library
- check result of import in DB view
- remove music library from DB view by removing top key in PC Directory 

Once I was satisfied with result I started streaming music. It worked by some songs were showed with wrong metadata of other imported song(s). I could drop the whole DB and import it from scratch. But I would like to do those operations also later on. And I would expect the same will happen if inotify detects removal of the files.

I looked into code. It seems that:
- there is a typo in model for sqlite3 https://github.com/gerbera/gerbera/blob/master/config/sqlite3.sql#L19-L20, references cds_object instead of mt_cds_object
- sqlite3 has switched off foreign key functionality by default (see https://www.sqlite.org/foreignkeys.html), it means:
  - no FK integrity checks
  - no delete on cascade, update on cascade to switch it on, PRAGMA foreign_keys = ON clause must be used at the beginning of every session
- code executes recursive deletes from mt_cds_object and later on reuse freed PKs for a new objects but child records from table mt_metadata are not removed either by code or by FK delete on cascade

Could someone confirm my observations and possibly fix it?

**Comment by v00d00** [comment]
Firslty, thanks for using Gerbera and the bug report.

It certainly does look like a typo there, good spot! Its been there since at least 2006! :laughing: 

Records not being deleted from `mt_metadata` certainly sounds plausible

**Comment by v00d00** [comment]
Hey @pcerny, Can you try a master build and tell me how you get on? Should be fixed :+1:

**Comment by pcerny** [comment]
Hello @v00d00, thanks for a quick fix. Unfortunately fix had ripple effect uncovering another issue.

I built and installed gerbera from master, it shows me version 1.4.0alpha. With this version I executed the following test:
- previous sqite3 DB file removed
- gerbera started - it created new DB and populated it with fixed schema definition
- using web UI, music library imported
- in web UI FileSystem view, `PC Directory` top item with music library removed to purge the whole music library

#### Test results
On the bright side, after the test, `mt_metadata` had only records referencing existing lines in `mt_cds_object`, i.e. it is now purged.
But all the virtual folders where not removed from DB. Removal operation works like a charm without enabled FKs in sqlite3 (with the exception of purging `mt_metadata` table). So the current code to recursively remove data is not compatible with enabled FKs. As recursive remove is common for all DB backends, it should be somehow solved for mysql already or there is the same issue.

#### My idea why virtual folders were not purged:
My music library has more than 1000 items including containers. Note that `MAX_REMOVE_SIZE` is defined to 1000. When I removed top container from `PC Directory`, method `SQLStorage::_recursiveRemove` went down the tree to items. Items were planned for scan (`itemIds` vector), but before that, `SQLStorage::_removeObjects` was called for all containers and items. As FKs are active, `ON DELETE CASCADE` removes all records referencing containers and items by `parent_id` or `ref_id`. It means, all lists of virtual folder structure were removed before scan of `itemIds` vector. Once `itemIds` vector scan is executed all virtual list items are gone so virtual containers are not marked as changed.

#### sqlite model versioning
If the decision will be made to leave FKs enabled, a new version of DB model should be created including code to migrate to it. It is a bit tricky because sqlite3 does not support DROP/CREATE constraint. A new table must be created, data copied and old one dropped, see https://sqlite.org/lang_altertable.html, section "Making Other Kinds Of Table Schema Changes".
To be honest I do not care about migration much. But others could be interested.

**Comment by whyman** [comment]
Closing this and opening the removal issue as #547
