### ISSUE TITLE
Help needed: Transcoding Streams from DVB-C (tvheadend) to flac or mp3

### ISSUE THREAD

**Issue by Phaet** [gerbera/gerbera#488]
### Help needed

I would like to stream from DVB-C to my internet radios using tvheadend and Gerbera, the latter as directory service and for transcoding (all running on my home-brewed NAS with Ubuntu 18.04 server).
I added a playlist with the links to the tvheadend streams. This part works smoothly, for example with VLC or Kodi on my Tablet which can deal with mpeg-ts and mp2 audio.

But my internet radios ask for a different audio format, that is mp3 or preferably flac. I struggled a whole week now setting up transcoding, but with no success. 

The transcoding section in the config looks like this:                                                                                                                                  
`  <transcoding enabled="yes">                                                                                `    
`    <mimetype-profile-mappings>     `                                                                                
`      ...                                               `   
`     <transcode mimetype="audio/mp2" using="mpeg2flac"/>                `                                           
`    </mimetype-profile-mappings>                 `                                                                   
`   <profiles>                                        `                                                              
`      <profile name="mpeg2flac" enabled="yes" type="external">           `                                           
`        <mimetype>audio/flac</mimetype>                      `                                                       
`        <accept-url>yes</accept-url>                     `                                                           
`        <first-resource>yes</first-resource>        `                                                                
`        <hide-original-resource>yes</hide-original-resource>            `                                            
`        <accept-ogg-theora>no</accept-ogg-theora>        `                                                           
`        <agent command="ffmpeg" arguments="-y -i %in -map 0 -codec:a:0 flac -ar 44100 %out"/>    `                   
`        <buffer size="1048576" chunk-size="131072" fill-size="262144"/>     `                                        
`      </profile>`

I do not really know which mime-type to specify.
I do also not know what the \<treat\> stanzas exactly do.

Anyway, regardless which combination of transcode mime-type and treat settings I used so far, nothing happens. 
_Interestingly, when I click the edit button for a playlist entry, it alway reports "audio/mpeg", regardless whether it is a video mpeg ts transport stream of a tv channel or mp2 for a radio channel._

#### ffprobe for a video channel
`Input #0, mpegts, from 'http://192.168.1.98:9981/stream/channelid/835108875':`                                     
`  Duration: N/A, start: 46512.294011, bitrate: N/A`                                                                
`  Program 11100 `                                                                                                  
`    Metadata:`                                                                                                     
`      service_name    : ?Das Erste HD`                                                                             
`      service_provider: ARD`                                                                                       
`    Stream #0:0[0x177a]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, progressive), 1280x720 [SA
R 1:1 DAR 16:9], 50 fps, 50 tbr, 90k tbn, 100 tbc`                                                                  
`    Stream #0:1[0x1784](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 256 kb/s`                
`    Stream #0:2[0x1785](mis): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 256 kb/s`                
`    Stream #0:3[0x1786](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 448 kb/s`                
`    Stream #0:4[0x178e](deu): Subtitle: dvb_teletext ([6][0][0][0] / 0x0006)`                                      
`    Stream #0:5[0x178f](deu): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006) (hearing impaired)` 
                  
#### ffprobe for a radio  channel                                                                              
`Input #0, mpegts, from 'http://192.168.1.98:9981/stream/channelid/1275354359':`                                    
`  Duration: N/A, start: 26848.683811, bitrate: 768 kb/s`                                                           
`  Program 28403 `                                                                                                  
`    Metadata:`                                                                                                     
`      service_name    : ?BR-KLASSIK`                                                                               
`      service_provider: ARD BR`                                                                                    
`    Stream #0:0[0xc3b](deu): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, s16p, 320 kb/s`                 
`    Stream #0:1[0xc3c](deu): Audio: ac3 ([6][0][0][0] / 0x0006), 48000 Hz, stereo, fltp, 448 kb/s`

I also switched on debug mode, but don't see anything in the log what could give a hint.

[gerbera.log](https://github.com/gerbera/gerbera/files/3421973/gerbera.log)

**Comment by v00d00** [comment]
Have you been through the [Transcoding docs?](http://docs.gerbera.io/en/latest/transcoding.html)

**Comment by v00d00** [comment]
Have you been through the [Transcoding docs?](http://docs.gerbera.io/en/latest/transcoding.html)

**Comment by Phaet** [comment]
Yes, I read alot during the past days and digged also into old mediatomb forum threats.
In the beginning I thought that gerbera, in order to figure out the mime-type of an online stream, Gerbera performs dynamically some fancy probing with ffprobe or the like.
But now, after analyzing the Java scripts and the debug log, I learnt that all is done as static mapping during import of a playlist. Moreover, for an external URL, i.e. containing the string "://", the mime-type is fixed set to audio/mpeg (which is somewhere else mapped to mp3), regardless of the actual transport stream content. Probably upon the assumption that internet radios send in mp3 anyway.
So in order to see what will happen, I changed in playlists.js the mime-type assignment to audio/mp2
and set up a transcoding profile for audio/mp2 to audio/flac.

`  <transcoding enabled="yes">`                                                     
`    <mimetype-profile-mappings>`                                                   
`      <transcode mimetype="audio/mp2" using="mpeg2flac"/>`                         
`    <profiles>`                                                                    
`      <profile name="mpeg2flac" enabled="yes" type="external">`                    
`        <mimetype>audio/flac</mimetype>`                                           
`        <accept-url>yes</accept-url>`                                              
`        <first-resource>yes</first-resource>`                                      
`        <hide-original-resource>no</hide-original-resource>`                       
`        <accept-ogg-theora>no</accept-ogg-theora>`                                 
`        <agent command="ffmpeg" arguments="-y -i %in -acodec flac -ar 44100 -f flac
 %out"/>                                                                            
         <buffer size="1048576" chunk-size="131072" fill-size="262144"/>`           
`      </profile>`                                                                  
`    </profiles>`

I tested the ffmpeg line on the command line with a fifo and tested the result with ffprobe. This works fine. BTW: The -f option is necessary because the fifo output has no extension and ffmpeg complains about it. The -y option is required because otherwise ffmpeg asks before overwriting the existing fifo.

Now, after importing the playlist, I found how mapping items for each entry are created in the debug log, for instance:
`<item id="61035" parentID="61006" restricted="1">`                                 
`<dc:title>SWR2</dc:title>`                                                         
`<upnp:class>object.item.audioItem.musicTrack</upnp:class>`                         
`<dc:description>Song from Radio.m3u</dc:description>`                              
`<res protocolInfo="http-get:*:audio/flac:*">/online/object_id/61035/res_id/none/pr_name/mpeg2flac/tr/1</res>`                                                          
`<res protocolInfo="http-get:*:audio/mp2:*">http://192.168.1.98:9981/stream/channelid/1643010205?ticket=40F111025D080A7F10EBF8885FF5786D265E3678&amp;amp;profile=pass</res></item>`

As one can see, two res elements are created. The first one for the transcoding stream, because of the first-resource stanza, and the second one for the original stream address.

I would now expect that an upnp client sees the two streams and can select one according to its capabilities. BUT NOPE.

Testing with BubbleUPNP and VLC on my Tablet, both only see one stream, the original one. The clients see the playlist entries, but each provide only one stream.

I read somewhere in the documentation that transcoding only starts after an HTTP GET request to the transcoding address. But I do not have any idea how this address should look like. Something like 
`/online/object_id/61035/res_id/none/pr_name/mpeg2flac/tr/1</res>`                                                          
Anyway, with my set-up the clients are not provided with such an address.

So I wonder what might be wrong ...

**Comment by v00d00** [comment]
Thanks for the extra info.

The thing that sticks out to me is:

```
<res protocolInfo="http-get:*:audio/flac:*">/online/object_id/61035/res_id/none/pr_name/mpeg2flac/tr/1</res>
<res protocolInfo="http-get:*:audio/mp2:*">http://192.168.1.98:9981/stream/channelid/1643010205?ticket=40F111025D080A7F10EBF8885FF5786D265E3678&amp;amp;profile=pass</res>
```

So, it looks like we need to add our server address before hand

**Comment by Phaet** [comment]
OK, thanks. Please keep me posted as soon as a fix is available.

**Comment by Phaet** [comment]
I just tried to start a transcoded stream manually in a browser with the address
`http://192.168.1.98:49152/online/object_id/61035/res_id/none/pr_name/mpeg2flac/tr/1`
but with no success (404 not found).
In comparison calling a piece of music stored in the filesystem with an address of, for example
`http://192.168.1.98:49152/content/media/object_id/1770/res_id/0`
works well.

I wonder therefore whether it is only a matter of the missing server address ...

**Comment by Phaet** [comment]
BTW: Also the Gerbera WebUI provides only the link to the original stream and not to the transcoded stream or offering a popup with a choice of the two.

**Comment by Phaet** [comment]
Found this in the log: 2019-08-01 08:59:16 DEBUG: [src/server.cc:411] createRequestHandler(): Filename: /content/online/object_id/61035/res_id/none/pr_name/mpeg2flac/tr/1 
 2019-08-01 08:59:16 DEBUG: [src/url_request_handler.cc:63] getInfo(): start 
 2019-08-01 08:59:16 DEBUG: [src/url_request_handler.cc:77] getInfo(): full url (f ilename): /content/online/object_id/61035/res_id/none/pr_name/mpeg2flac/tr/1, parame ters: object_id/61035/res_id/none/pr_name/mpeg2flac/tr/1 
 2019-08-01 08:59:16 ERROR: Object not found: 61035 
 2019-08-01 08:59:29 DEBUG: [src/server.cc:411] createRequestHandler(): Filename: /content/object_id/61035/res_id/none/pr_name/mpeg2flac/tr/1 
 2019-08-01 08:59:29 ERROR: no valid handler type in /content/object_id/61035/res_ id/none/pr_name/mpeg2flac/tr/1

**Comment by cweiske** [comment]
This issue is very old, and gerbera's internals have changed significantly in the last years. @Phaet please tell us if the problem still exists.
