### ISSUE TITLE
GUI not working on debian 10 / Gerbera 1.3.2

### ISSUE THREAD

**Issue by EricdeWaal** [gerbera/gerbera#492]
Hello, 
I installed Gerbera 1.1.0+dfsg-3 from the Debian Duster packages source and it worked. 
Although login in the GUI was not possible, I had to set "accounts enabled" to "no" to see the interface to the files and database.
To get a newer version, I upgraded to version gerbera 1.3.2-dmo1 from deb-multimedia.org.
That works too, except the UI. With or without accounts enabeled, Login does nothing and I cannot see the Database or File System.
Until there is a fix, is there another way to set options for scanning etc?
Thanks a lot for the great work and a quick answer!

Best,
Eric

**Comment by v00d00** [comment]
Is the daemon actually running? Can you provide a log file?

**Comment by EricdeWaal** [comment]
Oh yes, it runs. My dlna clients can see it, and in Webmin I see it under 'running processes':
ID: 4237 | gerbera | 09:46 | /usr/bin/gerbera -c /etc/gerbera/config.xml
The deamon log says: 
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Gerbera UPnP Server version 1.3.2 - http://gerbera.io/
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: ===============================================================================
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Gerbera is free software, covered by the GNU General Public License version 2
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Copyright 2016-2019 Gerbera Contributors.
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: ===============================================================================
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Loading configuration from: /etc/gerbera/config.xml
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Checking configuration...
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Setting filesystem import charset to UTF-8
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Setting metadata import charset to UTF-8
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Setting playlist charset to UTF-8
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Configuration check succeeded.
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: No metadata migration required
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Initialized port: 49152
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: Server bound to: 192.168.0.5
Jul 31 09:46:13 NAS gerbera[4237]: 2019-07-31 09:46:13    INFO: The Web UI can be reached by following this link: http://192.168.0.5:49152/

Is there a specific gerbera log?

**Comment by v00d00** [comment]
That log looks fine, is there an error in your browser dev tools?

**Comment by EricdeWaal** [comment]
I was just looking at this, 2 bootstrap files could not be loaded: vendor/bootstrap/css/bootstrap.css and vendor/bootstrap/js/bootstrap.min.js.
That is probably the issue. Which bootstrap version do you use?

**Comment by EricdeWaal** [comment]
I found that /usr/share/gerbera/web/vendor/bootstrap is a symlink to /usr/share/javascript/bootstrap.
In there, css/bootstrap-grid.css is a file and it's loaded OK by the GUI page.

But in there I also see css/bootstrap.css which is a symlink to a non-existing file. There are similar symlinks to css/bootstrap.css.map, css/bootstrap.min.css, js/bootstrap/js and js/bootstrap.min.js. 

All invalid links, which seem to come from the gerbera installer package.

Trying to replace them with real files now!

**Comment by EricdeWaal** [comment]
That did the trick, the bootstrap version the is included in gerbera is 4.0.0.
It can be downloaded from https://getbootstrap.com/docs/4.0/getting-started/download/.
Just replace the css and js directories in /usr/share/javascript/bootstrap and you're in business!

**Comment by EricdeWaal** [comment]
Well, not quite, logging in still does not work, but at least with "accounts enabled" set to "no" it works

**Comment by v00d00** [comment]
Okay, thanks, it sounds like a packaging bug, please report it to the Debian multimedia guys :+1:

**Comment by EricdeWaal** [comment]
Thanks, I have reported it. 
A bit off-topic: the config.xml file still has references to urls that no longer exist:
<config version="2" xmlns="http://mediatomb.cc/config/2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mediatomb.cc/config/2 http://mediatomb.cc/config/2.xsd">

**Comment by v00d00** [comment]
I guess we should host our schemas ourselves now, they definitely used to be available at that address

**Comment by v00d00** [comment]
Closing this for now, feel free to open
