### ISSUE TITLE
FOREIGN KEY error at database creation time

### ISSUE THREAD

**Issue by whorfin** [gerbera/gerbera#504]
I see some changes involving various "foreign key" behavior, so I'm scratching my head.
I recently rebuilt gerbera from master, since my Solaris version now supports inotify.
I'm rebuilding the db [sqlite3] from scratch as I saw some weirdness, but I'm seeing tons of stuff like this:
```
2019-09-15 23:11:29 WARNING: skipping /tank/whorfin/Audio/Musiq/Kraftwerk/The Catalogue [2009]/CD8 Tour de France/09 - Elektro Kardiogramm.flac : SQLITE3: (19) FOREIGN KEY constraint failed
Query:INSERT INTO "mt_cds_object" ("id","parent_id","object_type","upnp_class","dc_title","location","location_hash","ref_id") VALUES (74961,74310,1,'object.container.album.musicAlbum','Tour de France','V/Audio/Artists/Kraftwerk/Tour de France',2381891902,74960)
error: FOREIGN KEY constraint failed
```
eh?

**Comment by whyman** [comment]
We recently enabled Foreign key support on Sqlite... Clearly something is not happy.

**Comment by whyman** [comment]
I can replicate this locally, so thats nice.
