### ISSUE TITLE
Provide tagged Docker images

### ISSUE THREAD

**Issue by klausenbusk** [gerbera/gerbera#511]
The [README](https://github.com/gerbera/gerbera/blob/59c2e111cffe0e58c9a0c8a47449d6c95ef27a5c/README.md#docker) recommend running a version tagged image, but there isn't [any version tagged images](https://hub.docker.com/r/gerbera/gerbera/tags).

**Comment by whyman** [comment]
Correct.

As soon as we do the next release, there will be a tagged image...

**Comment by whyman** [comment]
v1.3.3 triggered a tagged build :+1: 

https://hub.docker.com/r/gerbera/gerbera/tags
