### ISSUE TITLE
disabled ui has no effect

### ISSUE THREAD

**Issue by osce0** [gerbera/gerbera#512]
in my config.xml, I have

```
<server>
  <ui enabled="no" show-tooltips="yes">
   <accounts enabled="yes" session-timeout="30">
...
```
gerbera log still shows
Initialized_port: 49152
Server bound to: XX.XX.XX.XX

debug log (using -D option) only shows the following related to ui:
src/config_manager.cc:1386 getOption(): Config: option not found: /server/ui/attribute ...
src/config_manager.cc:1386 getOption(): Config: option not found: /server/ui/items-per-page/attribute ...

It looks like it never parses server/ui/enable option

I can confirm that http://localhost:49152/ is still accessible (and is not pointing to disabled.html either), and I can browse other files thru http://localhost:49152/OTHERFILE

For some reason if I disallow port 49152 in firewall, gerbera doesn't seem to broadcast its presence.

**Comment by whyman** [comment]
It will use the same port for serving the file content and the XML descriptions of the device, which is why it disappears when you block it.

As for the UI disabling not working that is strange, it definitely used to work, so must be a regression

**Comment by whyman** [comment]
Going to close this, if your UI is still serving please re-open
