### ISSUE TITLE
--create-config dont works

### ISSUE THREAD

**Issue by akadawa** [gerbera/gerbera#513]
unrecognized option '--create-config
is this option still alive `?

**Comment by whyman** [comment]
Which version of gerbera are you running?

**Comment by akadawa** [comment]
i have install gerbera with apt-get

`root@plexSRV:~# gerbera --version

Gerbera UPnP Server version 1.1.0 - http://gerbera.io/`

**Comment by whyman** [comment]
The behaviour in that version was different. You shouldn't need to create a config file if you installed via debian package anyway, the config will be at `/etc/gerbera/config.xml`
