### ISSUE TITLE
Does not recognize .mpg files

### ISSUE THREAD

**Issue by lrhorer** [gerbera/gerbera#516]
A large number of the video files in my library are MPEG-II (*.mpg), but Gerbera does not seem to recognize these as video files.  It does not pick them up in the database scan.  I tried making a few changes to config.xml that I thought might help, such as changing <transcoding enabled="no"> to <transcoding enabled="yes"> and adding <map from="mpg" to="video/mpeg"/>, but then Gerbera just dies.

I am running Gerbera under Debian Buster on an AMD-64 machine with a Sony Bravia client.

**Comment by whyman** [comment]
Do they show up in the web UI?

**Comment by lrhorer** [comment]
No.  Mp4 and mkv files do, but not mpg.

**Comment by whyman** [comment]
Can you provide a log with debug enabled?

**Comment by lrhorer** [comment]
[gerbera.log](https://github.com/gerbera/gerbera/files/3886380/gerbera.log)

**Comment by lrhorer** [comment]
I doubt it is related, but note Gerbera would not run under systemd with the debug option enabled.  I had to run it manually.

**Comment by lrhorer** [comment]
Anything on this?

**Comment by whyman** [comment]
Perhaps try uncommenting `<!-- map from="mpg" to="video/mpeg"/ -->`

**Comment by pamapa** [comment]
@lrhorer does it work for you now, if so please close the issue. For me, mpg files are working fine
