### ISSUE TITLE
Renderer not showing tracknumer & artist when playing track ... (question)

### ISSUE THREAD

**Issue by count00zero** [gerbera/gerbera#524]
Hi there,

I really searched my a** off, trying to find a solution for that, but the only thing comparable to be found is the virtual containers (which I don't need).

So my thing is: when browsing through the library (on my upnp renderer) I see everything: Track# + Artists + Title. But when I'm playing the title (I wanna hear), my renderer just shows me the title of the currently played file/song (no track#, no artist).

Is there a way to make it happen, so that I can see this information?

And another question (maybe I'm to dumb for the import-scripts): is it able (when using the standard layout) to just strip the whole "PC Directory"&path part and start with my music-directory being the root?

Thanks a lot and appologies for my noob questions ;-)

PS: keep up the great work; I'm lovin' it of course :)

**Comment by whyman** [comment]
> So my thing is: when browsing through the library (on my upnp renderer) I see everything: Track# + Artists + Title. But when I'm playing the title (I wanna hear), my renderer just shows me the title of the currently played file/song (no track#, no artist).
> 
> Is there a way to make it happen, so that I can see this information?
> 
One option would be a custom layout that puts all the information into the title, asi ii sounds like thats all you are getting form your renderer, but that would affect the browser too (until we maybe one day get per device settings) 

> And another question (maybe I'm to dumb for the import-scripts): is it able (when using the standard layout) to just strip the whole "PC Directory"&path part and start with my music-directory being the root?

Not using the standard layout

> Thanks a lot and appologies for my noob questions ;-)
> 
> PS: keep up the great work; I'm lovin' it of course :)

No problem, and thanks!

**Comment by count00zero** [comment]
Thanks a lot for the information!!!
