### ISSUE TITLE
http video playlist

### ISSUE THREAD

**Issue by alex-eri** [gerbera/gerbera#525]
Set Title from #EXTINF seems is not supported.
Can i serve playlist of videos served via HTTP?

I have TV streamed with `udpxy` http://iptv.youlike.ru/plist.m3u

**Comment by alex-eri** [comment]
Can i write plugin that generates collection of video items?

**Comment by whyman** [comment]
You should be able to use [Scripting](http://docs.gerbera.io/en/latest/scripting.html) to parse your playlists and add items
