### ISSUE TITLE
Remove "Directories" level from Video section

### ISSUE THREAD

**Issue by stvrly** [gerbera/gerbera#530]
Is there a way, perhaps via modifying a script, to remove the "Directories" level from the tree of items shown in "Video"? My preference would be, when I navigate to the "Video" item in my DLNA player, just to show the directories themselves and not under one more level in the hierarchy.

**Comment by whyman** [comment]
You should be able to do that with a scripted layout http://docs.gerbera.io/en/latest/scripting.html#how-it-works
