### ISSUE TITLE
Missing JPEG_LRG and co in the <res> tag

### ISSUE THREAD

**Issue by jkiusAlarus** [gerbera/gerbera#532]
Hello,
I try to have my dlna viewers see images using alternatives resolutions using transcode. It works great if there is only one resource available for each item. 
When the original resource and/or a thumbnail is also present, things become complicated and depend on the client implementation. 
However, gerbera does not advertise the resource consistently: for thumbnails it uses the DLNA.ORG_PN=JPEG_TN and do not for the other resources. See for example:
```<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_OP=00;DLNA.ORG_CI=1" resolution="1024x768">http://192.168.0.4:49154/content/media/object_id/504575/res_id/none/pr_name/resizejpeg/tr/1/ext/file.jpg</res>
<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_OP=01;DLNA.ORG_CI=0" size="3177616" resolution="4288x2848">http://192.168.0.4:49154/content/media/object_id/504575/res_id/0/ext/file.jpg</res>
<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=01;DLNA.ORG_CI=0" resolution="160x120">http://192.168.0.4:49154/content/media/object_id/504575/res_id/1/rct/EX_TH/ext/file.jpg</res>
```

Would it be usefull to insert also a JPEG_LRG for the original picture and JPEG_SM/JPEG_MED for the transcoded ones?

regards
Laurent

**Comment by whyman** [comment]
Yes, there is a difference between the transcoded and non-transcoded code paths it seems.

Its an area ripe for tidying up.

**Comment by whyman** [comment]
So, I have more of a look of this and its a hard one to address, as Gerbera doesn't really have access to the transcoded resources.

When transcoding all we have available is a profile and set of named pipes, which the scripts write into, and which is then passed off to the server to serve to a client.

This means as it stands currently we cannot access the data to read its properties before its sent to the client, and to get the data in time to render a menu item (before the content is requested) we would have transcode it, then read its properties.

Either that or we would need some way to ask the transcode script for details of the output, but again, that is an overhead of an exec per transcode profile at runtime. 

Most metadata stuff is done at import time to keep responses quick currently.

**Comment by whyman** [comment]
Didnt mean to close it!

**Comment by jkiusAlarus** [comment]
Hello
There is a resolution tag in the transcoding options in the config file. Maybe gerbera could apply the corresponding JPEG_XX to the transcoded res tag? It'd avoid all the dance to get back the actual resolution from the transcoded flow. I'd be up to the user to match the transcoding script with the option however..
Would it be a good idea?

Note also, as you can see from my original post, the original resource isn't either tagged with a JPEG_XX tag when you take the transcode path.

**Comment by whyman** [comment]
> Hello
> There is a resolution tag in the transcoding options in the config file. Maybe gerbera could apply the corresponding JPEG_XX to the transcoded res tag? It'd avoid all the dance to get back the actual resolution from the transcoded flow. I'd be up to the user to match the transcoding script with the option however..
> Would it be a good idea?

Yes

> Note also, as you can see from my original post, the original resource isn't either tagged with a JPEG_XX tag when you take the transcode path.

Good spot, that will need addressing also.

**Comment by KarlStraussberger** [comment]
I think this was added when reworking meta data display
