### ISSUE TITLE
UPNP_CLASS_CONTAINER assignments

### ISSUE THREAD

**Issue by tommyp-vr4** [gerbera/gerbera#548]
Not really an issue here.  More of a question/help needed.  Can't find any messageboards to help me out. 
I am retrofitting my custom import.js file to set up my controller's structure/layout.  I have a container of containers.  I'd like to do this is so I can have nicer eye candy for the containers instead of a yellow folder.  I *think* the UPNP_CLASS_CONTAINER defines the icons.  I could be wrong though.  

Q1 - Is there a way to assign a "UPNP_CLASS_CONTAINER_MUSIC_ALBUM", UPNP_CLASS_CONTAINER_MUSIC_ARTIST" or "UPNP_CLASS_CONTAINER_MUSIC_GENRE" to the containers?  I'd like to do it via my custom import.js if at all possible.  
Q2 - Also, some other server softwares are able to show a collage of album artwork on a container full of albums.  Is this possible with Gerbera too?

Here's a little ascii diagram to visually show what I'm trying to do:

container1             <------ how do I assign a UPNP_CLASS_CONTAINER here?
---container2        <------ how do I assign a UPNP_CLASS_CONTAINER here?
-----container2a
---------objects
-----container2b
---------objects
---container3
-----container3a
---------objects
-----container3a
---------objects
---container4
etc

**Comment by Kyle-B** [comment]
I've also been trying to sort this out, and as far as I can tell it's not possible to do cleanly at the moment. #480 has a partial solution, but does throw errors. It feels like this is currently a gap.

I'm also trying to a layout setup like:

Artists
-- Foo (UPNP_CLASS_CONTAINER_MUSIC_ARTIST)
---- Bar (UPNP_CLASS_CONTAINER_MUSIC_ALBUM)
------ Track1
------ Track2

**Comment by KarlStraussberger** [comment]
Fixed with #1218
