### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by TrashCoder1997** [gerbera/gerbera#552]
On my Samsung TV when I include a .srt file with the same name as the video, it will automatically use the subtitles. When I tried the same thing Gerbera, it plays the video fine, but there are no subtitles.

Does anybody else have this issue? I hope it will get fixed.

**Comment by whyman** [comment]
This is a known annoyance.

Try setting

`<protocolInfo extend="yes" dlna-seek="yes" samsung-hack="yes" />`

Under the server section of your `config.xml`

No guarantees, it might help, though.

**Comment by whyman** [comment]
Any success?

**Comment by TrashCoder1997** [comment]
I am very sorry for not responding for so long. I didn't receive your second message.
Yes, everything works flawlessly now.

**Comment by whyman** [comment]
Great news!
