### ISSUE TITLE
No album cover under object.container.album.musicAlbum

### ISSUE THREAD

**Issue by parkmino** [gerbera/gerbera#553]
I want to sort audio by track number, replaced 'object.item.audioItem.musicTrack' with 'object.container.album.musicAlbum'.
However album covers are not visible in audio.
Please advise me how to show album covers under 'object.container.album.musicAlbum'.

**Comment by whyman** [comment]
Tracks should be sorted by number by default?

**Comment by parkmino** [comment]
Tracks are sorted by name by default and I want to change it by track number.
If tracks are named as 01. bbb, 02. aaa an then it is OK, however if it is named bbb, aaa, then sorted reversed.

**Comment by KarlStraussberger** [comment]
Fixed with #1140
