### ISSUE TITLE
Error with libebml after compiling on Raspbian Buster

### ISSUE THREAD

**Issue by ItsMeMarc** [gerbera/gerbera#555]
I compiled and installed Gerbera for my Rasperry Pi 4 with Raspbian Buster according RedKage’s tutorial on [https://github.com/gerbera/gerbera/issues/218#issuecomment-354555006](https://github.com/gerbera/gerbera/issues/218#issuecomment-354555006). I had to install the packages `libebml-dev` and  `libmatroska-dev` in addition to finish compiling without errors.

This is the version number of my compilation:
```
sudo gerbera –version
Gerbera UPnP Server version 1.4.0alpha - http://gerbera.io/
```
When I start Gerbera with `sudo gerbera -c /etc/gerbera/config.xml -D` it seems to be as usual. But after a short time Gerbera stops working with the followeng error:
```
gerbera: /build/libebml-IZ1EDg/libebml-1.3.6/src/StdIOCallback.cpp:124: virtual void libebml::StdIOCallback::setFilePointer(int64, libebml::seek_mode): Zusicherung »Offset <= LONG_MAX« nicht erfüllt.
```
Does anybody know what I can do. Did I do anything wrong during compiling? Did I install a wrong libebml package?

Here are the last few lines of the debug output:
```
2019-12-22 19:08:05   DEBUG: [src/content_manager.cc:614] _rescanDirectory(): Rescanning location: /media/pi/[…]
2019-12-22 19:08:05   DEBUG: [src/content_manager.cc:1813] run(): running add file task with path /media/pi/[…] recursive: 1
2019-12-22 19:08:05   DEBUG: [src/singleton.cc:68] registerSingleton(): registering new singleton... - 6 -> 7
2019-12-22 19:08:05   DEBUG: [src/content_manager.cc:753] addRecursive(): Checking path /media/pi/[…]
2019-12-22 19:08:05   DEBUG: [src/content_manager.cc:771] addRecursive(): IS TASK VALID? [1], taskoath: [/media/pi/[…]]
2019-12-22 19:08:05   DEBUG: [src/content_manager.cc:753] addRecursive(): Checking path /media/pi/[…]
2019-12-22 19:08:05   DEBUG: [src/content_manager.cc:771] addRecursive(): IS TASK VALID? [1], taskoath: [/media/pi/[…]]
gerbera: /build/libebml-IZ1EDg/libebml-1.3.6/src/StdIOCallback.cpp:124: virtual void libebml::StdIOCallback::setFilePointer(int64, libebml::seek_mode): Zusicherung »Offset <= LONG_MAX« nicht erfüllt.
Abgebrochen
```
I would be happy, if somebody could tell me how to get Gerbera working.
Thanks.

**Comment by pamapa** [comment]
Hi

Thanks for reporting, i will have a look at it. In the meantime you can disable libebml/libmatroska by using cmake ... -DWITH_MATROSKA=0

**Comment by ItsMeMarc** [comment]
Hi

Thanks for your reply.

> you can disable libebml/libmatroska by using cmake ... -DWITH_MATROSKA=0

Ok, I will do it.

Here are the answers to your questions:

> How did you install libebml-dev and libmatroska-dev, via apt-get package manager?

Yes, I installed it via the apt-get package manager. The version numbers of the installed packages are:
```
apt list libebml-dev libmatroska-dev
libebml-dev/stable,now 1.3.6-2 armhf  [installiert]
libmatroska-dev/stable,now 1.4.9-1 armhf  [installiert]
```
> Are you using a 32bit or 64bit kernel?

I’m using a 32bit kernel.

Please let me know, if you need any more information to solve this issue.

**Comment by pamapa** [comment]
@ItsMeMarc
Can you verify if https://github.com/gerbera/gerbera/pull/560 fixes the problem?

**Comment by ItsMeMarc** [comment]
@pamapa 
It works now without any errors. Thank you very much.

**Comment by whyman** [comment]
Great!
