### ISSUE TITLE
introduce io-handler tell #542

### ISSUE THREAD

**Issue by count00zero** [gerbera/gerbera#561]
its now up with master + i have replaced ftell with ftello (for 32bit os)

_Originally posted by @pamapa in https://github.com/gerbera/gerbera/pull/542#issuecomment-568890793_

Hi there ...  this latest change leaves me with: 

```
... gerbera/src/metadata/ffmpeg_handler.cc:452:6: error: ‘data_size’ was not declared in this scope
  452 |     *data_size = (off_t)img->image_data_size;
```

**Comment by count00zero** [comment]
barked up the wrong tree, cause usually I am using whyman/gerbera not gerbera/gerbera :-)

**Comment by whyman** [comment]
Thanks for reporting!

I guess this shows we need to have the CI build with all the supported deps turned on, and on 32 bit as well -- I wil take a look at that.

It looks like `*data_size = (off_t)img->image_data_size;` just needs to be removed from `ffmpeg_handler.cc` as its not needed any more...

Maybe you could test and open a PR?

**Comment by count00zero** [comment]
Sorry for not replying ... I was on a short vacation .... I will continue with the other open issue ...
