### ISSUE TITLE
access to <directory location> by script?

### ISSUE THREAD

**Issue by nobanzai** [gerbera/gerbera#565]
Hi *,

is there any chance to access a "directory location" value by script?
I'd need the base for a file to make decisions regarding the tree.

TIA.

Bye.
Michael.

**Comment by whyman** [comment]
You can get the path of the file from [orig.location](http://docs.gerbera.io/en/latest/scripting.html#orig.location)>

Is that what you meant?

**Comment by nobanzai** [comment]
No, I need the base of the location, where gerbera started the search for this file.
I'd need it in a regexp. It is possible to get the desired result without the value from directory location, but it is much more complicated.

**Comment by KarlStraussberger** [comment]
Fixed with #1248
