### ISSUE TITLE
replace zmm:Ref/zmm::Object with std::shared_ptr or std::unique_ptr

### ISSUE THREAD

**Issue by pamapa** [gerbera/gerbera#567]
- [x] singleton.h/cc (replaced by injecting objects directly into depended classes via constructor, see #374)
- [x] content_manager.h/cc
- [x] config_manager.h/cc
- [x] storage/*
- [x] iohandler/*
- [x] metadata/*
- [x] request_handler.h/cc
- [x] subscription_request.h/cc
- [x] action_request.h/cc
- [x] cds_objects.h/cc
- [x] cds_resource.h/cc
- [x] autoscan*.h/cc
- [x] timer.h/cc
- [x] mxml/* (replaced by using https://pugixml.org)

**Comment by pamapa** [comment]
you can assign me

**Comment by pamapa** [comment]
@whyman:
i dont think its worth porting mxml to std. We should replace it with a standard xml library. What do you think? On the other hand mxml is not only used for the configuration part but also in the upnp code.
- possible candidate: https://pugixml.org
- others?

**Comment by whyman** [comment]
We already link to `libexpat` so could use it? Though its its C so not that nice to use. If you are going to swap it out, make sure to replace the expat as well mxml.

**Comment by pamapa** [comment]
done
