### ISSUE TITLE
Official support for genre - artist - album audio hierarchy

### ISSUE THREAD

**Issue by gaydenko** [gerbera/gerbera#576]
Hi!

Some tome ago I was struggling with custom scripts to get Genre - Artist - Albums-by-year (with tracks inside selected album only) audio hierarchy for exposed content, and some success was gained. Then there was a period without Gerbera. Now I'd like to restore Gerbera using, but just don't remember all those customization.

Is it possible to add the hierarchy support on the official level?

**Comment by whyman** [comment]
I doubt we would add this to the built in layout as it's possible with scripting.

That said we do ship a couple of js layouts, so we would happily accept another with this layout.

**Comment by gaydenko** [comment]
I play with this one.
[import_genre.js.zip](https://github.com/gerbera/gerbera/files/4023938/import_genre.js.zip)
