### ISSUE TITLE
Error: Directory Photo: Next pointer is out of bounds; ignored.

### ISSUE THREAD

**Issue by JohanvdS** [gerbera/gerbera#594]
The server stopped :( 
gerbera.service - Gerbera Media Server
   Loaded: loaded (/lib/systemd/system/gerbera.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2020-01-05 20:07:33 CET; 2s ago
     Docs: man:gerbera(1)
           https://gerbera.io/
  Process: 5939 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml $EXTRAARGS (code=exited, status=1/FAILURE)
 Main PID: 5939 (code=exited, status=1/FAILURE)
what is going on ? I cannot find it ?

thanks :)

**Comment by whyman** [comment]
Thanks for reporting! Whciht version are you running? Which action where you doing at the time?

**Comment by JohanvdS** [comment]
it was reading de dbase when i restart after this it will resume to update the dbase but stopped this as result. I am using kubuntu 18.04  
Gerbera UPnP Server version 1.3.5 - http://gerbera.io/

**Comment by JohanvdS** [comment]
I found out that the dbase is corrupt what can i do to replace the corrupt file and make a new one? I am new to this :) so need everything to find out :D

**Comment by whyman** [comment]
> found out that the dbase is corrupt what can i do to replace the corrupt file and make a new one? 

Assuming you are using sqlite you can delete the DB file in the config directory.

> ERROR: LibUPnP could not bind to socket.

This is because you already have another gerbera (or some other upnp service) running

**Comment by JohanvdS** [comment]
Thanks whyman, for repl

> > found out that the dbase is corrupt what can i do to replace the corrupt file and make a new one?
> 
> Assuming you are using sqlite you can delete the DB file in the config directory.
> 
> > ERROR: LibUPnP could not bind to socket.
> 
> This is because you already have another gerbera (or some other upnp service) running

thanks for reply; I deleted every dbase file. It is now fully functional working and discover a misconfig in chown file ~/.config/gerbera
