### ISSUE TITLE
Errors in building on FreeBSD 11.3 + some debug

### ISSUE THREAD

**Issue by dmist** [gerbera/gerbera#595]
Hi,

I have tried building on FreeBSD 11.3 (as a jail in FreeNAS) following the instructions given here: http://docs.gerbera.io/en/latest/compile.html

However it did not work. 

There were several problems I ran into, so I managed to get it right with some corrections that I detail here:

1. "pkg install wget git autoconf automake libtool taglib cmake gcc libav ffmpeg libexif pkgconf liblastfm gmake" ==> "liblastfm" is not available, used "liblastfm-qt5" instead
2. "cmake ../gerbera ..." => "CMake Error at CMakeLists.txt:541 (message): Matroska not found" ==> fixed with "pkg install libmatroska"
3. again: "Could NOT find INOTIFY" ==> fixed with "pkg install libinotify" (some warnings on kernel patches needed for fixing "Libinotify functionality on FreeBSD is missing support for...")
4. again: "/gerbera/src/util/process.h:46:15: error: unknown type name 'pid_t'" ==> fixed with "#include <sys/types.h>"
5. again: "/gerbera/src/main.cc:142:34: error: expected '(' for function-style cast or type construction std::optional<std::string> logfile;" ==> fixed with "#include \<optional\>" in main.cc
6. required support of C++17: maybe better use CLANG 7.0 instead of 6.0 (but is not default in the system), so installed with "pkg install llvm70" and added "-DCMAKE_CXX_COMPILER=/usr/local/llvm70/bin/clang" to the cmake command (as 1st argument not to mess up with CMake arguments): "cmake ../gerbera -DCMAKE_CXX_COMPILER=/usr/local/llvm70/bin/clang -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=0"
7. "/usr/bin/ld: undefined reference to symbol `ceilf@@FBSD_1.0' (try adding -lm)" AND "/usr/bin/ld: undefined reference to symbol `_ZNSt3__18ios_base5clearEj' (try adding -lc++)" ==> changed instruction in CMakeLists.txt for CLang with "set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++ -lm -lc++") ; generates lots of "'linker' input unused" but works.

Could you please review and incorporate the corrections to the source and build code so that it builds flawlessly on FreeBSD ?

Thanks & regards
David

**Comment by whyman** [comment]
Hi David,

Thanks for this and the various posted fixes. I am happy to accept a patch if you have one.

If not I will try and incorporate your suggestions over the next week or so, and look at getting a fbsd target added to the CI

**Comment by dmist** [comment]
Hi,
Thanks for your reply and the suggestion for a CI target (that would be awesome).
Also my apologies, as I was trying to make it work as fast as possible in "quick & dirty" mode ; unfortunately I am not acquainted with the patching system, so I am not able to provide such "clean" patch in the short term. 
My next step will be setting up the runtime managed as a system service, so I'll give more feedback soon about it.
Thanks & regards,
David

**Comment by whyman** [comment]
@dmist We are hoping to release 1.5 soon, it would be nice if you could test master on FBSD before we tag it.

**Comment by dmist** [comment]
> @dmist We are hoping to release 1.5 soon, it would be nice if you could test master on FBSD before we tag it.

@whyman Hi, no problem, tell me what to do.

**Comment by whyman** [comment]
Pull the code from the git master branch, then try and build and run it on your system, as you did above?

**Comment by dmist** [comment]
Ok, I'll see to it this weekend.

**Comment by whyman** [comment]
Great!

**Comment by dmist** [comment]
Hi,
sorry for the late update. 
Still working on this, needed more time than expected. Have compilation error which needs some more study for a graceful solution:  "/usr/local/include/fmt/core.h:902:20: error: invalid application of 'sizeof' to an incomplete type 'pthread'
    static_assert(!sizeof(T), "formatting of non-void pointers is disallowed");
                   ^~~~~~~~~
".
I hope solving this in the upcoming days.

**Comment by dmist** [comment]
Hi, didn't have much time, hit a few problems but made some progress:
1. prerequisite packages: "pkg install wget git autoconf automake libtool taglib cmake gcc libav ffmpeg libexif pkgconf liblastfm-qt5 gmake libmatroska libinotify libfmt spdlog pugixml"
2. update compiler to cmake 9.0 : "pkg install llvm90"
3. scripts: number of cpus: modify "../gerbera/scripts/install-pupnp.sh" "install-googletest.sh" "install-lastfm.sh" "install-taglib111.sh" : change "nproc" to "sysctl -n hw.ncpu"
4. scripts: name of OS: modify "install-duktape.sh" "install-lastfm.sh" "install-pugixml.sh" "install-pupnp.sh" : change ". /etc/os-release" to ID=$( uname | tr '[:upper:]' '[:lower:]' )
5. sh ../gerbera/scripts/install-pupnp.sh => ok
6. sh ../gerbera/scripts/install-duktape.sh => ok
7. compile: make use of clang 9.0 : cmake ../gerbera -DCMAKE_CXX_COMPILER=/usr/local/llvm90/bin/clang -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=0

==> stuck here with cmake error stack:
-- The CXX compiler identification is Clang 9.0.1
-- Check for working CXX compiler: /usr/local/llvm90/bin/clang
-- Check for working CXX compiler: /usr/local/llvm90/bin/clang -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include optional
-- Looking for C++ include optional - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - not found
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - found
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Failed
-- Performing Test CXX_FILESYSTEM_STDCPPFS_NEEDED
-- Performing Test CXX_FILESYSTEM_STDCPPFS_NEEDED - Failed
-- Performing Test CXX_FILESYSTEM_CPPFS_NEEDED
-- Performing Test CXX_FILESYSTEM_CPPFS_NEEDED - Failed
CMake Error at cmake/FindFilesystem.cmake:227 (message):
  Cannot Compile simple program using std::filesystem
Call Stack (most recent call first):
  CMakeLists.txt:272 (find_package)

==> if you have any pointers, that would be welcome, I'll continue looking for a workaround.

**Comment by dmist** [comment]
Ok I have the root cause: as of LLVM 9.0, linking to libc++fs is no longer required, cf. https://releases.llvm.org/9.0.0/projects/libcxx/docs/UsingLibcxx.html

==> hence the file FindFilesystem.cmake erroneously detects an error, whereas it should not try to link with the library for this compiler version. No time yet to fix it, but maybe should hint the original creators (it comes from https://github.com/vector-of-bool/CMakeCM/blob/master/modules/FindFilesystem.cmake , I presume ?)

**Comment by whyman** [comment]
The  CXX_FILESYSTEM_NO_LINK_NEEDED case should pass then, right?

**Comment by diizzyy** [comment]
I think as we can close this as both 1.6.4 and 1.7.0 compiles
https://www.freshports.org/net/gerbera/
