### ISSUE TITLE
Thanks whyman, for repl

### ISSUE THREAD

**Issue by JohanvdS** [gerbera/gerbera#602]
Thanks whyman, for repl

> > found out that the dbase is corrupt what can i do to replace the corrupt file and make a new one?
> 
> Assuming you are using sqlite you can delete the DB file in the config directory.
> 
> > ERROR: LibUPnP could not bind to socket.
> 
> This is because you already have another gerbera (or some other upnp service) running

thanks for reply; I deleted every dbase file. It is now fully functional working and discover a misconfig in chown file ~/.config/gerbera

_Originally posted by @JohanvdS in https://github.com/gerbera/gerbera/issues/594#issuecomment-572050309_

**Comment by JohanvdS** [comment]
It was working good, but this morning starting up the pc everything is back :( the dbase is not accessible again. It was not starting gerbera the dbase in .config/gerbera is chown root root I think something went wrong here

**Comment by JohanvdS** [comment]
This is what i found 

gerbera.service - Gerbera Media Server
   Loaded: loaded (/lib/systemd/system/gerbera.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2020-01-09 05:55:37 CET; 1s ago
     Docs: man:gerbera(1)
           https://gerbera.io/
  Process: 21713 ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml $EXTRAARGS (code=exited, status=1/FAILURE)
 Main PID: 21713 (code=exited, status=1/FAILURE)

gerda-johan@gerda-johan-MS-7982:~$ gerbera
2020-01-09 05:57:44    INFO: Gerbera UPnP Server version 1.3.5 - http://gerbera.io/
2020-01-09 05:57:44    INFO: ===============================================================================
2020-01-09 05:57:44    INFO: Gerbera is free software, covered by the GNU General Public License version 2
2020-01-09 05:57:44    INFO: Copyright 2016-2019 Gerbera Contributors.
2020-01-09 05:57:44    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
2020-01-09 05:57:44    INFO: ===============================================================================
2020-01-09 05:57:44    INFO: Loading configuration from: /home/gerda-johan/.config/gerbera/config.xml
2020-01-09 05:57:44    INFO: Checking configuration...
2020-01-09 05:57:44    INFO: Setting filesystem import charset to UTF-8
2020-01-09 05:57:44    INFO: Setting metadata import charset to UTF-8
2020-01-09 05:57:44    INFO: Setting playlist charset to UTF-8
2020-01-09 05:57:44    INFO: Configuration check succeeded.
2020-01-09 05:57:44   ERROR: Error while accessing sqlite database file (/home/gerda-johan/.config/gerbera/library.db): Toegang geweigerd
Exception raised in [src/storage/sqlite3/sqlite3_storage.cc:94] init(): Error while accessing sqlite database file (/home/gerda-johan/.config/gerbera/library.db): Toegang geweigerd
9/01/20 05:56	gerda-johan-MS-7982	systemd[1]	Stopped Gerbera Media Server.
9/01/20 05:56	gerda-johan-MS-7982	systemd[1]	Started Gerbera Media Server.
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Gerbera UPnP Server version 1.3.5 - http://gerbera.io/
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: ===============================================================================
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Gerbera is free software, covered by the GNU General Public License version 2
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Copyright 2016-2019 Gerbera Contributors.
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: ===============================================================================
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Loading configuration from: /etc/gerbera/config.xml
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Checking configuration...
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Setting filesystem import charset to UTF-8
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Setting metadata import charset to UTF-8
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Setting playlist charset to UTF-8
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19    INFO: Configuration check succeeded.
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	2020-01-09 05:56:19   ERROR: Error while accessing sqlite database file (/home/gerda-johan/.config/gerbera/library.db): Toegang geweigerd
9/01/20 05:56	gerda-johan-MS-7982	gerbera[21902]	Exception raised in [src/storage/sqlite3/sqlite3_storage.cc:94] init(): Error while accessing sqlite database file (/home/gerda-johan/.config/gerbera/library.db): Toegang geweigerd
9/01/20 05:56	gerda-johan-MS-7982	systemd[1]	gerbera.service: Main process exited, code=exited, status=1/FAILURE
9/01/20 05:56	gerda-johan-MS-7982	systemd[1]	gerbera.service: Failed with result 'exit-code'.
9/01/20 06:01	gerda-johan-MS-7982	systemd[1]	gerbera.service: Service hold-off time over, scheduling restart.
9/01/20 06:01	gerda-johan-MS-7982	systemd[1]	gerbera.service: Scheduled restart job, restart counter is at 784.
9/01/20 06:01	gerda-johan-MS-7982	systemd[1]	Stopped Gerbera Media Server.
9/01/20 06:01	gerda-johan-MS-7982	systemd[1]	Started Gerbera Media Server.
9/01/20 06:01	gerda-johan-MS-7982	wpa_supplicant[1069]	wlp3s0: CTRL-EVENT-SCAN-FAILED ret=-95 retry=1
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Gerbera UPnP Server version 1.3.5 - http://gerbera.io/
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: ===============================================================================
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Gerbera is free software, covered by the GNU General Public License version 2
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Copyright 2016-2019 Gerbera Contributors.
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: ===============================================================================
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Loading configuration from: /etc/gerbera/config.xml
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Checking configuration...
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Setting filesystem import charset to UTF-8
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Setting metadata import charset to UTF-8
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Setting playlist charset to UTF-8
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03    INFO: Configuration check succeeded.
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	2020-01-09 06:01:03   ERROR: Error while accessing sqlite database file (/home/gerda-johan/.config/gerbera/library.db): Toegang geweigerd
9/01/20 06:01	gerda-johan-MS-7982	gerbera[22175]	Exception raised in [src/storage/sqlite3/sqlite3_storage.cc:94] init(): Error while accessing sqlite database file (/home/gerda-johan/.config/gerbera/library.db): Toegang geweigerd
9/01/20 06:01	gerda-johan-MS-7982	systemd[1]	gerbera.service: Main process exited, code=exited, status=1/FAILURE
9/01/20 06:01	gerda-johan-MS-7982	systemd[1]	gerbera.service: Failed with result 'exit-code'.

**Comment by JohanvdS** [comment]
I believe this is the issue but not sure. http://192.168.0.147:49152/ which is the main server which i can start but after rebooting the dbase is not accessible. But I made a new dbase file and start the gerbera in my own profile It worked, but after rebooting not accessible. dbase chown root root  I saw another point which was **http://192.168.0.5:49152** I believe this is ment to start a user dbase, but won't work lol But i saw something it was for vmnet very strange for me :)


a lot of these i got too
9/01/20 07:32	gerbera	Warning: Directory Image, entry 0x0111: Strip 527 is outside of the data area; ignored.
9/01/20 07:32	gerbera	Warning: Directory Image, entry 0x0111: Strip 528 is outside of the data area; ignored.
9/01/20 07:32	gerbera	Warning: Directory Image, entry 0x0111: Strip 529 is outside of the data area; ignored.
9/01/20 07:32	gerbera	Warning: Directory Image, entry 0x0111: Strip 530 is outside of the data area; ignored.
9/01/20 07:32	gerbera	Warning: Directory Image, entry 0x0111: Strip 531 is outside of the data area; ignored.
9/01/20 07:32	gerbera	Warning: Directory Image, entry 0x0111: Strip 532 is outside of the data area; ignored.
9/01/20 07:32	gerbera	Warning: Directory Image, entry 0x0111: Strip 533 is outside of the data area; ignored.
9/01/20 07:32	gerbera	Warning: Directory Image, entry 0x0111: Strip 534 is outside of the data area; ignored.

**Comment by whyman** [comment]
When it runs under systemd it will run as a dedicated user (normally). The user doesnt have permission to read your home directory for sensible reasons.

You will need to update your config so that the DB file is in some location writable by the "gerbera" user (usually somehting like `/var/lib/gerbera`)

**Comment by JohanvdS** [comment]
I see something else. It gives me another ip 192.168.5.1 I have installed vmware and there is something it links to that vmnet when i start gerbera in root it gives me the 192.168.0.147 and i can acces everything because it is the localhost



-- 
 Veilig verzonden met Tutanota. Reserveer je versleutelde, advertentievrije mailbox: 
 https://tutanota.com


9 jan. 2020 20:37 door notifications@github.com:

**Comment by whyman** [comment]
You can specify an address or an interface to bind to by passing `--ip` or `--interface`, if needed.
