### ISSUE TITLE
mp4 video from m3u  playlist file is recognized as audio

### ISSUE THREAD

**Issue by g79petova** [gerbera/gerbera#605]
I tried different approaches to change the config file but to no avail. Which leads me to think that it is good to ship with a program a config that opens and maintains all formats instead of looking for a way to overcome it on its own.

**Comment by whyman** [comment]
Have a look at `addPlaylistItem()` in the `playlist.js` file.

It is hardcoded to assume the mimetypes.

Just need to make sure the correct stuff is passed to `addCdsObject()` which actually adds the info to the DB.

**Comment by g79petova** [comment]
Yesq it is q i see in common.js -
`if (mimetype == 'audio/x-mpegurl')
        return 'm3u';`
then in playlist.js -
` exturl.mimetype = 'audio/mpeg';`

So i tray to rewrite but no luk..

**Comment by g79petova** [comment]
I'm implementing an example playlist for experiments
`#EXTM3U
#EXTINF:0,Какво трябва да знаеш за спорта?
https://download-a.akamaihd.net/files/content_assets/b8/502018215_BL_cnt_1_r720P.mp4
#EXTINF:0,Преди да пиеш, помисли
https://download-a.akamaihd.net/files/content_assets/44/502017872_BL_cnt_1_r720P.mp4
#EXTINF:0,Как да спреш клюките?
https://download-a.akamaihd.net/files/content_assets/d6/502016241_BL_cnt_1_r720P.mp4
#EXTINF:0,Устоявай на натиска от околните!
https://download-a.akamaihd.net/files/content_assets/1b/502015143_BL_cnt_1_r720P.mp4
#EXTINF:0,Използвай разумно социалните мрежи
https://download-a.akamaihd.net/files/content_assets/5b/502014276_BL_cnt_1_r720P.mp4
#EXTINF:0,Какъв е истинският приятел?
https://download-a.akamaihd.net/files/content_assets/14/502013393_BL_cnt_1_r720P.mp4
#EXTINF:0,Как да се защитиш, без да използваш сила
https://download-a.akamaihd.net/files/content_assets/35/502013189_BL_cnt_1_r720P.mp4`

**Comment by whyman** [comment]
You can change the `playlist.js` to do something else, if you want, thats the idea!

**Comment by g79petova** [comment]
i change : 
`if (mimetype == 'video/x-mpegurl') return 'm3u';`
then in playlist.js -
`exturl.mimetype = 'video/mpeg';`
and in config.xml i add line
`<map from="mp4" to="video/mpeg"/>`
but it is not correct for my 
Any suggestions ...?

**Comment by gitchomik** [comment]
Hi, 

I have the same issue on v1.9.2.

```addPlaylistItem()``` **ignores** ```exturl.mimetype``` and also ```exturl.protocol```
probably when ```exturl.objectType = OBJECT_TYPE_ITEM_EXTERNAL_URL```
the problem is that protocolInfo is based on ```playlist.mimeType``` (in this case ```audio/x-mpegurl```)

protocolInfo should be build based on ```exturl.mimeType``` NOT the ```playlist.mimeType```

**Comment by KarlStraussberger** [comment]
Ok folks, there is the first draft for this. You can add another colon in in the EXTINF line after which the mimetype can be supplied.

This is no official extension of m3u files so you may get errors with other players

**Comment by KarlStraussberger** [comment]
You can als switch to pls playlists which are a bit more flexible with respect to extensions or convert to asx playlists where you may use <param name="mimetype" ..> and <param name="protocol" ..>

**Comment by KarlStraussberger** [comment]
> @KarlStraussberger
> asx playlists works well but without "protocol" support probably the problem is in file common.js typo ```entry.ptotocol```
> 
> 

Oops, going to fix that. Thank you!
