### ISSUE TITLE
Master: files do not play

### ISSUE THREAD

**Issue by bouwew** [gerbera/gerbera#612]
Hi,

Recently, also just now, I've updated to the latest master version.
When trying to play a music file on my Yamaha receiver it shows: Access denied.
When trying to play a movie file on my LG tv it shows: Your device is disconnected. Please check the connection status.

When I create a build based on the latest release-version (1.4.0-1), all works fine.
Unfortunately I cannot use the release-version as it doesn't give me subtitles on my tv.
I used to be on the master-version but hadn't updated during several weeks.

So, something got broken recently.

**Comment by whyman** [comment]
We have made some pretty big changes lately in master, so I am not that surprised there are bugs.

That said, 1.4 should work for you. What changes do you need to make for your subtitles to work?

**Comment by whyman** [comment]
If you can provide a log, or ideally a backtrace from the crash, that would be super helpful!

**Comment by bouwew** [comment]
Yes, version 1.4 works for me, meaning it plays music and movie files without any issues.

About the subtitles working, I'm a bit lost, maybe version 1.4 was newer than the previous master-version that was on my system. Because with version 1.4 it does not show any subtitle-option while there is a separate srt-file available with the same name as the MKV-file I am playing. 

Also, there is no crash, gerbera keeps running, nothing is shown when I check the status of the gerbera.service.

**Comment by whyman** [comment]
@bouwew no problem!
