### ISSUE TITLE
Advertised address from Docker container?

### ISSUE THREAD

**Issue by scbash** [gerbera/gerbera#624]
Thanks for resurrecting MediaTomb! I used it many years ago and I'm excited to start using (and hacking) it again!

Hopefully this is a quick question: when I run the Gerbera Docker container on my Synology NAS using the default bridge networking, Gerbera advertises the Docker container IP address rather than the NAS. Other devices see Gerbera's advertisements, but fail to connect (because they can't route to the Docker IP address?). Host networking works perfectly.

Does bridge networking work for other people? I'm not sure if this is a Gerbera, Docker, or Synology problem... Thanks!

**Comment by whyman** [comment]
I dont think the default docker bridge will work as AFAIK it does a NAT on the way out, which is will then mean that the address in our messages is wrong as you've identified.

Glad to see host networking works as expected. `macvlan` should work too (in my head at least)

**Comment by scbash** [comment]
Glad to know I'm not missing something obvious 🙂  Thanks!
