### ISSUE TITLE
cleanup various small stuff

### ISSUE THREAD

**Issue by pamapa** [gerbera/gerbera#631]
- [x] constify where possible: "std::string str" -> "const std::string& str" (done by @neheb)
- [x] replace getValueOrDefault + !string_ok with find iterator
```
    std::string orchestra = getValueOrDefault(meta, MetadataHandler::getMetaFieldName(M_ORCHESTRA));
    if (!string_ok(orchestra)) {
       orchestra = "None";
    }
    ->
    auto it = meta.find(MetadataHandler::getMetaFieldName(M_ORCHESTRA));
    std::string orchestra = it != meta.end() && !it->second.empty() ? it->second : "None";
```
- [x] simplify loops (done by @neheb)
```
    for (size_t i = 0; i < arr.size(); i++) {
    ->
    for (auto const& a: arr) {
```
- [x] replace string_ok() and string_ok_ex() with str.empty()...
- [x] replace std::stringstream with std::ostringstream (output only)

**Comment by pamapa** [comment]
you can assign me

**Comment by neheb** [comment]
Noe that I only ran clang-tidy. There might be more opportunity when changing manually.

**Comment by pamapa** [comment]
ok, i will search through and fix remaining ones

**Comment by neheb** [comment]
There's also C++17's strinv_view that could also be used.
