### ISSUE TITLE
make more use of std::filesystem

### ISSUE THREAD

**Issue by pamapa** [gerbera/gerbera#632]
we can eliminate quite a lot of util or static functions, that deal with dirname, basename, normalize, etc... by using std::filesystem.

**Comment by pamapa** [comment]
you can assign me

**Comment by pamapa** [comment]
I am planing to replace "std::string path" in methods + members with "fs::path path" by using:
```
#include <filesystem>
using fs = std::filesystem;

old:
int SQLStorage::createContainer(int parentID, std::string name, std::string path...
new:
int SQLStorage::createContainer(int parentID, std::string name, fs::path path...
```

i will add <string>, <memory> + <filesystem> includes to common.h, as we anyway need those mostly everywhere now

**Comment by whyman** [comment]
Can we keep the includes to the files that need it?

**Comment by pamapa** [comment]
ok, will do so

**Comment by pamapa** [comment]
done
