### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by Shmik2003** [gerbera/gerbera#640]
I'm trying install the newest commit that fixed one very annoying bug. I built old version already and removed it now. But the building of new version is failing. I have Raspbian Buster on Raspberry Pi 3. 
CMake command
```cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=0 -WITH_FFMPEGTHUMBNAILER=1 -WITH_EXIF=1```
CMake output

```-- Looking for BSD native UUID
-- Looking for libuuid
-- Looking for libuuid - found
-- Found Sqlite3: /usr/lib/arm-linux-gnueabihf/libsqlite3.so
-- Looking for native inotify
-- Looking for native inotify - found
-- Found TagLib: -L/usr/local/lib -ltag
-- Found MAGIC: /usr/lib/arm-linux-gnueabihf/libmagic.so  
-- Checking for modules 'libavformat;libavutil'
--   Found libavformat, version 58.20.100
--   Found libavutil, version 56.22.100
-- Found EXIF: /usr/lib/arm-linux-gnueabihf/libexif.so (found version "") 
-- Found EBML: /usr/lib/arm-linux-gnueabihf/libebml.so  
-- Found MATROSKA: /usr/lib/arm-linux-gnueabihf/libmatroska.so  
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/romus/git/gerbera/build
```

make -j4 output
```[  3%] Building CXX object CMakeFiles/libgerbera.dir/src/autoscan.cc.o
[  3%] Building CXX object CMakeFiles/libgerbera.dir/src/autoscan_inotify.cc.o
[  3%] Building CXX object CMakeFiles/libgerbera.dir/src/cds_objects.cc.o
[  4%] Building CXX object CMakeFiles/libgerbera.dir/src/action_request.cc.o
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[2]: *** [CMakeFiles/libgerbera.dir/build.make:89: CMakeFiles/libgerbera.dir/src/autoscan_inotify.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/libgerbera.dir/all] Error 2
make: *** [Makefile:130: all] Error 2```

There are a lot of time was spent between 4% of make and c++ fatal error
How to fix it? Which dependency I don't installed?

**Comment by Shmik2003** [comment]
aww... sorry, it's my first issue report... how to format code? :D

**Comment by whyman** [comment]
I would make sure you start with a fresh build folder. It looks like you aren't building from scratch.

**Comment by Shmik2003** [comment]
Yes, I tried to build it earlier with MySQL, but I don't installed it and I tried again without MySQL. After this report I wanted to check will it build again or not. A fresh building given the same effect. I can do it again if you want to make sure

**Comment by Shmik2003** [comment]
> I would make sure you start with a fresh build folder. It looks like you aren't building from scratch.
Fresh CMake
`
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include optional
-- Looking for C++ include optional - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - found
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - found
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED
-- Performing Test CXX_FILESYSTEM_NO_LINK_NEEDED - Failed
-- Performing Test CXX_FILESYSTEM_STDCPPFS_NEEDED
-- Performing Test CXX_FILESYSTEM_STDCPPFS_NEEDED - Success
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST
-- Performing Test ICONV_SECOND_ARGUMENT_IS_CONST - Failed
-- Found Iconv: /usr/lib/arm-linux-gnueabihf/libc.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Looking for BSD native UUID
-- Looking for libuuid
-- Looking for libuuid - found
-- Found UUID: TRUE  
-- Looking for native LFS support
-- Looking for native LFS support - not found
-- Looking for LFS support using  -D_LARGEFILE_SOURCE;-D_FILE_OFFSET_BITS=64 ;
-- Looking for LFS support using  -D_LARGEFILE_SOURCE;-D_FILE_OFFSET_BITS=64 ; - found
-- Found LFS: TRUE  
-- Found UPnP: /usr/local/lib/libupnp.so (found version "1.8.6") 
-- Found PUGIXML: /usr/lib/arm-linux-gnueabihf/libpugixml.so  
-- Found Sqlite3: /usr/lib/arm-linux-gnueabihf/libsqlite3.so
-- Looking for native inotify
-- Looking for native inotify - found
-- Found Duktape: /usr/local/lib/libduktape.so  
-- Found TagLib: -L/usr/local/lib -ltag
-- Found MAGIC: /usr/lib/arm-linux-gnueabihf/libmagic.so  
-- Checking for modules 'libavformat;libavutil'
--   Found libavformat, version 58.20.100
--   Found libavutil, version 56.22.100
-- Found EXIF: /usr/lib/arm-linux-gnueabihf/libexif.so (found version "") 
-- Found EBML: /usr/lib/arm-linux-gnueabihf/libebml.so  
-- Found MATROSKA: /usr/lib/arm-linux-gnueabihf/libmatroska.so  
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.11") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/romus/git/gerbera/build
`
make -j4 have the same output

**Comment by whyman** [comment]
`c++: fatal error: Killed signal terminated program cc1plus` Sounds like you are running out of memory? Do you have a swap file? How does your memory usage look when you are compiling?

**Comment by Shmik2003** [comment]
> `c++: fatal error: Killed signal terminated program cc1plus` Sounds like you are running out of memory? Do you have a swap file? How does your memory usage look when you are compiling?

"free -m" output:
`              total        used        free      shared  buff/cache   available
Mem:            747         130          32           5         584         558
Swap:            99          21          78
`

**Comment by whyman** [comment]
Can you try with say 1G swap?

**Comment by Shmik2003** [comment]
> Can you try with say 1G swap?

Thanks for advice, I'll try it

**Comment by whyman** [comment]
If it fails again please attach full logs :slightly_smiling_face:

**Comment by Shmik2003** [comment]
> If it fails again please attach full logs slightly_smiling_face

Thanks again, after 1G swap and +256M for RAM make process reached 30% instead of 4%  when it crashed. I don't know, will it build and install. I think, Gerbera will build ok.

**Comment by Shmik2003** [comment]
> If it fails again please attach full logs

It's built OK. Many thanks for help

**Comment by whyman** [comment]
Great news! :tada:

**Comment by ignacioiky** [comment]
que es lo que hizo

**Comment by ignacioiky** [comment]
alguno me puede ayudar a hacer ese intercmbio no se mucho de eso pero quisiera saber

**Comment by KarlStraussberger** [comment]
please ask your question in english and use a new issue for your topic.
