### ISSUE TITLE
gerbera failure when vmplayer is installed

### ISSUE THREAD

**Issue by JohanvdS** [gerbera/gerbera#642]
When vmplayer is installed gerbera gives another ip 
example localhost 192.168.0.147:49152/ but when i start gerbera when vmplayer installed it gives 192.168.1.5:49152 and is not working. (gerbera -ip is not working)
Is there a file where I can change this address ? the symlinks on the desktop gives now these ip adress so i made a link in the browser ;)
I did sudo route add -net 239.0.0.0 netmask 255.0.0.0 enp2s0 but still not working. 
sudo route del -net 239.0.0.0 netmask 255.0.0.0 vmnet8 
sudo route del -net 239.0.0.0 netmask 255.0.0.0 vmnet1 but it said it isn't there anymore for both.
even gerbera ip is not working.
then i tried gerbera to start from root. It worked, but it gives the dbfiles etc root acces. and af course after reboot this is also not working anymore.
sudo systemctl status gerbera
gives failure

So I removed Vmplayer and everything is backonline
and gives the dbfile the rights it is normally used. Everything is working, but vmplayer is gone LOL  Till now i am happy with gerbera and not happy with vmplayer hahahahaha

Something went wrong, but couldn't find any solution. Hopefully someone can give me hints :) Then i tried again, but i like so much music 50.000 mp3 (flac) is what i like to hear :) this because of an internetradio i was owner of it. 

greetings

Johan

**Comment by whyman** [comment]
Hi Johan, you should be able to set the IP that gerbera uses by passing the `--ip 192.168.0.147` argument.

**Comment by JohanvdS** [comment]
it works thanks :) Is there a possibility to see who is listening and what ? with 50.000 mp3 and some video's I want to know this ?

**Comment by JohanvdS** [comment]
it works thanks :) Is there a possibility to see who is listening and what ? with 50.000 mp3 and some video's I want to know this ?

**Comment by whyman** [comment]
We dont keep any information about the client devices currently, sorry!
