### ISSUE TITLE
External Subtitles LG TVs

### ISSUE THREAD

**Issue by Neocazen** [gerbera/gerbera#676]
Hi, guys.
   I end up touching on this subject again, because the other topics that follow this line are closed. Excuse me.
   I have Gerbera version 1.4.0, upnp 1.8.6 running on Ubuntu 19.10 and the external subtitles are not played on my LG Led TV model LB5800(no system WebOS). I'm sending data from wireshark, maybe something can be discovered that ends up helping others. Only this is missing for Gerbera to be perfect.
   Thanks.
https://my.pcloud.com/publink/show?code=XZvk2skZ2iI5YERKhAjuI4QVQYsPVVASuuAk

**Comment by whyman** [comment]
Did you get it to work, or?

**Comment by Neocazen** [comment]
No.

**Comment by pamapa** [comment]
does the fix for #744 help you too?

**Comment by Neocazen** [comment]
> does the fix for #744 help you too?

I will test as soon as possible. Thanks.

**Comment by whyman** [comment]
@Neocazen Did you get a chance to try the possible fix?

**Comment by Neocazen** [comment]
> @Neocazen Did you get a chance to try the possible fix?

Is the code embedded in the master or should I just add the code in 1.4? Taking a while because I want to install from Zero on my new Ubuntu.

**Comment by whyman** [comment]
Please try a master git build. We want to release 1.5 soon, so would be good to know.

**Comment by Neocazen** [comment]
> Please try a master git build. We want to release 1.5 soon, so would be good to know.

ok

**Comment by Neocazen** [comment]
> > Please try a master git build. We want to release 1.5 soon, so would be good to know.
> 
> ok

**Comment by Neocazen** [comment]
> > > Please try a master git build. We want to release 1.5 soon, so would be good to know.
> > 
> > 
> > ok

Hello Whyman. It was not clear whether the code was on the master or not. But if it is, it didn't work. There is not so much problem just put it in the video container.

**Comment by Neocazen** [comment]
> Please try a master git build. We want to release 1.5 soon, so would be good to know.

Hello Whyman. It was not clear whether the code was on the master or not. But if it is, it didn't work. There is not so much problem just put it in the video container.
