### ISSUE TITLE
Should not override interface flags for spdlog

### ISSUE THREAD

**Issue by marillat** [gerbera/gerbera#691]
Hi,
I reported this bug https://bugs.debian.org/951474

The Debian maintainer tell me the problem is in  CMakeLists.txt added in commit fe81e5f
This line should be removed:

```add_compile_definitions("SPDLOG_FMT_EXTERNAL")```

This fix the build for several architectures (armel, armhf, arm64 and powerpc).

**Comment by whyman** [comment]
Ah, well, we just need to improve the CMake so that it complains if the fmt is not >=6.

**Comment by marillat** [comment]
/usr/lib/x86_64-linux-gnu/cmake/fmt/fmt-config-version.cmake
seems to be here for that.

**Comment by ytimenkov** [comment]
OOC: which feature of v6 is required?

**Comment by whyman** [comment]
Nothing that we are using directly, but for compatibility with spdlog

**Comment by pamapa** [comment]
should be fixed now with above commit

**Comment by ytimenkov** [comment]
That was not merged. I'm cooking another one 😐
