### ISSUE TITLE
error: File '/home/xxx/.gerbera/js' does not exist!

### ISSUE THREAD

**Issue by count00zero** [gerbera/gerbera#693]
Hi there,

since one of the last commits (3 or so ago), I cant' get gerbera to run; I am always confronted with that: `error: File '/home/xxx/.gerbera/js' does not exist!`

Do you have an clue?
If I create an empty file, gerbera starts, but doesn't work properly (no file is imported).
If I create a symbolic link, it doesn't work (but older versions do).

I am clueless ....

**Comment by whyman** [comment]
Hmm sorry about that, can you post a debug log?

**Comment by whyman** [comment]
Also, thanks for running a master build!

**Comment by count00zero** [comment]
unfortunately, I don't get more detailed information ..
It has to do something with the definition of my gerbera home path ...

**Comment by count00zero** [comment]
I was able to replicate and narrow down the error when using a newly generated config file!
As soon as I switch the `<virtual-layout type="builtin"> to <virtual-layout type="js">` (as per documentation), the error occurs!
`error: File '/home/xxx/.config/gerbera/js' does not exist!`

**Comment by count00zero** [comment]
ahhh ... and when using <virtual-layout type="builtin">, gerbera starts, but all my music-files (mp3, flac, etc.) [I am only importing those] receive a "file ignored" when adding my music path => no music-files in the database ... WEIRD!

**Comment by pamapa** [comment]
@count00zero (If I create a symbolic link, it doesn't work (but older versions do)):
Yes this has changed. With "std::filesystem usage". In "ConfigManager::resolvePath" "fs::is_regular_file" is used.

@whyman:
We can add symbol link support again for configuration files: fs::is_regular_file || fs::is_symlink => good
Should i provide a patch?

**Comment by count00zero** [comment]
yepp and thanks, that did it!
But it is still some sort of a mystery to me :)
When using `<virtual-layout type="js">`, I point to my modified import script: `/usr/local/share/gerbera/js/import_structured.js` BUT STILL ... gerbera NEEDS the link to that file in my config-home-dir with the simple name "js" ... if that link (or file) doesn't exist, gerbera won't start!

**Comment by whyman** [comment]
You should be able to give it a normal file path and have it work

**Comment by count00zero** [comment]
```
<virtual-layout type="js">
        <import-script>/usr/local/share/gerbera/js/import_structured.js</import-script>
</virtual-layout>
```
The above worked until a few pulls ago, then that started:  `error: File '/home/xxx/.gerbera/js' does not exist!`
To have gerbera start again, I now had to make a symbolic link to my import script `js -> /usr/local/share/gerbera/js/import_structured.js`.

gerbera starts and runs and imports now, but unfortunately it doesn't really work, because no audio-file is presented via DLNA/uPNP although they are visible via the web-gui ....

**Comment by whyman** [comment]
@count00zero Thanks for reporting the `master` bugs, its appreciated. Shame its not working for you, though.

**Comment by count00zero** [comment]
OK, of course :)
