### ISSUE TITLE
#628 introduced bug (location import script not found)

### ISSUE THREAD

**Issue by joszon** [gerbera/gerbera#709]
Already described in [https://github.com/gerbera/gerbera/issues/693]().
The fix did not solved this issue, as stated by the issuer.
The bug is introduced with [https://github.com/gerbera/gerbera/issues/628]().
In management.cc, line 788 the code:

`temp = resolvePath(temp, true, temp == "js");`

is inserted.
This was not described or mentioned in the diff.
The result of this new code is that resolvePath of  variable “temp” (value: ‘js”) is returned, instead of variable “script_path”.
Please change management.cc line 782 in the current tree to:

`temp = resolvePath(script_path, true, temp == "js");`

See also attached file.
[diff.txt](https://github.com/gerbera/gerbera/files/4256690/diff.txt)

**Comment by pamapa** [comment]
i guess this has been fixed with this commit https://github.com/gerbera/gerbera/commit/f797570a9f9f7b8a9b84e640fb3d7c904f63f10d ?

**Comment by joszon** [comment]
Proposed fix seems to be implemented.
 [f797570](https://github.com/gerbera/gerbera/commit/f797570a9f9f7b8a9b84e640fb3d7c904f63f10d)
Would be nice that is was mentioned here by [Karl](https://github.com/KarlStraussberger).

**Comment by whyman** [comment]
Can you open a PR for this?

**Comment by whyman** [comment]
Are you happy to close this then @joszon ?
