### ISSUE TITLE
/media is excluded from available directories

### ISSUE THREAD

**Issue by Rogach** [gerbera/gerbera#717]
In commit b99a548 directory excludes were introduced (in order to avoid bothering users with system directorties). The exclude list contains the [`/media` directory](https://github.com/gerbera/gerbera/blob/master/src/web/directories.cc#L73) - was that intentional?

For example I have my external disk mounted at /media, and previously I was streaming video directly from it.

**Comment by pamapa** [comment]
After the [filesystem hierarchy standard (FHS)](http://www.pathname.com/fhs/pub/fhs-2.3.html#MEDIAMOUNTPOINT) is the /media where the Linux system mounts removable media. As the name says removable media could actually be removed and then those media files are missing, that is why i excluded it first hand.

I will provide a patch to allow /media again.

**Comment by whyman** [comment]
I guess the ignored filepaths should move to the config xml

**Comment by pamapa** [comment]
the remaining paths should be safe + there are already too many options in config.xml :-)
