### ISSUE TITLE
fix issues found with cppclean

### ISSUE THREAD

**Issue by pamapa** [gerbera/gerbera#730]
https://github.com/myint/cppclean

cppclean can find the following:
- Classes with virtual methods, no virtual destructor, and no bases
- Global/static data that are potential problems when using threads
- Functions that are declared but not defined
- Unnecessary forward class declarations
- Unnecessary function declarations
- Undeclared function definitions
- Unnecessary #includes in header files
  - No direct reference to anything in the header
  - Header is unnecessary if classes were forward declared instead
- Inconsistent case in #includes (foo.h versus Foo.h)

**Comment by pamapa** [comment]
i plan to cleanup header handling like this:

example.cc:
```cpp
/*
...
*/
/// \file import_script.cc

#include "example.h"

#include "other_project_headers.h"

#include <system headers_last>
...
```

Like this our header files are self contained and do not depend included in a specific order.

**Comment by whyman** [comment]
Yay for the include tidy!

**Comment by whyman** [comment]
Once it's done consider a GitHub action to make sure it stays that way.

**Comment by pamapa** [comment]
cppclean show many false positive, like this we can not add it to CI :-(
