### ISSUE TITLE
Video file is not recognized (Log says: Not a file)

### ISSUE THREAD

**Issue by ItsMeMarc** [gerbera/gerbera#737]
Hi,

On my Raspberry Pi 4 (Raspbian Buster, 32 bit kernel) I recognized another strange behaviour.

In a directory there are four mkv files. I can play all of them in VLC without any problems.
```
pi@rpi4:/media/pi/raid/Videos/TEMP/Temp $ ls -lh --time-style=long-iso
insgesamt 8,0G
-rwxr--r-- 1 pi pi 2,5G 2014-03-29 09:27 1.mkv
-rwxr--r-- 1 pi pi 1,5G 2014-03-28 17:24 2.mkv
-rwxr--r-- 1 pi pi 1,7G 2014-03-29 10:36 3.mkv
-rwxr--r-- 1 pi pi 2,3G 2014-03-29 09:29 4.mkv
```
But gerbera only recognizes 2.mkv and 3.mkv as valid video files. For the other two files the debug log says `Not a file`. What does this mean? Is there a way to get some more debug information?
```
2020-03-11 17:35:34  debug: [content_manager.cc:731] addRecursive(): Checking path /media/pi/raid/Videos/TEMP/Temp
2020-03-11 17:35:34  debug: [content_manager.cc:748] addRecursive(): IS TASK VALID? [true], task path: [/media/pi/raid/Videos/TEMP/Temp]
2020-03-11 17:35:34 warning: [content_manager.cc:828] addRecursive(): skipping /media/pi/raid/Videos/TEMP/Temp/4.mkv : Not a file: /media/pi/raid/Videos/TEMP/Temp/4.mkv
2020-03-11 17:35:34 warning: [content_manager.cc:828] addRecursive(): skipping /media/pi/raid/Videos/TEMP/Temp/1.mkv : Not a file: /media/pi/raid/Videos/TEMP/Temp/1.mkv
```
Thanks.

**Comment by kyak** [comment]
Hi!

Both 1.mkv and 4.mkv are bigger than 2 Gb. Might be related to this: https://github.com/gerbera/gerbera/issues/738

**Comment by pamapa** [comment]
are you using master or 1.4.0?

**Comment by ItsMeMarc** [comment]
@pamapa 
I'm using master:
```
* commit 0bda7840 (HEAD -> master, origin/master, origin/HEAD)
| Date:   2020-03-09 16:52:58 +0300
```
@kyak 
You're right both files are larger than 2 Gb and are only examples. I have many other video files on my hdd and after your comment I analyzed the log file. For all files with more than 2 Gb there is an entry with `Not a file`.

Is this a problem with gerbera or could it be an issue with my operating system?

**Comment by ItsMeMarc** [comment]
Like @kyak in issue #738 I checked CmakeCache.txt for LFS. But everything seems to be ok.
```
pi@rpi4:~/build $ grep LFS CMakeCache.txt
LFS_COMPILE_OPTIONS:STRING=
LFS_DEFINITIONS:STRING=-D_LARGEFILE_SOURCE;-D_FILE_OFFSET_BITS=64
LFS_LIBRARIES:STRING=
//Details about finding LFS
FIND_PACKAGE_MESSAGE_DETAILS_LFS:INTERNAL=[TRUE][v()]
//Found LFS
LFS_FOUND:INTERNAL=TRUE

```

**Comment by pamapa** [comment]
Is the exception coming from "SQLStorage::findObjectByPath" aka "fs::is_regular_file(fullpath)"? If so, why?

Does this pull request give you more information about the problem you have?
https://github.com/gerbera/gerbera/pull/740

**Comment by kyak** [comment]
Here is more information:

```
gerbera[24333]: 2020-03-15 13:11:54 warning: skipping /home/user/file.mkv (type:8 perms:65535 ex:Not a file: /home/user/file.mkv)
```

**Comment by ItsMeMarc** [comment]
I get excactly the same log information with files sizes > 2Gb with Raspbian Buster on a Raspberry Pi 4:
```
2020-03-15 08:15:13 warning: [content_manager.cc:829] addRecursive(): skipping /media/pi/raid/Videos/TEMP/Temp/4.mkv (type:8 perms:65535 ex:Not a file: /media/pi/raid/Videos/TEMP/Temp/4.mkv)
2020-03-15 08:15:13 warning: [content_manager.cc:829] addRecursive(): skipping /media/pi/raid/Videos/TEMP/Temp/1.mkv (type:8 perms:65535 ex:Not a file: /media/pi/raid/Videos/TEMP/Temp/1.mkv)
```

**Comment by pamapa** [comment]
interesting, type 6 means fifo, but why that?
```
include/bits/fs_fwd.h
...
  enum class file_type : signed char {
      none = 0, not_found = -1, regular = 1, directory = 2, symlink = 3,
      block = 4, character = 5, fifo = 6, socket = 7, unknown = 8
  };
```

**Comment by pamapa** [comment]
what shows up via command line:
```
stat /home/user/file.mkv
or
stat /media/pi/raid/Videos/TEMP/Temp/1.mkv
```
?

**Comment by ItsMeMarc** [comment]
Here is stat from 1.mkv (>2Gb):
```
pi@rpi4:~ $ stat /media/pi/raid/Videos/TEMP/Temp/1.mkv                            
  Datei: /media/pi/raid/Videos/TEMP/Temp/1.mkv
  Größe: 2683821587     Blöcke: 5241848    EA Block: 4096   reguläre Datei
Gerät: 900h/2304d       Inode: 9109536     Verknüpfungen: 1
Zugriff: (0744/-rwxr--r--)  Uid: ( 1000/      pi)   Gid: ( 1000/      pi)
Zugriff    : 2020-03-14 23:28:13.803240713 +0100
Modifiziert: 2014-03-29 09:27:52.000000000 +0100
Geändert   : 2020-03-11 17:27:04.407305482 +0100
 Geburt    : -
```
And for comparison, here is stat for 2,mkv (<2Gb):
```
pi@rpi4:~ $ stat /media/pi/raid/Videos/TEMP/Temp/2.mkv
  Datei: /media/pi/raid/Videos/TEMP/Temp/2.mkv
  Größe: 1609904726     Blöcke: 3144360    EA Block: 4096   reguläre Datei
Gerät: 900h/2304d       Inode: 9109537     Verknüpfungen: 1
Zugriff: (0744/-rwxr--r--)  Uid: ( 1000/      pi)   Gid: ( 1000/      pi)
Zugriff    : 2020-03-14 23:29:08.862318586 +0100
Modifiziert: 2014-03-28 17:24:42.000000000 +0100
Geändert   : 2020-03-11 17:28:26.826155052 +0100
 Geburt    : -
```
Output is in German. Here is the Google translation for 1.mkv:
```
pi @ rpi4: ~ $ stat /media/pi/raid/Videos/TEMP/Temp/2.mkv
  File: /media/pi/raid/Videos/TEMP/Temp/2.mkv
  Size: 1609904726 Blocks: 3144360 EA Block: 4096 regular file
Device: 900h / 2304d Inode: 9109537 Links: 1
Access: (0744 / -rwxr - r--) Uid: (1000 / pi) Gid: (1000 / pi)
Access: 2020-03-14 23: 29: 08.862318586 +0100
Modified: 2014-03-28 17:24: 42.000000000 +0100
Modified: 2020-03-11 17: 28: 26.826155052 +0100
 Birth: -
```

**Comment by kyak** [comment]
> interesting, type 6 means fifo, but why that?
> 

But it's type 8 both for me and @ItsMeMarc

**Comment by pamapa** [comment]
@kyak yes its 8, looks like a libstd++ limitation/bug on 32bit systems. I have added a workaround by not using that function. Can you test with https://github.com/gerbera/gerbera/pull/743?

**Comment by kyak** [comment]
When using https://github.com/gerbera/gerbera/pull/743, I'm somehow getting error very similar (but not exactly the same) to https://github.com/gerbera/gerbera/issues/738:

```
error: Exception caught: filesystem error: cannot get file size: Value too large for defined data type [/home/user/file.mkv]
```

**Comment by ItsMeMarc** [comment]
On Raspbian I have the same behaviour like @kyak: `filesystem error: cannot get file size: Value too large for defined data type` 
```
2020-03-15 21:41:33 warning: [content_manager.cc:829] addRecursive(): skipping /media/pi/raid/Videos/TEMP/Temp/4.mkv (ex:filesystem error: cannot get file size: Der Wert ist zu groß für den definierten Datentyp [/media/pi/raid/Videos/TEMP/Temp/4.mkv])
2020-03-15 21:41:33 warning: [content_manager.cc:829] addRecursive(): skipping /media/pi/raid/Videos/TEMP/Temp/1.mkv (ex:filesystem error: cannot get file size: Der Wert ist zu groß für den definierten Datentyp [/media/pi/raid/Videos/TEMP/Temp/1.mkv])
```

**Comment by pamapa** [comment]
LFS on Raspbian buster 32bit seems not to work at all? Does an older version (e.g. 1.4.0) of gerbera work? I am not so sure how down the rabbit hole we should actually go :-) For Raspberry Pi 4, there are 64it versions nowadays...

Can you start gerbera master compiled with `-DCMAKE_BUILD_TYPE=Debug` inside Visual Studio Code and find out where the problematic code line is?

**Comment by pamapa** [comment]
please test this patch, hopefully it is the last puzzle. :-)

**Comment by kyak** [comment]
@pamapa all right, it works now! Many thanks!

**Comment by pamapa** [comment]
Hey guys, i would like to report that back to raspbian, therefore i need some more information. Can you please provide me this?

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
* Which OS and version (`cat /etc/rpi-issue`)?
* Which firmware version (`vcgencmd version`)?
* Which kernel version (`uname -a`)?

**Logs**
If applicable, add the relevant output from `dmesg` or similar.

**Comment by kyak** [comment]
I'm running Arch Linux, and it's not Raspberry. Do you still need any information?

**Comment by pamapa** [comment]
Yes please provide OS version + kernel version (`uname -a`)

**Comment by kyak** [comment]
Arch Linux (no version, since it's rolling release).

uname -a:
```
Linux user 4.14.165-1-ARCH #1 SMP PREEMPT Sat Jan 18 02:01:06 UTC 2020 armv7l GNU/Linux
```

grep -m 2 -E 'model|Features' /proc/cpuinfo
```
model name      : ARMv7 Processor rev 3 (v7l)
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae
```

**Comment by ItsMeMarc** [comment]
@pamapa 
Thank you. You're the very best. :-) Gerbera is working like a charm now. Can I therefore close this issue?

Here is the output from raspinfo: [raspinfo.txt](https://github.com/gerbera/gerbera/files/4362814/raspinfo.txt)
Do you need any more information?
