### ISSUE TITLE
Crashes on ARM

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#738]
Hi! Thanks a lot for this software. It works very well on my laptop; however, my main use case would be to run it on a ARM-based server.

Unfortunately, gerbera crashes on ARM - presumably when scanning for files and trying to create the database.

Below is more details about my environment:
- I'm running Arch Linux ARM on ODROID-HC2. See here for more details about the hardware: https://archlinuxarm.org/platforms/armv7/samsung/odroid-hc2
- gerbera 1.4.0 with the following options:
Compile info
-------------
WITH_MAGIC=1
WITH_MYSQL=0
WITH_CURL=1
WITH_INOTIFY=1
WITH_JS=1
WITH_TAGLIB=1
WITH_AVCODEC=1
WITH_FFMPEGTHUMBNAILER=1
WITH_EXIF=1
WITH_EXIV2=0
WITH_PROTOCOL_EXTENSIONS=
WITH_SYSTEMD=1
WITH_LASTFM=0
WITH_DEBUG=1
WITH_TESTS=0

Here is the crash message in system logs:
```
gerbera[479]: terminate called after throwing an instance of 'libebml::CRTError'                                                            
gerbera[479]:   what():  Can't open stdio file "/home/user/video.mkv" in mode "rb": Value too large for defined data type
systemd[1]: Started Process Core Dump (PID 496/UID 0).      
systemd[1]: gerbera.service: Main process exited, code=killed, status=6/ABRT                                                                
systemd[1]: gerbera.service: Failed with result 'signal'.   
systemd-coredump[497]: Process 479 (gerbera) of user 973 dumped core.                                                                       
                                                                                
                                              Stack trace of thread 494:        
                                              #0  0x00000000b643919c raise (libc
.so.6 + 0x3119c)
```

By searching for the error, it looks like this is due to a missing definition for large file support: https://stackoverflow.com/questions/13893580/calling-stat-from-sys-stat-h-faills-with-value-too-large-for-defined-data-typ

However, I double checked and it looks like all the needed definitions are in place:
```
$ grep LFS src/gerbera-1.4.0/CMakeCache.txt
LFS_COMPILE_OPTIONS:STRING=
LFS_DEFINITIONS:STRING=-D_LARGEFILE_SOURCE;-D_FILE_OFFSET_BITS=64
LFS_LIBRARIES:STRING=
//Details about finding LFS
FIND_PACKAGE_MESSAGE_DETAILS_LFS:INTERNAL=[TRUE][v()]
//Found LFS
LFS_FOUND:INTERNAL=TRUE
```

And I'm stuck now. Looking forward to your help.

**Comment by pamapa** [comment]
hi, i made i fix in src/metadata/matroska_handler.cc, but after the 1.4.0 release. When using 1.4.0 please disable this with: -d WITH_MATROSKA=0. Or use master.

**Comment by kyak** [comment]
@pamapa thank you! Running without MATROSKA now, the problem is no more.
