### ISSUE TITLE
gerbera tries to create database tables when they are empty

### ISSUE THREAD

**Issue by cweiske** [gerbera/gerbera#74]
I changed my import script, stopped gerbera, emptied all SQL database tables and started gerbera:

> INFO: database doesn't seem to exist. automatically creating database...
> ERROR: Mysql: error while creating db: mysql_error (1050): "Table 'mt_cds_object' already exists"
> Exception raised in [src/storage/mysql/mysql_storage.cc:226] init(): Mysql: error while creating db: mysql_error (1050): "Table 'mt_cds_object' already exists"

Gerbera should not assume that no tables exist when they are simply empty.

**Comment by elmodaddyb** [comment]
It looks like the logic to **recreate** the schema is based on the presence of the database version.
[MysqlStorage::init()](https://github.com/v00d00/gerbera/blob/master/src/storage/mysql/mysql_storage.cc#L182)

`mt_internal_setting.key = 'db_version'`

While this is a simple clean approach, it does not account for clearing ALL db table data.  Reliance on another means (like a whitelist of tables??) could be more effective.

Could we also eliminate the [DB UPGRADES?](https://github.com/v00d00/gerbera/blob/master/src/storage/mysql/mysql_storage.cc#L48).  The incremental upgrades seem redundant if you start your DB at version `4`??

Any thoughts?

**Comment by cweiske** [comment]
Gerbera could drop all tables when it detects that the dbVersion is empty, before initializing the db again.

**Comment by cweiske** [comment]
I'll close this.

Truncating all tables is not something that the average user does. Now that I know that I have to keep the `db_version` property in `mt_internal_setting`, I can workaround my problem.
