### ISSUE TITLE
Populate metadata from external files

### ISSUE THREAD

**Issue by ytimenkov** [gerbera/gerbera#747]
I was thinking on this idea for a long time and now it more or less crystallized.

Problems I have right now:
1. no custom thumbnail for video
2. potentially multiple subtitle tracks for video
3. custom tags for photos (and maybe video, like ok for kids)

Also would be nice to have ability to interop with other software (for example digikam) or use with custom metadata providers (egh.. like kodi scrubbers or why not kodi itself), probably written in some scripting language. Saw also requests in digikam to pass an image through some ai tagging service...

I think the (a?) solution is quite simple and doesn't change current model of JavaScript-based connection organizer.

1. add a "metadata provider" js function. It registers for a certain file pattern, e.g. `[item name]*.srt` or `[item name].xmp`. 
2. these files are watched and when changed, corresponding hook us invoked which reads the file and updates metadata for an item.
2. I think function should return whether the file was accepted as metadata or not. Then they could be stored in db and watched for changes. And to stop processing as ordinary items.
3. it can add it update properties (eg custom title) or resources (fanart or subtitle or even audio track)
4. after that the import hook needs to be reran to update virtual structure (delete all items associated with that physical item).
5. hooks can be specified in the config in the priority order (in case some are dependent or just overwrite properties)
6. also would be nice to read file as json/yaml/xml in addition to current functions for playlist.

I think this won't change much of gerbera internals, but will give a lot of flexibility to users.
For example I could just create a yaml file next to a video and tip gerbera on how I want to see it (e.g. series vs cartoon or not a film but my own video).

**Comment by ytimenkov** [comment]
Does this make sense?

**Comment by whyman** [comment]
We actually now have support for "fanart", if your media has no images and gerbera finds `folder.jpg` or `poster.jpg` it will use it. See [fanart_handler.cc](https://github.com/gerbera/gerbera/blob/86ae8cb831d4b1ddecbf16941bc421fe782f463d/src/metadata/fanart_handler.cc). Obviously this doesnt cover actual metadata though. At some point I woud like to add support for Kodi's XML NFO format files.

As for the rest of the proposal it certainly sounds good, so long as the default behaviour is sensible I dont see why we wouldn't be interested as its an extension of the scripting concepts we already have.

Of course, we would need someone to write the patches for it!

**Comment by ytimenkov** [comment]
> We actually now have support for "fanart", if your media has no images and gerbera finds folder.jpg or poster.jpg it will use it. See fanart_handler.cc. 

I tried to make this work but I can't make gerbera sending me proper tags. If I read the code correctly those handlers executed when scanning directory and populating sql db record. In most of my cases I can add those files afterwards and therefore they're just ignored. Even if I copy directory with `folder.jpg` there's is no guarantee that image will be copied first before main element (well, this is again a case for inotify and lesser issue for periodic scans).

That's why I think that item should be reimported once change in metadata is detected.

Anyways, this on its own is not a big disappointment. More important is to have custom tags for organizing collection.

> Of course, we would need someone to write the patches for it!

Yeah, I didn't expect you to jump on it 😁. On the other hand working on feature that is not aligned with the project is not good either.

**Comment by ghlupe2** [comment]
> Anyways, this on its own is not a big disappointment. More important is to have custom tags for organizing collection.

I just gave it a try using [mp3Tag](https://help.mp3tag.de/index.html) to populate standard tags (like ARTIST and COMMENT) and add some custom tags to .mp4 and .mkv video files which works just fine. A first run with Gerbera 1.3 on Ubuntu imported the standard tags of my mp4-video at least but nothing from the .mkv (--compile-info does not mention matroska support, so ...):
```

2020-04-20 13:49:49      JS: dc:title--->Tag Testing
2020-04-20 13:49:49      JS: upnp:artist--->Test Artist
2020-04-20 13:49:49      JS: dc:date--->2020-01-01
2020-04-20 13:49:49      JS: dc:description--->Sample Comment
2020-04-20 13:49:49      JS: protocolInfo--->http-get:*:video/mp4:*
2020-04-20 13:49:49      JS: size--->8101941
2020-04-20 13:49:49      JS: bitrate--->41979
2020-04-20 13:49:49      JS: duration--->00:03:12.9
2020-04-20 13:49:49      JS: sampleFrequency--->44100
2020-04-20 13:49:49      JS: nrAudioChannels--->2
2020-04-20 13:49:49      JS: resolution--->1280x720

2020-04-20 13:49:16      JS: protocolInfo--->http-get:*:video/x-matroska:*
2020-04-20 13:49:16      JS: size--->7906409
2020-04-20 13:49:16      JS: duration--->00:03:13.1
2020-04-20 13:49:16      JS: bitrate--->40944
2020-04-20 13:49:16      JS: resolution--->1280x720
2020-04-20 13:49:16      JS: sampleFrequency--->44100
2020-04-20 13:49:16      JS: nrAudioChannels--->2

```
I guess, that is quite promising. Enhancing Gerbera's capabilities along this line would definitely be

> aligned with the project

 :-)

**Comment by ghlupe2** [comment]
I just discovered by chance that there is an undocumented ffmpeg library option

```
    <library-options>
	<ffmpeg>	
         <auxdata>
	    <add-data tag="COLLECTION"/>
         </auxdata>
      </ffmpeg>
    </library-options>
```

and I could use the COLLECTION frame in import.js for both my test mp4 and mkv video files.

I have the current master build compiled with matroska support.

**Comment by whyman** [comment]
We should add that to docs, PR anyone?

**Comment by ghlupe2** [comment]
I'd like to do so

Ian Whyman <notifications@github.com> schrieb am Sa., 2. Mai 2020, 10:17:
