### ISSUE TITLE
upnp:artist@role[AlbumArtist] breaks folder display on clients

### ISSUE THREAD

**Issue by michaelkl** [gerbera/gerbera#749]
I came across the following problem: _some folders with MP3 files were displayed empty by DLNA client_.

I used debug mode to inspect the exact data transferred to a client and it turned out that items were actually sent by Gerbera. By analyzing the logs for folders which works correctly I finally tracked the problem down to a `upnp:artist@role[AlbumArtist]` tag.

I know nothing about DLNA protocol but quick googling revealed articles like [this](https://community.netgear.com/t5/Using-your-ReadyNAS-in-Business/ReadyDLNA-1-1-2-3-solved-my-albumartist-problems-but/td-p/952775).

So, I tried to fix the problem with a simple SQL:
```
UPDATE mt_metadata
SET property_name='upnp:albumArtist'
WHERE property_name='upnp:artist@role[AlbumArtist]'
```
**And it helped!**

The problem persists with the following clients:
- VLC (Android)
- BubbleUPnP (Android)
- LG Smart TV

The problem does not persist with:
- foobar2000 (Android)

BubbleUPnP even shows the error message when I was trying to enter this folder: "The Media Server sent invalid data".

Might also be related to #707

**Comment by whyman** [comment]
Is this a master build?

**Comment by michaelkl** [comment]
> Is this a master build?

Yes, but not the latest. I built it a month or two ago. But I am pretty sure [it is still here](https://github.com/gerbera/gerbera/blob/bd66bc847b0ca09e3571dddb20d0a7e0a2aedf95/src/metadata/metadata_handler.cc#L81).

**Comment by count00zero** [comment]
I tried it with the latest master build: same behaviour; SQL fix helped
https://github.com/gerbera/gerbera/issues/707#issuecomment-602260613
https://github.com/gerbera/gerbera/issues/707#issuecomment-602263434

**Comment by whyman** [comment]
Thanks for reporting and confirming both.

**Comment by astylos** [comment]
Seeing same issue, submitting a PR

**Comment by whyman** [comment]
Ive taken a look into this.

The issue here that the special code that handeld the album artist got lost during the removal of the legacy `mxml` stuff.

`upnp:artist@role[AlbumArtist]` should not end up in the XML. It needs to be rendered as `<upnp:artist role="AlbumArtist">`

Here is the original commit: https://github.com/gerbera/gerbera/commit/b31f659235b9fb328abb1404f9e7e07bdfdcb18d where the special case was added.

This should be pretty easy to restore with the nice new XML library.
