### ISSUE TITLE
Gerbera stops processing - how to setup logs

### ISSUE THREAD

**Issue by hornetster** [gerbera/gerbera#755]
Have just (re-)installed Gerbera, and having issues getting it to read my files.
Gets some of the way through, then seems to stop at this line when viewing status or journalctl:
`Mar 26 14:43:54 MeDiA1 gerbera[3133]: 2020-03-26 14:43:54      JS: Processing playlist: /mnt/ExtHDD/mEdIa/Music/AAA/Australian Crawl/Semantics/Australian Crawl - Semantics.m3u`
so am trying to fault-find. Gerbera is starting through systemd. Generated file:
```
[Unit]
Description=Gerbera Media Server
Documentation=man:gerbera(1) https://gerbera.io/
After=mysql.target network.target

[Service]
Type=simple
# EnvironmentFile=/etc/default/gerbera
User=gerbera
Group=gerbera
ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml $EXTRAARGS
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```
which works OK. Trying to start with an external logfile in debug mode, so editing Execstart line to:
ExecStart=/usr/bin/gerbera -c /etc/gerbera/config.xml -l /var/log/gerbera.log -D $EXTRAARGS
which fails to start.
Questions: How can I get this line to work AND/OR
what/how is the $EXTRAARGS item?

**Comment by whyman** [comment]
Hi!

Looks like `$EXTRAARGS` is an environment variable that can be defined in the `EnvironmentFile`

so you should be able to add your args in there, once you uncomment the line.

**Comment by hornetster** [comment]
Thanks!
Yep, have sort of figured it out - you are right.
Uncommented that line (EnvironmentFile...... ) and created the file (/etc/default/gerbera), and managed to get the debug stuff going to its own file.
Not sure about my initial issue (Gerbera caching the file info), it did never get any further, but seems to have cached a "good percentage" of available files, anyway...
Will continue to play...

**Comment by whyman** [comment]
Good to hear it. Please open a new issue if you find one.
