### ISSUE TITLE
[1.1.0] UI javascript not working

### ISSUE THREAD

**Issue by torstenzenk** [gerbera/gerbera#757]
Hello everybody.
First of all thanks to the developers and contributors for this fresh kind of work.

As i am trying what gerbera has to offer and after a very smooth install on debian buster i have it up and running on port 49152.

I first tried  the version you from debian default repository and now with the 
> gerbera/stable 1.1.0+dfsg-3+b1 amd64 <

Both versions have the same problem with the 4 first Javascript-Links that are presented on the startpage named:

+ Add some files
Browse and import your multimedia files
+ View Indexed Files
View, update and remove files from gerbera

My Browsers Firefox, Chrome, Opera and Edge, all in the latest stable versions simply show empty javascript.

what am i missing here?

![gerbera_javascript_1](https://user-images.githubusercontent.com/11678736/77676786-187be280-6f8f-11ea-87c5-46949d162e62.png)

**Comment by torstenzenk** [comment]
In Fact there is no working link in any of the browsers, not even
+ Home
 + Database
 +File System

**Comment by whyman** [comment]
Do all the resources load as expected? (in the network tab of dev tools)

**Comment by torstenzenk** [comment]
Hey,
that was the right way to look at: There are symlinks in the css + js folder that are wrong:
![vendor_js](https://user-images.githubusercontent.com/11678736/78558192-78397f80-7812-11ea-84f6-e8ffbd64939f.PNG)
![vendor_js2](https://user-images.githubusercontent.com/11678736/78558890-b3887e00-7813-11ea-9455-b941a5ca6190.PNG)
and i had to delete the wrong symlinks and then cp the existing files and name the new ones to the names of the missing ones.
![vendor_js3](https://user-images.githubusercontent.com/11678736/78559345-825c7d80-7814-11ea-953b-e78153ad4c3f.PNG)
![vendor_js4](https://user-images.githubusercontent.com/11678736/78559424-a750f080-7814-11ea-944d-953821023e01.PNG)

 . Then it worked, not looking too good, but works.

**Comment by whyman** [comment]
Glad to hear it.

I would suggest upgrading to 1.4.0. As expected the version in Debian is pretty ancient and sounds like it has packaging issues...

I think deb-multimedia have newer versions, if not there is a docker version.
