### ISSUE TITLE
remove content type/mime mapping

### ISSUE THREAD

**Issue by pamapa** [gerbera/gerbera#775]
Directly working with mime types makes everything must easier. In case a specific client needs a quirk we can make use of this #752 feature.

- [ ] libmagic needs to become from optional to a hard build requirement.

- [ ] removed configuration properties:
  - CFG_IMPORT_MAPPINGS_IGNORE_UNKNOWN_EXTENSIONS
  - CFG_IMPORT_MAPPINGS_EXTENSION_TO_MIMETYPE_CASE_SENSITIVE
  - CFG_IMPORT_MAPPINGS_EXTENSION_TO_MIMETYPE_LIST
  - CFG_IMPORT_MAPPINGS_MIMETYPE_TO_UPNP_CLASS_LIST
  - CFG_IMPORT_MAPPINGS_MIMETYPE_TO_CONTENTTYPE_LIST

@whyman
If libmagic can not be a hard build requirement, an alternativewould be to simply use the file extension and work with that. Like this
```
bool isImage(const fs::path& filename)
{
  static std::vector<std::string> v{".jpg",  ".jpeg"};
  return std::find(v.begin(), v.end(), filename.extension()) != v.end();
}
```

**Comment by whyman** [comment]
@pamapa I think its fine to have magic as build requirement, lets keep our code-paths as simple as possible.
