### ISSUE TITLE
Undocumented "Basic" and "Full" Scan level

### ISSUE THREAD

**Issue by cisba** [gerbera/gerbera#778]
<img width="398" alt="Screenshot 2020-04-06 at 09 25 45" src="https://user-images.githubusercontent.com/2389559/78533817-db62ec00-77e9-11ea-86eb-7b4ab8c1d02b.png">

In the documentation of [filesystem-view](https://github.com/gerbera/gerbera/blob/master/doc/ui.rst#filesystem-view) the autoscan feature is not explained.

Everything is intuitive except the difference between "Basic" and "Full" Scan level.

Could someone please explain the difference - or point out the source file from which to derive it?

**Comment by ytimenkov** [comment]
If you asked for source location, I see it's used only here: https://github.com/gerbera/gerbera/blob/2c8dca25031cd5b9f5cf5f54276c590752f2edae/src/content_manager.cc#L664
(beside other places where it propagates into this one).

As I understand if you do scan level full it will re-add item causing updating layout (if item was modified), while basic will just skip items which already exist in a DB. Not sure how it plays together with timed vs inotify-based scans (as some places in code tell to use full scan with inotify saying that it's ignored).

I'm not sure I understand it well enough to document...

**Comment by whyman** [comment]
Based on that, I see no value in keeping this pretty useless option.

A patch to always do "Full" and remove any mention would be welcome.
