### ISSUE TITLE
Gerbera 1.5 Release

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#780]
There have been a lot of great changes merged since 1.4 in the codebase, so I think we should create a new release to get wider testing on the new code paths.

- [x] Merge client quirks stuff
- [x] Fix up any bugs we can in a week or so
- [x] Ensure that there is a upstream libupnp release we can build against
- [x] Require `fmt >=6` in CMake
- [x] Require `pupnp >=1.12.1` in CMake and remove old `ifdef`
- [x] Fix Album artist rendering (#749)
- [x] Write release notes
- [x] Bump versions
- [x] Create 1.5.x branch
- [x] Push tag
- [ ] Bump homebrew (https://github.com/gerbera/homebrew-gerbera/)
- [ ] Profit?

**Comment by whyman** [comment]
Upstream pupnp release issue: https://github.com/pupnp/pupnp/issues/167

**Comment by neheb** [comment]
Will this require libupnp 1.12?

**Comment by whyman** [comment]
It will require 1.12.1

**Comment by neheb** [comment]
Ah that's unfortunate. Looks like it will take a bit of work.

**Comment by pamapa** [comment]
What about #775. It will be quite invasive and depends on client quirks + detection. We might do this after the 1.5.0?

**Comment by whyman** [comment]
> What about #775. It will be quite invasive and depends on client quirks + detection. We might do this after the 1.5.0?

Sure.
