### ISSUE TITLE
Request transcoding help: DTS to AC3 in .mkv

### ISSUE THREAD

**Issue by ras07** [gerbera/gerbera#781]
My TV will play .mkv streams with AC3 audio, but not DTS. I've tried various transcoding options but I don't really know what I'm doing. I read the transcoding doc section but I'm afraid much of it went over my head. Can someone suggest edits to the config.xml file that will get me there?

**Comment by pamapa** [comment]
To keep it simple i convert all videos with DTS before hand and do not need and transcoding options. This converts only the audio stream and leaves the image stream as is:
```
audio_opts="-c:a ac3" # convert all
ffmpeg -i "$input" \
   -map 0 \
   -c:v copy \
   $audio_opts \
   -c:s copy \
   "$output"
```

**Comment by ras07** [comment]
Thanks - I'd sure love to be able to do this on the fly though, rather than either losing the original file or keeping two copies of everything. Can anyone point me in a direction that lets me use @pamapa 's ffmpeg parameters to accomplish transcoding?

**Comment by jkiusAlarus** [comment]
Hello
you can maybe have a look to the issue https://github.com/gerbera/gerbera/issues/370 
there is a script that you can use to transcode you mkv using ffmpeg.
regards
Laurent

**Comment by JoeNyland** [comment]
I have the same requirement, too: My TV will not play DTS from an .mkv container, but it will play AC3. I'd love to see some support in Gerbera for transcoding audio for this use case. The script linked above seems a bit too complicated and we'd lose the ability of seeking transcoded files.

**Comment by jmgh77** [comment]
I am new to Gerbera and have the same issue with my LG WebOS TV (OLED65CX6LA with WebOS 5.0).  So I dig in the transcode option and put this in my config.xml file:

  <transcoding enabled="yes">
    <mimetype-profile-mappings>
      <transcode mimetype="video/x-matroska" using="nodts" />
    </mimetype-profile-mappings>

      <profile name="nodts" enabled="yes" type="external">
        <mimetype>audio/ac3</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <hide-original-resource>no</hide-original-resource>
        <agent command="ffmpeg" arguments="-y -i %in -f ac3 %out" />
        <buffer size="1048576" chunk-size="131072" fill-size="262144" />
      </profile>

For the buffer part I took it from the ogg2mp3 exemple, but this is not important here. Testing with VLC it works pretty well. The existing DTS track(s) are still there, but I have now an additional AC3 track I can select. Unfortunatly with the TV this does not work. The issue is that the transcoding part (ffmpeg) does not start with the TV. I did some debug and packets capture and it works a bit different between VLC and the TV. With VLC more things happen, it does 6 times:

**Comment by jmgh77** [comment]
I am new to Gerbera and have the same issue with my LG WebOS TV (OLED65CX6LA with WebOS 5.0). So I dig in the transcode option and put this in my config.xml file:

  <profile name="nodts" enabled="yes" type="external">
    <mimetype>audio/ac3</mimetype>
    <accept-url>no</accept-url>
    <first-resource>yes</first-resource>
    <hide-original-resource>no</hide-original-resource>
    <agent command="ffmpeg" arguments="-y -i %in -f ac3 %out" />
    <buffer size="1048576" chunk-size="131072" fill-size="262144" />
  </profile>

For the buffer part I took it from the ogg2mp3 exemple, but this is not important here. Testing with VLC it works pretty well. The existing DTS track(s) are still there, but I have now an additional AC3 track I can select. Unfortunatly with the TV this does not work. The issue is that the transcoding part (ffmpeg) does not start with the TV. I did some debug and packets capture and it works a bit different between VLC and the TV. 

With VLC it does many times this, 5 or more:

createRequestHandler(): Filename: /content/media/object_id/3245/res_id/0/ext/file.mkv

and then this, which is the transcoded AC3 track:

 createRequestHandler(): Filename: /content/media/object_id/3245/res_id/none/pr_name/nodts/tr/1

and then ffmpeg starts.

With the TV it never goes that far. I only have 2 requests to file.mkv and nothing more.

LG is not specified in the supported device, so I dont know if it is meant to work,  but beside this it works pretty well. The user agent in the packet is:

Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36 WebAppManager

I am using Gerbera 1.60 on Ubuntu 20.04. I can provide trace and debug.

Regards
JM

**Comment by jmgh77** [comment]
my xml config is:

```
 <transcoding enabled="yes">
   <mimetype-profile-mappings>
      <transcode mimetype="video/x-matroska" using="nodts" />
   </mimetype-profile-mappings>
   <profiles>
      <profile name="nodts" enabled="yes" type="external">
        <mimetype>audio/ac3</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <hide-original-resource>no</hide-original-resource>
        <agent command="ffmpeg" arguments="-y -i %in -f ac3 %out" />
        <buffer size="1048576" chunk-size="131072" fill-size="262144" />
      </profile>

```

**Comment by jkiusAlarus** [comment]
hello
I would suggest to hide original resource so that the TV can only see the transcoded flow:
`<hide-original-resource>yes</hide-original-resource>`
to see if it makes any difference
Laurent Jacquot

**Comment by jmgh77** [comment]
I thought at doing that actually. This is why I have the line in my config set at "no". When put at yes, all the mkv files are no more visible, already in VLC. The difficulty here is that we need to transcode an audio track within a mkv container and not a sound file. So I had to put mkv in the profile mapping. I tried to put audio DTS mime type, but it does not work.

**Comment by Koga-Miyata** [comment]
I am experiencing the same as @jmgh77 the transcoding with ffmpeg does not start with a LG TV but with VLC, can there be anything done?

**Comment by KarlStraussberger** [comment]
I suppose the TV peeks into the stream instead of looking at the metadata and resources so it never triggers the transcoding request. First of all we need to find out what the TV wants to _see_ to accept the media as playable (does it play without sound or is the file listed only). Did you find any useful information in other web forums?

There have been some changes in Gerbera in resource handling recently, which version are you running?

**Comment by Koga-Miyata** [comment]
I am using 1.3.2 from current Debian Stable Repos (Buster), I suppose I should change that to sth. >1.8, before going into more detail, I'll do so and be back...

**Comment by Koga-Miyata** [comment]
I upgraded to 1.8.2
I am trying to use this transcode block to establish an ac3 audiostream within a matroska container and turn the volume up a bit. On console the ffmpeg command does what it should...
```
<transcoding enabled="yes">
  <mimetype-profile-mappings>
    <transcode mimetype="video/x-matroska" using="ac3_vol_up" />
  </mimetype-profile-mappings>
  <profile name="ac3_vol_up" enabled="yes" type="external">
    <mimetype>video/x-matroska</mimetype>
    <accept-url>yes</accept-url>
    <first-resource>yes</first-resource>
    <agent command="/usr/bin/ffmpeg" arguments="-i %in -map 0 -vcodec copy -scodec copy -acodec ac3 -b:a 640k -filter:a volume=4.0 %out"/>
    <buffer size="14400000" chunk-size="512000" fill-size="120000"/>
  </profile>
</profiles>
</transcoding>
```
Unforunaltelly now it gives me:
```
[*** LOG ERROR #0001 ***] [2021-06-17 09:17:46] [] {string pointer is null}
```
When starting Gerbera. Seems I a missing some expected clause but which?

**Comment by KarlStraussberger** [comment]
Can you run gerbera with `--debug`, please. Because this message comes straight from the fmt-lib and can happen almost everywhere, so we need to find the context when it happens.

**Comment by Koga-Miyata** [comment]
I did not close the `<profiles> block in my above comment which caused the error, now I'm back to transcode not starting as in 1.3.2

**Comment by KarlStraussberger** [comment]
Still you may start with `--debug` to see what your TV request from gerbera that we de not provide, yet.

**Comment by Koga-Miyata** [comment]
I selected a file and played it in the attached log.
[debug_ger_1.log](https://github.com/gerbera/gerbera/files/6668580/debug_ger_1.log)

**Comment by KarlStraussberger** [comment]
As far as I understand the log, it does want I suspected. It reads the media itsself and extracts necessary detail from it:
```
2021-06-17 10:17:50.481  debug: [server.cc:503] createRequestHandler(): Filename: /content/media/object_id/5/res_id/0/ext/file.mkv
2021-06-17 10:17:50.481  debug: [file_request_handler.cc:218] open(): start
```
This means that you have to convert the movie before this happens otherwise the TV drops the file because it cannot decode it.

NB: I like the name of your TV set :smile:

**Comment by Koga-Miyata** [comment]
so what you're saying is that there's no way to have a "on the fly" transcode handled by gerbera for that device (LGC9) due to its way it retrieves the media from gerbera?

**Comment by KarlStraussberger** [comment]
There may be a way if we learn what there must be in the UPnP browse response for the TV to change its behaviour.

At least, I don't know at the moment. But there's others around who may help.

**Comment by Koga-Miyata** [comment]
I could wireshark the same process I did in the debug log, that would help I guess, will take me a while, but doable...

**Comment by KarlStraussberger** [comment]
If you can get another server, like serviio, for the test as well, you may grab the difference.

**Comment by KarlStraussberger** [comment]
Actually, it would be interesting to see the difference in communication between your TV and a heavy weight media server like serviio. That may help us to update the responses gerbera sends.

**Comment by Koga-Miyata** [comment]
ok, will install serviio and sniff that, won't have time for that before next week though...

**Comment by Koga-Miyata** [comment]
Now I captured a conversation beetween my LGC9 and Serviio. Since I am not sure what I am looking for I attach the pcap
[Serviio_LGC9.pcap.gz](https://github.com/gerbera/gerbera/files/6686592/Serviio_LGC9.pcap.gz)

**Comment by KarlStraussberger** [comment]
I just managed to look into it and found that you stopped recording before the interesting part

```
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">
	<container id="A" parentID="0" restricted="1">
		<dc:title>Audio</dc:title>
		<upnp:class>object.container</upnp:class>
	</container>
	<container id="I" parentID="0" restricted="1">
		<dc:title>Image</dc:title>
		<upnp:class>object.container</upnp:class>
	</container>
	<container id="V" parentID="0" restricted="1">
		<dc:title>Video</dc:title>
		<upnp:class>object.container</upnp:class>
	</container>
</DIDL-Lite>
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">
	<container id="V_T^INI*77" parentID="V_T" restricted="1">
		<dc:title>M</dc:title>
		<upnp:class>object.container</upnp:class>
	</container>
</DIDL-Lite>
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">
	<container id="V_F^FOL*R1" parentID="V_F" restricted="1">
		<dc:title>media</dc:title>
		<upnp:class>object.container.storageFolder</upnp:class>
		<upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.178.2:8895/resource/1/COVER_IMAGE</upnp:albumArtURI>
		<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=00;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=00D00000000000000000000000000000" resolution="160x106">http://192.168.178.2:8895/resource/1/COVER_IMAGE</res>
	</container>
</DIDL-Lite>
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">
	<container id="V_RY^Y*2021" parentID="V_RY" restricted="1">
		<dc:title>2021</dc:title>
		<upnp:class>object.container</upnp:class>
	</container>
</DIDL-Lite>

```

It does not contain a media file.

**Comment by Koga-Miyata** [comment]
THX for looking at it, don't know why that part is missing. I did a new recording and left it running a bit longer. What I did for the following two recordings:
- start media server
- add testfile
- start tv
- start recording
- select testfile from tv mediaplayer app
- play testfile for a bit
- exit tv mediaplayer app
- stop recording
[gerbera.pcap.gz](https://github.com/gerbera/gerbera/files/6769962/gerbera.pcap.gz)
[serviio.pcap.gz](https://github.com/gerbera/gerbera/files/6769965/serviio.pcap.gz)

**Comment by KarlStraussberger** [comment]
It took me a long time to peek into your files

You TV gets the following response

```
<?xml version="1.0" encoding="UTF-8"?>
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:sec="http://www.sec.co.kr/dlna">
	<item id="5" parentID="4" restricted="1">
		<dc:title>MyTestFile</dc:title>
		<upnp:class>object.item.videoItem</upnp:class>
		<dc:created>2010-08-29</dc:created>
		<dc:date>2010-08-29</dc:date>
		<res duration="0:45:16.992" nrAudioChannels="6" protocolInfo="http-get:*:video/x-matroska;rate=48000;channels=6:DLNA.ORG_PN=MKV;DLNA.ORG_OP=00;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=01700000000000000000000000000000" sampleFrequency="48000">http://192.168.178.2:49152/content/media/object_id/5/res_id/none/pr_name/ac3_vol_up/tr/1/ext/file.mkv</res>
		<res bitrate="212186" duration="0:45:16.992" nrAudioChannels="6" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_PN=MKV;DLNA.ORG_OP=01;DLNA.ORG_CI=0" resolution="720x480" sampleFrequency="48000" size="576508523">http://192.168.178.2:49152/content/media/object_id/5/res_id/0/ext/file.mkv</res>
	</item>
</DIDL-Lite>
```
and picks thew wrong resource 
![grafik](https://user-images.githubusercontent.com/23654788/134944464-59ba3ca5-ae92-4f80-9086-b6f57527b5ec.png)


Looking at the serviio protocol I see 

```
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">
	<item id="V_F^FOL*R1$MI1" parentID="V_F^FOL*R1" restricted="1">
		<dc:title>MyTestFile.mkv</dc:title>
		<upnp:class>object.item.videoItem</upnp:class>
		<upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.178.2:8895/resource/1/COVER_IMAGE</upnp:albumArtURI>
		<dc:date>2021-06-17</dc:date>
		<res bitrate="212125" duration="0:45:16.000" protocolInfo="http-get:*:video/x-matroska:DLNA.ORG_PN=AVC_MKV_HP_HD_AC3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01500000000000000000000000000000" resolution="720x480" size="576508523">http://192.168.178.2:8895/resource/1/MEDIA_ITEM/AVC_MKV_HP_HD_AC3-0/ORIGINAL</res>
		<res protocolInfo="http-get:*:image/jpeg:DLNA.ORG_PN=JPEG_TN;DLNA.ORG_OP=00;DLNA.ORG_CI=1;DLNA.ORG_FLAGS=00D00000000000000000000000000000" resolution="160x106">http://192.168.178.2:8895/resource/1/COVER_IMAGE</res>
	</item>
</DIDL-Lite>
```

With the major difference in the `DLNA.ORG_PN`. So my idea is to add a <dlna-profile> element to transcoding which overwrites the default profile string generated derived from content type. Also the default profile needs to look at the encoding resource properties (`sec:acodec` and `sec:vcodec`) to create the proper `DLNA.ORG_PN`.

Most of it happens here: 
https://github.com/gerbera/gerbera/blob/744621f745d64f0827ee2163fde8efeeaed3f289/src/upnp_xml.cc#L760
and here
https://github.com/gerbera/gerbera/blob/744621f745d64f0827ee2163fde8efeeaed3f289/src/util/tools.cc#L1027

**Comment by KarlStraussberger** [comment]
I just created a PR that addresses the topic. You need to configure the `contenttype-dlnaprofile` mapping in the import section as well as the `dlna-profile` for transcondig

**Comment by KarlStraussberger** [comment]
You need four pieces that have to match to get transcoding right
1. clients: `<client ip="???" flags="0x1000"/>` or `<client userAgent="???" flags="0x1000"/>` to transcode for the specific device. You may skip this and remove the client-flags if you only have one device.
2. mapping/contenttype-dlnaprofile: `<map from="mkv" audioCodec="dts" to="AVC_MKV_HP_HD_DTS"/>`. audioCodec can be copied from the file's data in the web ui.
3. transcoding/mimetype-profile-mappings: `<transcode mimetype="video/x-mkv" source-profile="AVC_MKV_HP_HD_DTS" using="dts2ac3" client-flags="0x1000"/>`
4. transcoding/profiles:
```
<profile name="dts2ac3" enabled="yes" type="external">
  <mimetype>video/x-mkv</mimetype>
  <dlna-profile>AVC_MKV_HP_HD_AC3</dlna-profile>
  <agent> ... </agent>
  <buffer size="14400000" chunk-size="512000" fill-size="120000"/>
</profile>
```
