### ISSUE TITLE
additional tags from M4A

### ISSUE THREAD

**Issue by tb2496** [gerbera/gerbera#784]
Hi, I've been trying to get additional tags from itunes m4a files. for example album artist which should be aART based on https://help.mp3tag.de/main_tags.html

I added this to config.xml

```
<library-options>
      <id3>
        <auxdata>
          <add-data tag="aART"/>
        </auxdata>
      </id3>
</library-options>
```

and import.js

    var aartist = obj.aux['aART'];

**Comment by whyman** [comment]
Album artists should work for MP4 out of the box, assuming you have taglib support.

Which version of Gerbera are you running? Can you provide a debug log?

**Comment by tb2496** [comment]
ok, i think i'm missing taglib then as i cant find it anywhere.  is it separate install?  i'm running 1.35 on ubuntu

**Comment by whyman** [comment]
I think the package is called libtag on Ubuntu for some reason.

**Comment by tb2496** [comment]
ok, I got it working.  I didn't know I could use obj.meta[M_ALBUMARTIST]

the other thing is I'm trying to get a custom tag from m4a called Type.  I add it using Foobar2000 to organize my library based on Album, Single, Live, Best of, Compilation....  I have it working for mp3's and flac but not sure what to do with m4a.  Using exiftool the tag looks like this:

  | | | | | Name = Type
  | | | | | - Tag 'name' (8 bytes):
  | | | | |    13e4c: 00 00 00 00 54 79 70 65                         [....Type]
  | | | | | Data = .Album
  | | | | | - Tag 'data' (13 bytes):
  | | | | |    13e5c: 00 00 00 01 00 00 00 00 41 6c 62 75 6d          [........Album]

I tried `obj.aux['Type']` in import.js and  `<add-data tag="Type"/>` in config.xml but doesn't work.

**Comment by whyman** [comment]
We dont have support for extra tags in MP4 currently :-1:

**Comment by tb2496** [comment]
ok, thanks for your help.
