### ISSUE TITLE
Web-UI: Add External URL forces mimetype

### ISSUE THREAD

**Issue by TimelessNL** [gerbera/gerbera#790]
Hi,

I've been trying to add my Tvheadend livestreams as `external links` in Gerbera, but unfortunately this seems to force the mimetype to `application/octet-stream`. This works on my new DLNA devices but does not work on my older ones.

I also captured some live TV footage and stored them as `.mp4`[HD] and `.m2ts`[SD]. Those played fine on all devices when the Mimetype was set to `video/mpeg`. This implies that my devices support the necessary codecs.

After searching the internet for a while I stumbled on this [MediaTomb result](https://tvheadend.org/boards/5/topics/12850) where they seem to accomplish something similar.

_Here is a picture of the issue I'm facing, after adding the virtual file the Mimetype is changed and cannot be modified._
![Knipsel](https://user-images.githubusercontent.com/10838968/79081389-367e6c80-7d1d-11ea-897b-78b61c555a52.JPG)

**Comment by whyman** [comment]
This is an interesting case as 99% of the time you would not want to change the detected mimetype.

Odd that you provide it, but it is ignored... that sounds like a bug to me.

**Comment by TimelessNL** [comment]
> Odd that you provide it

(_yeah... eh.. Samsung I guess?_)
2012 models require specific mimetype's else they will refuse to play anything. I hope by manually specifying the stream as  `video/mpeg` or `video/ts` that they will play the video just like they did the recordings.
