### ISSUE TITLE
ffmpeg_handler.cc; std::unique_ptr<IOHandler> FfmpegHandler::serveContent(std::shared_ptr<CdsItem> item, int resNum) and return nullptr; does not fit

### ISSUE THREAD

**Issue by djstkg** [gerbera/gerbera#792]
https://github.com/gerbera/gerbera/blob/5c0353827804ce95146eb757172af15bb40e5d00/src/metadata/ffmpeg_handler.cc#L379

Build fails:

`
[ 25%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o
[ 26%] Building CXX object CMakeFiles/libgerbera.dir/src/metadata/metadata_handler.cc.o
In file included from /usr/include/c++/8/bits/locale_conv.h:41,
                 from /usr/include/c++/8/locale:43,
                 from /usr/include/c++/8/bits/fs_path.h:38,
                 from /usr/include/c++/8/filesystem:37,
                 from /home/pi/applications/gerbera/src/metadata/ffmpeg_handler.h:41,
                 from /home/pi/applications/gerbera/src/metadata/ffmpeg_handler.cc:43:
/usr/include/c++/8/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = IOHandler]’:
/usr/include/c++/8/bits/unique_ptr.h:274:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = IOHandler; _Dp = std::default_delete<IOHandler>]’
/home/pi/applications/gerbera/src/metadata/ffmpeg_handler.cc:379:12:   required from here
/usr/include/c++/8/bits/unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type ‘IOHandler’
  static_assert(sizeof(_Tp)>0,
                ^~~~~~~~~~~
make[2]: *** [CMakeFiles/libgerbera.dir/build.make:362: CMakeFiles/libgerbera.dir/src/metadata/ffmpeg_handler.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/libgerbera.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
`
Fails on:

`    return nullptr;`
does not fit with
`std::unique_ptr<IOHandler> FfmpegHandler::serveContent(std::shared_ptr<CdsItem> item, int resNum)`

Debian Buster, ARM 64bit.
Linux orangepipc2 5.4.28-sunxi64 #20.02.7 SMP Sat Mar 28 17:25:10 CET 2020 aarch64 GNU/Linux

**Comment by whyman** [comment]
That's interesting. Which compiler and stdlib are you using?

**Comment by neheb** [comment]
Looks like GCC8.

**Comment by djstkg** [comment]
> That's interesting. Which compiler and stdlib are you using?

`gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/8/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --disable-libphobos --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6)`

PasteBin on stdlib.h https://pastebin.com/FYVK98U3

**Comment by djstkg** [comment]
P.S. I just switched on ffmpegthumbnailer and circumvented the thing. But problem persists I guess.

**Comment by whyman** [comment]
This builds fine in the CI with GCC 9.2/Clang 9.

**Comment by Akkunasenbohrer** [comment]
I have exactly the same problem as djstkg.

FreeBSD 12.0-p7, amd64, 
gcc version 9.3.0 (FreeBSD Ports Collection)
