### ISSUE TITLE
Help creating a directory entry in the database

### ISSUE THREAD

**Issue by jpino1** [gerbera/gerbera#793]
I want to thank for the effort and the great work 
do in providing us with this great piece of software, I love it.

I need help to know how I could create an entry in the database 
that would give me the structure as it is in the filesystem 
but showing only the Path from the point where I mark it. 
I don't want the server to show the structure of the 
phisical disk server where Gerbera is hosted.

in fact I have hidden the server filesystem with the option:

 pc-directory upnp-hide = "yes" />

What I want would be something like this:
Database:
----------Audio:
----------------Folders:
----------------------(total content including subfolders from here).

Where the actual PATH in the filesystem would be:
/ mnt / raid / raid0 / multimedia / audio / (total content including subfolders from here).
                                                    Folders from this point --------->        
Thanks!

**Comment by whyman** [comment]
Hi,

This should be possible using the scripted layout.

It will take a small amount of Javascript but lets you render the tree as you want.

http://docs.gerbera.io/en/latest/scripting.html

**Comment by ghlupe2** [comment]
Hi, 
Make sure to have `<virtual-layout type="js"> 
`activated. This worked for me:
```
    var chain;
    var main = "Audio";
    var path = [];
    var dir = obj.location.split('/');
    var skip = 5; //directory levels to skip
    if (skip <= dir.length - 2) {
        for (i = skip; i <= (dir.length - 2); i++) {
            path.push(dir[i]);
            }
    }


    chain = [main, 'Folders'];
    chain = chain.concat(path);
    addCdsObject(obj, createContainerChain(chain));

```

**Comment by jpino1** [comment]
Thanks for your responses and for trying to help me.
@ ghlupe2
Thanks for giving me your script, very kind of you.

I have this option <virtual-layout type = "js"> activated in config.xml
I am not very clear where I have to insert the code.
I have tried several options:
-I added it to import.js
-I have replaced full import.js with this script
-I have created a separate script inside / usr / share / gerbera / js /dirs.js

I have called it dirs.js
 
But neither has worked for me I have tried to see the log file in var / log / gerbera.log to try to debug the problem but I can't find this file.
I keep testing until I run out of ideas.

**Comment by KarlStraussberger** [comment]
Your config.XML points to the file location (here's my example)

`<virtual-layout type="js">
   <import-script>/etc/gerbera/js/import-ks.js</import-script>
</virtual-layout>`

**Comment by jpino1** [comment]
At the end I have finished understanding how it works.
I have taken the photo/directories part, and I have modified it and pasted it in the Audio part  and  it works as i want. 
I have modified the import.js scrip  leaving the Audio section like this :


`  var track = '';

 **var dir = getRootPath(object_script_path, obj.location);

   if (dir.length > 0)
    {
        chain = new Array('Audio', 'Directories');
        chain = chain.concat(dir);

        addCdsObject(obj, createContainerChain(chain));
	}**

    
    chain = new Array('Audio', 'Artists', artist, 'All Songs');
    addCdsObject(obj, createContainerChain(chain));
                  
    chain = new Array('Audio', 'Genres', genre);
    addCdsObject(obj, createContainerChain(chain), UPNP_CLASS_CONTAINER_MUSIC_GENRE);
    
    chain = new Array('Audio', 'Year', date);
    addCdsObject(obj, createContainerChain(chain));
}
    
function addVideo(obj)`
