### ISSUE TITLE
Exception thrown by sockAddrGetNameInfo()

### ISSUE THREAD

**Issue by astylos** [gerbera/gerbera#805]
The error observed is:
2020-04-17 23:55:17   info: Exception: could not determine getnameinfo (Success) file:/home/david/projects/gerbera/src/util/tools.cc line:1302 function:sockAddrGetNameInfo

Gerbera doesn't respond to attempts to browse from foobar2000 (or bubbleupnp).

Looked at the code and errno is getting checked but mt_strerror(errno)==Success. Errno is only set if ret==EAI_SYSTEM. Debugger showed ret==EAI_FAMILY. It also shows a null pointer getting passed to getnameinfo(). Not an expert with sockets, but not sure that is correct?
```
(gdb) where
#0  sockAddrGetNameInfo[abi:cxx11](sockaddr const*) (sa=0x0) at /home/david/projects/gerbera/src/util/tools.cc:1299
#1  0x000000000059101f in Clients::getInfo (addr=0x0, userAgent="", ppInfo=0x7fffbc000df0)
    at /home/david/projects/gerbera/src/util/upnp_clients.cc:184
#2  0x00000000005922e3 in Quirks::Quirks (this=0x7fffbc000de0, 
    config=std::shared_ptr<ConfigManager> (empty) = {...}, addr=0x7fffbc004540, 
    userAgent="UPnP/1.0 DLNADOC/1.50 Platinum/1.0.4.2-bb / foobar2000")
    at /home/david/projects/gerbera/src/util/upnp_quirks.cc:38
#3  0x00000000005a993a in __gnu_cxx::new_allocator<Quirks>::construct<Quirks, std::shared_ptr<ConfigManager>&, sockaddr_storage const*&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (
    this=0x7fffd97f8f7f, __p=0x7fffbc000de0, 
    __args#0=std::shared_ptr<ConfigManager> (use count 10, weak count 0) = {...}, 
    __args#1=@0x7fffd97f9180: 0x7fffbc004540, __args#2="UPnP/1.0 DLNADOC/1.50 Platinum/1.0.4.2-bb / foobar2000")
    at /usr/include/c++/8/ext/new_allocator.h:136
```

**Comment by pamapa** [comment]
Looks like the addr in your case is nullptr. Are you using latest master with offical pupnp 1.12.1? I am some changes in that area yesterday.

**Comment by pamapa** [comment]
found and fixed the problem, thanks for reporting

**Comment by astylos** [comment]
OK, will try it later and let you know.

**Comment by astylos** [comment]
Looks good, thanks
