### ISSUE TITLE
Browsing playlists not working with some clients

### ISSUE THREAD

**Issue by zimj0** [gerbera/gerbera#807]
I build gerbera from source and am having issues browsing playlists when using the vlc player or BubbleUPnP as clients.
Vlc simply jumps to the next element.
BubbleUPnP shows a message: "The media server sent invalid data."

Both clients worked without issue with gerbera v1.4.0

[gerbera.log](https://github.com/gerbera/gerbera/files/4496266/gerbera.log)

**Comment by pamapa** [comment]
What sticks out is this:
```
&lt;upnp:album&gt;Hallo Frühling&lt;/upnp:album&gt;
```
The **ü** is not encoded...

**Comment by whyman** [comment]
This looks like #749 to me

**Comment by pamapa** [comment]
i am able to reproduce when i use **ü** in title

**Comment by pamapa** [comment]
I am trying to get a fix upstream:
https://github.com/zeux/pugixml/issues/342

**Comment by pamapa** [comment]
if upstream takes too long i can provide a workaround solution

**Comment by pamapa** [comment]
does not fully work

**Comment by pamapa** [comment]
it has nothing to do with the ä, i was looking into the wrong direction.

@whyman  
Your guess is correct #749, when i temporary skip `p:artist@role[AlbumArtist]` it start working again. So we need to fix this.

**Comment by pamapa** [comment]
@zimj0
should be fixed, can you try with latest master?

**Comment by zimj0** [comment]
Can confirm
