### ISSUE TITLE
Some clients do not show videos

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#819]
VLC and Windows Explorer do not show videos if [need some tests for the exact reason]
- caption file does not exist or 
- sec:CaptionInfoEx is present in the BrowseResponse.

No proper solution other than commenting out line 813 in upnp_xml.cc, yet.

May also be the reason for #707 .

**Comment by whyman** [comment]
Is this with a current master build?

**Comment by KarlStraussberger** [comment]
Yes.

**Comment by KarlStraussberger** [comment]
Compared with 1.4 output and found that xmlns:sec="http://www.sec.co.kr/" is missing in <DIDL-Lite ...>
