### ISSUE TITLE
media player stops after 30min

### ISSUE THREAD

**Issue by michel-briand** [gerbera/gerbera#821]
My PS4 will always stops playing after 30 min.
This is because default value of gerbera setting `alive` is `1800`.

I changed this value to `86400` and all movies play nicely.

**Comment by whyman** [comment]
That's an odd one. Alive is the time /2 between upnp announcement. It should have no bearing on the playback...

**Comment by michel-briand** [comment]
Indeed.
I spotted that the interval (30min) was the unique clue to figure out this issue.
So: _what if the SSDP Advertisement Interval was the cause of the media player to stop?_

I read this page and it decided me to test this assertion above:
> "Tip: If you regularly experience disconnection problems from your device when streaming videos at the 20-30 minute interval, you can try changing Mezzmo's advertisement value to 86400 (which is 24 hours)."
http://forum.conceiva.com/showthread.php/6245-FAQ-Change-the-default-SSDP-advertisement-interval

Another page confirmed my idea:
> https://www.ckode.dk/smart-tv/samsung-tizen-disconnects-or-freeze-when-playing-dlna-content-how-to-fix/

Anyway, I don't understand why the media player stops.
Bad client software, surely.

**Comment by whyman** [comment]
As an experiment what happens if you reduce the interval to say 5 minutes?

**Comment by michel-briand** [comment]
Interval set to 5 min: `<alive>300</alive>`.
Media player stopped after 5 min ...

**Comment by KarlStraussberger** [comment]
I can confirm this too. Setting it to its minimum of 62 kills the movie after 30 seconds or so. 

Afterwards gerbera disappears from the media server list. You need to restart the PS4 media play to get it rediscovered.

Ran some wireshark coverage to almost no avail. Right after the NOTIFY packet PS requests to end the stream.
![grafik](https://user-images.githubusercontent.com/23654788/80024561-8ad4d980-84df-11ea-8304-d6e802073efd.png)

PS4 obviously only expects SSDP packets after sending its M_SEARCH request.

**Comment by pamapa** [comment]
has it to do with this code? What happen when you comment that code?

server.cc
```
ret = UpnpRegisterClient(
        handleUpnpClientEventCallback,
        this,
        &clientHandle);
    if (ret != UPNP_E_SUCCESS) {
        throw UpnpException(ret, "run: UpnpRegisterClient failed");
    }
```

**Comment by whyman** [comment]
I wonder if somehow our advertisements are corrupted or invalid, and that upsets the PS4?

**Comment by KarlStraussberger** [comment]
> 
> 
> has it to do with this code? What happen when you comment that code?
> 
> server.cc
> 
> ```
> ret = UpnpRegisterClient(
>         handleUpnpClientEventCallback,
>         this,
>         &clientHandle);
>     if (ret != UPNP_E_SUCCESS) {
>         throw UpnpException(ret, "run: UpnpRegisterClient failed");
>     }
> ```

I'm sorry not.

@whyman Do you have a special part of our advertisement in mind? My son is willing to test!

**Comment by astylos** [comment]
Don't know if it is the same issue but gerbera disappears from foobar2000's media server list after some time and it takes a foobar2000 restart to get it back. This didn't used to happen, but doubt recal the version it did start. I'd assumed it was a new version of foobar that had caused it (even though the upnp plugin hadn't been updated in years). I'll try and take more notice of how long it takes to get dropped.

**Comment by KarlStraussberger** [comment]
We (my son and me) did a crosscheck with MiniDLNA 1.2.1 (ReadyDLNA) and Serviio 2.0 which causes the same issue even though the SSDP broadcast is quite different. So let's close this issue with the above comment in the documentation of "alive"

> If you experience disconnection problems from your device, e.g., Playstation 4, when streaming videos after about 5 minutes, you can try changing the alive value to 86400 (which is 24 hours)

**Comment by whyman** [comment]
@KarlStraussberger Thanks to you both. I suppose there is not much we can do here then.

**Comment by michel-briand** [comment]
Thank you all.
