### ISSUE TITLE
Not respecting folder hierarchy

### ISSUE THREAD

**Issue by Neocazen** [gerbera/gerbera#825]
Here's what's going on.
    If I have a folder named Animes, this folder does not appear in directories but what has inside it, regardless of the settings of autoscan
For example,
Directories/folder 1 folder 2... and not Directories/Animes/ folder 1 folder 2 ...

**Comment by pamapa** [comment]
Is it related to this? https://github.com/gerbera/gerbera/pull/714

In that case add the subfolder of Animes...

**Comment by Neocazen** [comment]
> Is it related to this? #714
> 
> In that case add the parent folder of Animes...

Understand. The way to choose folders now, in a way, changed then. Because with version 1.4 it worked as I said.
![Captura de tela de 2020-04-22 17-01-20](https://user-images.githubusercontent.com/15347187/80028723-f016d380-84bb-11ea-9e4c-221c280227a1.png)
![Captura de tela de 2020-04-22 17-01-36](https://user-images.githubusercontent.com/15347187/80028728-f0af6a00-84bb-11ea-97fb-e7443a7ce3c3.png)

**Comment by Neocazen** [comment]
It's just weird. I have a Movies folder in the same place and if I choose it, the Movies folder is created in the Video directory (even with the name '.') and looks like in previous versions. The problem is having subfolders as you can see earlier.
![Captura de tela de 2020-04-24 07-11-56](https://user-images.githubusercontent.com/15347187/80201760-fa8bb700-85fa-11ea-8811-d22e5c2da7d9.png)
![Captura de tela de 2020-04-24 07-12-27](https://user-images.githubusercontent.com/15347187/80201764-fb244d80-85fa-11ea-8f31-32434e1f26b3.png)
