### ISSUE TITLE
mimetype ignored for external url

### ISSUE THREAD

**Issue by cinhcet** [gerbera/gerbera#836]
Hi,

when I try to manually add an external url item via the web ui and set the mimetype to "audio/mpeg", this setting is ignored and it gets the octet-stream mimetype.

One of my renderers does not accept this mimetype. I can confirm that the external url works, since if I put it into a playlist and import that playlist, it gets the audio/mpeg mimetype.

What am I doing wrong?

**Comment by KarlStraussberger** [comment]
Please See #790 for this issue. It will be fixed in gerbera 1.5

**Comment by cinhcet** [comment]
thanks! (I only looked at open issues :-))
