### ISSUE TITLE
Unrecognized action X_SetBookmark (aka make resume work)

### ISSUE THREAD

**Issue by kyak** [gerbera/gerbera#848]
Hi!

I'm using latest gerbera git with Samsung UHD 4K 2019 model.

When stopping video, I see the following in the log file:

```
info: unrecognized action X_SetBookmark
error: ActionRequest::update(): response is nullptr, code -115 for X_SetBookmark
```

I assume that TV is trying to set a "bookmark" in order to resume playing from that moment later on.
However, resuming doesn't work.
What needs to be done in order to support resuming?

Resuming works perfectly when using minidlna with the same TV.

**Comment by whyman** [comment]
Hi, thanks for reporting.

Looks like another Samsung extension, yay!

There is a post over on the Serviio forum where someone has worked out how it works by sniffing the Samsung server response: https://forum.serviio.org/viewtopic.php?t=272#p6504

**Comment by whyman** [comment]
Now implemented thanks to @dyseg in #1288

**Comment by aleho** [comment]
How are multiple flags specified in the config?

Or-ed like this? Or comma separated? Couldn't find the place where its parsed at first glance.
Maybe I'm too stupid or docs need an update too?

```XML
<clients enabled="yes">
    <client ip="192.168.1.69" flags="SAMSUNG|SAMSUNG_BOOKMARK_SEC"></client>
</clients>
```

**Comment by kyak** [comment]
Nice, will try that, thanks!

**Comment by dyseg** [comment]
@aleho You guessed it right.
https://docs.gerbera.io/en/latest/config-clients.html
>Containing the flags you want to set. Must be given in the following format SAMSUNG|0x100, where the text either contains one of the known flags or an integer number if the flags has no name. For valid flags see: `Supported Devices`.

They are parsed here: https://github.com/gerbera/gerbera/blob/bb924ba43d5ba52fc6781539b1b01708a50d8d69/src/config/config_setup.cc#L1422-L1424

**Comment by whyman** [comment]
Note you will need to run a git build or 1.8.0 when it is released to use this feature :+1:
