### ISSUE TITLE
Docker container failing to run on arm32

### ISSUE THREAD

**Issue by neheb** [gerbera/gerbera#852]
I'm getting this error:

```
standard_init_linux.go:207: exec user process caused "exec format error"
```

It seems there is a file that is missing 
```
#!/bin/bash
```

at the top.

**Comment by whyman** [comment]
Which tag is this? What docker command did you run?

**Comment by neheb** [comment]
I used docker pull gerbera/latest and docker run gerbera/latest

**Comment by stheine** [comment]
On the docker hub, according to the tags, there is only 'amd64'. I'm running gerbera on my qnap nas, which is 'arm32'. that gives the same type of error message, so I'm building myself, based on the Dockerfile, which is a great help.

Also, I'd like to note that the docker hub documentation is not really helpful, as it describes how to build gerbera, which is exactly what's NOT required when running the dockered version.

**Comment by neheb** [comment]
I tried it on arm32 as well.

**Comment by whyman** [comment]
> Also, I'd like to note that the docker hub documentation is not really helpful, as it describes how to build gerbera, which is exactly what's NOT required when running the dockered version.

Yes, this is annoying, they just take the Github README which is not that useful.

**Comment by neheb** [comment]
So the issue is that the docker image is x86 only?

**Comment by whyman** [comment]
Yes, DockerHub only builds an `amd64` image.

**Comment by neheb** [comment]
Doesn’t sound right. linuxserver images on rocker hub are amd64, arm32, and arm64.

**Comment by whyman** [comment]
To build other arches on DockerHub you need to use qemu.... 

https://github.com/multiarch/qemu-user-static/blob/master/README.md

I want to switch our build to be done via Actions instead, as DockerHub builds are slow.

**Comment by unquietwiki** [comment]
Something like the following might work; I'm still playing with my setup...

- Make a directory in **/srv** to handle gerbera content (**/srv/gerbera**)
- **chown -R 1000:1000** that new directory
- **git clone https://github.com/gerbera/gerbera.git**
- **cd gerbera && docker build gerbera:arm64 .**
- **docker run -p 49152 -p 1900/udp --detach --restart always -v (local directory for gerbera config):/root -v (media directory):/media --name gerbera gerbera:arm64**

**Comment by whyman** [comment]
@unquietwiki Yes, one way to run on ARM/Pi currently is to build the dockerfile yourself on that hardware.

**Comment by unquietwiki** [comment]
@whyman Verified on Pi4 running ARM64 Ubuntu. You may want to review the setup I edited in my comment, and use that to help with the Docker Hub documentation.

BTW, I just found this tonight and posted it to Reddit too. Looks cool! https://www.reddit.com/r/opensource/comments/gv25xl/gerbera_a_free_media_server_stream_your_media_to/

**Comment by neheb** [comment]
I can't seem to get this working:

```

2020-06-04 05:47:19   info: Gerbera UPnP Server version 1.5.0 - http://gerbera.io/


2020-06-04 05:47:19   info: ===============================================================================


2020-06-04 05:47:19   info: Gerbera is free software, covered by the GNU General Public License version 2


2020-06-04 05:47:19   info: Copyright 2016-2020 Gerbera Contributors.


2020-06-04 05:47:19   info: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.


2020-06-04 05:47:19   info: ===============================================================================


2020-06-04 05:47:19   info: Loading configuration from: /root/.config/gerbera/config.xml


[*** LOG ERROR #0001 ***] [2020-06-04 05:47:19] [] {string pointer is null}
```

It just dies and reboots. happens on 1.5.0 and master.

**Comment by neheb** [comment]
Got it. A blank config.xml caused that.

**Comment by neheb** [comment]
It seems that port 1900 is not listening over IPv6. Bug?

**Comment by neheb** [comment]
I found my answer... https://github.com/gerbera/gerbera/issues/683#issuecomment-617617898

Guess I'll need to try that npupnp PR...
