### ISSUE TITLE
How to make UI File System view sort by directory name

### ISSUE THREAD

**Issue by ghlupe2** [gerbera/gerbera#855]
Gerbera looks via nfs at my NAS which contains folders with 100+ subfolders. They get displayed in the UI in a - to me at least - random manner. An alphabetical order as a default to me would make more sense. Or do I miss some way for configuration?

**Comment by whyman** [comment]
Can you post a screenshot?

**Comment by ghlupe2** [comment]
This is my directory
![ls](https://user-images.githubusercontent.com/16803676/81665887-34512000-9439-11ea-94c1-23eb44da47c1.jpg)

and how it looks like via Gerbera UI
![filesystem](https://user-images.githubusercontent.com/16803676/81666050-6b273600-9439-11ea-81a7-df9addc2df08.jpg)

while database view sorts OK
![database](https://user-images.githubusercontent.com/16803676/81666133-885c0480-9439-11ea-920e-73318eb4a7f5.jpg)

**Comment by whyman** [comment]
Thanks!

**Comment by ghlupe2** [comment]
Thanks a lot, will try ASAP

**Comment by ghlupe2** [comment]
Thanks, sorting perfectly now!
