### ISSUE TITLE
How to make the UI maintain the navigation path

### ISSUE THREAD

**Issue by ghlupe2** [gerbera/gerbera#856]
Switching between Database and File System view always resets the current navigation path which is quite inconvenient. Is there a way to configure this behavior? It's the same on Win10 / Chrome and Linux / Firefox.

**Comment by whyman** [comment]
Yes this is really annoying! Also during development when you reload the page it loses the path. Wanted to implement this for a while. Should be a simple case of pushing to the history API

**Comment by ghlupe2** [comment]
Works like a charm, thanks for this huge improvement!
