### ISSUE TITLE
Gerbera cannot tolerate an unused transcoding profile

### ISSUE THREAD

**Issue by fpoto** [gerbera/gerbera#862]
If I create a profile in the conf.xml that no transcode uses, Gerbera refuses to start.

As far as I can tell, this does not make sense, and forces me to add comments in the file for profiles I can use later of that I have used in the past.

**Comment by whyman** [comment]
Can you post a debug log? And try it with the latest 1.5.0 version.

**Comment by fpoto** [comment]
If you have an enabled profile that is not used, Gerbera exits after reading the config file.

In my opinion, the "enable" flag on profiles is useless: profiles just stay there, there is no point in enabling or disabling them, no point for Gerbera to check that a given profile is used or not and most importantly no point for Gerbera to error out and exit.

This one is tested with 1.5.0

```
gerbera[1746193]: 2020-05-17 23:32:48  error: [main.cc:302] main(): error in configuration: you specified a mimetype to transcoding profile mapping, but no match for profile "testunused" exists
pot systemd[1]: gerbera.service: Main process exited, code=exited, status=1/FAILURE
pot systemd[1]: gerbera.service: Failed with result 'exit-code'.
```

**Comment by KarlStraussberger** [comment]
You're right. The current checking does not really make sense, because it throws an error if the profile is unused but ignores a mapping with no profile!

Added two options that control checking: Unused mappings (changed behaviour) and unused profiles (activate to test profiles, turn off if config is stable).
