### ISSUE TITLE
Samsung TV UE40D6510, again

### ISSUE THREAD

**Issue by fpoto** [gerbera/gerbera#863]
I cannot have Gerbera interact with an old Samsung TV.

I use Gerbera packaged by Debian, which I fear is quite old. It is marked as 1.1.0 and packaged in November 2018. After adding to the conf lots of tricks found in the forums, among which samsung-hack and custom headers, I still get an unrecognised format message from the TV. It is an AVI file which Gerbera sees as video/x-msvideo, and the TV manual says it can decode Windows media video v9, so I suppose this is not the problem.

I get this in the logs:
ERROR: ActionRequest::update(): response is nullptr, code -115
I can try and debug something if instructed how to.

**Comment by whyman** [comment]
I doubt we are going to want to spend much time supporting that older version.

Can you try the latest 1.5.0 version?

**Comment by fpoto** [comment]
I will. I see that deb-mulimedia carries 1.5.0, so I'll install that and retry adn report

**Comment by eisengrau** [comment]
Hello, and sorry for hijacking the issue.

I have checked deb-multimedia, and it does not have the latest 1.5 version, unfortunately. I have also tried the AUR git package on Arch, but for reasons over me (not really familiar with Arch linux) I had problems getting dependencies resolved (timed-out Arch mirros, not available packages, etc).

Maybe it is possible to complie from git on Debian Buster (?)

**Comment by fpoto** [comment]
It's there for testing (Bullseye) at least: http://deb-multimedia.org/dists/testing/main/binary-amd64/package/gerbera

In fact, I've installed it but it does not appear to work out-of-the-box: pointing either Firefox or Chromium at http://10.20.30.4:49152 shows the main page but clicking on the links does nothing. Will have to investigate

**Comment by eisengrau** [comment]
Sorry, my bad! I checked the bullseye repo, and 1.5.0 is indeed available there! Just installed it.

What I noticed for me, that the links are working, but the layout is messed-up in Firefox and also in Chromium.

**Comment by pamapa** [comment]
@fpoto
regarding older Samsung TVs see my comment https://github.com/gerbera/gerbera/issues/323#issuecomment-624827326

**Comment by fpoto** [comment]
> @fpoto
> regarding older Samsung TVs see my comment [#323 (comment)](https://github.com/gerbera/gerbera/issues/323#issuecomment-624827326)

This could explain the error I observed with 1.1.0 which I described in the original post, right?

**Comment by whyman** [comment]
> What I noticed for me, that the links are working, but the layout is messed-up in Firefox and also in Chromium.

Make sure you clear your cache. If it still doesnt work after that, open browser dev tools, and check the network tab, likely some files are missing

**Comment by fpoto** [comment]
> > What I noticed for me, that the links are working, but the layout is messed-up in Firefox and also in Chromium.
> 
> Make sure you clear your cache. If it still doesnt work after that, open browser dev tools, and check the network tab, likely some files are missing.
> 
> I think the debian packaing is a bit borked: #757

Curious. When I installed the Debian one everything worked. When I upgraded to the deb-multimedia one, links did not work. Upon inspection, I discovered that the bootstrap.js installation ended up in an infinite symlink loop. `apt-get reinstall libjs-bootstrap` cured the problem. This looks like the same problem reported in #757
