### ISSUE TITLE
Build Deb packages via Github Actions

### ISSUE THREAD

**Issue by AFDudley** [gerbera/gerbera#867]
It should be possible to generate the deb for the PPA via github actions instead of waiting for someone to do it after a release, I'm volunteering to help if required.

**Comment by whyman** [comment]
@stephen-czetty has generally done a good job of keeping on top of the maintenance of his PPA.

That said PRs are always welcome.

**Comment by ytimenkov** [comment]
I wonder whether it's an acceptable option to just make a standalone package with CPack?

I don't follow modern tends with flatpack, snap, etc, but it should be possible to just drop all dependencies into `/opt/gerbera` and guarantee to run. Letting cpack create an rpm and deb should cover quite meant demands. These could be attached to releases making it even more accessible.

Sure, being "natively" integrated into a distro has many benefits, but gerbera started requiring fairly new libraries and figuring out what to install for each distribution is an insane amount of work for few active contributors.

**Comment by whyman** [comment]
I guess CPack and a static build would be easiest. We have no issues linking to things as we are GPLv2 anyway.

**Comment by whyman** [comment]
This is done, packages are not built and published to Bintray. You can also build your own package using CPack.
