### ISSUE TITLE
autoscan with Inotify only works after manually adding an item

### ISSUE THREAD

**Issue by fpoto** [gerbera/gerbera#868]
Using UI on a just-installed 1.5.0

I go to the video directory and set recursive autoscan with inotify from the UI. I do the same for photos and music. I then look at the database of indexed files and it's empty.

I go back to the video directory and press + on one video file. I get no feedback from the UI. If I now look at the database, all video files are there.

I do the same with one photo file, and I see that all photo files appear in the database. I do the same with audio, and now I have all my files in the database.

So two bugs here:
- pressing the + should elicit some feedbackl from the UI
- setting inotify recursive autoscan should populate the database immediately

**Comment by fpoto** [comment]
Apparently this bug is another consequence of #872

**Comment by whyman** [comment]
https://github.com/gerbera/gerbera/issues/872#issuecomment-630075349
