### ISSUE TITLE
Scripting error message gives line:# of script.cc instead of import.js

### ISSUE THREAD

**Issue by ghlupe2** [gerbera/gerbera#869]
If Gerbera fails to compile the import script it displays 

`error: ContentManager virtual container layout: Scripting: failed to compile /path/to/active/import.js` 

which is good, plus

`file:/path/to/gerbera/src/scripting/script.cc line:299 function:_load` 

which does not make sense to me. Formally line:# used to refer to the import script.

I wonder if this is only the case if you compile gerbera from source?

**Comment by whyman** [comment]
The `file:/path/to/gerbera/src/scripting/script.cc line:299 function:_load` is from the Exception that is thrown in the C++, per: https://github.com/gerbera/gerbera/blob/45dc09e76d9c07921a2c246b02b94520ac80ce1d/src/exceptions.h#L47-L48.

**Comment by ghlupe2** [comment]
I wanted to say: **formerly** (i. e. Mediatomb) the error message referred to the line number of import.js

@whyman: 

> The `file:/path/to/gerbera/src/scripting/script.cc line:299 function:_load` is from the Exception that is thrown in the C++, per:
> 
> https://github.com/gerbera/gerbera/blob/45dc09e76d9c07921a2c246b02b94520ac80ce1d/src/exceptions.h#L47-L48
> .

And do you agree that this needs to be fixed?

**Comment by KarlStraussberger** [comment]
Your issues comes from a severe error like missing braces so load fails. In this case even MT did not print the error message. Just added a PR to print it.

**Comment by ghlupe2** [comment]
This is great, your commit #940 does what it says and shows the duk script error message. Thank you for that! 

The line number and path however still refers to the gerbera source in my home directory from where I compiled.

```
2020-07-14 17:14:16  error: Failed to execute script: TypeError: cannot read property 'replace' of undefined
2020-07-14 17:14:16  error: Exception caught: Script: failed to execute script file:/home/elmar/gerbera/src/scripting/script.cc line:317 function:_execute
```

**Comment by KarlStraussberger** [comment]
We can only print what dukTape returns. Mediatomb was build on another lib which had other flaws.

**Comment by ghlupe2** [comment]
I see, better than the problems we had to get libmozjs2 in ancient versions running on current systems

**Comment by ghlupe2** [comment]
Just wanted to correct myself and confirm, that in many cases duktape does return the script line number, like

`error: Failed to load script: SyntaxError: invalid regexp flags (line 393) `

Thanks again for this very useful enhancement!
