### ISSUE TITLE
Gerbera ppa for Ubuntu dead?

### ISSUE THREAD

**Issue by emk2203** [gerbera/gerbera#878]
The gerbera ppa for Ubuntu was last touched half a year ago and still carries the old 1.3.5, and nothing for the new LTS release 20.04. I have asked the maintainer if there will be updates, but this was unanswered. I assume this ppa is dead for now, but the Gerbera Ubuntu install instructions point to it.

Could we have an update for the Ubuntu install instructions to get something up-to-date, i. e. version 1.5.0 on Ubuntu 20.04LTS?

**Comment by whyman** [comment]
Oh, thats a shame :disappointed: 

I guess we need another community member to step up and maintain a PPA.

I certainly don't have time (or run Ubuntu).

**Comment by stephen-czetty** [comment]
I am so sorry, I was maintaining the ppa, but life happened.  Please be patient, I hope to bring things back to current within the next month or so.

**Comment by whyman** [comment]
Nice!

**Comment by emk2203** [comment]
Works well with armhf architecture. 1.6.0 installed without a hitch and removed the irritating error message I had at startup as well. For a media device, supporting only Ubuntu focus and up is a good strategy.

**Comment by lastonpl** [comment]
Cannot install on 20.04. Any workaround? It's unfortunate that the most common distribution is not properly supported.
