### ISSUE TITLE
Browsing files error

### ISSUE THREAD

**Issue by b4r0z** [gerbera/gerbera#879]
I'm trying to access via GUI some directories named after dates and years but I can't as Gerbera returns this error:

`{"success":true,"containers":{"parent_id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c6174657374","select_it":0,"type":"filesystem","container":[{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f32303133","child_count":1,"title":2013},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f32303139","child_count":1,"title":2019},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f30313331","child_count":1,"title":0131},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f30333135","child_count":1,"title":0315},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f30323239","child_count":1,"title":0229},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f30353135","child_count":1,"title":0515},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f32303136","child_count":1,"title":2016},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f32303138","child_count":1,"title":2018},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f32303134","child_count":1,"title":2014},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f32303135","child_count":1,"title":2015},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f30343330","child_count":1,"title":0430},{"id":"2f7372762f6465762d6469736b2d62792d6c6162656c2d46726565636f6d2f626172657269612f6d70332f6c61746573742f32303137","child_count":1,"title":2017}]}}×`

1 digit directory name is ok, 2 or more digits directory name result in errors.

is it me? did I make some error compiling?

**Comment by b4r0z** [comment]
the problem is the due to a name two or more digits with a 0 as first digit.
adding a character at the end (even a space) then gerbera can browse again

**Comment by whyman** [comment]
Interesting, looks like we need to force the title to be a string when we are encoding it as JSON.

**Comment by KarlStraussberger** [comment]
```
util/xml_to_json.cc line 118
``` seems responsible for this behaviour. Do we add some hint-property or hard-code it for title?

**Comment by whyman** [comment]
> `util/xml_to_json.cc line 118` seems responsible for this behaviour. Do we add some hint-property or hard-code it for title?

via hints, if possible

**Comment by KarlStraussberger** [comment]
Should be fixed by PR #900. Could you please double check on your side.

**Comment by KarlStraussberger** [comment]
fixes

**Comment by b4r0z** [comment]
Hello, I managed to compile 1.6.1 on my BananaPi but for some reasons I can't still browse directories and I'm getting the same messages from my first post.
#900 was supposed to be fixed, am I right?

**Comment by KarlStraussberger** [comment]
It is fixed, but there may be other properties that could break the ui. Can you share the messages from the web console?

**Comment by b4r0z** [comment]
sorry for tha late reply!
I get the same message, no browsing but the directory can nonetheless be added to the database.

 {"success":true,"containers":{"parent_id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c6174657374","select_it":0,"type":"filesystem","container":[{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30313331","child_count":true,"title":0131},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30323239","child_count":true,"title":0229},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30333135","child_count":true,"title":0315},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30343330","child_count":true,"title":0430},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30353135","child_count":true,"title":0515},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30353331","child_count":true,"title":0531},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30363135","child_count":true,"title":0615},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30373135","child_count":true,"title":0715},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30373331","child_count":true,"title":0731},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30383331","child_count":true,"title":0831},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30393135","child_count":true,"title":0915},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f30393330","child_count":true,"title":0930},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f31303135","child_count":true,"title":1015},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f32303135","child_count":true,"title":2015},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f32303136","child_count":true,"title":2016},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f32303137","child_count":true,"title":2017},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f32303138","child_count":true,"title":2018},{"id":"2f736861726564666f6c646572732f66726565636f6d2f626172657269612f6d70332f6c61746573742f32303139","child_count":true,"title":2019}]}}

**Comment by KarlStraussberger** [comment]
Thank you, I found two more places where a digit-only title may cause trouble.

**Comment by b4r0z** [comment]
thank you!
can't wait to text the new build when ready
