### ISSUE TITLE
UPNP.Truncate the whole directory structure.

### ISSUE THREAD

**Issue by Alezzzander** [gerbera/gerbera#887]
Hello,Devs!
Could you make option in web gui or config file to change root folder to browse?
Currently clients must browse full path from / to rearch desired folder. Is it possible to change it after import?
I know,that there is a script in archwiki mediatomb page,but i dont know what should i do with it :)

**Comment by KarlStraussberger** [comment]
@whyman: What do you think about a mapping of the generated virtual structure to new paths with some sort of pattern. The perfect place would be ContentManager::addContainerChain.

This would solve serveral issues/feature requests currently open and enable the user to simply define its own layout without further scripting.

**Comment by KarlStraussberger** [comment]
fixed

**Comment by michaelbagrov** [comment]
Hello devs. I'm trying to achieve the behaviour expected to be possible after this fix, but it seems that something is not working as expected. Or I'm doing something wrong.
My configuration:
`
    <autoscan use-inotify="yes">
        <directory location="/cloud/shared" mode="inotify" recursive="yes" hidden-files="no"/>
    </autoscan>

    <layout parent-path=“no”>
        <path from="cloud/shared“ to=“Content”/>
    </layout>
`
I'm expecting, that all the contents of the /cloud/shared directory will be under PC Directory/Content. Instead of that I'm getting everything in PC Directory/cloud/shared/

Please help to understand where the issue is.

**Comment by KarlStraussberger** [comment]
Thank you for asking, but the mapping only works for virtual layouts which in some places also reflect the physical structure.

Everything under PC Directory does. It holds all files regardless of their types and cannot be manipulated. You may hide PC Directory and use virtual folders only, which typically are focused on media type and meta data.

**Comment by michaelbagrov** [comment]
Thank You @KarlStraussberger for speedy reply. Now the behavior is crystal clear.
Wouldn't it be too much to ask for an advice a configuration sample to fulfill the following need:
To have a virtual folder, which would aggregate content of different physical directories, including paths to the files in these directories, but omitting pats to these directories.
For instance:
Physical directories:
/cloud/shared/photo/**/*
/mnt/media/video/**/*
Virtual folder with name "Contents" to have:
Contents/photo/**/*
Contents/video/**/*

**Comment by KarlStraussberger** [comment]
The virtual layout we create has Photo and Video right below root like PC Directory.

So if you use autoscan directory `/cloud/shared/photo` you will get `/Photos/Directory/**` if you set `<layout parent-path="no"> ...` (https://docs.gerbera.io/en/stable/config-import.html#layout)

For the other layout you need to overload  some javascript functions (https://docs.gerbera.io/en/stable/scripting.html#index-0)
