### ISSUE TITLE
Scraping http link from video tag

### ISSUE THREAD

**Issue by frankwalter1301** [gerbera/gerbera#893]
It will be fantastic if there is a functionality to extract the http video stream from a web page with a video player. Or at least to try. The most basic form is to parse the html and get the http stream from the video tag. So people can just copy a link and load it into gerbera web UI.

Also, I think it will be good if are not only single websites supported, but instead the protocol that the website uses, so that can be utilisable with all websites that use it.

**Comment by whyman** [comment]
I think your idea in #893 could possibly be a good generic solution. We do not want to be scraping web pages ourselves.
