### ISSUE TITLE
Streamlink implementation in the webui

### ISSUE THREAD

**Issue by frankwalter1301** [gerbera/gerbera#894]
To make streaming from websites user-friendly, it would be cool to implement a streamlink wrapper (a software that supports many web streaming protocols and outputs an http stream as output) in the web-ui and use it in conjunction with Gerbera.

If you like I can work on it.

**Comment by whyman** [comment]
Interesting idea, how do you see it working? What would be shown to clients? How would an import work?

**Comment by cweiske** [comment]
No answer in 4 years. I think this can be closed.
