### ISSUE TITLE
Testing exotic platforms / architectures

### ISSUE THREAD

**Issue by ytimenkov** [gerbera/gerbera#896]
Basically a question how the subject is done and whether anyone cares?

Also how to determine minimal required version for dependency and when to bump it.

There is some code requires special handling for Solaris and FreeBSD which may be obsolete now, but how to test the build?

Gerbera requires C++17 which means at least compiler sound be 3-4 years old... Also recent requirement for punpn which is not in most distros...

Also how / who is responsible for non-x86 architectures (arm maybe more popular with pie, but also mips, sparc?)

**Comment by whyman** [comment]
I think we should make reasonable efforts to support people regardless of platform. We are not doing anything overly arch specific.

Ive heard of people running on x86_64 servers, ARM devices like Pis, but also MIPS based routers via entware etc. I doubt anyone is on SPARC now, though.

I have been meaning to get ARM32/64 builds into the CI for a while, for example.

In terms of compilers and libraries we should depend on the versions that make development most simple, as users will likely use packaged versions anyway.

**Comment by ytimenkov** [comment]
Makes sense.

My major concern is no CI => no guarantee that things won't suddenly break 🙁.

I think for arm/mips it should be possible to cross-compile with docker and tools are likely modern (well, rpi runs a distro, so it's similar to x86 in terms of runtime dependencies).

However I have no idea about bsd and Solaris... Bsd I assume it's freenas (or how it's called today) but I don't know if there are any services for open source projects like Travis.
