### ISSUE TITLE
InternetRadio not available on upnp-client

### ISSUE THREAD

**Issue by franconianmetal** [gerbera/gerbera#897]
Hi,
I added some Internet-Radio-urls which work fine within gerbera.
Browser opens the stream-player.
But trying to find on my upnp-client (i.e. vlc) there is no entry for these radio-urls to play via vlc (bubbleupnp behaves the same)
Other media is working fine

What can I do to make these urls to be visible in the upnp-clients and to start streaming

![Bildschirmfoto vom 2020-06-03 19-52-24](https://user-images.githubusercontent.com/18643293/83670805-02645100-a5d4-11ea-956f-f5c30e560e67.png)
![Bildschirmfoto vom 2020-06-03 19-52-41](https://user-images.githubusercontent.com/18643293/83670814-06906e80-a5d4-11ea-869c-92cc4b20b8c1.png)

**Comment by whyman** [comment]
Can you paste a debug log?

**Comment by whyman** [comment]
Also, please make sure you are using the latest 1.5 version!

**Comment by franconianmetal** [comment]
thanks, solved the problem
