### ISSUE TITLE
Static code analysis for finding possible bugs [code-quality][WIP]

### ISSUE THREAD

**Issue by unquietwiki** [gerbera/gerbera#898]
[gerbera-flawfinder.txt](https://github.com/gerbera/gerbera/files/4725926/gerbera-flawfinder.txt)

Bunch of [race condition](https://cwe.mitre.org/data/definitions/362.html) issues detected by [Flawfinder](https://dwheeler.com/flawfinder/). [cppcheck](http://cppcheck.sourceforge.net/) seemed more forgiving; both it and myself are really confused by all the division operators used on **fs::path** & **std::string** variables, and therefore it thinks they're divide-by-zero possibilities. I spend more time in C#, C, and JS; I know C++ can have overloaded operators.

The easiest fix I spotted via cppcheck is that **src/utils/tools.cc** has two **getnameinfo** calls that could have zero-lengths on their **len** properties. I think [try/catch](https://en.cppreference.com/w/cpp/language/try_catch) will work if you're compiling on a newer C++ standard.

**Comment by ytimenkov** [comment]
Much of stuff it rants on is 12+ years old and should be replaced with C++ standard equivalent.

Another part is that many security "issues" reported are not really a viable attack vector: whoever has access to local fs can do much more.

I was also thinking that some asio/afio library with proper event loop (even libuv) would be nice to use, getting benefits like new uring. However content serving part is in libupnp and I don't know how it's extensible.

> both it and myself are really confused by all the division operators used on fs::path & std::string variables

I imagine your reaction on boost.spirit then 😂

**Comment by unquietwiki** [comment]
@ytimenkov thanks for the feedback on this. I'm used to running older code, which really does have issues & still rely on C99, let alone any newer C++ (I learned C++ ~2000, before all the new revisions). As someone who's been both IT admin, and developer; I've developed a belief that good code = less stress for everyone.

boost.sprint... I found https://panthema.net/2018/0912-Boost-Spirit-Tutorial/slides-2018-09-12-Cpp-Meetup.pdf ; at least this kinda makes sense, though I think C# is cleaner. 🔢

**Comment by ytimenkov** [comment]
@unquietwiki 
Could you please elaborate on this:
> The easiest fix I spotted via cppcheck is that src/utils/tools.cc has two getnameinfo calls that could have zero-lengths on their len properties. I think try/catch will work if you're compiling on a newer C++ standard.

What is the problem and example mitigation. I'm really curios.

**Comment by unquietwiki** [comment]
Hey @ytimenkov . So, calls like that would like to know the length of the string being provided, and programs usually crash on null or zero-input for such things. So either there needs to be an **if/then** for **len == 0**, or a **try/catch** block that would handle what would happen if that call failed because of a bad string length, or some other issue.

**Comment by neheb** [comment]
Simple way to crash gerbera... create an empty config.xml file using touch config.xml or whatever.

clang-analyzer also has a bunch of complaints. I think that's where any work on fixing issues needs to start.
