### ISSUE TITLE
Can't play mp3 on Samsung UHD 4k 2019

### ISSUE THREAD

**Issue by St3ll4rM4n** [gerbera/gerbera#901]
Guys,

I'm using latest GIT Gerbera (06.06.2020) and can play literaly all files (mp4, mkv, mov, jpg, png, etc) but not mp3.

My TV says format not supported. 

Any ideas?

`
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [server.cc:485] createRequestHandler(): Filename: /content/media/object_id/169574/res_id/0/ext/file.mp3
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:69] getInfo(): start
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [upnp_clients.cc:218] getInfo(): client info: 192.168.1.13:38077 'samsung-agent/1.1' -> 'Unknown' as None
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:85] getInfo(): full url (filename): /content/media/object_id/169574/res_id/0/ext/file.mp3, parameters: object_id/169574/res_id/0/ext/file.mp3
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:148] getInfo(): path: /storage2/public/Music/Luke Bryan/Luke Bryan - What Makes You Country (2017)/08-Land Of A Million Songs.mp3
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:156] getInfo(): fetching resource id 0
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [upnp_headers.cc:63] addHeader(): Adding header: 'contentFeatures.dlna.org: DLNA.ORG_PN=DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01200000000000000000000000000000'
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [upnp_headers.cc:63] addHeader(): Adding header: 'transferMode.dlna.org: Streaming'
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:248] getInfo(): web_get_info(): end
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [server.cc:485] createRequestHandler(): Filename: /content/media/object_id/169574/res_id/0/ext/file.mp3
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:254] open(): start
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:265] open(): full url (filename): /content/media/object_id/169574/res_id/0/ext/file.mp3, parameters: object_id/169574/res_id/0/ext/file.mp3
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:273] open(): Opening media file with object id 169574
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:387] open(): fetching resource id 0
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [content_manager.cc:1646] triggerPlayHook(): start
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [content_manager.cc:1666] triggerPlayHook(): end
Jun 06 23:25:08 myserver gerbera[499703]: 2020-06-06 23:25:08  debug: [file_request_handler.cc:467] open(): end
`

Clients tab shows multiple lines for my TV.

192.168.1.13 | 192.168.1.13 | Samsung other TVs | DLNADOC/1.50 SEC_HHP_[TV] My UHD TV/1.0 UPnP/1.0 | UserAgent | SEC_HHP_ | SamsungSeriesCDE | Sat Jun 6 23:12:30 2020 | Sat Jun 6 23:18:23 2020 | SAMSUNG
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
192.168.1.13 | 192.168.1.13 | Unknown |   | None |   | None | Sat Jun 6 23:12:33 2020 | Sat Jun 6 23:16:52 2020 | None
192.168.1.13 | 192.168.1.13 | Unknown | samsung-agent/1.1 | None |   | None | Sat Jun 6 23:12:42 2020 | Sat Jun 6 23:17:53 2020 | None

**Comment by KarlStraussberger** [comment]
I suggest to add a client entry in the config.XML for your TV's IP and set flags to SAMSUNG. This forces Samsung mode for all renderers in your TV.

**Comment by whitesnake-pl** [comment]
I added following lines to config.xml but still doesn't work. However, I see that it identifies the samsung-agent correctly now and sets the SAMSUNG flag.

`
  <clients enabled="yes">
    <client ip="192.168.1.13" flags="SAMSUNG"></client>
  </clients>
`

Debug:
`
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [server.cc:485] createRequestHandler(): Filename: /content/media/object_id/169570/res_id/0/ext/file.mp3
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:69] getInfo(): start
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [upnp_clients.cc:218] getInfo(): client info: 192.168.1.13:51617 'samsung-agent/1.1' -> 'Manual Setup for UserAgent samsung-agent/1.1' as None
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:85] getInfo(): full url (filename): /content/media/object_id/169570/res_id/0/ext/file.mp3, parameters: object_id/169570/res_id/0/ext/file.mp3
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:148] getInfo(): path: /storage2/public/Music/Luke Bryan/Luke Bryan - What Makes You Country (2017)/05-Sunrise, Sunburn, Sunset.mp3
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:156] getInfo(): fetching resource id 0
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [upnp_headers.cc:63] addHeader(): Adding header: 'contentFeatures.dlna.org: DLNA.ORG_PN=DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01200000000000000000000000000000'
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [upnp_headers.cc:63] addHeader(): Adding header: 'transferMode.dlna.org: Streaming'
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:248] getInfo(): web_get_info(): end
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [server.cc:485] createRequestHandler(): Filename: /content/media/object_id/169570/res_id/0/ext/file.mp3
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:254] open(): start
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:265] open(): full url (filename): /content/media/object_id/169570/res_id/0/ext/file.mp3, parameters: object_id/169570/res_id/0/ext/file.mp3
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:273] open(): Opening media file with object id 169570
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:387] open(): fetching resource id 0
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [content_manager.cc:1646] triggerPlayHook(): start
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [content_manager.cc:1666] triggerPlayHook(): end
Jun 07 08:44:52 myserver gerbera[522122]: 2020-06-07 08:44:52  debug: [file_request_handler.cc:467] open(): end
`

Clients entry tab:
`
192.168.1.13 | 192.168.1.13 | Manual Setup for UserAgent samsung-agent/1.1 | samsung-agent/1.1 | UserAgent | samsung-agent/1.1 | None | Sun Jun 7 08:41:52 2020 | Sun Jun 7 08:41:52 2020 | SAMSUNG
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
`

Am I missing something?

**Comment by KarlStraussberger** [comment]
Looks good now. Cannot see any issue in your log. Does the file play from another source like USB?

**Comment by whitesnake-pl** [comment]
Yup it's fine from USB.

Also, I was using Universal Media Server before and all including mp3 was fine. However it's was to heavy and that's the reason I switched to Gerbera.

**Comment by whitesnake-pl** [comment]
I tried to play with mapping mimetypes to 
audio/mpeg3
audio/mpg3
audio/x-mpeg-3
audio/x-mpeg3
but gerbera reports in log that format is not supported.

**Comment by KarlStraussberger** [comment]
Can double check in the gerbera ui which mime type is set for your mp3 files. Also, there should be a mapping entry 
`<mimetype-contenttype>
                                <treat mimetype="audio/mpeg" as="mp3"/> ...`. 

Did you try downloading the file (GET ...) with your browser?

**Comment by whitesnake-pl** [comment]
Mimetype is set in default to "audio/mpeg" as you wrote. I tried to play with it setting to the values which I mentioned in previous comment but this did not help. I'm in default setting back again.

I have the following in UI

> Type
Item
Title
05-Sunrise, Sunburn, Sunset.mp3
Location
/storage2/public/Music/Luke Bryan/Luke Bryan - What Makes You Country (2017)/05-Sunrise, Sunburn, Sunset.mp3
Class
object.item.audioItem.musicTrack
Description
Mimetype
audio/mpeg

Just to mention, the file plays well via UI, using GET and also on my Iphone via VLC and UPNP from Gerbera. 
Looks like it's really specific to my TV and Gerbera.... But again, the files from USB and other UPNP server - UMS  plays well.

**Comment by KarlStraussberger** [comment]
Obviously the issue is client related. Can you check out the [UMS renderers](https://github.com/UniversalMediaServer/UniversalMediaServer/tree/master/src/main/extrnal-resources/renderers) for some hints on specific handling for your device

**Comment by whitesnake-pl** [comment]
This is the [config ](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/master/src/main/external-resources/renderers/Samsung-UHD.conf)which is being used during play in UMS.

Here are the logs from UMS.

> DEBUG 2020-06-19 22:18:37.637 [cling-8] New renderer found: "[TV] My UHD TV" with dlna details: {friendlyName=[TV] My UHD TV, address=192.168.1.13, udn=uuid:e2733262-6522-43b2-be22-d43ac2df46a9, manufacturer=Samsung Electronics, modelName=UE65NU8042, modelNumber=AllShare1.0, modelDescription=Samsung TV DMR, manufacturerURL=http://www.samsung.com/sec, modelURL=http://www.samsung.com/sec}
DEBUG 2020-06-19 22:18:37.638 [cling-8] Adding device: urn:schemas-upnp-org:device:MediaRenderer:1 (RemoteDevice) Identity: (RemoteDeviceIdentity) UDN: uuid:e2733262-6522-43b2-be22-d43ac2df46a9, Descriptor: http://192.168.1.13:9197/dmr, Root: true

Below is also some short TRACE data from debug.log file

> GET /get/63/03-Simple.mp3 HTTP/1.1

>HEADER:
  Host: 192.168.1.10:6001
  Range: bytes=0-
  User-Agent: samsung-agent/1.1
  Accept: */*
  Accept-Encoding: deflate, gzip

>Renderer UUID=uuid:e2733262-6522-43b2-be22-d43ac2df46a9
TRACE 2020-06-19 22:19:38.787 [HTTPv2 Request Worker 7] Asked stream chunk : TimeRange [start=null, end=null] of 03-Simple.mp3 and player null
TRACE 2020-06-19 22:19:38.787 [HTTPv2 Request Worker 7] Setting lastStartPosition from time-seeking: 0.0
TRACE 2020-06-19 22:19:38.791 [HTTPv2 Request Worker 7] Sending 7531387 bytes.
TRACE 2020-06-19 22:19:38.792 [StartPlaying Event] Matched media renderer "[TV] My UHD TV" based on address 192.168.1.13
INFO  2020-06-19 22:19:38.794 [StartPlaying Event] Started playing 03-Simple.mp3 on your [TV] My UHD TV
DEBUG 2020-06-19 22:19:38.795 [StartPlaying Event] The full filename of which is: /storage2/public/Music/Florida Georgia Line/Florida Georgia Line - Can't Say I Ain't Country (2019)/03-Simple.mp3 and the address of the renderer is: 192.168.1.13
TRACE 2020-06-19 22:19:38.796 [HTTPv2 Request Worker 7] Transfer response sent to [TV] My UHD TV [Samsung LED UHD]:

>HEADER:
  HTTP/1.1 206 Partial Content (non-chunked)
  Content-Type: audio/mpeg
  Content-Range: bytes 0-7531386/7531387
  Accept-Ranges: bytes
  Connection: keep-alive
  Server: Linux-amd64-5.7.2-arch1-1, UPnP/1.0 DLNADOC/1.50, UMS/9.4.3
  Content-Length: 7531387

Any other thoughts what I can do/check?

**Comment by neheb** [comment]
Just tried this with my TV. Can't play FLAC either. Used to be able to...

**Comment by KarlStraussberger** [comment]
Your issue is pending for a long time already.

Triggered by another issue I've been looking at `contentFeatures.dlna.org: DLNA.ORG_PN=DLNA.ORG_PN=MP3` which looks broken to me. There have been quite some changes to that code in the meantime so I wonder whether you are able to test again.

**Comment by tietzc** [comment]
Still doesn't work on Samsung RU7179 UHD 4k.

**Comment by KarlStraussberger** [comment]
What's your gerbera version?

What's the output of `gerbera --compile-info`.

Did you rebuild the database after updating.

Can you provide some debug log with the client's requests?

**Comment by tietzc** [comment]
> What's your gerbera version?
> 
1.11.0
> What's the output of `gerbera --compile-info`.
> 
Gerbera UPnP Server 1.11.0
Copyright 2016-2022 Gerbera Contributors.
Licence GPLv2: GNU GPL version 2.
This is free software: you are free to change and redistribute it.

Compile info
-------------
WITH_NPUPNP=NO
WITH_MAGIC=yes
WITH_MYSQL=no
WITH_CURL=no
WITH_INOTIFY=1
WITH_JS=yes
WITH_TAGLIB=yes
WITH_AVCODEC=yes
WITH_FFMPEGTHUMBNAILER=no
WITH_EXIF=yes
WITH_EXIV2=no
WITH_MATROSKA=yes
WITH_WAVPACK=NO
WITH_SYSTEMD=no
WITH_LASTFM=no
WITH_DEBUG=no
WITH_TESTS=NO

> Did you rebuild the database after updating.
> 
Yes.
> Can you provide some debug log with the client's requests?
Not now.
