### ISSUE TITLE
Initialization / reload logic is too complicated

### ISSUE THREAD

**Issue by ytimenkov** [gerbera/gerbera#904]
> Simple way to crash gerbera... create an empty config.xml file using touch config.xml or whatever.

_Originally posted by @neheb in https://github.com/gerbera/gerbera/issues/898#issuecomment-641072060_

I noticed that initialization failure of upnp (e.g. if configured to bind to `lo`) leads to some entanglement in initialization/shutdown.

Much of complexity (and issues) come from "reload" logic, because otherwise it is possible to rewrite `main()` into a simpler flow.

Moreover, I'm not sure that it correctly reloads config.

So my question is whether this reload needed and isn't it possible to rely on restart by system?

**Comment by whyman** [comment]
I was going to write that I think its useful to keep it, but I am not convinced on my reasoning, which was that generally we do a full folder scan on start-up, which is a pretty heavy operation. And you would end up doing said scan for every config edit, which with a large library is pretty rough.

**Comment by ytimenkov** [comment]
I think it highly depends on what kind of change in the config file. When I thought about configurable logging, it felt nice to be able to tune log level on the fly, for example to troubleshoot some issue happening right now.
Unfortunately logging settings applied only at start and don't change.
On the other hand if change includes new directories to scan or (what I did recently) change to layout script I do want to do a rescan.
In fact I miss opportunity to update collection after I tune the script.

Apart from this I feel that
1. Changes to config are relatively rare.
2. Scan (or rescan) should be adequate (fast and not affecting overall performance much) in any case.
