### ISSUE TITLE
Pc directory

### ISSUE THREAD

**Issue by Neocazen** [gerbera/gerbera#905]
Does the option hide Pc directories no longer work?

**Comment by ytimenkov** [comment]
Yep, was cut in 5956e9633589eeb0c5371c18998169903aaef618
Should be few lines fewer 🤣

**Comment by Neocazen** [comment]
Bad change, but I hope that one day it will be like Universal Media Server or Minidlna with the target folders on the first screen

**Comment by Neocazen** [comment]
Thank you for all
