### ISSUE TITLE
Build problems on Opensuse Raspberry-Pi

### ISSUE THREAD

**Issue by Richard-MQ** [gerbera/gerbera#919]
I'm trying to build 1.50 or latest GIT source (makes no difference) on Opensuse Leap 15.1 running on RaspberryPi-3. All listed dependencies are installed, but the cmake preparation fails with 

```
build $> cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=1
... 
CMake Error at cmake/FindFilesystem.cmake:227 (message):
  Cannot Compile simple program using std::filesystem
```

The error log file shows
```Run Build Command:"/usr/bin/gmake" "cmTC_bd728/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_bd728.dir/build.make CMakeFiles/cmTC_bd728.dir/build
gmake[1]: Entering directory '/home/rpm/Progs/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_bd728.dir/CheckIncludeFile.cxx.o
/usr/bin/c++    -Wall    -std=c++1z -o CMakeFiles/cmTC_bd728.dir/CheckIncludeFile.cxx.o -c /home/rpm/Progs/build/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx
/home/rpm/Progs/build/CMakeFiles/CMakeTmp/CheckIncludeFile.cxx:1:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~
compilation terminated.
```

I have tried a range of things, including adding flags
```
-DBOOST_INCLUDE_DIR="/usr/include/boost"  (boost is installed)
-DWITH_BOOST_INCLUDE_DIR='/usr/include/boost'
-DCPU='cortex-a53' 
-DWITH_ARCH='arm'
```

Nothing seems to help. I can't work out why it doesn't find the header file which is clearly present at /usr/include/boost/filesystem.hpp

Any pointers greatly appreciated as gerbera 1.5 does not appear to be available from any of the repositories for raspberry-pi.
Thanks
Richard

**Comment by whyman** [comment]
Hi Richard!

Can you post your full configure output?

**Comment by KarlStraussberger** [comment]
Hi Richard, 
I am compiling 15.1 on a x86 with the following settings.
```
cmake \
       -Wno-dev \
       -DWITH_MAGIC=1 -DWITH_MYSQL=1 -DWITH_CURL=1 -DWITH_JS=1 \
       -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_FFMPEGTHUMBNAILER=1 -DWITH_EXIF=1 -DWITH_EXIV2=1 -DWITH_INOTIFY=1 \
       -DWITH_LASTFM=0 -DWITH_MATROSKA=1\
       -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_CXX_STANDARD_LIBRARIES="-lstdc++fs"
```

Maybe some time in the future my SuSE pal and me set up an OBS repository or fix the existing build.

**Comment by whyman** [comment]
Our CMake should detect if you need `-lstdc++fs`.... [FindFilesystem.cmake](https://github.com/gerbera/gerbera/blob/a60b7dd2b175306c4d1878dab2f2a2c409a85287/cmake/FindFilesystem.cmake#L196)

Also if you have a newer GCC (>=9) that is better.

**Comment by KarlStraussberger** [comment]
Well, so I installed gcc-9 but got an error in cmake.

```
CMake Error at cmake/FindFilesystem.cmake:227 (message):
  Cannot Compile simple program using std::filesystem
Call Stack (most recent call first):
  CMakeLists.txt:275 (find_package)
```
Any clues whats missing?

**Comment by Richard-MQ** [comment]
Sorry for delay.

```
rpm@Raspi-3:~/Progs/gerbera> rm CMakeCache.txt; cmake ../gerbera -DBOOST_INCLUDE_DIR="/usr/include/boost" -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=1 -DCPU='cortex-a53' -DWITH_ARCH='arm' -DWITH_BOOST_INCLUDE_DIR='/usr/include/boost'
rm: cannot remove 'CMakeCache.txt': No such file or directory
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include optional
-- Looking for C++ include optional - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - found
-- Looking for C++ include filesystem
-- Looking for C++ include filesystem - not found
CMake Error at cmake/FindFilesystem.cmake:227 (message):
  Cannot Compile simple program using std::filesystem
Call Stack (most recent call first):
  CMakeLists.txt:275 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/rpm/Progs/gerbera/CMakeFiles/CMakeOutput.log".
See also "/home/rpm/Progs/gerbera/CMakeFiles/CMakeError.log".
rpm@Raspi-3:~/Progs/gerbera> 
```
Happy to attach CMakeOutput.log but CMakeError.log has not been created
Thanks
Richard

**Comment by Richard-MQ** [comment]
@Karl - I hadn't realised the x86 repos didn't have gerbera either - I've been using an old raspberry-pi 1B with gerbera that I built myself in 2017 as an upgrade from an older mediatomb system, but it is time to pension the raspi-1 off. Previous build was using configure I think rather than cmake.
Thanks, Richard

**Comment by Richard-MQ** [comment]
@Whyman - PS Will see if a later gcc is available this evening, and give it a try if so.

**Comment by whyman** [comment]
My guess is you will need `libstdc++6-devel-gcc9` as well

**Comment by Richard-MQ** [comment]
Yes gcc-9 (and g++-9) fixes the problem. Now it complains libupnp is too old, but that's an old problem.
Thanks, I'll mark this closed.
Richard

**Comment by Richard-MQ** [comment]
Hmm I was too hasty in closing - cmake completes (which is a big improvement) but complains of errors. Indeed in the error log I can see problems with the tests for

```
"Determining if the pthread_create exist" 
...  "undefined reference to `pthread_create`"
"Performing C++ SOURCE FILE Test ICONV_SECOND_ARGUMENT_IS_CONST"
... "error: invalid conversion from ‘const char**’ to ‘char**’"
`and` "Performing C++ SOURCE FILE Test FOUND_BSD_UUID"
... "fatal error: uuid.h: No such file or directory"
```

I find the first two really confusing, and the third seems strange given that libuuid1.devel is installed, and /usr/include/uuid/uuid.h exists. Possibly relevant that I also have uuid.devel installed, so /usr/include/ossp/uuid.h also exists

@KarlStraussberger - did you get any further with OSL 15.1 on x86?

Any pointers gratefully received - again! 
Thanks
Richard

**Comment by ytimenkov** [comment]
Try running cmake with `--debug-try-compile` or should give more clues somewhere under `CMakeFiles/`

Btw, I've noticed that you have redundant options like cnake_prefix (i think) and definitely libc+-fs not needed for gcc9.

**Comment by Richard-MQ** [comment]
Thanks, tried as you suggested 
`rm -rI *; cmake --debug-try-compile ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=1 -DCPU='cortex-a53' -DWITH_ARCH='arm'  -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9
`
but this makes no difference. I saw in the console output:
`
...
CMake Error at cmake/FindFilesystem.cmake:209 (target_compile_features):
  Cannot specify compile features for imported target "std::filesystem".
Call Stack (most recent call first):
  CMakeLists.txt:282 (find_package)
`
and realised it was there before. 
And the error log shows the same 3 errors that I had before.

Worth trying, anyway.
R.

**Comment by ytimenkov** [comment]
Your cmake is too old you need 3.10 (see https://github.com/gerbera/gerbera/pull/818#issuecomment-641461110).

**Comment by KarlStraussberger** [comment]
That is correct. In the very beginning of compiling gerbera I added the dev tools repository to zypper `/etc/zypp/repos.d/obs_dev_tools.repo`

```
[obs-dev-tools]
name=OBS DEV TOOLS openSUSE-Leap 15.1
enabled=1
autorefresh=1
baseurl=http://download.opensuse.org/repositories/devel:/tools:/building/openSUSE_Leap_15.1/
path=/
type=rpm-md
keeppackages=0
```
My first check resulted in the fact that it is not available for arm. You might want to compile from source or you the factory rep `http://download.opensuse.org/repositories/devel:/tools:/building/openSUSE_Factory_ARM/`

**Comment by Richard-MQ** [comment]
cmake reports version 3.10.2, this is teh latest in the repos.
Am now building 3.17.3 from Kitware...

**Comment by Richard-MQ** [comment]
Upgraded to 3.17 and indeed that fixes it. 
A word to anyone using this thread for support - uninstall cmake with your package manager (just) before doing "make install" or you will end up with a broken cmake reporting "can't find CMAKE_ROOT".

Also cmake reports "CPU" and "WITH_ARCH" were not used; final cmake invocation is:
`rm -rI *; cmake ../gerbera -DWITH_MAGIC=1 -DWITH_MYSQL=0 -DWITH_CURL=1 -DWITH_JS=1 -DWITH_TAGLIB=1 -DWITH_AVCODEC=1 -DWITH_EXIF=1 -DWITH_LASTFM=0 -DWITH_SYSTEMD=1 -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DCMAKE_CXX_STANDARD_LIBRARIES="-lstdc++fs"`

Will leave the thread open this time until I have actually built gerbera, but thanks both for the help so far!

**Comment by Richard-MQ** [comment]
Compilation failed with out-of-memory, and (probably getting off-topic for this forum) I realised that I only had 500M of swap for 1G of RAM. In re-sizing the partitions I have somehow bricked the SD card, and `fdisk -l` only reports 1 MiB capacity, `hdparm -I` replies with "SG_IO: bad/missing sense data".

So I will try a bit longer to repair this (it's a 64G card, if it had been a little one I'd just bin it) but will probably have to re-install from scratch which will take a while.

Until then...

**Comment by ytimenkov** [comment]
Sd card is not for volatile data like object files...

If you oom, check that compilation goes in one thread (-j1 option to make).

You can also cross-compile...

I was going to suggest my Conan pr, but unfortunately it's not suitable for cross-compilation right now since it installs some packages (actually most optional ones) like ffmpeg using system package manager and it's not suitable for cross-compilation.
But it's a definitely an interesting case.

**Comment by ytimenkov** [comment]
If you have free space you can add swap on loopback device. Google gives this: https://blog.nerdcruft.net/2017/02/06/linux-swap-over-loopback-devices/

**Comment by Richard-MQ** [comment]
Unfortunately Raspberry-Pis all run from SD card with no easy way of using anything else.
The problem was me being gung-ho in resizing a running system (yes I know...) instead of taking it off-line.

But your suggestion of using swap on loopback is a good idea, I had not thought of that - thanks.

When I re-install I will ensure at least 1G of swap which should help quite a lot with big compilations. Possibly `make -j 1` rather than `make -j 4` would also help?

**Comment by ytimenkov** [comment]
> Possibly make -j 1 rather than make -j 4 would also help albeit at the expense of speed?

That's definitely. Especially on higher optimization levels and when using LTO. In my cases gcc raised internal compiler error when OOMed. If your system is functional after this, just restart the build. You can also try `-j1` for heavy files and then continue with `-j4` after couple files.

**Comment by ytimenkov** [comment]
BTW, I've tried to cross-compile gerbera to aarch64 (rpi3) with Conan, however I don't have hardware to test.

See the last section in `docs/conan.rst`:
https://github.com/ytimenkov/gerbera/tree/feature/conan-fixes

I plan to submit a PR once iron out github actions (feels good, only 4 commands) and Docker image.

But feedback is welcome.
