### ISSUE TITLE
Why all my videos are marked that they have subtitles?

### ISSUE THREAD

**Issue by Hunsu** [gerbera/gerbera#920]
I'm using Gerbera with BubbleUPnP Server and the android app. I compiled Gerbera from sources. In the android app all my videos are showing that they have subtitles stored in the server but it is not right.
How can I debug and fix this issue?

**Comment by whyman** [comment]
Hi @Hunsu , thanks for reporting!

Can you provide us with a debug log? Ideally both importing the files, and then trying to play one

**Comment by Hunsu** [comment]
I started gerbera in debug mode and added a test file that does not have any subtitles.
Here are the logs [logs.LOG](https://github.com/gerbera/gerbera/files/4807591/logs.LOG)

**Comment by whyman** [comment]
Thanks!

It looks like we add a subtitle element to all video content currently...
```c++
        if (startswith(mimeType, "video")) {
            renderCaptionInfo(url, parent);
        }
```

**Comment by ytimenkov** [comment]
Do you feel it can be easily fixed properly? I found ".srt" in 5 different places, mostly related...

@whyman Do you know why some things (like poster) are processed during scan while some others (like subtitles and thumbnails) dynamically when serving content (in `UpnpXMLBuilder`)?

I have (or had) some thoughts, but would like to confirm.

**Comment by whyman** [comment]
Ideally we would do everything at scan, rather that serving time.

Obviously we cannot do some things at import time (virtual resources, transcoding, client specifics)

Art processing should be moved to import time, same with subs.

Both art and subs have "Internal"  and "Embedded" types and want serving in a similar fashion, so some mechanism to handle "associated" resources is needed that could be used for both cases.

**Comment by ytimenkov** [comment]
Right, IIRC major problem with populating data at scan time was that some resources may be added afterwards and thus will be just ignored.

**Comment by whyman** [comment]
Yes, but assuming you run timed scans often enough (or inotify) then your content should get reindexed and included.

It does mean that we have to be smart and when we see art or a poster get created, associate it correctly with the existing resource, and not treat it as a resource itself.

**Comment by ytimenkov** [comment]
Current code only looks for "satellite" resources during the main scan (i.e. get path and check for `folder.jpg`).

I don't have a good idea how to do the reverse mapping: how to find the "main" resource given random file changed, but not the "main" resource.

**Comment by KarlStraussberger** [comment]
Currently, CaptionInfo is added in a loop with each resource!

I see a way to add caption in the same fashion as fanart (`FanArtHandler` is rather small) and store it in resources (`#define VIDEO_SUB "vs"`). Then it is added in resource loop (with a bit of handling) only if existing.

For identification file name stem has to be the same as the video file. Extension ".srt".

Even if subtitle files are not stored in database (PC Directory), we need to add some hook to `AutoscanInotify` to update resources of media items if satellite is added or changed later.

**Comment by ytimenkov** [comment]
@KarlStraussberger are you working on this?
To fix subtitles and fanart is basically my primary interest in gerbera ☺️

**Comment by KarlStraussberger** [comment]
Did not start yet, some thoughts for next week.

**Comment by Eelisland** [comment]
i'm using 1.6.0_git compiled from source and my UPNP client show for every MKV files a second track with exactly same name and extension with a thumbnail SUB. Obviously there is no srt subtitles files in my folder. All my mkv files have subtitles in it.

**Comment by KarlStraussberger** [comment]
@ytimenkov Do you already have something to share? Can spend some time on this.

**Comment by ytimenkov** [comment]
Not really... Mostly did archeology.

I think the way to go is to refactor resources from plain list to categorized fields in cds_item, having a dedicated poster resource, a list of extra audio tracks, a list of subtitles, etc. And of course a main resource. This way the chain of metadata handlers can "communicate" to each other and do not overwrite fields (or do overwrite). For example poster can be embedded, if not then look for folder.jpg otherwise call back to thumbnailer.

However this is not strictly necessary for subtitles. For this particular issue only a check whether file exists or not prior to building xml response would be sufficient.

I also wondered about how to test all such things, but end-to-end testing requires a sample library.

**Comment by KarlStraussberger** [comment]
Ok, I suggest adding some resource for the subtitles like fanart without changing the data structure - fixing the the issue. Afterwards, we may refactor the whole thing according to your plan.

**Comment by ytimenkov** [comment]
If you add as resource which is stored in the db then you need to find out how to sync when srt and main file appear (and disappear) at different times (for inotify): srt may be added afterwards and somehow db need to be updated.

Therefore I suggest a simple stat right before agreeing adding it to the cds response.

I think this lack of rescan is a reason why srt is not stored in the db in the original code.

**Comment by KarlStraussberger** [comment]
I upgraded FanArtHandler with a bit of configuration to make search for cover in db obsolete (still used for album).

On that I based the new subtitle handler, so it uses the same mechanisms.

There is not yet an update of existing videos if subtitle is added later.

You may check and comment on https://github.com/KarlStraussberger/gerbera/tree/subtitle-handler

**Comment by Eelisland** [comment]
don't know if it's a dumb comment but, been able to compile and test this version, no more subtitles error in log when playing (VLC) MKV file (containing subs). Will test further later this day on other upnp player to see if i still see duplicate movie names tagged sub in tree.
thanks :)

**Comment by Eelisland** [comment]
No more duplicate names in tree for mkv without external srt.
Tested ok with a MKV file and a valid external srt with VLC and my ISP box player (i believe they use Gstreamer).
Srt file didn't appear in Gerbera web interface, only on ISP box tree.

**Comment by ytimenkov** [comment]
@KarlStraussberger Thanks for looping me in 👍 

I've looked at the changes and I wonder how do you plan to support the case if srt is added afterwards. This is really important to me personally since it's like 95% of cases and those changes will break it for me :/. (this will require a wipe of db for every added video with subtitles).

**Comment by ytimenkov** [comment]
I also have quite negative attitude to the idea that handler both **fills** and **serves**.  In my opinion they should only fill metadata but serving should be done by `FileRequestHandler`.

Serving is for special cases, like an embedded resource into a corresponding container.

**Comment by whyman** [comment]
@KarlStraussberger nice work! 

Maybe rather than clogging up this issue, you could open a Draft PR?

**Comment by KarlStraussberger** [comment]
That's the thing I'm working on at the moment. Likely to be done by tomorrow, including PR.

**Comment by KarlStraussberger** [comment]
In order for the PR to work, you need to add the correct configuration (section resources)
