### ISSUE TITLE
Bump CMake minimum version

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#921]
Your cmake is too old you need 3.10 (see https://github.com/gerbera/gerbera/pull/818#issuecomment-641461110).

_Originally posted by @ytimenkov in https://github.com/gerbera/gerbera/issues/919#issuecomment-646313885_

**Comment by ytimenkov** [comment]
I suggest 3.14. Has a lot of improvements to imported targets as well as IConv and SQLite3 find modules.

**Comment by whyman** [comment]
Sounds good. Should be an easy PR for someone...

**Comment by ytimenkov** [comment]
Pupnp and duktape were accepted into official conan repo. So I could groom cmakelists bit more unless someone does only this change before me.

**Comment by ytimenkov** [comment]
So... Conan branch is ready: builds both with and without Conan. I also fixed build issues for FreeBSD (went surprisingly smooth), where I've bumped into (and fixed) issues @neheb had with ffmpeg in #884.
However opening a PR at midnight is not a good idea 😊

**Comment by whyman** [comment]
closed in #923
