### ISSUE TITLE
How do I delete items from the database.

### ISSUE THREAD

**Issue by larand54** [gerbera/gerbera#924]
By misstake some files was copied to wrong library and I discovered that when I checked the database view. As there where no way to delete the files in that view I just deleted the files from the library and hoped the database would be notified and updated. But sadly not.
So, how can I remove them from the database?

**Comment by KarlStraussberger** [comment]
There is an issue in 1.5 that files are not removed from the database if you remove the whole directory. It's fixed in current master.

**Comment by KarlStraussberger** [comment]
Just remove the whole database file and have everything reindexed

**Comment by whyman** [comment]
You should be able to remove them from the DB view

![image](https://user-images.githubusercontent.com/345034/85232922-f4e3ff00-b3fa-11ea-875d-d0a511fb26fc.png)
