### ISSUE TITLE
Build times

### ISSUE THREAD

**Issue by ytimenkov** [gerbera/gerbera#931]
This is kind of FYI and findings.

Compiling gerbera takes more time than I like and I looked a little bit into where it goes.
On my machine each file takes ~10-12 seconds to compile more or less regardless of size.

Simply compiling with `-E` shows that simple inclusion of `<filesystem>` pulls most of STL: chrono, streams, you name it 🤮 
Just randomly scrolling to any place in 3Mb preprocessor output of main.cc shows we're still in some STL guts, quite surprising.

gcc `-ftime-report` also confirms that a lot of time is spent in parsing and template instantiation.

And there is no obvious entanglement of headers.

So my first idea was to try PCH.

Fortunately CMake 3.16 makes it extremely easy to add ones with couple lines.
Unfortunately results were not great (from 160s -> 130s), but now I realize that maybe it's still worth it: I used pch only for libgerbera while built tests also, this needs to be revisited.

However I was really surprised by unity build. Just adding 2 parameters to cmake command line (even without changing any cmake file) dropped build time 3x: from 136 secs down to 40. 🥳 
`-DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=20`

There are 2 issues with Unity:
1. CMake "glues" files so compiler compiles something else and therefore `compile_commands.json` won't work.
2. Tests redefine static functions and don't build (however with a few touches this is easy to overcome).

And I'm not sure about using it on CI: even if the pipeline will run 3 times faster it will compile slightly differently than on developer's machine.

**Comment by whyman** [comment]
_Personally_ build time is a non-problem for me.

My IDE supports partial rebuilds as needed, and I dont sit around waiting for the CI to run....
