### ISSUE TITLE
Deb-Multimedia stable version gerbera 1.3 WebUI non-functional

### ISSUE THREAD

**Issue by ThomasKorimort** [gerbera/gerbera#934]
After trying to use the Buster version of gerbera some time ago on my Raspberrry Pi 4 4 GB(raspbian) i tried yesterday to install the stable deb-multimedia version 1.3 of gerbera. Even after purging the old gerbera package it does not work. As one tries to use the WebUI it is not possible to add any files or to look into the database. Maybe somehow the scripts don't get started?

**Comment by whyman** [comment]
This is a packaging bug (which is fixed in 1.5.0-dmo3), see #872

You may need to contact @marillat for a fix.

**Comment by KarlStraussberger** [comment]
The package replaces some javascript files by links to separately installed ones which are older (esp. bpptstrap).
```
 bootstrap.bundle.js                                                        
 bootstrap.bundle.js.map                                                    
 bootstrap.bundle.min.js                                                    
 bootstrap.bundle.min.js.map                                                
 bootstrap.js -> ../../../../../javascript/bootstrap/js/bootstrap.js        
 bootstrap.js.map                                                           
 bootstrap.min.js -> ../../../../../javascript/bootstrap/js/bootstrap.min.js
 bootstrap.min.js.map                                                       
```
 
So if you want to run 1.3 just grab the files from the source repository and replace the js-tree (delete vendor directory before!).

**Comment by ThomasKorimort** [comment]
Will gerbera 1.5 be included in the stable section of deb-multimedia repository any time soon?

**Comment by marillat** [comment]
@whyman Thomas

In stable-backports as gerbera depends on packages not available in stable.

I'll post here when packages will be ready (or not).
Christian

**Comment by ThomasKorimort** [comment]
I have not yet seen a single open-source media server with systemd service working nicely. Neither gerbera nor MiniDLNA. It looks like the best to be expected to work is a commercial solution. Obviously, working DLNA/UPnP server implementations are not a free giveaway anymore (if they ever were). Industry seems to prepare for the big coming wave of self-hosters to buy commercial media servers...

**Comment by ytimenkov** [comment]
Gerbera runs well with systemd on my gentoo nas. If you have some issues with systemd would be nice to get a bug report with more concrete description.

**Comment by ThomasKorimort** [comment]
I have tried to use both miniDLNA and gerbera for my personal media library on my Raspberry Pi 4 4 GB. MiniDLNA crashes all the time and gerbera 1.3 complained on server start about inotify_max_users exceeded and even after adjusting that variable it did not work. So, Debian Buster does not include any working open-source media server solution even if you just request very basic DLNA/UPnP server functionality.

**Comment by marillat** [comment]
> Will gerbera 1.5 be included in the stable section of deb-multimedia repository any time soon?

Package 1.5.0-dmo0~bpo10+1 uploaded to stable-backports only amd64 arch.

Please report any problem.

**Comment by marillat** [comment]
> I have tried to use both miniDLNA and gerbera for my personal media library on my Raspberry Pi 4 4 GB. MiniDLNA crashes all the time and gerbera 1.3 complained on server start about inotify_max_users exceeded and even after adjusting that variable it did not work. So, Debian Buster does not include any working open-source media server solution even if you just request very basic DLNA/UPnP server functionality.

I use gerbera and mindlna from my repository since years without problem.
