### ISSUE TITLE
ERROR: ActionRequest::update(): response is nullptr, code -115

### ISSUE THREAD

**Issue by cot-al** [gerbera/gerbera#937]
HI, 
Running gerbera on las generation of raspberry PI. Worked well so far except transcoding ogg. 
But since last update, UPNP client can detect it, but all lists of media are empty, yet using the GUI we can see all medias (there is a long list) :( services status is as follow : 
`● gerbera.service - Gerbera Media Server
   Loaded: loaded (/lib/systemd/system/gerbera.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-07-04 11:51:16 CEST; 8min ago
     Docs: man:gerbera(1)
           https://gerbera.io/
 Main PID: 1451 (gerbera)
    Tasks: 11 (limit: 4915)
   Memory: 39.1M
   CGroup: /system.slice/gerbera.service
           └─1451 /usr/bin/gerbera -c /etc/gerbera/config.xml

juil. 04 11:51:17 raspberrypi gerbera[1451]:                              By using this feature you may be violating YouTube
juil. 04 11:51:17 raspberrypi gerbera[1451]:                              service terms and conditions!
juil. 04 11:51:17 raspberrypi gerbera[1451]: 2020-07-04 11:51:17    INFO: Configuration check succeeded.
juil. 04 11:51:17 raspberrypi gerbera[1451]: 2020-07-04 11:51:17    INFO: Initialized port: 49152
juil. 04 11:51:17 raspberrypi gerbera[1451]: 2020-07-04 11:51:17    INFO: Server bound to: 192.168.1.5
juil. 04 11:51:17 raspberrypi gerbera[1451]: 2020-07-04 11:51:17    INFO: The Web UI can be reached by following this link: http://192.168.1.5:49152/
juil. 04 11:51:17 raspberrypi gerbera[1451]: 2020-07-04 11:51:17   ERROR: ActionRequest::update(): response is nullptr, code -115
juil. 04 11:51:17 raspberrypi gerbera[1451]: 2020-07-04 11:51:17   ERROR: ActionRequest::update(): response is nullptr, code -115
`
Note interesting message about youtube that is not activeated in conf.xml :)

**Comment by cot-al** [comment]
And sometimes restarting the server it works...!??

**Comment by ytimenkov** [comment]
The most likely suspects are `ConnectionManagerService` or `MRRegistrarService` (their corresponding `processActionRequest` methods set this code, `UPNP_E_INVALID_ACTION`). But to troubleshoot logs at debug level are needed.

**Comment by whyman** [comment]
You are clearly running a very old version as Youtube stuff was removed year(s?) ago. Please try a newer build. 1.5.0 ideally.
