### ISSUE TITLE
[REQUEST] Have option in the config.xml to use Video title rather than file name?

### ISSUE THREAD

**Issue by the16bitgamer** [gerbera/gerbera#947]
Is it possible to read the video title when you scan it into the database, and use that as the presented name, like what's used in minidlna?

It would make sorting through my video collection a whole lot neater

**Comment by KarlStraussberger** [comment]
Can you give a little bit more details on your installation (architecture, version, build setup). What type of video file do you have?

Basically titles are read by ffmpeg and taglib integration depending on file type.

**Comment by the16bitgamer** [comment]
Sorry about that.

I am running Gerbera on my Raspberry Pi 3 B+, so ARM 32 Bit with 1GB of RAM, running a Clean install of Raspberry Pi OS Lite based on Debian Buster. No desktop environment (and no .config folder).

The version of gerbera I hope is the latest since I installed it like most other apps on my Pi `sudo apt install gerbera`

And for configuration I have no clue how to run any of the commands since gerbera wouldn't run due to no .config folder existing and though gerbera does run as a Daemon, and I was able to update the config file in /etc/gerbera/config.xml and build the database with the UI, since from what I've tested that's the only way it worked.

As an aside I'm also having an issue where my Directories are getting squashed down so that only the Folders with videos in it are visible after a second scan.

i.e. "Top Gear -> Season 15 -> E05 Somehting.mp4" get turned into "Season 15 -> E05 Something.mp4"

**Comment by KarlStraussberger** [comment]
Just run `gerbera --compile-info` and all the details of gerbera will show up. 

Also run `ldd gerbera` for the details on linked libraries.

Finally, run something like `mediainfo` on your video file in order to get the tags as they are in the file.

**Comment by the16bitgamer** [comment]
Unfortunately I cannot run any `gerbera` commands since I am using Raspberry Pi OS Lite, which doesn't have a .config folder. I just keep getting errors stating that ./config/gerbera/gerbera.conf is missing.

**Comment by KarlStraussberger** [comment]
So your issue isn't a gerbera issue, it is a setup issue on Raspberry Pi OS Lite, which I do not know (I prefer the full versions). 

I recommend reading [First Time Launch](http://docs.gerbera.io/en/latest/run.html#first-time-launch) and also some FAQ on accessing the shell on RaspPiOSLite (either via ssh or via console login).

**Comment by the16bitgamer** [comment]
Sorry for the delay replying. Fixed the "user error" and I have gerbera running in shell.

I am running: Gerbera UPnP Server version 1.1.0

apparently that's because of the stable nature of Debain which RaspPiOSLite is based on

No mention of ffmpeg during boot

**Comment by KarlStraussberger** [comment]
1.1, that's really old. You should consider upgrading with packets from https://www.deb-multimedia.org

**Comment by the16bitgamer** [comment]
Since I am using a Raspberry Pi by default I am limited to http://raspbian.raspberrypi.org/raspbian/

However I was able to add https://www.deb-multimedia.org by reading the very tiny font on the poorly colored background, and I was able to install Gerbera 1.3.2 in stable

> Gerbera UPnP Server version 1.3.2 - http://gerbera.io/
> 
> ===============================================================================
> Gerbera is free software, covered by the GNU General Public License version 2
> 
> Copyright 2016-2019 Gerbera Contributors.
> Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Sergey Bostandzhyan, Leonhard Wimmer.
> ===============================================================================
> Compile info
> -------------
> WITH_MAGIC=1
> WITH_MYSQL=1
> WITH_CURL=1
> WITH_INOTIFY=1
> WITH_JS=1
> WITH_TAGLIB=1
> WITH_AVCODEC=1
> WITH_FFMPEGTHUMBNAILER=1
> WITH_EXIF=1
> WITH_EXIV2=1
> WITH_PROTOCOL_EXTENSIONS=
> WITH_SYSTEMD=1
> WITH_LASTFM=0
> WITH_DEBUG=1
> WITH_TESTS=0

Unfortunately my videos on Gerbera are still reporting the file names rather than the video titles which all of my video have

**Comment by KarlStraussberger** [comment]
That's better. Can you give me also your mediainfo output in order to see the populated tags and the ldd output for the library versions used.

**Comment by the16bitgamer** [comment]
No clue if this is user error or not, but `ldd gerbera` returned as "ldd: ./gerbera: No such file or directory" so I ran `ldd /usr/bin/gerbera` and got a return

And here is the Media Tag for one of my Video Files, I've assigned a "Movie Name" to all video files.

> pi@yourflix:/ $ mediainfo /home/pi/Videos/Grand\ Tour/Season\ 01/E01\ The\ Holy\ Trinity.mp4
> General
> Complete name                            : /home/pi/Videos/Grand Tour/Season 01/E01 The Holy Trinity.mp4
> Format                                   : MPEG-4
> Format profile                           : Base Media / Version 2
> Codec ID                                 : mp42 (isom/iso2/avc1/mp41)
> File size                                : 1.38 GiB
> Duration                                 : 1 h 11 min
> Overall bit rate mode                    : Variable
> Overall bit rate                         : 2 789 kb/s
> Movie name                               : Grand Tour S01E01 The Holy Trinity
> Encoded date                             : UTC 2018-09-23 17:28:48
> Tagged date                              : UTC 2018-09-23 17:28:48
> Writing application                      : HandBrake 1.1.2 2018090500
> 
> Video
> ID                                       : 1
> Format                                   : AVC
> Format/Info                              : Advanced Video Codec
> Format profile                           : Main@L4
> Format settings                          : CABAC / 4 Ref Frames
> Format settings, CABAC                   : Yes
> Format settings, ReFrames                : 4 frames
> Codec ID                                 : avc1
> Codec ID/Info                            : Advanced Video Coding
> Duration                                 : 1 h 11 min
> Bit rate                                 : 2 622 kb/s
> Width                                    : 1 280 pixels
> Height                                   : 720 pixels
> Display aspect ratio                     : 16:9
> Frame rate mode                          : Constant
> Frame rate                               : 29.970 (30000/1001) FPS
> Color space                              : YUV
> Chroma subsampling                       : 4:2:0
> Bit depth                                : 8 bits
> Scan type                                : Progressive
> Bits/(Pixel*Frame)                       : 0.095
> Stream size                              : 1.30 GiB (94%)
> Writing library                          : x264 core 155 r2901 7d0ff22
> Encoding settings                        : cabac=1 / ref=2 / deblock=1:0:0 / analyse=0x1:0x111 / me=hex / subme=6 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=0 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=18 / lookahead_threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=300 / keyint_min=30 / scenecut=40 / intra_refresh=0 / rc_lookahead=30 / rc=crf / mbtree=1 / crf=22.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / vbv_maxrate=20000 / vbv_bufsize=25000 / crf_max=0.0 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00
> Encoded date                             : UTC 2018-09-23 17:28:48
> Tagged date                              : UTC 2018-09-23 17:28:48
> Color range                              : Limited
> Color primaries                          : BT.709
> Transfer characteristics                 : BT.709
> Matrix coefficients                      : BT.709
> Codec configuration box                  : avcC
> 
> Audio
> ID                                       : 2
> Format                                   : AAC LC
> Format/Info                              : Advanced Audio Codec Low Complexity
> Codec ID                                 : mp4a-40-2
> Duration                                 : 1 h 11 min
> Bit rate mode                            : Variable
> Bit rate                                 : 160 kb/s
> Channel(s)                               : 2 channels
> Channel layout                           : L R
> Sampling rate                            : 48.0 kHz
> Frame rate                               : 46.875 FPS (1024 SPF)
> Compression mode                         : Lossy
> Stream size                              : 81.5 MiB (6%)
> Title                                    : Stereo / Stereo
> Language                                 : English
> Default                                  : Yes
> Alternate group                          : 1
> Encoded date                             : UTC 2018-09-23 17:28:48
> Tagged date                              : UTC 2018-09-23 17:28:48

> 
> pi@yourflix:~/.config $ ldd /usr/bin/gerbera
>         linux-vdso.so.1 (0x7efd6000)
>         /usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0x76d9a000)
>         libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76d70000)
>         libuuid.so.1 => /lib/arm-linux-gnueabihf/libuuid.so.1 (0x76d59000)
>         libupnp.so.13 => /usr/lib/arm-linux-gnueabihf/libupnp.so.13 (0x76d27000)
>         libixml.so.10 => /usr/lib/arm-linux-gnueabihf/libixml.so.10 (0x76d10000)
>         libexpat.so.1 => /lib/arm-linux-gnueabihf/libexpat.so.1 (0x76ccf000)
>         libsqlite3.so.0 => /usr/lib/arm-linux-gnueabihf/libsqlite3.so.0 (0x76bc7000)
>         libduktape.so.203 => /usr/lib/arm-linux-gnueabihf/libduktape.so.203 (0x76b7a000)
>         libmariadb.so.3 => /usr/lib/arm-linux-gnueabihf/libmariadb.so.3 (0x76b2e000)
>         libcurl-gnutls.so.4 => /usr/lib/arm-linux-gnueabihf/libcurl-gnutls.so.4 (0x76aac000)
>         libtag.so.1 => /usr/lib/arm-linux-gnueabihf/libtag.so.1 (0x769e9000)
>         libmagic.so.1 => /usr/lib/arm-linux-gnueabihf/libmagic.so.1 (0x769b8000)
>         libavformat.so.58 => /usr/lib/arm-linux-gnueabihf/libavformat.so.58 (0x76813000)
>         libavutil.so.56 => /usr/lib/arm-linux-gnueabihf/libavutil.so.56 (0x767a1000)
>         libffmpegthumbnailer.so.4 => /usr/lib/arm-linux-gnueabihf/libffmpegthumbnailer.so.4 (0x76780000)
>         libexif.so.12 => /usr/lib/arm-linux-gnueabihf/libexif.so.12 (0x7673d000)
>         libexiv2.so.14 => /usr/lib/arm-linux-gnueabihf/libexiv2.so.14 (0x7650a000)
>         libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0x764df000)
>         libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76398000)
>         libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x7624a000)
>         /lib/ld-linux-armhf.so.3 (0x76eec000)
>         libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x7621d000)
>         libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76199000)
>         libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76186000)
>         libgnutls.so.30 => /usr/lib/arm-linux-gnueabihf/libgnutls.so.30 (0x75fe4000)
>         libnghttp2.so.14 => /usr/lib/arm-linux-gnueabihf/libnghttp2.so.14 (0x75fb5000)
>         libidn2.so.0 => /usr/lib/arm-linux-gnueabihf/libidn2.so.0 (0x75f89000)
>         librtmp.so.1 => /usr/lib/arm-linux-gnueabihf/librtmp.so.1 (0x75f65000)
>         libssh2.so.1 => /usr/lib/arm-linux-gnueabihf/libssh2.so.1 (0x75f2f000)
>         libpsl.so.5 => /usr/lib/arm-linux-gnueabihf/libpsl.so.5 (0x75f0f000)
>         libnettle.so.6 => /usr/lib/arm-linux-gnueabihf/libnettle.so.6 (0x75ecb000)
>         libgssapi_krb5.so.2 => /usr/lib/arm-linux-gnueabihf/libgssapi_krb5.so.2 (0x75e81000)
>         libkrb5.so.3 => /usr/lib/arm-linux-gnueabihf/libkrb5.so.3 (0x75dc4000)
>         libk5crypto.so.3 => /usr/lib/arm-linux-gnueabihf/libk5crypto.so.3 (0x75d84000)
>         libcom_err.so.2 => /lib/arm-linux-gnueabihf/libcom_err.so.2 (0x75d71000)
>         libldap_r-2.4.so.2 => /usr/lib/arm-linux-gnueabihf/libldap_r-2.4.so.2 (0x75d1c000)
>         liblber-2.4.so.2 => /usr/lib/arm-linux-gnueabihf/liblber-2.4.so.2 (0x75d00000)
>         libicuuc.so.63 => /usr/lib/arm-linux-gnueabihf/libicuuc.so.63 (0x75b7a000)
>         libavcodec.so.58 => /usr/lib/arm-linux-gnueabihf/libavcodec.so.58 (0x74ac7000)
>         libbz2.so.1.0 => /lib/arm-linux-gnueabihf/libbz2.so.1.0 (0x74aa7000)
>         libgme.so.0 => /usr/lib/arm-linux-gnueabihf/libgme.so.0 (0x74a59000)
>         libopenmpt.so.0 => /usr/lib/arm-linux-gnueabihf/libopenmpt.so.0 (0x7489a000)
>         libchromaprint.so.1 => /usr/lib/arm-linux-gnueabihf/libchromaprint.so.1 (0x74879000)
>         libbluray.so.2 => /usr/lib/arm-linux-gnueabihf/libbluray.so.2 (0x74834000)
>         libgcrypt.so.20 => /lib/arm-linux-gnueabihf/libgcrypt.so.20 (0x7475a000)
>         libssl.so.1.1 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.1 (0x746db000)
>         libcrypto.so.1.1 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1 (0x744c2000)
>         libvdpau.so.1 => /usr/lib/arm-linux-gnueabihf/libvdpau.so.1 (0x744ae000)
>         libX11.so.6 => /usr/lib/arm-linux-gnueabihf/libX11.so.6 (0x7438c000)
>         libOpenCL.so.1 => /usr/lib/arm-linux-gnueabihf/libOpenCL.so.1 (0x74374000)
>         libavfilter.so.7 => /usr/lib/arm-linux-gnueabihf/libavfilter.so.7 (0x74171000)
>         libjpeg.so.62 => /usr/lib/arm-linux-gnueabihf/libjpeg.so.62 (0x7412c000)
>         libpng16.so.16 => /usr/lib/arm-linux-gnueabihf/libpng16.so.16 (0x740ee000)
>         libp11-kit.so.0 => /usr/lib/arm-linux-gnueabihf/libp11-kit.so.0 (0x73fe9000)
>         libunistring.so.2 => /usr/lib/arm-linux-gnueabihf/libunistring.so.2 (0x73e6d000)
>         libtasn1.so.6 => /usr/lib/arm-linux-gnueabihf/libtasn1.so.6 (0x73e4d000)
>         libhogweed.so.4 => /usr/lib/arm-linux-gnueabihf/libhogweed.so.4 (0x73e0e000)
>         libgmp.so.10 => /usr/lib/arm-linux-gnueabihf/libgmp.so.10 (0x73d95000)
>         libkrb5support.so.0 => /usr/lib/arm-linux-gnueabihf/libkrb5support.so.0 (0x73d7b000)
>         libkeyutils.so.1 => /lib/arm-linux-gnueabihf/libkeyutils.so.1 (0x73d67000)
>         libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0x73d43000)
>         libsasl2.so.2 => /usr/lib/arm-linux-gnueabihf/libsasl2.so.2 (0x73d1a000)
>         libicudata.so.63 => /usr/lib/arm-linux-gnueabihf/libicudata.so.63 (0x7231c000)
>         libswresample.so.3 => /usr/lib/arm-linux-gnueabihf/libswresample.so.3 (0x722fa000)
>         libvpx.so.6 => /usr/lib/arm-linux-gnueabihf/vfp/neon/libvpx.so.6 (0x72188000)
>         libwebpmux.so.3 => /usr/lib/arm-linux-gnueabihf/libwebpmux.so.3 (0x72170000)
>         libwebp.so.6 => /usr/lib/arm-linux-gnueabihf/libwebp.so.6 (0x7210c000)
>         liblzma.so.5 => /lib/arm-linux-gnueabihf/liblzma.so.5 (0x720db000)
>         libopencore-amrwb.so.0 => /usr/lib/arm-linux-gnueabihf/libopencore-amrwb.so.0 (0x720ba000)
>         libzvbi.so.0 => /usr/lib/arm-linux-gnueabihf/libzvbi.so.0 (0x72037000)
>         libsnappy.so.1 => /usr/lib/arm-linux-gnueabihf/libsnappy.so.1 (0x72020000)
>         libaom.so.0 => /usr/lib/arm-linux-gnueabihf/libaom.so.0 (0x71d3e000)
>         libcodec2.so.0.8.1 => /usr/lib/arm-linux-gnueabihf/libcodec2.so.0.8.1 (0x71cd5000)
>         libfdk-aac.so.2 => /usr/lib/arm-linux-gnueabihf/libfdk-aac.so.2 (0x71bf7000)
>         libgsm.so.1 => /usr/lib/arm-linux-gnueabihf/libgsm.so.1 (0x71bdc000)
>         libilbc.so.2 => /usr/lib/arm-linux-gnueabihf/libilbc.so.2 (0x71bbc000)
>         libmp3lame.so.0 => /usr/lib/arm-linux-gnueabihf/libmp3lame.so.0 (0x71b4c000)
>         libopencore-amrnb.so.0 => /usr/lib/arm-linux-gnueabihf/libopencore-amrnb.so.0 (0x71b19000)
>         libopenjp2.so.7 => /usr/lib/arm-linux-gnueabihf/libopenjp2.so.7 (0x71abe000)
>         libopus.so.0 => /usr/lib/arm-linux-gnueabihf/libopus.so.0 (0x71a5f000)
>         libshine.so.3 => /usr/lib/arm-linux-gnueabihf/libshine.so.3 (0x71a45000)
>         libspeex.so.1 => /usr/lib/arm-linux-gnueabihf/libspeex.so.1 (0x71a1e000)
>         libtheoraenc.so.1 => /usr/lib/arm-linux-gnueabihf/libtheoraenc.so.1 (0x719db000)
>         libtheoradec.so.1 => /usr/lib/arm-linux-gnueabihf/libtheoradec.so.1 (0x719b3000)
>         libvo-amrwbenc.so.0 => /usr/lib/arm-linux-gnueabihf/libvo-amrwbenc.so.0 (0x71993000)
>         libvorbis.so.0 => /usr/lib/arm-linux-gnueabihf/libvorbis.so.0 (0x7195c000)
>         libvorbisenc.so.2 => /usr/lib/arm-linux-gnueabihf/libvorbisenc.so.2 (0x718ca000)
>         libx264.so.157 => /usr/lib/arm-linux-gnueabihf/libx264.so.157 (0x716b8000)
>         libx265.so.176 => /usr/lib/arm-linux-gnueabihf/libx265.so.176 (0x71492000)
>         libxvidcore.so.4 => /usr/lib/arm-linux-gnueabihf/libxvidcore.so.4 (0x713bf000)
>         libopenh264.so.5 => /usr/lib/arm-linux-gnueabihf/libopenh264.so.5 (0x71301000)
>         libkvazaar.so.4 => /usr/lib/arm-linux-gnueabihf/libkvazaar.so.4 (0x7129f000)
>         libmpg123.so.0 => /usr/lib/arm-linux-gnueabihf/libmpg123.so.0 (0x71240000)
>         libvorbisfile.so.3 => /usr/lib/arm-linux-gnueabihf/libvorbisfile.so.3 (0x71228000)
>         libxml2.so.2 => /usr/lib/arm-linux-gnueabihf/libxml2.so.2 (0x710ab000)
>         libfontconfig.so.1 => /usr/lib/arm-linux-gnueabihf/libfontconfig.so.1 (0x71063000)
>         libfreetype.so.6 => /usr/lib/arm-linux-gnueabihf/libfreetype.so.6 (0x70fc0000)
>         libgpg-error.so.0 => /lib/arm-linux-gnueabihf/libgpg-error.so.0 (0x70f96000)
>         libXext.so.6 => /usr/lib/arm-linux-gnueabihf/libXext.so.6 (0x70f77000)
>         libxcb.so.1 => /usr/lib/arm-linux-gnueabihf/libxcb.so.1 (0x70f48000)
>         libswscale.so.5 => /usr/lib/arm-linux-gnueabihf/libswscale.so.5 (0x70ee5000)
>         libpostproc.so.55 => /usr/lib/arm-linux-gnueabihf/libpostproc.so.55 (0x70ecc000)
>         libavresample.so.4 => /usr/lib/arm-linux-gnueabihf/libavresample.so.4 (0x70eac000)
>         libbs2b.so.0 => /usr/lib/arm-linux-gnueabihf/libbs2b.so.0 (0x70e97000)
>         librubberband.so.2 => /usr/lib/arm-linux-gnueabihf/librubberband.so.2 (0x70e62000)
>         libfribidi.so.0 => /usr/lib/arm-linux-gnueabihf/libfribidi.so.0 (0x70e38000)
>         libtesseract.so.4 => /usr/lib/arm-linux-gnueabihf/libtesseract.so.4 (0x709f6000)
>         libass.so.9 => /usr/lib/arm-linux-gnueabihf/libass.so.9 (0x709c9000)
>         libvidstab.so.1.1 => /usr/lib/libvidstab.so.1.1 (0x709ad000)
>         libzimg.so.2 => /usr/lib/arm-linux-gnueabihf/libzimg.so.2 (0x7097d000)
>         libffi.so.6 => /usr/lib/arm-linux-gnueabihf/libffi.so.6 (0x70965000)
>         libsoxr.so.0 => /usr/lib/arm-linux-gnueabihf/libsoxr.so.0 (0x70903000)
>         libogg.so.0 => /usr/lib/arm-linux-gnueabihf/libogg.so.0 (0x708ec000)
>         libcairo.so.2 => /usr/lib/arm-linux-gnueabihf/libcairo.so.2 (0x707f3000)
>         librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x707dc000)
>         libicui18n.so.63 => /usr/lib/arm-linux-gnueabihf/libicui18n.so.63 (0x7058e000)
>         libXau.so.6 => /usr/lib/arm-linux-gnueabihf/libXau.so.6 (0x7057b000)
>         libXdmcp.so.6 => /usr/lib/arm-linux-gnueabihf/libXdmcp.so.6 (0x70566000)
>         libsamplerate.so.0 => /usr/lib/arm-linux-gnueabihf/libsamplerate.so.0 (0x703eb000)
>         libfftw3.so.3 => /usr/lib/arm-linux-gnueabihf/libfftw3.so.3 (0x702ed000)
>         liblept.so.5 => /usr/lib/arm-linux-gnueabihf/liblept.so.5 (0x7009b000)
>         libgomp.so.1 => /usr/lib/arm-linux-gnueabihf/libgomp.so.1 (0x70063000)
>         libharfbuzz.so.0 => /usr/lib/arm-linux-gnueabihf/libharfbuzz.so.0 (0x6ff65000)
>         libpixman-1.so.0 => /usr/lib/arm-linux-gnueabihf/libpixman-1.so.0 (0x6fe8a000)
>         libxcb-shm.so.0 => /usr/lib/arm-linux-gnueabihf/libxcb-shm.so.0 (0x6fe77000)
>         libxcb-render.so.0 => /usr/lib/arm-linux-gnueabihf/libxcb-render.so.0 (0x6fe5c000)
>         libXrender.so.1 => /usr/lib/arm-linux-gnueabihf/libXrender.so.1 (0x6fe43000)
>         libbsd.so.0 => /usr/lib/arm-linux-gnueabihf/libbsd.so.0 (0x6fe1b000)
>         libgif.so.7 => /usr/lib/arm-linux-gnueabihf/libgif.so.7 (0x6fe03000)
>         libtiff.so.5 => /usr/lib/arm-linux-gnueabihf/libtiff.so.5 (0x6fd83000)
>         libglib-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0 (0x6fc71000)
>         libgraphite2.so.3 => /usr/lib/arm-linux-gnueabihf/libgraphite2.so.3 (0x6fc40000)
>         libzstd.so.1 => /usr/lib/arm-linux-gnueabihf/libzstd.so.1 (0x6fba7000)
>         libjbig.so.0 => /usr/lib/arm-linux-gnueabihf/libjbig.so.0 (0x6fb8a000)
>         libpcre.so.3 => /lib/arm-linux-gnueabihf/libpcre.so.3 (0x6fb13000)

**Comment by KarlStraussberger** [comment]
I'm a bit confused now, because I have MP4 files which are loaded correctly. There has been no real change in video metadata code, as far as I can see, and and I don't want to blame any of the libraries - which look fine to me.

So we need to investigate furthermore: DId you clean your database after updating and configuring to 1.3.2? At least try to remove and re-add the movie from the database.

**Comment by KarlStraussberger** [comment]
Seems to be a configuration issue `mediainfo` prints out `Movie name`. This is not `Title`. You need to map this property to `title` via `auxdata` in javascript import.
