### ISSUE TITLE
Fix build with pupnp 1.14.0

### ISSUE THREAD

**Issue by whyman** [gerbera/gerbera#949]
I must agree as gerbera 1.5.0 doesn't build with pupnp 1.14.0

_Originally posted by @marillat in https://github.com/gerbera/gerbera/issues/948#issuecomment-661747836_

**Comment by marillat** [comment]
Apparently gerbera is only affected by a header rename but I'm not familiar with gerbera and upnp.

````
--- a/src/util/upnp_headers.h
+++ b/src/util/upnp_headers.h
@@ -26,7 +26,7 @@
 #ifndef GERBERA_HEADERS_H
 #define GERBERA_HEADERS_H
 
-#include <ExtraHeaders.h>
+#include <UpnpExtraHeaders.h>
 #include <map>
 #include <memory>
 #include <upnp.h>
````
