### ISSUE TITLE
[REQUEST] Play Count

### ISSUE THREAD

**Issue by Trip69** [gerbera/gerbera#964]
It search and read the manual script and for the life of me can not find what I can only assume exists, the play count of a particular item, can someone point me the way, or if its no implemented, can I put in a request plz.

 Thanks for this awesome software I have been abler to produce exactly (almost) the menu system for all my films with it :)

**Comment by akvadrako** [comment]
This would be great. Even if it just logged every file accessed.

**Comment by KarlStraussberger** [comment]
It's available now. Maybe you can point me to a client that display `upnp:playbackCount`

**Comment by bwalocha** [comment]
Hi, how to use this field in search criteria?
The following does not work. How to include items without an existing "upnp:playbackCount "?

```
<container location="/NeverPlayed" title="Music Never Played" sort="upnp:album" upnp-shortcut="MUSIC_NEVER_PLAYED" max-count="100">
        <filter>upnp:class derivedfrom "object.item.audioItem" and upnp:playbackCount &lt;= "0"</filter>
</container>
```

This works but I need oposite result:

`<filter>upnp:class derivedfrom "object.item.audioItem" and upnp:playbackCount &gt; "0"</filter>`

**Comment by KarlStraussberger** [comment]
> Hi, how to use this field in search criteria? The following does not work. How to include items without an existing "upnp:playbackCount "?
> 
> ```
> <container location="/NeverPlayed" title="Music Never Played" sort="upnp:album" upnp-shortcut="MUSIC_NEVER_PLAYED" max-count="100">
>         <filter>upnp:class derivedfrom "object.item.audioItem" and upnp:playbackCount &lt;= "0"</filter>
> </container>
> ```
> 
> This works but I need oposite result:
> 
> `<filter>upnp:class derivedfrom "object.item.audioItem" and upnp:playbackCount &gt; "0"</filter>`

Which gerbera version are you using?

**Comment by bwalocha** [comment]
Thx @KarlStraussberger, the latest. I solved the issue. "upnp:playbackCount exists false" did the trick:

```
 <container location="/NeverPlayed" title="Music Never Played" sort="upnp:album" upnp-shortcut="MUSIC_NEVER_PLAYED" max-count="100">
        <filter>upnp:class derivedfrom "object.item.audioItem" and (upnp:playbackCount exists false or upnp:playbackCount = "0")</filter>
      </container>
```

**Comment by KarlStraussberger** [comment]
Anyways, found another issue because of your request and added your example to the documentation
