### ISSUE TITLE
v1.6.0 is not available for Docker

### ISSUE THREAD

**Issue by LinAGKar** [gerbera/gerbera#965]
The latest stable version on [Docker Hub](https://hub.docker.com/r/gerbera/gerbera/tags?page=1&name=v) is v1.5.0. There is no v1.6.0.

**Comment by whyman** [comment]
Thanks for reporting. Not sure what has happened there!

**Comment by whyman** [comment]
We will need to push a new tag to get a new build....

I guess we can cut a 1.7.0 or 1.6.1 release

**Comment by whyman** [comment]
`gerbera/gerbera:v1.6.1` is now available on docker hub!
