### ISSUE TITLE
Duplicated file extensions on Samsung TV

### ISSUE THREAD

**Issue by JoeNyland** [gerbera/gerbera#969]
My Samsung TV is showing duplicated file extensions for each video file that's presented to the TV from Gerbera. I have an LG TV that doesn't have this issue, so it's just affecting the Samsung one. I have a pretty default config file, but I've included the bits that I've changed from the default config below.

<img src="https://user-images.githubusercontent.com/7666402/91552506-d41cb600-e923-11ea-832a-666fc50087de.jpeg" height="500"/>

Here's the file listing on disk:

```
$ ls -lh
total 2.3G
-rw-rw-r-- 1 joe users 398M Dec 10  2019 S01E00.mp4
-rw-rw-r-- 1 joe users 275M Dec 10  2019 S01E01.mp4
-rw-rw-r-- 1 joe users 302M Dec 10  2019 S01E02.mp4
-rw-rw-r-- 1 joe users 281M Dec 10  2019 S01E03.mp4
-rw-rw-r-- 1 joe users 313M Dec 10  2019 S01E04.mp4
-rw-rw-r-- 1 joe users 355M Dec 10  2019 S01E05.mp4
-rw-rw-r-- 1 joe users 347M Dec 10  2019 S01E06.mp4
```

Differences in config from default:

```
    <name>Server</name>
    <home>/var/lib/gerbera</home>
    <pc-directory upnp-hide="yes" />
    <protocolInfo extend="yes" />
      <ffmpegthumbnailer enabled="yes">
        <thumbnail-size>160</thumbnail-size>
        <seek-percentage>10</seek-percentage>
        <image-quality>10</image-quality>
      </ffmpegthumbnailer>
      <virtual-layout type="js">
        <import-script>/usr/local/share/gerbera/js/import.js</import-script> <!-- default script supplied with Gerbera (I've not edited this)
      </virtual-layout>
```

* Affected TV: Samsung UE32J5500AK
* Gerbera version: 1.7.0_git (Docker)

**Comment by neheb** [comment]
I see this as well.

**Comment by whyman** [comment]
@neheb on a samsung client?

**Comment by neheb** [comment]
Yeah my TV

**Comment by JoeNyland** [comment]
@whyman Is there somewhere in the code that you could direct me to as being potential places where this bug could be? At the moment I'm a bit lost, but with some pointers on where to look, I could have a go at trying to sort this.

**Comment by KarlStraussberger** [comment]
It's not as straighforward as one expects 😃 This is the line where the title is rendered:

[renderObject](https://github.com/gerbera/gerbera/blob/2fa8c7362bbcbf435aa2d01210ebff9d0ac54010/src/upnp_xml.cc#L71)

Obviously we have to strip the extension for some clients which normally is handled in `client_quirks.cc`. I am not aware of side effects on other clients if we do so.

**Comment by KarlStraussberger** [comment]
What if we removed the extension from all file names if there is not metadata for title? Might be done on import.

**Comment by Brunobasta** [comment]
Hello all, I just checked out MediaTomb vs. Gerbera regarding the "Duplicated file extensions on Samsung TV" problem.
It is in both same problem! Yes I have a Samsung Q60.

**Comment by Brunobasta** [comment]
I just tested the MediaServer from Fritz.Box (AVM.de) and I get the same results with duplicated file extensions on Samsung TV...
So the problem is on Samsung side! Same results than MediaTomb and Gerbera on TV!
http://0x0.st/-KR5.png
http://0x0.st/-KRG.png
