### ISSUE TITLE
HEIC to JPG transode doesn't work

### ISSUE THREAD

**Issue by whitesnake-pl** [gerbera/gerbera#971]
Dear colleagues,

I'm trying to enable transcoding of HEIC files to JPG. Below is the configuration I have.

```
...
       <transcode mimetype="image/heic" using="heicjpg" />
...
      <profile name="heicjpg" enabled="yes" type="external">
        <mimetype>image/jpg</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <agent command="heif-convert" arguments="%in %out" />
        <buffer size="1048576" chunk-size="131072" fill-size="262144" />
      </profile>
```

However, it doesn't work. In logs I see the following.

Sep 01 22:47:51 myserver gerbera[264227]: Unknown file type in /tmp/grb_transcode_8SP8P0

Any ideas?

**Comment by whyman** [comment]
It looks like that that utility does not support reading from named pipes?

**Comment by whitesnake-pl** [comment]
Yes, it could be a case. I have changed from heif-convert to convert tool (imagemagix) and it works find.

      <profile name="heicjpg" enabled="yes" type="external">
        <mimetype>image/jpg</mimetype>
        <accept-url>no</accept-url>
        <first-resource>yes</first-resource>
        <agent command="convert" arguments="%in jpg:%out" />
        <buffer size="1048576" chunk-size="131072" fill-size="262144" />
      </profile>

You may close this issue.

**Comment by whyman** [comment]
:+1:
