### ISSUE TITLE
Add bits_per_sample (sample width)  to obj.res

### ISSUE THREAD

**Issue by ghlupe2** [gerbera/gerbera#978]
Is there a way to make this resource information available for scripting? I would like to organise my audio files by format, like 
**FLAC | 24 bit | 96 KHz | stereo**. Taglib presents this as bitsPerSample if I'm not mistaken.

**Comment by KarlStraussberger** [comment]
Did you already try to read it with "id3/auxdata" in `<library-options>` [Config](https://docs.gerbera.io/en/latest/config-import.html#id2)
