### ISSUE TITLE
Video MimeType Impossible ?

### ISSUE THREAD

**Issue by enigma131** [gerbera/gerbera#980]
HI,
I want to add Tvheadend channels on Gerbera Upnp server

I'm on Ubuntu and have installed via PPA so I think I have latest one : https://doc.ubuntu-fr.org/gerbera
I have created a .m3u file like this: 

#EXTM3U
#EXTINF:-1,60 : Channel Name
http://localhost:9981/stream/channel/   Channel id  ?ticket=   channel's ticket  (copied from Tvheadend's web interface)
etc

Then i have add this file via web interface of Gerbera. It creates entries of each channel, fine, it's working with VLC as client.
But I have problems with some other clients (TV, set top box etc).
The problem comes from wrong Mime type, it detects audio/mpeg and as class object.item.audioItem.musicTrack , so only sound is streamed.
I want to edit this , not possible because it's greyed, so I switch to old interface and modify the fields like here : 
https://tvheadend.org/boards/5/topics/12850
After modifying both fields, I click on update fields then I get error : Error: sqlForDelete called with invalid arguments

Can you correct this ?

**Comment by enigma131** [comment]
I have to make it work.
In filed class , i write with old interface: object.item.videoItem
in field mimeType; i write video/mpeg
then i click on button update fields, I get the message  Error: sqlForDelete
I restart the service ... and miracle the settings are stored .. and it works.
So it seems only a check from database to correct

**Comment by enigma131** [comment]
Other solution is to edit database with sqlitebrowser, but you have to know what you do...

**Comment by whyman** [comment]
We have no way of telling what the mimetype from a playlist item. You could edit the `playlist.js` to do what you want, perhaps?

**Comment by enigma131** [comment]
Thanks for answer.

I have done a try, have modified like this in playlist.js: 
//      exturl.mimetype = 'audio/mpeg';
	exturl.mimetype = 'video/mpeg';
        exturl.objectType = OBJECT_TYPE_ITEM_EXTERNAL_URL;
        exturl.location = location;
        exturl.title = (title ? title : location);
        exturl.protocol = 'http-get';
      exturl.upnpclass = UPNP_CLASS_ITEM_MUSIC_TRACK;
//	exturl.upnpclass = UPNP_CLASS_ITEM_VIDEO;
//      exturl.description = "Song from " + playlist.title;
	exturl.description = "Channel from " + playlist.title;

And gives result after importing .m3u : 
![class](https://user-images.githubusercontent.com/31815445/93233116-fc594100-f77a-11ea-89ac-1bca0c7c116a.png)

As you can see class is not correct for video, when i modify UPNP_CLASS_ITEM_MUSIC_TRACK by UPNP_CLASS_ITEM_VIDEO (the right matching class) I have no more playlist after open (import) the .m3u file.

Perhaps a other modification and / or in a other .js or conf file ?

Shame the field is not editable ....

**Comment by KarlStraussberger** [comment]
closed by #2361
