### ISSUE TITLE
1.4.0, 1.7.0-git: Alpine: Web UI responds with HTTP 500, yet shows no appropriate logging

### ISSUE THREAD

**Issue by ngc4579** [gerbera/gerbera#981]
Accessing Gerbera's web UI results in an _HTTP 500 Internal Server Error_ with no further traces of related logging whatsoever, even though Gerbera was started with the **-D** flag. Web UI is enabled in config. - Gerbera 1.4.0 from Alpine Package Directory, installed in a small Docker image (this is currently the latest version available in the Alpine repositories).

Is there any other place or hint for investigating this issue? UI files (/usr/share/gerbera/web) are present and accessible; Gerbera is started as root inside the container, Flags **-c** and **-f** point to existing directories.

```
...
318883-03-11 09:21:04   DEBUG: [src/timer.cc:41] init(): Starting Timer thread...
318883-03-11 09:24:32   DEBUG: [src/config_manager.cc:1472] writeBookmark(): Writing bookmark file to: /data/gerbera.html
698791571-01-17 04:21:12    INFO: The Web UI can be reached by following this link: http://192.168.xxx.xxx:49152/
318883-03-11 09:26:08   DEBUG: [src/server.cc:241] run(): end
318876-12-15 20:31:52   DEBUG: [src/timer.cc:54] staticThreadProc(): Started Timer thread.
318876-12-15 20:29:44   DEBUG: [src/timer.cc:102] triggerWait(): triggerWait. - 0 subscriber(s)
318876-12-15 20:29:44   DEBUG: [src/timer.cc:105] triggerWait(): Nothing to do, sleeping...
```

**Comment by whyman** [comment]
I can only find one area where we throw a 500 and that is if we hit a `StorageException` - is there any messages realting to sqlite or mysql?

There could be some case where something internal to libupnp is blowing up also.

**Comment by ngc4579** [comment]
All messages dealing with storage are _DEBUG_ level, I can see no indication of an issue there. See attached log file.

[gerbera.log](https://github.com/gerbera/gerbera/files/5220184/gerbera.log)

**Comment by ngc4579** [comment]
In the meantime, I've managed to build a Docker image based on sources from Git. Gerbera running inside a container created from that image shows the exact same behaviour - its web interface responds with an HTTP 500 error.

Attatching debug log and Dockerfile.
[Dockerfile.txt](https://github.com/gerbera/gerbera/files/5249775/Dockerfile.txt)
[gerbera-1.7.0-git.log](https://github.com/gerbera/gerbera/files/5249776/gerbera-1.7.0-git.log)

**Comment by whyman** [comment]
Odd, our docker images are alpine based, but we build our own libupnp (as the packages didnt exist yet) where as you are using the alpine provided packages.

So, I am thinking this is likely a libupnp bug. Perhaps try enabling libupnp's debug logging?

**Comment by ngc4579** [comment]
I've actually no idea how to enable debug logging on libupnp... - hints appreciated. ;)

**Comment by whyman** [comment]
I think you need to compile it with debug enabled.

**Comment by ngc4579** [comment]
Well... yep, I was suspecting that. Ok, so now I'm rather trying to build a working image for armhf architecture based on the Dockerfile in the repo, yet with a builder pattern in order to have a smaller memory footprint on the resulting image. I'll keep you posted. :)

**Comment by ngc4579** [comment]
... Finally, it works. Image size about 21MiB. I guess we might close this issue then?

**Comment by whyman** [comment]
Oh, well that's annoying
