### ISSUE TITLE
Files missing on gerbera restart since gerbera-1.6.1

### ISSUE THREAD

**Issue by phi-whiterabbit** [gerbera/gerbera#985]
Since i switched to gerbera-1.6.1, the layout is broken. It does not matter whether i am using builtin or js: The first import, creating a fresh new database, works just fine. However, if i restart gerbera, then a lot of the files that i had imported are missing in gerbera.
This is definitely a regression that came with 1.6.1. In version 1.6.0 this problem did not occur.

Please tell me how i can help in debugging this issue. I can also try patches since i am anyway compiling gerbera myself.

**Comment by KarlStraussberger** [comment]
I already made similar observations and I suspect that my fix in [autoscan](https://github.com/gerbera/gerbera/pull/959/commits/942ca7b6255163ed46d2569e676524585f85aef6) that subdirs are monitored on startup again (that broke on the way to 1.5) somehow leads to this behaviour. If you what to look into the issue it's in [ContentManager](https://github.com/gerbera/gerbera/blob/master/src/content_manager.cc) _rescanDirectory. I recommend comparing the current logic with 1.3.5 logic.

**Comment by phi-whiterabbit** [comment]
> I already made similar observations and I suspect that my fix in [autoscan](https://github.com/gerbera/gerbera/pull/959/commits/942ca7b6255163ed46d2569e676524585f85aef6) that subdirs are monitored on startup again (that broke on the way to 1.5) somehow leads to this behaviour. If you what to look into the issue it's in [ContentManager](https://github.com/gerbera/gerbera/blob/master/src/content_manager.cc) _rescanDirectory. I recommend comparing the current logic with 1.3.5 logic.

Given that this only happens to some of the files, this appears to be a race condition, no?

**Comment by KarlStraussberger** [comment]
This idea sounds reasonable. I just observed it, while developing another feature. To me, it look like the newest files are removed (I could not really make out another cause).

**Comment by whyman** [comment]
Do we have concrete steps to replicate this?

**Comment by phi-whiterabbit** [comment]
> Do we have concrete steps to replicate this?

Well, for me the issue happens after the following steps:
1. Have a few audio files available in a directory that is observed via autoscan. I do not know how many and whether there has to be a certain level of sub directories in order to trigger the BUG.
2. Start gerbera with no database existing yet.
3. Wait until gerbera is finished with importing the audio files.
4. Stop gerbera
5. Start gerbera again and wait until its finished scanning the directories again.
6. Look at its web ui or browse the audio files via dlna. The some of the files that have been imported in step 3 are gone.

Eben i have some spare time i will try to determine whether i can make a more specific statement regarding step 1, i.e. how many files, sub directories.

**Comment by phi-whiterabbit** [comment]
It is also interesting that at least for me always the same set of files is missing. Thus, the issue is somewhat deterministic, which does not indicate a race condition.

I will also try to reproduce without using the js layout so that we can exclude that as a cause of the issue.

**Comment by whyman** [comment]
So I had a poke around looking at this last night.

Luckily I could replicate by restarting twice, the first time the would get removed, next it would get added again.

For my test case the file getting remove was the first one retuned by the OS's `dir` call.

Anyway, the first file triggers the check to see if the modification time has changed:
https://github.com/gerbera/gerbera/blob/5cb2ecfd4a3c293597a0db7c9689919f7b37e4c8/src/content_manager.cc#L715-L724

Which then does a remove and add

The problem is that `removeObject()` is by default async. So, sometimes it does an add then remove and boom, the file goes.

A fix could be to set async=false:`removeObject(objectId, false, false)`

I didnt have time sort a PR, but should be a simple change to test

**Comment by phi-whiterabbit** [comment]
OK, i'll test it soon. Will report my findings here.

**Comment by phi-whiterabbit** [comment]
> OK, i'll test it soon. Will report my findings here.

Hi Ian, nice catch. I can confirm that changing removeObject to be called synchronously does indeed fix the issue. No missing files anymore. Thanks.

**Comment by KarlStraussberger** [comment]
I wonder whether last_modified_time for the autoscan directory is not updated when files are first discovered.

So fixing the symptom should be the first step before addressing the root cause.

**Comment by phi-whiterabbit** [comment]
> I wonder why last_modified_time for the autoscan directory is not updated when files are first discovered.
> 
> So fixing the symptom should be the first step before addressing the root cause.

Hm... Yes, and the change fixes the symptom...
I guess you wanted to say it the other way around? ;)

Be that as it may. What Ian describes is a BUG that occurs if last_modified_time is updated. I think it should be fixed. Whether this BUG is caused by some other BUG or last_modified_time is updated for a valid reason does not really matter i think: In both cases the BUG is triggered.
