### ISSUE TITLE
Unable to edit item metadata

### ISSUE THREAD

**Issue by reffu42** [gerbera/gerbera#986]
Version: 1.6.1
OS: ArchLinuxArm 

I just set up Gerbera with the default config file, primarily with the intent to set up video streaming to a smart tv in another room. Install worked fine and I was able to start it without issue. Likewise, I had no problems getting it to start scanning my media folders (set up with AutoScan - Inotify).

When I went to edit the title on some of the added videos (Pencil Icon -> Save Item), I got a bar along the bottom saying "Failed To Save Item". In the logs, I see a line saying `warning: Web Error: 800 Error: Item validation failed: missing mimetype`. This seems to occur no matter what file type or extension the item has. It also occurs whether running in the terminal or as a service.

Is there some config option I've forgotten or failed to set up, or do I need to install some additional libraries/programs?

**Comment by whyman** [comment]
Hi @reffu42, thanks for taking the time to report this.
