### ISSUE TITLE
add permissions per client device

### ISSUE THREAD

**Issue by c3o8k1e18u** [gerbera/gerbera#99]
I would highly appreciate a feature to restrict access to a selected subset of the media. By default all media should be accessible by all clients as is currently. Additionally access to selected media (e.g. based on the source folders in the filesystem) should be restrictable to selected clients (e.g. identified by their IP or probably even better by their MAC address).

**Comment by v00d00** [comment]
Yes, this would be useful, especially for families. Time based access restrictions would also be good.

**Comment by matt-matt2** [comment]
Or a PIN system. One DLNA server project I saw used a set of fake folders 1-8 and required the user to "tap" a pin code in by accessing them in the chosen order to unlock a bunch of other content. Thus remaining compatible with almost all client devices. I think the rest of its functionality was extremely limited however..

**Comment by whyman** [comment]
@pamapa I suppose as we are tracking clients for quirks now we could think about how this could be implemented? I suppose we would need to resolve the client IPs to their MAC addresses?

**Comment by pamapa** [comment]
i am not so sure, my use case would be the same TV, but depended on time. e.g. during day no videos only music, after 17:00 kids videos, after 19:00 all videos.

**Comment by c3o8k1e18u** [comment]
I think the basic functionality to implement would be a limitation/filter based on the client (MAC address).

Further on this filter could be extended with a shedule that can be enabled in addition (to fit pamapa´s requirenments). And as a second feature that can be enabled if required the filter could be extended with any kind of PIN code like suggested by matt-matt2.

I would suggest that this additional features (shedule + PIN code) can be configured/enabled optionally. For example in my use case a PIN code would be just an annoying limitation.

**Comment by cweiske** [comment]
I'd only support IP addresses and not MAC addresses, because Gerbera only sees the IP address. Resolving the MAC from an IP is tricky, especially with non-trivial network setups.

The user can define hard MAC-to-IP mappings in the DHCP server.

**Comment by KarlStraussberger** [comment]
We already have further stuff like friendlyName or the userAgent of the device which would provide further filtering.

**Comment by cweiske** [comment]
great!
