### ISSUE TITLE
Adding files does not update last_modified_time in autoscan

### ISSUE THREAD

**Issue by KarlStraussberger** [gerbera/gerbera#992]
Created to follow up root cause of #985

**Comment by whyman** [comment]
My guess would be some path that `returns` before the end of the method where the timestamp is updated

**Comment by KarlStraussberger** [comment]
I'll look into this after finishing the config ui. But feel free to look yourself :-)

**Comment by KarlStraussberger** [comment]
The reason is quite simple. `ContentManager::shutdown()` does not consider recursive scanning.

```
dir->resetLMT();
if (fs::is_directory(dir->getLocation())) {
  auto t = getLastWriteTime(dir->getLocation());
   dir->setCurrentLMT(t);
  }
dir->updateLMT();
```
